package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesG {
    
    G00("Bakterijski meningitis, nesvrstan drugamo", "G00"),
    G00_0("Haemophilus meningitis", "G00.0"),
    G00_1("Pneumokokni meningitis", "G00.1"),
    G00_2("Streptokokni meningitis", "G00.2"),
    G00_3("Stafilokokni meningitis", "G00.3"),
    G00_8("Ostali bakterijski meningitisi", "G00.8"),
    G00_9("Bakterijski meningitis, nespecificiran", "G00.9"),
    G01("Meningitis kod bakterijskih bolesti svrstanih drugamo", "G01"),
    G01_0("Meningitis kod bakterijskih bolesti svrstanih drugamo", "G01.0"),
    G02("Meningitis kod zaraznih i parazitarnih bolesti svrstanih drugamo", "G02"),
    G02_0("Meningitis kod virusnih bolesti svrstanih drugamo", "G02.0"),
    G02_1("Meningitis kod mikoza", "G02.1"),
    G02_8("Meningitis kod drugih specificiranih zaraznih i parazitarnih bolesti svrstanih drugamo", "G02.8"),
    G03("Meningitis prouzročen ostalim i nespecificiranim uzrocima", "G03"),
    G03_0("Nepiogeni meningitis", "G03.0"),
    G03_1("Kronični meningitis", "G03.1"),
    G03_2("Benigni rekurentni meningitis (Mollaret)", "G03.2"),
    G03_8("Meningitis uzrokovan ostalim specificiranim uzrocima", "G03.8"),
    G03_9("Meningitis, nespecificiran", "G03.9"),
    G04("Encefalitis, mijelitis i encefalomijelitis", "G04"),
    G04_0("Akutni diseminirani encefalitis", "G04.0"),
    G04_1("Tropska spastična paraplegija", "G04.1"),
    G04_2("Bakterijski meningoencefalitis i meningomijelitis, nesvrstan drugamo", "G04.2"),
    G04_8("Ostali encefalitisi, mijelitisi i encefalomijelitisi", "G04.8"),
    G04_9("Encefalitis, mijelitis i encefalomijelitis, nespecificiran", "G04.9"),
    G05("Encefalitis, mijelitis i encefalomijelitis kod bolesti svrstanih drugamo", "G05"),
    G05_0("Encefalitis, mijelitis i encefalomijelitis kod bakterijskih bolesti svrstanih drugamo", "G05.0"),
    G05_1("Encefalitis, mijelitis i encefalomijelitis kod virusnih bolesti svrstanih drugamo", "G05.1"),
    G05_2("Encefalitis, mijelitis i encefalomijelitis kod ostalih zaraznih i parazitarnih bolesti svrstanih drugamo", "G05.2"),
    G05_8("Encefalitis, mijelitis i encefalomijelitis kod bolesti svrstanih drugamo", "G05.8"),
    G06("Intrakranijalni i intraspinalni apscesi i granulomi", "G06"),
    G06_0("Intrakranijalni apsces i granulom", "G06.0"),
    G06_1("Intraspinalni apsces i granulom", "G06.1"),
    G06_2("Ekstraduralni i subduralni apsces, nespecificiran", "G06.2"),
    G07("Intrakranijalni i intraspinalni apsces i granulom kod bolesti svrstanih drugamo", "G07"),
    G07_0("Intrakranijalni i intraspinalni apses i granulom kod bolesti svrstanih drugamo", "G07.0"),
    G08("Intrakranijalni i intraspinalni flebitis i tromboflebitis", "G08"),
    G08_0("Intrakranijalni i intraspinalni flebitis i tromboflebitis", "G08.0"),
    G09("Posljedice upalnih bolesti središnjega živčanog sustava", "G09"),
    G09_0("Posljedice upalnih bolesti središnjega živčanog sustava", "G09.0"),
    G10("Huntingtonova bolest", "G10"),
    G10_0("Huntingtonova bolest", "G10.0"),
    G11("Nasljedna ataksija", "G11"),
    G11_0("Prirođena neprogresivna ataksija", "G11.0"),
    G11_1("Cerebelarna ataksija s ranim početkom", "G11.1"),
    G11_2("Cerebelarna ataksija s kasnim početkom", "G11.2"),
    G11_3("Cerebelarna ataksija s oštećenim obnavljanjem DNK", "G11.3"),
    G11_4("Nasljedna spastična paraplegija", "G11.4"),
    G11_8("Ostale nasljedne ataksije", "G11.8"),
    G11_9("Nasljedna ataksija, nespecificirana", "G11.9"),
    G12("Spinalna muskularna atrofija i sindromi u vezi s njom", "G12"),
    G12_0("Infantilna spinalna mišićna atrofija, tip I (Werdnig-Hoffman)", "G12.0"),
    G12_1("Ostale nasljedne spinalne mišićne atrofije", "G12.1"),
    G12_2("Bolest motoričkog neurona", "G12.2"),
    G12_8("Ostale spinalne mišićne atrofije i sindromi u vezi s njima", "G12.8"),
    G12_9("Spinalna mišićna atrofija, nespecificirana", "G12.9"),
    G13("Sistemne atrofije koje prije svega zahvaćaju središnji živčani sustav kod bolesti svrstanih drugamo", "G13"),
    G13_0("Paraneoplastična neuromiopatija i neuropatija", "G13.0"),
    G13_1("Ostale sistemne atrofije koje prije svega zahvaćaju središnji živčani sustav kod neoplastičnih bolesti", "G13.1"),
    G13_2("Sistemna atrofija koja primarno zahvaća središnji živčani sustav kod miksedema (E00.1, E03.-)", "G13.2"),
    G13_8("Sistemna atrofija koja prije svega zahvaća središnji živčani sustav kod ostalih bolesti svrstanih drugamo", "G13.8"),
    G20("Parkinsonova bolest", "G20"),
    G20_0("Parkinsonova bolest", "G20.0"),
    G21("Sekundarni parkinsonizam", "G21"),
    G21_0("Maligni neuroleptični sindrom", "G21.0"),
    G21_1("Ostali lijekom uzrokovani sekundarni parkinsonizam", "G21.1"),
    G21_2("Sekundarni parkinsonizam uzrokovan ostalim vanjskim uzrocima (agensima)", "G21.2"),
    G21_3("Postencefalitični parkinsonizam", "G21.3"),
    G21_8("Drugi sekundarni parkinsonizam", "G21.8"),
    G21_9("Sekundarni parkinsonizam, nespecificiran", "G21.9"),
    G22("Parkinsonizam kod bolesti svrstanih drugamo", "G22"),
    G22_0("Parkinsonizam kod bolesti svrstanih drugamo", "G22.0"),
    G23("Ostale degenerativne bolesti bazalnih ganglija", "G23"),
    G23_0("Hallervorden-Spatzova bolest", "G23.0"),
    G23_1("Progresivna supranuklearna oftalmoplegija (Steele-Richardson-Olszewski)", "G23.1"),
    G23_2("Strijatonigralna degeneracija", "G23.2"),
    G23_8("Ostale specificirane degenerativne bolesti bazalnih ganglija", "G23.8"),
    G23_9("Degenerativne bolesti bazalnih ganglija, nespecificirane", "G23.9"),
    G24("Distonija", "G24"),
    G24_0("Distonija uzrokovana lijekom", "G24.0"),
    G24_1("Idiopatska obiteljska distonija", "G24.1"),
    G24_2("Idiopatska neobiteljska distonija", "G24.2"),
    G24_3("Spazmodični tortikolis", "G24.3"),
    G24_4("Idiopatska orofacijalna distonija", "G24.4"),
    G24_5("Blefarospazam", "G24.5"),
    G24_8("Ostale distonije", "G24.8"),
    G24_9("Distonija, nespecificirana", "G24.9"),
    G25("Ostali ekstrapiramidalni poremećaji i poremećaji kretnji", "G25"),
    G25_0("Esencijalni tremor", "G25.0"),
    G25_1("Tremor uzrokovan lijekom", "G25.1"),
    G25_2("Ostali specificirani oblici tremora", "G25.2"),
    G25_3("Mioklonus", "G25.3"),
    G25_4("Koreja uzrokovana lijekom", "G25.4"),
    G25_5("Ostale koreje", "G25.5"),
    G25_6("Tikovi uzrokovani lijekom i ostali tikovi organskog podrijetla", "G25.6"),
    G25_8("Ostali specificirani ekstrapiramidalni poremećaji i poremećaji kretnji", "G25.8"),
    G25_9("Ekstrapiramidalni poremećaj i poremećaj kretnji, nespecificiran", "G25.9"),
    G26("Ekstrapiramidalni poremećaj i poremećaj kretnji kod bolesti svrstanih drugamo", "G26"),
    G26_0("Ekstrapiramidalni poremećaj i poremećaj kretnji kod bolesti svrstanih drugamo", "G26.0"),
    G30("Alzheimerova bolest", "G30"),
    G30_0("Alzheimerova bolest s ranim početkom", "G30.0"),
    G30_1("Alzheimerova bolest s kasnim početkom", "G30.1"),
    G30_8("Druga Alzheimerova bolest", "G30.8"),
    G30_9("Alzheimerova bolest, nespecificirana", "G30.9"),
    G31("Ostale degenerativne bolesti živčanog sustava, nesvrstane drugamo", "G31"),
    G31_0("Cirkumskriptna atrofija mozga", "G31.0"),
    G31_1("Senilna degeneracija mozga, nesvrstana drugamo", "G31.1"),
    G31_2("Degeneracija živčanog sustava uzrokovana alkoholom", "G31.2"),
    G31_8("Ostale specificirane degenerativne bolesti živčanog sustava", "G31.8"),
    G31_9("Degenerativna bolest živčanog sustava, nespecificirana", "G31.9"),
    G32("Ostale degenerativne bolesti živčanog sustava kod bolesti svrstanih drugamo", "G32."),
    G32_0("Subakutna kombinirana degeneracija kralježnične moždine kod bolesti svrstanih drugamo", "G32.0"),
    G32_8("Ostali specificirani degenerativni poremećaji živčanog sustava kod bolesti svrstanih drugamo", "G32.8"),
    G35("Multipla skleroza", "G35"),
    G35_0("Multipla skleroza", "G35.0"),
    G36("Druga akutna diseminirana demijelinizacija", "G36"),
    G36_0("Neuromyelitis optica (Devic)", "G36.0"),
    G36_1("Akutni i subakutni hemoragijski leukoencefalitis (Hurst)", "G36.1"),
    G36_8("Ostale specificirane akutne diseminirane demijelinizacije", "G36.8"),
    G36_9("Akutna diseminirana demijelinizacija, nespecificirana", "G36.9"),
    G37("Ostale demijelinizirajuće bolesti središnjeg živčanog sustava", "G37"),
    G37_0("Difuzna skleroza", "G37.0"),
    G37_1("Centralna demijelinizacija korpusa kalozuma", "G37.1"),
    G37_2("Centralna pontina mijelinoliza", "G37.2"),
    G37_3("Akutni transverzni mijelitis kod demijelinizirajuće bolesti središnjega živčanog sustava", "G37.3"),
    G37_4("Subakutni nekrotizirajući mijelitis", "G37.4"),
    G37_5("Koncentrični sklerozitis (Balo)", "G37.5"),
    G37_8("Ostale specificirane demijelinizirajuće bolesti središnjega živčanog sustava", "G37.8"),
    G37_9("Demijelinizirajuća bolest središnjega živčanog sustava, nespecificirana", "G37.9"),
    G40("Epilepsija", "G40"),
    G40_0("Vezana uz određeno sijelo (fokalna) (parcijalna) idiopatska epilepsija i epilepsijski sindromi s napadajima lokaliziranog početka", "G40.0"),
    G40_1("Vezana uz određeno sijelo (fokalna) (parcijalna) simptomatska epilepsija i epilepsijski sindromi s jednostavnim parcijalnim napadajima", "G40.1"),
    G40_2("Vezana uz određeno sijelo (fokalna)(parcijalna) simptomatska epilepsija i epilepsijski sindromi s kompleksnim parcijalnim napadajima", "G40.2"),
    G40_3("Generalizirana idiopatska epilepsija i epilepsijski sindromi", "G40.3"),
    G40_4("Druga generalizirana epilepsija i epilepsijski sindromi", "G40.4"),
    G40_5("Posebni epilepsijski sindromi", "G40.5"),
    G40_6("Grand mal napadaji, nespecificirani (s petit mal ili bez njega)", "G40.6"),
    G40_7("Petit mal, nespecificiran, bez grand mal napadaja", "G40.7"),
    G40_8("Ostale epilepsije", "G40.8"),
    G40_9("Epilepsija, nespecificirana", "G40.9"),
    G41("Status epilepticus", "G41"),
    G41_0("Grand mal status epilepticus", "G41.0"),
    G41_1("Petit mal status epilepticus", "G41.1"),
    G41_2("Kompleksni parcijalni epilepsijski status", "G41.2"),
    G41_8("Drugi epilepsijski status", "G41.8"),
    G41_9("Status epilepticus, nespecificiran", "G41.9"),
    G43("Migrena", "G43"),
    G43_0("Migrena bez aure (obična migrena)", "G43.0"),
    G43_1("Migrena s aurom (klasična migrena)", "G43.1"),
    G43_2("Status migraenosus", "G43.2"),
    G43_3("Komplicirana migrena", "G43.3"),
    G43_8("Ostale migrene", "G43.8"),
    G43_9("Migrena, nespecificirana", "G43.9"),
    G44("Ostale glavobolje", "G44"),
    G44_0("Klaster glavobolja", "G44.0"),
    G44_1("Vaskularna glavobolja, nesvrstana drugamo", "G44.1"),
    G44_2("Tenzijska glavobolja", "G44.2"),
    G44_3("Kronična posttraumatska glavobolja", "G44.3"),
    G44_4("Glavobolja uzrokovana lijekom, nesvrstana drugamo", "G44.4"),
    G44_8("Ostale specificirane glavobolje", "G44.8"),
    G45("Prolazni cerebralni ishemijski napadaji i sindromi u vezi s njima", "G45"),
    G45_0("Sindrom vertebro-bazilarne arterije", "G45.0"),
    G45_1("Sindrom karotidne arterije (hemisferični)", "G45.1"),
    G45_2("Multipli i bilateralni sindrom precerebralne arterije", "G45.2"),
    G45_3("Amaurosis fugax", "G45.3"),
    G45_4("Prolazna globalna amnezija", "G45.4"),
    G45_8("Ostali prolazni cerebralni ishemijski napadaji i sindromi u vezi s njima", "G45.8"),
    G45_9("Prolazni cerebralni ishemijski napadaj, nespecificiran", "G45.9"),
    G46("Vaskularni sindromi mozga kod cerebrovaskularnih bolesti", "G46"),
    G46_0("Sindrom središnje cerebralne arterije (I66.0)", "G46.0"),
    G46_1("Sindrom prednje cerebralne arterije (I66.1)", "G46.1"),
    G46_2("Sindrom stražnje cerebralne arterije (I66.2)", "G46.2"),
    G46_3("Sindrom apopleksije moždanoga stabla (I60-I67)", "G46.3"),
    G46_4("Sindrom cerebelarne apopleksije (I60-I67)", "G46.4"),
    G46_5("Motorni lakunarni sindrom (I60-I67)", "G46.5"),
    G46_6("Senzorni lakunarni sindrom (I60-I67)", "G46.6"),
    G46_7("Ostali lakunarni sindromi (I60-I67)", "G46.7"),
    G46_8("Ostali vaskularni sindromi mozga kod cerebrovaskularnih bolesti (I60-I67)", "G46.8"),
    G47("Poremećaji spavanja", "G47"),
    G47_0("Poremećaji zaspivanja i trajanja sna (insomnije)", "G47.0"),
    G47_1("Poremećaji izrazite somnolencije (hipersomnije)", "G47.1"),
    G47_2("Poremećaji ritma spavanja i budnosti", "G47.2"),
    G47_3("Apneja u snu", "G47.3"),
    G47_4("Narkolepsija i katalepsija", "G47.4"),
    G47_8("Ostali poremećaji spavanja", "G47.8"),
    G47_9("Poremećaj spavanja, nespecificiran", "G47.9"),
    G50("Poremećaji trigeminalnog živca", "G50"),
    G50_0("Neuralgija trigeminusa", "G50.0"),
    G50_1("Atipična facijalna bol", "G50.1"),
    G50_8("Ostali poremećaji trigeminalnog živca", "G50.8"),
    G50_9("Poremećaj trigeminalnog živca, nespecificiran", "G50.9"),
    G51("Poremećaji facijalnog živca", "G51"),
    G51_0("Bellova kljenut", "G51.0"),
    G51_1("Genikulatni ganglionitis", "G51.1"),
    G51_2("Melkerssonov sindrom", "G51.2"),
    G51_3("Klonični hemifacijalni spazam", "G51.3"),
    G51_4("Facijalna miokimija", "G51.4"),
    G51_8("Ostali poremećaji facijalnog živca", "G51.8"),
    G51_9("Poremećaj facijalnog živca, nespecificiran", "G51.9"),
    G52("Poremećaji ostalih kranijalnih živaca", "G52"),
    G52_0("Poremećaji olfaktornog živca", "G52.0"),
    G52_1("Poremećaji glosofaringealnog živca", "G52.1"),
    G52_2("Poremećaji vagusa", "G52.2"),
    G52_3("Poremećaji hipoglosusa", "G52.3"),
    G52_7("Poremećaji više moždanih živaca", "G52.7"),
    G52_8("Poremećaji drugih specificiranih moždanih živaca", "G52.8"),
    G52_9("Poremećaj moždanog živca, nespecificiran", "G52.9"),
    G53("Poremećaji kranijalnih živaca kod bolesti svrstanih drugamo", "G53"),
    G53_0("Neuralgija nakon zostera (B02.2)", "G53.0"),
    G53_1("Višestruke kljenuti moždanih živaca kod zaraznih i parazitarnih bolesti svrstanih drugamo (A00-B99)", "G53.1"),
    G53_2("Višestruke kljenuti moždanih živaca kod sarkoidoze (D86.8)", "G53.2"),
    G53_3("Višestruke kljenuti moždanih živaca kod zloćudnih bolesti (C00-D48)", "G53.3"),
    G53_8("Ostali poremećaji moždanih živaca kod ostalih bolesti svrstanih drugamo", "G53.8"),
    G54("Poremećaji živčanih korijena i pleksusa", "G54"),
    G54_0("Poremećaji brahijalnoga pleksusa", "G54.0"),
    G54_1("Poremećaji lumbosakralnoga pleksusa", "G54.1"),
    G54_2("Poremećaji cervikalnih korijena, nesvrstani drugamo", "G54.2"),
    G54_3("Poremećaji torakalnih korijena, nesvrstani drugamo", "G54.3"),
    G54_4("Poremećaji lumbosakralnih korijena, nesvrstani drugamo", "G54.4"),
    G54_5("Neuralgična amiotrofija", "G54.5"),
    G54_6("Sindrom fantomskog uda s boli", "G54.6"),
    G54_7("Sindrom fantomskog uda bez boli", "G54.7"),
    G54_8("Ostali poremećaji živčanih korijena i pleksusa", "G54.8"),
    G54_9("Poremećaj živčanog korijena i pleksusa, nespecificiran", "G54.9"),
    G55("Kompresija živčanih korijena i pleksusa kod bolesti svrstanih drugamo", "G55"),
    G55_0("Kompresija živčanog korijena i pleksusa kod zloćudnih bolesti (C00-D48)", "G55.0"),
    G55_1("Kompresija živčanog korijena i pleksusa kod poremećaja intervertebralnog diska (M50-M51)", "G55.1"),
    G55_2("Kompresija živčanog korijena i pleksusa kod spondiloze (M47.-)", "G55.2"),
    G55_3("Kompresija živčanog korijena i pleksusa kod ostalih dorzopatija (M45-M46, M48.-, M53-M54)", "G55.3"),
    G55_8("Kompresija živčanog korijena i pleksusa kod ostalih drugamo svrstanih bolesti", "G55.8"),
    G56("Mononeuropatije ruke", "G56"),
    G56_0("Sindrom karpalnog kanala", "G56.0"),
    G56_1("Ostale lezije medijanusa", "G56.1"),
    G56_2("Lezija ulnarnog živca", "G56.2"),
    G56_3("Lezija radijalnog živca", "G56.3"),
    G56_4("Kauzalgija", "G56.4"),
    G56_8("Ostale mononeuropatije ruke", "G56.8"),
    G56_9("Mononeuropatija ruke, nespecificirana", "G56.9"),
    G57("Mononeuropatije noge", "G57"),
    G57_0("Lezija ishijadikusa", "G57.0"),
    G57_1("Meralgia paraesthetica", "G57.1"),
    G57_2("Lezija femoralnog živca", "G57.2"),
    G57_3("Lezija lateralnoga poplitealnog živca", "G57.3"),
    G57_4("Lezija medijalnoga poplitealnog živca", "G57.4"),
    G57_5("Sindrom tarzalnog kanala", "G57.5"),
    G57_6("Lezija plantarnog živca", "G57.6"),
    G57_8("Ostale mononeuropatije noge", "G57.8"),
    G57_9("Mononeuropatija noge, nespecificirana", "G57.9"),
    G58("Ostale mononeuropatije", "G58"),
    G58_0("Interkostalna neuropatija", "G58.0"),
    G58_7("Mononeuritis multiplex", "G58.7"),
    G58_8("Ostale specificirane mononeuropatije", "G58.8"),
    G58_9("Mononeuropatija, nespecificirana", "G58.9"),
    G59("Mononeuropatija kod bolesti svrstanih drugamo", "G59"),
    G59_0("Dijabetična mononeuropatija", "G59.0"),
    G60("Nasljedna i idopatska neuorpatija", "G60"),
    G60_0("Nasljedna motorna i senzorna neuropatija", "G60.0"),
    G60_1("Refsumova bolest", "G60.1"),
    G60_2("Neuropatija udružena s nasljednom ataksijom", "G60.2"),
    G60_3("Idiopatska progresivna neuropatija", "G60.3"),
    G60_8("Ostale nasljedne i idiopatske neuropatije", "G60.8"),
    G60_9("Nasljedna i idiopatska neuropatija, nespecificirana", "G60.9"),
    G61("Upalne polineuropatije", "G61"),
    G61_0("Guillain-Barreov sindrom", "G61.0"),
    G61_1("Serumska neuropatija", "G61.1"),
    G61_8("Ostale upalne polineuropatije", "G61.8"),
    G61_9("Upalna polineuropatija, nespecificirana", "G61.9"),
    G62("Ostale polineuropatije", "G62"),
    G62_0("Lijekom uzrokovana polineuropatija", "G62.0"),
    G62_1("Alkoholna polineuropatija", "G62.1"),
    G62_2("Polineuropatija uzrokovana ostalim toksičnim tvarima", "G62.2"),
    G62_8("Ostale specificirane polineuropatije", "G62.8"),
    G62_9("Polineuropatija, nespecificirana", "G62.9"),
    G63("Polineuropatija kod bolesti svrstanih drugamo", "G63"),
    G63_0("Polineuropatija kod infekcijskih i parazitarnih bolesti svrstanih drugamo", "G63.0"),
    G63_1("Polineuropatija kod neoplastične bolesti (C00-D48)", "G63.1"),
    G63_2("Dijabetična polineuropatija", "G63.2"),
    G63_3("Polineuropatija kod ostalih endokrinih i metaboličkih bolesti (E00-E07, E15-E16, E20-E34, E70-E89)", "G63.3"),
    G63_4("Polineuropatija kod manjkave prehrane (E40-E64)", "G63.4"),
    G63_5("Polineuropatija kod sistemnih poremećaja vezivnoga tkiva (M30-M35)", "G63.5"),
    G63_6("Polineuropatija kod ostalih poremećaja mišićno-koštanog sustava (M00-M25, M40-M96)", "G63.6"),
    G63_8("Polineuropatija kod ostalih bolesti svrstanih drugamo", "G63.8"),
    G64("Ostali poremećaji perifernoga živčanog sustava", "G64"),
    G64_0("Ostali poremećaji perifernoga živčanog sustava", "G64.0"),
    G70("Miastenija gravis i ostali mioneuralni poremećaji", "G70"),
    G70_0("Miastenija gravis", "G70.0"),
    G70_1("Toksični mioneuralni poremećaji", "G70.1"),
    G70_2("Prirođena i razvojna miastenija", "G70.2"),
    G70_8("Ostali specificirani mioneuralni poremaćaji", "G70.8"),
    G70_9("Mioneuralni poremećaj, nespecificiran", "G70.9"),
    G71("Primarni poremećaji mišića", "G71"),
    G71_0("Mišićna distrofija", "G71.0"),
    G71_1("Miotonični poremećaji", "G71.1"),
    G71_2("Prirođene miopatije", "G71.2"),
    G71_3("Mitohondrijalna miopatija, nesvrstana drugamo", "G71.3"),
    G71_8("Ostali primarni poremećaji mišića", "G71.8"),
    G71_9("Primarni poremećaj mišića, nespecificiran", "G71.9"),
    G72("Ostale miopatije", "G72"),
    G72_0("Miopatija uzrokovana lijekom", "G72.0"),
    G72_1("Alkoholna miopatija", "G72.1"),
    G72_2("Miopatija uzrokovana ostalim toksičnim tvarima", "G72.2"),
    G72_3("Periodična paraliza", "G72.3"),
    G72_4("Upalna miopatija, nesvrstana drugamo", "G72.4"),
    G72_8("Ostale specificirane miopatije", "G72.8"),
    G72_9("Miopatija, nespecificirana", "G72.9"),
    G73("Poremećaji mioneuralne veze i mišića kod bolesti svrstanih drugamo", "G73"),
    G73_0("Mijastenični sindromi kod endokrinih bolesti", "G73.0"),
    G73_1("Eaton-Lambertov sindrom (C80)", "G73.1"),
    G73_2("Ostali mijastenični sindromi kod zloćudnih bolesti (C00-D48)", "G73.2"),
    G73_3("Mijastenični sindromi kod ostalih bolesti svrstanih drugamo", "G73.3"),
    G73_4("Miopatija kod zaraznih i parazitarnih bolesti svrstanih drugamo", "G73.4"),
    G73_5("Miopatija kod endokrinih bolesti", "G73.5"),
    G73_6("Miopatija kod bolesti metabolizma", "G73.6"),
    G73_7("Miopatija kod ostalih bolesti svrstanih drugamo", "G73.7"),
    G80("Infantilna cerebralna paraliza", "G80"),
    G80_0("Spastična cerebralna paraliza", "G80.0"),
    G80_1("Spastična diplegija", "G80.1"),
    G80_2("Infantilna hemiplegija", "G80.2"),
    G80_3("Diskinetična cerebralna paraliza", "G80.3"),
    G80_4("Ataksična cerebralna paraliza", "G80.4"),
    G80_8("Ostale infantilne cerebralne paralize", "G80.8"),
    G80_9("Infantilna cerebralna paraliza, nespecificirana", "G80.9"),
    G81("Hemiplegija", "G81"),
    G81_0("Mlohava hemiplegija", "G81.0"),
    G81_1("Spastična hemiplegija", "G81.1"),
    G81_9("Hemiplegija, nespecificirana", "G81.9"),
    G82("Paraplegija i tetraplegija", "G82"),
    G82_0("Mlohava paraplegija", "G82.0"),
    G82_1("Spastična paraplegija", "G82.1"),
    G82_2("Paraplegija, nespecificirana", "G82.2"),
    G82_3("Mlohava tetraplegija", "G82.3"),
    G82_4("Spastična tetraplegija", "G82.4"),
    G82_5("Tetraplegija, nespecificirana", "G82.5"),
    G83("Ostali paralitični sindromi", "G83"),
    G83_0("Diplegija ruku", "G83.0"),
    G83_1("Monoplegija noge", "G83.1"),
    G83_2("Monoplegija ruke", "G83.2"),
    G83_3("Monoplegija, nespecificirana", "G83.3"),
    G83_4("Sindrom kaude ekvine", "G83.4"),
    G83_8("Ostali specificirani paralitični sindromi", "G83.8"),
    G83_9("Paralitični sindrom, nespecificiran", "G83.9"),
    G90("Poremećaji autonomnoga živčanog sustava", "G90"),
    G90_0("Idiopatska periferna autonomna neuropatija", "G90.0"),
    G90_1("Obiteljska disautonomija (Riley-Day)", "G90.1"),
    G90_2("Hornerov sindrom", "G90.2"),
    G90_3("Multisistemna degeneracija", "G90.3"),
    G90_8("Ostali poremećaji autonomnoga živčanog sustava", "G90.8"),
    G90_9("Poremećaj autonomnoga živčanog sustava, nespecificiran", "G90.9"),
    G91("Hidrocefalus", "G91"),
    G91_0("Komunicirajući hidrocefalus", "G91.0"),
    G91_1("Opstruktivni hidrocefalus", "G91.1"),
    G91_2("Normotonični hidrocefalus", "G91.2"),
    G91_3("Posttraumatski hidrocefalus, nespecificiran", "G91.3"),
    G91_8("Drugi hidrocefalus", "G91.8"),
    G91_9("Hidrocefalus, nespecificiran", "G91.9"),
    G92("Toksična encefalopatija", "G92"),
    G92_0("Toksična encefalopatija", "G92.0"),
    G93("Ostali poremećaji mozga", "G93"),
    G93_0("Cerebralna cista", "G93.0"),
    G93_1("Anoksično oštećenje mozga, nesvrstano drugamo", "G93.1"),
    G93_2("Benigna intrakranijalna hipertenzija", "G93.2"),
    G93_3("Sindrom iscrpljenosti nakon virusne infekcije", "G93.3"),
    G93_4("Encefalopatija, nespecificirana", "G93.4"),
    G93_5("Kompresija mozga", "G93.5"),
    G93_6("Edem mozga", "G93.6"),
    G93_7("Reyeov sindrom", "G93.7"),
    G93_8("Ostali specificirani poremećaji mozga", "G93.8"),
    G93_9("Poremećaj mozga, nespecificiran", "G93.9"),
    G94("Ostali poremećaji mozga kod bolesti svrstanih drugamo", "G94"),
    G94_0("Hidrocefalus kod zaraznih i parazitarnih bolesti svrstanih drugamo (A00-B99)", "G94.0"),
    G94_1("Hidrocefalus kod zloćudnih bolesti (C00-D48)", "G94.1"),
    G94_2("Hidrocefalus kod ostalih bolesti svrstanih drugamo", "G94.2"),
    G94_8("Ostali specificirani poremećaji mozga kod bolesti svrstanih drugamo", "G94.8"),
    G95("Ostale bolesti kralježnične moždine", "G95"),
    G95_0("Siringomijelija i siringobulbija", "G95.0"),
    G95_1("Vaskularne mijelopatije", "G95.1"),
    G95_2("Kompresija kralježnične moždine, nespecificirana", "G95.2"),
    G95_8("Ostale specificirane bolesti kralježnične moždine", "G95.8"),
    G95_9("Bolest kralježnične moždine, nespecificirana", "G95.9"),
    G96("Ostali poremećaji središnjega živčanog sustava", "G96"),
    G96_0("Istjecanje cerebrospinalne tekućine", "G96.0"),
    G96_1("Poremećaji moždanih ovojnica, nesvrstani drugamo", "G96.1"),
    G96_8("Ostali specificirani poremećaji središnjeg živčanog sustava", "G96.8"),
    G96_9("Poremećaj središnjega živčanog sustava, nespecificiran", "G96.9"),
    G97("Poremećaji živčanog sustava nakon medicinskih postupaka, nesvrstani drugamo", "G97"),
    G97_0("Istjecanje cerebrospinalne tekućine zbog spinalne punkcije", "G97.0"),
    G97_1("Ostale reakcije na spinalnu i lumbalnu punkciju", "G97.1"),
    G97_2("Intrakranijalna hipotenzija nakon ventrikularnog shunta", "G97.2"),
    G97_8("Ostali poremećaji živčanog sustava nakon medicinskih postupaka", "G97.8"),
    G97_9("Poremećaj živčanog sustava nakon medicinskih postupaka, nespecificiran", "G97.9"),
    G98("Ostali poremećaji živčanog sustava, nesvrstani drugamo", "G98"),
    G98_0("Ostali poremećaji živčanog sustava kod bolesti svrstanih drugamo", "G98.0"),
    G99("Ostali poremećaji živčanog sustava kod bolesti nesvrstanih drugamo", "G99"),
    G99_0("Autonomna neuropatija kod endokrinih bolesti i bolesti metabolizma", "G99.0"),
    G99_1("Ostali poremećaji autonomnoga živčanog sustava kod ostalih bolesti svrstanih drugamo", "G99.1"),
    G99_2("Mijelopatija kod bolesti svrstanih drugamo", "G99.2"),
    G99_8("Ostali specificirani poremećaji živčanog sustava kod bolesti svrstanih drugamo", "G99.8");
    
    private final String displayName;
    private final String code;
    
    MkbCodesG(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
