package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesI {
    
    I00("Reumatska groznica bez napomene o srčanoj bolesti", "I00"),
    I00_0("Reumatska groznica bez napomene o srčanoj bolesti", "I00.0"),
    I01("Reumatska groznica sa srčanom bolesti", "I01"),
    I01_0("Akutni reumatski perikarditis", "I01.0"),
    I01_1("Akutni reumatski endokarditis", "I01.1"),
    I01_2("Akutni reumatski miokarditis", "I01.2"),
    I01_8("Druga akutna reumatska bolest srca", "I01.8"),
    I01_9("Akutna reumatska bolest srca, nespecificirana", "I01.9"),
    I02("Reumatska koreja", "I02"),
    I02_0("Reumatska koreja sa srčanom bolesti", "I02.0"),
    I02_9("Reumatska koreja bez srčane bolesti", "I02.9"),
    I05("Reumatske bolesti mitralne valvule", "I05"),
    I05_0("Mitralna stenoza", "I05.0"),
    I05_1("Reumatska mitralna insuficijencija", "I05.1"),
    I05_2("Mitralna stenoza s insuficijencijom", "I05.2"),
    I05_8("Ostale bolesti mitralne valvule", "I05.8"),
    I05_9("Bolest mitralne valvule, nespecificirana", "I05.9"),
    I06("Reumatske bolesti aortne valvule", "I06"),
    I06_0("Reumatska aortna stenoza", "I06.0"),
    I06_1("Reumatska aortna insuficijencija", "I06.1"),
    I06_2("Reumatska aortna stenoza s insuficijencijom", "I06.2"),
    I06_8("Ostale reumatske bolesti aortne valvule", "I06.8"),
    I06_9("Reumatska bolest aortne valvule, nespecificirana", "I06.9"),
    I07("Reumatske bolesti trikuspidalne valvule", "I07"),
    I07_0("Trikuspidalna stenoza", "I07.0"),
    I07_1("Trikuspidalna insuficijencija", "I07.1"),
    I07_2("Trikuspidalna stenoza s insuficijencijom", "I07.2"),
    I07_8("Ostale bolesti trikuspidalne valvule", "I07.8"),
    I07_9("Bolest trikuspidalne valvule, nespecificirana", "I07.9"),
    I08("Višestruke valvularne bolesti", "I08"),
    I08_0("Poremećaji i mitralnih i aortnih valvula", "I08.0"),
    I08_1("Zahvaćanje obiju, i mitralne i trikuspidalne valvule", "I08.1"),
    I08_2("Zahvaćanje obiju, i aortne i trikuspidalne valvule", "I08.2"),
    I08_3("Udruženi poremećaji mitralne, aortne i trikuspidalne valvule", "I08.3"),
    I08_8("Ostali višestruki valvularni poremećaji", "I08.8"),
    I08_9("Višestruki valvularni poremećaj, nespecificiran", "I08.9"),
    I09("Ostale reumatske bolesti srca", "I09"),
    I09_0("Reumatski miokarditis", "I09.0"),
    I09_1("Reumatske bolesti endokarda, valvula nespecificirana", "I09.1"),
    I09_2("Kronični reumatski perikarditis", "I09.2"),
    I09_8("Ostale specificirane reumatske bolesti srca", "I09.8"),
    I09_9("Reumatska bolest srca, nespecificirana", "I09.9"),
    I10("Esencijalna (primarna) hipertenzija", "I10"),
    I10_0("Esencijalna (primarna) hipertenzija", "I10.0"),
    I11("Hipertenzivna bolest srca", "I11"),
    I11_0("Hipertenzivna srčana bolest s kongestivnim slabljenjem srca", "I11.0"),
    I11_9("Hipertenzivna srčana bolest bez kongestivnog slabljenja srca", "I11.9"),
    I12("Hipertenzivna bolest bubrega", "I12"),
    I12_0("Hipertenzivna renalna bolest s oštećenjem bubrega", "I12.0"),
    I12_9("Hipertenzivna renalna bolest bez oštećenja bubrega", "I12.9"),
    I13("Hipertenzivna bolest srca i bubrega", "I13"),
    I13_0("Hipertenzivna bolest srca i bubrežna bolest s kongestivnim srčanim slabljenjem", "I13.0"),
    I13_1("Hipertenzivna bolest srca i bubrežna bolest s oštećenjem bubrega", "I13.1"),
    I13_2("Hipertenzivna bolest srca i bubrežna bolest s kongestivnim srčanim slabljenjem i oštećenjem bubrega", "I13.2"),
    I13_9("Hipertenzivna bolest srca i bubrežna bolest, nespecificirana", "I13.9"),
    I15("Sekundarna hipertenzija", "I15"),
    I15_0("Renovaskularna hipertenzija", "I15.0"),
    I15_1("Sekundarna hipertenzija zbog drugih bubrežnih bolesti", "I15.1"),
    I15_2("Sekundarna hipertenzija zbog endokrinih bolesti", "I15.2"),
    I15_8("Druga sekundarna hipertenzija", "I15.8"),
    I15_9("Sekundarna hipertenzija, nespecificirana", "I15.9"),
    I20("Angina pektoris", "I20"),
    I20_0("Nestabilna angina", "I20.0"),
    I20_1("Angina pektoris s dokazanim spazmom", "I20.1"),
    I20_8("Ostali oblici agnine pektoris", "I20.8"),
    I20_9("Angina pektoris, nespecificirana", "I20.9"),
    I21("Akutni infarkt miokarda", "I21"),
    I21_0("Akutni transmuralni infarkt prednje stijenke miokarda", "I21.0"),
    I21_1("Akutni transmuralni infarkt donje stijenke miokarda", "I21.1"),
    I21_2("Akutni transmuralni infarkt miokarda ostalih lokalizacija", "I21.2"),
    I21_3("Akutni transmuralni infarkt miokarda nespecificirane lokalizacije", "I21.3"),
    I21_4("Akutni subendokardijalni infarkt miokarda", "I21.4"),
    I21_9("Akutni infarkt miokarda, nespecificirani", "I21.9"),
    I22("Ponovljeni infarkt miokarda", "I22"),
    I22_0("Ponovljeni infarkt prednje stijenke miokarda", "I22.0"),
    I22_1("Ponovljeni infarkt donje stijenke miokarda", "I22.1"),
    I22_8("Ponovljeni infarkt miokarda ostalih lokalizacija", "I22.8"),
    I22_9("Ponovljeni infarkt miokarda nespecificirane lokalizacije", "I22.9"),
    I23("Komplikacije nakon akutnog infarkta miokarda", "I23"),
    I23_0("Hemoperikard nastao kao komplikacija nakon akutnog infarkta miokarda", "I23.0"),
    I23_1("Atrijalni septalni defekt nastao kao komplikacija nakon akutnog infarkta miokarda", "I23.1"),
    I23_2("Ventrikularni septalni defekt nastao kao komplikacija nakon akutnog infarkta miokarda", "I23.2"),
    I23_3("Ruptura srčane stijenke bez hemoperikarda nastala kao komplikacija nakon akutnog infarkta miokarda", "I23.3"),
    I23_4("Ruptura korde tendineje nastala kao komplikacija nakon akutnog infarkta miokarda", "I23.4"),
    I23_5("Ruptura papilarnog mišića nastala kao komplikacija nakon akutnog infarkta miokarda", "I23.5"),
    I23_6("Tromboza atrija, aurikule atrija i ventrikula nastala kao komplikacija nakon akutnog infarkta miokarda", "I23.6"),
    I23_8("Ostale komplikacije nastale nakon akutnog infarkta miokarda", "I23.8"),
    I24("Ostale akutne ishemične bolesti srca", "I24"),
    I24_0("Koronarna tromboza nakon koje nije nastao infarkt miokarda", "I24.0"),
    I24_1("Dresslerov sindrom", "I24.1"),
    I24_8("Ostali oblici akutne ishemične bolesti srca", "I24.8"),
    I24_9("Akutna ishemična bolest srca, nespecificirana", "I24.9"),
    I25("Kronična ishemična bolest srca", "I25"),
    I25_0("Aterosklerotska kardiovaskularna bolest", "I25.0"),
    I25_1("Aterosklerotska bolest srca", "I25.1"),
    I25_2("Stari infarkt miokarda", "I25.2"),
    I25_3("Aneurizma srca", "I25.3"),
    I25_4("Aneurizma koronarne arterije", "I25.4"),
    I25_5("Ishemična kardiomiopatija", "I25.5"),
    I25_6("Asimptomatska ishemija miokarda", "I25.6"),
    I25_8("Ostali oblici kronične ishemične bolesti srca", "I25.8"),
    I25_9("Kronična ishemična bolest srca, nespecificirana", "I25.9"),
    I26("Plućna embolija", "I26"),
    I26_0("Plućna embolija uz spominjanje akutnoga plućnog srca", "I26.0"),
    I26_9("Plućna embolija bez spominjanja akutnoga plućnog srca", "I26.9"),
    I27("Ostale plućne bolesti srca", "I27"),
    I27_0("Primarna plućna hipertenzija", "I27.0"),
    I27_1("Kifoskoliotična bolest srca", "I27.1"),
    I27_8("Ostale specificirane plućne bolesti srca", "I27.8"),
    I27_9("Plućna bolest srca, nespecificirana", "I27.9"),
    I28("Ostale bolesti plućnih krvnih žila", "I28"),
    I28_0("Arterio-venska fistula plućnih krvnih žila", "I28.0"),
    I28_1("Aneurizma plućne arterije", "I28.1"),
    I28_8("Ostale specificirane bolesti plućnih krvnih žila", "I28.8"),
    I28_9("Bolest plućnih krvnih žila, nespecificirana", "I28.9"),
    I30("Akutni perikarditis", "I30"),
    I30_0("Akutni nespecifični idiopatski perikarditis", "I30.0"),
    I30_1("Infektivni perikarditis", "I30.1"),
    I30_8("Ostali oblici akutnog perikarditisa", "I30.8"),
    I30_9("Akutni perikarditis, nespecificirani", "I30.9"),
    I31("Ostale bolesti perikarda", "I31"),
    I31_0("Kronični adhezivni perikarditis", "I31.0"),
    I31_1("Kronični konstriktivni perikarditis", "I31.1"),
    I31_2("Hemoperikard, nesvrstan drugamo", "I31.2"),
    I31_3("Perikardni izljev (neupalni)", "I31.3"),
    I31_8("Ostale specificirane bolesti perikarda", "I31.8"),
    I31_9("Bolest perikarda, nespecificirana", "I31.9"),
    I32("Perikarditis u bolestima svrstanim drugamo", "I32"),
    I32_0("Perikarditis u bakterijskim bolestima svrstanim drugamo", "I32.0"),
    I32_1("Perikarditis u ostalim zaraznim i parazitarnim bolestima svrstanim drugamo", "I32.1"),
    I32_8("Perikarditis u ostalim bolestima svrstanim drugamo", "I32.8"),
    I33("Akutni i subakutni endokarditis", "I33"),
    I33_0("Akutni i subakutni infektivni endokarditis", "I33.0"),
    I33_9("Akutni endokarditis, nespecificirani", "I33.9"),
    I34("Nereumatske bolesti mitralne valvule", "I34"),
    I34_0("Mitralna (valvule) insuficijencija", "I34.0"),
    I34_1("Prolaps mitralne valvule", "I34.1"),
    I34_2("Nereumatska mitralna (valvule) stenoza", "I34.2"),
    I34_8("Ostale nereumatske bolesti mitralne valvule", "I34.8"),
    I34_9("Nereumatska bolest mitralne valvule, nespecificirana", "I34.9"),
    I35("Nereumatske bolesti aortne valvule", "I35"),
    I35_0("Aortna (valvule) stenoza", "I35.0"),
    I35_1("Aortna (valvule) insuficijencija", "I35.1"),
    I35_2("Aortna (valvule) stenoza s insuficijencijom", "I35.2"),
    I35_8("Ostale bolesti aortne valvule", "I35.8"),
    I35_9("Bolest aortne valvule, nespecificirana", "I35.9"),
    I36("Nereumatske bolesti trikuspidalne valvule", "I36"),
    I36_0("Nereumatska trikuspidalna (valvule) stenoza", "I36.0"),
    I36_1("Nereumatska trikuspidalna (valvule) insuficijencija", "I36.1"),
    I36_2("Nereumatska trikuspidalna (valvule) stenoza s insuficijencijom", "I36.2"),
    I36_8("Ostale nereumatske bolesti trikuspidalne valvule", "I36.8"),
    I36_9("Nereumatska bolest trikuspidalne valvule, nespecificirana", "I36.9"),
    I37("Bolesti pulmonalne valvule", "I37"),
    I37_0("Stenoza pulmonalne valvule", "I37.0"),
    I37_1("Insuficijencija pulmonalne valvule", "I37.1"),
    I37_2("Stenoza pulmonalne valvule s insuficijencijom", "I37.2"),
    I37_8("Ostale bolesti pulmonalne valvule", "I37.8"),
    I37_9("Bolest pulmonalne valvule, nespecificirana", "I37.9"),
    I38("Endokarditis, valvula nespecificirana", "I38"),
    I38_0("Endokarditis, valvula nespecificirana", "I38.0"),
    I39("Endokarditis i bolesti srčanih valvula u bolestima svrstanim drugamo", "I39"),
    I39_0("Bolesti mitralne valvule u bolestima svrstanim drugamo", "I39.0"),
    I39_1("Bolesti aortne valvule u bolestima svrstanim drugamo", "I39.1"),
    I39_2("Bolesti trikuspidalne valvule u bolestima svrstanim drugamo", "I39.2"),
    I39_3("Bolesti pulmonalne valvule u bolestima svrstanim drugamo", "I39.3"),
    I39_4("Bolesti više valvula u bolestima svrstanim drugamo", "I39.4"),
    I39_8("Endokarditis nespecificirane valvule u bolestima svrstanim drugamo", "I39.8"),
    I40("Akutni miokarditis", "I40"),
    I40_0("Infektivni miokarditis", "I40.0"),
    I40_1("Izolirani miokarditis", "I40.1"),
    I40_8("Drugi akutni miokarditis", "I40.8"),
    I40_9("Akutni miokarditis, nespecificirani", "I40.9"),
    I41("Miokarditis u bolestima svrstanim drugamo", "I41"),
    I41_0("Miokarditis u bakterijskim bolestima svrstanim drugamo", "I41.0"),
    I41_1("Miokarditis u virusnim bolestima svrstanim drugamo", "I41.1"),
    I41_2("Miokarditis u ostalim zaraznim i parazitarnim bolestima svrstanim drugamo", "I41.2"),
    I41_8("Miokarditis u ostalim bolestima svrstanim drugamo", "I41.8"),
    I42("Kardiomiopatija", "I42"),
    I42_0("Dilatacijska kardiomiopatija", "I42.0"),
    I42_1("Opstruktivna hipertrofična kardiomiopatija", "I42.1"),
    I42_2("Druga hipertrofična kardiomiopatija", "I42.2"),
    I42_3("Endomiokardijalna (eozinofilna) bolest", "I42.3"),
    I42_4("Endokardijalna fibroelastoza", "I42.4"),
    I42_5("Druga restriktivna kardiomiopatija", "I42.5"),
    I42_6("Alkoholna kardiomiopatija", "I42.6"),
    I42_7("Kardiomiopatija nastala zbog lijekova i ostalih vanjskih uzroka", "I42.7"),
    I42_8("Ostale kardiomiopatije", "I42.8"),
    I42_9("Kardiomiopatija, nespecificirana", "I42.9"),
    I43("Kardiomiopatija kod bolesti svrstanih drugamo", "I43"),
    I43_0("Kardiomiopatija kod zaraznih i parazitarnih bolesti svrstanih drugamo", "I43.0"),
    I43_1("Kardiomiopatija kod bolesti metabolizma", "I43.1"),
    I43_2("Kardiomiopatija u nutritivnim bolestima", "I43.2"),
    I43_8("Kardiomiopatija u ostalim bolestima svrstanim drugamo", "I43.8"),
    I44("Atrioventrikularni blok i blok lijeve grane", "I44"),
    I44_0("Atrioventrikularni blok, prvi stupanj", "I44.0"),
    I44_1("Atrioventrikularni blok, drugi stupanj", "I44.1"),
    I44_2("Atrioventrikularni blok, kompletni", "I44.2"),
    I44_3("Drugi i nespecificirani atrioventrikularni blok", "I44.3"),
    I44_4("Prednji lijevi fascikularni blok", "I44.4"),
    I44_5("Stražnji lijevi fascikularni blok", "I44.5"),
    I44_6("Drugi i nespecificirani fascikularni blok", "I44.6"),
    I44_7("Blok lijeve grane, nespecificiran", "I44.7"),
    I45("Ostali poremećaji provođenja", "I45"),
    I45_0("Blok desne grane", "I45.0"),
    I45_1("Drugi i nespecificirani blok desne grane", "I45.1"),
    I45_2("Bifascikularni blok", "I45.2"),
    I45_3("Trifascikularni blok", "I45.3"),
    I45_4("Nespecifični intraventrikularni blok", "I45.4"),
    I45_5("Drugi i specificirani blok srca", "I45.5"),
    I45_6("Sindrom preekscitacije", "I45.6"),
    I45_8("Ostali specificirani poremećaji provođenja", "I45.8"),
    I45_9("Poremećaj provođenja, nespecificiran", "I45.9"),
    I46("Arest srca", "I46"),
    I46_0("Srčani arest s uspješnim oživljavanjem", "I46.0"),
    I46_1("Iznenadna srčana smrt", "I46.1"),
    I46_9("Srčani arest, nespecificiran", "I46.9"),
    I47("Paroksizmalna tahikardija", "I47"),
    I47_0("Kružna (re-entry) ventrikularna aritmija", "I47.0"),
    I47_1("Supraventrikularna tahikardija", "I47.1"),
    I47_2("Ventrikularna tahikardija", "I47.2"),
    I47_9("Paroksizmalna tahikardija, nespecificirana", "I47.9"),
    I48("Fibrilacija atrija i undulacija", "I48"),
    I48_0("Fibrilacija atrija i undulacija", "I48.0"),
    I49("Ostale srčane aritmije", "I49"),
    I49_0("Ventrikularna fibrilacija i undulacija", "I49.0"),
    I49_1("Atrijalna preuranjena depolarizacija", "I49.1"),
    I49_2("Junkcionalna preuranjena depolarizacija", "I49.2"),
    I49_3("Ventrikularna preuranjena depolarizacija", "I49.3"),
    I49_4("Druga i nespecificirana preuranjena depolarizacija", "I49.4"),
    I49_5("Sindrom bolesnoga sinusnog čvora (Sick sinus sindrom)", "I49.5"),
    I49_8("Ostale specificirane srčane aritmije", "I49.8"),
    I49_9("Srčana aritmija, nespecificirana", "I49.9"),
    I50("Insuficijencija srca", "I50"),
    I50_0("Kongestivna insuficijencija srca", "I50.0"),
    I50_1("Insuficijencija lijevog ventrikula", "I50.1"),
    I50_9("Insuficijencija srca, nespecificirana", "I50.9"),
    I51("Komplikacije i nedovoljno definirani opisi srčane bolesti", "I51"),
    I51_0("Defekt septuma srca, stečeni", "I51.0"),
    I51_1("Ruptura korde tendineje, nesvrstana drugamo", "I51.1"),
    I51_2("Ruptura papilarnog mišića, nesvrstana drugamo", "I51.2"),
    I51_3("Intrakardijalna tromboza, nesvrstana drugamo", "I51.3"),
    I51_4("Miokarditis, nespecificirani", "I51.4"),
    I51_5("Degeneracija miokarda", "I51.5"),
    I51_6("Kardiovaskularna bolest, nespecificirana", "I51.6"),
    I51_7("Kardiomegalija", "I51.7"),
    I51_8("Ostale nedovoljno definirane srčane bolesti", "I51.8"),
    I51_9("Srčana bolest, nespecificirana", "I51.9"),
    I52("Ostale srčane bolesti u bolestima svrstanim drugamo", "I52"),
    I52_0("Ostale srčane bolesti kod bakterijskih bolesti svrstanih drugamo", "I52.0"),
    I52_1("Ostale srčane bolesti u drugim zaraznim i parazitarnim bolestima svrstanim drugamo", "I52.1"),
    I52_8("Ostale srčane bolesti u ostalim bolestima svrstanim drugamo", "I52.8"),
    I60("Subarahnoidalno krvarenje", "I60"),
    I60_0("Subarahnoidalno krvarenje iz sifona i bifurkacije karotide", "I60.0"),
    I60_1("Subarahnoidalno krvarenje iz arterije cerebri medije", "I60.1"),
    I60_2("Subarahnoidalno krvarenje iz prednje arterije komunikans", "I60.2"),
    I60_3("Subarahnoidalno krvarenje iz stražnje arterije komunikans", "I60.3"),
    I60_4("Subarahnoidalno krvarenje iz bazilarne arterije", "I60.4"),
    I60_5("Subarahnoidalno krvarenje iz vertebralne arterije", "I60.5"),
    I60_6("Subarahnoidalno krvarenje iz ostalih intrakranijalnih arterija", "I60.6"),
    I60_7("Subarahnoidalno krvarenje iz intrakranijalne arterije, nespecificirano", "I60.7"),
    I60_8("Ostala subarahnoidalna krvarenja", "I60.8"),
    I60_9("Subarahnoidalno krvarenje, nespecificirano", "I60.9"),
    I61("Intracerebralno krvarenje", "I61"),
    I61_0("Intracerebralno krvarenje u hemisferi, subkortikalno", "I61.0"),
    I61_1("Intracerebralno krvarenje u hemisferi, kortikalno", "I61.1"),
    I61_2("Intracerebralno krvarenje u hemisferi, nespecificirano", "I61.2"),
    I61_3("Intracerebralno krvarenje u moždanom deblu", "I61.3"),
    I61_4("Intracerebralno krvarenje u malom mozgu", "I61.4"),
    I61_5("Intracerebralno krvarenje, intraventrikularno", "I61.5"),
    I61_6("Intracerebralno krvarenje, s više lokalizacija", "I61.6"),
    I61_8("Drugo intracerebralno krvarenje", "I61.8"),
    I61_9("Intracerebralno krvarenje, nespecificirano", "I61.9"),
    I62("Ostala netraumatska intrakranijalna krvarenja", "I62"),
    I62_0("Subduralno krvarenje (akutno) (netraumatsko)", "I62.0"),
    I62_1("Netraumatsko ekstraduralno krvarenje", "I62.1"),
    I62_9("Intrakranijalno krvarenje (netraumatsko), nespecificirano", "I62.9"),
    I63("Cerebralni infarkt", "I63"),
    I63_0("Cerebralni infarkt zbog tromboze ekstracerebralnih arterija", "I63.0"),
    I63_1("Cerebralni infarkt zbog embolije ekstracerebralnih arterija", "I63.1"),
    I63_2("Cerebralni infarkt zbog nespecificirane okluzije ili stenoze ekstracerebralnih arterija", "I63.2"),
    I63_3("Cerebralni infarkt zbog tromboze cerebralnih arterija", "I63.3"),
    I63_4("Cerebralni infarkt zbog embolije cerebralnih arterija", "I63.4"),
    I63_5("Cerebralni infarkt zbog nespecificirane okluzije ili stenoze cerebralnih arterija", "I63.5"),
    I63_6("Cerebralni infarkt zbog cerebralne venske tromboze, aseptični", "I63.6"),
    I63_8("Drugi cerebralni infarkt", "I63.8"),
    I63_9("Cerebralni infarkt, nespecificiran", "I63.9"),
    I64("Inzult, nespecificiran kao krvarenje ili infarkt", "I64"),
    I64_0("Inzult, nespecificiran kao krvarenje ili infarkt", "I64.0"),
    I65("Okluzija i stenoza ekstracerebralnih arterija koje nisu uzrokovale cerebralni infarkt", "I65"),
    I65_0("Okluzija i stenoza vertebralne arterije", "I65.0"),
    I65_1("Okluzija i stenoza bazilarne arterije", "I65.1"),
    I65_2("Okluzija i stenoza karotidne arterije", "I65.2"),
    I65_3("Okluzija i stenoza više ekstracerebralnih, kao i bilateralnih ekstracerebralnih arterija", "I65.3"),
    I65_8("Okluzija i stenoza druge ekstracerebralne arterije", "I65.8"),
    I65_9("Okluzija i stenoza nespecificirane ekstracerebralne arterije", "I65.9"),
    I66("Okluzija i stenoza cerebralnih arterija koje nisu uzrokovale cerebralni infarkt", "I66"),
    I66_0("Okluzija i stenoza srednje cerebralne arterije", "I66.0"),
    I66_1("Okluzija i stenoza prednje cerebralne arterije", "I66.1"),
    I66_2("Okluzija i stenoza stražnje cerebralne arterije", "I66.2"),
    I66_3("Okluzija i stenoza cerebelarnih arterija", "I66.3"),
    I66_4("Okluzija i stenoza više cerebralnih, kao i bilateralnih cerebralnih arterija", "I66.4"),
    I66_8("Okluzija i stenoza druge cerebralne arterije", "I66.8"),
    I66_9("Okluzija i stenoza nespecificirane cerebralne arterije", "I66.9"),
    I67("Ostale cerebrovaskularne bolesti", "I67"),
    I67_0("Disekcija cerebralnih arterija, nerupturirana", "I67.0"),
    I67_1("Cerebralna aneurizma, nerupturirana", "I67.1"),
    I67_2("Cerebralna ateroskleroza", "I67.2"),
    I67_3("Progresivna vaskularna leukoencefalopatija", "I67.3"),
    I67_4("Hipertenzivna encefalopatija", "I67.4"),
    I67_5("Moyamoya bolest", "I67.5"),
    I67_6("Aseptična tromboza intrakranijalnoga venskog sustava", "I67.6"),
    I67_7("Cerebralni arteritis, nesvrstan drugamo", "I67.7"),
    I67_8("Ostale specificirane cerebrovaskularne bolesti", "I67.8"),
    I67_9("Cerebrovaskularna bolest, nespecificirana", "I67.9"),
    I68("Cerebrovaskularni poremećaji u bolestima svrstanim drugamo", "I68"),
    I68_0("Cerebralna amiloidna angiopatija (E85.-)", "I68.0"),
    I68_1("Cerebralni arteritis kod zaraznih i parazitarnih bolesti svrstanih drugamo", "I68.1"),
    I68_2("Cerebralni arteritis kod ostalih bolesti svrstanih drugamo", "I68.2"),
    I68_8("Ostali cerebrovaskularni poremećaji u bolestima svrstanim drugamo", "I68.8"),
    I69("Posljedice cerebrovaskularnih bolesti", "I69"),
    I69_0("Posljedice subarahnoidalnoga krvarenja", "I69.0"),
    I69_1("Posljedice intracerebralnoga krvarenja", "I69.1"),
    I69_2("Posljedice ostalih netraumatskih intrakranijalnih krvarenja", "I69.2"),
    I69_3("Posljedice cerebralnog infarkta", "I69.3"),
    I69_4("Posljedice inzulta, nespecificiranog kao krvarenje ili infarkt", "I69.4"),
    I69_8("Posljedice ostalih i nespecificiranih cerebrovaskularnih bolesti", "I69.8"),
    I70("Ateroskleroza", "I70"),
    I70_0("Ateroskleroza aorte", "I70.0"),
    I70_1("Ateroskleroza bubrežne arterije", "I70.1"),
    I70_2("Ateroskleroza arterija udova", "I70.2"),
    I70_8("Ateroskleroza ostalih arterija", "I70.8"),
    I70_9("Generalizirana i nespecificirana ateroskleroza", "I70.9"),
    I71("Aneurizma i disekcija aorte", "I71"),
    I71_0("Disekcija aorte", "I71.0"),
    I71_1("Aneurizma torakalne aorte, rupturirana", "I71.1"),
    I71_2("Aneurizma torakalne aorte, bez napomene o rupturi", "I71.2"),
    I71_3("Aneurizma abdominalne aorte, rupturirana", "I71.3"),
    I71_4("Aneurizma abdominalne aorte, bez napomene o rupturi", "I71.4"),
    I71_5("Aneurizma torakoabdominalne aorte, rupturirana", "I71.5"),
    I71_6("Aneurizma torakoabdominalne aorte, bez napomene o rupturi", "I71.6"),
    I71_8("Aneurizma aorte nespecificirane lokalizacije, rupturirana", "I71.8"),
    I71_9("Aneurizma aorte nespecificirane lokalizacije, bez napomene o rupturi", "I71.9"),
    I72("Ostale aneurizme", "I72"),
    I72_0("Aneurizma karotidne arterije", "I72.0"),
    I72_1("Aneurizma arterije ruke", "I72.1"),
    I72_2("Aneurizma bubrežne arterije", "I72.2"),
    I72_3("Aneurizma ilijačne arterije", "I72.3"),
    I72_4("Aneurizma arterije noge", "I72.4"),
    I72_8("Aneurizma ostalih specificiranih arterija", "I72.8"),
    I72_9("Aneurizma nespecificirane lokalizacije", "I72.9"),
    I73("Ostale bolesti perifernih krvnih žila", "I73"),
    I73_0("Raynaudov sindrom", "I73.0"),
    I73_1("Thrombangiitis obliterans (Buerger)", "I73.1"),
    I73_8("Ostale specificirane bolesti perifernih krvnih žila", "I73.8"),
    I73_9("Bolesti perifernih krvnih žila, nespecificirane", "I73.9"),
    I74("Embolija i tromboza arterija", "I74"),
    I74_0("Embolija i tromboza abdominalne aorte", "I74.0"),
    I74_1("Embolija i tromboza ostalih i nespecificiranih dijelova aorte", "I74.1"),
    I74_2("Embolija i tromboza arterija ruke", "I74.2"),
    I74_3("Embolija i tromboza arterija noge", "I74.3"),
    I74_4("Embolija i tromboza arterija udova, nespecificirana", "I74.4"),
    I74_5("Embolija i tromboza ilijačne arterije", "I74.5"),
    I74_8("Embolija i tromboza ostalih arterija", "I74.8"),
    I74_9("Embolija i tromboza nespecificiranih arterija", "I74.9"),
    I77("Ostale bolesti arterija i arteriola", "I77"),
    I77_0("Arterio-venska fistula, stečena", "I77.0"),
    I77_1("Striktura arterije", "I77.1"),
    I77_2("Ruptura arterije", "I77.2"),
    I77_3("Fibromuskularna displazija arterije", "I77.3"),
    I77_4("Kompresivni sindrom celijačne arterije", "I77.4"),
    I77_5("Nekroza arterije", "I77.5"),
    I77_6("Arteritis, nespecificirani", "I77.6"),
    I77_8("Ostale specificirane bolesti arterija i arteriola", "I77.8"),
    I77_9("Bolest arterija i arteriola, nespecificirana", "I77.9"),
    I78("Bolesti kapilara", "I78"),
    I78_0("Hereditarna hemoragijska teleangiektazija", "I78.0"),
    I78_1("Nevus, neneoplastični", "I78.1"),
    I78_8("Ostale bolesti kapilara", "I78.8"),
    I78_9("Bolest kapilara, nespecificirana", "I78.9"),
    I79("Bolesti arterija, arteriola i kapilara kod bolesti svrstanih drugamo", "I79"),
    I79_0("Aneurizma aorte kod bolesti svrstanih drugamo", "I79.0"),
    I79_1("Aortitis kod bolesti svrstanih drugamo", "I79.1"),
    I79_2("Periferna angiopatija kod bolesti svrstanih drugamo", "I79.2"),
    I79_8("Ostale bolesti arterija, arteriola i kapilara kod bolesti svrstanih drugamo", "I79.8"),
    I80("Flebitis i tromboflebitis", "I80"),
    I80_0("Flebitis i tromboflebitis površinskih krvnih žila nogu", "I80.0"),
    I80_1("Flebitis i tromboflebitis femoralne vene", "I80.1"),
    I80_2("Flebitis i tromboflebitis ostalih dubokih krvnih žila nogu", "I80.2"),
    I80_3("Flebitis i tromboflebitis nogu, nespecificirani", "I80.3"),
    I80_8("Flebitis i tromboflebitis ostalih lokalizacija", "I80.8"),
    I80_9("Flebitis i tromboflebitis nespecificirane lokalizacije", "I80.9"),
    I81("Tromboza vene porte", "I81"),
    I81_0("Tromboza vene porte", "I81.0"),
    I82("Ostale embolije i tromboze vena", "I82"),
    I82_0("Budd-Chiarijev sindrom", "I82.0"),
    I82_1("Thrombophlebitis migrans", "I82.1"),
    I82_2("Embolija i tromboza šuplje vene", "I82.2"),
    I82_3("Embolija i tromboza bubrežne vene", "I82.3"),
    I82_8("Embolija i tromboza ostalih specificiranih vena", "I82.8"),
    I82_9("Embolija i tromboza nespecificirane vene", "I82.9"),
    I83("Varikozne vene nogu", "I83"),
    I83_0("Varikozne vene nogu s ulkusom", "I83.0"),
    I83_1("Varikozne vene nogu s upalom", "I83.1"),
    I83_2("Varikozne vene nogu s ulkusom i upalom", "I83.2"),
    I83_9("Varikozne vene nogu bez ulkusa ili upale", "I83.9"),
    I84("Hemoroidi", "I84"),
    I84_0("Unutrašnji hemoroidi, trombozirani", "I84.0"),
    I84_1("Unutrašnji hemoroidi s ostalim komplikacijama", "I84.1"),
    I84_2("Unutrašnji hemoroidi bez komplikacija", "I84.2"),
    I84_3("Vanjski hemoroidi, trombozirani", "I84.3"),
    I84_4("Vanjski hemoroidi s ostalim komplikacijama", "I84.4"),
    I84_5("Vanjski hemoroidi bez komplikacija", "I84.5"),
    I84_6("Fibrozne resice nakon izlječenja hemoroida", "I84.6"),
    I84_7("Nespecificirani hemoroidi, trombozirani", "I84.7"),
    I84_8("Nespecificirani hemoroidi s ostalim komplikacijama", "I84.8"),
    I84_9("Nespecificirani hemoroidi bez komplikacija", "I84.9"),
    I85("Varikoziteti jednjaka", "I85"),
    I85_0("Varikoziteti jednjaka s krvarenjem", "I85.0"),
    I85_9("Varikoziteti jednjaka bez krvarenja", "I85.9"),
    I86("Varikozne vene ostalih lokalizacija", "I86"),
    I86_0("Sublingvalni varikoziteti", "I86.0"),
    I86_1("Varikoziteti skrotuma", "I86.1"),
    I86_2("Varikoziteti zdjelice", "I86.2"),
    I86_3("Varikoziteti stidnice", "I86.3"),
    I86_4("Varikoziteti želuca", "I86.4"),
    I86_8("Varikoziteti vena ostalih specificiranih mjesta", "I86.8"),
    I87("Ostale venske bolesti", "I87"),
    I87_0("Postflebitični sindrom", "I87.0"),
    I87_1("Kompresija vene", "I87.1"),
    I87_2("Venska insuficijencija (kronična) (periferna)", "I87.2"),
    I87_8("Ostale specificirane venske bolesti", "I87.8"),
    I87_9("Bolest vene, nespecificirana", "I87.9"),
    I88("Nespecifični limfadenitis", "I88"),
    I88_0("Nespecifični mezenterični limfadenitis", "I88.0"),
    I88_1("Kronični limfadenitis, osim mezenteričnog", "I88.1"),
    I88_8("Ostali nespecifični limfadenitisi", "I88.8"),
    I88_9("Nespecifični limfadenitis, nespecificiran", "I88.9"),
    I89("Ostale neinfektivne bolesti limfnih žila i limfnih čvorova", "I89"),
    I89_0("Limfedem, nesvrstan drugamo", "I89.0"),
    I89_1("Limfangitis", "I89.1"),
    I89_8("Ostale specificirane neinfektivne bolesti limfnih žila i limfnih čvorova", "I89.8"),
    I89_9("Neinfektivna bolest limfnih žila i limfnih čvorova, nespecificirana", "I89.9"),
    I95("Hipotenzija", "I95"),
    I95_0("Idiopatska hipotenzija", "I95.0"),
    I95_1("Ortostatska hipotenzija", "I95.1"),
    I95_2("Hipotenzija uzrokovana lijekovima", "I95.2"),
    I95_8("Ostale hipotenzije", "I95.8"),
    I95_9("Hipotenzija, nespecificirana", "I95.9"),
    I97("Bolesti cirkulacijskog sustava nastale nakon medicinskih postupaka, a nesvrstane drugamo", "I97"),
    I97_0("Postkardiotomni sindrom", "I97.0"),
    I97_1("Ostali funkcionalni poremećaji nakon operacije srca", "I97.1"),
    I97_2("Sindrom limfedema nakon mastektomije", "I97.2"),
    I97_8("Ostale bolesti cirkulacijskog sustava nastale nakon medicinskih postupaka, a nesvrstane drugamo", "I97.8"),
    I97_9("Bolest cirkulacijskog sustava nastala nakon medicinskih postupaka, nespecificirana", "I97.9"),
    I98("Ostale bolesti cirkulacijskog sustava u bolestima svrstanim drugamo", "I98"),
    I98_0("Kardiovaskularni sifilis", "I98.0"),
    I98_1("Kardiovaskularne bolesti u ostalim infektivnim i parazitarnim bolestima svrstanim drugamo", "I98.1"),
    I98_2("Varikoziteti jednjaka u bolestima svrstanim drugamo", "I98.2"),
    I98_8("Ostale specificirane bolesti cirkulacijskog sustava kod bolesti svrstanih drugamo", "I98.8"),
    I99("Ostale i nespecificirane bolesti cirkulacijskog sustava", "I99"),
    I99_0("Ostale i nespecificirane bolesti cirkulacijskog sustava", "I99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesI(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
