package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesQ {
    
    Q00("Anencefalija i slične malformacije", "Q00"),
    Q00_0("Anencefalus", "Q00.0"),
    Q00_1("Craniorachischisis", "Q00.1"),
    Q00_2("Iniencephalus", "Q00.2"),
    Q01("Encephalocela", "Q01"),
    Q01_0("Frontalna encephalocela", "Q01.0"),
    Q01_1("Nazofrontalna encephalocela", "Q01.1"),
    Q01_2("Okcipitalna encephalocela", "Q01.2"),
    Q01_8("Encephalocela ostalih sijela", "Q01.8"),
    Q01_9("Encephalocela, nespecificirana", "Q01.9"),
    Q02("Microcefalus", "Q02"),
    Q02_0("Microcefalus", "Q02.0"),
    Q03("Kongenitalni hidrocefalus", "Q03"),
    Q03_0("Malformacija Sylviusova akvedukta", "Q03.0"),
    Q03_1("Atrezija foramena Magendie i Luschka", "Q03.1"),
    Q03_8("Ostali kongenitalni hidrocefalus", "Q03.8"),
    Q03_9("Kongenitalni hidrocefalus, nespecificiran", "Q03.9"),
    Q04("Ostale prirođene malformacije mozga", "Q04"),
    Q04_0("Prirođene malformacije korpus kalozuma", "Q04.0"),
    Q04_1("Arhinencefalus", "Q04.1"),
    Q04_2("Holoprosencefalus", "Q04.2"),
    Q04_3("Ostali deformiteti sa smanjenjem mozga", "Q04.3"),
    Q04_4("Septo-optička displazija", "Q04.4"),
    Q04_5("Megaloencefalija", "Q04.5"),
    Q04_6("Prirođene cerebralne ciste", "Q04.6"),
    Q04_8("Ostale označene prirođene malformacije mozga", "Q04.8"),
    Q04_9("Prirođena malformacija mozga, nespecificirana", "Q04.9"),
    Q05("Spina bifida", "Q05"),
    Q05_0("Cervikalna spina bifida s hidrocefalusom", "Q05.0"),
    Q05_1("Torakalna spina bifida s hidrocefalusom", "Q05.1"),
    Q05_2("Lumbalna spina bifida s hidrocefalusom", "Q05.2"),
    Q05_3("Sakralna spina bifida s hidrocefalusom", "Q05.3"),
    Q05_4("Neoznačena spina bifida s hidrocefalusom", "Q05.4"),
    Q05_5("Cervikalna spina bifida bez hidrocefalusa", "Q05.5"),
    Q05_6("Torakalna spina bifida bez hidrocefalusa", "Q05.6"),
    Q05_7("Lumbalna spina bifida bez hidrocefalusa", "Q05.7"),
    Q05_8("Sakralna spina bifida bez hidrocefalusa", "Q05.8"),
    Q05_9("Spina bifida, nespecificirana", "Q05.9"),
    Q06("Ostale prirođene malformacije kralježnične moždine", "Q06"),
    Q06_0("Amijelija", "Q06.0"),
    Q06_1("Hipoplazija i displazija kralježnične moždine", "Q06.1"),
    Q06_2("Diastematomijelija", "Q06.2"),
    Q06_3("Ostale prirođene malformacije kaude ekvine", "Q06.3"),
    Q06_4("Hidromijelija", "Q06.4"),
    Q06_8("Ostale označene prirođene malformacije kralježnične moždine", "Q06.8"),
    Q06_9("Prirođena malformacija kralježnične moždine, nespecificirana", "Q06.9"),
    Q07("Ostale prirođene malformacije živčanog sustava", "Q07"),
    Q07_0("Arnold-Chiarijev sindrom", "Q07.0"),
    Q07_8("Ostale označene prirođene malformacije živčanog sustava", "Q07.8"),
    Q07_9("Prirođena malformacija živčanog sustava, nespecificirana", "Q07.9"),
    Q10("Prirođene malformacije očne vjeđe, suznog aparata i orbite", "Q10"),
    Q10_0("Prirođena ptoza", "Q10.0"),
    Q10_1("Prirođeni ektropion", "Q10.1"),
    Q10_2("Prirođeni entropion", "Q10.2"),
    Q10_3("Ostale prirođene malformacije očne vjeđe", "Q10.3"),
    Q10_4("Nepostojanje ili ageneza suznog aparata", "Q10.4"),
    Q10_5("Prirođena stenoza ili striktura suznog kanala", "Q10.5"),
    Q10_6("Ostale prirođene malformacije suznog aparata", "Q10.6"),
    Q10_7("Kongenitalna malformacija orbite", "Q10.7"),
    Q11("Anoftalmus, mikroftalmus i makroftalmus", "Q11"),
    Q11_0("Cistična očna jabučica", "Q11.0"),
    Q11_1("Ostali anoftalmus", "Q11.1"),
    Q11_2("Mikroftalmus", "Q11.2"),
    Q11_3("Makroftalmus", "Q11.3"),
    Q12("Prirođena malformacija leće", "Q12"),
    Q12_0("Prirođena katarakta", "Q12.0"),
    Q12_1("Prirođeno pomaknuće leće", "Q12.1"),
    Q12_2("Kolobom leće", "Q12.2"),
    Q12_3("Prirođena afakija", "Q12.3"),
    Q12_4("Sferofakija", "Q12.4"),
    Q12_8("Ostale prirođene malformacije leće", "Q12.8"),
    Q12_9("Prirođena malformacija leće, nespecificirana", "Q12.9"),
    Q13("Prirođena malformacija prednjeg segmenta oka", "Q13"),
    Q13_0("Kolobom šarenice", "Q13.0"),
    Q13_1("Nepostojanje šarenice", "Q13.1"),
    Q13_2("Ostale prirođene malformacije šarenice", "Q13.2"),
    Q13_3("Prirođeno kornealno zamućenje", "Q13.3"),
    Q13_4("Ostale prirođene kornealne malformacije", "Q13.4"),
    Q13_5("Plava bjeloočnica", "Q13.5"),
    Q13_8("Druge prirođene malformacije prednjeg segmenta oka", "Q13.8"),
    Q13_9("Prirođena malformacija prednjeg segmenta oka, nespecificirana", "Q13.9"),
    Q14("Prirođene malformacije stražnjeg segmenta oka", "Q14"),
    Q14_0("Prirođena malformacija staklovine", "Q14.0"),
    Q14_1("Prirođena malformacija mrežnice", "Q14.1"),
    Q14_2("Prirođena malformacija optičkog diska", "Q14.2"),
    Q14_3("Prirođena malformacija žilnice", "Q14.3"),
    Q14_8("Ostale prirođene malformacije stražnjeg segmenta oka", "Q14.8"),
    Q14_9("Prirođena malformacija stražnjeg segmenta oka, nespecificirana", "Q14.9"),
    Q15("Ostale prirođene malformacije oka", "Q15"),
    Q15_0("Prirođeni glaukom", "Q15.0"),
    Q15_8("Ostale označene prirođene malformacije oka", "Q15.8"),
    Q15_9("Prirođena malformacija oka, nespecificirana", "Q15.9"),
    Q16("Prirođene malformacije uha koje uzrokuju oštećenje sluha", "Q16"),
    Q16_0("Prirođeno nepostojanje ušne školjke (aurikule)", "Q16.0"),
    Q16_1("Prirođeno nepostojanje, atrezija ili striktura slušnog kanala (vanjskog)", "Q16.1"),
    Q16_2("Nepostojanje Eustachijeve tube", "Q16.2"),
    Q16_3("Prirođena malformacija ušnih koščica", "Q16.3"),
    Q16_4("Ostale prirođene malformacije srednjeg uha", "Q16.4"),
    Q16_5("Prirođena malformacija unutrašnjeg uha", "Q16.5"),
    Q16_9("Prirođena malformacija uha koja uzrokuje oštećenje sluha, nespecificirana", "Q16.9"),
    Q17("Ostale prirođene malformacije uha", "Q17"),
    Q17_0("Prekobrojna ušna školjka", "Q17.0"),
    Q17_1("Macrotia", "Q17.1"),
    Q17_2("Microtia", "Q17.2"),
    Q17_3("Ostalo izobličeno uho", "Q17.3"),
    Q17_4("Krivo smješteno uho", "Q17.4"),
    Q17_5("Stršeće uho", "Q17.5"),
    Q17_8("Ostale označene prirođene malformacije uha", "Q17.8"),
    Q17_9("Prirođena malformacija uha, nespecificirana", "Q17.9"),
    Q18("Ostale prirođene malformacije lica i vrata", "Q18"),
    Q18_0("Sinus, fistula i cista škržne pukotine", "Q18.0"),
    Q18_1("Preaurikularni sinus i cista", "Q18.1"),
    Q18_2("Ostale malformacije škržnih pukotina", "Q18.2"),
    Q18_3("Nabor vrata", "Q18.3"),
    Q18_4("Macrostomia", "Q18.4"),
    Q18_5("Microstomia", "Q18.5"),
    Q18_6("Macrocheilia", "Q18.6"),
    Q18_7("Microcheilia", "Q18.7"),
    Q18_8("Ostale označene prirođene malformacije lica i vrata", "Q18.8"),
    Q18_9("Prirođena malformacija lica i vrata, nespecificirana", "Q18.9"),
    Q20("Prirođene malformacije srčanih komora i srčanih spojeva", "Q20"),
    Q20_0("Truncus arteriosus communis", "Q20.0"),
    Q20_1("Dvostruki izlaz iz desne komore", "Q20.1"),
    Q20_2("Dvostruki izlaz iz lijeve komore", "Q20.2"),
    Q20_3("Nesklad ventrikuloarterijalnog spoja", "Q20.3"),
    Q20_4("Komora s dvostrukim ulazom", "Q20.4"),
    Q20_5("Nesklad atrioventrikularnoga spoja", "Q20.5"),
    Q20_6("Izomerizam atrijalnih privjesaka", "Q20.6"),
    Q20_8("Ostale prirođene malformacije srčanih komora i spojeva", "Q20.8"),
    Q20_9("Prirođena malformacija srčanih komora i spojeva, nespecificirana", "Q20.9"),
    Q21("Prirođene malformacije srčanih septuma", "Q21"),
    Q21_0("Defekt ventrikularnog septuma", "Q21.0"),
    Q21_1("Defekt atrijalnog septuma", "Q21.1"),
    Q21_2("Defekt atrioventrikularnog septuma", "Q21.2"),
    Q21_3("Fallotova tetralogija", "Q21.3"),
    Q21_4("Aortopulmonalni septalni defekt", "Q21.4"),
    Q21_8("Ostale prirođene malformacije srčanog septuma", "Q21.8"),
    Q21_9("Prirođena malformacija srčanog septuma, nespecificirana", "Q21.9"),
    Q22("Prirođene malformacije pulmonalnih i trikuspidalnih valvula", "Q22"),
    Q22_0("Atrezija pulmonalne valvule", "Q22.0"),
    Q22_1("Prirođena stenoza pulmonalne valvule", "Q22.1"),
    Q22_2("Prirođena insuficijencija pulmonalne valvule", "Q22.2"),
    Q22_3("Ostale prirođene malformacije pulmonalne valvule", "Q22.3"),
    Q22_4("Prirođena trikuspidalna stenoza", "Q22.4"),
    Q22_5("Ebsteinova anomalija", "Q22.5"),
    Q22_6("Sindrom hipoplastičnoga desnog srca", "Q22.6"),
    Q22_8("Ostale prirođene malformacije trikuspidalne valvule", "Q22.8"),
    Q22_9("Prirođena malformacija trikuspidalne valvule, nespecificirana", "Q22.9"),
    Q23("Prirođene malformacije aortalnih i mitralnih valvula", "Q23"),
    Q23_0("Prirođena stenoza aortalne valvule", "Q23.0"),
    Q23_1("Prirođena insuficijencija aortalne valvule", "Q23.1"),
    Q23_2("Prirođena mitralna stenoza", "Q23.2"),
    Q23_3("Prirođena mitralna insuficijencija", "Q23.3"),
    Q23_4("Sindrom hipoplastičnoga lijevog srca", "Q23.4"),
    Q23_8("Ostale prirođene malformacije aortalnih i mitralnih valvula", "Q23.8"),
    Q23_9("Prirođena malformacija aortalnih i mitralnih valvula, nespecificirana", "Q23.9"),
    Q24("Ostale prirođene malformacije srca", "Q24"),
    Q24_0("Dekstrokardija", "Q24.0"),
    Q24_1("Laevocardia", "Q24.1"),
    Q24_2("Cor triatriatum", "Q24.2"),
    Q24_3("Stenoza pulmonalnog infundibuluma", "Q24.3"),
    Q24_4("Prirođena subaortalna stenoza", "Q24.4"),
    Q24_5("Malformacija koronarnih žila", "Q24.5"),
    Q24_6("Prirođeni srčani blok", "Q24.6"),
    Q24_8("Ostale označene prirođene malformacije srca", "Q24.8"),
    Q24_9("Prirođena malformacija srca, nespecificirana", "Q24.9"),
    Q25("Prirođene malformacije velikih arterija", "Q25"),
    Q25_0("Otvoren ductus arteriosus", "Q25.0"),
    Q25_1("Koarktacija aorte", "Q25.1"),
    Q25_2("Atrezija aorte", "Q25.2"),
    Q25_3("Stenoza aorte", "Q25.3"),
    Q25_4("Ostale prirođene malformacije aorte", "Q25.4"),
    Q25_5("Atrezija pulmonalne arterije", "Q25.5"),
    Q25_6("Stenoza pulmonalne arterije", "Q25.6"),
    Q25_7("Ostale prirođene malformacije pulmonalne arterije", "Q25.7"),
    Q25_8("Ostale prirođene malformacije velikih arterija", "Q25.8"),
    Q25_9("Prirođena malformacija velikih arterija, nespecificirana", "Q25.9"),
    Q26("Prirođene malformacije velikih vena", "Q26"),
    Q26_0("Prirođena stenoza šuplje vene", "Q26.0"),
    Q26_1("Postojeća lijeva gornja šuplja vena", "Q26.1"),
    Q26_2("Potpuna anomalija povezivanja plućnih vena", "Q26.2"),
    Q26_3("Djelomična anomalija povezivanja plućnih vena", "Q26.3"),
    Q26_4("Anomalija povezivanja plućnih vena, neoznačena", "Q26.4"),
    Q26_5("Anomalija povezivanja portalne vene", "Q26.5"),
    Q26_6("Fistula portalne vene - hepatične arterije", "Q26.6"),
    Q26_8("Ostale prirođene malformacije velikih vena", "Q26.8"),
    Q26_9("Prirođena malformacija velike vene, nespecificirana", "Q26.9"),
    Q27("Ostale prirođene malformacije perifernoga cirkulacijskog sustava", "Q27"),
    Q27_0("Prirođeno nepostojanje ili hipoplazija umbilikalne arterije", "Q27.0"),
    Q27_1("Prirođena stenoza bubrežne arterije", "Q27.1"),
    Q27_2("Ostale prirođene malformacije bubrežne arterije", "Q27.2"),
    Q27_3("Periferna arterio-venska malformacija", "Q27.3"),
    Q27_4("Prirođena flebektazija", "Q27.4"),
    Q27_8("Ostale označene kongenitalne malformacije perifernoga cirkulacijskog sustava", "Q27.8"),
    Q27_9("Prirođena malformacija perifernoga cirkulacijskog sustava, nespecificirana", "Q27.9"),
    Q28("Ostale prirođene malformacije cirkulacijskog sustava", "Q28"),
    Q28_0("Arterio-venska malformacija precerebralnih žila", "Q28.0"),
    Q28_1("Ostale malformacije precerebralnih žila", "Q28.1"),
    Q28_2("Arterio-venska malformacija cerebralnih žila", "Q28.2"),
    Q28_3("Ostale malformacije cerebralnih žila", "Q28.3"),
    Q28_8("Ostale označene prirođene malformacije cirkulacijskog sustava", "Q28.8"),
    Q28_9("Prirođena malformacija cirkulacijskog sustava, nespecificirana", "Q28.9"),
    Q30("Prirođene malformacije nosa", "Q30"),
    Q30_0("Atrezija hoane", "Q30.0"),
    Q30_1("Ageneza i nerazvijenost nosa", "Q30.1"),
    Q30_2("Rascijepljen, urezan i rascijepljen nos", "Q30.2"),
    Q30_3("Prirođeno perforiran nosni septum", "Q30.3"),
    Q30_8("Ostale prirođene malformacije nosa", "Q30.8"),
    Q30_9("Prirođena malformacija nosa, nespecificirana", "Q30.9"),
    Q31("Prirođene malformacije grkljana", "Q31"),
    Q31_0("Nabor grkljana", "Q31.0"),
    Q31_1("Prirođena subglotična stenoza", "Q31.1"),
    Q31_2("Laringealna hipoplazija", "Q31.2"),
    Q31_3("Laringokela", "Q31.3"),
    Q31_4("Prirođeni laringealni stridor", "Q31.4"),
    Q31_8("Ostale prirođene malformacije grkljana", "Q31.8"),
    Q31_9("Prirođena malformacija grkljana, nespecificirana", "Q31.9"),
    Q32("Prirođene malformacije traheje i bronha", "Q32"),
    Q32_0("Prirođena traheomalacija", "Q32.0"),
    Q32_1("Ostale prirođene malformacije traheje", "Q32.1"),
    Q32_2("Prirođena bronhomalacija", "Q32.2"),
    Q32_3("Prirođena stenoza bronha", "Q32.3"),
    Q32_4("Ostale prirođene malformacije bronha", "Q32.4"),
    Q33("Prirođene malformacije pluća", "Q33"),
    Q33_0("Prirođena cistična pluća", "Q33.0"),
    Q33_1("Prekobrojni plućni režanj", "Q33.1"),
    Q33_2("Sekvestrirana pluća", "Q33.2"),
    Q33_3("Ageneza pluća", "Q33.3"),
    Q33_4("Prirođene bronhiektazije", "Q33.4"),
    Q33_5("Ektopično tkivo u plućima", "Q33.5"),
    Q33_6("Hipoplazija i displazija pluća", "Q33.6"),
    Q33_8("Ostale prirođene malformacije pluća", "Q33.8"),
    Q33_9("Prirođena malformacija pluća, nespecificirana", "Q33.9"),
    Q34("Ostale prirođene malformacije dišnog sustava", "Q34"),
    Q34_0("Anomalija pleure", "Q34.0"),
    Q34_1("Prirođena cista medijastinuma", "Q34.1"),
    Q34_8("Ostale označene prirođene malformacije dišnog sustava", "Q34.8"),
    Q34_9("Prirođena malformacija dišnog sustava, nespecificirana", "Q34.9"),
    Q35("Rascijepljeno nepce", "Q35"),
    Q35_0("Rascijepljeno tvrdo nepce, obostrano", "Q35.0"),
    Q35_1("Rascijepljeno tvrdo nepce, jednostrano", "Q35.1"),
    Q35_2("Rascijepljeno meko nepce, obostrano", "Q35.2"),
    Q35_3("Rascijepljeno meko nepce, jednostrano", "Q35.3"),
    Q35_4("Rascijepljeno tvrdo nepce s rascijepljenim mekim nepcem, obostrano", "Q35.4"),
    Q35_5("Rascijepljeno tvrdo nepce s rascijepljenim mekim nepcem, jednostrano", "Q35.5"),
    Q35_6("Rascijepljeno nepce, medijalno", "Q35.6"),
    Q35_7("Rascijepljena resica (uvula)", "Q35.7"),
    Q35_8("Rascijepljeno nepce, nespecificirano, obostrano", "Q35.8"),
    Q35_9("Rascijepljeno nepce, nespecificirano, jednostrano", "Q35.9"),
    Q36("Rascijepljena usna", "Q36"),
    Q36_0("Rascijepljena usna, obostrano", "Q36.0"),
    Q36_1("Rascijepljena usna, medijalno", "Q36.1"),
    Q36_9("Rascijepljena usna, jednostrano", "Q36.9"),
    Q37("Rascijepljeno nepce s rascijepljenom usnom", "Q37"),
    Q37_0("Rascijepljeno tvrdo nepce s rascijepljenom usnom, obostrano", "Q37.0"),
    Q37_1("Rascijepljeno tvrdo nepce s rascijepljenom usnom, jednostrano", "Q37.1"),
    Q37_2("Rascijepljeno meko nepce s rascijepljenom usnom, obostrano", "Q37.2"),
    Q37_3("Rascijepljeno meko nepce s rascijepljenom usnom, jednostrano", "Q37.3"),
    Q37_4("Rascijepljeno tvrdo i meko nepce s rascijepljenom usnom, obostrano", "Q37.4"),
    Q37_5("Rascijepljeno tvrdo i meko nepce s rascijepljenom usnom, jednostrano", "Q37.5"),
    Q37_8("Nespecificirano rascijepljeno nepce s rascijepljenom usnom, obostrano", "Q37.8"),
    Q37_9("Nespecificirano rascijepljeno nepce s rascijepljenom usnom, jednostrano", "Q37.9"),
    Q38("Ostale prirođene malformacije jezika, usta i ždrijela", "Q38"),
    Q38_0("Prirođene malformacije usana, neklasificirane na drugom mjestu", "Q38.0"),
    Q38_1("Ankiloglosija", "Q38.1"),
    Q38_2("Makroglosija", "Q38.2"),
    Q38_3("Ostale prirođene malformacije jezika", "Q38.3"),
    Q38_4("Prirođene malformacije žlijezda slinovnica i kanala", "Q38.4"),
    Q38_5("Prirođene malformacije nepca, nesvrstane drugamo", "Q38.5"),
    Q38_6("Ostale prirođene malformacije usta", "Q38.6"),
    Q38_7("Faringealna vreća", "Q38.7"),
    Q38_8("Ostale prirođene malformacije ždrijela", "Q38.8"),
    Q39("Prirođene malformacije jednjaka", "Q39"),
    Q39_0("Atrezija jednjaka bez fistule", "Q39.0"),
    Q39_1("Atrezija jednjaka s traheoezofagealnom fistulom", "Q39.1"),
    Q39_2("Prirođena traheoezofagealna fistula bez atrezije", "Q39.2"),
    Q39_3("Prirođena stenoza i striktura jednjaka", "Q39.3"),
    Q39_4("Nabor jednjaka", "Q39.4"),
    Q39_5("Prirođena dilatacija jednjaka", "Q39.5"),
    Q39_6("Divertikul jednjaka", "Q39.6"),
    Q39_8("Ostale prirođene malformacije jednjaka", "Q39.8"),
    Q39_9("Prirođena malformacija jednjaka, nespecificirana", "Q39.9"),
    Q40("Ostale prirođene malformacije gornjega probavnog trakta", "Q40"),
    Q40_0("Prirođena hipertrofična stenoza pilorusa", "Q40.0"),
    Q40_1("Prirođena hijatalna hernija", "Q40.1"),
    Q40_2("Ostale označene prirođene malformacije želuca", "Q40.2"),
    Q40_3("Prirođena malformacija želuca, nespecificirana", "Q40.3"),
    Q40_8("Ostale označene prirođene malformacije gornjega probavnog trakta", "Q40.8"),
    Q40_9("Prirođena malformacija gornjega probavnog trakta, nespecificirana", "Q40.9"),
    Q41("Prirođeno nepostojanje, atrezija i stenoza tankoga crijeva", "Q41"),
    Q41_0("Prirođeno nepostojanje, atrezija i stenoza dvanaesnika", "Q41.0"),
    Q41_1("Prirođeno nepostojanje, atrezija i stenoza jejunuma", "Q41.1"),
    Q41_2("Prirođeno nepostojanje, atrezija i stenoza ileuma", "Q41.2"),
    Q41_8("Prirođeno nepostojanje, atrezija i stenoza ostalih označenih dijelova tankoga crijeva", "Q41.8"),
    Q41_9("Prirođeno nepostojanje, atrezija i stenoza tankoga crijeva, dio nespecificiran", "Q41.9"),
    Q42("Prirođeno nepostojanje, atrezija i stenoza debeloga crijeva", "Q42"),
    Q42_0("Prirođeno nepostojanje, atrezija i stenoza rektuma s fistulom", "Q42.0"),
    Q42_1("Prirođeno nepostojanje, atrezija i stenoza rektuma bez fistule", "Q42.1"),
    Q42_2("Prirođeno nepostojanje, atrezija i stenoza anusa s fistulom", "Q42.2"),
    Q42_3("Prirođeno nepostojanje, atrezija i stenoza anusa bez fistule", "Q42.3"),
    Q42_8("Prirođeno nepostojanje, atrezija i stenoza drugih dijelova debeloga crijeva", "Q42.8"),
    Q42_9("Prirođeno nepostojanje, atrezija i stenoza debeloga crijeva, dio nespecificiran", "Q42.9"),
    Q43("Ostale prirođene malformacije crijeva", "Q43"),
    Q43_0("Meckelov divertikul", "Q43.0"),
    Q43_1("Hirschsprungova bolest", "Q43.1"),
    Q43_2("Ostali prirođeni funkcionalni poremećaji kolona", "Q43.2"),
    Q43_3("Prirođene malformacije u fiksaciji crijeva", "Q43.3"),
    Q43_4("Duplicitet crijeva", "Q43.4"),
    Q43_5("Ektopični anus", "Q43.5"),
    Q43_6("Prirođena fistula rektuma i anusa", "Q43.6"),
    Q43_7("Cloaca persistens", "Q43.7"),
    Q43_8("Ostale označene prirođene malformacije crijeva", "Q43.8"),
    Q43_9("Prirođena malformacija crijeva, nespecificirana", "Q43.9"),
    Q44("Prirođene malformacije žučnoga mjehura, žučnih vodova i jetre", "Q44"),
    Q44_0("Ageneza, aplazija i hipoplazija žučnoga mjehura", "Q44.0"),
    Q44_1("Ostale prirođene malformacije žučnoga mjehura", "Q44.1"),
    Q44_2("Atrezija žučnih vodova", "Q44.2"),
    Q44_3("Prirođena stenoza i striktura žučnih vodova", "Q44.3"),
    Q44_4("Koledokalna cista", "Q44.4"),
    Q44_5("Ostale prirođene malformacije žučnih vodova", "Q44.5"),
    Q44_6("Cistična bolest jetre", "Q44.6"),
    Q44_7("Ostale prirođene malformacije jetre", "Q44.7"),
    Q45("Ostale prirođene malformacije probavnog sustava", "Q45"),
    Q45_0("Ageneza, aplazija i hipoplazija pankreasa", "Q45.0"),
    Q45_1("Prstenasti pankreas", "Q45.1"),
    Q45_2("Prirođena cista pankreasa", "Q45.2"),
    Q45_3("Ostale prirođene malformacije gušterače i gušteračnih vodova", "Q45.3"),
    Q45_8("Ostale označene prirođene malformacije probavnog sustava", "Q45.8"),
    Q45_9("Prirođena malformacija probavnog sustava, nespecificirana", "Q45.9"),
    Q50("Prirođene malformacije jajnika, jajovoda i širokih ligamenata", "Q50"),
    Q50_0("Prirođeni nedostatak jajnika", "Q50.0"),
    Q50_1("Razvojna cista jajnika", "Q50.1"),
    Q50_2("Prirođena torzija jajnika", "Q50.2"),
    Q50_3("Ostale prirođene malformacije jajnika", "Q50.3"),
    Q50_4("Embrionalna cista jajovoda", "Q50.4"),
    Q50_5("Embrionalna cista širokog ligamenta", "Q50.5"),
    Q50_6("Ostale prirođene malformacije jajovoda i širokog ligamenta", "Q50.6"),
    Q51("Prirođene malformacije maternice i cerviksa", "Q51"),
    Q51_0("Agenezija i aplazija maternice", "Q51.0"),
    Q51_1("Dvostruka maternica s dvostrukim vratom (cerviksom) i rodnicom (vaginom)", "Q51.1"),
    Q51_2("Ostali dupliciteti maternice", "Q51.2"),
    Q51_3("Dvoroga maternica", "Q51.3"),
    Q51_4("Unikornalna maternica", "Q51.4"),
    Q51_5("Agenezija i aplazija cerviksa", "Q51.5"),
    Q51_6("Embrionalna cista cerviksa", "Q51.6"),
    Q51_7("Prirođene fistule između maternice te probavnoga i urinarnoga trakta", "Q51.7"),
    Q51_8("Ostale malformacije maternice i cerviksa", "Q51.8"),
    Q51_9("Prirođena malformacija maternice i cerviksa, nespecificirana", "Q51.9"),
    Q52("Ostale prirođene malformacije ženskih spolnih organa", "Q52"),
    Q52_0("Prirođeni nedostatak rodnice", "Q52.0"),
    Q52_1("Dvostruka vagina", "Q52.1"),
    Q52_2("Prirođena rektovaginalna fistula", "Q52.2"),
    Q52_3("Neperforirani himen", "Q52.3"),
    Q52_4("Ostale prirođene malformacije rodnice", "Q52.4"),
    Q52_5("Fuzija labija", "Q52.5"),
    Q52_6("Prirođena malformacija klitorisa", "Q52.6"),
    Q52_7("Ostale prirođene malformacije vulve", "Q52.7"),
    Q52_8("Ostale specificirane prirođene malformacije ženskih spolnih organa", "Q52.8"),
    Q52_9("Prirođena malformacija ženskih spolnih organa, nespecificirana", "Q52.9"),
    Q53("Nespušteni testis", "Q53"),
    Q53_0("Ektopija testisa", "Q53.0"),
    Q53_1("Nespušteni testis, unilateralno", "Q53.1"),
    Q53_2("Nespušteni testis, bilateralno", "Q53.2"),
    Q53_9("Nespušteni testis, nespecificirano", "Q53.9"),
    Q54("Hipospadija", "Q54"),
    Q54_0("Hipospadija, balanička", "Q54.0"),
    Q54_1("Hipospadija, penisna", "Q54.1"),
    Q54_2("Hipospadija, penoskrotalna", "Q54.2"),
    Q54_3("Hipospadija, perinealna", "Q54.3"),
    Q54_4("Kongenitalne korde", "Q54.4"),
    Q54_8("Ostale hipospadije", "Q54.8"),
    Q54_9("Hipospadija, nespecificirana", "Q54.9"),
    Q55("Ostale prirođene malformacije muških spolnih organa", "Q55"),
    Q55_0("Nedostatak ili aplazija testisa", "Q55.0"),
    Q55_1("Hipoplazija testisa i skrotuma", "Q55.1"),
    Q55_2("Ostale prirođene malformacije testisa i skrotuma", "Q55.2"),
    Q55_3("Atrezija sjemenovoda", "Q55.3"),
    Q55_4("Ostale prirođene malformacije sjemenovoda, epididimisa, sjemenih mjehurića i prostate", "Q55.4"),
    Q55_5("Prirođeni nedostatak i aplazija penisa", "Q55.5"),
    Q55_6("Ostale prirođene malformacije penisa", "Q55.6"),
    Q55_8("Ostale specificirane prirođene malformacije muških spolnih organa", "Q55.8"),
    Q55_9("Prirođena malformacija muških spolnih organa, nespecificirana", "Q55.9"),
    Q56("Neodređeni spol i pseudohermafroditizam", "Q56"),
    Q56_0("Hermafroditizam, nesvrstan drugamo", "Q56.0"),
    Q56_1("Muški pseudohermafroditizam, nesvrstan drugamo", "Q56.1"),
    Q56_2("Ženski pseudohermafroditizam, nesvrstan drugamo", "Q56.2"),
    Q56_3("Pseudohermafroditizam, nespecificiran", "Q56.3"),
    Q56_4("Neodređeni spol, nespecificiran", "Q56.4"),
    Q60("Agenezija bubrega i drugi redukcijski nedostaci bubrega", "Q60"),
    Q60_0("Agenezija bubrega, jednostrana", "Q60.0"),
    Q60_1("Agenezija bubrega, obostrana", "Q60.1"),
    Q60_2("Agenezija bubrega, nespecificirana", "Q60.2"),
    Q60_3("Hipoplazija bubrega, jednostrana", "Q60.3"),
    Q60_4("Hipoplazija bubrega, obostrana", "Q60.4"),
    Q60_5("Hipoplazija bubrega, nespecificirana", "Q60.5"),
    Q60_6("Potterov sindrom", "Q60.6"),
    Q61("Cistična bubrežna bolest", "Q61"),
    Q61_0("Prirođena pojedinačna bubrežna cista", "Q61.0"),
    Q61_1("Policistični bubreg, infantilnog tipa", "Q61.1"),
    Q61_2("Policistični bubreg, adultnog tipa", "Q61.2"),
    Q61_3("Policistični bubreg, nespecificiran", "Q61.3"),
    Q61_4("Displazija bubrega", "Q61.4"),
    Q61_5("Medularni cistični bubreg", "Q61.5"),
    Q61_8("Ostale cistične bolesti bubrega", "Q61.8"),
    Q61_9("Cistična bolest bubrega, nespecificirana", "Q61.9"),
    Q62("Prirođeni opstruktivni defekti bubrežne čašice i prirođene malformacije uretera", "Q62"),
    Q62_0("Prirođena hidronefroza", "Q62.0"),
    Q62_1("Atrezija ili stenoza uretera", "Q62.1"),
    Q62_2("Prirođeni megaureter", "Q62.2"),
    Q62_3("Ostali opstruktivni defekti bubrežne čašice i uretera", "Q62.3"),
    Q62_4("Agenezija uretera", "Q62.4"),
    Q62_5("Dvostruki ureter", "Q62.5"),
    Q62_6("Pogrešan položaj uretera", "Q62.6"),
    Q62_7("Prirođeni veziko-uretero-renalni refluks", "Q62.7"),
    Q62_8("Ostale prirođene malformacije uretera", "Q62.8"),
    Q63("Ostale prirođene malformacije bubrega", "Q63"),
    Q63_0("Akcesorni bubreg", "Q63.0"),
    Q63_1("Lobulirani, spojeni i potkovasti bubreg", "Q63.1"),
    Q63_2("Ektopični bubreg", "Q63.2"),
    Q63_3("Hiperplastični i divovski bubreg", "Q63.3"),
    Q63_8("Ostale specificirane prirođene malformacije bubrega", "Q63.8"),
    Q63_9("Prirođena malformacija bubrega, nespecificirana", "Q63.9"),
    Q64("Ostale prirođene malformacije urinarnog sustava", "Q64"),
    Q64_0("Epispadija", "Q64.0"),
    Q64_1("Ekstrofija mokraćnoga mjehura", "Q64.1"),
    Q64_2("Prirođene stražnje uretralne valvule", "Q64.2"),
    Q64_3("Ostale atrezije i stenoze uretre i vrata mokraćnoga mjehura", "Q64.3"),
    Q64_4("Malformacije urahusa", "Q64.4"),
    Q64_5("Prirođeni nedostatak mokraćnoga mjehura i uretre", "Q64.5"),
    Q64_6("Prirođeni divertikul mokraćnoga mjehura", "Q64.6"),
    Q64_7("Ostale prirođene malformacije mokraćnoga mjehura i uretre", "Q64.7"),
    Q64_8("Ostale specificirane prirođene malformacije urinarnog sustava", "Q64.8"),
    Q64_9("Prirođena malformacija urinarnog sustava, nespecificirana", "Q64.9"),
    Q65("Prirođeni deformiteti kuka", "Q65"),
    Q65_0("Prirođena dislokacija kuka, jednostrana", "Q65.0"),
    Q65_1("Prirođena dislokacija kuka, obostrana", "Q65.1"),
    Q65_2("Prirođena dislokacija kuka, nespecificirana", "Q65.2"),
    Q65_3("Prirođena subluksacija kuka, jednostrana", "Q65.3"),
    Q65_4("Prirođena subluksacija kuka, obostrana", "Q65.4"),
    Q65_5("Prirođena subluksacija kuka, nespecificirana", "Q65.5"),
    Q65_6("Nestabilan kuk", "Q65.6"),
    Q65_8("Ostali prirođeni deformiteti kuka", "Q65.8"),
    Q65_9("Prirođeni deformitet kuka, nespecificiran", "Q65.9"),
    Q66("Prirođeni deformiteti stopala", "Q66"),
    Q66_0("Ekvinovarus stopala", "Q66.0"),
    Q66_1("Kalkaneovarus stopala", "Q66.1"),
    Q66_2("Metatarzus varus", "Q66.2"),
    Q66_3("Ostali prirođeni varusni deformiteti stopala", "Q66.3"),
    Q66_4("Kalkaneovalgus stopala", "Q66.4"),
    Q66_5("Prirođeno spušteno stopalo", "Q66.5"),
    Q66_6("Ostali prirođeni valgusni deformiteti stopala", "Q66.6"),
    Q66_7("Pes cavus", "Q66.7"),
    Q66_8("Ostali prirođeni deformiteti stopala", "Q66.8"),
    Q66_9("Prirođeni deformitet stopala, nespecificirani", "Q66.9"),
    Q67("Prirođeni mišićno-koštani deformiteti glave, lica, kralježnice i prsnog koša", "Q67"),
    Q67_0("Asimetrija lica", "Q67.0"),
    Q67_1("Kompresija lica", "Q67.1"),
    Q67_2("Dolihocefalija", "Q67.2"),
    Q67_3("Plagiocefalija", "Q67.3"),
    Q67_4("Ostali prirođeni deformiteti lubanje, lica i čeljusti", "Q67.4"),
    Q67_5("Prirođena deformacija kralježnice", "Q67.5"),
    Q67_6("Pectus excavatum", "Q67.6"),
    Q67_7("Pectus carinatum", "Q67.7"),
    Q67_8("Ostali prirođeni deformiteti prsnog koša", "Q67.8"),
    Q68("Ostali prirođeni mišićno-koštani deformiteti", "Q68"),
    Q68_0("Prirođeni deformitet sternokleidomastoidnog mišića", "Q68.0"),
    Q68_1("Prirođena deformacija šake", "Q68.1"),
    Q68_2("Prirođena deformacija koljena", "Q68.2"),
    Q68_3("Prirođeno iskrivljena bedrena kost", "Q68.3"),
    Q68_4("Prirođeno iskrivljenje tibije i fibule", "Q68.4"),
    Q68_5("Prirođeno iskrivljenje dugih kostiju nogu, nespecificirano", "Q68.5"),
    Q68_8("Ostale specificirane prirođene mišićno-koštane deformacije", "Q68.8"),
    Q69("Polidaktilija", "Q69"),
    Q69_0("Akcesorni prst (prsti)", "Q69.0"),
    Q69_1("Akcesorni palac (palci)", "Q69.1"),
    Q69_2("Akcesorni nožni prst (prsti)", "Q69.2"),
    Q69_9("Polidaktilija, nespecificirana", "Q69.9"),
    Q70("Sindaktilija", "Q70"),
    Q70_0("Srašteni prsti na šaci", "Q70.0"),
    Q70_1("Plivaća kožica (šake)", "Q70.1"),
    Q70_2("Srašteni nožni prsti", "Q70.2"),
    Q70_3("Plivaća kožica (stopala)", "Q70.3"),
    Q70_4("Polisindaktilija", "Q70.4"),
    Q70_9("Sindaktilija, nespecificirana", "Q70.9"),
    Q71("Redukcijski defekti ruke", "Q71"),
    Q71_0("Prirođeni kompletni nedostatak ruke(u)", "Q71.0"),
    Q71_1("Prirođeni nedostatak nadlaktice i podlaktice s razvijenom šakom", "Q71.1"),
    Q71_2("Prirođeni nedostatak i podlaktice i šake", "Q71.2"),
    Q71_3("Prirođeni nedostatak šake i prsta (prstiju)", "Q71.3"),
    Q71_4("Longitudinalni redukcijski defekt radijusa", "Q71.4"),
    Q71_5("Longitudinalni redukcijski defekt ulne", "Q71.5"),
    Q71_6("Šaka poput jastogovih kliješta", "Q71.6"),
    Q71_8("Ostali redukcijski defekti ruke(u)", "Q71.8"),
    Q71_9("Redukcijski defekt ruke(u), nespecificiran", "Q71.9"),
    Q72("Redukcijski defekt noge", "Q72"),
    Q72_0("Prirođeni kompletni nedostatak noge(u)", "Q72.0"),
    Q72_1("Prirođeni nedostatak natkoljenice i potkoljenice s razvijenim stopalom", "Q72.1"),
    Q72_2("Prirođeni nedostatak i potkoljenice i stopala", "Q72.2"),
    Q72_3("Prirođeni nedostatak stopala i prsta (prstiju)", "Q72.3"),
    Q72_4("Longitudinalni redukcijski defekt femura", "Q72.4"),
    Q72_5("Longitudinalni redukcijski defekt tibije", "Q72.5"),
    Q72_6("Longitudinalni redukcijski defekt fibule", "Q72.6"),
    Q72_7("Rascijepljeno stopalo", "Q72.7"),
    Q72_8("Ostali redukcijski defekti noge(u)", "Q72.8"),
    Q72_9("Redukcijski defekt noge(u), nespecificiran", "Q72.9"),
    Q73("Redukcijski defekt nespecificiranog uda", "Q73"),
    Q73_0("Prirođeni nedostatak nespecificiranog(ih) uda(ova)", "Q73.0"),
    Q73_1("Fokomelija, nespecificiranog(ih) uda(ova)", "Q73.1"),
    Q73_8("Ostali redukcijski defekti nespecificiranog(ih) uda(ova)", "Q73.8"),
    Q74("Ostale prirođene malformacije ekstremiteta", "Q74"),
    Q74_0("Ostale prirođene malformacije ruke(u) uključujući i rameni pojas", "Q74.0"),
    Q74_1("Prirođena malformacija koljena", "Q74.1"),
    Q74_2("Ostale prirođene malformacije noge(u) uključujući zdjelični pojas", "Q74.2"),
    Q74_3("Arthrogryposis multiplex congenita", "Q74.3"),
    Q74_8("Ostale specificirane prirođene malformacije udova", "Q74.8"),
    Q74_9("Nespecificirana prirođena malformacija udova", "Q74.9"),
    Q75("Ostale prirođene malformacije kostiju lubanje i lica", "Q75"),
    Q75_0("Kraniosinostoza", "Q75.0"),
    Q75_1("Kraniofacijalna disostoza", "Q75.1"),
    Q75_2("Hipertelorizam", "Q75.2"),
    Q75_3("Makrocefalija", "Q75.3"),
    Q75_4("Mandibulofacijalna disostoza", "Q75.4"),
    Q75_5("Okulomandibularna disostoza", "Q75.5"),
    Q75_8("Ostale specificirane prirođene malformacije kostiju lubanje i lica", "Q75.8"),
    Q75_9("Prirođena malformacija kostiju lubanje i lica, nespecificirana", "Q75.9"),
    Q76("Prirođene malformacije kralježnice i prsnog koša (koštanog dijela)", "Q76"),
    Q76_0("Spina bifida occulta", "Q76.0"),
    Q76_1("Klippel-Feilov sindrom", "Q76.1"),
    Q76_2("Prirođena spondilolisteza", "Q76.2"),
    Q76_3("Prirođena skolioza zbog prirođene koštane malformacije", "Q76.3"),
    Q76_4("Ostale prirođene malformacije kralježnice, nevezane uz skoliozu", "Q76.4"),
    Q76_5("Vratno rebro", "Q76.5"),
    Q76_6("Ostale prirođene malformacije rebara", "Q76.6"),
    Q76_7("Prirođena malformacija sternuma", "Q76.7"),
    Q76_8("Ostale prirođene malformacije koštanog dijela prsnog koša", "Q76.8"),
    Q76_9("Prirođena malformacija koštanog dijela prsnog koša, nespecificirana", "Q76.9"),
    Q77("Osteohondrodisplazija s defektima rasta tubularnih kostiju i kralježnice", "Q77"),
    Q77_0("Ahondrogeneza", "Q77.0"),
    Q77_1("Tanatoforički niski rast", "Q77.1"),
    Q77_2("Sindrom kratkog rebra", "Q77.2"),
    Q77_3("Točkasta hondrodisplazija", "Q77.3"),
    Q77_4("Ahondroplazija", "Q77.4"),
    Q77_5("Diastrofična displazija", "Q77.5"),
    Q77_6("Ellis-van Creveldov sindrom (hondroektodermalna displazija)", "Q77.6"),
    Q77_7("Spondiloepifizealna displazija", "Q77.7"),
    Q77_8("Ostala osteohondrodisplazija s defektima rasta tubularnih kostiju i kralježnice", "Q77.8"),
    Q77_9("Osteohondrodisplazija s defektima rasta tubularnih kostiju i kralježnice, nespecificirana", "Q77.9"),
    Q78("Ostale osteohondrodisplazije", "Q78"),
    Q78_0("Osteogenesis imperfecta", "Q78.0"),
    Q78_1("Poliostotička fibrozna displazija", "Q78.1"),
    Q78_2("Osteopetroza", "Q78.2"),
    Q78_3("Progresivna dijafizealna displazija", "Q78.3"),
    Q78_4("Enhondromatoza", "Q78.4"),
    Q78_5("Metafizealna displazija", "Q78.5"),
    Q78_6("Multipla prirođena egzostoza", "Q78.6"),
    Q78_8("Ostale specificirane osteohondrodisplazije", "Q78.8"),
    Q78_9("Osteohondrodisplazija, nespecificirana", "Q78.9"),
    Q79("Prirođene malformacije mišićno-koštanoga sustava, nesvrstane drugamo", "Q79"),
    Q79_0("Prirođena dijafragmalna hernija", "Q79.0"),
    Q79_1("Ostale prirođene malformacije ošita", "Q79.1"),
    Q79_2("Egzomfalos", "Q79.2"),
    Q79_3("Gastroshiza", "Q79.3"),
    Q79_4("Prune-belly sindrom", "Q79.4"),
    Q79_5("Ostale prirođene malformacije trbušne stijenke", "Q79.5"),
    Q79_6("Ehlers-Danlosov sindrom", "Q79.6"),
    Q79_8("Ostale prirođene malformacije mišićno-koštanog sustava", "Q79.8"),
    Q79_9("Prirođena malformacija mišićno-koštanog sustava, nespecificirana", "Q79.9"),
    Q80("Kongenitalna ihtioza", "Q80"),
    Q80_0("Obična ihtioza (ichtyosis vulgaris)", "Q80.0"),
    Q80_1("Ihtioza prenosiva kromosomom X", "Q80.1"),
    Q80_2("Lamelarna ihtioza", "Q80.2"),
    Q80_3("Prirođena bulozna ihtioziformna eritrodermija", "Q80.3"),
    Q80_4("Fetus poput harlekina", "Q80.4"),
    Q80_8("Ostale prirođene ihtioze", "Q80.8"),
    Q80_9("Prirođena ihtioza, nespecificirana", "Q80.9"),
    Q81("Bulozna epidermoliza", "Q81"),
    Q81_0("Epidermolitička bulozna epidermoliza (epidermolysis bullosa simplex)", "Q81.0"),
    Q81_1("Junkcijska bulozna epidermoliza (pidermolysis bullosa letalis) (Herlitzova bolest)", "Q81.1"),
    Q81_2("Distrofijska bulozna epidermoliza (epidermolysis bullosa dystrophica)", "Q81.2"),
    Q81_8("Druge bulozne epidermolize", "Q81.8"),
    Q81_9("Bulozna epidermoliza, nespecificirana", "Q81.9"),
    Q82("Ostale prirođene malformacije kože", "Q82"),
    Q82_0("Hereditarni limfedem", "Q82.0"),
    Q82_1("Pigmentna kseroderma", "Q82.1"),
    Q82_2("Mastocitoza", "Q82.2"),
    Q82_3("Incontinencija pigmenta (Bloch-Sulzbergerov sindrom)", "Q82.3"),
    Q82_4("Ektodermalna displazija (anhidrotična)", "Q82.4"),
    Q82_5("Prirođeni neneoplastični nevus", "Q82.5"),
    Q82_8("Ostale specificirane prirođene malformacije kože", "Q82.8"),
    Q82_9("Prirođena malformacija kože, nespecificirana", "Q82.9"),
    Q83("Prirođene malformacije dojki", "Q83"),
    Q83_0("Prirođeni nedostatak dojke s nedostatkom bradavice", "Q83.0"),
    Q83_1("Dodatna dojka", "Q83.1"),
    Q83_2("Nedostatak bradavice", "Q83.2"),
    Q83_3("Prekobrojna bradavica", "Q83.3"),
    Q83_8("Ostale prirođene malformacije dojke", "Q83.8"),
    Q83_9("Prirođena malformacija dojke, nespecificirana", "Q83.9"),
    Q84("Ostale prirođene malformacije tjelesnog omotača", "Q84"),
    Q84_0("Prirođena alopecija", "Q84.0"),
    Q84_1("Prirođene morfološke promjene kose, nesvrstane drugamo", "Q84.1"),
    Q84_2("Ostale prirođene malformacije kose", "Q84.2"),
    Q84_3("Anonihija", "Q84.3"),
    Q84_4("Prirođena leukonihija", "Q84.4"),
    Q84_5("Povećani i hipertrofični nokti", "Q84.5"),
    Q84_6("Ostale prirođene malformacije noktiju", "Q84.6"),
    Q84_8("Ostale specificirane prirođene malformacije tjelesnog omotača", "Q84.8"),
    Q84_9("Prirođena malformacija tjelesnog omotača, nespecificirana", "Q84.9"),
    Q85("Fakomatoza, nesvrstana drugamo", "Q85"),
    Q85_0("Neurofibromatoza (nemaligna)", "Q85.0"),
    Q85_1("Tuberozna skleroza", "Q85.1"),
    Q85_8("Ostale fakomatoze, nesvrstane drugamo", "Q85.8"),
    Q85_9("Fakomatoza, nespecificirana", "Q85.9"),
    Q86("Prirođeni malformacijski sindromi uvjetovani poznatim egzogenim čimbenicima, nesvrstani drugamo", "Q86"),
    Q86_0("Fetalni alkoholni sindrom (dismorfični)", "Q86.0"),
    Q86_1("Fetalni hidantoinski sindrom", "Q86.1"),
    Q86_2("Dismorfizam zbog varfarina", "Q86.2"),
    Q86_8("Ostali prirođeni malformacijski sindromi uvjetovani poznatim egzogenim uzrocima", "Q86.8"),
    Q87("Ostali specificirani prirođeni malformacijski sindromi koji se očituju u više organskih sustava", "Q87"),
    Q87_0("Ostali malformacijski sindromi koji se uglavnom očituju u izgledu lica", "Q87.0"),
    Q87_1("Prirođeni malformacijski sindromi uglavnom vezani uz niski rast", "Q87.1"),
    Q87_2("Prirođeni malformacijski sindromi koji se uglavnom očituju na udovima", "Q87.2"),
    Q87_3("Prirođeni malformacijski sindromi koji imaju kao posljedicu rani pojačani rast", "Q87.3"),
    Q87_4("Marfanov sindrom", "Q87.4"),
    Q87_5("Ostali prirođeni malformacijski sindromi s drugim koštanim promjenama", "Q87.5"),
    Q87_8("Ostali specificirani prirođeni malformacijski sindromi, nesvrstani drugamo", "Q87.8"),
    Q89("Ostale prirođene malformacije, nesvrstane drugamo", "Q89"),
    Q89_0("Prirođene malformacije slezene", "Q89.0"),
    Q89_1("Prirođene malformacije nadbubrežne žlijezde", "Q89.1"),
    Q89_2("Prirođene malformacije drugih endokrinih žlijezda", "Q89.2"),
    Q89_3("Situs inversus", "Q89.3"),
    Q89_4("Sijamski blizanci", "Q89.4"),
    Q89_7("Multiple prirođene malformacije, nesvrstane drugamo", "Q89.7"),
    Q89_8("Ostale specificirane prirođene malformacije", "Q89.8"),
    Q89_9("Prirođena malformacija, nespecificirana", "Q89.9"),
    Q90("Downov sindrom", "Q90"),
    Q90_0("Trisomija 21, mejotičko nerazdvajanje", "Q90.0"),
    Q90_1("Trisomija 21, mozaicizam (mitotičko nerazdvajanje)", "Q90.1"),
    Q90_2("Trisomija 21, translokacija", "Q90.2"),
    Q90_9("Downov sindrom, nespecificiran", "Q90.9"),
    Q91("Edwardsov sindrom i Patauov sindrom", "Q91"),
    Q91_0("Trisomija 18, mejotičko nerazdvajanje", "Q91.0"),
    Q91_1("Trisomija 18, mozaicizam (mitotičko nerazdvajanje)", "Q91.1"),
    Q91_2("Trisomija 18, translokacija", "Q91.2"),
    Q91_3("Edwardsov sindrom, nespecificiran", "Q91.3"),
    Q91_4("Trisomija 13, mejotičko nerazdvajanje", "Q91.4"),
    Q91_5("Trisomija 13, mozaicizam (mitotičko nerazdvajanje)", "Q91.5"),
    Q91_6("Trisomija 13, translokacija", "Q91.6"),
    Q91_7("Patauov sindrom, nespecificiran", "Q91.7"),
    Q92("Ostale trisomije i parcijalne trisomije autosoma, nesvrstane drugamo", "Q92"),
    Q92_0("Trisomija cijeloga kromosoma, mejotičko nerazdvajanje", "Q92.0"),
    Q92_1("Trisomija cijeloga kromosoma, mozaicizam (mitotičko nerazdvajanje)", "Q92.1"),
    Q92_2("Velika parcijalna trisomija", "Q92.2"),
    Q92_3("Mala parcijalna trisomija", "Q92.3"),
    Q92_4("Udvostručenje vidljivo samo u prometafazi", "Q92.4"),
    Q92_5("Udvostručenje s drugim kompliciranim promjenama", "Q92.5"),
    Q92_6("Prekobrojni marker-kromosomi", "Q92.6"),
    Q92_7("Triploidija i poliploidija", "Q92.7"),
    Q92_8("Ostale specificirane trisomije i parcijalne trisomije autosoma", "Q92.8"),
    Q92_9("Trisomija i parcijalna trisomija autosoma, nespecificirana", "Q92.9"),
    Q93("Monosomije i delecije autosoma, nesvrstane drugamo", "Q93"),
    Q93_0("Monosomija cijeloga kromosoma, mejotičko nerazdvajanje", "Q93.0"),
    Q93_1("Monosomija cijeloga kromosoma, mozaicizam (mitotičko nerazdvajanje)", "Q93.1"),
    Q93_2("Prstenasti kromosom ili dicentrični kromosom", "Q93.2"),
    Q93_3("Delecija kratkoga kraka 4. kromosoma", "Q93.3"),
    Q93_4("Delecija kratkoga kraka 5. kromosoma", "Q93.4"),
    Q93_5("Druge delecije dijela kromosoma", "Q93.5"),
    Q93_6("Delecije vidljive samo u prometafazi", "Q93.6"),
    Q93_7("Delecije s drugim kompleksnim promjenama", "Q93.7"),
    Q93_8("Ostale delecije autosoma", "Q93.8"),
    Q93_9("Delecija autosoma, nespecificirana", "Q93.9"),
    Q95("Uravnotežene promjene i strukturni marker-kromosomi, nesvrstani drugamo", "Q95"),
    Q95_0("Uravnotežena translokacija i insercija u normalnih osoba", "Q95.0"),
    Q95_1("Inverzija kromosoma u normalne osobe", "Q95.1"),
    Q95_2("Uravnotežene promjene autosoma u abnormalne osobe", "Q95.2"),
    Q95_3("Uravnotežene razmjene između spolnih kromosoma i autosoma u abnormalne osobe", "Q95.3"),
    Q95_4("Osobe s marker-heterokromatinom", "Q95.4"),
    Q95_5("Osobe s fragilnim mjestom na autosomu", "Q95.5"),
    Q95_8("Ostale uravnotežene promjene rasporeda i strukturni markeri", "Q95.8"),
    Q95_9("Uravnotežena promjena i strukturni marker, nespecificiran", "Q95.9"),
    Q96("Turnerov sindrom", "Q96"),
    Q96_0("Kariotip 45,X", "Q96.0"),
    Q96_1("Kariotip 46,X iso (Xq)", "Q96.1"),
    Q96_2("Kariotip 46,X s abnormalnim spolnim kromosomom, osim iso (Xq)", "Q96.2"),
    Q96_3("Mozaičnost, 45,X/46,XX ili XY", "Q96.3"),
    Q96_4("Mozaičnost, 45,X/druga stanična loza (druge stanične loze) s nenormalnim spolnim kromosomom", "Q96.4"),
    Q96_8("Ostale varijacije Turnerova sindroma", "Q96.8"),
    Q96_9("Turnerov sindrom, nespecificiran", "Q96.9"),
    Q97("Ostale abnormalnosti spolnih kromosoma, ženski fenotip, nesvrstane drugamo", "Q97"),
    Q97_0("Kariotip 47,XXX", "Q97.0"),
    Q97_1("Abnormalnost kromosoma, žensko s više od tri X kromosoma", "Q97.1"),
    Q97_2("Mozaičnost, loze s različitim brojem kromosoma X", "Q97.2"),
    Q97_3("Abnormalnost kromosoma, kariotip 46,XY, žensko", "Q97.3"),
    Q97_8("Ostale specificirane abnormalnosti spolnih kromosoma, ženski fenotip", "Q97.8"),
    Q97_9("Abnormalnost spolnog kromosoma, ženski fenotip, nespecificiran", "Q97.9"),
    Q98("Ostale abnormalnosti spolnih kromosoma, muški fenotip, nesvrstane drugamo", "Q98"),
    Q98_0("Klinefelterov sindrom, kariotip 47,XXY", "Q98.0"),
    Q98_1("Klinefelterov sindrom, muško s više od dva X kromosoma", "Q98.1"),
    Q98_2("Klinefelterov sindrom, muško s 46,XX kariotipom", "Q98.2"),
    Q98_3("Ostali muški s 46,XX kariotipom", "Q98.3"),
    Q98_4("Klinefelterov sindrom, nespecificiran", "Q98.4"),
    Q98_5("Kariotip 47,XYY", "Q98.5"),
    Q98_6("Muško sa strukturnom anomalijom spolnog kromosoma", "Q98.6"),
    Q98_7("Muško s mozaičnim spolnim kromosomima", "Q98.7"),
    Q98_8("Ostale specificirane anomalije spolnih kromosoma, muški fenotip", "Q98.8"),
    Q98_9("Anomalija spolnog kromosoma, muški fenotip, nespecificirana", "Q98.9"),
    Q99("Ostale kromosomske aberacije, nesvrstane drugamo", "Q99"),
    Q99_0("Himerizam 46,XX/46,XY", "Q99.0"),
    Q99_1("Pravi hermafrodit, 46,XX", "Q99.1"),
    Q99_2("Lomljiv kromosom X", "Q99.2"),
    Q99_8("Ostale specificirane kromosomske aberacije", "Q99.8"),
    Q99_9("Kromosomska aberacija, nespecificirana", "Q99.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesQ(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
