package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesO {
    
    O00("Izvanmaternična trudnoća", "O00"),
    O00_0("Abdominalna trudnoća", "O00.0"),
    O00_1("Tubarna trudnoća", "O00.1"),
    O00_2("Ovarijalna trudnoća", "O00.2"),
    O00_8("Ostale izvanmaternične trudnoće", "O00.8"),
    O00_9("Izvanmaternična trudnoća, nespecificirana", "O00.9"),
    O01("Hidatidozna mola", "O01"),
    O01_0("Klasična hidatidozna mola", "O01.0"),
    O01_1("Nepotpuna i parcijalna hidatidozna mola", "O01.1"),
    O01_9("Hidatidozna mola, nespecificirana", "O01.9"),
    O02("Ostali abnormalni produkti začeća", "O02"),
    O02_0("Odumrlo jajašce i nehidatidozna mola", "O02.0"),
    O02_1("Neostvareni pobačaj (missed abortion) (abortus retentus)", "O02.1"),
    O02_8("Ostali specificirani abnormalni produkti začeća", "O02.8"),
    O02_9("Abnormalni produkt začeća, nespecificiran", "O02.9"),
    O03("Spontani pobačaj", "O03"),
    O03_0("Spontani pobačaj", "O03.0"),
    O04("Legalno inducirani (medicinski) pobačaj", "O04"),
    O04_0("Legalno inducirani (medicinski) pobačaj", "O04.0"),
    O05("Ostali pobačaj", "O05"),
    O05_0("Ostali pobačaj", "O05.0"),
    O06("Nespecificirani pobačaj", "O06"),
    O06_0("Nespecificirani pobačaj", "O06.0"),
    O07("Neuspio pokušaj pobačaja", "O07"),
    O07_0("Neuspio legalno inducirani (medicinski) pobačaj, kompliciran infekcijom genitalnog sustava i zdjeličnih organa", "O07.0"),
    O07_1("Neuspio legalno inducirani (medicinski) pobačaj, kompliciran kasnim ili obilnim krvarenjem", "O07.1"),
    O07_2("Neuspio legalno inducirani (medicinski) pobačaj, kompliciran embolijom", "O07.2"),
    O07_3("Neuspio legalno inducirani (medicinski) pobačaj, s ostalim i nespecificiranim komplikacijama", "O07.3"),
    O07_4("Neuspio legalno inducirani (medicinski) pobačaj, bez komplikacija", "O07.4"),
    O07_5("Ostali i nespecificiran neuspio pokušaj pobačaja, kompliciran infekcijom genitalnog sustava i zdjeličnih organa", "O07.5"),
    O07_6("Ostali i nespecificiran neuspio pokušaj pobačaja, kompliciran kasnim ili obilnim krvarenjem", "O07.6"),
    O07_7("Ostali i nespecificiran neuspio pokušaj pobačaja, kompliciran embolijom", "O07.7"),
    O07_8("Ostali i nespecificiran neuspio pokušaj pobačaja, kompliciran ostalim i nespecificiranim komplikacijama", "O07.8"),
    O07_9("Ostali i nespecificiran neuspio pokušaj pobačaja, bez komplikacija", "O07.9"),
    O08("Komplikacije nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08"),
    O08_0("Infekcija spolnog sustava i zdjeličnih organa nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.0"),
    O08_1("Kasno ili obilno krvarenje nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.1"),
    O08_2("Embolija nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.2"),
    O08_3("Šok nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.3"),
    O08_4("Zatajenje bubrega nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.4"),
    O08_5("Metabolički poremećaji nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.5"),
    O08_6("Oštećenje zdjeličnih organa i tkiva nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.6"),
    O08_7("Ostale venske bolesti kao komplikacije nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.7"),
    O08_8("Ostale komplikacije nakon pobačaja i izvanmaternične ili molarne trudnoće", "O08.8"),
    O08_9("Komplikacija nakon pobačaja i izvanmaternične ili molarne trudnoće, nespecificirana", "O08.9"),
    O10("Hipertenzija, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10"),
    O10_0("Hipertenzija, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10.0"),
    O10_1("Hipertenzivna bolest srca, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10.1"),
    O10_2("Hipertenzivna bolest bubrega, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10.2"),
    O10_3("Hipertenzivna bolest srca i bubrega, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10.3"),
    O10_4("Sekundarna hipertenzija, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja", "O10.4"),
    O10_9("Hipertenzija, koja je i prije postojala, kao komplikacija trudnoće, porođaja i babinja, nespecificirana", "O10.9"),
    O11("Hipertenzivni poremećaji, koji su i prije postojali, sa superponiranom proteinurijom", "O11"),
    O11_0("Hipertenzivni poremećaji, koji su i prije postojali, sa superponiranom proteinurijom", "O11.0"),
    O12("Edemi u trudnoći (uzrokovani trudnoćom) i proteinurija bez hipertenzije", "O12"),
    O12_0("Edemi u trudnoći", "O12.0"),
    O12_1("Proteinurija u trudnoći", "O12.1"),
    O12_2("Edemi u trudnoći s proteinurijom", "O12.2"),
    O13("Hipertenzija u trudnoći (uzrokovana trudnoćom) bez značajne proteinurije", "O13"),
    O13_0("Hipertenzija u trudnoći (uzrokovana trudnoćom) bez značajne proteinurije", "O13.0"),
    O14("Hipertenzija u trudnoći (uzrokovana trudnoćom) sa značajnom proteinurijom", "O14"),
    O14_0("Blaga preeklampsija", "O14.0"),
    O14_1("Teška preeklampsija", "O14.1"),
    O14_9("Preeklampsija, nespecificirana", "O14.9"),
    O15("Eklampsija", "O15"),
    O15_0("Eklampsija u trudnoći", "O15.0"),
    O15_1("Eklampsija u tijeku porođaja", "O15.1"),
    O15_2("Eklampsija u babinjama", "O15.2"),
    O15_9("Eklampsija u nespecificiranom razdoblju", "O15.9"),
    O16("Hipertenzija u majke, nespecificirana", "O16"),
    O16_0("Hipertenzija u majke, nespecificirana", "O16.0"),
    O20("Krvarenje u ranoj trudnoći", "O20"),
    O20_0("Prijeteći pobačaj", "O20.0"),
    O20_8("Ostala krvarenja u ranoj trudnoći", "O20.8"),
    O20_9("Krvarenje u ranoj trudnoći, nespecificirano", "O20.9"),
    O21("Prekomjerno povraćanje u trudnoći (hyperemesis gravidarum)", "O21"),
    O21_0("Povraćanje u trudnoći - blagi oblik", "O21.0"),
    O21_1("Povraćanje u trudnoći s metaboličkim poremećajem", "O21.1"),
    O21_2("Kasno povraćanje u trudnoći", "O21.2"),
    O21_8("Ostala povraćanja kao komplikacija trudnoće", "O21.8"),
    O21_9("Povraćanje u trudnoći, nespecificirano", "O21.9"),
    O22("Bolesti vena kao komplikacije trudnoće", "O22"),
    O22_0("Proširenje nožnih vena u trudnoći", "O22.0"),
    O22_1("Proširenje vena u području spolovila u trudnoći", "O22.1"),
    O22_2("Tromboflebitis površinskih vena u trudnoći", "O22.2"),
    O22_3("Tromboflebitis dubokih vena u trudnoći", "O22.3"),
    O22_4("Hemoroidi u trudnoći", "O22.4"),
    O22_5("Tromboza moždanih vena u trudnoći", "O22.5"),
    O22_8("Ostale venske bolesti kao komplikacije u trudnoći", "O22.8"),
    O22_9("Venska bolest kao komplikacija u trudnoći, nespecificirana", "O22.9"),
    O23("Infekcije mokraćnog i spolnog sustava u trudnoći", "O23"),
    O23_0("Infekcije bubrega u trudnoći", "O23.0"),
    O23_1("Infekcije mokraćnoga mjehura u trudnoći", "O23.1"),
    O23_2("Infekcije uretre u trudnoći", "O23.2"),
    O23_3("Infekcije ostalih dijelova mokraćnog sustava u trudnoći", "O23.3"),
    O23_4("Infekcija mokraćnog sustava u trudnoći, nespecificirana", "O23.4"),
    O23_5("Infekcije spolnog sustava u trudnoći", "O23.5"),
    O23_9("Ostala i nespecificirana infekcija mokraćnog i spolnog sustava u trudnoći", "O23.9"),
    O24("Dijabetes melitus (šećerna bolest) u trudnoći", "O24"),
    O24_0("Dijabetes melitus ovisan o inzulinu koji je i prije postojao", "O24.0"),
    O24_1("Dijabetes melitus neovisan o inzulinu koji je i prije postojao", "O24.1"),
    O24_2("Dijabetes melitus povezan s neishranjenošću koji je i prije postojao", "O24.2"),
    O24_3("Dijabetes melitus koji je i prije postojao, nespecificiran", "O24.3"),
    O24_4("Dijabetes melitus nastao u trudnoći", "O24.4"),
    O24_9("Dijabetes melitus u trudnoći, nespecificiran", "O24.9"),
    O25("Neishranjenost u trudnoći", "O25"),
    O25_0("Neishranjenost u trudnoći", "O25.0"),
    O26("Zbrinjavanje majke zbog ostalih stanja prije svega vezanih uz trudnoću", "O26"),
    O26_0("Prekomjerno dobivanje na težini u trudnoći", "O26.0"),
    O26_1("Slabo dobivanje na težini u trudnoći", "O26.1"),
    O26_2("Trudnička skrb za ženu s habitualnim pobačajem", "O26.2"),
    O26_3("Zaostalo intrauterino kontraceptivno sredstvo u trudnoći", "O26.3"),
    O26_4("Herpes gestationis (gestacijski herpes)", "O26.4"),
    O26_5("Hipotenzivni sindrom u majke", "O26.5"),
    O26_6("Poremećaji jetrene funkcije u trudnoći, porođaju i babinjama", "O26.6"),
    O26_7("Subluksacija simfize (pubisa) u trudnoći, porođaju i babinjama", "O26.7"),
    O26_8("Ostala specificirana stanja vezana uz trudnoću", "O26.8"),
    O26_9("Stanje vezano uz trudnoću, nespecificirano", "O26.9"),
    O28("Abnormalni nalazi antenatalnog skrininga majke", "O27"),
    O28_0("Abnormalni hematološki nalaz na antenatalnom skriningu majke", "O27.0"),
    O28_1("Abnormalni biokemijski nalaz na antenatalnom skriningu majke", "O27.1"),
    O28_2("Abnormalni citološki nalaz na antenatalnom skriningu majke", "O27.2"),
    O28_3("Abnormalni ultrazvučni nalaz na antenatalnom skriningu majke", "O27.3"),
    O28_4("Abnormalni rendgenološki nalaz na antenatalnom skriningu majke", "O27.4"),
    O28_5("Abnormalni kromosomski i genski nalaz na antenatalnom skriningu majke", "O27.5"),
    O28_8("Ostali abnormalni nalazi na antenatalnom skriningu majke", "O27.8"),
    O28_9("Abnormalni nalaz na antenatalnom skriningu majke, nespecificiran", "O27.9"),
    O29("Komplikacije zbog anestezije za vrijeme trudnoće", "O28"),
    O29_0("Plućne komplikacije zbog anestezije za vrijeme trudnoće", "O28.0"),
    O29_1("Srčane komplikacije zbog anestezije za vrijeme trudnoće", "O28.1"),
    O29_2("Komplikacije središnjega živčanog sustava zbog anestezije za vrijeme trudnoće", "O28.2"),
    O29_3("Toksična reakcija na lokalnu anesteziju za vrijeme trudnoće", "O28.3"),
    O29_4("Glavobolja zbog spinalne i epiduralne anestezije za vrijeme trudnoće", "O28.4"),
    O29_5("Ostale komplikacije zbog spinalne i epiduralne anestezije za vrijeme trudnoće", "O28.5"),
    O29_6("Neuspjela ili otežana intubacija za vrijeme trudnoće", "O28.6"),
    O29_8("Ostale komplikacije zbog anestezije za vrijeme trudnoće", "O28.8"),
    O29_9("Komplikacija zbog anestezije za vrijeme trudnoće, nespecificirana", "O28.9"),
    O30("Višeplodna trudnoća", "O30"),
    O30_0("Blizanačka trudnoća", "O30.0"),
    O30_1("Troplodna trudnoća", "O30.1"),
    O30_2("Četveroplodna trudnoća", "O30.2"),
    O30_8("Ostala višeplodna trudnoća", "O30.8"),
    O30_9("Višeplodna trudnoća, nespecificirana", "O30.9"),
    O31("Komplikacije specifične za višeplodnu trudnoću", "O31"),
    O31_0("Fetus papyraceus", "O31.0"),
    O31_1("Nastavljena trudnoća nakon pobačaja jednog ili više fetusa", "O31.1"),
    O31_2("Nastavljena trudnoća nakon intrauterine smrti jednog ili više fetusa", "O31.2"),
    O31_8("Druge komplikacije specifične za višeplodnu trudnoću", "O31.8"),
    O32("Zbrinjavanje majke zbog utvrđenog ili suspektnoga nepravilnog stava fetusa", "O32"),
    O32_0("Zbrinjavanje majke zbog nestabilna položaja fetusa", "O32.0"),
    O32_1("Zbrinjavanje majke zbog stava zatkom", "O32.1"),
    O32_2("Zbrinjavanje majke zbog poprečnog i kosog položaja fetusa", "O32.2"),
    O32_3("Zbrinjavanje majke zbog stava licem, čelom i bradom", "O32.3"),
    O32_4("Zbrinjavanje majke zbog stava glavice visokog za termin", "O32.4"),
    O32_5("Zbrinjavanje majke zbog višeplodne trudnoće s nepravilnim stavom jednog ili više fetusa", "O32.5"),
    O32_6("Zbrinjavanje majke zbog kombiniranog nepravilnog stava fetusa", "O32.6"),
    O32_8("Zbrinjavanje majke zbog drugog nepravilnog stava fetusa", "O32.8"),
    O32_9("Zbrinjavanje majke zbog nepravilnog stava fetusa, nespecificiranog", "O32.9"),
    O33("Zbrinjavanje majke zbog poznate ili suspektne disproporcije", "O33"),
    O33_0("Zbrinjavanje majke zbog disproporcije koju uzrokuje deformitet zdjeličnih kostiju", "O33.0"),
    O33_1("Zbrinjavanje majke zbog disproporcije koju uzrokuje jednakomjerno sužena zdjelica", "O33.1"),
    O33_2("Zbrinjavanje majke zbog disproporcije koju uzrokuje suženje ulaza zdjelice", "O33.2"),
    O33_3("Zbrinjavanje majke zbog disproporcije koju uzrokuje suženje izlaza zdjelice", "O33.3"),
    O33_4("Zbrinjavanje majke zbog disproporcije koju uzrokuju i majka i fetus", "O33.4"),
    O33_5("Zbrinjavanje majke zbog disproporcije koju uzrokuje neuobičajeno veliki fetus", "O33.5"),
    O33_6("Zbrinjavanje majke zbog disproporcije koju uzrokuje hidrocefalija fetusa", "O33.6"),
    O33_7("Zbrinjavanje majke zbog disproporcije koju uzrokuju drugi deformiteti fetusa", "O33.7"),
    O33_8("Zbrinjavanje majke zbog disproporcije izazvane ostalim uzrocima", "O33.8"),
    O33_9("Zbrinjavanje majke zbog disproporcije, nespecificirane", "O33.9"),
    O34("Zbrinjavanje majke zbog poznate ili suspektne abnormalnosti zdjeličnih organa", "O34"),
    O34_0("Zbrinjavanje majke zbog prirođene malformacije maternice", "O34.0"),
    O34_1("Zbrinjavanje majke zbog tumora tijela maternice", "O34.1"),
    O34_2("Zbrinjavanje majke zbog ožiljka maternice uzrokovanog prijašnjom operacijom", "O34.2"),
    O34_3("Zbrinjavanje majke zbog insuficijencije vrata maternice", "O34.3"),
    O34_4("Zbrinjavanje majke zbog ostalih abnormalnosti vrata maternice", "O34.4"),
    O34_5("Zbrinjavanje majke zbog ostalih abnormalnosti maternice u trudnoći", "O34.5"),
    O34_6("Zbrinjavanje majke zbog abnormalnosti rodnice", "O34.6"),
    O34_7("Zbrinjavanje majke zbog abnormalnosti vulve i perineuma", "O34.7"),
    O34_8("Zbrinjavanje majke zbog ostalih abnormalnosti zdjeličnih organa", "O34.8"),
    O34_9("Zbrinjavanje majke zbog abnormalnosti zdjeličnih organa, nespecificirane", "O34.9"),
    O35("Zbrinjavanje majke zbog poznate ili suspektne abnormalnosti i oštećenja fetusa", "O35"),
    O35_0("Zbrinjavanje majke zbog sumnje na malformaciju središnjega živčanog sustava fetusa", "O35.0"),
    O35_1("Zbrinjavanje majke zbog sumnje na kromosomske abnormalnosti fetusa", "O35.1"),
    O35_2("Zbrinjavanje majke zbog sumnje na hereditarne bolesti fetusa", "O35.2"),
    O35_3("Zbrinjavanje majke zbog sumnje na oštećenje fetusa uzrokovano virusnom bolesti u majke", "O35.3"),
    O35_4("Zbrinjavanje majke zbog sumnje na oštećenje fetusa uzrokovano alkoholom", "O35.4"),
    O35_5("Zbrinjavanje majke zbog sumnje na oštećenje fetusa uzrokovano lijekovima", "O35.5"),
    O35_6("Zbrinjavanje majke zbog sumnje na oštećenje fetusa uzrokovano zračenjem", "O35.6"),
    O35_7("Zbrinjavanje majke zbog sumnje na oštećenje fetusa uzrokovano ostalim medicinskim postupcima", "O35.7"),
    O35_8("Zbrinjavanje majke zbog sumnje na drugu abnormalnost i oštećenje fetusa", "O35.8"),
    O35_9("Zbrinjavanje majke zbog sumnje na abnormalnost i oštećenje fetusa, nespecificirano", "O35.9"),
    O36("Zbrinjavanje majke zbog drugih poznatih ili suspektnih problema fetusa", "O36"),
    O36_0("Zbrinjavanje majke zbog Rh izoimunizacije", "O36.0"),
    O36_1("Zbrinjavanje majke zbog druge izoimunizacije", "O36.1"),
    O36_2("Zbrinjavanje majke zbog fetalnog hidropsa", "O36.2"),
    O36_3("Zbrinjavanje majke zbog znakova fetalne hipoksije", "O36.3"),
    O36_4("Zbrinjavanje majke zbog intrauterine smrti", "O36.4"),
    O36_5("Zbrinjavanje majke zbog usporena rasta fetusa", "O36.5"),
    O36_6("Zbrinjavanje majke zbog prekomjerna rasta fetusa", "O36.6"),
    O36_7("Zbrinjavanje majke zbog fetusa sposobnog za život u abdominalnoj trudnoći", "O36.7"),
    O36_8("Zbrinjavanje majke zbog ostalih specificiranih problema fetusa", "O36.8"),
    O36_9("Zbrinjavanje majke zbog problema fetusa, nespecificiranog", "O36.9"),
    O40("Polihidramnion", "O40"),
    O40_0("Polihidramnion", "O40.0"),
    O41("Ostali poremećaji amnionske tekućine i ovojnica", "O41"),
    O41_0("Oligohidramnion", "O41.0"),
    O41_1("Infekcija amnionske vreće i ovojnica", "O41.1"),
    O41_8("Ostali specificirani poremećaji amnionske tekućine i ovojnica", "O41.8"),
    O41_9("Poremećaj amnionske tekućine i ovojnica, nespecificiran", "O41.9"),
    O42("Prijevremena ruptura ovojnica", "O42"),
    O42_0("Prijevremena ruptura ovojnica, početak trudova unutar 24 sata", "O42.0"),
    O42_1("Prijevremena ruptura ovojnica, početak trudova nakon 24 sata", "O42.1"),
    O42_2("Prijevremena ruptura ovojnica, trudovi odgođeni terapijski", "O42.2"),
    O42_9("Prijevremena ruptura ovojnica, nespecificirana", "O42.9"),
    O43("Poremećaji posteljice (placente)", "O43"),
    O43_0("Sindrom placentarne transfuzije", "O43.0"),
    O43_1("Malformacije posteljice", "O43.1"),
    O43_8("Ostali poremećaji posteljice", "O43.8"),
    O43_9("Placentarni poremećaj, nespecificiran", "O43.9"),
    O44("Placenta praevia", "O44"),
    O44_0("Placenta praevia, bez krvarenja", "O44.0"),
    O44_1("Placenta praevia, s krvarenjem", "O44.1"),
    O45("Prijevremeno odljuštenje posteljice (abruptio placentae)", "O45"),
    O45_0("Prijevremeno odljuštenje posteljice s poremećajem koagulacije", "O45.0"),
    O45_8("Drugo prijevremeno odljuštenje posteljice", "O45.8"),
    O45_9("Prijevremeno odljuštenje posteljice, nespecificirano", "O45.9"),
    O46("Krvarenje prije porođaja nesvrstano drugamo", "O46"),
    O46_0("Krvarenje prije porođaja s poremećajem koagulacije", "O46.0"),
    O46_8("Druga krvarenja prija porođaja", "O46.8"),
    O46_9("Krvarenje prije porođaja, nespecificirano", "O46.9"),
    O47("Lažni trudovi", "O47"),
    O47_0("Lažni trudovi prije navršenog 37. tjedna trudnoće", "O47.0"),
    O47_1("Lažni trudovi u navršenom 37. tjednu trudnoće ili nakon njega", "O47.1"),
    O47_9("Lažni trudovi, nespecificirani", "O47.9"),
    O48("Produžena trudnoća", "O48"),
    O48_0("Produžena trudnoća", "O48.0"),
    O60("Prijevremeni porođaj", "O60"),
    O60_0("Prijevremeni porođaj", "O60.0"),
    O61("Neuspješna indukcija porođaja", "O61"),
    O61_0("Neuspješna indukcija porođaja lijekovima", "O61.0"),
    O61_1("Neuspješna indukcija porođaja instrumentima", "O61.1"),
    O61_8("Druga neuspješna indukcija porođaja", "O61.8"),
    O61_9("Neuspješna indukcija porođaja, nespecificirana", "O61.9"),
    O62("Nepravilnosti jačine trudova", "O62"),
    O62_0("Primarno tromi trudovi (primarna inercija)", "O62.,"),
    O62_1("Sekundarno tromi trudovi (sekundarna inercija)", "O62.1"),
    O62_2("Druga tromost maternice (inertia uteri)", "O62.2"),
    O62_3("Ubrzani (nagli) trudovi", "O62.3"),
    O62_4("Hipertonične, nekoordinirane i produžene kontrakcije maternice", "O62.4"),
    O62_8("Druge nepravilnosti jačine trudova", "O62.8"),
    O62_9("Nepravilnosti jačine trudova, nespecificirane", "O62.9"),
    O63("Dugotrajni (produženi) porođaj", "O63"),
    O63_0("Produženo prvo porođajno doba", "O63.0"),
    O63_1("Produženo drugo porođajno doba", "O63.1"),
    O63_2("Odgođeni porođaj drugog blizanca, trećeg itd.", "O63.2"),
    O63_9("Dugotrajni porođaj, nespecificiran", "O63.9"),
    O64("Zapreka rađanja zbog nepravilna položaja i stava fetusa", "O64"),
    O64_0("Zapreka rađanja zbog nepotpune rotacije glavice fetusa", "O64.0"),
    O64_1("Zapreka rađanja zbog stava zatkom", "O64.1"),
    O64_2("Zapreka rađanja zbog stava licem", "O64.2"),
    O64_3("Zapreka rađanja zbog stava čelom", "O64.3"),
    O64_4("Zapreka rađanja zbog stava ramenom", "O64.4"),
    O64_5("Zapreka rađanja zbog kombiniranog položaja fetusa", "O64.5"),
    O64_8("Zapreka rađanja zbog drugog nepravilnog položaja i nepravilnog stava fetusa", "O64.8"),
    O64_9("Zapreka rađanja zbog nepravilnoga položaja i nepravilnog stava fetusa, nespecificiranog", "O64.9"),
    O65("Zapreka rađanja zbog abnormalnosti majčine zdjelice", "O65"),
    O65_0("Zapreka rađanja zbog deformiteta zdjelice", "O65.0"),
    O65_1("Zapreka rađanja zbog jednakomjerno sužene zdjelice", "O65.1"),
    O65_2("Zapreka rađanja zbog suženja ulaza zdjelice", "O65.2"),
    O65_3("Zapreka rađanja zbog suženja sredine i izlaza zdjelice", "O65.3"),
    O65_4("Zapreka rađanja zbog fetopelvične disproporcije, nespecificirane", "O65.4"),
    O65_5("Zapreka rađanja zbog abnormalnosti majčinih zdjeličnih organa", "O65.5"),
    O65_8("Zapreka rađanja zbog drugih abnormalnosti majčine zdjelice", "O65.8"),
    O65_9("Zapreka rađanja zbog abnormalnosti majčine zdjelice, nespecificirane", "O65.9"),
    O66("Ostale zapreke rađanja", "O66"),
    O66_0("Zapreka rađanja zbog ramene distocije", "O66.,"),
    O66_1("Zapreka rađanja zbog isprepletenih blizanaca", "O66.1"),
    O66_2("Zapreka rađanja zbog neuobičajeno velikog fetusa", "O66.2"),
    O66_3("Zapreka rađanja zbog drugih abnormalnosti fetusa", "O66.3"),
    O66_4("Neuspješna indukcija porođaja, nespecificirana", "O66.4"),
    O66_5("Neuspješna primjena vakuumskog ekstraktora i forcepsa, nespecificirana", "O66.5"),
    O66_8("Ostale specificirane zapreke rađanja", "O66.8"),
    O66_9("Zapreka rađanja, nespecificirana", "O66.9"),
    O67("Porođaj kompliciran krvarenjem, koje nije svrstano drugamo", "O67"),
    O67_0("Krvarenje u porođaju s poremećajem koagulacije", "O67.0"),
    O67_8("Drugo krvarenje u porođaju", "O67.8"),
    O67_9("Krvarenje u porođaju, nespecificirano", "O67.9"),
    O68("Porođaj kompliciran fetalnom patnjom (distres)", "O68"),
    O68_0("Porođaj kompliciran poremećajem srčanog rada fetusa", "O68.0"),
    O68_1("Porođaj kompliciran mekonijem u amnionskoj tekućini", "O68.1"),
    O68_2("Porođaj kompliciran poremećajem srčane frekvencije s mekonijem u amnionskoj tekućini", "O68.2"),
    O68_3("Porođaj kompliciran biokemijskim pokazateljima fetalne patnje", "O68.3"),
    O68_8("Porođaj kompliciran drugim pokazateljima fetalne patnje", "O68.8"),
    O68_9("Porođaj kompliciran fetalnom patnjom, nespecificiranom", "O68.9"),
    O69("Porođaj otežan komplikacijama pupčane vrpce", "O69"),
    O69_0("Porođaj kompliciran prolapsom pupkovine", "O69.0"),
    O69_1("Porođaj kompliciran pupkovinom oko vrata (fetusa), s kompresijom", "O69.1"),
    O69_2("Porođaj kompliciran drugim zapletajima pupkovine", "O69.2"),
    O69_3("Porođaj kompliciran kratkom pupkovinom", "O69.3"),
    O69_4("Porođaj kompliciran s vasa praevia", "O69.4"),
    O69_5("Porođaj kompliciran vaskularnim oštećenjem pupčane vrpce", "O69.5"),
    O69_8("Porođaj otežan drugim komplikacijama pupčane vrpce", "O69.8"),
    O69_9("Porođaj otežani komplikacijom pupčane vrpce, nespecificiranom", "O69.9"),
    O70("Laceracija međice (perineuma) u tijeku rađanja", "O70"),
    O70_0("Laceracija perineuma prvoga stupnja u tijeku rađanja", "O70.0"),
    O70_1("Laceracija perineuma drugoga stupnja u tijeku rađanja", "O70.1"),
    O70_2("Laceracija perineuma trećega stupnja u tijeku rađanja", "O70.2"),
    O70_3("Laceracija perineuma četvrtoga stupnja u tijeku rađanja", "O70.3"),
    O70_9("Laceracija perineuma u tijeku rađanja, nespecificirana", "O70.9"),
    O71("Druga porodnička ozljeda", "O71"),
    O71_0("Ruptura maternice prije početka porođaja", "O71.0"),
    O71_1("Ruptura maternice tijekom porođaja", "O71.1"),
    O71_2("Inverzija maternice nakon porođaja", "O71.2"),
    O71_3("Porodnička laceracija ušća maternice", "O71.3"),
    O71_4("Porodnička visoka laceracija rodnice, izolirana", "O71.4"),
    O71_5("Druga porodnička ozljeda zdjeličnih organa", "O71.5"),
    O71_6("Porodničko oštećenje zdjeličnih zglobova i ligamenata", "O71.6"),
    O71_7("Porodnički hematom zdjelice", "O71.7"),
    O71_8("Druge specificirane porodničke ozljede", "O71.8"),
    O71_9("Porodnička ozljeda, nespecificirana", "O71.9"),
    O72("Krvarenje nakon poroda", "O72"),
    O72_0("Krvarenje u trećoj dobi", "O72.0"),
    O72_1("Drugo krvarenje neposredno nakon porođaja", "O72.1"),
    O72_2("Kasno i sekundarno krvarenje nakon porođaja", "O72.2"),
    O72_3("Poremećaji koagulacije nakon porođaja", "O72.3"),
    O73("Zaostala posteljica i ovojnice, bez krvarenja", "O73"),
    O73_0("Placenta retenta, bez krvarenja", "O73.0"),
    O73_1("Zaostali dijelovi posteljice i ovojnica, bez krvarenja", "O73.1"),
    O74("Komplikacije u tijeku porođaja zbog anestezije", "O74"),
    O74_0("Aspiracijski pneumonitis zbog anestezije u tijeku porođaja", "O74.0"),
    O74_1("Druge plućne komplikacije zbog anestezije u tijeku porođaja", "O74.1"),
    O74_2("Srčane komplikacije zbog anestezije u tijeku porođaja", "O74.2"),
    O74_3("Komplikacije središnjega živčanog sustava zbog anestezije u tijeku porođaja", "O74.3"),
    O74_4("Toksična reakcija na lokalnu anesteziju u tijeku porođaja", "O74.4"),
    O74_5("Glavobolja zbog spinalne i epiduralne anestezije u tijeku porođaja", "O74.5"),
    O74_6("Druge komplikacije spinalne i epiduralne anestezije u tijeku porođaja", "O74.6"),
    O74_7("Neuspješna ili otežana intubacija u tijeku porođaja", "O74.7"),
    O74_8("Druge komplikacije zbog anestezije u tijeku porođaja", "O74.8"),
    O74_9("Komplikacija zbog anestezije u tijeku porođaja, nespecificirana", "O74.9"),
    O75("Ostale komplikacije porođaja, nesvrstane drugamo", "O75"),
    O75_0("Distres majke u tijeku porođaja", "O75.0"),
    O75_1("Šok za vrijeme ili nakon porođaja", "O75.1"),
    O75_2("Povišena temperatura u tijeku porođaja, nesvrstana drugamo", "O75.2"),
    O75_3("Druge infekcije u tijeku porođaja", "O75.3"),
    O75_4("Druge komplikacije porodničkih kirurških zahvata i postupaka", "O75.4"),
    O75_5("Odgođeno rađanje nakon artificijalne rupture ovojnica", "O75.5"),
    O75_6("Odgođeno rađanje nakon spontane ili nespecificirane rupture ovojnica", "O75.6"),
    O75_7("Vaginalno rađanje nakon prijašnjeg carskog reza", "O75.7"),
    O75_8("Druge specificirane komplikacije porođaja", "O75.8"),
    O75_9("Komplikacija porođaja, nespecificirana", "O75.9"),
    O80("Jednoplodni spontani porođaj", "O80"),
    O80_0("Spontani porođaj glavicom", "O80.0"),
    O80_1("Spontani porođaj zatkom", "O80.1"),
    O80_8("Drugi jednoplodni spontani porođaj", "O80.8"),
    O80_9("Jednoplodni spontani porođaj, nespecificiran", "O80.9"),
    O81("Jednoplodno rađanje forcepsom i vakuumskim ekstraktorom", "O81"),
    O81_0("Rađanje s niskom primjenom forcepsa", "O81.0"),
    O81_1("Rađanje s primjenom forcepsa u središnjem prostoru", "O81.1"),
    O81_2("Rađanje s primjenom forcepsa u središnjem prostoru s rotacijom", "O81.2"),
    O81_3("Drugo i nespecificirano rađanje s forcepsom", "O81.3"),
    O81_4("Rađanje vakuumskim ekstraktorom", "O81.4"),
    O81_5("Rađanje kombinacijom forcepsa i vakuumskog ekstraktora", "O81.5"),
    O82("Jednoplodno rađanje carskim rezom", "O82"),
    O82_0("Rađanje elektivnim carskim rezom", "O82.0"),
    O82_1("Rađanje hitnim carskim rezom", "O82.1"),
    O82_2("Rađanje histerektomijom (Caesarean hysterectomy)", "O82.2"),
    O82_8("Ostalo jednoplodno rađanje carskim rezom", "O82.8"),
    O82_9("Rađanje carskim rezom, nespecificirano", "O82.9"),
    O83("Drugo jednoplodno rađanje uz pomoć", "O83"),
    O83_0("Ekstrakcija zatka", "O83.0"),
    O83_1("Drugo rađanje zatkom uz pomoć ruku", "O83.1"),
    O83_2("Drugo rađanje uz pomoćne postupke", "O83.2"),
    O83_3("Rađanje za život sposobnog fetusa u abdominalnoj trudnoći", "O83.3"),
    O83_4("Destruktivne operacije pri rađanju", "O83.4"),
    O83_8("Drugo specificirano rađanje uz pomoć ruku", "O83.8"),
    O83_9("Jednoplodno rađanje uz pomoć, nespecificirano", "O83.9"),
    O84("Višeplodni porođaj", "O84"),
    O84_0("Višeplodni porođaj, svi spontani", "O84.0"),
    O84_1("Višeplodni porođaj, svi forcepsom ili vakuumskim ekstraktorom", "O84.1"),
    O84_2("Višeplodni porođaj, svi carskim rezom", "O84.2"),
    O84_8("Drugi višeplodni porođaj", "O84.8"),
    O84_9("Višeplodni porođaj, nespecificiran", "O84.9"),
    O85("Sepsa u babinjama (puerperalna sepsa)", "O85"),
    O85_0("Sepsa u babinjama (puerperalna sepsa)", "O85.0"),
    O86("Druge infekcije u babinjama", "O86"),
    O86_0("Infekcije porodničke kirurške rane", "O86.0"),
    O86_1("Druge infekcije spolnog sustava nakon porođaja", "O86.1"),
    O86_2("Infekcije urinarnog sustava nakon porođaja", "O86.2"),
    O86_3("Druge infekcije genitourinarnog sustava nakon porođaja", "O86.3"),
    O86_4("Povišena temperatura nepoznatoga podrijetla nakon porođaja", "O86.4"),
    O86_8("Druge specificirane infekcije u babinjama", "O86.8"),
    O87("Bolesti vena kao komplikacije babinja", "O87"),
    O87_0("Tromboflebitis površinskih vena u babinjama", "O87.0"),
    O87_1("Tromboflebitis dubokih vena u babinjama", "O87.1"),
    O87_2("Hemoroidi u babinjama", "O87.2"),
    O87_3("Tromboza moždanih vena u babinjama", "O87.3"),
    O87_8("Ostale venske bolesti kao komplikacije babinja", "O87.8"),
    O87_9("Venska bolest kao komplikacija babinja, nespecificirana", "O87.9"),
    O88("Porodnička embolija", "O88"),
    O88_0("Porodnička zračna embolija", "O88.0"),
    O88_1("Embolija plodovom vodom", "O88.1"),
    O88_2("Porodnička embolija krvnim ugruškom", "O88.2"),
    O88_3("Porodnička piemična i septična embolija", "O88.3"),
    O88_8("Druga porodnička embolija", "O88.8"),
    O89("Komplikacije zbog anestezije u babinjama", "O89"),
    O89_0("Plućne komplikacije zbog anestezije u babinjama", "O89.0"),
    O89_1("Srčane komplikacije zbog anestezije u babinjama", "O89.1"),
    O89_2("Komplikacije središnjega živčanog sustava zbog anestezije u babinjama", "O89.2"),
    O89_3("Toksična reakcija na lokalnu anesteziju u babinjama", "O89.3"),
    O89_4("Glavobolja zbog spinalne i epiduralne anestezije u babinjama", "O89.4"),
    O89_5("Druge komplikacije spinalne i epiduralne anestezije u babinjama", "O89.5"),
    O89_6("Neuspješna ili otežana intubacija u babinjama", "O89.6"),
    O89_8("Druge komplikacije zbog anestezije u babinjama", "O89.8"),
    O89_9("Komplikacija zbog anestezije u babinjama, nespecificirana", "O89.9"),
    O90("Komplikacije u babinjama nesvrstane drugamo", "O90"),
    O90_0("Rascjep rane carskog reza", "O90.0"),
    O90_1("Rascjep perinealne porodničke rane", "O90.1"),
    O90_2("Hematom porodničke rane", "O90.2"),
    O90_3("Kardiomiopatija u babinjama", "O90.3"),
    O90_4("Akutno zatajenje bubrega nakon porođaja", "O90.4"),
    O90_5("Postpartalni tireoiditis", "O90.5"),
    O90_8("Druge komplikacije u babinjama nesvrstane drugamo", "O90.8"),
    O90_9("Komplikacija u babinjama, nespecificirana", "O90.9"),
    O91("Infekcije dojke povezane s trudnoćom i porođajem", "O91"),
    O91_0("Infekcija bradavice povezana s trudnoćom i porođajem", "O91.0"),
    O91_1("Apsces dojke povezan s trudnoćom i porođajem", "O91.1"),
    O91_2("Nepurulentni mastitis povezan s trudnoćom i porođajem", "O91.2"),
    O92("Drugi poremećaji dojke i laktacije povezani s trudnoćom i porođajem", "O92"),
    O92_0("Uvučena bradavica povezana s trudnoćom i porođajem", "O92.0"),
    O92_1("Ragade bradavica povezane s trudnoćom i porođajem", "O92.1"),
    O92_2("Drugi i nespecificirani poremećaji dojke povezani s trudnoćom i porođajem", "O92.2"),
    O92_3("Agalakcija", "O92.3"),
    O92_4("Hipogalakcija (smanjena laktacija)", "O92.4"),
    O92_5("Obustavljena laktacija", "O92.5"),
    O92_6("Galaktoreja", "O92.6"),
    O92_7("Drugi i nespecificirani poremećaji laktacije", "O92.7"),
    O95("Porodnička smrt nespecificirana uzroka", "O95"),
    O95_0("Porodnička smrt nespecificirana uzroka", "O95.0"),
    O96("Smrt zbog bilo kojeg porodničkog uzroka koja je nastupila više od 42 dana, ali manje od jedne godine nakon porođaja", "O96"),
    O96_0("Smrt zbog bilo kojeg porodničkog uzroka koja je nastupila više od 42 dana, ali manje od jedne godine nakon porođaja", "O96.0"),
    O97("Smrt zbog posljedica izravna porodničkog uzroka", "O97"),
    O97_0("Smrt zbog posljedica izravna porodničkog uzroka", "O97.0"),
    O98("Infektivne i parazitarne bolesti majke koje su svrstane drugamo kao komplikacije trudnoće, porođaja i babinja", "O98"),
    O98_0("Tuberkuloza kao komplikacija trudnoće, porođaja i babinja", "O98.0"),
    O98_1("Sifilis kao komplikacija trudnoće, porođaja i babinja", "O98.1"),
    O98_2("Gonoreja kao komplikacija trudnoće, porođaja i babinja", "O98.2"),
    O98_3("Druge infekcije s prije svega spolnim načinom prijenosa kao komplikacije trudnoće, porođaja i babinja", "O98.3"),
    O98_4("Virusni hepatitis kao komplikacija trudnoće, porođaja i babinja", "O98.4"),
    O98_5("Druge virusne bolesti kao komplikacije trudnoće, porođaja i babinja", "O98.5"),
    O98_6("Protozoalne bolesti kao komplikacije trudnoće, porođaja i babinja", "O98.6"),
    O98_8("Druge infektivne i parazitarne bolesti majke kao komplikacije trudnoće, porođaja i babinja", "O98.8"),
    O98_9("Nespecificirane infektivne i parazitarne bolesti majke kao komplikacije trudnoće, porođaja i babinja", "O98.9"),
    O99("Druge bolesti majke svrstane drugamo kao komplikacije trudnoće, porođaja i babinja", "O99"),
    O99_0("Anemija kao komplikacija trudnoće, porođaja i babinja", "O99.0"),
    O99_1("Druge bolesti krvi i krvotvornih organa i određeni poremećaji koji zahvaćaju imunološki sustav kao komplikacije trudnoće, porođaja i babinja", "O99.1"),
    O99_2("Endokrine, metaboličke i nutritivne bolesti kao komplikacije trudnoće, porođaja i babinja", "O99.2"),
    O99_3("Duševni poremećaji i bolesti živčanoga sustava kao komplikacije trudnoće, porođaja i babinja", "O99.3"),
    O99_4("Bolesti cirkulacijskog sustava kao komplikacije trudnoće, porođaja i babinja", "O99.4"),
    O99_5("Bolesti dišnog sustava kao komplikacije trudnoće, porođaja i babinja", "O99.5"),
    O99_6("Bolesti probavnog sustava kao komplikacije trudnoće, porođaja i babinja", "O99.6"),
    O99_7("Bolesti kože i potkožnoga tkiva kao komplikacije trudnoće, porođaja i babinja", "O99.7"),
    O99_8("Druge specificirane bolesti i stanja kao komplikacije trudnoće, porođaja i babinja", "O99.8");
    
    private final String displayName;
    private final String code;
    
    MkbCodesO(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
