package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesZ {
    
    Z00("Opći pregled i ispitivanje osoba bez tegoba ili postavljene dijagnoze", "Z00"),
    Z00_0("Sistematski pregled", "Z00.0"),
    Z00_1("Sistematski pregled dojenčadi i djece", "Z00.1"),
    Z00_2("Sistematski pregled u razdoblju nagla rasta u djetinjstvu", "Z00.2"),
    Z00_3("Sistematski pregled radi utvrđivanja stanja razvoja adolescenata", "Z00.3"),
    Z00_4("Opći psihijatrijski pregled, nesvrstan drugamo", "Z00.4"),
    Z00_5("Sistematski pregled potencijalnog davatelja tkiva i organa", "Z00.5"),
    Z00_6("Pregled za usporedbu i kontrolu nalaza kliničkih istraživanja programa", "Z00.6"),
    Z00_8("Ostali sistematski pregled", "Z00.8"),
    Z01("Drugi specijalni pregled i ispitivanja osoba bez tegoba ili utvrđene dijagnoze", "Z01"),
    Z01_0("Pregled očiju i vida", "Z01.0"),
    Z01_1("Pregled uha i sluha", "Z01.1"),
    Z01_2("Pregled zubala", "Z01.2"),
    Z01_3("Mjerenje krvnoga tlaka", "Z01.3"),
    Z01_4("Ginekološki pregled (opći) (rutinski)", "Z01.4"),
    Z01_5("Dijagnostički kožni testovi i testovi na preosjetljivost", "Z01.5"),
    Z01_6("Radiološke pretrage, nesvrstane drugamo", "Z01.6"),
    Z01_7("Laboratorijske pretrage", "Z01.7"),
    Z01_8("Ostali specificirani specijalni pregledi", "Z01.8"),
    Z01_9("Specijalni pregled, nespecificiran", "Z01.9"),
    Z02("Pretrage i pregled zbog administrativnih razloga", "Z02"),
    Z02_0("Pregled za upis u obrazovnu ustanovu", "Z02.0"),
    Z02_1("Prethodni pregled prije zapošljavanja", "Z02.1"),
    Z02_2("Pregled za prijam na boravak u ustanovu", "Z02.2"),
    Z02_3("Pregled za novačenje", "Z02.3"),
    Z02_4("Pregled za izdavanje vozačke dozvole", "Z02.4"),
    Z02_5("Pregled za dozvolu za bavljenje sportom", "Z02.5"),
    Z02_6("Pregled radi osiguranja", "Z02.6"),
    Z02_7("Izdavanje liječničke svjedodžbe", "Z02.7"),
    Z02_8("Ostali pregledi zbog administrativnih razloga", "Z02.8"),
    Z02_9("Pregledi zbog administrativnih razloga, nespecificirani", "Z02.9"),
    Z03("Medicinsko promatranje i praćenje (opservacija i evaluacija) zbog sumnje na bolest i bolesna stanja", "Z03"),
    Z03_0("Promatranje zbog sumnje na tuberkulozu", "Z03.0"),
    Z03_1("Promatranje zbog sumnje na zloćudnu novotvorinu", "Z03.1"),
    Z03_2("Promatranje zbog sumnje na duševne poremećaje i poremećaje ponašanja", "Z03.2"),
    Z03_3("Promatranje zbog sumnje na poremećaje živčanog sustava", "Z03.3"),
    Z03_4("Promatranje zbog sumnje na infarkt miokarda", "Z03.4"),
    Z03_5("Promatranje zbog sumnje na druge bolesti cirkulacijskog sustava", "Z03.5"),
    Z03_6("Promatranje znakova otrovanja pri sumnji na otrovanje progutanom tvari", "Z03.6"),
    Z03_8("Promatranje zbog sumnje na druge bolesti i stanja", "Z03.8"),
    Z03_9("Promatranje zbog sumnje na bolesti i stanja, nespecificirano", "Z03.9"),
    Z04("Pregled i promatranje zbog drugih razloga", "Z04"),
    Z04_0("Test za utvrđivanje prisutnosti aklohola i lijekova u krvi", "Z04.0"),
    Z04_1("Pregled i promatranje nakon prometne nesreće", "Z04.1"),
    Z04_2("Pregled i promatranje nakon nesreće na radu", "Z04.2"),
    Z04_3("Pregled i promatranje nakon ostalih nesreća", "Z04.3"),
    Z04_4("Pregled i promatranje nakon navodnog silovanja ili zavođenja", "Z04.4"),
    Z04_5("Pregled i promatranje nakon nanesenih ozljeda", "Z04.5"),
    Z04_6("Opći psihijatrijski pregled, na zahtjev službenog organa", "Z04.6"),
    Z04_8("Pregled i promatranje zbog ostalih specificiranih razloga", "Z04.8"),
    Z04_9("Pregled i promatranje zbog ostalih nespecificiranih razloga", "Z04.9"),
    Z08("Kontrolni pregledi nakon liječenja zloćudne novotvorine", "Z08"),
    Z08_0("Kontrolni pregled nakon operacije zloćudne novotvorine", "Z08.0"),
    Z08_1("Kontrolni pregled nakon radioterapije zloćudne novotvorine", "Z08.1"),
    Z08_2("Kontrolni pregled nakon kemoterapije zloćudne novotvorine", "Z08.2"),
    Z08_7("Kontrolni pregled nakon kombinirana liječenja zloćudne novotvorine", "Z08.7"),
    Z08_8("Kontrolni pregled nakon drugih oblika liječenja zloćudne novotvorine", "Z08.8"),
    Z08_9("Kontrolni pregled nakon nespecificirana liječenja zloćudne novotvorine", "Z08.9"),
    Z09("Kontrolni pregledi nakon liječenja drugih bolesti i stanja, koja nisu zloćudne novotvorine", "Z09"),
    Z09_0("Kontrolni pregled nakon operacije zbog drugih bolesti", "Z09.0"),
    Z09_1("Kontrolni pregled nakon radioterapije zbog drugih bolesti", "Z09.1"),
    Z09_2("Kontrolni pregled nakon kemoterapije zbog drugih bolesti", "Z09.2"),
    Z09_3("Kontrolni pregled nakon psihoterapije", "Z09.3"),
    Z09_4("Kontrolni pregled nakon liječenja prijeloma", "Z09.4"),
    Z09_7("Kontrolni pregled nakon kombinirana liječenja ostalih bolesti", "Z09.7"),
    Z09_8("Kontrolni pregled nakon ostalih oblika liječenja drugih bolesti", "Z09.8"),
    Z09_9("Kontrolni pregled nakon nespecificirana liječenja ostalih bolesti", "Z09.9"),
    Z10("Sistematski pregled definiranih subpopulacija", "Z10"),
    Z10_0("Pregled zbog profesionalnih bolesti", "Z10.0"),
    Z10_1("Sistematski pregled štićenika ustanove", "Z10.1"),
    Z10_2("Sistematski pregled pripadnika vojske", "Z10.2"),
    Z10_3("Sistematski pregled članova sporstkih momčadi", "Z10.3"),
    Z10_8("Sistematski pregledi drugih definiranih subpopulacija", "Z10.8"),
    Z11("Specijalni skrining-pregled za otkrivanje zaraznih i parazitarnih bolesti", "Z11"),
    Z11_0("Specijalni skrining-pregled za otkrivanje crijevnih zaraznih bolesti", "Z11.0"),
    Z11_1("Specijalni skrining-pregled za otkrivanje plućne tuberkuloze", "Z11.1"),
    Z11_2("Specijalni skrining-pregled za otkrivanje drugih bakterijskih bolesti", "Z11.2"),
    Z11_3("Specijalni skrining-pregled za otkrivanje bolesti koje se prenose prije svega seksualnim kontaktom", "Z11.3"),
    Z11_4("Specijalni skrining-pregled za otkrivanje humanog imunodeficijencijskog virusa (HIV)", "Z11.4"),
    Z11_5("Specijalni skrining-pregled za otkrivanje drugih virusnih bolesti", "Z11.5"),
    Z11_6("Specijalni skrining-pregled za otkrivanje protozoalnih bolesti i helmintijaze", "Z11.6"),
    Z11_8("Specijalni skrining-pregled za otkrivanje drugih zaraznih i parazitarnih bolesti", "Z11.8"),
    Z11_9("Specijalni skrining-pregled za otkrivanje drugih zaraznih i parazitarnih bolesti, nespecificiran", "Z11.9"),
    Z12("Specijalni skrining-pregled za otkrivanje zloćudnih novotvorina", "Z12"),
    Z12_0("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine želuca", "Z12.0"),
    Z12_1("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine crijeva", "Z12.1"),
    Z12_2("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine dišnih organa", "Z12.2"),
    Z12_3("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine dojke", "Z12.3"),
    Z12_4("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine vrata (cerviksa) maternice", "Z12.4"),
    Z12_5("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine prostate", "Z12.5"),
    Z12_6("Specijalni skrining-pregled za otkrivanje zloćudne novotvorine mokraćnoga mjehura", "Z12.6"),
    Z12_8("Specijalni skrining-pregled za otkrivanje zloćudnih novotvorina na drugim mjestima", "Z12.8"),
    Z12_9("Specijalni skrining-pregled za otkrivanje zloćudnih novotvorina, nespecificiran", "Z12.9"),
    Z13("Specijalni skrining-pregled za otkrivanje drugih bolesti i poremećaja", "Z13"),
    Z13_0("Specijalni skrining-pregled za otkrivanje bolesti krvi i krvotvornih organa i nekih poremećaja imunološkog sustava", "Z13.0"),
    Z13_1("Specijalni skrining-pregled za otkrivanje šećerne bolesti", "Z13.1"),
    Z13_2("Specijalni skrining-pregled za otkrivanje poremećaja prehrane", "Z13.2"),
    Z13_3("Specijalni skrining-pregled za otkrivanje duševnih bolesti i poremećaja ponašanja", "Z13.3"),
    Z13_4("Specijalni skrining-pregled za otkrivanje određenih poremećaja razvoja u djetinjstvu", "Z13.4"),
    Z13_5("Specijalni skrining-pregled za otkrivanje poremećaja vida i sluha", "Z13.5"),
    Z13_6("Specijalni skrining-pregled za otkrivanje kardiovaskularnih poremećaja", "Z13.6"),
    Z13_7("Specijalni skrining-pregled za otkrivanje kongenitalnih malformacija, deformacija i kromosomske abnormalnosti", "Z13.7"),
    Z13_8("Specijalni skrining-pregled za otkrivanje drugih specificiranih bolesti i stanja", "Z13.8"),
    Z13_9("Specijalni skrining-pregled, nespecificiran", "Z13.9"),
    Z20("Izloženost ili kontakt sa zaraznim bolestima", "Z20"),
    Z20_0("Izloženost ili kontakt s crijevnim zaraznim bolestima", "Z20.0"),
    Z20_1("Izloženost ili kontakt s tuberkulozom", "Z20.1"),
    Z20_2("Izloženost ili kontakt s bolestima koje se prenose prije svega seksualnim kontaktom", "Z20.2"),
    Z20_3("Izloženost ili kontakt s bjesnoćom", "Z20.3"),
    Z20_4("Izloženost ili kontakt s rubeolom", "Z20.4"),
    Z20_5("Izloženost ili kontakt s virusnim hepatitisom", "Z20.5"),
    Z20_6("Izloženost ili kontakt s humanim imunodefinicijskim virusom (HIV)", "Z20.6"),
    Z20_7("Izloženost ili kontakt s pedikulozom, askarijazom i drugim infestacijama", "Z20.7"),
    Z20_8("Izloženost ili kontakt s drugim prenosivim bolestima", "Z20.8"),
    Z20_9("Izloženost ili kontakt s nespecificiranim prenosivim bolestima", "Z20.9"),
    Z21("Stanje asimptomatske infekcije humanim imunodeficijencijskim virusom (HIV)", "Z21"),
    Z21_0("Stanje asimptomatske infekcije humanim imunodeficijencijskim virusom (HIV)", "Z21.0"),
    Z22("Kliconoša", "Z22"),
    Z22_0("Kliconoša trbušnog tifusa", "Z22.0"),
    Z22_1("Kliconoša drugih crijevnih bolesti", "Z22.1"),
    Z22_2("Kliconoša difterije", "Z22.2"),
    Z22_3("Kliconoša drugih specificiranih zaraznih bolesti", "Z22.3"),
    Z22_4("Kliconoša bolesti koje se prenose prije svega seksualnim kontaktom", "Z22.4"),
    Z22_5("Kliconoša virusnog hepatitisa", "Z22.5"),
    Z22_6("Kliconoša infekcije humanim T-limfotropnim virusom tip 1 (HTLV-1)", "Z22.6"),
    Z22_8("Kliconoša drugih zaraznih bolesti", "Z22.8"),
    Z22_9("Kliconoša zaraznih bolesti, nespecificiran", "Z22.9"),
    Z23("Potreba za cijepljenjem protiv pojedinih bakterijskih bolesti", "Z23"),
    Z23_0("Potreba za cijepljenjem protiv kolere", "Z23.0"),
    Z23_1("Potreba za cijepljenjem protiv trbušnog tifusa i paratifusa (TAB)", "Z23.1"),
    Z23_2("Potreba za cijepljenjem protiv tuberkuloze (BCG)", "Z23.2"),
    Z23_3("Potreba za cijepljenjem protiv kuge", "Z23.3"),
    Z23_4("Potreba za cijepljenjem protiv tularemije", "Z23.4"),
    Z23_5("Potreba za cijepljenjem protiv tetanusa", "Z23.5"),
    Z23_6("Potreba za cijepljenjem protiv difterije", "Z23.6"),
    Z23_7("Potreba za cijepljenjem protiv hripavca", "Z23.7"),
    Z23_8("Potreba za cijepljenjem protiv pojedinih drugih bakterijskih bolesti", "Z23.8"),
    Z24("Potreba za cijepljenjem protiv pojedinih virusnih bolesti", "Z24"),
    Z24_0("Potreba za cijepljenjem protiv poliomijelitisa", "Z24.0"),
    Z24_1("Potreba za cijepljenjem protiv krpeljnog encefalitisa", "Z24.1"),
    Z24_2("Potreba za cijepljenjem protiv bjesnoće", "Z24.2"),
    Z24_3("Potreba za cijepljenjem protiv žute groznice", "Z24.3"),
    Z24_4("Potreba za cijepljenjem protiv ospica", "Z24.4"),
    Z24_5("Potreba za cijepljenjem protiv rubeole", "Z24.5"),
    Z24_6("Potreba za cijepljenjem protiv virusnog hepatitisa", "Z24.6"),
    Z25("Potreba za cijepljenjem protiv drugih pojedinačnih virusnih bolesti", "Z25"),
    Z25_0("Potreba za cijepljenjem protiv zaušnjaka", "Z25.0"),
    Z25_1("Potreba za cijepljenjem protiv gripe", "Z25.1"),
    Z25_8("Potreba za cijepljenjem protiv drugih specificiranih virusnih bolesti", "Z25.8"),
    Z26("Potreba za cijepljenjem protiv drugih pojedinačnih zaraznih bolesti", "Z26"),
    Z26_0("Potreba za cijepljenjem protiv lišmenijaze", "Z26.0"),
    Z26_8("Potreba za cijepljenjem protiv drugih pojedinačnih specificiranih zaraznih bolesti", "Z26.8"),
    Z26_9("Potreba za cijepljenjem protiv nespecificiranih zaraznih bolesti", "Z26.9"),
    Z27("Potreba za cijepljenjem protiv kombinacije zaraznih bolesti", "Z27"),
    Z27_0("Potreba za cijepljenjem protiv kolere s trbušnim tifusom i paratifusom (kolera + TAB)", "Z27.0"),
    Z27_1("Potreba za cijepljenjem protiv difterije - tetanusa - pertusisa, kombinirano (DTP)", "Z27.1"),
    Z27_2("Potreba za cijepljenjem protiv difterije - tetanusa - pertusisa s trbušnim tifusom i paratifusom (DTP, TAB)", "Z27.2"),
    Z27_3("Potreba za cijepljenjem protiv difterije - tetanusa - pertusisa s poliomijelitisom (DTP + polio)", "Z27.3"),
    Z27_4("Potreba za cijepljenjem protiv morbila - rubeole - parotitisa (MO RU PA)", "Z27.4"),
    Z27_8("Potreba za cijepljenjem protiv drugih kombinacija zaraznih bolesti", "Z27.8"),
    Z27_9("Potreba za cijepljenjem protiv drugih nespecificiranih kombinacija zaraznih bolesti", "Z27.9"),
    Z28("Neobavljeno cijepljenje", "Z28"),
    Z28_0("Neobavljeno cijepljenje zbog kontraindikacija", "Z28.0"),
    Z28_1("Neobavljeno cijepljenje zbog bolesnikova protivljenja iz vjerskih razloga ili zbog pritiska društvene skupine", "Z28.1"),
    Z28_2("Neobavljeno cijepljenje zbog bolesnikova protivljenja iz drugih i nespecificiranih razloga", "Z28.2"),
    Z28_8("Neobavljeno cijepljenje zbog drugih razloga", "Z28.8"),
    Z28_9("Neobavljeno cijepljenje zbog nespecificiranih razloga", "Z28.9"),
    Z29("Potreba za drugim profilaktičkim mjerama", "Z29"),
    Z29_0("Izolacija", "Z29.0"),
    Z29_1("Profilaksa imunoterapijom", "Z29.1"),
    Z29_2("Ostala profilaksa kemoterapijom", "Z29.2"),
    Z29_8("Ostale specificirane profilaktične mjere", "Z29.8"),
    Z29_9("Profilaktične mjere, nespecificirano", "Z29.9"),
    
    
    Z30("Postupci u vezi sa sprečavanjem neželjene trudnoće", "Z30."),
    Z30_0("Opći i posebni savjeti o konracepciji", "Z30."),
    Z30_1("Umetanje unutarmaterničnih i kontacepcijskih sredstava", "Z30."),
    Z30_2("Sterilizacija", "Z30."),
    Z30_3("Kiretaža (curretage)", "Z30."),
    Z30_4("Nadzor nad uporabom (uzimanjem) kontraceptiva", "Z30."),
    Z30_5("Kontrola uporabe unutarmaterničnih kontracepcijskih sredstava", "Z30."),
    Z30_8("Drugi kontracepcijski postupci", "Z30."),
    Z30_9("Kontracepcijski postupci, nespecificirano", "Z30."),
    
    Z31("Postupci u vezi s oplodnjom", "Z31."),
    Z31_0("Plastika jajovoda ili sjemenovoda (tuboplasty or vasoplasty) nakon prethodne sterilizacije", "Z31."),
    Z31_1("Umjetna oplodnja", "Z31."),
    Z31_2("In vitro oplodnja", "Z31."),
    Z31_3("Druge pomoćne metode oplodnje", "Z31."),
    Z31_4("Pretrage i testovi u vezi s oplodnjom", "Z31."),
    Z31_5("Genetsko savjetovanje", "Z31."),
    Z31_6("Opće savjetovanje i savjeti u vezi s oplodnjom", "Z31."),
    Z31_8("Drugi postupci u vezi s oplodnjom", "Z31."),
    Z31_9("Ostali nespecificirani postupci u vezi s oplodnjom", "Z31."),
    
    Z32("Pregledi i testovi na trudnoću", "Z32."),
    Z32_0("Trudnoća, još nepotvrđena", "Z32."),
    Z32_1("Trudnoća, potvrđena", "Z32."),
    
    Z33("Trudnoća, slučajna (neplanirana)", "Z33."),
    Z33_0("Trudnoća,slučajna (neplanirana)", "Z33."),
    
    Z34("Nadzor nad normalnom trudnoćom", "Z34."),
    Z34_0("Nadzor nad normalnom prvom trudnoćom", "Z34."),
    Z34_8("Nadzor nad drugim normalnim trudnoćama", "Z34."),
    Z34_9("Nadzor nad trudnoćom, nespecificiran", "Z34."),
    
    Z35("Nadzor nad visokorizičnom trudnoćom", "Z35."),
    Z35_0("Nadzor nad trudnoćom s neplodnošću u anamnezi", "Z35."),
    Z35_1("Nadzor nad trudnoćom s posljedicama prijašnjih pobačaja u anamnezi", "Z35."),
    Z35_2("Nadzor nad trudnoćom s ostalim opstetričnim i reproduktivnim nepovoljnim ishodima u anamnezi", "Z35."),
    Z35_3("Nadzor nad trudnoćom s nedovoljnom antenatalnom skrbi u anamnezi", "Z35."),
    Z35_4("Nadzor nad trudnoćom višerotkinje", "Z35."),
    Z35_5("Nadzor nad starijom prvorotkinjom", "Z35."),
    Z35_6("Nadzor nad vrlo mladom prvorotkinjom", "Z35."),
    Z35_7("Nadzor nad visokorizičnom trudnoćom zbog socijalnih problema", "Z35."),
    Z35_8("Nadzor nad drugom visokorizičnom trudnoćom", "Z35."),
    Z35_9("Nespecificirani nadzor nad visokorizičnom trudnoćom", "Z35."),
    
    Z36("Antenatalni skrining (depistaža)", "Z36."),
    Z36_0("Antenatalni skrining na kromosomske anomalije", "Z36."),
    Z36_1("Antenatalni skrining povišene razine alfa-fetoproteina", "Z36."),
    Z36_2("Ostali antenatalni skrining metodom amniocenteze", "Z36."),
    Z36_3("Antenatalni skrining deformiteta s pomoću ultrazvuka i drugih fizikalnih metoda", "Z36."),
    Z36_4("Antenatalni skrining fetalnog rasta s pomoću ultrazvuka i drugih fizikalnih metoda", "Z36."),
    Z36_5("Antenatalni skrining izoimunizacije", "Z36."),
    Z36_8("Drugi antenatalni skrining", "Z36."),
    Z36_9("Nespecificirani antenatalni skrining", "Z36."),
    
    Z37("Ishod porođaja", "Z37."),
    Z37_0("Jedno živorođeno", "Z37."),
    Z37_1("Jedno mrtvorođeno", "Z37."),
    Z37_2("Blizanci, oba živorođena", "Z37."),
    Z37_3("Blizanci, jedan živorođeni i jedan mrtvorođeni", "Z37."),
    Z37_4("Blizanci, oba mrtvorođena", "Z37."),
    Z37_5("Drugi višestruki porođaji (trojci, četvorke itd.), svi živorođeni", "Z37."),
    Z37_6("Drugi višestruki porođaji (trojci, četvorke itd.) samo neki živorođeni", "Z37."),
    Z37_7("Drugi višeplodni porođaji, (trojci, četvorke itd.) svi mrtvorođeni", "Z37."),
    Z37_9("Nespecificirano", "Z37."),
    
    Z38("Novorođenčad prema mjestu rođenja", "Z38."),
    Z38_0("Jedno, rođeno u bolnici", "Z38."),
    Z38_1("Jedno, rođeno izvan bolnice", "Z38."),
    Z38_2("Jedno, nespecificirano mjesto rođenja", "Z38."),
    Z38_3("Blizanci, rođeni u bolnici", "Z38."),
    Z38_4("Blizanci, rođeni izvan bolnice", "Z38."),
    Z38_5("Blizanci, nespecificirano mjesto rođenja", "Z38."),
    Z38_6("Više novorođenčadi (trojci, četvorke itd.), rođeni u bolnici", "Z38."),
    Z38_7("Više novorođenčadi (trojci, četvorke itd.), rođeni izvan bolnice", "Z38."),
    Z38_8("Više novorođenčadi, nespecificirano mjesto rođenja", "Z38."),
    
    Z39("Skrb i pretrage nakon porođaja", "Z39."),
    Z39_0("Skrb i pretrage neposredno nakon porođaja", "Z39."),
    Z39_1("Skrb i pretrage dojilje", "Z39."),
    Z39_2("Redovito praćenje nakon porođaja", "Z39."),
    Z40("Operacija radi profilakse", "Z40"),
    Z40_0("Operacija radi profilakse rizičnih čimbenika u vezi sa zloćudnim novotvorinama", "Z40.0"),
    Z40_8("Druga operacija radi profilakse", "Z40.8"),
    Z40_9("Operacija radi profilakse, nespecificirana", "Z40.9"),
    Z41("Ostali zahvati koji nisu vezani za liječenje narušena zdravstvenog stanja", "Z41"),
    Z41_0("Presadba kose", "Z41.0"),
    Z41_1("Druge plastične operacije zbog neprihvatljivoga kozmetskog izgleda (nagrđenosti)", "Z41.1"),
    Z41_2("Rutinsko i ritualno obrezivanje", "Z41.2"),
    Z41_3("Bušenje ušne školjke", "Z41.3"),
    Z41_8("Drugi zahvati obavljeni bez namjere liječenja stanja", "Z41.8"),
    Z41_9("Zahvati obavljeni bez namjere liječenja stanja, nespecificirani", "Z41.9"),
    Z42("Naknadno zbrinjavanje koje uključuje plastičnu operaciju", "Z42"),
    Z42_0("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na glavi i vratu", "Z42.0"),
    Z42_1("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na dojci", "Z42.1"),
    Z42_2("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na drugim dijelovima trupa", "Z42.2"),
    Z42_3("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na ruci", "Z42.3"),
    Z42_4("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na nozi", "Z42.4"),
    Z42_8("Naknadno zbrinjavanje koje uključuje plastičnu operaciju na drugim dijelovima tijela", "Z42.8"),
    Z42_9("Naknadno zbrinjavanje koje uključuje plastičnu operaciju, nespecificirano", "Z42.9"),
    Z43("Nadgledanje i zbrinjavanje umjetnih otvora", "Z43"),
    Z43_0("Nadgledanje i zbrinjavanje traheostome", "Z43.0"),
    Z43_1("Nadgledanje i zbrinjavanje gastrostome", "Z43.1"),
    Z43_2("Nadgledanje i zbrinjavanje ileostome", "Z43.2"),
    Z43_3("Nadgledanje i zbrinjavanje kolostome", "Z43.3"),
    Z43_4("Nadgledanje i zbrinjavanje drugih umjetnih otvora na probavnom sustavu", "Z43.4"),
    Z43_5("Nadgledanje i zbrinjavanje cistostome", "Z43.5"),
    Z43_6("Nadgledanje i zbrinjavanje drugih umjetnih otvora mokraćnih putova", "Z43.6"),
    Z43_7("Nadgledanje i zbrinjavanje umjetne rodnice", "Z43.7"),
    Z43_8("Nadgledanje i zbrinjavanje drugih umjetnih otvora", "Z43.8"),
    Z43_9("Nadgledanje i zbrinjavanje umjetnih otvora, nespecificirano", "Z43.9"),
    Z44("Postavljanje i podešavanje vanjskih proteza", "Z44"),
    Z44_0("Postavljanje i podešavanje umjetne ruke (kompletno) (djelomično)", "Z44.0"),
    Z44_1("Postavljanje i podešavanje umjetne noge (kompletno) (djelomično)", "Z44.1"),
    Z44_2("Postavljanje i podešavanje umjetnog oka", "Z44.2"),
    Z44_3("Postavljanje i podešavanje vanjske proteze dojke", "Z44.3"),
    Z44_8("Postavljanje i podešavanje drugih vanjskih proteza", "Z44.8"),
    Z44_9("Postavljanje i podešavanje vanjskih proteza, nespecificirano", "Z44.9"),
    Z45("Podešavanje i kontrola ugrađenih naprava", "Z45"),
    Z45_0("Podešavanje i kontrola srčanog predvodnika (pacemakera)", "Z45.0"),
    Z45_1("Podešavanje i kontrola infuzijske crpke", "Z45.1"),
    Z45_2("Podešavanje i kontrola krvnožilnih pomoćnih naprava", "Z45.2"),
    Z45_3("Podešavanje i kontrola ugrađene slušne naprave", "Z45.3"),
    Z45_8("Podešavanje i kontrola drugih naprava", "Z45.8"),
    Z45_9("Podešavanje i kontrola ugrađenih naprava, nespecificirano", "Z45.9"),
    Z46("Postavljanje i podešavanje drugih naprava", "Z46"),
    Z46_0("Postavljanje i podešavanje naočala i kontaktnih leća", "Z46.0"),
    Z46_1("Postavljanje i podešavanje slušnog pomagala", "Z46.1"),
    Z46_2("Postavljanje i podešavanje drugih naprava namijenjenih živčanom sustavu i osjetilima", "Z46.2"),
    Z46_3("Postavljanje i podešavanje zubne proteze", "Z46.3"),
    Z46_4("Postavljanje i podešavanje ortodontske naprave", "Z46.4"),
    Z46_5("Postavljanje i podešavanje ileostome i drugih crijevnih naprava", "Z46.5"),
    Z46_6("Postavljanje i podešavanje urinarnih naprava", "Z46.6"),
    Z46_7("Postavljanje i podešavanje ortopedskih naprava", "Z46.7"),
    Z46_8("Postavljanje i podešavanje drugih specificiranih naprava", "Z46.8"),
    Z46_9("Postavljanje i podešavanje naprava, nespecificirano", "Z46.9"),
    Z47("Drugo ortopedsko praćenje i zbrinjavanje", "Z47"),
    Z47_0("Praćenje i zbrinjavanje uključujući uklanjanje pločica ili drugih naprava za unutrašnju fiksaciju prijeloma", "Z47.0"),
    Z47_8("Drugo specificirano ortopedsko praćenje i zbrinjavanje", "Z47.8"),
    Z47_9("Ortopedsko praćenje i zbrinjavanje, nespecificirano", "Z47.9"),
    Z48("Drugo kirurško praćenje i zbrinjavanje", "Z48"),
    Z48_0("Nadziranje i zbrinjavanje zavoja i šavova", "Z48.0"),
    Z48_8("Drugo specificirano kirurško praćenje i zbrinjavanje", "Z48.8"),
    Z48_9("Kirurško praćenje i zbrinjavanje, nespecificirano", "Z48.9"),
    Z49("Liječenje koje uključuje dijalizu", "Z49"),
    Z49_0("Priprema bolesnika za dijalizu", "Z49.0"),
    Z49_1("Ekstrakorporalna dijaliza", "Z49.1"),
    Z49_2("Druge dijalize", "Z49.2"),
    Z50("Njega koja uključuje rehabilitacijske postupke", "Z50"),
    Z50_0("Kardijalna rehabilitacija", "Z50.0"),
    Z50_1("Druga fiziklana terapija", "Z50.1"),
    Z50_2("Rehabilitacija alkoholičara", "Z50.2"),
    Z50_3("Rehabilitacija narkomana", "Z50.3"),
    Z50_4("Psihoterapija, nesvrstana drugamo", "Z50.4"),
    Z50_5("Rehabilitacija govora", "Z50.5"),
    Z50_6("Ortoptičke vježbe (vježbe oka)", "Z50.6"),
    Z50_7("Radna terapija i profesionalna rehabilitacija, nesvrstana drugamo", "Z50.7"),
    Z50_8("Pomoć drugim rehabilitacijskim postupcima", "Z50.8"),
    Z50_9("Njega uz primjenu rehabilitacijskih postupaka, nespecificirana", "Z50.9"),
    Z51("Ostala medicinska skrb (zaštita)", "Z51"),
    Z51_0("Radioterapijsko ozračivanje (pojedinačno)", "Z51.0"),
    Z51_1("Kemoterapijska kura za novotvorine", "Z51.1"),
    Z51_2("Druge kemoterapije", "Z51.2"),
    Z51_3("Transfuzija krvi bez navođenja dijagnoze", "Z51.3"),
    Z51_4("Pripremna njega za kasnije liječenje, nesvrstana drugamo", "Z51.4"),
    Z51_5("Palijativna skrb", "Z51.5"),
    Z51_6("Hiposenzibilizacija na alergene", "Z51.6"),
    Z51_8("Druga medicinska skrb (zaštita)", "Z51.8"),
    Z51_9("Medicinska skrb (zaštita), nespecificirana", "Z51.9"),
    Z52("Davatelji organa i tkiva", "Z52"),
    Z52_0("Davatelj krvi", "Z52.0"),
    Z52_1("Davatelj kože", "Z52.1"),
    Z52_2("Davatelj kosti", "Z52.2"),
    Z52_3("Davatelj koštane srži", "Z52.3"),
    Z52_4("Davatelj bubrega", "Z52.4"),
    Z52_5("Davatelj rožnice", "Z52.5"),
    Z52_8("Davatelj drugih organa i tkiva", "Z52.8"),
    Z52_9("Davatelj organa i tkiva, nespecificiran", "Z52.9"),
    Z53("Osobe koje se koriste uslugama zdravstvene službe zbog specificiranih postupaka koji nisu obavljeni", "Z53"),
    Z53_0("Postupak neobavljen zbog kontraindikacija", "Z53.0"),
    Z53_1("Postupak neobavljen zbog bolesnikova protivljenja iz vjerskih razloga ili zbog pritiska društvene skupine", "Z53.1"),
    Z53_2("Postupak neobavljen zbog bolesnikova protivljenja iz drugih i nespecificiranih razloga", "Z53.2"),
    Z53_8("Postupak neobavljen zbog drugih specificiranih razloga", "Z53.8"),
    Z53_9("Postupak neobavljen, razlog nespecificiran", "Z53.9"),
    Z54("Oporavak", "Z54"),
    Z54_0("Oporavak nakon operacije", "Z54.0"),
    Z54_1("Oporavak nakon radioterapije", "Z54.1"),
    Z54_2("Oporavak nakon kemoterapije", "Z54.2"),
    Z54_3("Oporavak nakon psihoterapije", "Z54.3"),
    Z54_4("Oporavak nakon liječenja prijeloma", "Z54.4"),
    Z54_7("Oporavak nakon kombiniranog liječenja", "Z54.7"),
    Z54_8("Oporavak nakon ostalog liječenja", "Z54.8"),
    Z54_9("Oporavak nakon liječenja, nespecificirano", "Z54.9"),
    Z55("Problemi zbog obrazovanja i pismenosti", "Z55"),
    Z55_0("Nepismenost ili pismenost niskog stupnja", "Z55.0"),
    Z55_1("Školovanje nedostupno i nedostižno", "Z55.1"),
    Z55_2("Učestalo padanje na ispitima", "Z55.2"),
    Z55_3("Nedovoljan, polovičan uspjeh u školi", "Z55.3"),
    Z55_4("Neprilagođenost školskom sustavu i neslaganje s nastavnicima i kolegama", "Z55.4"),
    Z55_8("Drugi problemi zbog pismenosti i obrazovanja", "Z55.8"),
    Z55_9("Problemi zbog obrazovanja i pismenosti, nespecificirani", "Z55.9"),
    Z56("Problemi vezani uz zaposlenost i nezaposlenost", "Z56"),
    Z56_0("Nezaposlenost, nespecificirana", "Z56.0"),
    Z56_1("Promjena posla (radnog mjesta)", "Z56.1"),
    Z56_2("Ugroženost od gubitka namještenja", "Z56.2"),
    Z56_3("Stres zbog preopterećenosti poslom", "Z56.3"),
    Z56_4("Neslaganje s poslodavcem i kolegama", "Z56.4"),
    Z56_5("Neodgovarajući posao", "Z56.5"),
    Z56_6("Drugo tjelesno i psihičko naprezanje vezano uz rad", "Z56.6"),
    Z56_7("Ostali i nespecificirani problemi u vezi sa zapošljavanjem", "Z56.7"),
    Z57("Izloženost rizičnim čimbenicima na radnome mjestu (profesionalna)", "Z57"),
    Z57_0("Izloženost buci na radnome mjestu", "Z57.0"),
    Z57_1("Izloženost zračenju na radnome mjestu", "Z57.1"),
    Z57_2("Izloženost prašini na radnome mjestu", "Z57.2"),
    Z57_3("Izloženost drugim onečišćenjima na radnome mjestu", "Z57.3"),
    Z57_4("Izloženost otrovnim agensima na radnome mjestu u poljoprivredi", "Z57.4"),
    Z57_5("Izloženost otrovnim agensima na radnome mjestu u drugim industrijama", "Z57.5"),
    Z57_6("Izloženost nepovoljnoj temperaturi na radnome mjestu", "Z57.66"),
    Z57_7("Izloženost vibracijama na radnome mjestu", "Z57.7"),
    Z57_8("Izloženost drugim rizičnim čimbenicima na radnome mjestu", "Z57.8"),
    Z57_9("Nespecificirana izloženost rizičnim čimbenicima na radnome mjestu", "Z57.9"),
    Z58("Problemi uzrokovani fizikalnim čimbenicima okoliša", "Z58"),
    Z58_0("Izloženost buci", "Z58.0"),
    Z58_1("Izloženost onečišćenju zraka", "Z58.1"),
    Z58_2("Izloženost onečišćenju vode", "Z58.2"),
    Z58_3("Izloženost onečišćenju tla", "Z58.3"),
    Z58_4("Izloženost zračenju", "Z58.4"),
    Z58_5("Izloženost drugim onečišćenjima", "Z58.5"),
    Z58_6("Opskrba neodgovarajućom pitkom vodom", "Z58.6"),
    Z58_8("Drugi problemi izloženosti fizikalnim čimbenicima okoliša", "Z58.8"),
    Z58_9("Nespecificirani problemi izloženosti fizikalnim čimbenicima okoliša", "Z58.9"),
    Z59("Problemi stanovanja i imovinskoga stanja", "Z59"),
    Z59_0("Beskućništvo", "Z59.0"),
    Z59_1("Neodgovarajući stambeni smještaj", "Z59.1"),
    Z59_2("Nesloga sa susjedima, stanarima i kućevlasnikom", "Z59.2"),
    Z59_3("Problemi vezani uz život u ustanovama za smještaj", "Z59.3"),
    Z59_4("Manjak prikladnih namirnica", "Z59.4"),
    Z59_5("Krajnje siromaštvo", "Z59.5"),
    Z59_6("Niska primanja", "Z59.6"),
    Z59_7("Nedostatno socijalno osiguranje i socijalna pomoć", "Z59.7"),
    Z59_8("Drugi problemi stanovanja i imovinskog stanja", "Z59.8"),
    Z59_9("Nespecificirani problemi stanovanja i imovinskoga stanja", "Z59.9"),
    Z60("Problemi u vezi s društvenom okolinom", "Z60"),
    Z60_0("Problemi prilagodbe u prijelaznim životnim razdobljima", "Z60.0"),
    Z60_1("Netipične roditeljske situacije", "Z60.1"),
    Z60_2("Samački život", "Z60.2"),
    Z60_3("Teško uklapanje u lokalnu kulturu", "Z60.3"),
    Z60_4("Isključenost i neprihvaćenost od društva", "Z60.4"),
    Z60_5("Diskriminirana ili progonjena osoba", "Z60.5"),
    Z60_8("Drugi problemi u vezi s društvenom sredinom", "Z60.8"),
    Z60_9("Nespecificirani problem u vezi s društvenom sredinom", "Z60.9"),
    Z61("Teškoće vezane uz negativne događaje u djetinjstvu", "Z61"),
    Z61_0("Gubitak ljubavi u djetinjstvu", "Z61.0"),
    Z61_1("Udaljavanje od kuće u djetinjstvu", "Z61.1"),
    Z61_2("Promjena strukture odnosa u obitelji za vrijeme djetinjstva", "Z61.2"),
    Z61_3("Događaji koji su uvjetovali gubitak samopoštovanja u djetinjstvu", "Z61.3"),
    Z61_4("Problemi u vezi s navodnim seksualnim zlostavljanjem djeteta od osobe iz skupine glavnih skrbnika", "Z61.4"),
    Z61_5("Problemi u vezi s navodnim seksualnim zlostavljanjem od osobe koja ne pripada skupini glavnih skrbnika", "Z61.5"),
    Z61_6("Problemi u vezi s navodnim fizičkim zlostavljanjem djeteta", "Z61.6"),
    Z61_7("Zastrašujući događaji u djetinjstvu", "Z61.7"),
    Z61_8("Ostali negativni događaji u djetinjstvu", "Z61.8"),
    Z61_9("Nespecificirani negativni događaj u djetinjstvu", "Z61.9"),
    Z62("Drugi problemi u vezi s odgojem djeteta", "Z62"),
    Z62_0("Nedovoljni roditeljski nadzor i kontrola", "Z62.0"),
    Z62_1("Pretjerano roditeljsko štićenje djeteta", "Z62.1"),
    Z62_2("Institucijski odgoj", "Z62.2"),
    Z62_3("Neprijateljstvo prema djetetu i postupanje prema djetetu kao prema žrtvenom jarcu", "Z62.3"),
    Z62_4("Emocionalno zanemarivanje djeteta", "Z62.4"),
    Z62_5("Drugi problemi u vezi s nemarnim odgojem", "Z62.5"),
    Z62_6("Neprikladan pritisak roditelja i druge abnormalnosti u odgoju", "Z62.6"),
    Z62_8("Ostali specificirani odgojni problemi", "Z62.8"),
    Z62_9("Nespecificirani odgojni problem", "Z62.9"),
    Z63("Drugi problemi u vezi s osnovnom skupinom skrbnika, uključujući i okolnosti u obitelji", "Z63"),
    Z63_0("Problemi u bračnim odnosima", "Z63.0"),
    Z63_1("Problemi u odnosima prema roditeljima i osobama koje su postale rodbinom sklapanjem braka", "Z63.1"),
    Z63_2("Nedovoljna potpora obitelji", "Z63.2"),
    Z63_3("Odsutnost člana obitelji", "Z63.3"),
    Z63_4("Nestanak i smrt člana obitelji", "Z63.4"),
    Z63_5("Raspad obitelji zbog odvojena života i razvoda braka", "Z63.5"),
    Z63_6("Potreba uzdržavanog člana obitelji za kućnom njegom", "Z63.6"),
    Z63_7("Ostali životno važni stresni događaji koji pogađaju obitelj i kućanstvo", "Z63.7"),
    Z63_8("Ostali specificirani problemi u vezi s osnovnom skupinom skrbnika", "Z63.8"),
    Z63_9("Nespecificirani problem u vezi s osnovnom skupinom skrbnika", "Z63.9"),
    Z64("Problemi u vezi s određenim psihosocijalnim okolnostima", "Z64"),
    Z64_0("Problemi u vezi s neželjenom trudnoćom", "Z64.0"),
    Z64_1("Problemi u vezi s rađanjem više djece", "Z64.1"),
    Z64_2("Traženje i prihvaćanje poznato opasnih i štetnih fizičkih, prehrambenih i kemijskih postupaka", "Z64.2"),
    Z64_3("Traženje i prihvaćanje poznato opasnih i štetnih psiholoških postupaka i postupaka s promjenom ponašanja", "Z64.3"),
    Z64_4("Neslaganje sa savjetnicima", "Z64.4"),
    Z65("Problemi zbog drugih psihosocijalnih razloga", "Z65"),
    Z65_0("Osuda u građanskim i krivičnim postupcima bez zatvaranja", "Z65.0"),
    Z65_1("Zatvaranje i ostali oblici lišavanja slobode", "Z65.1"),
    Z65_2("Problemi u vezi s oslobađanjem iz zatvora", "Z65.2"),
    Z65_3("Problemi u vezi s ostalim pravnim postupcima", "Z65.3"),
    Z65_4("Žrtve kriminala ili terorizma", "Z65.4"),
    Z65_5("Izloženost nesreći, ratu i ostalim oblicima neprijateljstva", "Z65.5"),
    Z65_8("Drugi specificirani problemi u vezi sa psihosocijalnim okolnostima", "Z65.8"),
    Z65_9("Ostali problemi u vezi s nespecificiranim psihosocijalnim okolnostima", "Z65.9"),
    Z70("Savjetovanje o stavovima, ponašanju i orijentaciji o spolnosti", "Z70"),
    Z70_0("Savjetovanje o stavovima o spolnosti", "Z70.0"),
    Z70_1("Savjetovanje u vezi s bolesnikovim seksualnim ponašanjem i orijentacijom", "Z70.1"),
    Z70_2("Savjetovanje o spolnom ponašanju i orijentiranosti druge osobe", "Z70.2"),
    Z70_3("Savjetovanje zbog niza briga oko stava, ponašanja i orijentacije u vezi sa spolnošću", "Z70.3"),
    Z70_8("Ostalo savjetovanje o spolnim problemima", "Z70.8"),
    Z70_9("Nespecificirano savjetovanje o spolnim problemima", "Z70.9"),
    Z71("Osobe koje od zdravstvene službe traže socijalne i medicinske savjete nesvrstani drugamo", "Z71"),
    Z71_0("Osoba koja traži savjet u ime nekoga drugoga", "Z71.0"),
    Z71_1("Osoba za koju postoji bojazan da je bolesna, a u koje dijagnoza nije postavljena", "Z71.1"),
    Z71_2("Bolesnik koji traži da mu se rastumače nalazi", "Z71.2"),
    Z71_3("Savjeti i nadzor nad prehranom", "Z71.3"),
    Z71_4("Savjetovanje i nadziranje alkoholičara", "Z71.4"),
    Z71_5("Savjetovanje i nadziranje narkomana", "Z71.5"),
    Z71_6("Savjetovanje pušača", "Z71.6"),
    Z71_7("Savjetovanje u vezi s HIV-om", "Z71.7"),
    Z71_8("Ostalo savjetovanje, specificirano", "Z71.8"),
    Z71_9("Savjetovanje, nespecificirano", "Z71.9"),
    Z72("Problemi u vezi s načinom života", "Z72"),
    Z72_0("Pušenje", "Z72.0"),
    Z72_1("Pijenje", "Z72.1"),
    Z72_2("Drogiranje", "Z72.2"),
    Z72_3("Nedovoljno tjelesno vježbanje", "Z72.3"),
    Z72_4("Neprikladna prehrana i jedenje", "Z72.4"),
    Z72_5("Visokorizično spolno ponašanje", "Z72.5"),
    Z72_6("Kockanje i klađenje", "Z72.6"),
    Z72_8("Ostali problemi u vezi s načinom života", "Z72.8"),
    Z72_9("Problem u vezi s načinom života, nespecificiran", "Z72.9"),
    Z73("Problemi u vezi s organiziranjem vlastita života", "Z73"),
    Z73_0("Krajnja iscrpljenost", "Z73.0"),
    Z73_1("Isticanje crta ličnosti", "Z73.1"),
    Z73_2("Nedostatak opuštanja i dokolice", "Z73.2"),
    Z73_3("Stres, nesvrstan drugamo", "Z73.3"),
    Z73_4("Neodgovarajući život u društvu, nesvrstan drugamo", "Z73.4"),
    Z73_5("Sukob s ulogom u društvu, nesvrstan drugamo", "Z73.5"),
    Z73_6("Ograničenje aktivnosti zbog invalidnosti", "Z73.6"),
    Z73_8("Drugi problemi u vezi s organiziranjem vlastita života", "Z73.8"),
    Z73_9("Problem u vezi s organiziranjem vlastita života, nespecificiran", "Z73.9"),
    Z74("Problemi u vezi s ovisnošću o davatelju njege", "Z74"),
    Z74_0("Smanjena pokretljivost", "Z74.0"),
    Z74_1("Potrebna pomoć kod osobne higijene", "Z74.1"),
    Z74_2("Potrebna pomoć u kući ako nitko u kućanstvu ne može pružati njegu", "Z74.2"),
    Z74_3("Potreba za stalnim nadzorom", "Z74.3"),
    Z74_8("Drugi problemi u vezi s ovisnošću o davatelju njege", "Z74.8"),
    Z74_9("Problem u vezi s ovisnošću o davatelju njege, nespecificiran", "Z74.9"),
    Z75("Problemi u vezi s medicinskim ustanovama i ostalim oblicima zaštite zdravlja", "Z75"),
    Z75_0("Nemogućnost pružanja medicinske pomoći u kući", "Z75.0"),
    Z75_1("Čekanje na prijam u drugu odgovarajuću ustanovu", "Z75.1"),
    Z75_2("Ostala razdoblja čekanja na pretrage i liječenje", "Z75.2"),
    Z75_3("Neraspolaganje ustanovama za pružanje zaštite i njihova nedostupnost", "Z75.3"),
    Z75_4("Neraspolaganje drugim ustanovama za pružanje zaštite i njihova nedostupnost", "Z75.4"),
    Z75_5("Odmor njegovatelja", "Z75.5"),
    Z75_8("Drugi problemi u vezi sa zdravstvenim ustanovama", "Z75.8"),
    Z75_9("Nespecificirani problem u vezi sa zdravstvenim ustanovama i ostalim oblicima zdravstvene skrbi", "Z75.9"),
    Z76("Osobe koje kontaktiraju zdravstvenu službu u drugim okolnostima", "Z76"),
    Z76_0("Ponovno izdavanje recepta", "Z76.0"),
    Z76_1("Zdravstveni nadzor i njega nađene djece", "Z76.1"),
    Z76_2("Zdravstveni nadzor i njega ostale zdrave dojenčadi i djece", "Z76.2"),
    Z76_3("Zdravi pratilac bolesnika", "Z76.3"),
    Z76_4("Smještanje druge osobe, a ne bolesnika, u zdravstvenu ustanovu", "Z76.4"),
    Z76_5("Simulant", "Z76.5"),
    Z76_8("Osobe koje kontaktiraju zdravstvenu službu u drugim specificiranim okolnostima", "Z76.8"),
    Z76_9("Osobe koje kontaktiraju zdravstvenu službu u nespecificiranim okolnostima", "Z76.9"),
    Z80("Zloćudne novotovorine u obiteljskoj anamnezi", "Z80"),
    Z80_0("Zloćudne novotvorine probavnih organa u obiteljskoj anamnezi", "Z80.0"),
    Z80_1("Zloćudne novotvorine dušnika, dušnice, pluća u obiteljskoj anamnezi", "Z80.1"),
    Z80_2("Zloćudne novotvorine drugih respiratornih i intratorakalnih organa u obiteljskoj anamnezi", "Z80.2"),
    Z80_3("Zloćudne novotvorine dojke u obiteljskoj anamnezi", "Z80.3"),
    Z80_4("Zloćudne novotvorine spolnih organa u obiteljskoj anamnezi", "Z80.4"),
    Z80_5("Zloćudne novotvorine urinarnog sustava u obiteljskoj anamanezi", "Z80.5"),
    Z80_6("Leukemija u obiteljskoj anamnezi", "Z80.6"),
    Z80_7("Ostale zloćudne novotvorine limfoidnih, hematopoeznih i srodnih tkiva u obiteljskoj anamnezi", "Z80.7"),
    Z80_8("Zloćudne novotvorine drugih organa ili sustava u obiteljskoj anamnezi", "Z80.8"),
    Z80_9("Zloćudne novotvorine u obiteljskoj anamnezi, nespecificirane", "Z80.9"),
    Z81("Duševni poremećaji i poremećaji ponašanja u obiteljskoj anamnezi", "Z81"),
    Z81_0("Duševna zaostalost u obiteljskoj anamnezi", "Z81.0"),
    Z81_1("Ovisnost o alkoholu u obiteljskoj anamnezi", "Z81.1"),
    Z81_2("Ovisnost o pušenju u obiteljskoj anamnezi", "Z81.2"),
    Z81_3("Ostali oblici ovisnosti o psihoaktivnim tvarima u obiteljskoj anamnezi", "Z81.3"),
    Z81_4("Drugi oblici ovisnosti u obiteljskoj anamnezi", "Z81.4"),
    Z81_8("Ostali duševni poremećaji i poremećaji ponašanja u obiteljskoj anamnezi", "Z81.8"),
    Z82("Pojedine invalidnosti i kronične bolesti koje završavaju invalidnošću u obiteljskoj anamnezi", "Z82"),
    Z82_0("Epilepsija i druge bolesti živčanog sustava u obiteljskoj anamnezi", "Z82.0"),
    Z82_1("Sljepoća i gubitak vida u obiteljskoj anamnezi", "Z82.1"),
    Z82_2("Gluhoća i gubitak sluha u obiteljskoj anamnezi", "Z82.2"),
    Z82_3("Moždani udar u obiteljskoj anamnezi", "Z82.3"),
    Z82_4("Ishemična bolest srca i druge bolesti cirkulacijskog sustava u obiteljskoj anamnezi", "Z82.4"),
    Z82_5("Astma i druge kronične bolesti donjih dišnih putova u obiteljskoj anamnezi", "Z82.5"),
    Z82_6("Artritis i druge bolesti mišićno-koštanog sustava i vezivnoga tkiva u obiteljskoj anamnezi", "Z82.6"),
    Z82_7("Kongenitalne malformacije, deformacije i kromosomske abnormalnosti u obiteljskoj anamnezi", "Z82.7"),
    Z82_8("Invalidnost, drugi poremećaji i kronične bolesti koje završavaju invalidnošću u obiteljskoj anamnezi, nesvrstane drugamo", "Z82.8"),
    Z83("Ostali specifični poremećaji u obiteljskoj anamnezi", "Z83"),
    Z83_0("HIV-bolest u obiteljskoj anamnezi", "Z83.0"),
    Z83_1("Druge zarazne i parazitarne bolesti u obiteljskoj anamnezi", "Z83.1"),
    Z83_2("Bolesti krvi i krvotvornih organa i neki poremećaji imunološkog sustava u obiteljskoj anamnezi", "Z83.2"),
    Z83_3("Šećerna bolest u obiteljskoj anamnezi", "Z83.3"),
    Z83_4("Endokrine bolesti, poremećaji metabolizma i prehrane u obiteljskoj anamnezi", "Z83.4"),
    Z83_5("Poremećaji vida i sluha u obiteljskoj anamnezi", "Z83.5"),
    Z83_6("Bolesti dišnog sustava u obiteljskoj anamnezi", "Z83.6"),
    Z83_7("Bolesti probavnog sustava u obiteljskoj anamnezi", "Z83.7"),
    Z84("Ostale bolesti i stanja u obiteljskoj anamnezi", "Z84"),
    Z84_0("Bolesti kože i potkožnih tkiva u obiteljskoj anamnezi", "Z84.0"),
    Z84_1("Bolesti bubrega i uretera u obiteljskoj anamnezi", "Z84.1"),
    Z84_2("Bolesti genitourinarnog sustava u obiteljskoj anamnezi", "Z84.2"),
    Z84_3("Konsangvinitet u obiteljskoj anamnezi", "Z84.3"),
    Z84_8("Druga naznačena stanja u obiteljskoj anamnezi", "Z84.8"),
    Z85("Zloćudne novotvorine u osobnoj anamnezi", "Z85"),
    Z85_0("Zloćudne novotvorine probavnih organa u osobnoj anamnezi", "Z85.0"),
    Z85_1("Zloćudne novotvorine dušnika, bronha i pluća u osobnoj anamnezi", "Z85.1"),
    Z85_2("Zloćudne novotvorine drugih respiratornih i intratorakalnih organa u osobnoj anamnezi", "Z85.2"),
    Z85_3("Zloćudne novotvorine dojke u osobnoj anamnezi", "Z85.3"),
    Z85_4("Zloćudne novotvorine spolnih organa u osobnoj anamnezi", "Z85.4"),
    Z85_5("Zloćudne novotvorine urinarnog sustava u osobnoj anamnezi", "Z85.5"),
    Z85_6("Leukemija u osobnoj anamnezi", "Z85.6"),
    Z85_7("Ostale zloćudne novotvorine limfoidnih, hematopoeznih i srodnih tkiva u osobnoj anamnezi", "Z85.7"),
    Z85_8("Zloćudne novotvorine drugih organa ili sustava u osobnoj anamnezi", "Z85.8"),
    Z85_9("Zloćudne novotvorine u osobnoj anamnezi, nespecificirane", "Z85.9"),
    Z86("Dokazane druge bolesti u osobnoj anamnezi", "Z86"),
    Z86_0("Zloćudne novotvorine u osobnoj anamnezi", "Z86.0"),
    Z86_1("Zarazne i parazitarne bolesti u osobnoj anamnezi", "Z86.1"),
    Z86_2("Bolesti krvi i krvotvornih organa i nekih poremećaja imunološkog sustava u osobnoj anamnezi", "Z86.2"),
    Z86_3("Endokrine bolesti, bolesti prehrane i metabolizma u osobnoj anamnezi", "Z86.3"),
    Z86_4("Ovisnost o psihoaktivnim tvarima u osobnoj anamnezi", "Z86.4"),
    Z86_5("Duševni poremećaji i poremećaji ponašanja u osobnoj anamnezi", "Z86.5"),
    Z86_6("Bolesti živčanog sustava i organa osjetila u osobnoj anamnezi", "Z86.6"),
    Z86_7("Bolesti srca i krvnožilnog sustava u osobnoj anamnezi", "Z86.7"),
    Z87("Ostale bolesti i stanja u osobnoj anamnezi", "Z87"),
    Z87_0("Bolesti dišnog sustava u osobnoj anamnezi", "Z87.0"),
    Z87_1("Bolesti probavnog sustava u osobnoj anamnezi", "Z87.1"),
    Z87_2("Bolesti kože i potkožnoga tkiva u osobnoj anamnezi", "Z87.2"),
    Z87_3("Bolesti mišićno-koštanog sustava i vezivnoga tkiva u osobnoj anamnezi", "Z87.3"),
    Z87_4("Bolesti genitourinarnog sustava u osobnoj anamnezi", "Z87.4"),
    Z87_5("Komplikacije u trudnoći, porođaju i babinjama u osobnoj anamnezi", "Z87.5"),
    Z87_6("Određena stanja nastala u novorođenačkom razdoblju u osobnoj anamnezi", "Z87.6"),
    Z87_7("Priorođene malformacije, deformiteti i kromosomske abnormalnosti u osobnoj anamnezi", "Z87.7"),
    Z87_8("Druga specificirana stanja u osobnoj anamnezi", "Z87.8"),
    Z88("Alergija na lijekove, medicinske preparate i biološke tvari u osobnoj anamnezi", "Z88"),
    Z88_0("Alergija na penicilin u osobnoj anamnezi", "Z88.0"),
    Z88_1("Alergija na druge antibiotike u osobnoj anamnezi", "Z88.1"),
    Z88_2("Alergija na sulfonamide u osobnoj anamnezi", "Z88.2"),
    Z88_3("Alergija na druge antiinfektivne lijekove u osobnoj anamnezi", "Z88.3"),
    Z88_4("Alergija na anestetska sredstva u osobnoj anamnezi", "Z88.4"),
    Z88_5("Alergija na narkotička sredstva u osobnoj anamnezi", "Z88.5"),
    Z88_6("Alergija na analgetska sredstva u osobnoj anamnezi", "Z88.6"),
    Z88_7("Alergija na serume i cjepiva u osobnoj anamnezi", "Z88.7"),
    Z88_8("Alergija na druge lijekove, medicinske preparate i biološka sredstva u osobnoj anamnezi", "Z88.8"),
    Z88_9("Alergija na nespecificirane lijekove, medicinske preparate i biološka sredstva u osobnoj anamnezi", "Z88.9"),
    Z89("Stečeni gubitak udova", "Z89"),
    Z89_0("Stečeni gubitak prsta(iju) (uključujući palac), jednostrani", "Z89.0"),
    Z89_1("Stečeni gubitak šake i ručnoga zgloba", "Z89.1"),
    Z89_2("Stečeni gubitak ruke iznad ručnoga zgloba", "Z89.2"),
    Z89_3("Stečeni gubitak obiju ruku (sve razine)", "Z89.3"),
    Z89_4("Stečeni gubitak stopala i gležnja", "Z89.4"),
    Z89_5("Stečeni gubitak noge do ili ispod koljena", "Z89.5"),
    Z89_6("Stečeni gubitak noge iznad koljena", "Z89.6"),
    Z89_7("Stečeni gubitak obiju nogu (sve razine, osim kada nedostaju samo prsti stopala)", "Z89.7"),
    Z89_8("Stečeni gubitak ruke i noge (sve razine)", "Z89.8"),
    Z89_9("Stečeni gubitak uda, nespecificiran", "Z89.9"),
    Z90("Stečeni gubici organa, nesvrstani drugamo", "Z90"),
    Z90_0("Stečeni gubitak dijela glave i vrata", "Z90.0"),
    Z90_1("Stečeni gubitak dojke(i)", "Z90.1"),
    Z90_2("Stečeni gubitak jetre (dijela)", "Z90.2"),
    Z90_3("Stečeni gubitak dijelova želuca", "Z90.3"),
    Z90_4("Stečeni gubitak drugih dijelova probavnog sustava", "Z90.4"),
    Z90_5("Stečeni gubitak bubrega", "Z90.5"),
    Z90_6("Stečeni gubitak drugih dijelova urinarnog sustava", "Z90.6"),
    Z90_7("Stečeni gubitak spolnih organa", "Z90.7"),
    Z90_8("Stečeni gubitak drugih organa", "Z90.8"),
    Z91("Rizični čimbenici u osobnoj anamnezi, nesvrstani drugamo", "Z91"),
    Z91_0("Alergija na druge tvari, izuzevši lijekove i biološke tvari, u osobnoj anamnezi", "Z91.0"),
    Z91_1("Neobavljanje medicinskog liječenja i nepridržavanje propisanog načina života u osobnoj anamnezi", "Z91.1"),
    Z91_2("Loša osobna higijena u osobnoj anamnezi", "Z91.2"),
    Z91_3("Nezdravi raspored (ritam) spavanja i budnosti u osobnoj anamnezi", "Z91.3"),
    Z91_4("Psihološka trauma u osobnoj anamnezi, nesvrstana drugamo", "Z91.4"),
    Z91_5("Samoozljeđivanje u osobnoj anamnezi", "Z91.5"),
    Z91_6("Druga psihička trauma u osobnoj anamnezi", "Z91.6"),
    Z91_8("Ostali nesvrstani rizični čimbenici u osobnoj anamnezi, nesvrstani drugamo", "Z91.8"),
    Z92("Medicinsko liječenje u osobnoj anamnezi", "Z92"),
    Z92_0("Kontracepcija u osobnoj anamnezi", "Z92.0"),
    Z92_1("Dugotrajno uzimanje antikoagulatnih lijekova (i sada) u osobnoj anamnezi", "Z92.1"),
    Z92_2("Dugotrajno uzimanje drugih lijekova (i sada) u osobnoj anamnezi", "Z92.2"),
    Z92_3("Zračenje u osobnoj anamnezi", "Z92.3"),
    Z92_4("Velika operacija u osobnoj anamnezi, nesvrstana drugamo", "Z92.4"),
    Z92_5("Rehabilitacija u osobnoj anamnezi", "Z92.5"),
    Z92_8("Drugo medicinsko liječenje u osobnoj anamnezi", "Z92.8"),
    Z92_9("Medicinsko liječenje u osobnoj anamnezi, nespecificirano", "Z92.9"),
    Z93("Stanje nakon uspostavljanja umjetnih otvora", "Z93"),
    Z93_0("Stanje traheostome", "Z93.0"),
    Z93_1("Stanje gastrostome", "Z93.1"),
    Z93_2("Stanje ileostome", "Z93.2"),
    Z93_3("Stanje kolostome", "Z93.3"),
    Z93_4("Stanje drugih umjetnih otvora u probavnom sustavu", "Z93.4"),
    Z93_5("Stanje cistostome", "Z93.5"),
    Z93_6("Stanje drugih umjetnih otvora mokraćnih putova", "Z93.6"),
    Z93_8("Stanje drugih umjetnih otvora", "Z93.8"),
    Z93_9("Stanje umjetnih otvora, nespecificirano", "Z93.9"),
    Z94("Stanje nakon presadbe organa i tkiva", "Z94"),
    Z94_0("Stanje nakon presadbe bubrega", "Z94.0"),
    Z94_1("Stanje nakon presadbe srca", "Z94.1"),
    Z94_2("Stanje nakon presadbe pluća", "Z94.2"),
    Z94_3("Stanje nakon presadbe srca i pluća", "Z94.3"),
    Z94_4("Stanje nakon presadbe jetre", "Z94.4"),
    Z94_5("Stanje nakon presadbe kože", "Z94.5"),
    Z94_6("Stanje nakon presadbe kosti", "Z94.6"),
    Z94_7("Stanje nakon presadbe rožnice", "Z94.7"),
    Z94_8("Stanje nakon presadbe drugih organa i tkiva", "Z94.8"),
    Z94_9("Stanje nakon presadbe organa i tkiva, nespecificirano", "Z94.9"),
    Z95("Prisutnost srčanih i krvnožilnih usadaka (implantata) i presađenih dijelova", "Z95"),
    Z95_0("Prisutnost srčanog predvodnika (pacemakera)", "Z95.0"),
    Z95_1("Prisutnost aortokoronarnog premoštenja (bypass) presađivanjem dijelova žile", "Z95.1"),
    Z95_2("Prisutnost srčanog zaliska - proteze", "Z95.2"),
    Z95_3("Prisutnost srčanog zaliska - biološkog podrijetla", "Z95.3"),
    Z95_4("Prisutnost drugih srčanih zalistaka", "Z95.4"),
    Z95_5("Prisutnost koronarnih angioplastičnih umetaka i presađenih dijelova", "Z95.5"),
    Z95_8("Prisutnost drugih srčanih i krvnožilnih usadaka i presađenih dijelova", "Z95.8"),
    Z95_9("Prisutnost srčanih i krvnožilnih usadaka i presađenih dijelova, nespecificirana", "Z95.9"),
    Z96("Prisutnost drugih funkcionalnih usadaka (implantata)", "Z96"),
    Z96_0("Prisutnost urogenitalnih implantata", "Z96.0"),
    Z96_1("Prisutnost intraokularne leće", "Z96.1"),
    Z96_2("Prisutnost ušnih i slušnih implantata", "Z96.2"),
    Z96_3("Prisutnost umjetnog grkljana", "Z96.3"),
    Z96_4("Prisutnost endokrinih implantata", "Z96.4"),
    Z96_5("Prisutnost zubnih usadaka i implantata donje čeljusti", "Z96.5"),
    Z96_6("Prisutnost ortopedskih implantata zglobova", "Z96.6"),
    Z96_7("Prisutnost drugih implantata kostiju i tetiva", "Z96.7"),
    Z96_8("Prisutnost drugih specificiranih funkcionalnih implantata", "Z96.8"),
    Z96_9("Prisutnost funkcionalnih implantata, nespecificirana", "Z96.9"),
    Z97("Prisutnost ostalih naprava", "Z97"),
    Z97_0("Prisutnost umjetnog oka", "Z97.0"),
    Z97_1("Prisutnost umjetnog uda (potpuna, djelomična)", "Z97.1"),
    Z97_2("Prisutnost zubne proteze (potpuna, djelomična)", "Z97.2"),
    Z97_3("Prisutnost naočala i kontaktnih leća", "Z97.3"),
    Z97_4("Prisutnost vanjskoga slušnog pomagala", "Z97.4"),
    Z97_5("Prisutnost intrauterinog kontracepcijskog sredstva", "Z97.5"),
    Z97_8("Prisutnost drugih specificiranih pomagala", "Z97.8"),
    Z98("Druga stanja nakon operacija", "Z98"),
    Z98_0("Stanje nakon premoštenja i spajanja crijeva", "Z98.0"),
    Z98_1("Stanje nakon artrodeze (kirurško zakočenje zgloba)", "Z98.1"),
    Z98_2("Stanje nakon ugradnje naprave za drenažu cerebrospinalne tekućine", "Z98.2"),
    Z98_8("Druga specificirana stanja nakon operacije", "Z98.8"),
    Z99("Ovisnost o napravama i pomagalima, nesvrstana drugamo", "Z99"),
    Z99_0("Ovisnost o aspiratoru", "Z99.0"),
    Z99_1("Ovisnost o respiratoru (umjetna pluća)", "Z99.1"),
    Z99_2("Ovisnost o dijalizi bubrega", "Z99.2"),
    Z99_3("Ovisnost o invalidskim kolicima", "Z99.3"),
    Z99_8("Ovisnost o drugim napravama i pomagalima", "Z99.8"),
    Z99_9("Ovisnost o napravama i pomagalima, nespecificirana", "Z99.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesZ(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
