package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesD {
    
    D00("Karcinom in situ usne šupljine, jednjaka i želuca", "D00"),
    D00_0("Usna, usna šupljina i ždrijelo", "D00.0"),
    D00_1("Jednjak", "D00.1"),
    D00_2("Karcinom in situ, želudac", "D00.2"),
    D01("Karcinom in situ ostalih i nespecificiranih probavnih organa", "D01"),
    D01_0("Debelo crijevo (kolon)", "D01.0"),
    D01_1("Rektosigmoidni prijelaz", "D01.1"),
    D01_2("Završno debelo crijevo (rektum)", "D01.2"),
    D01_3("Anus i analni kanal", "D01.3"),
    D01_4("Ostali i nespecificirani dijelovi crijeva", "D01.4"),
    D01_5("Jetra, žučni mjehur i žučni vodovi", "D01.5"),
    D01_7("Ostali specificirani probavni organi", "D01.7"),
    D01_9("Probavni organ, nespecificiran", "D01.9"),
    D02("Karcinom in situ srednjeg uha i dišnog sustava", "D02"),
    D02_0("Grkljan (larinks)", "D02.0"),
    D02_1("Dušnik (traheja)", "D02.1"),
    D02_2("Bronh i pluća", "D02.2"),
    D02_3("Ostali dijelovi dišnog sustava", "D02.3"),
    D02_4("Dišni sustav, nespecificiran", "D02.4"),
    D03("Melanom in situ", "D03"),
    D03_0("Melanom in situ usne", "D03.0"),
    D03_1("Melanom in situ očne vjeđe, uključujući kantus", "D03.1"),
    D03_2("Melanom in situ uha i vanjskoga ušnog kanala", "D03.2"),
    D03_3("Melanom in situ ostalih i nespecificiranih dijelova lica", "D03.3"),
    D03_4("Melanom in situ vlasišta i vrata", "D03.4"),
    D03_5("Melanom in situ trupa", "D03.5"),
    D03_6("Melanom in situ ruke, uključujući rame", "D03.6"),
    D03_7("Melanom in situ noge, uključujući kuk", "D03.7"),
    D03_8("Melanom in situ ostalih sijela", "D03.8"),
    D03_9("Melanom in situ, nespecificiran", "D03.9"),
    D04("Karcinom in situ kože", "D04"),
    D04_0("Koža usne", "D04.0"),
    D04_1("Koža očne vjeđe, uključujući kantus", "D04.1"),
    D04_2("Koža uha i vanjskoga ušnog kanala", "D04.2"),
    D04_3("Koža ostalih i nespecificiranih dijelova lica", "D04.3"),
    D04_4("Koža vlasišta i vrata", "D04.4"),
    D04_5("Koža trupa", "D04.5"),
    D04_6("Koža ruke, uključujući rame", "D04.6"),
    D04_7("Koža noge, uključujući kuk", "D04.7"),
    D04_8("Koža ostalih sijela", "D04.8"),
    D04_9("Koža, nespecificirana", "D04.9"),
    D05("Karcinom in situ dojke", "D05"),
    D05_0("Lobularni karcinom in situ", "D05.0"),
    D05_1("Intraduktalni karcinom in situ", "D05.1"),
    D05_7("Ostali karcinomi dojke in situ", "D05.7"),
    D05_9("Karcinom in situ dojke, nespecificiran", "D05.9"),
    D06("Karcinom in situ vrata maternice (cerviksa uterusa)", "D06"),
    D06_0("Endocerviks", "D06.0"),
    D06_1("Egzocerviks", "D06.1"),
    D06_7("Ostali dijelovi cerviksa", "D06.7"),
    D06_9("Cerviks, nespecificiran", "D06.9"),
    D07("Karcinom in situ ostalih i nespecificiranih spolnih organa", "D07"),
    D07_0("Endometrij", "D07.0"),
    D07_1("Stidnica (vulva)", "D07.1"),
    D07_2("Rodnica (vagina)", "D07.2"),
    D07_3("Ostali i nespecificirani ženski spolni organi", "D07.3"),
    D07_4("Spolni ud (penis)", "D07.4"),
    D07_5("Prostata", "D07.5"),
    D07_6("Ostali i nespecificirani muški spolni organi", "D07.6"),
    D09("Karcinom in situ ostalih i nespecificiranih sijela", "D09"),
    D09_0("Mokraćni mjehur", "D09.0"),
    D09_1("Ostali i nespecificirani urinarni organi", "D09.1"),
    D09_2("Oko", "D09.2"),
    D09_3("Karcinom in situ, štitnjača i ostale endokrine žlijezde", "D09.3"),
    D09_7("Karcinom in situ ostalih specificiranih sijela", "D09.7"),
    D09_9("Karcinom in situ, nespecificiran", "D09.9"),
    D10("Dobroćudna novotvorina usta i ždrijela", "D10"),
    D10_0("Usna", "D10.0"),
    D10_1("Jezik", "D10.1"),
    D10_2("Dno usta", "D10.2"),
    D10_3("Ostali i nespecificirani dijelovi usta", "D10.3"),
    D10_4("Tonzila", "D10.4"),
    D10_5("Ostali dijelovi orofarinksa", "D10.5"),
    D10_6("Nazofarinks", "D10.6"),
    D10_7("Hipofarinks", "D10.7"),
    D10_9("Farinks, nespecificiran", "D10.9"),
    D11("Dobroćudna novotvorina velikih žlijezda slinovnica", "D11"),
    D11_0("Parotidna žlijezda", "D11.0"),
    D11_7("Ostale velike žlijezde slinovnice", "D11.7"),
    D11_9("Velika žlijezda slinovnica, nespecificirana", "D11.9"),
    D12("Dobroćudna novotvorina kolona, rektuma, anusa i analnog kanala", "D12"),
    D12_0("Cekum", "D12.0"),
    D12_1("Crvuljak (apendiks)", "D12.1"),
    D12_2("Uzlazno debelo crijevo (ascendentni kolon)", "D12.2"),
    D12_3("Poprečno debelo crijevo (transverzalni kolon)", "D12.3"),
    D12_4("Silazno debelo crijevo (descendentni kolon)", "D12.4"),
    D12_5("Sigmoidni kolon", "D12.5"),
    D12_6("Kolon, nespecificiran", "D12.6"),
    D12_7("Rektosigmoidni prijelaz", "D12.7"),
    D12_8("Završno debelo crijevo (rektum)", "D12.8"),
    D12_9("Dobroćudna novotvorina, čmar (anus) i analni kanal", "D12.9"),
    D13("Dobroćudna novotvorina ostalih i nedovoljno definiranih dijelova probavnog sustava", "D13"),
    D13_0("Jednjak", "D13.0"),
    D13_1("Dobroćudna novotvorina želuca", "D13.1"),
    D13_2("Dvanaesnik (duodenum)", "D13.2"),
    D13_3("Ostali i nespecificirani dijelovi tankoga crijeva", "D13.3"),
    D13_4("Jetra", "D13.4"),
    D13_5("Ekstrahepatični žučni vodovi", "D13.5"),
    D13_6("Gušterača", "D13.6"),
    D13_7("Endokrina gušterača", "D13.7"),
    D13_9("Nedovoljno definirana sijela u probavnom sustavu", "D13.9"),
    D14("Dobroćudna novotvorina srednjeg uha i dišnog sustava", "D14"),
    D14_0("Srednje uho, nosna šupljina i akcesorni sinusi", "D14.0"),
    D14_1("Grkljan (larinks)", "D14.1"),
    D14_2("Dušnik (traheja)", "D14.2"),
    D14_3("Bronh i pluća", "D14.3"),
    D14_4("Dišni sustav, nespecificiran", "D14.4"),
    D15("Dobroćudna novotvorina ostalih i nespecificiranih intratorakalnih organa", "D15"),
    D15_0("Prsna žlijezda (timus)", "D15.0"),
    D15_1("Srce", "D15.1"),
    D15_2("Sredoprsje (medijastinum)", "D15.2"),
    D15_3("Ostali specificirani intratorakalni organi", "D15.3"),
    D15_9("Intratorakalni organ, nespecificiran", "D15.9"),
    D16("Dobroćudna novotvorina kosti i zglobne hrskavice", "D16"),
    D16_0("Lopatica (skapula) i dugačke kosti ruke", "D16.0"),
    D16_1("Kratke kosti ruke", "D16.1"),
    D16_2("Dugačke kosti noge", "D16.2"),
    D16_3("Kratke kosti noge", "D16.3"),
    D16_4("Kosti lubanje i lica", "D16.4"),
    D16_5("Kost donje čeljusti", "D16.5"),
    D16_6("Kralježnica", "D16.6"),
    D16_7("Rebra, sternum i klavikula", "D16.7"),
    D16_8("Zdjelične kosti, sakrum i kokcigij", "D16.8"),
    D16_9("Kost i zglobna hrskavica, nespecificirani", "D16.9"),
    D17("Dobroćudne lipomatozne novotvorine", "D17"),
    D17_0("Dobroćudna lipomatozna novotvorina kože i potkožnoga tkiva glave, lica i vrata", "D17.0"),
    D17_1("Dobroćudna lipomatozna novotvorina kože i potkožnoga tkiva trupa", "D17.1"),
    D17_2("Dobroćudna lipomatozna novotvorina kože i potkožnoga tkiva udova", "D17.2"),
    D17_3("Dobroćudna lipomatozna novotvorina kože i potkožnoga tkiva ostalih i nespecificiranih sijela", "D17.3"),
    D17_4("Dobroćudna lipomatozna novotvorina intratorakalnih organa", "D17.4"),
    D17_5("Dobroćudna lipomatozna novotvorina intraabdominalnih organa", "D17.5"),
    D17_6("Dobroćudna lipomatozna novotvorina sjemene vrpce", "D17.6"),
    D17_7("Dobroćudna lipomatozna novotvorina ostalih sijela", "D17.7"),
    D17_9("Dobroćudna lipomatozna novotvorina, nespecificirana", "D17.9"),
    D18("Hemangiom i limfangiom bilo kojeg sijela", "D18"),
    D18_0("Hemangiom bilo kojeg sijela", "D18.0"),
    D18_1("Limfangiom bilo kojeg sijela", "D18.1"),
    D19("Dobroćudna novotvorina mezotelijalnoga tkiva", "D19"),
    D19_0("Mezotelijalno tkivo pleure", "D19.0"),
    D19_1("Mezotelijalno tkivo peritoneja", "D19.1"),
    D19_7("Mezotelijalno tkivo ostalih sijela", "D19.7"),
    D19_9("Mezotelijalno tkivo, nespecificirano", "D19.9"),
    D20("Dobroćudna novotvorina mekoga tkiva retroperitoneja i peritoneja", "D20"),
    D20_0("Retroperitonej", "D20.0"),
    D20_1("Peritonej", "D20.1"),
    D21("Ostale dobroćudne novotvorine vezivnoga i ostaloga mekoga tkiva", "D21"),
    D21_0("Vezivno i ostalo meko tkivo glave, lica i vrata", "D21.0"),
    D21_1("Vezivno i ostalo meko tkivo ruke, uključujući rame", "D21.1"),
    D21_2("Vezivno i ostalo meko tkivo noge, uključujući kuk", "D21.2"),
    D21_3("Vezivno i ostalo meko tkivo prsnog koša", "D21.3"),
    D21_4("Vezivno i ostalo meko tkivo trbušne šupljine", "D21.4"),
    D21_5("Vezivno i ostalo meko tkivo zdjelice", "D21.5"),
    D21_6("Vezivno i ostalo meko tkivo trupa, nespecificirano", "D21.6"),
    D21_9("Vezivno i ostalo meko tkivo, nespecificirano", "D21.9"),
    D22("Melanocitni madež", "D22"),
    D22_0("Melanocitni madež usne", "D22.0"),
    D22_1("Melanocitni madež očne vjeđe, uključujući kantus", "D22.1"),
    D22_2("Melanocitni madež uha i vanjskoga ušnog kanala", "D22.2"),
    D22_3("Melanocitni madež ostalih i nespecificiranih dijelova lica", "D22.3"),
    D22_4("Melanocitni madež vlasišta i vrata", "D22.4"),
    D22_5("Melanocitni madež trupa", "D22.5"),
    D22_6("Melanocitni madež gornjeg uda, uključujući rame", "D22.6"),
    D22_7("Melanocitni madež donjeg uda, uključujući kuk", "D22.7"),
    D22_9("Melanocitni madež, nespecificiran", "D22.9"),
    D23("Ostale dobroćudne novotvorine kože", "D23"),
    D23_0("Koža usne", "D23.0"),
    D23_1("Koža očne vjeđe, uključujući kantus", "D23.1"),
    D23_2("Koža uha i vanjskoga ušnog kanala", "D23.2"),
    D23_3("Koža ostalih i nespecificiranih dijelova lica", "D23.3"),
    D23_4("Koža vlasišta i vrata", "D23.4"),
    D23_5("Koža trupa", "D23.5"),
    D23_6("Koža ruke, uključujući rame", "D23.6"),
    D23_7("Koža noge, uključujući kuk", "D23.7"),
    D23_9("Koža, nespecificirana", "D23.9"),
    D24("Dobroćudna novotvorina dojke", "D24"),
    D24_0("Dobroćudna novotvorina dojke", "D24.0"),
    D25("Lejomiom maternice", "D25"),
    D25_0("Submukozni lejomiom maternice", "D25.0"),
    D25_1("Intramuralni lejomiom maternice", "D25.1"),
    D25_2("Supserozni lejomiom maternice", "D25.2"),
    D25_9("Lejomiom maternice, nespecificiran", "D25.9"),
    D26("Ostale dobroćudne novotvorine maternice", "D26"),
    D26_0("Vrat maternice", "D26.0"),
    D26_1("Tijelo maternice", "D26.1"),
    D26_7("Ostali dijelovi maternice", "D26.7"),
    D26_9("Maternica, nespecificirana", "D26.9"),
    D27("Dobroćudna novotvorina jajnika (ovarija)", "D27"),
    D27_0("Dobroćudna novotvorina jajnika (ovarija)", "D27.0"),
    D28("Dobroćudna novotvorina ostalih i nespecificiranih ženskih spolnih organa", "D28"),
    D28_0("Stidnica (vulva)", "D28.0"),
    D28_1("Rodnica (vagina)", "D28.1"),
    D28_2("Jajovod i sveze (ligamenti)", "D28.2"),
    D28_7("Ostali specificirani ženski spolni organi", "D28.7"),
    D28_9("Dobroćudna novotvorina, ženski spolni organ, nespecificiran", "D28.9"),
    D29("Dobroćudna novotvorina muških spolnih organa", "D29"),
    D29_0("Spolni ud (penis)", "D29.0"),
    D29_1("Kestenjača (prostata)", "D29.1"),
    D29_2("Sjemenik (testis)", "D29.2"),
    D29_3("Pasjemenik (epididimis)", "D29.3"),
    D29_4("Mošnja (skrotum)", "D29.4"),
    D29_7("Ostali muški spolni organi", "D29.7"),
    D29_9("Muški spolni organ, nespecificiran", "D29.9"),
    D30("Dobroćudna novotvorina mokraćnih organa", "D30."),
    D30_0("Bubreg", "D30."),
    D30_1("Bubrežna zdjelica", "D30."),
    D30_2("Mokraćovod (ureter)", "D30."),
    D30_3("Mokraćni mjehur", "D30."),
    D30_4("Mokraćna cijev (uretra)", "D30."),
    D30_7("Ostali mokraćni organi", "D30."),
    D30_9("Mokraćni organ nespecificiran", "D30."),
    D31("Dobroćudna novotvorina oka i adneksa", "D31"),
    D31_0("Spojnica oka (konjunktiva)", "D31.0"),
    D31_1("Rožnica (korneja)", "D31.1"),
    D31_2("Mrežnica (retina)", "D31.2"),
    D31_3("Novotvorina nesigurne i nepoznate prirode, žilnica (korioideja)", "D31.3"),
    D31_4("Zrakasto (cilijarno) tijelo", "D31.4"),
    D31_5("Suzna žlijezda i kanal", "D31.5"),
    D31_6("Očna šupljina (orbita), nespecificirana", "D31.6"),
    D31_9("Oko, nespecificirano", "D31.9"),
    D32("Dobroćudna novotvorina moždanih ovojnica (meningi)", "D32"),
    D32_0("Cerebralne moždane ovojnice", "D32.0"),
    D32_1("Spinalne moždane ovojnice", "D32.1"),
    D32_9("Moždane ovojnice, nespecificirane", "D32.9"),
    D33("Dobroćudna novotvorina mozga i ostalih dijelova središnjega živčanog sustava", "D33"),
    D33_0("Mozak, supratentorijalno", "D33.0"),
    D33_1("Mozak, infratentorijalno", "D33.1"),
    D33_2("Mozak, nespecificiran", "D33.2"),
    D33_3("Kranijalni živci", "D33.3"),
    D33_4("Kralježnična moždina", "D33.4"),
    D33_7("Ostali specificirani dijelovi središnjega živčanog sustava", "D33.7"),
    D33_9("Središnji živčani sustav, nespecificiran", "D33.9"),
    D34("Dobroćudna novotvorina štitnjače", "D34"),
    D34_0("Dobroćudna novotvorina štitnjače", "D34.0"),
    D35("Dobroćudna novotvorina ostalih i nespecificiranih žlijezda s unutrašnjim izlučivanjem (endokrinih)", "D35"),
    D35_0("Nadbubrežna žlijezda", "D35.0"),
    D35_1("Paratireoidna žlijezda", "D35.1"),
    D35_2("Hipofiza", "D35.2"),
    D35_3("Kraniofaringealni kanal", "D35.3"),
    D35_4("Epifiza", "D35.4"),
    D35_5("Karotidno tijelo", "D35.5"),
    D35_6("Aortno tijelo i ostali paragangliji", "D35.6"),
    D35_7("Ostale specificirane endokrine žlijezde", "D35.7"),
    D35_8("Pluriglandularna zahvaćenost", "D35.8"),
    D35_9("Endokrina žlijezda, nespecificirana", "D35.9"),
    D36("Dobroćudna novotvorina ostalih i nespecificiranih sijela", "D36"),
    D36_0("Limfni čvorovi", "D36.0"),
    D36_1("Periferni živci i vegetativni (autonomni) živčani sustav", "D36.1"),
    D36_7("Ostala specificirana sijela", "D36.7"),
    D36_9("Dobroćudna novotvorina nespecificiranog sijela", "D36.9"),
    D37("Novotvorine usne šupljine i probavnih organa nesigurne ili nepoznate prirode", "D37"),
    D37_0("Usna, usna šupljina i ždrijelo", "D37.0"),
    D37_1("Novotvorina nesigurne i nepoznate prirode, želudac", "D37.1"),
    D37_2("Tanko crijevo", "D37.2"),
    D37_3("Crvuljak (apendiks)", "D37.3"),
    D37_4("Debelo crijevo (kolon)", "D37.4"),
    D37_5("Završno debelo crijevo (rektum)", "D37.5"),
    D37_6("Jetra, žučni mjehur i žučni vodovi", "D37.6"),
    D37_7("Ostali probavni organi", "D37.7"),
    D37_9("Probavni organ, nespecificiran", "D37.9"),
    D38("Novotvorina srednjeg uha, dišnih i intratorakalnih organa nesigurne i nepoznate prirode", "D38"),
    D38_0("Grkljan (larinks)", "D38.0"),
    D38_1("Dušnik, bronh i pluća", "D38.1"),
    D38_2("Pleura", "D38.2"),
    D38_3("Medijastinum", "D38.3"),
    D38_4("Timus", "D38.4"),
    D38_5("Ostali dišni organi", "D38.5"),
    D38_6("Dišni organ, nespecificiran", "D38.6"),
    D39("Novotvorina ženskih spolnih organa nesigurne ili nepoznate prirode", "D39"),
    D39_0("Maternica (uterus)", "D39.0"),
    D39_1("Jajnik (ovarij)", "D39.1"),
    D39_2("Posteljica (placenta)", "D39.2"),
    D39_7("Ostali ženski spolni organi", "D39.7"),
    D39_9("Novotvorina nesigurne i nepoznate prirode, ženski spolni organ, nespecificiran", "D39.9"),
    D40("Novotovorina muških spolnih organa nesigurne ili nepoznate prirode", "D40"),
    D40_0("Prostata", "D40.0"),
    D40_1("Sjemenik (testis)", "D40.1"),
    D40_7("Ostali muški spolni organi", "D40.7"),
    D40_9("Muški spolni organ, nespecificiran", "D40.9"),
    D41("Novotvorina mokraćnih organa nesigurne ili nepoznate prirode", "D41"),
    D41_0("Bubreg", "D41.0"),
    D41_1("Bubrežna zdjelica", "D41.1"),
    D41_2("Mokraćni vod (ureter)", "D41.2"),
    D41_3("Mokraćna cijev (uretra)", "D41.3"),
    D41_4("Mokraćni mjehur", "D41.4"),
    D41_7("Ostali mokraćni organi", "D41.7"),
    D41_9("Mokraćni organ, nespecificiran", "D41.9"),
    D42("Novotvorina moždanih ovojnica (meningi) nesigurne ili nepoznate prirode", "D42"),
    D42_0("Cerebralne moždane ovojnice", "D42.0"),
    D42_1("Spinalne moždane ovojnice", "D42.1"),
    D42_9("Moždane ovojnice, nespecificirane", "D42.9"),
    D43("Novotvorina mozga i središnjega živčanog sustava nesigurne ili nepoznate prirode", "D43"),
    D43_0("Mozak, supratentorijalno", "D43.0"),
    D43_1("Mozak, infratentorijalno", "D43.1"),
    D43_2("Mozak, nespecificiran", "D43.2"),
    D43_3("Moždani (kranijalni) živci", "D43.3"),
    D43_4("Kralježnična moždina", "D43.4"),
    D43_7("Ostali dijelovi središnjega živčanog sustava", "D43.7"),
    D43_9("Središnji živčani sustav, nespecificiran", "D43.9"),
    D44("Novotvorina žlijezda s unutrašnjim izlučivanjem (endokrinih) nesigurne ili nepoznate prirode", "D44"),
    D44_0("Štitnjača", "D44.0"),
    D44_1("Nadbubrežna žlijezda", "D44.1"),
    D44_2("Paratireoidna žlijezda", "D44.2"),
    D44_3("Hipofiza", "D44.3"),
    D44_4("Kraniofaringealni kanal", "D44.4"),
    D44_5("Epifiza", "D44.5"),
    D44_6("Karotidno tijelo", "D44.6"),
    D44_7("Aortno tijelo i ostali paragangliji", "D44.7"),
    D44_8("Pluriglandularna zahvaćenost", "D44.8"),
    D44_9("Endokrina žlijezda, nespecificirana", "D44.9"),
    D45("Policitemija vera", "D45"),
    D45_0("Policitemija vera", "D45.0"),
    D46("Mijelodisplastični sindromi", "D46"),
    D46_0("Refraktarna anemija bez sideroblasta, ako je to navedeno", "D46.0"),
    D46_1("Refraktarna anemija sa sideroblastima", "D46.1"),
    D46_2("Refraktarna anemija s viškom blasta", "D46.2"),
    D46_3("Refraktarna anemija s viškom blasta u transformaciji", "D46.3"),
    D46_4("Refraktarna anemija, nespecificirana", "D46.4"),
    D46_7("Ostali mijelodisplastični sindromi", "D46.7"),
    D46_9("Mijelodisplastični sindrom, nespecificiran", "D46.9"),
    D47("Ostale novotvorine limfnoga, hematopoeznoga i srodnoga tkiva nesigurne ili nepoznate prirode", "D47"),
    D47_0("Histocitni i mastocitni tumori nesigurne i nepoznate prirode", "D47.0"),
    D47_1("Kronična mijeloproliferativna bolest", "D47.1"),
    D47_2("Monoklonalna gamopatija", "D47.2"),
    D47_3("Esencijalna (hemoragijska) trombocitemija", "D47.3"),
    D47_7("Ostale specificirane novotvorine limfnoga, hematopoeznoga i srodnoga tkiva nesigurne ili nepoznate prirode", "D47.7"),
    D47_9("Novotvorina limfnoga, hematopoeznoga i srodnoga tkiva, nesigurne ili nepoznate prirode, nespecificirana", "D47.9"),
    D48("Novotvorina ostalih i nespecificiranih sijela nesigurne ili nepoznate prirode", "D48"),
    D48_0("Kost i zglobna hrskavica", "D48.0"),
    D48_1("Vezivno tkivo i ostalo meko tkivo", "D48.1"),
    D48_2("Periferni živci i autonomni živčani sustav", "D48.2"),
    D48_3("Retroperitonej", "D48.3"),
    D48_4("Peritonej", "D48.4"),
    D48_5("Koža", "D48.5"),
    D48_6("Dojka", "D48.6"),
    D48_7("Ostala specificirana sijela", "D48.7"),
    D48_9("Novotvorina nesigurne ili nepoznate prirode, nespecificirana", "D48.9"),
    D50("Anemija zbog manjka željeza", "D50"),
    D50_0("Anemija zbog manjka željeza, nakon gubitka krvi (kroničnog)", "D50.0"),
    D50_1("Sideropenijska disfagija", "D50.1"),
    D50_8("Ostale anemije zbog manjka željeza", "D50.8"),
    D50_9("Anemija zbog manjka željeza, nespecificirana", "D50.9"),
    D51("Anemija zbog manjka vitamina B12", "D51"),
    D51_0("Anemija zbog manjka vitamina B12 kao posljedica manjka unutrašnjeg faktora", "D51.0"),
    D51_1("Anemija zbog manjka vitamina B12 uzrokovana selektivnom malapsorpcijom vitamina B12 s proteinurijom", "D51.1"),
    D51_2("Manjak transkobalamina II", "D51.2"),
    D51_3("Druga anemija zbog manjka vitamina B12 u prehrani", "D51.3"),
    D51_8("Ostale anemije zbog manjka vitamina B12", "D51.8"),
    D51_9("Anemija zbog manjka vitamina B12, nespecificirana", "D51.9"),
    D52("Anemija zbog manjka folne kiseline", "D52"),
    D52_0("Anemija zbog manjka folne kiseline u prehrani", "D52.0"),
    D52_1("Anemija zbog manjka folne kiseline uzrokovana lijekom", "D52.1"),
    D52_8("Ostale anemije zbog manjka folne kiseline", "D52.8"),
    D52_9("Anemija zbog manjka folne kiseline, nespecificirana", "D52.9"),
    D53("Ostale nutricijske anemije", "D53"),
    D53_0("Anemija zbog manjka bjelančevina", "D53.0"),
    D53_1("Ostale megaloblastične anemije nesvrstane drugamo", "D53.1"),
    D53_2("Anemija u skorbutu", "D53.2"),
    D53_8("Ostale specificirane nutricijske anemije", "D53.8"),
    D53_9("Anemija zbog neodgovarajuće prehrane (nutricijska), nespecificirana", "D53.9"),
    D55("Anemija zbog poremećaja enzima", "D55"),
    D55_0("Anemija zbog manjka glukoza-6-fosfat dehidrogenaze (G6PDH)", "D55.0"),
    D55_1("Anemija zbog ostalih poremećaja metabolizma glutationa", "D55.1"),
    D55_2("Anemija zbog poremećaja enzima glikolitičkog ciklusa", "D55.2"),
    D55_3("Anemija zbog poremećaja metabolizma nukleotida", "D55.3"),
    D55_8("Ostale anemije zbog enzimskih poremećaja", "D55.8"),
    D55_9("Anemija zbog enzimskih poremećaja, nespecificirana", "D55.9"),
    D56("Talasemija", "D56"),
    D56_0("Alfa-talasemija", "D56.0"),
    D56_1("Beta-talasemija", "D56.1"),
    D56_2("Delta-beta-talasemija", "D56.2"),
    D56_3("Talasemija nasljedno obilježena", "D56.3"),
    D56_4("Nasljedne perzistencije fetalnog hemoglobina (HPFH)", "D56.4"),
    D56_8("Ostale talasemije", "D56.8"),
    D56_9("Talasemija, nespecificirana", "D56.9"),
    D57("Poremećaji srpastih stanica", "D57"),
    D57_0("Anemija srpastih stanica s krizama", "D57.0"),
    D57_1("Anemija srpastih stanica bez kriza", "D57.1"),
    D57_2("Dvostruki heterozigoti za poremećaje na srpastim stanicama", "D57.2"),
    D57_3("Nasljedno obilježje srpastih stanica", "D57.3"),
    D57_8("Ostale bolesti sa srpastim stanicama", "D57.8"),
    D58("Ostale nasljedne hemolitičke anemije", "D58"),
    D58_0("Nasljedna sferocitoza", "D58.0"),
    D58_1("Nasljedna eliptocitoza", "D58.1"),
    D58_2("Ostale hemoglobinopatije", "D58.2"),
    D58_8("Ostale specificirane nasljedne hemolitičke anemije", "D58.8"),
    D58_9("Nasljedna hemolitička anemija, nespecificirana", "D58.9"),
    D59("Stečena hemolitička anemija", "D59"),
    D59_0("Autoimuna hemolitička anemija uzrokovana lijekom", "D59.0"),
    D59_1("Ostale hemolitičke autoimune anemije", "D59.1"),
    D59_2("Hemolitička anemija zbog lijeka, koja nije uzrokovana autoimunim mehanizmom", "D59.2"),
    D59_3("Hemolitičko-uremijski sindrom", "D59.3"),
    D59_4("Ostale hemolitičke anemije koje nisu uzrokovane autoimunim mehanizmom", "D59.4"),
    D59_5("Paroksizmalna noćna hemoglobinurija (Marchiafava-Micheli)", "D59.5"),
    D59_6("Hemoglobinurija zbog hemolize uzrokovana ostalim vanjskim uzrocima", "D59.6"),
    D59_8("Ostale stečene hemolitičke anemije", "D59.8"),
    D59_9("Stečena hemolitička anemija, nespecificirana", "D59.9"),
    D60("Stečena izolirana aplazija crvene loze (eritroblastopenija)", "D60"),
    D60_0("Kronična stečena izolirana aplazija crvene loze", "D60.0"),
    D60_1("Prolazna stečena izolirana aplazija crvene loze", "D60.1"),
    D60_8("Ostale stečene izlorane splazije crvene loze", "D60.8"),
    D60_9("Stečena izolirana aplazija crvene loze, nespecificirana", "D60.9"),
    D61("Ostale aplastične anemije", "D61"),
    D61_0("Konstitucijska aplastična anemija", "D61.0"),
    D61_1("Aplastična anemija uzrokovana lijekom", "D61.1"),
    D61_2("Aplastična anemija uzrokovana drugim vanjskim uzrocima (agensima)", "D61.2"),
    D61_3("Idiopatska aplastična anemija", "D61.3"),
    D61_8("Ostale specificirane aplastične anemije", "D61.8"),
    D61_9("Aplastična anemija, nespecificirana", "D61.9"),
    D62("Akutna posthemoragijska anemija", "D62"),
    D62_0("Akutna posthemoragijska anemija", "D62.0"),
    D63("Anemija u kroničnim bolestima svrstanim drugamo", "D63"),
    D63_0("Anemija u neoplastičnim bolestima (C00-D48)", "D63.0"),
    D63_8("Anemije u ostalim kroničnim bolestima svrstanim drugamo", "D63.8"),
    D64("Ostale anemije", "D64"),
    D64_0("Nasljedna sideroblastična anemija", "D64.0"),
    D64_1("Sekundarna sideroblastična anemija zbog bolesti", "D64.1"),
    D64_2("Sekundarna sideroblastična anemija zbog lijekova i otrova", "D64.2"),
    D64_3("Ostale sideroblastične anemije", "D64.3"),
    D64_4("Prirođena dizeritropoezna anemija", "D64.4"),
    D64_8("Ostale specificirane anemije", "D64.8"),
    D64_9("Anemija, nespecificirana", "D64.9"),
    D65("Diseminirana intravaskularna koagulacija (sindrom defibrinacije)", "D65"),
    D65_0("Diseminirana intravaskularna koagulacija (sindrom defibrinacije)", "D65.0"),
    D66("Nasljedni manjak faktora VIII.", "D66"),
    D66_0("Nasljedni manjak fatora VIII.", "D66.0"),
    D67("Nasljedni manjak faktora IX.", "D67"),
    D67_0("Nasljedni manjak faktora IX.", "D67.0"),
    D68("Ostali poremećaji koagulacije", "D68"),
    D68_0("Von Willebrandova bolest", "D68.0"),
    D68_1("Nasljedni manjak faktora XI.", "D68.1"),
    D68_2("Nasljedni manjak ostalih faktora zgrušavanja krvi", "D68.2"),
    D68_3("Hemoragijski poremećaji zbog cirkulirajućih antikoagulansa", "D68.3"),
    D68_4("Stečeni manjak faktora koagulacije", "D68.4"),
    D68_8("Ostali specificirani poremećaji koagulacije", "D68.8"),
    D68_9("Poremećaj koagulacije, nespecificiran", "D68.9"),
    D69("Purpura i ostala hemoragijska stanja", "D69"),
    D69_0("Alergijska purpura", "D69.0"),
    D69_1("Kvalitativni poremećaji trombocita", "D69.1"),
    D69_2("Ostale netrombocitopenijske purpure", "D69.2"),
    D69_3("Idiopatska trombocitopenijska purpura", "D69.3"),
    D69_4("Druga primarna trombocitopenija", "D69.4"),
    D69_5("Sekundarna trombocitopenija", "D69.5"),
    D69_6("Trombocitopenija, nespecificirana", "D69.6"),
    D69_8("Ostala specificirana hemoragijska stanja", "D69.8"),
    D69_9("Hemoragijsko stanje, nespecificirano", "D69.9"),
    D70("Agranulocitoza", "D70"),
    D70_0("Agranulocitoza", "D70.0"),
    D71("Funkcionalni poremećaji polimorfonuklearnih neutrofila", "D71"),
    D71_0("Funkcionalni poremaćaji polimorfnonuklearnih neutrofila", "D71.0"),
    D72("Ostali poremećaji bijelih krvnih stanica", "D72"),
    D72_0("Genetske anomalije leukocita", "D72.0"),
    D72_1("Eozinofilija", "D72.1"),
    D72_8("Ostale specificirane bolesti bijelih krvnih stanica", "D72.8"),
    D72_9("Poremećaj bijelih krvnih stanica, nespecificiran", "D72.9"),
    D73("Bolesti slezene", "D73"),
    D73_0("Hiposplenizam", "D73.0"),
    D73_1("Hipersplenizam", "D73.1"),
    D73_2("Kronična kongestivna splenomegalija", "D73.2"),
    D73_3("Apsces slezene", "D73.3"),
    D73_4("Cista slezene", "D73.4"),
    D73_5("Infarkt slezene", "D73.5"),
    D73_8("Ostale slezenske bolesti", "D73.8"),
    D73_9("Bolest slezene, nespecificirana", "D73.9"),
    D74("Methemoglobinemija", "D74"),
    D74_0("Prirođena methemoglobinemija", "D74.0"),
    D74_8("Ostale methemoglobinemije", "D74.8"),
    D74_9("Methemoglobinemija, nespecificirana", "D74.9"),
    D75("Ostale bolesti krvi i krvotvornog sustava", "D75"),
    D75_0("Obiteljska eritrocitoza", "D75.0"),
    D75_1("Sekundarna policitemija", "D75.1"),
    D75_2("Esencijalna trombocitoza", "D75.2"),
    D75_8("Ostale specificirane bolesti krvi i krvotvornog sustava", "D75.8"),
    D75_9("Bolest krvi i krvotvornog sustava, nespecificirana", "D75.9"),
    D76("Određene bolesti koje zahvaćaju limforetikularno tkivo i retikulohistiocitni sustav", "D76"),
    D76_0("Histiocitoza Langerhansovih stanica, nesvrstana drugamo", "D76.0"),
    D76_1("Hemofagocitna limfohistiocitoza", "D76.1"),
    D76_2("Hemofagocitni sindrom povezan s infekcijom", "D76.2"),
    D76_3("Ostali histiocitozni sindromi", "D76.3"),
    D77("Ostali poremećaji krvi i krvotvornog sustava kod bolesti svrstanih drugamo", "D77"),
    D77_0("Ostali poremaćaji kvi i krvotvornog sustava kod bolesti svrstanih drugamo", "D77.0"),
    D80("Imunodeficijencija s prevladavajućim poremaćajima protutijela", "D80"),
    D80_0("Nasljedna hipogamaglobulinemija", "D80.0"),
    D80_1("Stečena hipogamaglobulinemija", "D80.1"),
    D80_2("Izolirani manjak imunoglobulina A (igA)", "D80.2"),
    D80_3("Izolirani manjak imunoglobulina G (IgG) supklase", "D80.3"),
    D80_4("Izolirani manjak imunoglobulina M (IgM)", "D80.4"),
    D80_5("Imunodeficijencija s povećanjem imunoglobulina M (IgM)", "D80.5"),
    D80_6("Manjak protutijela s imunoglobulinima blizu normale ili heperimunoglobulinemijom", "D80.6"),
    D80_7("Prolazna hipogamaglobulinemija u ranom djetinjstvu", "D80.7"),
    D80_8("Ostale imunodeficijencije s prevladavajućim poremećajem protutijela", "D80.8"),
    D80_9("Imunonodeficijencija s prevladavajućim poremaćajem protutijela, nespecificirana", "D80.9"),
    D81("Kombinirane imunodeficijencije", "D81"),
    D81_0("Teški kombinirani imunodeficit (SCID) s retikularnom dizgenezom", "D81.0"),
    D81_1("Teški kombinirani imunodeficit (SCID) s malim brojem T i B-limfocita", "D81.1"),
    D81_2("Teški kombinirani imunodeficit (SCID) s malim ili normalnim brojem B-limfocita", "D81.2"),
    D81_3("Manjak adenozin deaminaze (ADA)", "D81.3"),
    D81_4("Nezelofov sindrom", "D81.4"),
    D81_5("Manjak purinske nukleozid fosforilaze (PNP)", "D81.5"),
    D81_6("Manjak glavnog sustava tkivne snošljivosti klase I.", "D81.6"),
    D81_7("Manjak glavnog sustava tkivne snošljivosti klase II.", "D81.7"),
    D81_8("Ostale kombinirane imunodeficijencije", "D81.8"),
    D81_9("Kombinirani imunodeficit, nespecificiran", "D81.9"),
    D82("Imunodeficijencije povezane s ostalim većim poremećajima", "D82"),
    D82_0("Wiskott-Aldrichov sindrom", "D82.0"),
    D82_1("Di Georgeov sindrom", "D82.1"),
    D82_2("Imunodeficijencija kod konstitucije s kratkim udovima", "D82.2"),
    D82_3("Imunodeficijencija kao posljedica nasljednog, defektnog odgovora na infekciju Epstein-Barr virusom", "D82.3"),
    D82_4("Sindrom hiperimunoglobulinemije E (IgE)", "D82.4"),
    D82_8("Imunodeficijencija povezana s ostalim specificiranim većim defektima", "D82.8"),
    D82_9("Imunodeficijencija povezana s većim defektima, nespecificirana", "D82.9"),
    D83("Obična varijabilna imunodeficijencija", "D83"),
    D83_0("Obična varijabilna imunodeficijencija s prevladavajućim poremećajem broja i funkcije B-limfocita", "D83.0"),
    D83_1("Obična varijabilna imunodeficijencija s prevladavajućim poremećajem imunoregulacijskih T-limfocita", "D83.1"),
    D83_2("Obična varijabilna imunodeficijencija s protutijelima na B i T-limfocite", "D83.2"),
    D83_8("Ostale obične varijabilne imunodeficijencije", "D83.8"),
    D83_9("Obična varijabilna imunodeficijencija, nespecificirana", "D83.9"),
    D84("Ostale imunodeficijencije", "D84"),
    D84_0("Poremećaji u funkciji limfocitnog antigena-1 (LFA-1)", "D84.0"),
    D84_1("Defekti sustava komplementa", "D84.1"),
    D84_8("Ostale specificirane imunodeficijencije", "D84.8"),
    D84_9("Imunodeficijencija, nespecificirana", "D84.9"),
    D86("Sarkoidoza", "D86"),
    D86_0("Sarkoidoza pluća", "D86.0"),
    D86_1("Sarkoidoza limfnih čvorova", "D86.1"),
    D86_2("Sarkoidoza pluća sa sarkoidozom limfnih čvorova", "D86.2"),
    D86_3("Sarkoidoza kože", "D86.3"),
    D86_8("Sarkoidoza ostalih i kombiniranih lokalizacija", "D86.8"),
    D86_9("Sarkoidoza, nespecificirana", "D86.9"),
    D89("Ostali poremećaji imunološkog sustava, nesvrstani drugamo", "D89"),
    D89_0("Poliklonska hipergamaglobulinemija", "D89.0"),
    D89_1("Krioglobulinemija", "D89.1"),
    D89_2("Hipergamaglobulinemija, nespecificirana", "D89.2"),
    D89_8("Ostali specificirani poremećaji imunološkog sustava nesvrstani drugamo", "D89.8"),
    D89_9("Poremećaj imunološkog sustava, nespecificiran", "D89.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesD(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
