package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesS {
    
    S00("Površinska ozljeda glave", "SOO"),
    S00_0("Površinska ozljeda vlasišta", "SOO.0"),
    S00_1("Kontuzija očne vjeđe i periokularnog područja", "SOO.1"),
    S00_2("Druge površinske ozljede očne vjeđe i periokularnog područja", "SOO.2"),
    S00_3("Površinska ozljeda nosa", "SOO.3"),
    S00_4("Površinska ozljeda uha", "SOO.4"),
    S00_5("Površinska ozljeda usana i usne šupljine", "SOO.5"),
    S00_7("Višestruke površinske ozljede glave", "SOO.7"),
    S00_8("Površinska ozljeda ostalih dijelova glave", "SOO.8"),
    S00_9("Površinska ozljeda, nespecificiranog dijela", "SOO.9"),
    S01("Otvorena rana glave", "SO1"),
    S01_0("Otvorena rana vlasišta", "SO1.0"),
    S01_1("Otvorena rana očne vjeđe i periokularnog područja", "SO1.1"),
    S01_2("Otvorena rana nosa", "SO1.2"),
    S01_3("Otvorena rana uha", "SO1.3"),
    S01_4("Otvorena rana obraza i temporomandibularnog područja", "SO1.4"),
    S01_5("Otvorena rana usana i usne šupljine", "SO1.5"),
    S01_7("Višestruke otvorene rane glave", "SO1.7"),
    S01_8("Otvorena rana ostalih dijelova glave", "SO1.8"),
    S01_9("Otvorena rana glave, nespecificiranog dijela", "SO1.9"),
    S02("Prijelom lubanje i kosti lica", "SO2"),
    S02_0("Prijelom svoda lubanje", "SO2.0"),
    S02_1("Prijelom baze lubanje", "SO2.1"),
    S02_2("Prijelom nosne kosti", "SO2.2"),
    S02_3("Prijelom dna očne šupljine", "SO2.3"),
    S02_4("Prijelom jagodične kosti i kosti gornje čeljusti", "SO2.4"),
    S02_5("Prijelom zuba", "SO2.5"),
    S02_6("Prijelom mandibule", "SO2.6"),
    S02_7("Višestruki prijelomi lubanje i kosti lica", "SO2.7"),
    S02_8("Ostali prijelomi lubanje i kosti lica", "SO2.8"),
    S02_9("Prijelom lubanje i kosti lica, nespecificiranog dijela", "SO2.9"),
    S03("Dislokacija, iščašenje i nategnuće zglobova i ligamenata glave", "SO3"),
    S03_0("Dislokacija čeljusti", "SO3.0"),
    S03_1("Dislokacija septalne hrskavice nosa", "SO3.1"),
    S03_2("Dislokacija zuba", "SO3.2"),
    S03_3("Dislokacija drugih i nespecificiranih dijelova glave", "SO3.3"),
    S03_4("Iščašenje i nategnuće čeljusti", "SO3.4"),
    S03_5("Iščašenje i nategnuće zglobova i ligamenata i drugih nespecificiranih dijelova glave", "SO3.5"),
    S04("Ozljede moždanih živaca", "SO4"),
    S04_0("Ozljeda vidnog živca (optikusa) i njegovih putova", "SO4.0"),
    S04_1("Ozljeda okulomotorijusa", "SO4.1"),
    S04_2("Ozljeda trohlearisa", "SO4.2"),
    S04_3("Ozljeda trigeminusa", "SO4.3"),
    S04_4("Ozljeda abducensa", "SO4.4"),
    S04_5("Ozljeda ličnog živca (facijalisa)", "SO4.5"),
    S04_6("Ozljeda akustikusa", "SO4.6"),
    S04_7("Ozljeda akcesornog živca", "SO4.7"),
    S04_8("Ozljeda ostalih moždanih živaca", "SO4.8"),
    S04_9("Ozljeda nespecificiranog moždanog živca", "SO4.9"),
    S05("Ozljeda oka i očne šupljine", "SO5"),
    S05_0("Ozljeda spojnice i abrazija rožnice bez spomena stranog tijela", "SO5.0"),
    S05_1("Kontuzija očne jabučice i tkiva očne šupljine", "SO5.1"),
    S05_2("Laceracija i ruptura oka s prolapsom ili gubitkom intraokularnoga tkiva", "SO5.2"),
    S05_3("Laceracija oka bez prolapsa ili gubitka intraokularnoga tkiva", "SO5.3"),
    S05_4("Penetrantna rana očne šupljine sa stranim tijelom ili bez njega", "SO5.4"),
    S05_5("Penetrantna rana očne jabučice sa stranim tijelom", "SO5.5"),
    S05_6("Penetrantna rana očne jabučice bez stranog tijela", "SO5.6"),
    S05_7("Avulzija oka", "SO5.7"),
    S05_8("Ostale ozljede oka i očne šupljine", "SO5.8"),
    S05_9("Ozljeda oka i očne šupljine, nespecificiranog dijela", "SO5.9"),
    S06("Intrakranijalna ozljeda", "SO6"),
    S06_0("Potres mozga", "SO6.0"),
    S06_1("Traumatski edem mozga", "SO6.1"),
    S06_2("Difuzna ozljeda mozga", "SO6.2"),
    S06_3("Fokalna ozljeda mozga", "SO6.3"),
    S06_4("Epiduralno krvarenje", "SO6.4"),
    S06_5("Traumatsko subduralno krvarenje", "SO6.5"),
    S06_6("Traumatsko subarahnoidalno krvarenje", "SO6.6"),
    S06_7("Intrakranijalna ozljeda s produženom komom", "SO6.7"),
    S06_8("Ostale intrakranijalne ozljede", "SO6.8"),
    S06_9("Intrakranijalna ozljeda, nespecificirana", "SO6.9"),
    S07("Zgnječenje glave (crush ozljeda glave)", "SO7"),
    S07_0("Zgnječenje lica", "SO7.0"),
    S07_1("Zgnječenje lubanje", "SO7.1"),
    S07_8("Zgnječenje ostalih dijelova glave", "SO7.8"),
    S07_9("Zgnječenje glave, nespecificiranog dijela", "SO7.9"),
    S08("Traumatska amputacija dijela glave", "SO8"),
    S08_0("Avulzija vlasišta", "SO8.0"),
    S08_1("Traumatska amputacija uha", "SO8.1"),
    S08_8("Traumatska amputacija ostalih dijelova glave", "SO8.8"),
    S08_9("Traumatska amputacija nespecificiranog dijela glave", "SO8.9"),
    S09("Ostale i nespecificirane ozljede glave", "SO9"),
    S09_0("Ozljeda krvnih žila glave, nesvrstana drugamo", "SO9.0"),
    S09_1("Ozljeda mišića i tetive glave", "SO9.1"),
    S09_2("Traumatska ruptura bubnjića", "SO9.2"),
    S09_7("Višestruke ozljede glave", "SO9.7"),
    S09_8("Ostale specificirane ozljede glave", "SO9.8"),
    S09_9("Nespecificirana ozljeda glave", "SO9.9"),
    S10("Površinska ozljeda vrata", "S1O"),
    S10_0("Kontuzija grla", "S1O.0"),
    S10_1("Ostale i nespecificirane površinske ozljede grla", "S1O.1"),
    S10_7("Višestruke površinske ozljede vrata", "S1O.7"),
    S10_8("Površinska ozljeda ostalih dijelova vrata", "S1O.8"),
    S10_9("Površinska ozljeda vrata, nespecificiranog dijela", "S1O.9"),
    S11("Otvorena rana vrata", "S11"),
    S11_0("Otvorena rana grkljana i dušnika (larinksa i traheje)", "S11.0"),
    S11_1("Otvorena rana štitnjače (tireoidne žlijezde)", "S11.1"),
    S11_2("Otvorena rana ždrijela i vratnog dijela jednjaka (farinksa i cervikalnog dijela ezofagusa)", "S11.2"),
    S11_7("Višestruke otvorene rane vrata", "S11.7"),
    S11_8("Otvorena rana ostalih dijelova vrata", "S11.8"),
    S11_9("Otvorena rana vrata, nespecificiranog dijela", "S11.9"),
    S12("Prijelom vrata", "S12"),
    S12_0("Prijelom prvoga vratnog kralješka", "S12.0"),
    S12_1("Prijelom drugoga vratnog kralješka", "S12.1"),
    S12_2("Prijelom ostalih specificiranih vratnih kralježaka", "S12.2"),
    S12_7("Višestruki prijelomi vratne kralježnice", "S12.7"),
    S12_8("Prijelom ostalih dijelova vrata", "S12.8"),
    S12_9("Prijelom vrata, nespecificiranog dijela", "S12.9"),
    S13("Dislokacija, iščašenje i nategnuće zglobova i ligamenata u području vrata", "S13"),
    S13_0("Traumatska ruptura cervikalnoga intervertebralnog diska", "S13.0"),
    S13_1("Dislokacija vratnog kralješka", "S13.1"),
    S13_2("Dislokacija drugih i nespecificiranih dijelova vrata", "S13.2"),
    S13_3("Višestruke dislokacije vrata", "S13.3"),
    S13_4("Iščašenje i nategnuće cervikalne kralježnice", "S13.4"),
    S13_5("Iščašenje i nategnuće tireoidnog područja", "S13.5"),
    S13_6("Iščašenje i nategnuće zglobova i ligamenata drugih i nespecificiranih dijelova vrata", "S13.6"),
    S14("Ozljeda živaca i kralježnične moždine u području vrata", "S14"),
    S14_0("Potres i edem cervikalnog dijela kralježnične moždine", "S14.0"),
    S14_1("Druge i nespecificirane ozljede cervikalnog dijela kralježnične moždine", "S14.1"),
    S14_2("Ozljeda živčanog korijena cervikalne kralježnice", "S14.2"),
    S14_3("Ozljeda brahijalnog pleksusa", "S14.3"),
    S14_4("Ozljeda vratnih perifernih živaca", "S14.4"),
    S14_5("Ozljeda cervikalnih simpatičkih živaca", "S14.5"),
    S14_6("Ozljeda drugih i nespecificiranih vratnih živaca", "S14.6"),
    S15("Ozljeda krvnih žila u području vrata", "S15"),
    S15_0("Ozljeda karotidne arterije", "S15.0"),
    S15_1("Ozljeda vertebralne arterije (a. vertebralis)", "S15.1"),
    S15_2("Ozljeda vanjske jugularne vene (v. jugularis externa)", "S15.2"),
    S15_3("Ozljeda unutarnje jugularne vene (v. jugularis interna)", "S15.3"),
    S15_7("Ozljeda više krvnih žila u području vrata", "S15.7"),
    S15_8("Ozljeda drugih krvnih žila u području vrata", "S15.8"),
    S15_9("Ozljeda nespecificirane krvne žile u području vrata", "S15.9"),
    S16("Ozljeda mišića i tetiva u području vrata", "S16"),
    S16_0("Ozljeda mišića i tetiva u području vrata", "S16.0"),
    S17("Zgnječenje (crush ozljeda) vrata", "S17"),
    S17_0("Zgnječenje larinksa i traheje", "S17.0"),
    S17_8("Zgnječenje ostalih dijelova vrata", "S17.8"),
    S17_9("Zgnječenje vrata, nespecificiranog dijela", "S17.9"),
    S18("Traumatska amputacija u razini vrata", "S18"),
    S18_0("Traumatska amputacija u razini vrata", "S18.0"),
    S19("Druge i nespecificirane ozljede vrata", "S19"),
    S19_7("Višestruke ozljede vrata", "S19.7"),
    S19_8("Ostale specificirane ozljede vrata", "S19.8"),
    S19_9("Nespecificirana ozljeda vrata", "S19.9"),
    S20("Površinska ozljeda prsnog koša", "S2O"),
    S20_0("Kontuzija dojke", "S2O.0"),
    S20_1("Druge i nespecificirane površinske ozljede dojke", "S2O.1"),
    S20_2("Kontuzija prsnog koša", "S2O.2"),
    S20_3("Ostale površinske ozljede prednje torakalne stijenke", "S2O.3"),
    S20_4("Ostale površinske ozljede stražnje torakalne stijenke", "S2O.4"),
    S20_7("Višestruke površinske ozljede prsnog koša", "S2O.7"),
    S20_8("Površinske ozljede drugih i nespecificiranih dijelova prsnog koša", "S2O.8"),
    S21("Otvorena rana prsnog koša", "S21"),
    S21_0("Otvorena rana dojke", "S21.0"),
    S21_1("Otvorena rana prednje torakalne stijenke", "S21.1"),
    S21_2("Otvorena rana stražnje torakalne stijenke", "S21.2"),
    S21_7("Višestruke otvorene rane torakalne stijenke", "S21.7"),
    S21_8("Otvorena rana ostalih dijelova prsnog koša", "S21.8"),
    S21_9("Otvorena rana prsnog koša, nespecificiranog dijela", "S21.9"),
    S22("Prijelom rebra(ara), prsne kosti i torakalne kralježnice", "S22"),
    S22_0("Prijelom torakalnog kralješka", "S22.0"),
    S22_1("Višestruki prijelom torakalne kralježnice", "S22.1"),
    S22_2("Prijelom prsne kosti (sternuma)", "S22.2"),
    S22_3("Prijelom rebra", "S22.3"),
    S22_4("Višestruki prijelomi rebara", "S22.4"),
    S22_5("Spljošteni prsni koš", "S22.5"),
    S22_8("Prijelom ostalih kosti prsnog koša", "S22.8"),
    S22_9("Prijelom kosti prsnog koša, nespecificiranog dijela", "S22.9"),
    S23("Dislokacija, iščašenje i nategnuće torakalnih zglobova i ligamenata", "S23"),
    S23_0("Traumatska ruptura torakalnoga intervertebralnog diska", "S23.0"),
    S23_1("Dislokacija torakalnog kralješka", "S23.1"),
    S23_2("Dislokacija drugih i nespecificiranih dijelova prsnog koša", "S23.2"),
    S23_3("Iščašenje i nategnuće torakalne kralježnice", "S23.3"),
    S23_4("Iščašenje i nategnuće rebara i prsne kosti", "S23.4"),
    S23_5("Iščašenje i nategnuće drugih i nespecificiranih dijelova prsnog koša", "S23.5"),
    S24("Ozljeda živaca i kralježnične moždine u području prsnog koša", "S24"),
    S24_0("Potres i edem torakalnog dijela kralježnične moždine", "S24.0"),
    S24_1("Druge i nespecificirane ozljede torakalnog dijela kralježnične moždine", "S24.1"),
    S24_2("Ozljeda živčanog korijena torakalne kralježnice", "S24.2"),
    S24_3("Ozljeda perifernih živaca prsnog koša", "S24.3"),
    S24_4("Ozljeda torakalnih simpatičkih živaca", "S24.4"),
    S24_5("Ozljeda ostalih torakalnih živaca", "S24.5"),
    S24_6("Ozljeda nespecificiranog živca prsnog koša", "S24.6"),
    S25("Ozljeda torakalnih krvnih žila", "S25"),
    S25_0("Ozljeda torakalne aorte", "S25.0"),
    S25_1("Ozljeda arterije innominate ili arterije supklavije", "S25.1"),
    S25_2("Ozljeda gornje šuplje vene (v. cava superior)", "S25.2"),
    S25_3("Ozljeda vene innominate ili vene supklavije", "S25.3"),
    S25_4("Ozljeda plućnih krvnih žila", "S25.4"),
    S25_5("Ozljeda interkostalnih krvnih žila", "S25.5"),
    S25_7("Ozljeda više torakalnih krvnih žila", "S25.7"),
    S25_8("Ozljeda ostalih torakalnih krvnih žila", "S25.8"),
    S25_9("Ozljeda nespecificirane torakalne krvne žile", "S25.9"),
    S26("Ozljeda srca", "S26"),
    S26_0("Ozljeda srca s hemoperikardom", "S26.0"),
    S26_8("Ostale ozljede srca", "S26.8"),
    S26_9("Ozljeda srca, nespecificirana", "S26.9"),
    S27("Ozljeda drugih i nespecificiranih intratorakalnih organa", "S27"),
    S27_0("Traumatski pneumotoraks", "S27.0"),
    S27_1("Traumatski hemotoraks", "S27.1"),
    S27_2("Traumatski hemopneumotoraks", "S27.2"),
    S27_3("Druge ozljede pluća", "S27.3"),
    S27_4("Ozljeda bronha", "S27.4"),
    S27_5("Ozljeda torakalnog dijela dušnika", "S27.5"),
    S27_6("Ozljeda plućne ovojnice (pleure)", "S27.6"),
    S27_7("Višestruke ozljede intratorakalnih organa", "S27.7"),
    S27_8("Ozljede ostalih specificiranih intratorakalnih organa", "S27.8"),
    S27_9("Ozljeda nespecificiranog intratorakalnog organa", "S27.9"),
    S28("Zgnječenje (crush ozljeda) prsnog koša i traumatska amputacija njegova dijela", "S28"),
    S28_0("Zgnječenje prsnog koša", "S28.0"),
    S28_1("Traumatska amputacija dijela prsnog koša", "S28.1"),
    S29("Druge i nespecificirane ozljede prsnog koša", "S29"),
    S29_0("Ozljeda mišića i tetive prsnog koša", "S29.0"),
    S29_7("Višestruke ozljede prsnog koša", "S29.7"),
    S29_8("Ostale specificirane ozljede prsnog koša", "S29.8"),
    S29_9("Nespecificirana ozljeda prsnog koša", "S29.9"),
    S30("Površinska ozljeda trbušne šupljine, donjeg dijela leđa i zdjelice", "S3O"),
    S30_0("Kontuzija donjeg dijela leđa i zdjelice", "S3O.0"),
    S30_1("Kontuzija trbušne stijenke", "S3O.1"),
    S30_2("Kontuzija vanjskih genitalnih organa", "S3O.2"),
    S30_7("Višestruke površinske ozljede trbušne šupljine, donjeg dijela leđa i zdjelice", "S3O.7"),
    S30_8("Ostale površinske ozljede trbušne šupljine, donjeg dijela leđa i zdjelice", "S3O.8"),
    S30_9("Površinska ozljeda trbušne šupljine, donjeg dijela leđa i zdjelice, nespecificiranog dijela", "S3O.9"),
    S31("Otvorena rana trbušne šupljine, donjeg dijela leđa i zdjelice", "S31"),
    S31_0("Otvorena rana donjeg dijela leđa i zdjelice", "S31.0"),
    S31_1("Otvorena rana trbušne stijenke", "S31.1"),
    S31_2("Otvorena rana penisa", "S31.2"),
    S31_3("Otvorena rana skrotuma i testisa", "S31.3"),
    S31_4("Otvorena rana vagine i vulve", "S31.4"),
    S31_5("Otvorena rana drugih i nespecificiranih vanjskih genitalnih organa", "S31.5"),
    S31_7("Višestruke otvorene rane trbušne šupljine, donjeg dijela leđa i zdjelice", "S31.7"),
    S31_8("Otvorena rana drugih i nespecificiranih dijelova trbušne šupljine, donjeg dijela leđa i zdjelice", "S31.8"),
    S32("Prijelom lumbalne kralježnice i zdjelice", "S32"),
    S32_0("Prijelom lumbalnog kralješka", "S32.0"),
    S32_1("Prijelom križne kosti (os sacrum)", "S32.1"),
    S32_2("Prijelom trtične kosti (os coccygis)", "S32.2"),
    S32_3("Prijelom bočne kosti (os ilium)", "S32.3"),
    S32_4("Prijelom acetabula", "S32.4"),
    S32_5("Prijelom preponske kosti (os pubis)", "S32.5"),
    S32_7("Višestruki prijelomi lumbalne kralježnice i zdjelice", "S32.7"),
    S32_8("Prijelom drugih i nespecificiranih dijelova lumbalne kralježnice i zdjelice", "S32.8"),
    S33("Dislokacija, iščašenje i nategnuće zglobova i ligamenata lumbalne kralježnice i zdjelice", "S33"),
    S33_0("Traumatska ruptura lumbalnoga intervertebralnog diska", "S33.0"),
    S33_1("Dislokacija lumbalnog kralješka", "S33.1"),
    S33_2("Dislokacija sakroilijakalnoga i sakrokokcigealnoga zgloba", "S33.2"),
    S33_3("Dislokacija drugih i nespecificiranih dijelova lumbalne kralježnice i zdjelice", "S33.3"),
    S33_4("Traumatska ruptura simfize pubične kosti", "S33.4"),
    S33_5("Iščašenje i nategnuće lumbalne kralježnice", "S33.5"),
    S33_6("Iščašenje i nategnuće sakroilijakalnoga zgloba", "S33.6"),
    S33_7("Iščašenje i nategnuće drugih i nespecificiranih dijelova lumbalne kralježnice i zdjelice", "S33.7"),
    S34("Ozljeda živaca i lumbalnog dijela kralježnične moždine u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S34"),
    S34_0("Potres i edem lumbalnog dijela kralježnične moždine", "S34.0"),
    S34_1("Ostale ozljede lumbalnog dijela kralježnične moždine", "S34.1"),
    S34_2("Ozljeda živčanog korijena lumbalne i sakralne kralježnice", "S34.2"),
    S34_3("Ozljeda kaude ekvine", "S34.3"),
    S34_4("Ozljeda lumbosakralnoga pleksusa", "S34.4"),
    S34_5("Ozljeda lumbalnih, sakralnih i pelvičnih simpatičkih živaca", "S34.5"),
    S34_6("Ozljeda perifernog(ih) živca(aca) trbušne šupljine, donjeg dijela leđa i zdjelice", "S34.6"),
    S34_8("Ozljeda drugih i nespecificiranih živaca u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S34.8"),
    S35("Ozljeda krvnih žila u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S35"),
    S35_0("Ozljeda abdominalne aorte", "S35.0"),
    S35_1("Ozljeda donje šuplje vene (v. cavae inferior)", "S35.1"),
    S35_2("Ozljeda celijačne ili mezenterične arterije", "S35.2"),
    S35_3("Ozljeda portalne ili splenične vene", "S35.3"),
    S35_4("Ozljeda bubrežnih krvnih žila", "S35.4"),
    S35_5("Ozljeda ilijačnih krvnih žila", "S35.5"),
    S35_7("Ozljeda više krvnih žila u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S35.7"),
    S35_8("Ozljeda drugih krvnih žila u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S35.8"),
    S35_9("Ozljeda nespecificirane krvne žile u području trbušne šupljine, donjeg dijela leđa i zdjelice", "S35.9"),
    S36("Ozljeda organa trbušne šupljine", "S36"),
    S36_0("Ozljeda slezene", "S36.0"),
    S36_1("Ozljeda jetre ili žučnjaka", "S36.1"),
    S36_2("Ozljeda gušterače", "S36.2"),
    S36_3("Ozljeda želuca", "S36.3"),
    S36_4("Ozljeda tankoga crijeva", "S36.4"),
    S36_5("Ozljeda kolona", "S36.5"),
    S36_6("Ozljeda rektuma", "S36.6"),
    S36_7("Ozljeda više intraabdominalnih organa", "S36.7"),
    S36_8("Ozljeda ostalih intraabdominalnih organa", "S36.8"),
    S36_9("Ozljeda nespecificiranoga intraabdominalnog organa", "S36.9"),
    S37("Ozljeda zdjeličnih organa", "S37"),
    S37_0("Ozljeda bubrega", "S37.0"),
    S37_1("Ozljeda mokraćovoda (uretera)", "S37.1"),
    S37_2("Ozljeda mokraćnog mjehura (vezike urinarije)", "S37.2"),
    S37_3("Ozljeda mokraćne cijevi (uretre)", "S37.3"),
    S37_4("Ozljeda jajnika (ovarija)", "S37.4"),
    S37_5("Ozljeda jajovoda (Fallopijeve tube)", "S37.5"),
    S37_6("Ozljeda maternice (uterusa)", "S37.6"),
    S37_7("Ozljeda više zdjeličnih organa", "S37.7"),
    S37_8("Ozljeda ostalih zdjeličnih organa", "S37.8"),
    S37_9("Ozljeda nespecificiranoga zdjeličnog organa", "S37.9"),
    S38("Zgnječenje (crush ozljeda) i traumatska amputacija dijela trbušne šupljine, donjeg dijela leđa i zdjelice", "S38"),
    S38_0("Zgnječenje vanjskih genitalnih organa", "S38.0"),
    S38_1("Zgnječenje drugih i nespecificiranih dijelova trbušne šupljine, donjeg dijela leđa i zdjelice", "S38.1"),
    S38_2("Traumatska amputacija vanjskih genitalnih organa", "S38.2"),
    S38_3("Traumatska amputacija drugih i nespecificiranih dijelova trbušne šupljine, donjeg dijela leđa i zdjelice", "S38.3"),
    S39("Druge i nescpecificirane ozljede trbušne šupljine, donjeg dijela leđa i zdjelice", "S39"),
    S39_0("Ozljeda mišića i tetiva trbušne šupljine, donjeg dijela leđa i zdjelice", "S39.0"),
    S39_6("Ozljeda intraabdomonalnog(ih) organa s organom(ima) zdjelice", "S39.6"),
    S39_7("Ostale višestruke ozljede trbušne šupljine, donjeg dijela leđa i zdjelice", "S39.7"),
    S39_8("Ostale specificirane ozljede trbušne šupljine, donjeg dijela leđa i zdjelice", "S39.8"),
    S39_9("Nespecificirana ozljeda trbušne šupljine, donjeg dijela leđa i zdjelice", "S39.9"),
    S40("Površinska ozljeda ramena i nadlaktice", "S4O"),
    S40_0("Kontuzija ramena i nadlaktice", "S4O.0"),
    S40_7("Višestruke površinske ozljede ramena i nadlaktice", "S4O.7"),
    S40_8("Ostale površinske ozljede ramena i nadlaktice", "S4O.8"),
    S40_9("Površinska ozljeda ramena i nadlaktice, nespecificirana", "S4O.9"),
    S41("Otvorena rana ramena i nadlaktice", "S41"),
    S41_0("Otvorena rana ramena", "S41.0"),
    S41_1("Otvorena rana nadlaktice", "S41.1"),
    S41_7("Višestruke otvorene rane ramena i nadlaktice", "S41.7"),
    S41_8("Otvorena rana drugih i nespecificiranih dijelova ramenog pojasa", "S41.8"),
    S42("Prijelom ramena i nadlaktice", "S42"),
    S42_0("Prijelom ključne kosti (klavikule)", "S42.0"),
    S42_1("Prijelom lopatice (skapule)", "S42.1"),
    S42_2("Prijelom gornjega kraja nadlaktične kosti (humerusa)", "S42.2"),
    S42_3("Prijelom dijafize humerusa", "S42.3"),
    S42_4("Prijelom donjega kraja humerusa", "S42.4"),
    S42_7("Višestruki prijelomi klavikule, skapule i humerusa", "S42.7"),
    S42_8("Prijelom ostalih dijelova ramena i nadlaktice", "S42.8"),
    S42_9("Prijelom ramenog pojasa, nespecificiranog dijela", "S42.9"),
    S43("Dislokacija, iščašenje i nategnuće zglobova i ligamenata ramenog pojasa", "S43"),
    S43_0("Dislokacija ramenoga zgloba", "S43.0"),
    S43_1("Dislokacija akromioklavikularnoga zgloba", "S43.1"),
    S43_2("Dislokacija sternoklavikularnoga zgloba", "S43.2"),
    S43_3("Dislokacija drugih i nespecificiranih dijelova ramenog pojasa", "S43.3"),
    S43_4("Iščašenje i nategnuće ramenoga zgloba", "S43.4"),
    S43_5("Iščašenje i nategnuće akromioklavikularnoga zgloba", "S43.5"),
    S43_6("Iščašenje i nategnuće sternoklavikularnoga zgloba", "S43.6"),
    S43_7("Iščašenje i nategnuće drugih i nespecificiranih dijelova ramenog pojasa", "S43.7"),
    S44("Ozljeda živaca u području ramena i nadlaktice", "S44"),
    S44_0("Ozljeda ulnarnog živca u području nadlaktice", "S44.0"),
    S44_1("Ozljeda medijanog živca u području nadlaktice", "S44.1"),
    S44_2("Ozljeda radijalnog živca u području nadlaktice", "S44.2"),
    S44_3("Ozljeda aksilarnog živca", "S44.3"),
    S44_4("Ozljeda muskulokutaneusa", "S44.4"),
    S44_5("Ozljeda senzibilnog kutaneusa u području ramena i nadlaktice", "S44.5"),
    S44_7("Ozljeda više živaca u području ramena i nadlaktice", "S44.7"),
    S44_8("Ozljeda ostalih živaca u području ramena i nadlaktice", "S44.8"),
    S44_9("Ozljeda nespecificiranog živca u području ramena i nadlaktice", "S44.9"),
    S45("Ozljeda krvnih žila u području ramena i nadlaktice", "S45"),
    S45_0("Ozljeda aksilarne arterije", "S45.0"),
    S45_1("Ozljeda brahijalne arterije", "S45.1"),
    S45_2("Ozljeda aksilarne i brahijalne vene", "S45.2"),
    S45_3("Ozljeda superficijalne vene u području ramena i nadlaktice", "S45.3"),
    S45_7("Ozljeda više krvnih žila u području ramena i nadlaktice", "S45.7"),
    S45_8("Ozljeda ostalih krvnih žila u području ramena i nadlaktice", "S45.8"),
    S45_9("Ozljeda nespecificirane krvne žile u području ramena i nadlaktice", "S45.9"),
    S46("Ozljeda mišića i tetive u području ramena i nadlaktice", "S46"),
    S46_0("Ozljeda tetive rotatorne manžete ramena", "S46.0"),
    S46_1("Ozljeda mišića i tetive duge glave bicepsa", "S46.1"),
    S46_2("Ozljeda mišića i tetive drugih dijelova bicepsa", "S46.2"),
    S46_3("Ozljeda mišića i tetive tricepsa", "S46.3"),
    S46_7("Ozljeda više mišića i tetiva u području ramena i nadlaktice", "S46.7"),
    S46_8("Ozljeda drugih mišića i tetiva u području ramena i nadlaktice", "S46.8"),
    S46_9("Ozljeda nespecificiranog mišića i tetive u području ramena i nadlaktice", "S46.9"),
    S47("Zgnječenje (crush ozljeda) ramena i nadlaktice", "S47"),
    S47_0("Zgnječenje ramena i nadlaktice", "S47.0"),
    S48("Traumatska amputacija ramena i nadlaktice", "S48"),
    S48_0("Traumatska amputacija u ramenome zglobu", "S48.0"),
    S48_1("Traumatska amputacija u području između ramena i lakta", "S48.1"),
    S48_9("Traumatska amputacija ramena i nadlaktice, nespecificirane razine", "S48.9"),
    S49("Druge i nespecificirane ozljede ramena i nadlaktice", "S49"),
    S49_7("Višestruke ozljede ramena i nadlaktice", "S49.7"),
    S49_8("Ostale specificirane ozljede ramena i nadlaktice", "S49.8"),
    S49_9("Nespecificirana ozljeda ramena i nadlaktice", "S49.9"),
    S50("Površinska ozljeda podlaktice", "S5O"),
    S50_0("Kontuzija lakta", "S5O.0"),
    S50_1("Kontuzija drugih i nespecificiranih dijelova podlaktice", "S5O.1"),
    S50_7("Višestruke površinske ozljede podlaktice", "S5O.7"),
    S50_8("Ostale površinske ozljede podlaktice", "S5O.8"),
    S50_9("Površinska ozljeda podlaktice, nespecificirana", "S5O.9"),
    S51("Otvorena rana podlaktice", "S51"),
    S51_0("Otvorena rana lakta", "S51.0"),
    S51_7("Višestruke otvorene rane podlaktice", "S51.7"),
    S51_8("Otvorena rana ostalih dijelova podlaktice", "S51.8"),
    S51_9("Otvorena rana podlaktice, nespecificiranog dijela", "S51.9"),
    S52("Prijelom podlaktice", "S52"),
    S52_0("Prijelom gornjega kraja lakatne kosti (ulne)", "S52.0"),
    S52_1("Prijelom gornjega kraja palčane kosti (radijusa)", "S52.1"),
    S52_2("Prijelom dijafize lakatne kosti (ulne)", "S52.2"),
    S52_3("Prijelom dijafize palčane kosti (radijusa)", "S52.3"),
    S52_4("Prijelom dijafize lakatne i palčane kosti (ulne i radijusa)", "S52.4"),
    S52_5("Prijelom donjeg dijela palčane kosti (radijusa)", "S52.5"),
    S52_6("Prijelom donjeg dijela lakatne i palčane kosti (ulne i radijusa)", "S52.6"),
    S52_7("Višestruki prijelomi podlaktice", "S52.7"),
    S52_8("Prijelom ostalih dijelova podlaktice", "S52.8"),
    S52_9("Prijelom podlaktice, nespecificiranog dijela", "S52.9"),
    S53("Dislokacija, iščašenje i nategnuće lakatnih zglobova i ligamenata", "S53"),
    S53_0("Dislokacija glave palčane kosti (radijusa)", "S53.0"),
    S53_1("Dislokacija lakta, nespecificirana", "S53.1"),
    S53_2("Traumatska ruptura radijalnoga kolateralnog ligamenta", "S53.2"),
    S53_3("Traumatska ruptura ulnarnoga kolateralnog ligamenta", "S53.3"),
    S53_4("Iščašenje i nategnuće lakta", "S53.4"),
    S54("Ozljeda živaca u području podlaktice", "S54"),
    S54_0("Ozljeda ulnarnog živca u području podlaktice", "S54.0"),
    S54_1("Ozljeda medijanog živca u području podlaktice", "S54.1"),
    S54_2("Ozljeda radijalnog živca u području podlaktice", "S54.2"),
    S54_3("Ozljeda senzibilnog kutaneusa u području podlaktice", "S54.3"),
    S54_7("Ozljeda više živaca u području podlaktice", "S54.7"),
    S54_8("Ozljeda ostalih živaca u području podlaktice", "S54.8"),
    S54_9("Ozljeda nespecificiranog živca u području podlaktice", "S54.9"),
    S55("Ozljeda krvnih žila u području podlaktice", "S55"),
    S55_0("Ozljeda ulnarne arterije u području podlaktice", "S55.0"),
    S55_1("Ozljeda radijalne arterije u području podlaktice", "S55.1"),
    S55_2("Ozljeda vene u području podlaktice", "S55.2"),
    S55_7("Ozljeda više krvnih žila u području podlaktice", "S55.7"),
    S55_8("Ozljeda ostalih krvnih žila u području podlaktice", "S55.8"),
    S55_9("Ozljeda nespecificirane krvne žile u području podlaktice", "S55.9"),
    S56("Ozljeda mišića i tetive u području podlaktice", "S56"),
    S56_0("Ozljeda mišića i tetive fleksora palca u području podlaktice", "S56.0"),
    S56_1("Ozljeda mišića i tetive fleksora ostalih prstiju u području podlaktice", "S56.1"),
    S56_2("Ozljeda ostalih mišića i tetiva fleksora u području podlaktice", "S56.2"),
    S56_3("Ozljeda mišića i tetive ekstenzora ili abduktora palca u području podlaktice", "S56.3"),
    S56_4("Ozljeda mišića i tetive ekstenzora ostalih prstiju u području podlaktice", "S56.4"),
    S56_5("Ozljeda ostalih mišića i tetiva ekstenzora u području podlaktice", "S56.5"),
    S56_7("Ozljeda više mišića i tetiva u području podlaktice", "S56.7"),
    S56_8("Ozljeda drugih i nespecificiranih mišića i tetiva u području podlaktice", "S56.8"),
    S57("Zgnječenje (crush ozljeda) podlaktice", "S57"),
    S57_0("Zgnječenje lakta", "S57.0"),
    S57_8("Zgnječenje drugih dijelova podlaktice", "S57.8"),
    S57_9("Zgnječenje podlaktice, nespecificiranog dijela", "S57.9"),
    S58("Traumatska amputacija podlaktice", "S58"),
    S58_0("Traumatska amputacija u razini lakta", "S58.0"),
    S58_1("Traumatska amputacija u području između lakta i ručnog zgloba", "S58.1"),
    S58_9("Traumatska amputacija podlaktice, nespecificirane razine", "S58.9"),
    S59("Druge i nespecificirane ozljede podlaktice", "S59"),
    S59_7("Višestruke ozljede podlaktice", "S59.7"),
    S59_8("Ostale specificirane ozljede podlaktice", "S59.8"),
    S59_9("Nespecificirana ozljeda podlaktice", "S59.9"),
    S60("Površinska ozljeda ručnoga zgloba i šake", "S6O"),
    S60_0("Kontuzija prsta(iju) bez oštećenja nokta", "S6O.0"),
    S60_1("Kontuzija prsta(iju) s oštećenjem nokta", "S6O.1"),
    S60_2("Kontuzija ostalih dijelova ručnoga zgloba i šake", "S6O.2"),
    S60_7("Višestruke površinske ozljede ručnoga zgloba i šake", "S6O.7"),
    S60_8("Ostale površinske ozljede ručnoga zgloba i šake", "S6O.8"),
    S60_9("Površinska ozljeda ručnoga zgloba i šake, nespecificirana", "S6O.9"),
    S61("Otvorena rana ručnoga zgloba i šake", "S61"),
    S61_0("Otvorena rana prsta(iju) bez oštećenja nokta", "S61.0"),
    S61_1("Otvorena rana prsta(iju) s oštećenjem nokta", "S61.1"),
    S61_7("Višestruke otvorene rane ručnoga zgloba i šake", "S61.7"),
    S61_8("Otvorena rana ostalih dijelova ručnoga zgloba i šake", "S61.8"),
    S61_9("Otvorena rana ručnoga zgloba i šake, nespecificiranog dijela", "S61.9"),
    S62("Prijelom u području ručnoga zgloba i šake", "S62"),
    S62_0("Prijelom navikularne ili skafoidne kosti šake", "S62.0"),
    S62_1("Prijelom drugih kostiju pešća (karpalnih kostiju)", "S62.1"),
    S62_2("Prijelom prve kosti zapešća (metakarpalne kosti)", "S62.2"),
    S62_3("Prijelom ostalih kostiju zapešća", "S62.3"),
    S62_4("Višestruki prijelomi kostiju zapešća", "S62.4"),
    S62_5("Prijelom palca", "S62.5"),
    S62_6("Prijelom ostalih prstiju", "S62.6"),
    S62_7("Višestruki prijelomi prstiju", "S62.7"),
    S62_8("Prijelom drugih i nespecificiranih dijelova ručnoga zgloba i šake", "S62.8"),
    S63("Dislokacija, iščašenje i nategnuće zglobova i ligamenata u području ručnoga zgloba i šake", "S63"),
    S63_0("Dislokacija ručnoga zgloba", "S63.0"),
    S63_1("Dislokacija prsta", "S63.1"),
    S63_2("Višestruke dislokacije prstiju", "S63.2"),
    S63_3("Traumatska ruptura ligamenta ručnoga zgloba i pešća (karpusa)", "S63.3"),
    S63_4("Traumatska ruptura ligamenta prsta u metakarpofalangealnom(im) i interfalangealnom(im) zglobu(ovima)", "S63.4"),
    S63_5("Iščašenje i nategnuće ručnoga zgloba", "S63.5"),
    S63_6("Iščašenje i nategnuće prsta(iju)", "S63.6"),
    S63_7("Iščašenje i nategnuće ostalih i nespecificiranih dijelova šake", "S63.7"),
    S64("Ozljeda živaca u području ručnoga zgloba i šake", "S64"),
    S64_0("Ozljeda ulnarnog živca u području ručnoga zgloba i šake", "S64.0"),
    S64_1("Ozljeda medijanog živca u području ručnoga zgloba i šake", "S64.1"),
    S64_2("Ozljeda radijalnog živca u području ručnoga zgloba i šake", "S64.2"),
    S64_3("Ozljeda digitalnog živca palca", "S64.3"),
    S64_4("Ozljeda digitalnog živca ostalih prstiju", "S64.4"),
    S64_7("Ozljeda više živaca u području ručnoga zgloba i šake", "S64.7"),
    S64_8("Ozljeda ostalih živaca u području ručnoga zgloba i šake", "S64.8"),
    S64_9("Ozljeda nespecificiranog živca u području ručnoga zgloba i šake", "S64.9"),
    S65("Ozljeda krvnih žila u području ručnoga zgloba i šake", "S65"),
    S65_0("Ozljeda ulnarne arterije u području ručnoga zgloba i šake", "S65.0"),
    S65_1("Ozljeda radijalne arterije u području ručnoga zgloba i šake", "S65.1"),
    S65_2("Ozljeda površinskoga palmarnog luka", "S65.2"),
    S65_3("Ozljeda dubokoga palmarnog luka", "S65.3"),
    S65_4("Ozljeda krvne(ih) žile(a) palca", "S65.4"),
    S65_5("Ozljeda krvne(ih) žile(a) drugih prstiju", "S65.5"),
    S65_7("Ozljeda više krvnih žila u području ručnoga zgloba i šake", "S65.7"),
    S65_8("Ozljeda ostalih krvnih žila u području ručnoga zgloba i šake", "S65.8"),
    S65_9("Ozljeda nespecificirane krvne žile u području ručnoga zgloba i šake", "S65.9"),
    S66("Ozljeda mišića i tetive u području ručnoga zgloba i šake", "S66"),
    S66_0("Ozljeda mišića i tetive dugačkog fleksora palca u području ručnoga zgloba i šake", "S66.0"),
    S66_1("Ozljeda mišića i tetive fleksora ostalih prstiju u području ručnoga zgloba i šake", "S66.1"),
    S66_2("Ozljeda mišića i tetive ekstenzora palca u području ručnoga zgloba i šake", "S66.2"),
    S66_3("Ozljeda mišića i tetive ekstenzora ostalih prstiju u području ručnoga zgloba i šake", "S66.3"),
    S66_4("Ozljeda mišića i tetive intrinzora palca u području ručnoga zgloba i šake", "S66.4"),
    S66_5("Ozljeda mišića i tetive intrinzora ostalih prstiju u području ručnoga zgloba i šake", "S66.5"),
    S66_6("Ozljeda više mišića i tetiva fleksora u području ručnoga zgloba i šake", "S66.6"),
    S66_7("Ozljeda više mišića i tetiva ekstenzora u području ručnoga zgloba i šake", "S66.7"),
    S66_8("Ozljeda ostalih mišića i tetiva u području ručnoga zgloba i šake", "S66.8"),
    S66_9("Ozljeda nespecificiranog mišića i tetive u području ručnoga zgloba i šake", "S66.9"),
    S67("Zgnječenje (crush ozljeda) ručnoga zgloba i šake", "S67"),
    S67_0("Zgnječenje palca i drugih prstiju", "S67.0"),
    S67_8("Zgnječenje drugih i nespecificiranih dijelova ručnoga zgloba i šake", "S67.8"),
    S68("Traumatska amputacija ručnoga zgloba i šake", "S68"),
    S68_0("Traumatska amputacija palca (kompletna) (djelomična)", "S68.0"),
    S68_1("Traumatska amputacija drugog (samo jednog) prsta (kompletna) (djelomična)", "S68.1"),
    S68_2("Traumatska amputacija dvaju ili više prstiju (kompletna) (djelomična)", "S68.2"),
    S68_3("Kombinirana traumatska amputacija (dijela) prsta(iju) s drugim dijelovima ručnoga zgloba i šake", "S68.3"),
    S68_4("Traumatska amputacija šake u razini ručnoga zgloba", "S68.4"),
    S68_8("Traumatska amputacija drugih dijelova ručnoga zgloba i šake", "S68.8"),
    S68_9("Traumatska amputacija ručnoga zgloba i šake, nespecificirane razine", "S68.9"),
    S69("Druge i nespecificirane ozljede ručnoga zgloba i šake", "S69"),
    S69_7("Višestruke ozljede ručnoga zgloba i šake", "S69.7"),
    S69_8("Ostale specificirane ozljede ručnoga zgloba i šake", "S69.8"),
    S69_9("Nespecificirana ozljeda ručnoga zgloba i šake", "S69.9"),
    S70("Površinska ozljeda boka (kuka) i bedra", "S7O"),
    S70_0("Kontuzija boka (kuka)", "S7O.0"),
    S70_1("Kontuzija bedra", "S7O.1"),
    S70_7("Višestruke površinske ozljede boka (kuka) i bedra", "S7O.7"),
    S70_8("Ostale površinske ozljede boka (kuka) i bedra", "S7O.8"),
    S70_9("Površinska ozljeda boka (kuka) i bedra, nespecificirana", "S7O.9"),
    S71("Otvorena rana boka (kuka) i bedra", "S71"),
    S71_0("Otvorena rana boka (kuka)", "S71.0"),
    S71_1("Otvorena rana bedra", "S71.1"),
    S71_7("Višestruke otvorene rane boka (kuka) i bedra", "S71.7"),
    S71_8("Otvorena rana drugih i nespecificiranih dijelova zdjeličnog pojasa", "S71.8"),
    S72("Prijelom bedrene kosti (femura)", "S72"),
    S72_0("Prijelom vrata bedrene kosti", "S72.0"),
    S72_1("Peritrohanterični prijelom", "S72.1"),
    S72_2("Suptrohanterični prijelom", "S72.2"),
    S72_3("Prijelom dijafize bedrene kosti", "S72.3"),
    S72_4("Prijelom donjeg kraja bedrene kosti", "S72.4"),
    S72_7("Višestruki prijelomi bedrene kosti", "S72.7"),
    S72_8("Prijelomi ostalih dijelova bedrene kosti", "S72.8"),
    S72_9("Prijelom bedrene kosti, nespecificiranog dijela", "S72.9"),
    S73("Dislokacija, iščašenje i nategnuće zgloba i ligamenta kuka", "S73"),
    S73_0("Dislokacija kuka", "S73.0"),
    S73_1("Iščašenje i nategnuće kuka", "S73.1"),
    S74("Ozljeda živaca u području kuka i bedra", "S74"),
    S74_0("Ozljeda ishijadičnog živca u području kuka i bedra", "S74.0"),
    S74_1("Ozljeda femoralnog živca u području kuka i bedra", "S74.1"),
    S74_2("Ozljeda senzibilnog kutaneusa u području kuka i bedra", "S74.2"),
    S74_7("Ozljeda više živaca u području kuka i bedra", "S74.7"),
    S74_8("Ozljeda ostalih živaca u području kuka i bedra", "S74.8"),
    S74_9("Ozljeda nespecificiranog živca u području kuka i bedra", "S74.9"),
    S75("Ozljeda krvnih žila u području kuka i bedra", "S75"),
    S75_0("Ozljeda femoralne arterije", "S75.0"),
    S75_1("Ozljeda femoralne vene u području kuka i bedra", "S75.1"),
    S75_2("Ozljeda vene saphene magne u području kuka i bedra", "S75.2"),
    S75_7("Ozljeda više krvnih žila u području kuka i bedra", "S75.7"),
    S75_8("Ozljeda ostalih krvnih žila u području kuka i bedra", "S75.8"),
    S75_9("Ozljeda nespecificiranih krvnih žila u području kuka i bedra", "S75.9"),
    S76("Ozljeda mišića i tetiva u području kuka i bedra", "S76"),
    S76_0("Ozljeda mišića i tetive kuka", "S76.0"),
    S76_1("Ozljeda mišića i tetive kvadricepsa", "S76.1"),
    S76_2("Ozljeda mišića i tetive aduktora bedra", "S76.2"),
    S76_3("Ozljeda mišića i tetive stražnje mišićne skupine u području bedra", "S76.3"),
    S76_4("Ozljeda drugih i nespecificiranih mišića i tetiva u području bedra", "S76.4"),
    S76_7("Ozljeda više mišića i tetiva u području kuka i bedra", "S76.7"),
    S77("Zgnječenje (crush ozljeda) kuka i bedra", "S77"),
    S77_0("Zgnječenje kuka", "S77.0"),
    S77_1("Zgnječenje bedra", "S77.1"),
    S77_2("Zgnječenje kuka i bedra", "S77.2"),
    S78("Traumatska amputacija kuka i bedra", "S78"),
    S78_0("Traumatska amputacija zgloba kuka", "S78.0"),
    S78_1("Traumatska amputacija u području između kuka i koljena", "S78.1"),
    S78_9("Traumatska amputacija kuka i bedra, nespecificirane razine", "S78.9"),
    S79("Druge i nespecificirane ozljede kuka i bedra", "S79"),
    S79_7("Višestruke ozljede kuka i bedra", "S79.7"),
    S79_8("Ostale specificirane ozljede kuka i bedra", "S79.8"),
    S79_9("Nespecificirana ozljeda kuka i bedra", "S79.9"),
    S80("Površinska ozljeda potkoljenice", "S8O"),
    S80_0("Kontuzija koljena", "S8O.0"),
    S80_1("Kontuzija drugih i nespecificiranih dijelova potkoljenice", "S8O.1"),
    S80_7("Višestruke površinske ozljede potkoljenice", "S8O.7"),
    S80_8("Ostale površinske ozljede potkoljenice", "S8O.8"),
    S80_9("Površinska ozljeda potkoljenice, nespecificirana", "S8O.9"),
    S81("Otvorena rana potkoljenice", "S81"),
    S81_0("Otvorena rana koljena", "S81.0"),
    S81_7("Višestruke otvorene rane potkoljenice", "S81.7"),
    S81_8("Otvorena rana ostalih dijelova potkoljenice", "S81.8"),
    S81_9("Otvorena rana potkoljenice, nespecificiranog dijela", "S81.9"),
    S82("Prijelom potkoljenice, uključujući nožni zglob", "S82"),
    S82_0("Prijelom ivera (patele)", "S82.0"),
    S82_1("Prijelom gornjega kraja goljenične kosti (tibije)", "S82.1"),
    S82_2("Prijelom dijafize goljenične kosti (tibije)", "S82.2"),
    S82_3("Prijelom donjeg kraja goljenične kosti (tibije)", "S82.3"),
    S82_4("Prijelom lisne kosti (fibule)", "S82.4"),
    S82_5("Prijelom medijalnog maleola", "S82.5"),
    S82_6("Prijelom lateralnog maleola", "S82.6"),
    S82_7("Višestruki prijelomi potkoljenice", "S82.7"),
    S82_8("Prijelomi ostalih dijelova potkoljenice", "S82.8"),
    S82_9("Prijelom potkoljenice, nespecificiranog dijela", "S82.9"),
    S83("Dislokacija, iščašenje i nategnuće koljenskih zglobova i ligamenata", "S83"),
    S83_0("Dislokacija ivera (patele)", "S83.0"),
    S83_1("Dislokacija koljena", "S83.1"),
    S83_2("Rascjep meniska, sadašnji", "S83.2"),
    S83_3("Rascjep zglobne hrskavice koljena, sadašnji", "S83.3"),
    S83_4("Iščašenje i nategnuće (fibularnog) (tibijalnog) kolateralnog ligamenta koljena", "S83.4"),
    S83_5("Iščašenje i nategnuće (prednjeg) (stražnjeg) križnog ligamenta koljena", "S83.5"),
    S83_6("Iščašenje i nategnuće drugih i nespecificiranih dijelova koljena", "S83.6"),
    S83_7("Ozljeda više koljenskih struktura", "S83.7"),
    S84("Ozljeda živaca u području potkoljenice", "S84"),
    S84_0("Ozljeda tibijalnog živca u području potkoljenice", "S84.0"),
    S84_1("Ozljeda peronealnog živca u području potkoljenice", "S84.1"),
    S84_2("Ozljeda senzibilnog kutaneusa u području potkoljenice", "S84.2"),
    S84_7("Ozljeda više živaca u području potkoljenice", "S84.7"),
    S84_8("Ozljeda ostalih živaca u području potkoljenice", "S84.8"),
    S84_9("Ozljeda nespecificiranog živca u području potkoljenice", "S84.9"),
    S85("Ozljeda krvnih žila u području potkoljenice", "S85"),
    S85_0("Ozljeda poplitealne arterije", "S85.0"),
    S85_1("Ozljeda tibijalne arterije (anterior) (posterior)", "S85.1"),
    S85_2("Ozljeda peronealne arterije", "S85.2"),
    S85_3("Ozljeda vene saphene magne u području potkoljenice", "S85.3"),
    S85_4("Ozljeda vene saphene parve u području potkoljenice", "S85.4"),
    S85_5("Ozljeda poplitealne vene", "S85.5"),
    S85_7("Ozljeda više krvnih žila u području potkoljenice", "S85.7"),
    S85_8("Ozljeda ostalih krvnih žila u području potkoljenice", "S85.8"),
    S85_9("Ozljeda nespecificirane krvne žile u području potkoljenice", "S85.9"),
    S86("Ozljeda mišića i tetiva u području potkoljenice", "S86"),
    S86_0("Ozljeda Ahilove tetive", "S86.0"),
    S86_1("Ozljeda ostalih mišića i tetiva stražnje mišićne skupine u području potkoljenice", "S86.1"),
    S86_2("Ozljeda mišića i tetive(a) prednje mišićne skupine u području potkoljenice", "S86.2"),
    S86_3("Ozljeda mišića i tetive(a) peronealne mišićne skupine u području potkoljenice", "S86.3"),
    S86_7("Ozljeda više mišića i tetiva u području potkoljenice", "S86.7"),
    S86_8("Ozljeda ostalih mišića i tetiva u području potkoljenice", "S86.8"),
    S86_9("Ozljeda nespecificiranog mišića i tetive u području potkoljenice", "S86.9"),
    S87("Zgnječenje (crush ozljeda) potkoljenice", "S87"),
    S87_0("Zgnječenje koljena", "S87.0"),
    S87_8("Zgnječenje drugih i nespecificiranih dijelova potkoljenice", "S87.8"),
    S88("Traumatska amputacija potkoljenice", "S88"),
    S88_0("Traumatska amputacija u razini koljena", "S88.0"),
    S88_1("Traumatska amputacija u području između koljena i gležnja", "S88.1"),
    S88_9("Traumatska amputacija potkoljenice, nespecificirane razine", "S88.9"),
    S89("Druge i nespecificirane ozljede potkoljenice", "S89"),
    S89_7("Višestruke ozljede potkoljenice", "S89.7"),
    S89_8("Ostale specificirane ozljede potkoljenice", "S89.8"),
    S89_9("Nespecificirana ozljeda potkoljenice", "S89.9"),
    S90("Površinska ozljeda nožnog zgloba (gležnja) i stopala", "S9O"),
    S90_0("Kontuzija nožnoga zgloba (gležnja)", "S9O.0"),
    S90_1("Kontuzija nožnog(ih) prsta(iju) bez oštećenja nokta", "S9O.1"),
    S90_2("Kontuzija nožnog(ih) prsta(iju) s oštećenjem nokta", "S9O.2"),
    S90_3("Kontuzija drugih i nespecificiranih dijelova stopala", "S9O.3"),
    S90_7("Višestruke površinske ozljede nožnoga zgloba (gležnja) i stopala", "S9O.7"),
    S90_8("Ostale površinske ozljede nožnoga zgloba (gležnja) i stopala", "S9O.8"),
    S90_9("Površinska ozljeda nožnog zgloba (gležnja) i stopala, nespecificirana", "S9O.9"),
    S91("Otvorena rana nožnoga zgloba (gležnja) i stopala", "S91"),
    S91_0("Otvorena rana nožnoga zgloba (gležnja)", "S91.0"),
    S91_1("Otvorena rana nožnog(ih) prsta(iju) bez oštećenja nokta", "S91.1"),
    S91_2("Otvorena rana nožnog(ih) prsta(iju) s oštećenjem nokta", "S91.2"),
    S91_3("Otvorena rana ostalih dijelova stopala", "S91.3"),
    S91_7("Višestruke otvorene rane nožnoga zgloba (gležnja) i stopala", "S91.7"),
    S92("Prijelom stopala, osim nožnoga zgloba (gležnja)", "S92"),
    S92_0("Prijelom kalkaneusa", "S92.0"),
    S92_1("Prijelom gležanjske kosti (talusa)", "S92.1"),
    S92_2("Prijelom drugih kostiju nožja (tarzalnih kostiju)", "S92.2"),
    S92_3("Prijelom kostiju donožja (metatarzalnih kostiju)", "S92.3"),
    S92_4("Prijelom nožnog palca", "S92.4"),
    S92_5("Prijelom ostalih nožnih prstiju", "S92.5"),
    S92_7("Višestruki prijelomi stopala", "S92.7"),
    S92_9("Prijelom stopala, nespecificiran", "S92.9"),
    S93("Dislokacija, iščašenje i nategnuće zglobova i ligamenata u području nožnoga zgloba (gležnja) i stopala", "S93"),
    S93_0("Dislokacija nožnoga zgloba", "S93.0"),
    S93_1("Dislokacija prsta(iju)", "S93.1"),
    S93_2("Ruptura ligamenata u području nožnoga zgloba (gležnja) i stopala", "S93.2"),
    S93_3("Dislokacija drugih i nespecificiranih dijelova stopala", "S93.3"),
    S93_4("Iščašenje i nategnuće nožnoga zgloba (gležnja)", "S93.4"),
    S93_5("Iščašenje i nategnuće nožnoga prsta(iju)", "S93.5"),
    S93_6("Iščašenje i nategnuće drugih i nespecificiranih dijelova stopala", "S93.6"),
    S94("Ozljeda živaca u području gležnja i stopala", "S94"),
    S94_0("Ozljeda lateralnoga plantarnog živca", "S94.0"),
    S94_1("Ozljeda medijalnoga plantarnog živca", "S94.1"),
    S94_2("Ozljeda dubokog peronealnog živca (n. peroneus profundus) u području gležnja i stopala", "S94.2"),
    S94_3("Ozljeda senzibilnog kutaneusa u području gležnja i stopala", "S94.3"),
    S94_7("Ozljeda više živaca u području gležnja i stopala", "S94.7"),
    S94_8("Ozljeda ostalih živaca u području gležnja i stopala", "S94.8"),
    S94_9("Ozljeda nespecificiranog živca u području gležnja i stopala", "S94.9"),
    S95("Ozljeda krvnih žila u području gležnja i stopala", "S95"),
    S95_0("Ozljeda dorzalne arterije stopala (a. dorsalis pedis)", "S95.0"),
    S95_1("Ozljeda plantarne arterije stopala (a. plantaris)", "S95.1"),
    S95_2("Ozljeda dorzalne vene stopala (v. dorsalis pedis)", "S95.2"),
    S95_7("Ozljeda više krvnih žila u području gležnja i stopala", "S95.7"),
    S95_8("Ozljeda ostalih krvnih žila u području gležnja i stopala", "S95.8"),
    S95_9("Ozljeda nespecificirane krvne žile u području gležnja i stopala", "S95.9"),
    S96("Ozljeda mišića i tetive u području gležnja i stopala", "S96"),
    S96_0("Ozljeda mišića i tetive dugačkog fleksora nožnoga prsta u području gležnja i stopala", "S96.0"),
    S96_1("Ozljeda mišića i tetive dugačkog ekstenzora nožnoga prsta u području gležnja i stopala", "S96.1"),
    S96_2("Ozljeda mišića i tetive intrinzora u području gležnja i stopala", "S96.2"),
    S96_7("Ozljeda više mišića i tetiva u području gležnja i stopala", "S96.7"),
    S96_8("Ozljeda ostalih mišića i tetiva u području gležnja i stopala", "S96.8"),
    S96_9("Ozljeda nespecificiranog mišića i tetive u području gležnja i stopala", "S96.9"),
    S97("Zgnječenje (crush ozljeda) gležnja i stopala", "S97"),
    S97_0("Zgnječenje gležnja", "S97.0"),
    S97_1("Zgnječenje nožnoga prsta(iju)", "S97.1"),
    S97_8("Zgnječenje ostalih dijelova gležnja i stopala", "S97.8"),
    S98("Traumatska amputacija gležnja i stopala", "S98"),
    S98_0("Traumatska amputacija stopala u razini gležnja", "S98.0"),
    S98_1("Traumatska amputacija jednoga nožnog prsta", "S98.1"),
    S98_2("Traumatska amputacija dvaju ili više nožnih prstiju", "S98.2"),
    S98_3("Traumatska amputacija ostalih dijelova stopala", "S98.3"),
    S98_4("Traumatska amputacija stopala, nespecificirane razine", "S98.4"),
    S99("Druge i nespecificirane ozljede gležnja i stopala", "S99"),
    S99_7("Višestruke ozljede gležnja i stopala", "S99.7"),
    S99_8("Ostale specificirane ozljede gležnja i stopala", "S99.8"),
    S99_9("Nespecificirana ozljeda gležnja i stopala", "S99.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesS(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
