package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesJ {
    
    J00("Akutni nazofaringitis (obična prehlada)", "J00"),
    J00_0("Akutni nazofaringitis (obična prehlada)", "J00.0"),
    J01("Akutna upala sinusa (akutni sinusitis)", "J01"),
    J01_0("Akutni maksilarni sinusitis", "J01.0"),
    J01_1("Akutni frontalni sinusitis", "J01.1"),
    J01_2("Akutni etmoidni sinusitis", "J01.2"),
    J01_3("Aktuni sfenoidni sinusitis", "J01.3"),
    J01_4("Akutni pansinusitis", "J01.4"),
    J01_8("Drugi akutni sinusitis", "J01.8"),
    J01_9("Akutni sinusitis, nespecificiran", "J01.9"),
    J02("Akutna upala ždrijela (akutni faringitis)", "J02"),
    J02_0("Streptokokni faringitis", "J02.0"),
    J02_8("Akutni faringitis uzrokovan drugim specificiranim uzročnicima", "J02.8"),
    J02_9("Akutni faringitis, nespecificiran", "J02.9"),
    J03("Akutna upala tonzila (akutni tonzilitis)", "J03"),
    J03_0("Streptokokni tonzilitis", "J03.0"),
    J03_8("Akutni tonzilitis uzrokovan drugim specificiranim mikroorganizmima", "J03.8"),
    J03_9("Akutni tonzilitis, nespecificiran", "J03.9"),
    J04("Akutna upala grkljana i dušnika (akutni laringitis i traheitis)", "J04"),
    J04_0("Akutni laringitis", "J04.0"),
    J04_1("Akutni traheitis", "J04.1"),
    J04_2("Akutni laringotraheitis", "J04.2"),
    J05("Akutni opstruktivni laringitis (krup) i epiglotitis", "J05"),
    J05_0("Akutni opstruktivni laringitis (krup)", "J05.0"),
    J05_1("Akutni epiglotitis", "J05.1"),
    J06("Akutna infekcija gornjega dišnog sustava multiplih i nespecificiranih lokalizacija", "J06"),
    J06_0("Akutni laringofaringitis", "J06.0"),
    J06_8("Druge infekcije gornjega dišnog sustava multiple lokalizacije", "J06.8"),
    J06_9("Akutna infekcija gornjega dišnog sustava, nespecificirana", "J06.9"),
    J09("Influenca uzrokovana dokazanim virusom ptičje gripe", "J09"),
    J09_0("Influenca uzrokovana dokazanim virusom ptičje gripe", "J09.0"),
    J10("Influenca uzrokovana dokazanim virusom influence", "J10"),
    J10_0("Influenca s pneumonijom, virus influence dokazan,", "J10.0"),
    J10_1("Influenca s drugim respiracijskim znakovima, virus influence dokazan", "J10.1"),
    J10_8("Influenca s drugim manifestacijama, virus influence dokazan", "J10.8"),
    J11("Influenca, virus nije dokazan", "J11"),
    J11_0("Influenca s pneumonijom, virus nije dokazan", "J11.0"),
    J11_1("Influenca s drugim respiracijskim znakovima, virus nije dokazan", "J11.1"),
    J11_8("Influenca s drugim manifestacijama, virus nije dokazan", "J11.8"),
    J12("Virusna pneumonija, nesvrstana drugamo", "J12"),
    J12_0("Pneumonija uzrokovana adenovirusom", "J12.0"),
    J12_1("Pneumonija uzrokovana respiracijskim sincicijskim virusom", "J12.1"),
    J12_2("Pneumonija uzrokovana virusom parainfluence", "J12.2"),
    J12_8("Druga virusna pneumonija", "J12.8"),
    J12_9("Virusna pneumonija, nespecificirana", "J12.9"),
    J13("Pneumonija koju uzrokuje Streptococcus pneumoniae (Pneumococcus)", "J13"),
    J13_0("Pneumonija koju uzrokuje Streptococcus pneumoniae (Pneumococcus)", "J13.0"),
    J14("Pneumonija koju uzrokuje Haemophilus influenzae", "J14"),
    J14_0("Pneumonija koju uzrokuje Haemophilus influenzae", "J14.0"),
    J15("Bakterijska pneumonija, nesvrstana drugamo", "J15"),
    J15_0("Pneumonija koju uzrokuje Klebsiella pneumoniae", "J15.0"),
    J15_1("Pneumonija koju uzrokuje Pseudomonas", "J15.1"),
    J15_2("Pneumonija koju uzrokuje Staphylococcus", "J15.2"),
    J15_3("Pneumonija koju uzrokuje Streptococcus grupe B", "J15.3"),
    J15_4("Pneumonija uzrokovana drugim streptokokima", "J15.4"),
    J15_5("Pneumonija koju uzrokuje Escherichia coli", "J15.5"),
    J15_6("Pneumonija uzrokovana drugim aerobnim Gram-negativnim bakterijama", "J15.6"),
    J15_7("Pneumonija koju uzrokuje Mycoplasma pneumoniae", "J15.7"),
    J15_8("Druga bakterijska pneumonija", "J15.8"),
    J15_9("Bakterijska pneumonija, nespecificirana", "J15.9"),
    J16("Pneumonija uzrokovana drugim infektivnim uzročnicima, nesvrstana drugamo", "J16"),
    J16_0("Pneumonija uzrokovana klamidijama", "J16.0"),
    J16_8("Pneumonija uzrokovana drugim specificiranim infektivnim uzročnicima", "J16.8"),
    J17("Pneumonija u bolestima svrstanima drugamo", "J17"),
    J17_0("Pneumonija u bakterijskim bolestima svrstanima drugamo", "J17.0"),
    J17_1("Pneumonija u virusnim bolestima svrstanima drugamo", "J17.1"),
    J17_2("Pneumonija u mikozama", "J17.2"),
    J17_3("Pneumonija u parazitarnim bolestima", "J17.3"),
    J17_8("Pneumonija u drugim bolestima svrstanima drugamo", "J17.8"),
    J18("Pneumonija, nespecificiranog uzročnika", "J18"),
    J18_0("Bronhopneumonija, nespecificirana", "J18.0"),
    J18_1("Lobarna pneumonija, nespecificirana", "J18.1"),
    J18_2("Hipostatska pneumonija, nespecificirana", "J18.2"),
    J18_8("Druga pneumonija, nespecificiranog uzročnika", "J18.8"),
    J18_9("Pneumonija, nespecificirana", "J18.9"),
    J20("Akutni bronhitis", "J20"),
    J20_0("Akutni bronhitis kojeg uzrokuje Mycoplasma pneumoniae", "J20.0"),
    J20_1("Akutni bronhitis kojeg uzrokuje Haemophilus influenzae", "J20.1"),
    J20_2("Akutni bronhitis kojeg uzrokuje streptokok", "J20.2"),
    J20_3("Akutni bronhitis kojeg uzrokuje coxsackievirus", "J20.3"),
    J20_4("Akutni bronhitis kojeg uzrokuje virus parainfluence", "J20.4"),
    J20_5("Akutni bronhitis kojeg uzrokuje respiracijski sincicijski virus", "J20.5"),
    J20_6("Akutni bronhitis kojeg uzrokuje rinovirus", "J20.6"),
    J20_7("Akutni bronhitis kojeg uzrokuje ECHO-virus", "J20.7"),
    J20_8("Akutni bronhitis kojeg uzrokuje drugi specificirani uzročnik", "J20.8"),
    J20_9("Akutni bronhitis, nespecificiran", "J20.9"),
    J21("Akutni bronhiolitis", "J21"),
    J21_0("Akutni bronhiolitis uzrokovan respiracijskim sincicijskim virusom", "J21.0"),
    J21_8("Akutni bronhiolitis uzrokovan drugim specificiranim uzročnicima", "J21.8"),
    J21_9("Akutni bronhiolitis, nespecificiran", "J21.9"),
    J22("Nespecificirana akutna bolest donjega dišnog sustava", "J22"),
    J22_0("Nespecificirana akutna bolest donjega dišnog sustava", "J22.0"),
    J30("Vazomotorni i alergijski rinitis", "J30"),
    J30_0("Vazomotorni rinitis", "J30.0"),
    J30_1("Alergijski rinitis koji uzrokuje pelud (peludna groznica)", "J30.1"),
    J30_2("Drugi sezonski alergijski rinitis", "J30.2"),
    J30_3("Drugi alergijski rinitis", "J30.3"),
    J30_4("Alergijski rinitis, nespecificiran", "J30.4"),
    J31("Kronični rinitis, nazofaringitis i faringitis", "J31"),
    J31_0("Kronični rinitis", "J31.0"),
    J31_1("Kronični nazofaringitis", "J31.1"),
    J31_2("Kronični faringitis", "J31.2"),
    J32("Kronična upala sinusa (kronični sinusitis)", "J32"),
    J32_0("Kronični maksilarni sinusitis", "J32.0"),
    J32_1("Kronični frontalni sinusitis", "J32.1"),
    J32_2("Kronični etmoidni sinusitis", "J32.2"),
    J32_3("Kronični sfenoidni sinusitis", "J32.3"),
    J32_4("Kronični pansinusitis", "J32.4"),
    J32_8("Drugi kronični sinusitis", "J32.8"),
    J32_9("Kronični sinusitis, nespecificiran", "J32.9"),
    J33("Nazalni polip", "J33"),
    J33_0("Polip nosne šupljine", "J33.0"),
    J33_1("Polipoidna degeneracija sinusa", "J33.1"),
    J33_8("Drugi polip sinusa", "J33.8"),
    J33_9("Nazalni polip, nespecificiran", "J33.9"),
    J34("Druge bolesti nosa i nosnih sinusa", "J34"),
    J34_0("Apsces, furunkul i karbunkul nosa", "J34.0"),
    J34_1("Cista i mukokela nazalnog sinusa", "J34.1"),
    J34_2("Devijacija nazalnog septuma", "J34.2"),
    J34_3("Hipertrofija nosnih školjki", "J34.3"),
    J34_8("Druge specificirane bolesti nosa i nosnih sinusa", "J34.8"),
    J35("Kronične bolesti tonzila i adenoida", "J35"),
    J35_0("Kronična upala tonzila (kronični tonzilitis)", "J35.0"),
    J35_1("Hipertrofija tonzila", "J35.1"),
    J35_2("Hipertrofija adenoida", "J35.2"),
    J35_3("Hipertrofija tonzila s hipertrofijom adenoida", "J35.3"),
    J35_8("Druge kronične bolesti tonzila i adenoida", "J35.8"),
    J35_9("Kronične bolesti tonzila i adenoida, nespecificirane", "J35.9"),
    J36("Peritonzilarni apsces", "J36"),
    J36_0("Peritonzilarni apsces", "J36.0"),
    J37("Kronična upala grkljana i dušnika (kronični laringitis i laringotraheitis)", "J37"),
    J37_0("Kronični laringitis", "J37.0"),
    J37_1("Kronični laringotraheitis", "J37.1"),
    J38("Bolesti glasnica i grkljana, nesvrstane drugamo", "J38"),
    J38_0("Paraliza glasnica i grkljana", "J38.0"),
    J38_1("Polip glasnice i grkljana", "J38.1"),
    J38_2("Noduli glasnica", "J38.2"),
    J38_3("Druge bolesti glasnica", "J38.3"),
    J38_4("Edem grkljana", "J38.4"),
    J38_5("Spazam grkljana", "J38.5"),
    J38_6("Stenoza grkljana", "J38.6"),
    J38_7("Druge bolesti grkljana", "J38.7"),
    J39("Druge bolesti gornjega dišnog sustava", "J39"),
    J39_0("Retrofaringealni i parafaringealni apsces", "J39.0"),
    J39_1("Drugi apsces ždrijela", "J39.1"),
    J39_2("Druge bolesti ždrijela", "J39.2"),
    J39_3("Hipersenzitivna reakcija gornjega dišnog sustava, nespecificiranog mjesta", "J39.3"),
    J39_8("Druge specificirane bolesti gornjega dišnog sustava", "J39.8"),
    J39_9("Bolest gornjega dišnog sustava, nespecificirana", "J39.9"),
    J40("Bronhitis, nespecificiran kao akutni ili kronični", "J40"),
    J40_0("Bronhitis, nespecificiran kao akutni ili kronični", "J40.0"),
    J41("Obični i mukopurulentni kronični bronhitis", "J41"),
    J41_0("Obični kronični bronhitis", "J41.0"),
    J41_1("Mukopurulentni kronični bronhitis", "J41.1"),
    J41_8("Mješoviti obični i mukopurulentni kronični bronhitis", "J41.8"),
    J42("Nespecificirani kronični bronhitis", "J42"),
    J42_0("Nespecificirani kronični bronhitis", "J42.0"),
    J43("Emfizem", "J43"),
    J43_0("MacLeodov sindrom", "J43.0"),
    J43_1("Panlobularni emfizem", "J43.1"),
    J43_2("Centrilobularni emfizem", "J43.2"),
    J43_8("Drugi emfizem", "J43.8"),
    J43_9("Emfizem, nespecificiran", "J43.9"),
    J44("Druga kronična opstruktivna plućna bolest", "J44"),
    J44_0("Kronična opstruktivna plućna bolest s akutnom infekcijom donjega dišnog sustava", "J44.0"),
    J44_1("Kronična opstruktivna plućna bolest s akutnom egzarcerbacijom, nespecificirana", "J44.1"),
    J44_8("Druga specificirana kronična opstruktivna plućna bolest", "J44.8"),
    J44_9("Kronična opstruktivna plućna bolest, nespecificirana", "J44.9"),
    J45("Astma", "J45"),
    J45_0("Pretežno alergijska astma", "J45.0"),
    J45_1("Nealergijska astma", "J45.1"),
    J45_8("Mješovita astma", "J45.8"),
    J45_9("Astma, nespecificirana", "J45.9"),
    J46("Astmatični status (status astmathicus)", "J46"),
    J46_0("Astmatični status (status asthmaticus)", "J46.0"),
    J47("Bronhiektazije", "J47"),
    J47_0("Bronhiektazije", "J47.0"),
    J60("Pneumokonioza kopača ugljena", "J60"),
    J60_0("Pneumokonioza kopača ugljena", "J60.0"),
    J61("Pneumokonioza uzrokovana azbestom i drugim mineralnim vlaknima", "J61"),
    J61_0("Pneumokonioza uzrokovana azbestom i drugim mineralnim vlaknima", "J61.0"),
    J62("Pneumokonioza uzrokovana prašinom koja sadrži silikate", "J62"),
    J62_0("Pneumokonioza uzrokovana talkom", "J62.0"),
    J62_8("Pneumokonioza uzrokovana drugom prašinom koja sadrži silikate", "J62.8"),
    J63("Pneumokonioza uzrokovana drugim anorganskim prašinama", "J63"),
    J63_0("Aluminoza (pluća)", "J63.0"),
    J63_1("Fibroza (pluća) uzrokovana boksitom", "J63.1"),
    J63_2("Berilioza", "J63.2"),
    J63_3("Fibroza (pluća) uzrokovana grafitom", "J63.3"),
    J63_4("Sideroza", "J63.4"),
    J63_5("Stanoza", "J63.5"),
    J63_8("Pneumokonioza uzrokovana drugim specificiranim anorganskim prašinama", "J63.8"),
    J64("Pneumokonioza, nespecificirana", "J64"),
    J64_0("Pneumokonioza, nespecificirana", "J64.0"),
    J65("Pneumokonioza povezana s tuberkulozom", "J65"),
    J65_0("Pneumokonioza povezana s tuberkulozom, nespecificirana", "J65.0"),
    J66("Bolest dišnih putova uzrokovana specificiranom organskom prašinom", "J66"),
    J66_0("Bisinoza", "J66.0"),
    J66_1("Bolest prerađivača lana", "J66.1"),
    J66_2("Kanabinoza", "J66.2"),
    J66_8("Bolest dišnih putova uzrokovana drugim specificiranim organskim prašinama", "J66.8"),
    J67("Hipersenzitivni pneumonitis uzrokovan organskom prašinom", "J67"),
    J67_0("Farmerska pluća", "J67.0"),
    J67_1("Bagasoza", "J67.1"),
    J67_2("Pluća uzgajatelja ptica", "J67.2"),
    J67_3("Suberoza", "J67.3"),
    J67_4("Pluća proizvođača slada", "J67.4"),
    J67_5("Pluća uzgajatelja gljiva", "J67.5"),
    J67_6("Pluća strugača javorove kore", "J67.6"),
    J67_7("Pluća izloženih kondicioniranome zraku i ovlaživačima", "J67.7"),
    J67_8("Hipersenzitivni pneumonitis uzrokovan drugim organskim prašinama", "J67.8"),
    J67_9("Hipersenzitivni pneumonitis uzrokovana nespecificiranom organskom prašinom", "J67.9"),
    J68("Respiracijska stanja uzrokovana udisanjem kemikalija, plinova, dimova i para", "J68"),
    J68_0("Bronhitis i pneumonitis uzrokovan kemikalijama, plinovima, dimovima i parama", "J68.0"),
    J68_1("Akutni plućni edem uzrokovan kemikalijama, plinovima, dimovima i parama", "J68.1"),
    J68_2("Upala gornjega dišnog sustava uzrokovana kemikalijama, plinovima, dimovima i parama, nesvrstana drugamo", "J68.2"),
    J68_3("Druga akutna i subakutna stanja dišnog sustava uzrokovana kemikalijama, plinovima, dimovima i parama", "J68.3"),
    J68_4("Kronična stanja dišnog sustava uzrokovana kemikalijama, plinovima, dimovima i parama", "J68.4"),
    J68_8("Druga stanja dišnog sustava uzrokovana kemikalijama, plinovima, dimovima i parama", "J68.8"),
    J68_9("Nespecificirano stanje dišnog sustava uzrokovano kemikalijama, plinovima, dimovima i parama", "J68.9"),
    J69("Pneumonitis uzrokovan krutim tvarima i tekućinama", "J69"),
    J69_0("Pneumonitis uzrokovan hranom i povraćenim sadržajem", "J69.0"),
    J69_1("Pneumonitis uzrokovan uljima i esencijama", "J69.1"),
    J69_8("Pneumonitis uzrokovan drugim krutim tvarima i tekućinama", "J69.8"),
    J70("Respiracijska stanja uzrokovana drugim vanjskim uzrocima", "J70"),
    J70_0("Akutne plućne manifestacije uzrokovane zračenjem", "J70.0"),
    J70_1("Kronične i druge plućne manifestacije uzrokovane radijacijom", "J70.1"),
    J70_2("Akutni poremećaj plućnog intersticija uzrokovan lijekom", "J70.2"),
    J70_3("Kronični poremećaj plućnog intersticija uzrokovan lijekom", "J70.3"),
    J70_4("Poremećaj plućnog intersticija uzrokovan lijekom, nespecificirani", "J70.4"),
    J70_8("Respiracijska stanja uzrokovana drugim specificiranim vanjskim uzrocima (agensima)", "J70.8"),
    J70_9("Respiracijska stanja uzrokovana nespecificiranim vanjskim uzrocima (agensima)", "J70.9"),
    J80("Sindrom dišnog distresa u odraslih", "J80"),
    J80_0("Sindrom dišnog distresa u odraslih", "J80.0"),
    J81("Plućni edem", "J81"),
    J81_0("Plućni edem", "J81.0"),
    J82("Plućna eozinofilija, nesvrstana drugamo", "J82"),
    J82_0("Plućna eozinofilija, nesvrstana drugamo", "J82.0"),
    J84("Druge intersticijske plućne bolesti", "J84"),
    J84_0("Alveolarni i parietoalveolarni poremećaji", "J84.0"),
    J84_1("Druge intersticijske plućne bolesti s fibrozom", "J84.1"),
    J84_8("Druge specificirane intersticijske plućne bolesti", "J84.8"),
    J84_9("Intersticijska plućna bolest, nespecificirana", "J84.9"),
    J85("Apsces pluća i sredoprsja (medijastinuma)", "J85"),
    J85_0("Gangrena i nekroza pluća", "J85.0"),
    J85_1("Plućni apsces s pneumonijom", "J85.1"),
    J85_2("Plućni apsces bez pneumonije", "J85.2"),
    J85_3("Apsces medijastinuma", "J85.3"),
    J86("Piotoraks", "J86"),
    J86_0("Piotoraks s fistulom", "J86.0"),
    J86_9("Piotoraks bez fistule", "J86.9"),
    J90("Pleuralni izljev, nesvrstan drugamo", "J90"),
    J90_0("Pleuralni izljev, nesvrstan drugamo", "J90.0"),
    J91("Pleuralni izljev u stanjima svrstanim drugamo", "J91"),
    J91_0("Pleuralni izljev u stanjima svrstanim drugamo", "J91.0"),
    J92("Pleuralni plak", "J92"),
    J92_0("Pleuralni plak uz azbestozu", "J92.0"),
    J92_9("Pleuralni plak bez azbestoze", "J92.9"),
    J93("Pneumotoraks", "J93"),
    J93_0("Spontani tenzijski pneumotoraks", "J93.0"),
    J93_1("Drugi spontani pneumotoraks", "J93.1"),
    J93_8("Ostali pneumotoraks", "J93.8"),
    J93_9("Pneumotoraks, nespecificiran", "J93.9"),
    J94("Druga pleuralna stanja", "J94"),
    J94_0("Hilozni izljev", "J94.0"),
    J94_1("Fibrotoraks", "J94.1"),
    J94_2("Hematotoraks", "J94.2"),
    J94_8("Druga specificirana stanja pleure", "J94.8"),
    J94_9("Stanje pleure, nespecificirano", "J94.9"),
    J95("Respiracijska oštećenja kao posljedica medicinskog postupka, nesvrstana drugamo", "J95"),
    J95_0("Poremećaj funkcije traheostome", "J95.0"),
    J95_1("Akutna plućna insuficijencija nakon torakalnoga kirurškog zahvata", "J95.1"),
    J95_2("Akutna plućna insuficijencija nakon netorakalnog kirurškog zahvata", "J95.2"),
    J95_3("Kronična plućna insuficijencija nakon kirurškog zahvata", "J95.3"),
    J95_4("Mendelsonov sindrom", "J95.4"),
    J95_5("Subglotična stenoza kao posljedica medicinskog postupka", "J95.5"),
    J95_8("Drugi respiracijski poremećaji kao posljedice medicinskog postupka", "J95.8"),
    J95_9("Respiracijski poremećaj nastao kao posljedica medicinskog postupka, nespecificiran", "J95.9"),
    J96("Respiracijska insuficijencija nesvrstana drugamo", "J96"),
    J96_0("Akutna respiracijska insuficijencija", "J96.0"),
    J96_1("Kronična respiracijska insuficijencija", "J96.1"),
    J96_9("Respiracijska insuficijencija, nespecificirana", "J96.9"),
    J98("Drugi respiracijski poremećaji", "J98"),
    J98_0("Bolesti bronha svrstane drugamo", "J98.0"),
    J98_1("Kolaps pluća", "J98.1"),
    J98_2("Intersticijski emfizem", "J98.2"),
    J98_3("Kompenzacijski emfizem", "J98.3"),
    J98_4("Drugi plućni poremećaji", "J98.4"),
    J98_5("Bolest sredoprsja (medijastinuma), nesvrstana drugamo", "J98.5"),
    J98_6("Poremećaji ošita (dijafragme)", "J98.6"),
    J98_8("Drugi specificirani respiracijski poremećaji", "J98.8"),
    J98_9("Respiracijski poremećaj, nespecificiran", "J98.9"),
    J99("Respiracijski poremećaji u bolestima svrstanima drugamo", "J99"),
    J99_0("Reumatoidna bolest pluća (M05.1)", "J99.0"),
    J99_1("Respiracijski poremećaji u drugim difuznim bolestima vezivnog tkiva", "J99.1"),
    J99_8("Respiracijski poremećaji u drugim bolestima svrstanima drugamo", "J99.8");
    
    private final String displayName;
    private final String code;
    
    MkbCodesJ(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
