package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesH {
    
    H00("Hordeolum i halacion", "H00"),
    H00_0("Hordeolum i druge duboke upale vjeđe", "H00.0"),
    H00_1("Halacion", "H00.1"),
    H01("Ostale upale vjeđe", "H01"),
    H01_0("Blefaritis", "H01.0"),
    H01_1("Neinfektivne vjeđne dermatoze", "H01.1"),
    H01_8("Ostale specificirane upale vjeđe", "H01.8"),
    H01_9("Upala vjeđe, nespecificirana", "H01.9"),
    H02("Drugi poremećaji vjeđe", "H02"),
    H02_0("Entropij i trihijaza vjeđe", "H02.0"),
    H02_1("Ektropij vjeđe", "H02.1"),
    H02_2("Lagoftalmus", "H02.2"),
    H02_3("Blefarohalaza", "H02.3"),
    H02_4("Ptoza vjeđe", "H02.4"),
    H02_5("Drugi poremećaji koji zahvaćaju funkciju vjeđe", "H02.5"),
    H02_6("Ksantelazma vjeđe", "H02.6"),
    H02_7("Drugi degenerativni poremećaji vjeđe i periokularnog područja", "H02.7"),
    H02_8("Ostali specificirani poremećaji vjeđe", "H02.8"),
    H02_9("Poremećaj vjeđe, nespecificiran", "H02.9"),
    H03("Poremećaji vjeđe u bolestima svrstanim drugamo", "H03"),
    H03_0("Parazitarne infestacije vjeđe u bolestima svrstanim drugamo", "H03.0"),
    H03_1("Promjene vjeđe u drugim zaraznim bolestima svrstanim drugamo", "H03.1"),
    H03_8("Promjene vjeđe u ostalim bolestima svrstanim drugamo", "H03.8"),
    H04("Bolesti suznog aparata", "H04"),
    H04_0("Dakrioadenitis", "H04.0"),
    H04_1("Druge bolesti suzne žlijezde", "H04.1"),
    H04_2("Epifora", "H04.2"),
    H04_3("Akutna i nespecificirana upala suznih kanala", "H04.3"),
    H04_4("Kronična upala suznih kanala", "H04.4"),
    H04_5("Stenoza i insuficijencija suznih putova", "H04.5"),
    H04_6("Drugi poremećaji suznih kanala", "H04.6"),
    H04_8("Ostali poremećaji suznog aparata", "H04.8"),
    H04_9("Poremećaj suznog aparata, nespecificiran", "H04.9"),
    H05("Bolesti očne šupljine", "H05"),
    H05_0("Akutna upala očne šupljine", "H05.0"),
    H05_1("Kronične upale očne šupljine", "H05.1"),
    H05_2("Egzoftalmus", "H05.2"),
    H05_3("Deformacija očne šupljine", "H05.3"),
    H05_4("Enoftalmus", "H05.4"),
    H05_5("Zaostalo (staro) strano tijelo nakon penetrirajuće ozljede očne šupljine", "H05.5"),
    H05_8("Ostale bolesti očne šupljine", "H05.8"),
    H05_9("Poremećaj očne šupljine, nespecificiran", "H05.9"),
    H06("Poremećaji suznog aparata i očne šupljine u bolestima svrstanim drugamo", "H06"),
    H06_0("Poremećaji suznog aparata u bolestima svrstanim drugamo", "H06.0"),
    H06_1("Parazitarne infestacije očne šupljine u bolestima svrstanim drugamo", "H06.1"),
    H06_2("Endokrini egzoftalmus (E05.-)", "H06.2"),
    H06_3("Ostali poremećaji očne šupljine u bolestima svrstanim drugamo", "H06.3"),
    H10("Konjunktivitis", "H10"),
    H10_0("Mukopurulentni konjunktivitis", "H10.0"),
    H10_1("Akutni atopični konjunktivitis", "H10.1"),
    H10_2("Drugi akutni konjunktivitisi", "H10.2"),
    H10_3("Akutni konjunktivitis, nespecificiran", "H10.3"),
    H10_4("Kronični konjunktivitis", "H10.4"),
    H10_5("Blefarokonjunktivitis", "H10.5"),
    H10_8("Ostali konjunktivitisi", "H10.8"),
    H10_9("Konjunktivitis, nespecificiran", "H10.9"),
    H11("Ostale bolesti spojnice", "H11"),
    H11_0("Pterigij", "H11.0"),
    H11_1("Degenerativne promjene i talozi spojnice", "H11.1"),
    H11_2("Ožiljne promjene spojnice", "H11.2"),
    H11_3("Krvarenje spojnice", "H11.3"),
    H11_4("Drugi vaskularni poremećaji i ciste spojnice", "H11.4"),
    H11_8("Ostale specificirane bolesti spojnice", "H11.8"),
    H11_9("Bolest spojnice, nespecificirana", "H11.9"),
    H13("Poremećaji spojnice u bolestima svrstanim drugamo", "H13"),
    H13_0("Infestacija spojnice uzrokovana filarijama (B74.-)", "H13.0"),
    H13_1("Konjunktivitis u zaraznim i parazitarnim bolestima svrstanim drugamo", "H13.1"),
    H13_2("Konjunktivitis u ostalim bolestima svrstanim drugamo", "H13.2"),
    H13_3("Konjunktivalni pemfigoid (L12.-)", "H13.3"),
    H13_8("Ostali poremećaji spojnice u bolestima svrstanim drugamo", "H13.8"),
    H15("Bolesti bjeloočnice", "H15"),
    H15_0("Skleritis", "H15.0"),
    H15_1("Episkleritis", "H15.1"),
    H15_8("Drugi poremećaji bjeloočnice", "H15.8"),
    H15_9("Bolest bjeloočnice, nespecificirana", "H15.9"),
    H16("Keratitis", "H16"),
    H16_0("Rožnični ulkus", "H16.0"),
    H16_1("Drugi superficijalni keratitisi bez konjunktivitisa", "H16.1"),
    H16_2("Keratokonjunktivitis", "H16.2"),
    H16_3("Intersticijalni i duboki keratitis", "H16.3"),
    H16_4("Neovaskularizacija rožnice", "H16.4"),
    H16_8("Drugi keratitisi", "H16.8"),
    H16_9("Keratitis, nespecificiran", "H16.9"),
    H17("Ožiljci i zamućenja rožnice", "H17"),
    H17_0("Adherentni leukom", "H17.0"),
    H17_1("Druga središnja zamućenja rožnice", "H17.1"),
    H17_8("Drugi ožiljci i zamućenja rožnice", "H17.8"),
    H17_9("Ožiljak i zamućenje rožnice, nespecificiran", "H17.9"),
    H18("Ostali poremećaji rožnice", "H18"),
    H18_0("Pigmentacije i talozi rožnice", "H18.0"),
    H18_1("Bulozna keratopatija", "H18.1"),
    H18_2("Drugi rožnični edemi", "H18.2"),
    H18_3("Promjene na membranama rožnice", "H18.3"),
    H18_4("Degenerativne promjene rožnice", "H18.4"),
    H18_5("Prirođene distrofije rožnice", "H18.5"),
    H18_6("Keratokonus", "H18.6"),
    H18_7("Druge deformacije rožnice", "H18.7"),
    H18_8("Ostali specificirani poremećaji rožnice", "H18.8"),
    H18_9("Poremećaj rožnice, nespecificiran", "H18.9"),
    H19("Poremećaji bjeloočnice i rožnice u bolestima svrstanim drugamo", "H19"),
    H19_0("Skleritis i episkleritis u bolestima svrstanim drugamo", "H19.0"),
    H19_1("Herpesvirusni keratitis i keratokonjunktivitis (B00.5)", "H19.1"),
    H19_2("Keratitis i keratokonjunktivitis u ostalim zaraznim i parazitarnim bolestima svrstanim drugamo", "H19.2"),
    H19_3("Keratitis i keratokonjunktivitis u ostalim bolestima svrstanim drugamo", "H19.3"),
    H19_8("Ostali poremećaji bjeloočnice i rožnice u bolestima svrstanim drugamo", "H19.8"),
    H20("Iridociklitis", "H20"),
    H20_0("Akutni i subakutni iridociklitis", "H20.0"),
    H20_1("Kronični iridociklitis", "H20.1"),
    H20_2("Fakogeni iridociklitis", "H20.2"),
    H20_8("Drugi iridociklitisi", "H20.8"),
    H20_9("Iridociklitis, nespcificiran", "H20.9"),
    H21("Ostale bolesti šarenice i zrakastog tijela", "H21"),
    H21_0("Hifema", "H21.0"),
    H21_1("Drugi vaskularni poremećaji šarenice i zrakastog tijela", "H21.1"),
    H21_2("Degenerativne promjene šarenice i zrakastog tijela", "H21.2"),
    H21_3("Cista šarenice, zrakastog tijela i prednje sobice", "H21.3"),
    H21_4("Zjenične membrane", "H21.4"),
    H21_5("Druge priraslice (sinehija) i rascjepi šarenice i zrakastog tijela", "H21.5"),
    H21_8("Ostali specificirani poremećaji šarenice i zrakastog tijela", "H21.8"),
    H21_9("Poremećaj šarenice i zrakastog tijela, nespecificiran", "H21.9"),
    H22("Poremećaji šarenice i zrakastog tijela u bolestima svrstanim drugamo", "H22"),
    H22_0("Iridociklitis u zaraznim i parazitarnim bolestima svrstanim drugamo", "H22.0"),
    H22_1("Iridociklitis u drugim bolestima svrstanim drugamo", "H22.1"),
    H22_8("Ostali poremećaji šarenice i zrakastog tijela u bolestima svrstanim drugamo", "H22.8"),
    H25("Senilna katarakta", "H25"),
    H25_0("Početna senilna katarakta", "H25.0"),
    H25_1("Senilna nuklearna katarakta", "H25.1"),
    H25_2("Morgagnijeva senilna katarakta", "H25.2"),
    H25_8("Ostale senilne katarakte", "H25.8"),
    H25_9("Senilna katarakta, nespecificirana", "H25.9"),
    H26("Druge katarakte", "H26"),
    H26_0("Infantilna, juvenilna i presenilna katarakta", "H26.0"),
    H26_1("Traumatska katarakta", "H26.1"),
    H26_2("Katarakta komplikata", "H26.2"),
    H26_3("Katarakta kao posljedica djelovanja lijekova", "H26.3"),
    H26_4("Stanje nakon (operacije) katarakte", "H26.4"),
    H26_8("Ostale specificirane katarakte", "H26.8"),
    H26_9("Katarakta, nespecificirana", "H26.9"),
    H27("Ostali poremećaji leće", "H27"),
    H27_0("Afakija", "H27.0"),
    H27_1("Dislokacija leće", "H27.1"),
    H27_8("Ostali specificirani poremećaji leće", "H27.8"),
    H27_9("Poremećaj leće, nespecificiran", "H27.9"),
    H28("Katarakta i ostali poremećaji leće u bolestima svrstanim drugamo", "H28"),
    H28_0("Dijabetička katarakta", "H28.0"),
    H28_1("Katarakta u drugim endokrinim bolestima, bolestima prehrane i bolestima metabolizma", "H28.1"),
    H28_2("Katarakta u drugim bolestima svrstanim drugamo", "H28.2"),
    H28_8("Ostali poremećaji leće u bolestima svrstanim drugamo", "H28.8"),
    H30("Korioretinalna upala", "H30"),
    H30_0("Fokalna korioretinalna upala", "H30.0"),
    H30_1("Diseminarna korioretinalna upala", "H30.1"),
    H30_2("Posteriorni ciklitis", "H30.2"),
    H30_8("Ostale korioretinalne upale", "H30.8"),
    H30_9("Korioretinalna upala, nespecificirana", "H30.9"),
    H31("Ostali poremećaji žilnice", "H31"),
    H31_0("Korioretinalni ožiljci", "H31.0"),
    H31_1("Degenerativne promjene žilnice", "H31.1"),
    H31_2("Nasljedne distrofije žilnice", "H31.2"),
    H31_3("Krvarenje i ruptura žilnice", "H31.3"),
    H31_4("Ablacija žilnice", "H31.4"),
    H31_8("Ostali specificirani poremećaji žilnice", "H31.8"),
    H31_9("Poremećaj žilnice, nespecificiran", "H31.9"),
    H32("Korioretinalni poremećaji u bolestima svrstanim drugamo", "H32"),
    H32_0("Korioretinitisi u zaraznim i parazitarnim bolestima svrstanim drugamo", "H32.0"),
    H32_8("Ostali korioretinalni poremećaji u bolestima svrstanim drugamo", "H32.8"),
    H33("Ablacije i rupture mrežnice", "H33"),
    H33_0("Ablacija mrežnice s rupturom", "H33.0"),
    H33_1("Retinoshiza i mrežnične ciste", "H33.1"),
    H33_2("Serozna ablacija mrežnice", "H33.2"),
    H33_3("Rupture mrežnice bez ablacije", "H33.3"),
    H33_4("Trakcijska ablacija mrežnice", "H33.4"),
    H33_5("Druge ablacije mrežnice", "H33.5"),
    H34("Retinalne vaskularne okluzije", "H34"),
    H34_0("Prolazna okluzija mrežnične arterije", "H34.0"),
    H34_1("Okluzija središnje mrežnične arterije", "H34.1"),
    H34_2("Ostale okluzije mrežnične arterije", "H34.2"),
    H34_8("Druge mrežnične vaskularne okluzije", "H34.8"),
    H34_9("Mrežnična vaskularna okluzija, nespecificirana", "H34.9"),
    H35("Ostali mrežnični poremećaji", "H35"),
    H35_0("Neproliferativna retinopatija i mrežnične vaskularne promjene", "H35.0"),
    H35_1("Prematurna retinopatija", "H35.1"),
    H35_2("Druge proliferativne retinopatije", "H35.2"),
    H35_3("Degeneracija makule i stražnjeg pola", "H35.3"),
    H35_4("Periferna mrežnična degeneracija", "H35.4"),
    H35_5("Nasljedna mrežnična distrofija", "H35.5"),
    H35_6("Krvarenje mrežnice", "H35.6"),
    H35_7("Odvajanje mrežničnih slojeva", "H35.7"),
    H35_8("Ostali specificirani poremećaji mrežnice", "H35.8"),
    H35_9("Poremećaj mrežnice, nespecificiran", "H35.9"),
    H36("Mrežnični poremećaji u bolestima svrstanim drugamo", "H36"),
    H36_0("Dijabetička retinopatija", "H36.0"),
    H36_8("Ostali mrežnični poremećaji u bolestima svrstanim drugamo", "H36.8"),
    H40("Glaukom", "H40"),
    H40_0("Suspektni glaukom", "H40.0"),
    H40_1("Primarni glaukom s otvorenim sobičnim kutom", "H40.1"),
    H40_2("Primarni glaukom sa zatvoreim sobičnim kutom", "H40.2"),
    H40_3("Sekundarni glaukom kao posljedica ozljede oka", "H40.3"),
    H40_4("Sekundarni glaukom kao posljedica upale oka", "H40.4"),
    H40_5("Sekundarni glaukom kao posljedica drugih poremećaja oka", "H40.5"),
    H40_6("Sekundarni glaukom kao posljedica djelovanja lijekova", "H40.6"),
    H40_8("Drugi glaukomi", "H40.8"),
    H40_9("Glaukom, nespecificiran", "H40.9"),
    H42("Glaukom u bolestima svrstanim drugamo", "H42"),
    H42_0("Glaukom u endokrinim bolestima, bolestima prehrane i metaboličkim bolestima", "H42.0"),
    H42_8("Glaukom u ostalim bolestima svrstanim drugamo", "H42.8"),
    H43("Poremećaji staklastog tijela", "H43"),
    H43_0("Prolaps staklastog tijela", "H43.0"),
    H43_1("Vitrealno krvarenje", "H43.1"),
    H43_2("Talozi kristala u staklastom tijelu", "H43.2"),
    H43_3("Druga zamućenja staklastog tijela", "H43.3"),
    H43_8("Ostali poremećaji staklastog tijela", "H43.8"),
    H43_9("Poremećaj staklastog tijela, nespecificiran", "H43.9"),
    H44("Poremećaji očne jabučice", "H44"),
    H44_0("Gnojni endoftalmitis", "H44.0"),
    H44_1("Drugi endoftalmitisi", "H44.1"),
    H44_2("Degenerativna miopija", "H44.2"),
    H44_3("Drugi degenerativni poremećaji očne jabučice", "H44.3"),
    H44_4("Hipotonija oka", "H44.4"),
    H44_5("Degenerativna stanja očne jabučice", "H44.5"),
    H44_6("Zaostalo (staro) intraokularno strano tijelo, magnetsko", "H44.6"),
    H44_7("Zaostalo (staro) intraokularno strano tijelo, nemagnetsko", "H44.7"),
    H44_8("Ostali poremećaji očne jabučice", "H44.8"),
    H44_9("Poremećaj očne jabučice, nespecificiran", "H44.9"),
    H45("Poremećaji staklastog tijela i očne jabučice u bolestima svrstanim drugamo", "H45"),
    H45_0("Krvarenje staklastog tijela u bolestima svrstanim drugamo", "H45.0"),
    H45_1("Endoftalmitis u bolestima svrstanim drugamo", "H45.1"),
    H45_8("Ostali poremećaji staklastog tijela i očne jabučice u bolestima svrstanim drugamo", "H45.8"),
    H46("Optički neuritis", "H46"),
    H46_0("Optički neuritis", "H46.0"),
    H47("Ostale bolesti vidnog živca i vidnih putova", "H47"),
    H47_0("Poremećaji vidnog živca nesvrstani drugamo", "H47.0"),
    H47_1("Edem papile, nespecificiran", "H47.1"),
    H47_2("Atrofija vidnog živca", "H47.2"),
    H47_3("Druge bolesti papile vidnog živca", "H47.3"),
    H47_4("Bolesti kijazme vidnog živca", "H47.4"),
    H47_5("Bolesti drugih vidnih putova", "H47.5"),
    H47_6("Bolesti vidnog korteksa", "H47.6"),
    H47_7("Poremećaj vidnih putova, nespecificiran", "H47.7"),
    H48("Poremećaji vidnog živca i vidnih putova u bolestima svrstanim drugamo", "H48"),
    H48_0("Atrofija vidnog živca u bolestima svrstanim drugamo", "H48.0"),
    H48_1("Retrobulbarni neuritis u bolestima svrstanim drugamo", "H48.1"),
    H48_8("Ostali poremećaji vidnog živca i vidnih putova u bolestima svrstanim drugamo", "H48.8"),
    H49("Paralitički strabizam", "H49"),
    H49_0("Kljenut trećega moždanog živca (okulomotorijusa)", "H49.0"),
    H49_1("Kljenut četvrtoga moždanog živca (trohlearisa)", "H49.1"),
    H49_2("Kljenut šestoga moždanog živca (abducensa)", "H49.2"),
    H49_3("Totalna oftalmoplegija vanjskih očnih mišića", "H49.3"),
    H49_4("Progresivna vanjska oftalmoplegija", "H49.4"),
    H49_8("Ostali paralitički strabizmi", "H49.8"),
    H49_9("Paralitički strabizam, nespecificiran", "H49.9"),
    H50("Ostali strabizmi", "H50"),
    H50_0("Konvergentni konkomitantni strabizam", "H50.0"),
    H50_1("Divergentni konkomitantni strabizam", "H50.1"),
    H50_2("Vertikalni strabizam", "H50.2"),
    H50_3("Intermitentna heterotropija", "H50.3"),
    H50_4("Druge i nespecificirane heterotropije", "H50.4"),
    H50_5("Heteroforija", "H50.5"),
    H50_6("Mehanički strabizam", "H50.6"),
    H50_8("Ostali specificirani strabizmi", "H50.8"),
    H50_9("Strabizam, nespecificiran", "H50.9"),
    H51("Ostali poremećaji binokularnog vida", "H51"),
    H51_0("Kljenut konjugiranih očnih pokreta", "H51.0"),
    H51_1("Insuficijencija i eksces konvergencije", "H51.1"),
    H51_2("Internuklearna oftalmoplegija", "H51.2"),
    H51_8("Ostali specificirani poremećaji binokularnog vida", "H51.8"),
    H51_9("Poremećaj binokularnog vida, nespecificiran", "H51.9"),
    H52("Poremećaji refrakcije i akomodacije", "H52"),
    H52_0("Hipermetropija", "H52.0"),
    H52_1("Miopija", "H52.1"),
    H52_2("Astigmatizam", "H52.2"),
    H52_3("Anizometropija i anizeikonija", "H52.3"),
    H52_4("Prezbiopija", "H52.4"),
    H52_5("Poremećaji akomodacije", "H52.5"),
    H52_6("Drugi poremećaji refrakcije", "H52.6"),
    H52_7("Poremećaj refrakcije, nespecificiran", "H52.7"),
    H53("Vidni poremećaji", "H53"),
    H53_0("Ambliopija zbog anopsije", "H53.0"),
    H53_1("Subjektivni vidni poremećaji", "H53.1"),
    H53_2("Diplopija", "H53.2"),
    H53_3("Drugi poremećaji binokularnog vida", "H53.3"),
    H53_4("Defekti vidnog polja", "H53.4"),
    H53_5("Poremećaji osjeta za boje", "H53.5"),
    H53_6("Noćna sljepoća", "H53.6"),
    H53_8("Drugi vidni poremećaji", "H53.8"),
    H53_9("Vidni poremećaj, nespecificiran", "H53.9"),
    H54("Sljepoća i slabovidnost", "H54"),
    H54_0("Sljepoća na oba oka", "H54.0"),
    H54_1("Sljepoća jednog oka, slabovidnost drugog oka", "H54.1"),
    H54_2("Slabovidnost na oba oka", "H54.2"),
    H54_3("Nesvrstan gubitak vida na oba oka", "H54.3"),
    H54_4("Sljepoća jednog oka", "H54.4"),
    H54_5("Slabovidnost jednog oka", "H54.5"),
    H54_6("Nesvrstan gubitak vida jednog oka", "H54.6"),
    H54_7("Nespecificiran gubitak vida", "H54.7"),
    H55("Nistagmus i drugi iregularni očni pokreti", "H55"),
    H55_0("Patološki nistagmus i drugi iregularni očni pokreti", "H55.0"),
    H57("Ostali poremećaji oka i očnih adneksa", "H57"),
    H57_0("Anomalije zjenične funkcije", "H57.0"),
    H57_1("Bol u oku", "H57.1"),
    H57_8("Ostali specificirani poremećaji oka i očnih adneksa", "H57.8"),
    H57_9("Poremećaj oka i očnih adneksa, nespecificiran", "H57.9"),
    H58("Ostali poremećaji oka i očnih adneksa u bolestima svrstanim drugamo", "H58"),
    H58_0("Anomalije zjenične funkcije u bolestima svrstanim drugamo", "H58.0"),
    H58_1("Vidni poremećaji u bolestima svrstanim drugamo", "H58.1"),
    H58_8("Ostali specificirani poremećaji oka i očnih adneksa u bolestima svrstanim drugamo", "H58.8"),
    H59("Poremećaji oka i očnih adneksa nakon zahvata i postupaka nesvrstanih drugamo", "H59"),
    H59_0("Sindrom staklastog tijela nakon operacije katarakte", "H59.0"),
    H59_8("Ostali poremećaji oka i očnih adneksa nakon zahvata", "H59.8"),
    H59_9("Poremećaj oka i očnih adneksa nakon zahvata, nespecificiran", "H59.9"),
    H60("Upala vanjskog uha", "H60"),
    H60_0("Apsces vanjskog uha", "H60.0"),
    H60_1("Celulitis vanjskog uha", "H60.1"),
    H60_2("Otitis externa maligna", "H60.2"),
    H60_3("Ostale infektivne upale vanjskog uha", "H60.3"),
    H60_4("Kolesteatom vanjskog uha", "H60.4"),
    H60_5("Akutna upala vanjskog uha, neinfektivna", "H60.5"),
    H60_8("Druga upala vanjskog uha", "H60.8"),
    H60_9("Upala vanjskog uha, nespecificirana", "H60.9"),
    H61("Druge bolesti vanjskog uha", "H61"),
    H61_0("Perihondritis vanjskog uha", "H61.0"),
    H61_1("Neinfektivni poremećaji pine", "H61.1"),
    H61_2("Opturirajući cerumen", "H61.2"),
    H61_3("Stečena stenoza zvukovoda", "H61.3"),
    H61_8("Drugi specificirani poremećaji vanjskog uha", "H61.8"),
    H61_9("Poremećaj vanjskog uha, nespecificiran", "H61.9"),
    H62("Bolesti vanjskog uha u bolestima svrstanim drugamo", "H62"),
    H62_0("Upala vanjskog uha u bakterijskim bolestima svrstanim drugamo", "H62.0"),
    H62_1("Upala vanjskog uha u virusnim bolestima svrstanim drugamo", "H62.1"),
    H62_2("Upala vanjskog uha kod mikoza", "H62.2"),
    H62_3("Upala vanjskog uha u drugim infektivnim i parazitarnim bolestima svrstanim drugamo", "H62.3"),
    H62_4("Upala vanjskog uha u drugim bolestima svrstanim drugamo", "H62.4"),
    H62_8("Drugi poremećaji vanjskog uha u bolestima svrstanim drugamo", "H62.8"),
    H65("Nesupurativna upala srednjeg uha", "H65"),
    H65_0("Akutna serozna upala srednjeg uha", "H65.0"),
    H65_1("Druga akutna nesupurativna upala srednjeg uha", "H65.1"),
    H65_2("Kronična serozna upala srednjeg uha", "H65.2"),
    H65_3("Kronična mukoidna upala srednjeg uha", "H65.3"),
    H65_4("Ostala kronična nesupurativna upala srednjeg uha", "H65.4"),
    H65_9("Nesupurativna upala srednjeg uha, nespecificirana", "H65.9"),
    H66("Supurativna i nespecificirana upala srednjeg uha", "H66"),
    H66_0("Akutna supurativna upala srednjeg uha", "H66.0"),
    H66_1("Kronična tubotimpanična supurativna upala srednjeg uha", "H66.1"),
    H66_2("Kronična atikoantralna supurativna upala srednjeg uha", "H66.2"),
    H66_3("Druga kronična supurativna upala srednjeg uha", "H66.3"),
    H66_4("Supurativna upala srednjeg uha, nespecificirana", "H66.4"),
    H66_9("Upala srednjeg uha, nespecificirana", "H66.9"),
    H67("Upala srednjeg uha u bolestima svrstanim drugamo", "H67"),
    H67_0("Upala srednjeg uha u bakterijskim bolestima svrstanim drugamo", "H67.0"),
    H67_1("Upala srednjeg uha u virusnim bolestima svrstanim drugamo", "H67.1"),
    H67_8("Upala srednjeg uha u drugim bolestima svrstanim drugamo", "H67.8"),
    H68("Salpingitis i opstrukcija Eustahijeve tube", "H68"),
    H68_0("Salpingitis Eustahijeve tube", "H68.0"),
    H68_1("Opstrukcija Eustahijeve tube", "H68.1"),
    H69("Drugi poremećaji Eustahijeve tube", "H69"),
    H69_0("Patološki prohodna (patulozna) Eustahijeva tuba", "H69.0"),
    H69_8("Drugi specificirani poremećaji Eustahijeve tube", "H69.8"),
    H69_9("Poremećaj Eustahijeve tube, nespecificiran", "H69.9"),
    H70("Mastoiditis i srodna stanja", "H70"),
    H70_0("Akutni mastoditis", "H70.0"),
    H70_1("Kronični mastoiditis", "H70.1"),
    H70_2("Petrozitis", "H70.2"),
    H70_8("Drugi mastoditis i srodna stanja", "H70.8"),
    H70_9("Mastoiditis, nespecificiran", "H70.9"),
    H71("Kolesteatom srednjeg uha", "H71"),
    H71_0("Kolesteatom srednjeg uha", "H71.0"),
    H72("Perforacija bubnjića (membrane timpani)", "H72"),
    H72_0("Centralna perforacija bubnjića", "H72.0"),
    H72_1("Perforacija bubnjića u atiku", "H72.1"),
    H72_2("Druge rubne perforacije bubnjića", "H72.2"),
    H72_8("Druge perforacije bubnjića", "H72.8"),
    H72_9("Perforacija bubnjića, nespecificirana", "H72.9"),
    H73("Drugi poremećaji bubnjića", "H73"),
    H73_0("Akutni miringitis", "H73.0"),
    H73_1("Kronični miringitis", "H73.1"),
    H73_8("Drugi specificirani poremećaji membrane timpani", "H73.8"),
    H73_9("Poremećaj membrane timpani, nespecificiran", "H73.9"),
    H74("Druge bolesti srednjeg uha i mastoida", "H74"),
    H74_0("Timpanoskleroza", "H74.0"),
    H74_1("Otitis media adhaesiva", "H74.1"),
    H74_2("Diskontinuitet lanca slušnih koščica i dislokacija slušnih koščica", "H74.2"),
    H74_3("Druge stečene abnormalnosti slušnih koščica", "H74.3"),
    H74_4("Polip srednjeg uha", "H74.4"),
    H74_8("Drugi specificirani poremećaji srednjeg uha i mastoida", "H74.8"),
    H74_9("Drugi poremećaj srednjeg uha i mastoida, nespecificiran", "H74.9"),
    H75("Druge bolesti srednjeg uha i mastoida u bolestima svrstanim drugamo", "H75"),
    H75_0("Mastoiditis u infektivnim i parazitarnim bolestima svrstanim drugamo", "H75.0"),
    H75_8("Drugi specificirani poremećaji srednjeg uha i mastoida u bolestima svrstanim drugamo", "H75.8"),
    H80("Otoskleroza", "H80"),
    H80_0("Otoskleroza koja zahvaća fenestru ovalis, neobliterirajuća", "H80.0"),
    H80_1("Otoskleroza koja zahvaća fenestru ovalis, obliterirajuća", "H80.1"),
    H80_2("Kohlearna otoskleroza", "H80.2"),
    H80_8("Druga otoskleroza", "H80.8"),
    H80_9("Otoskleroza nespecificirana", "H80.9"),
    H81("Poremećaji vestibularne funkcije", "H81"),
    H81_0("Menierova bolest", "H81.0"),
    H81_1("Benigni paroksizmalni vertigo", "H81.1"),
    H81_2("Vestibularni neuronitis", "H81.2"),
    H81_3("Drugi periferni vertigo", "H81.3"),
    H81_4("Vertigo centralnog podrijetla", "H81.4"),
    H81_8("Drugi poremećaji vestibularne funkcije", "H81.8"),
    H81_9("Poremećaj vestibularne funkcije, nespecificiran", "H81.9"),
    H82("Vertiginozni sindrom u bolestima svrstanim drugamo", "H82"),
    H82_0("Vertiginozni sindrom u bolestima svrstanim drugamo", "H82.0"),
    H83("Druge bolesti unutrašnjeg uha", "H83"),
    H83_0("Labirintitis", "H83.0"),
    H83_1("Fistula labirinta", "H83.1"),
    H83_2("Poremećaj funkcije labirinta", "H83.2"),
    H83_3("Posljedice djelovanja buke na unutrašnje uho", "H83.3"),
    H83_8("Druge specificirane bolesti unutrašnjeg uha", "H83.8"),
    H83_9("Bolest unutrašnjeg uha, nespecificirana", "H83.9"),
    H90("Provodni (konduktivni) i zamjedbeni (perceptivni) gubitak sluha", "H90"),
    H90_0("Konduktivni gubitak sluha, obostrani", "H90.0"),
    H90_1("Konduktivni gubitak sluha, jednostrani, s očuvanim sluhom na suprotnoj strani", "H90.1"),
    H90_2("Konduktivni gubitak sluha, nespecificiran", "H90.2"),
    H90_3("Perceptivni gubitak sluha, obostrani", "H90.3"),
    H90_4("Perceptivni gubitak sluha, jednostrani, s očuvanim sluhom na suprotnoj strani", "H90.4"),
    H90_5("Perceptivni gubitak sluha, nespecificiran", "H90.5"),
    H90_6("Mješoviti konduktivni i perceptivni gubitak sluha, obostrano", "H90.6"),
    H90_7("Mješoviti konduktivni i perceptivni gubitak sluha, jednostrano, s očuvanim sluhom na suprotnoj strani", "H90.7"),
    H90_8("Mješoviti konduktivni i perceptivni gubitak sluha, nespecificiran", "H90.8"),
    H91("Drugi gubitak sluha", "H91"),
    H91_0("Ototoksični gubitak sluha", "H91.0"),
    H91_1("Prezbiakuzija", "H91.1"),
    H91_2("Iznenadni idiopatski gubitak sluha", "H91.2"),
    H91_3("Gluhonijemost koja nije svrstana drugamo", "H91.3"),
    H91_8("Drugi specificirani gubitak sluha", "H91.8"),
    H91_9("Gubitak sluha, nespecificiran", "H91.9"),
    H92("Bol u uhu", "H92"),
    H92_0("Otalgija", "H92.0"),
    H92_1("Otorrhoa", "H92.1"),
    H92_2("Otorrhagia", "H92.2"),
    H93("Drugi poremećaji uha nesvrstani drugamo", "H93"),
    H93_0("Degenerativni i vaskularni poremećaji uha", "H93.0"),
    H93_1("Tinnitus (šum u uhu)", "H93.1"),
    H93_2("Druga abnormalnost slušne percepcije", "H93.2"),
    H93_3("Poremećaji akustičnog živca", "H93.3"),
    H93_8("Drugi specificirani poremećaji uha", "H93.8"),
    H93_9("Poremećaj uha, nespecificiran", "H93.9"),
    H94("Drugi poremećaji uha u bolestima svrstanim drugamo", "H94"),
    H94_0("Akustični neuritis u infektivnim i parazitarnim bolestima svrstanim drugamo", "H94."),
    H94_8("Drugi specificirani poremećaji uha u bolestima svrstanim drugamo", "H94."),
    H95("Poremećaji uha i mastoida nakon određenih zahvata, koji nisu svrstani drugamo", "H95"),
    H95_0("Povratni (rekurentni) kolesteatom trepanacijske šupljine nakon mastoidektomije", "H95.0"),
    H95_1("Drugi poremećaji nakon mastoidektomije", "H95.1"),
    H95_8("Drugi poremećaji uha i mastoidnog nastavka nakon određenih zahvata", "H95.8"),
    H95_9("Poremećaj uha i mastoida nakon određenih zahvata, nespecificiran", "H95.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesH(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
