package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesV {
    
    V01("Pješak ozlijeđen u sudaru s vozilom na pedale", "V01"),
    V01_0("Pješak ozlijeđen u sudaru s vozilom na pedale", "V01.0"),
    V02("Pješak ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V02"),
    V02_0("Pješak ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V02.0"),
    V03("Pješak ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V03"),
    V03_0("Pješak ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V03.0"),
    V04("Pješak ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V04"),
    V04_0("Pješak ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V04.0"),
    V05("Pješak ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V05"),
    V05_0("Pješak ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V05.0"),
    V06("Pješak ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V06"),
    V06_0("Pješak ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V06.0"),
    V09("Pješak ozlijeđen u drugim i nespecificiranim nezgodama pri prijevozu", "V09"),
    V09_0("Pješak ozlijeđen u nezgodi izvan prometa u koju su uključena druga i nespecificirana motorna vozila", "V09.0"),
    V09_1("Pješak ozlijeđen u nespecificiranoj nezgodi izvan prometa", "V09.1"),
    V09_2("Pješak ozlijeđen u prometnoj nezgodi pri prijevozu u koju su uključena druga i nespecificirana motorna vozila", "V09.2"),
    V09_3("Pješak ozlijeđen u nespecificiranoj prometnoj nezgodi", "V09.3"),
    V09_9("Pješak ozlijeđen u nespecificiranoj nezgodi pri prijevozu", "V09.9"),
    V10("Biciklist ozlijeđen u sudaru s pješakom ili životinjom", "V10"),
    V10_0("Biciklist ozlijeđen u sudaru s pješakom ili životinjom", "V10.0"),
    V11("Biciklist ozlijeđen u sudaru s drugim biciklistom", "V11"),
    V11_0("Biciklist ozlijeđen u sudaru s drugim biciklistom", "V11.0"),
    V12("Biciklist ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V12"),
    V12_0("Biciklist ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V12.0"),
    V13("Biciklist ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V13"),
    V13_0("Biciklist ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V13.0"),
    V14("Biciklist ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V14"),
    V14_0("Biciklist ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V14.0"),
    V15("Biciklist ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V15"),
    V15_0("Biciklist ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V15.0"),
    V16("Biciklist ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V16"),
    V16_0("Biciklist ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V16.0"),
    V17("Biciklist ozlijeđen u sudaru s prikvačenim ili nepokretnim objektom", "V17"),
    V17_0("Biciklist ozlijeđen u sudaru s prikvačenim ili nepokretnim objektom", "V17.0"),
    V18("Biciklist ozlijeđen u nezgodi tijekom prijevoza bez sudara", "V18"),
    V18_0("Biciklist ozlijeđen u nezgodi tijekom prijevoza bez sudara", "V18.0"),
    V19("Biciklist ozlijeđen u drugim i nespecificiranim nezgodama pri prijevozu", "V19"),
    V19_0("Vozač ozlijeđen u sudaru s drugim i pobliže nespecificiranim motornim vozilom u nezgodi izvan prometa", "V19.0"),
    V19_1("Suvozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilom u nezgodi izvan prometa", "V19.1"),
    V19_2("Nespecificirani biciklist ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilom u nezgodi izvan prometa", "V19.2"),
    V19_3("Biciklist (bilo koji) ozlijeđen u nespecificiranoj nezgodi, izvan prometa", "V19.3"),
    V19_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilom u prometnoj nezgodi", "V19.4"),
    V19_5("Suvozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilom u prometnoj nezgodi", "V19.5"),
    V19_6("Biciklist, nespecificirani, ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilom u prometnoj nezgodi", "V19.6"),
    V19_8("Biciklist (bilo koji) ozlijeđen u drugim specificiranim nezgodama tijekom prijevoza", "V19.8"),
    V19_9("Biciklist (bilo koji) ozlijeđen u nespecificiranoj prometnoj nezgodi", "V19.9"),
    V20("Motociklist ozlijeđen u sudaru s pješakom ili životinjom", "V20"),
    V20_0("Motociklist ozlijeđen u sudaru s pješakom ili životinjom", "V20.0"),
    V21("Motociklist ozlijeđen u sudaru s vozilom na pedale", "V21"),
    V21_0("Motociklist ozlijeđen u sudaru s vozilom na pedale", "V21.0"),
    V22("Motociklist ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V22"),
    V22_0("Motociklist ozlijeđen u sudaru s motornim vozilom na dva ili tri kotača", "V22.0"),
    V23("Motociklist ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V23"),
    V23_0("Motociklist ozlijeđen u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V23.0"),
    V24("Motociklist ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V24"),
    V24_0("Motociklist ozlijeđen u sudaru s teškim prijevoznim vozilom ili autobusom", "V24.0"),
    V25("Motociklist ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V25"),
    V25_0("Motociklist ozlijeđen u sudaru s vlakom ili željezničkim vozilom", "V25.0"),
    V26("Motociklist ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V26"),
    V26_0("Motociklist ozlijeđen u sudaru s drugim vozilom koje nije motorno", "V26.0"),
    V27("Motociklist ozlijeđen u sudaru s prikvačenim ili nepokretnim objektom", "V27"),
    V27_0("Motociklist ozlijeđen u sudaru s prikvačenim ili nepokretnim objektom", "V27.0"),
    V28("Motociklist ozlijeđen u nezgodi pri prijevozu bez sudara", "V28"),
    V28_0("Motociklist ozlijeđen u nezgodi pri prijevozu bez sudara", "V28.0"),
    V29("Motociklist ozlijeđen u drugim i nespecificiranim nezgodama pri prijevozu", "V29"),
    V29_0("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V29.0"),
    V29_1("Suvozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V29.1"),
    V29_2("Nespecificirani motociklist ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V29.2"),
    V29_3("Motociklist (bilo koji) ozlijeđen u nespecificiranoj nezgodi izvan prometa", "V29.3"),
    V29_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V29.4"),
    V29_5("Suvozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V29.5"),
    V29_6("Nespecificirani motociklist ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V29.6"),
    V29_8("Motociklist (bilo koji) ozlijeđen u drugoj specificiranoj nezgodi pri prijevozu", "V29.8"),
    V29_9("Motociklist (bilo koji) ozlijeđen u nespecificiranoj prometnoj nezgodi", "V29.9"),
    V30("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s pješakom ili životinjom", "V30"),
    V30_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s pješakom ili životinjom", "V30.0"),
    V31("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s vozilom na pedale", "V31"),
    V31_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s vozilom na pedale", "V31.0"),
    V32("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V32"),
    V32_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V32.0"),
    V33("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V33"),
    V33_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V33.0"),
    V34("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V34"),
    V34_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V34.0"),
    V35("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V35"),
    V35_0("Osoba na motronom vozilu s tri kotača ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V35.0"),
    V36("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V36"),
    V36_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V36.0"),
    V37("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V37"),
    V37_0("Osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V37.0"),
    V38("Osoba na motornom vozilu s tri kotača ozlijeđena u nezgodi pri prijevozu bez sudara", "V38"),
    V38_0("Osoba na motornom vozilu s tri kotača ozlijeđena u nezgodi pri prijevozu bez sudara", "V38.0"),
    V39("Osoba na motornom vozilu s tri kotača ozlijeđena u drugoj i nespecificiranoj nezgodi pri prijevozu", "V39"),
    V39_0("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V39.0"),
    V39_1("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V39.1"),
    V39_2("Nespecificirana osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilom u nezgodi izvan prometa", "V39.2"),
    V39_3("Osoba (bilo koja) na motornom vozilu s tri kotača ozlijeđena u nespecificiranoj nezgodi izvan prometa", "V39.3"),
    V39_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V39.4"),
    V39_5("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V39.5"),
    V39_6("Nespecificirana osoba na motornom vozilu s tri kotača ozlijeđena u sudaru s drugim ili nespecificiranim motornim vozilom u prometnoj nezgodi", "V39.6"),
    V39_8("Osoba (bilo koja) na motornom vozilu s tri kotača ozlijeđena u ostalim specificiranim nezgodama pri prijevozu", "V39.8"),
    V39_9("Osoba (bilo koja) na motornom vozilu s tri kotača ozlijeđena u nespecificiranoj prometnoj nezgodi", "V39.9"),
    V40("Osoba u automobilu ozlijeđena u sudaru s pješakom ili životinjom", "V40"),
    V40_0("Osoba u automobilu ozlijeđena u sudaru s pješakom ili životinjom", "V40.0"),
    V41("Osoba u automobilu ozlijeđena u sudaru s vozilom na pedale", "V41"),
    V41_0("Osoba u automobilu ozlijeđena u sudaru s vozilom na pdedale", "V41.0"),
    V42("Osoba u automobilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V42"),
    V42_0("Osoba u automobilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V42.0"),
    V43("Osoba u automobilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V43"),
    V43_0("Osoba u automobilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V43.0"),
    V44("Osoba u automobilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V44"),
    V44_0("Osoba u automobilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V44.0"),
    V45("Osoba u automobilu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V45"),
    V45_0("Osoba u automobilu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V45.0"),
    V46("Osoba u automobilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V46"),
    V46_0("Osoba u automobilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V46.0"),
    V47("Osoba u automobilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V47"),
    V47_0("Osoba u automobilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V47.0"),
    V48("Osoba u automobilu ozlijeđena u nezgodi pri prijevozu bez sudara", "V48"),
    V48_0("Osoba u automobilu ozlijeđena u nezgodi pri prijevozu bez sudara", "V48.0"),
    V49("Osoba u automobilu ozlijeđena u drugim i nespecificiranim nezgodama pri prijevozu", "V49"),
    V49_0("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V49.0"),
    V49_1("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V49.1"),
    V49_2("Nespecificirana osoba u automobilu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V49.2"),
    V49_3("Osoba u automobilu (bilo koja) ozlijeđena u nespecificiranoj nezgodi izvan prometa", "V49.3"),
    V49_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V49.4"),
    V49_5("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V49.5"),
    V49_6("Nespecificirana osoba u automobilu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V49.6"),
    V49_8("Osoba (bilo koja) u automobilu ozlijeđena u drugim specificiranim nezgodama pri prijevozu", "V49.8"),
    V49_9("Osoba (bilo koja) u automobilu ozlijeđena u nespecificiranoj prometnoj nezgodi", "V49.9"),
    V50("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s pješakom ili životinjom", "V50"),
    V50_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s pješakom ili životinjom", "V50.0"),
    V51("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s vozilom na pedale", "V51"),
    V51_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s vozilom na pedale", "V51.0"),
    V52("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V52"),
    V52_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V52.0"),
    V53("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V53"),
    V53_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V53.0"),
    V54("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V54"),
    V54_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V54.0"),
    V55("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V55"),
    V55_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V55.0"),
    V56("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V56"),
    V56_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V56.0"),
    V57("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V57"),
    V57_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V57.0"),
    V58("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u nezgodi pri prijevozu bez sudara", "V58"),
    V58_0("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u nezgodi pri prijevozu bez sudara", "V58.0"),
    V59("Osoba u kamionetu ili dostavnom vozilu ozlijeđena u ostalim i nespecificiranim nezgodama pri prijevozu", "V59"),
    V59_0("Vozač ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V59.0"),
    V59_1("Putnik ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V59.1"),
    V59_2("Nespecificirana osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V59.2"),
    V59_3("Osoba (bilo koja) u kamionetu ili dostavnom vozilu ozlijeđena u nespecificiranoj nezgodi izvan prometa", "V59.3"),
    V59_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V59.4"),
    V59_5("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V59.5"),
    V59_6("Nespecificirana osoba u kamionetu ili dostavnom vozilu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V59.6"),
    V59_8("Osoba (bilo koja) u kamionetu ili dostavnom vozilu ozlijeđena u nespecificiranoj nezgodi pri prijevozu", "V59.8"),
    V59_9("Osoba (bilo koja) u kamionetu ili dostavnom vozilu ozlijeđena u nespecificiranoj prometnoj nezgodi", "V59.9"),
    V60("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s pješakom ili životinjom", "V60"),
    V60_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s pješakom ili životinjom", "V60.0"),
    V61("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s vozilom na pedale", "V61"),
    V61_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s vozilom na pedale", "V61.0"),
    V62("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V62"),
    V62_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V62.0"),
    V63("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V63"),
    V63_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V63.0"),
    V64("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V64"),
    V64_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V64.0"),
    V65("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s teškim vlakom ili željezničkim vozilom", "V65"),
    V65_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s teškim vlakom ili željezničkim vozilom", "V65.0"),
    V66("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V66"),
    V66_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V66.0"),
    V67("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V67"),
    V67_0("Osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V67.0"),
    V68("Osoba u teškom prijevoznom vozilu ozlijeđena u nezgodi pri rijevozu bez sudara", "V68"),
    V68_0("Osoba u teškom prijevoznom vozilu ozlijeđena u nezgodi pri prijevozu bez sudara", "V68.0"),
    V69("Osoba u teškom prijevoznom vozilu ozlijeđena u drugim i nespecificiranim nezgodama pri prijevozu", "V69"),
    V69_0("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V69.0"),
    V69_1("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V69.1"),
    V69_2("Nespecificirana osoba u teškom prijevoznom vozilu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilom u nezgodi izvan prometa", "V69.2"),
    V69_3("Osoba (bilo koja) u teškom prijevoznom vozilu ozlijeđena u nespecificiranoj nezgodi izvan prometa", "V69.3"),
    V69_4("Vozač ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V69.4"),
    V69_5("Putnik ozlijeđen u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V69.5"),
    V69_6("Nespecificirana osoba u teškom prijevoznom vozilu ozlijeđena u prometnoj nezgodi s nespecificiranim motornim vozilima", "V69.6"),
    V69_8("Osoba (bilo koja) u teškom prijevoznom vozilu ozlijeđena u drugim specificiranim nezgodama pri prijevozu", "V69.8"),
    V69_9("Osoba (bilo koja) u teškom prijevoznom vozilu ozlijeđena u nespecificiranoj prometnoj nezgodi", "V69.9"),
    V70("Osoba u autobusu ozlijeđena u sudaru s pješakom ili životinjom", "V70"),
    V70_0("Osoba u autobusu ozlijeđena u sudaru s pješakom ili životinjom", "V70.0"),
    V71("Osoba u autobusu ozlijeđena u sudaru s vozilom na pedale", "V71"),
    V71_0("Osoba u autobusu ozlijeđena u sudaru s vozilom na pedale", "V71.0"),
    V72("Osoba u autobusu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V72"),
    V72_0("Osoba u autobusu ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V72.0"),
    V73("Osoba u autobusu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V73"),
    V73_0("Osoba u autobusu ozlijeđena u sudaru s automobilom, kamionetom ili dostavnim vozilom", "V73.0"),
    V74("Osoba u autobusu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V74"),
    V74_0("Osoba u autobusu ozlijeđena u sudaru s teškim prijevoznim vozilom ili autobusom", "V74.0"),
    V75("Osoba u autobusu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V75"),
    V75_0("Osoba u autobusu ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V75.0"),
    V76("Osoba u autobusu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V76"),
    V76_0("Osoba u autobusu ozlijeđena u sudaru s drugim vozilom koje nije motorno", "V76.0"),
    V77("Osoba u autobusu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V77"),
    V77_0("Osoba u autobusu ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V77.0"),
    V78("Osoba u autobusu ozlijeđena u nezgodi pri prijevozu bez sudara", "V78"),
    V78_0("Osoba u autobusu ozlijeđena u nezgodi pri prijevozu bez sudara", "V78.0"),
    V79("Osoba u autobusu ozlijeđena u ostalim i nespecificiranim nezgodama pri prijevozu", "V79"),
    V79_0("Vozač ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V79.0"),
    V79_1("Putnik ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u nezgodi izvan prometa", "V79.1"),
    V79_2("Nespecificirana osoba u autobusu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilom u nezgodi izvan prometa", "V79.2"),
    V79_3("Osoba (bilo koja) u autobusu ozlijeđena u nespecificiranoj nezgodi izvan prometa", "V79.3"),
    V79_4("Vozač ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V79.4"),
    V79_5("Putnik ozlijeđen u sudaru s ostalim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V79.5"),
    V79_6("Nespecificirana osoba u autobusu ozlijeđena u sudaru s drugim i nespecificiranim motornim vozilima u prometnoj nezgodi", "V79.6"),
    V79_8("Osoba (bilo koja) u autobusu ozlijeđena u drugoj specificiranoj nezgodi pri prijevozu", "V79.8"),
    V79_9("Osoba (bilo koja) u autobusu ozlijeđena u nespecificiranoj prometnoj nezgodi", "V79.9"),
    V80("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u nezgodi pri prijevozu", "V80."),
    V80_0("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena padom ili zbacivanjem sa životinje ili vozila sa životinjskom vučom u nezgodi bez sudara", "V80.0"),
    V80_1("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s pješakom ili životinjom", "V80.1"),
    V80_2("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s vozilom na pedale", "V80.2"),
    V80_3("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s motornim vozilom na dva ili tri kotača", "V80.3"),
    V80_4("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s automobilom, kaminetom ili dostavnim vozilom, teškim prijevoznim vozilom ili autobusom", "V80.4"),
    V80_5("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s drugim specificiranim motornim vozilom", "V80.5"),
    V80_6("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s vlakom ili željezničkim vozilom", "V80.6"),
    V80_7("Jahač ili osoba u vozilu sa životinjskom vučom ozliješena u sudaru s drugim vozilom koje nije motorno", "V80.7"),
    V80_8("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u sudaru s prikvačenim ili nepokretnim objektom", "V80.8"),
    V80_9("Jahač ili osoba u vozilu sa životinjskom vučom ozlijeđena u drugim i nespecificiranim nezgodama pri prijevozu", "V80.9"),
    V81("Osoba u vlaku ili željezničkom vozilu ozlijeđena u nezgodi pri prijevozu", "V81."),
    V81_0("Osoba u vlaku ili željezničkom vozilu ozlijeđena u sudaru s motornim vozilom u nezgodi izvan prometa", "V81.0"),
    V81_1("Osoba u vlaku ili željezničkom vozilu ozlijeđena u sudaru s motornim vozilom u prometnoj nezgodi", "V81.1"),
    V81_2("Osoba u vlaku ili željezničkom vozilu ozlijeđena u sudaru s drugim vlakom ili željezničkim vozilom", "V81.2"),
    V81_3("Osoba u vlaku ili željezničkom vozilu ozlijeđena u sudaru s drugim objektom", "V81.3"),
    V81_4("Osoba ozlijeđena dok je ulazila ili silazila s vlaka ili željezničkog vozila", "V81.4"),
    V81_5("Osoba u vlaku ili željezničkom vozilu ozlijeđena pri padu s vlaka ili željezničkog vozila", "V81.5"),
    V81_6("Osoba u vlaku ili željezničkom vozilu ozlijeđena zbog pada iz vlaka ili željezničkog vozila", "V81.6"),
    V81_7("Osoba u vlaku ili željezničkom vozilu ozlijeđena pri iskliznuću vlaka iz tračnica bez prethodnog sudara", "V81.7"),
    V81_8("Osoba u vlaku ili željezničkom vozilu ozlijeđena u drugim specificiranim željezničkim nezgodama", "V81.8"),
    V81_9("Osoba u vlaku ili željezničkom vozilu ozlijeđena u nespecificiranim željezničkim nezgodama", "V81.9"),
    V82("Osoba u tramvaju ozlijeđena u nezgodi pri prijevozu", "V82."),
    V82_0("Osoba u tramvaju ozlijeđena u sudaru s motornim vozilom u nezgodi izvan prijevoza", "V82.0"),
    V82_1("Osoba u tramvaju ozlijeđena u sudaru s motornim vozilom u prometnoj nezgodi", "V82.1"),
    V82_2("Osoba u tramvaju ozlijeđena u sudaru s drugim tramvajem", "V82.2"),
    V82_3("Osoba u tramvaju ozlijeđena u sudaru s drugim objektom", "V82.3"),
    V82_4("Osoba ozlijeđena dok je ulazila ili silazila s tramvaja", "V82.4"),
    V82_5("Osoba u tramvaju ozlijeđena pri padu u tramvaju", "V82.5"),
    V82_6("Osoba u tramvaju ozlijeđena pri padu iz tramvaja", "V82.6"),
    V82_7("Osoba u tramvaju ozlijeđena pri iskliznuću iz tračnica bez prethodnog sudara", "V82.7"),
    V82_8("Osoba u tramvaju ozlijeđena u drugim specificiranim nezgodama pri prijevozu", "V82.8"),
    V82_9("Osoba u tramvaju ozlijeđena u nespecificiranoj prometnoj nezgodi", "V82.9"),
    V83("Osoba u posebnom vozilu koje se uglavnom koristi u industriji ozlijeđena u nezgodi pri prijevozu", "V83."),
    V83_0("Vozač posebnog industrijskog vozila ozlijeđen u prometnoj nezgodi", "V83.0"),
    V83_1("Putnik u posebnom industrijskom vozilu ozlijeđen u prometnoj nezgodi", "V83.1"),
    V83_2("Osoba na vanjskom dijelu posebnog industrijskog vozila ozlijeđena u prometnoj nezgodi", "V83.2"),
    V83_3("Nespecificirana osoba u posebnom industrijskom vozilu ozlijeđena u prometnoj nezgodi", "V83.3"),
    V83_4("Osoba ozlijeđena za vrijeme ulaska ili silaska s posebnog industrijskog vozila", "V83.4"),
    V83_5("Vozač posebnog industrijskog vozila ozlijeđen u nezgodi izvan prometa", "V83.5"),
    V83_6("Putnik u posebnom industrijskom vozilu ozlijeđen u nezgodi izvan prometa", "V83.6"),
    V83_7("Osoba na vanjskom dijelu posebnog industrijskog vozila ozlijeđena u nezgodi izvan prometa", "V83.7"),
    V83_9("Nespecificirana osoba u posebnom industrijskom vozilu ozlijeđena u nezgodi izvan prometa", "V83.9"),
    V84("Osoba u posebnom vozilu koje se uglavnom koristi u poljoprivredi ozlijeđena u nezgodi pri prijevozu", "V84."),
    V84_0("Vozač posebnog poljoprivrednog vozila ozlijeđen u prometnoj nezgodi", "V84.0"),
    V84_1("Putnik u posebnom poljoprivrednom vozilu ozlijeđen u prometnoj nezgodi", "V84.1"),
    V84_2("Osoba na vanjskom dijelu posebnog poljoprivrednog vozila ozlijeđena u prometnoj nezgodi", "V84.2"),
    V84_3("Nespecificirana osoba u posebnom poljoprivrednom vozilu ozlijeđena u prometnoj nezgodi", "V84.3"),
    V84_4("Osoba ozlijeđena za vrijeme ulaska ili silaska s posebnog poljoprivrednog vozila", "V84.4"),
    V84_5("Vozač posebnog poljoprivrednog vozila ozlijeđen u nezgodi izvan prometa", "V84.5"),
    V84_6("Putnik u posebnom poljoprivrednom vozilu ozlijeđen u nezgodi izvan prometa", "V84.6"),
    V84_7("Osoba na vanjskom dijelu posebnog poljoprivrednog vozila ozlijeđena u nezgodi izvan prometa", "V84.7"),
    V84_9("Nespecificirana osoba u posebnom poljoprivrednom vozilu ozlijeđena u nezgodi izvan prometa", "V84.9"),
    V85("Osoba u posebnom građevinskom vozilu ozlijeđena u nezgodi pri prijevozu", "V85."),
    V85_0("Vozač posebnog građevinskog vozila ozlijeđen u prometnoj nezgodi", "V85.0"),
    V85_1("Putnik u posebnom građevinskom vozilu ozlijeđen u prometnoj nezgodi", "V85.1"),
    V85_2("Osoba na vanjskom dijelu posebnog građevinskog vozila ozlijeđena u prometnoj nezgodi", "V85.2"),
    V85_3("Nespecificirana osoba u posebnom građevinskom vozilu ozlijeđena u prometnoj nezgodi", "V85.3"),
    V85_4("Osoba ozlijeđena za vrijeme ulaska ili silaska s posebnog građevinskog vozila", "V85.4"),
    V85_5("Vozač posebnog građevinskog vozila ozlijeđen u nezgodi izvan prometa", "V85.5"),
    V85_6("Putnik u posebnom građevinskom vozilu ozlijeđen u nezgodi izvan prometa", "V85.6"),
    V85_7("Osoba na vanjskom dijelu posebnog građevinskog vozila ozlijeđena u nezgodi izvan prometa", "V85.7"),
    V85_9("Nespecificirana osoba u posebnom građevinskom vozilu ozlijeđena u nezgodi izvan prometa", "V85.9"),
    V86("Osoba u posebnom terenskom ili drugom motornom vozilu namijenjenom prije svega vožnji izvan ceste ozlijeđena u nezgodi pri prijevozu", "V86."),
    V86_0("Vozač posebnog terenskog vozila ili drugog motornog vozila namijenjenog prvenstveno izvancestovnoj uporabi, ozlijeđen u prometnoj nezgodi", "V86.0"),
    V86_1("Putnik u posebnom terenskom vozilu ili drugom motornom vozilu namijenjenom prvenstveno izvancestovnoj uporabi, ozlijeđen u prometnoj nezgodi", "V86.1"),
    V86_2("Osoba na vanjskom dijelu posebnog terenskog vozila ili drugog motornog vozila, namijenjenog prvenstveno izvancestovnoj uporabi, ozlijeđena u prometnoj nezgodi", "V86.2"),
    V86_3("Nespecificirana osoba u posebnom terenskom vozilu ili drugom motornom vozilu, namijenjenom prvenstveno izvancestovnoj uporabi, ozlijeđena u prometnoj nezgodi", "V86.3"),
    V86_4("Osoba ozlijeđena za vrijeme ulaska ili silaska s posebnog terenskog vozila ili drugog motornog vozila namijenjenog prvenstveno izvancestovnoj uporabi", "V86.4"),
    V86_5("Vozač posebnog terenskog vozila ili drugog motornog vozila, namijenjenog prvenstveno izvancestovnoj uporabi, ozlijeđen u nezgodi izvan prometa", "V86.5"),
    V86_6("Putnik u posebnom terenskom vozilu ili drugom motornom vozilu, namijenjenom prvenstveno izvancestovnoj uporabi, ozlijeđen u nezgodi izvan prometa", "V86.6"),
    V86_7("Osoba na vanjskom dijelu posebnog terenskog vozila ili drugog motornog vozila, namijenjenog prvenstveno izvancestovnoj uporabi, ozlijeđena u nezgodi izvan prometa", "V86.7"),
    V86_9("Nespecificirana osoba u posebnom terenskom vozilu ili drugom motornom vozilu, namijenjenom prvenstveno izvancestovnoj uporabi, ozlijeđena u nezgodi izvan prometa", "V86.9"),
    V87("Prometna nezgoda specificirane vrste, ali uz nepoznato prijevozno sredstvo ozlijeđenog", "V87."),
    V87_0("Osoba ozlijeđena u sudaru automobila i motornog vozila na dva ili tri kotača (u prometu)", "V87.0"),
    V87_1("Osoba ozlijeđena u sudaru drugog motornog vozila i motornog vozila s dva ili tri kotača (u prometu)", "V87.1"),
    V87_2("Osoba ozlijeđena u sudaru automobila i kamioneta ili dostavnog vozila (u prometu)", "V87.2"),
    V87_3("Osoba ozlijeđena u sudaru automobila i autobusa (u prometu)", "V87.3"),
    V87_4("Osoba ozlijeđena u sudaru automobila i teškog prijevoznog vozila (u prometu)", "V87.4"),
    V87_5("Osoba ozlijeđena u sudaru teškog prijevoznog vozila i autobusa (u prometu)", "V87.5"),
    V87_6("Osoba ozlijeđena u sudaru vlaka ili željezničkog vozila i automobila (u prometu)", "V87.6"),
    V87_7("Osoba ozlijeđena u sudaru između drugih specificiranih motornih vozila (u prometu)", "V87.7"),
    V87_8("Osoba ozlijeđena u drugim specificiranim nezgodama pri prijevozu bez sudara sa sudjelovanjem motornog vozila (u prometu)", "V87.8"),
    V87_9("Osoba ozlijeđena u drugim specificiranim (sa sudarom) (bez sudara) nezgodama pri prijevozu u kojima sudjeluje vozilo koje nije motorno (u prometu)", "V87.9"),
    V88("Nezgoda izvan prometa specificirane vrste, ali uz nepoznato prijevozno sredstvo ozlijeđenog", "V88."),
    V88_0("Osoba ozlijeđena u sudaru automobila i motornog vozila na dva ili tri kotača, izvan prometa", "V88.0"),
    V88_1("Osoba ozlijeđena u sudaru drugog motornog vozila i motornog vozila s dva ili tri kotača, izvan prometa", "V88.1"),
    V88_2("Osoba ozlijeđena u sudaru automobila i kamioneta ili dostavnog vozila, izvan prometa", "V88.2"),
    V88_3("Osoba ozlijeđena u sudaru automobila i autobusa, izvan prometa", "V88.3"),
    V88_4("Osoba ozlijeđena u sudaru automobila i teškog prijevoznog vozila, izvan prometa", "V88.4"),
    V88_5("Osoba ozlijeđena u sudaru teškog prijevoznog vozila i autobusa, izvan prometa", "V88.5"),
    V88_6("Osoba ozlijeđena u sudaru vlaka ili željezničkog vozila i automobila, izvan prometa", "V88.6"),
    V88_7("Osoba ozlijeđena u sudaru između drugih specificiranih motornih vozila, izvan prometa", "V88.7"),
    V88_8("Osoba ozlijeđena u drugim specificiranim nezgodama pri prijevozu bez sudara sa sudjelovanjem motornog vozila, izvan prometa", "V88.8"),
    V88_9("Osoba ozlijeđena u drugim specificiranim (sa sudarom)(bez sudara) nezgodama pri prijevozu u kojima sudjeluje vozilo koje nije motorno, izvan prometa", "V88.9"),
    V89("Nezgoda motornog vozila ili vozila koje nije motorno, nespecificirane vrste vozila", "V89."),
    V89_0("Osoba ozlijeđena u nespecificiranoj nezgodi motornog vozila, izvan prometa", "V89.0"),
    V89_1("Osoba ozlijeđena u nespecificiranoj nezgodi vozila koje nije motorno, izvan prometa", "V89.1"),
    V89_2("Osoba ozlijeđena u nespecificiranoj nezgodi motornog vozila, u prometu", "V89.2"),
    V89_3("Osoba ozlijeđena u nespecificiranoj prometnoj nezgodi vozila koje nije motorno", "V89.3"),
    V89_9("Osoba ozlijeđena u nezgodi nespecificiranog vozila", "V89.9"),
    V90("Nezgoda plovila koja uzrokuje utapanje i potapanje", "V90"),
    V90_0("Nezgoda plovila koja uzrokuje utapanje i potapanje", "V90.0"),
    V91("Nezgoda plovila koja uzrokuje drugu ozljedu", "V91"),
    V91_0("Nezgoda plovila koja uzrokuje drugu ozljedu", "V91.0"),
    V92("Utapanja i potapanja povezana s prijevozom na vodi bez nezgode plovila", "V92"),
    V92_0("Utapanja i potapanja povezana s prijevozom na vodi bez nezgode plovila", "V92.0"),
    V93("Nezgoda na palubi plovila bez nezgode samog plovila, koja ne uzrokuje utapanje ili potapanje", "V93"),
    V93_0("Nezgoda na palubi plovila bez nezgode samog plovila, koja ne uzrokuje utapanje ili potapanje", "V93.0"),
    V94("Druge i nespecificirane nezgode pri prijevozu na vodi", "V94"),
    V94_0("Druge i nespecificirane nezgode pri prijevozu na vodi", "V94.0"),
    V95("Nezgoda letjelice s motorom koja je uzrokovala ozljedu osobe u njoj", "V95"),
    V95_0("Nezgoda helikoptera koja uzrokuje ozljedu osobe u njemu", "V95.0"),
    V95_1("Nezgoda jedrilice s motorom te drugih laganih letjelica koja uzrokoje ozljedu osobe u njoj", "V95.1"),
    V95_2("Nezgoda druge letjelice s krilima montiranim u samogradnji koja uzrokuje ozljedu osobe u njoj", "V95.2"),
    V95_3("Nezgoda letjelice s komercijalno ugrađenim krilima s ozljedom osobe u njoj", "V95.3"),
    V95_4("Nezgoda svemirskog broda koja je uzrokovala ozljedu osobe u njemu", "V95.4"),
    V95_8("Druge nezgode letjelice koje uzrokuju ozljedu osobe u njoj", "V95.8"),
    V95_9("Nespecificirana nezgoda letjelice koja uzrokuje ozljedu osobe u njoj", "V95.9"),
    V96("Nezgoda letjelice bez motora koja uzrokuje ozljedu osobe u njoj", "V96"),
    V96_0("Nezgoda balona koja uzrokuje ozljedu osobe u njemu", "V96.0"),
    V96_1("Nezgoda jedrilice na vuču s ozljedom osobe u njoj", "V96.1"),
    V96_2("Nezgoda jedrilice bez motora s ozljedom osobe u njoj", "V96.2"),
    V96_8("Nezgode drugih letjelica bez motora s ozljedom osobe u njima", "V96.8"),
    V96_9("Nespecificirana nezgoda letjelice bez motora s ozljedom osobe u njoj", "V96.9"),
    V97("Druge specificirane nezgode u zračnome prijevozu", "V97"),
    V97_0("Osoba u letjelici ozlijeđena u ostalim specificiranim nezgodama zračnog prijevoza", "V97.0"),
    V97_1("Osoba ozlijeđena za vrijeme ulaska ili silaska s letjelice", "V97.1"),
    V97_2("Padobranac ozlijeđen u nezgodi zračnog prijevoza", "V97.2"),
    V97_3("Osoba na zemlji ozlijeđena u zračnoj nezgodi", "V97.3"),
    V97_8("Druge nezgode u zračnome prijevozu, nesvrstane drugamo", "V97.8"),
    V98("Druge specificirane nezgode pri prijevozu", "V98"),
    V98_0("Druge specificirane nezgode pri prijevozu", "V98.0"),
    V99("Nespecificirana nezgoda pri prijevozu", "V99"),
    V99_0("Nespecificirana nezgoda pri prijevozu", "V99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesV(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
