package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesM {
    
    M00("Piogeni artritis", "M00"),
    M00_0("Stafilokokni artritis i poliartritis", "M00.0"),
    M00_1("Pneumokokni artritis i poliartritis", "M00.1"),
    M00_2("Drugi streptokokni artritis i poliartritis", "M00.2"),
    M00_8("Artritis i poliartritis uzrokovan drugim specificiranim bakterijskim uzročnicima", "M00.8"),
    M00_9("Piogeni artritis, nespecificiran", "M00.9"),
    M01("Direktna infekcija zglobova kod infektivnih i parazitarnih bolesti svrstanih drugamo", "M01"),
    M01_0("Meningokokni artritis (A39.8)", "M01.0"),
    M01_1("Tuberkulozni artritis (A18.0)", "M01.1"),
    M01_2("Artritis kod Lymove bolesti (A69.2)", "M01.2"),
    M01_3("Artritis kod ostalih bakterijskih bolesti svrstanih drugamo", "M01.3"),
    M01_4("Artritis kod rubeole (B06.8)", "M01.4"),
    M01_5("Artritis kod ostalih virusnih bolesti svrstanih drugamo", "M01.5"),
    M01_6("Artritis kod mikoza (B35-B49)", "M01.6"),
    M01_8("Artritis kod ostalih infektivnih i parazitarnih bolesti svrstanih drugamo", "M01.8"),
    M02("Reaktivne artropatije", "M02"),
    M02_0("Artropatija nakon crijevnog premoštenja (intestinalnog bypassa)", "M02.0"),
    M02_1("Postdizenterična artropatija", "M02.1"),
    M02_2("Postimunizacijska artropatija", "M02.2"),
    M02_3("Reiterova bolest", "M02.3"),
    M02_8("Ostale reaktivne artropatije", "M02.8"),
    M02_9("Reaktivna artropatija, nespecificirana", "M02.9"),
    M03("Postinfektivne i reaktivne artropatije kod bolesti svrstanih drugamo", "M03"),
    M03_0("Postmeningokokni artritis (A39.8)", "M03.0"),
    M03_1("Postinfektivna artropatija kod sifilisa", "M03.1"),
    M03_2("Ostale postinfektivne artropatije kod bolesti svrstanih drugamo", "M03.2"),
    M03_6("Reaktivna artropatija kod ostalih bolesti svrstanih drugamo", "M03.6"),
    M05("Seropozitivni reumatoidni artritis", "M05"),
    M05_0("Feltyjev sindrom", "M05.0"),
    M05_1("Reumatoidna bolest pluća (J99.0)", "M05.1"),
    M05_2("Reumatoidni vaskulitis", "M05.2"),
    M05_3("Reumatoidni artritis koji zahvaća druge organe i sustave", "M05.3"),
    M05_8("Drugi seropozitivni reumatoidni artritis", "M05.8"),
    M05_9("Seropozitivni reumatoidni artritis, nespecificiran", "M05.9"),
    M06("Ostali reumatoidni artritisi", "M06"),
    M06_0("Seronegativni reumatoidni artritis", "M06.0"),
    M06_1("Stillova bolest koja započinje u odraslih osoba", "M06.1"),
    M06_2("Reumatoidni burzitis", "M06.2"),
    M06_3("Reumatoidni čvorići (noduli)", "M06.3"),
    M06_4("Upalna poliartropatija", "M06.4"),
    M06_8("Drugi specificirani reumatoidni artritis", "M06.8"),
    M06_9("Reumatoidni artritis, nespecificiran", "M06.9"),
    M07("Psorijatične i enteropatske artropatije", "M07"),
    M07_0("Distalna interfalangealna psorijatična artropatija (L40.5)", "M07.0"),
    M07_1("Artritis mutilans (L40.5)", "M07.1"),
    M07_2("Psorijatični spondilitis (L40.5)", "M07.2"),
    M07_3("Druge psorijatične artropatije (L40.5)", "M07.3"),
    M07_4("Artropatija kod Crohnove bolesti (regionalnog enteritisa) (K50.-)", "M07.4"),
    M07_5("Artropatija kod ulceroznog kolitisa (K51.-)", "M07.5"),
    M07_6("Ostale enteropatske artropatije", "M07.6"),
    M08("Mladenački (juvenilni) artritis", "M08"),
    M08_0("Juvenilni reumatoidni artritis", "M08.0"),
    M08_1("Juvenilni ankilozantni spondilitis", "M08.1"),
    M08_2("Juvenilni artritis koji započinje sistemski", "M08.2"),
    M08_3("Juvenilni poliartritis (seronegativni)", "M08.3"),
    M08_4("Juvenilni artritis malih zglobova", "M08.4"),
    M08_8("Drugi juvenilni artritis", "M08.8"),
    M08_9("Juvenilni artritis, nespecificiran", "M08.9"),
    M09("Juvenilni artritis kod bolesti svrstanih drugamo", "M09"),
    M09_0("Juvenilni artritis kod psorijaze (L40.5)", "M09.0"),
    M09_1("Juvenilni artritis kod Crohnove bolesti (regionalnog enteritisa) (K50.-)", "M09.1"),
    M09_2("Juvenilni artritis kod ulceroznog kolitisa (K51.-)", "M09.2"),
    M09_8("Juvenilni artritis kod ostalih bolesti svrstanih drugamo", "M09.8"),
    M10("Giht", "M10"),
    M10_0("Idiopatski giht", "M10.0"),
    M10_1("Giht uzrokovan olovom", "M10.1"),
    M10_2("Giht uzrokovan lijekovima", "M10.2"),
    M10_3("Giht uzrokovan opterećenjem bubrežne funkcije", "M10.3"),
    M10_4("Drugi sekundarni giht", "M10.4"),
    M10_9("Giht, nespecificiran", "M10.9"),
    M11("Druge artropatije uzrokovane kristalima", "M11"),
    M11_0("Bolest odlaganja hidroksiapatita", "M11.0"),
    M11_1("Obiteljska hondrokalcinoza", "M11.1"),
    M11_2("Druge hondrokalcinoze", "M11.2"),
    M11_8("Ostale specificirane artropatije uzrokovane kristalima", "M11.8"),
    M11_9("Artropatija uzrokovana kristalima, nespecificirana", "M11.9"),
    M12("Ostale specificirane artropatije", "M12"),
    M12_0("Kronična postreumatska artropatija (Jaccoud)", "M12.0"),
    M12_1("Kaschin-Beckova bolest", "M12.1"),
    M12_2("Vilonodularni sinovitis (pigmentirani)", "M12.2"),
    M12_3("Palindromični reumatizam", "M12.3"),
    M12_4("Intermitentna hidrartroza", "M12.4"),
    M12_5("Traumatska artropatija", "M12.5"),
    M12_8("Ostale specificirane artropatije nesvrstane drugamo", "M12.8"),
    M13("Drugi artritis", "M13"),
    M13_0("Poliartritis, nespecificiran", "M13.0"),
    M13_1("Monoartritis, nesvrstan drugamo", "M13.1"),
    M13_8("Ostali specificirani artritisi", "M13.8"),
    M13_9("Artritis, nespecificiran", "M13.9"),
    M14("Artropatije kod ostalih bolesti svrstanih drugamo", "M14"),
    M14_0("Gihtična artropatija uzrokovana manjkom enzima i ostalim naslijeđenim poremećajima", "M14.0"),
    M14_1("Artropatija uzrokovana kristalima kod drugih metaboličnih poremećaja", "M14.1"),
    M14_2("Dijabetična artropatija (E10-E14 s uobičajenom četvrtom oznakom .6)", "M14.2"),
    M14_3("Lipoidni dermatoartritis (E78.8)", "M14.3"),
    M14_4("Artropatija kod amiloidoze (E85.-)", "M14.4"),
    M14_5("Artropatije kod ostalih endokrinih, prehrambenih i metaboličnih poremećaja", "M14.5"),
    M14_6("Neuropatska artropatija", "M14.6"),
    M14_8("Artropatije kod ostalih specificiranih bolesti svrstanih drugamo", "M14.8"),
    M15("Poliartroza", "M15"),
    M15_0("Primarna generalizirana (osteo)artroza", "M15.0"),
    M15_1("Heberdenovi čvorovi (s artropatijom)", "M15.1"),
    M15_2("Bouchardovi čvorovi (s artropatijom)", "M15.2"),
    M15_3("Sekundarna višestruka (multipla) artroza", "M15.3"),
    M15_4("Erozivna (osteo)artroza", "M15.4"),
    M15_8("Ostale poliartroze", "M15.8"),
    M15_9("Poliartroza, nespecificirana", "M15.9"),
    M16("Koksartroza (artroza kuka)", "M16"),
    M16_0("Primarna koksartroza, obostrana", "M16.0"),
    M16_1("Druga primarna koksartroza", "M16.1"),
    M16_2("Koksartroza kao rezultat displazije, obostrana", "M16.2"),
    M16_3("Druga displazijska koksartroza", "M16.3"),
    M16_4("Posttraumatska koksartroza, obostrana", "M16.4"),
    M16_5("Druga posttraumatska koksartroza", "M16.5"),
    M16_6("Sekundarna koksartroza, obostrana", "M16.6"),
    M16_7("Ostale sekundarne koksartroze", "M16.7"),
    M16_9("Koksartroza, nespecificirana", "M16.9"),
    M17("Gonartroza (artroza koljena)", "M17"),
    M17_0("Primarna gonartroza, obostrana", "M17.0"),
    M17_1("Druga primarna gonartroza", "M17.1"),
    M17_2("Posttraumatska gonartroza, obostrana", "M17.2"),
    M17_3("Druga posttraumatska gonartroza", "M17.3"),
    M17_4("Druga sekundarna gonartroza, obostrana", "M17.4"),
    M17_5("Ostale sekundarne gonartroze", "M17.5"),
    M17_9("Gonartroza, nespecificirana", "M17.9"),
    M18("Artroza prvoga karpometakarpalnoga zgloba", "M18"),
    M18_0("Primarna artroza prvoga karpometakarpalnoga zgloba, obostrana", "M18.0"),
    M18_1("Druga primarna artroza prvoga karpometakarpalnoga zgloba", "M18.1"),
    M18_2("Posttraumatska artroza prvoga karpometakarpalnoga zgloba, obostrana", "M18.2"),
    M18_3("Druga posttraumatska artroza prvoga karpometakarpalnoga zgloba", "M18.3"),
    M18_4("Ostale sekundarne artroze prvoga karpometakarpalnoga zgloba, obostrane", "M18.4"),
    M18_5("Ostale sekundarne artroze prvoga karpometakarpalnoga zgloba", "M18.5"),
    M18_9("Artroza prvoga karpometakarpalnoga zgloba, nespecificirana", "M18.9"),
    M19("Ostale artroze", "M19"),
    M19_0("Primarna artroza ostalih zglobova", "M19.0"),
    M19_1("Posttraumatska artroza ostalih zglobova", "M19.1"),
    M19_2("Druge sekundarne artroze", "M19.2"),
    M19_8("Druga specificirana artroza", "M19.8"),
    M19_9("Artroza, nespecificirana", "M19.9"),
    M20("Stečene deformacije prstiju škake i stopala", "M20"),
    M20_0("Deformacija prsta (prstiju)", "M20.0"),
    M20_1("Hallux valgus (stečeni)", "M20.1"),
    M20_2("Hallux rigidus", "M20.2"),
    M20_3("Druge deformacije nožnog palca (stečene)", "M20.3"),
    M20_4("Hallux malleus (stečeni)", "M20.4"),
    M20_5("Ostale deformacije nožnog(ih) prsta(iju) (stečene)", "M20.5"),
    M20_6("Stečena deformacija nožnog(ih) prsta(iju), nespecificirana", "M20.6"),
    M21("Ostale stečene deformacije udova", "M21"),
    M21_0("Valgus deformacija, nesvrstana drugamo", "M21.0"),
    M21_1("Varus deformacija, nesvrstana drugamo", "M21.1"),
    M21_2("Fleksijska deformacija", "M21.2"),
    M21_3("Viseća šaka ili stopalo (stečeno)", "M21.3"),
    M21_4("Ravno stopalo (pes planus) (stečeno)", "M21.4"),
    M21_5("Stečena pandžasta šaka, zgrčena šaka, pandžasto stopalo i zgrčeno stopalo", "M21.5"),
    M21_6("Druge stečene deformacije gležnja i stopala", "M21.6"),
    M21_7("Nejednaka dužina udova (stečena)", "M21.7"),
    M21_8("Ostale specificirane stečene deformacije udova", "M21.8"),
    M21_9("Stečena deformacija udova, nespecificirana", "M21.9"),
    M22("Bolesti ivera (patele)", "M22"),
    M22_0("Povratna dislokacija ivera (rekurentna dislokacija patele)", "M22.0"),
    M22_1("Povratno djelomično iščašenje ivera (rekurentna subluksacija patele)", "M22.1"),
    M22_2("Patelofemoralni poremećaji", "M22.2"),
    M22_3("Drugi poremećaji patele", "M22.3"),
    M22_4("Hondromalacija patele", "M22.4"),
    M22_8("Ostale bolesti patele", "M22.8"),
    M22_9("Bolest patele, nespecificirana", "M22.9"),
    M23("Unutrašnje ozljede koljena", "M23"),
    M23_0("Cista meniska", "M23.0"),
    M23_1("Diskoidni menisk (kongenitalni)", "M23.1"),
    M23_2("Poremećaj meniska zbog starog rascjepa ili ozljede", "M23.2"),
    M23_3("Drugi poremećaji meniska", "M23.3"),
    M23_4("Slobodno tijelo u koljenu", "M23.4"),
    M23_5("Kronična nestabilnost koljena", "M23.5"),
    M23_6("Drugi spontani rascjep ligamenta (ligamenata) koljena", "M23.6"),
    M23_8("Ostali unutrašnji poremećaji koljena", "M23.8"),
    M23_9("Unutrašnji poremećaj koljena, nespecificiran", "M23.9"),
    M24("Drugi specificirani poremećaji zglobova", "M24"),
    M24_0("Slobodno tijelo u zglobu", "M24.0"),
    M24_1("Drugi poremećaji zglobne hrskavice", "M24.1"),
    M24_2("Poremećaj ligamenta", "M24.2"),
    M24_3("Patološka dislokacija i subluksacija zgloba, nesvrstana drugamo", "M24.3"),
    M24_4("Povratna dislokacija i subluksacija zgloba", "M24.4"),
    M24_5("Kontraktura zgloba", "M24.5"),
    M24_6("Ankiloza zgloba", "M24.6"),
    M24_7("Protruzija acetabula", "M24.7"),
    M24_8("Ostali specificirani poremećaji zgloba, nesvrstani drugamo", "M24.8"),
    M24_9("Poremećaj zgloba, nespecificiran", "M24.9"),
    M25("Ostali poremećaji zgloba, nesvrstani drugamo", "M25"),
    M25_0("Hemartroza (izljev krvi u zglob)", "M25.0"),
    M25_1("Fistula zgloba", "M25.1"),
    M25_2("Labav (klimav) zglob", "M25.2"),
    M25_3("Ostale nestabilnosti zgloba", "M25.3"),
    M25_4("Izljev u zglob", "M25.4"),
    M25_5("Bol u zglobu", "M25.5"),
    M25_6("Ukočenje zgloba, nesvrstano drugamo", "M25.6"),
    M25_7("Osteofit", "M25.7"),
    M25_8("Ostali specificirani poremećaji zgloba", "M25.8"),
    M25_9("Poremećaj zgloba, nespecificiran", "M25.9"),
    M30("Nodozni poliarteritis i srodna stanja", "M30"),
    M30_0("Nodozni poliarteritis (poliarteritis nodosa", "M30.0"),
    M30_1("Poliarteritis sa zahvaćenim plućima (Churg-Strauss)", "M30.1"),
    M30_2("Juvenilni poliarteritis", "M30.2"),
    M30_3("Mukokutani sindrom limfnih čovorova (Kawasaki)", "M30.3"),
    M30_8("Ostala srodna stanja nodoznoga poliarteritisa", "M30.8"),
    M31("Ostale nekrotizirajuće vaskulopatije", "M31"),
    M31_0("Hipersenzitivni angitis", "M31.0"),
    M31_1("Trombotična mikroangiopatija", "M31.1"),
    M31_2("Smrtonosni granulom srednje crte (midline)", "M31.2"),
    M31_3("Wegnerova granulomatoza", "M31.3"),
    M31_4("Sindrom aortnog luka (Takayasu)", "M31.4"),
    M31_5("Arteritis divovskih stanica (gigantocelularni arteritis) s reumatičnom polimialgijom", "M31.5"),
    M31_6("Ostali arteritisi divovskih stanica", "M31.6"),
    M31_8("Ostale specificirane nekrotizirajuće vaskulopatije", "M31.8"),
    M31_9("Nekrotizirajuća vaskulopatija, nespecificirana", "M31.9"),
    M32("Sistemni lupus eritematozus", "M32"),
    M32_0("Sistemni lupus eritematozus uzrokovan lijekovima", "M32.0"),
    M32_1("Sistemni lupus eritematozus sa zahvaćenim organom ili sustavom", "M32.1"),
    M32_8("Ostali oblici sistemnog eritematoznog lupusa", "M32.8"),
    M32_9("Sistemni lupus eritematozus, nespecificiran", "M32.9"),
    M33("Dermatopolimiozitis", "M33"),
    M33_0("Juvenilni dermatomiozitis", "M33.0"),
    M33_1("Drugi dermatomiozitis", "M33.1"),
    M33_2("Polimiozitis", "M33.2"),
    M33_9("Dermatopolimiozitis, nespecificiran", "M33.9"),
    M34("Sistemna skleroza", "M34"),
    M34_0("Progresivna sistemna skleroza", "M34.0"),
    M34_1("KREST (CREST) sindrom", "M34.1"),
    M34_2("Sistemna skleroza uzrokovana lijekovima i kemikalijama", "M34.2"),
    M34_8("Ostali oblici sistemne skleroze", "M34.8"),
    M34_9("Sistemna skleroza, nespecificirana", "M34.9"),
    M35("Ostale sistemne bolesti vezivnoga tkiva", "M35"),
    M35_0("Sindrom sicca (Sjögren)", "M35.0"),
    M35_1("Drugi sindromi preklapanja (overlap)", "M35.1"),
    M35_2("Behçetova bolest", "M35.2"),
    M35_3("Reumatska polimialgija", "M35.3"),
    M35_4("Difuzni (eozinofilni) fascitis", "M35.4"),
    M35_5("Multifokalna fibroskleroza", "M35.5"),
    M35_6("Povratni panikulitis (Weber-Christian)", "M35.6"),
    M35_7("Sindrom prekomjerne pokretljivosti (sindrom hipermobilnosti)", "M35.7"),
    M35_8("Ostale specificirane sistemne bolesti vezivnoga tkiva", "M35.8"),
    M35_9("Sistemna bolest vezivnoga tkiva, nespecificirana", "M35.9"),
    M36("Sistemni poremećaji vezivnoga tkiva kod bolesti svrstanih drugamo", "M36"),
    M36_0("Dermato(poli)miozitis kod novotvorina (C00-D48)", "M36.0"),
    M36_1("Artropatija kod novotvorina (C00-D48)", "M36.1"),
    M36_2("Hemofilična artropatija (D66-D68)", "M36.2"),
    M36_3("Artropatija kod drugih bolesti krvi (D50-D76)", "M36.3"),
    M36_4("Artropatija kod reakcija preosjetljivosti svrstanih drugamo", "M36.4"),
    M36_8("Sistemni poremećaji vezivnoga tkiva kod bolesti svrstanih drugamo", "M36.8"),
    M40("Kifoza i lordoza", "M40"),
    M40_0("Položajna (posturalna) kifoza", "M40.0"),
    M40_1("Druga sekundarna kifoza", "M40.1"),
    M40_2("Druga nespecificirana kifoza", "M40.2"),
    M40_3("Sindrom ravnih leđa ('flatback' sindrom)", "M40.3"),
    M40_4("Druga lordoza", "M40.4"),
    M40_5("Lordoza, nespecificirana", "M40.5"),
    M41("Skolioza", "M41"),
    M41_0("Dječja (infantilna) idiopatska skolioza", "M41.0"),
    M41_1("Mladenačka (juvenilna) idiopatska skolioza", "M41.1"),
    M41_2("Druga idiopatska skolioza", "M41.2"),
    M41_3("Torakogena skolioza", "M41.3"),
    M41_4("Skolioza, živčano-mišićna (neuromuskularna)", "M41.4"),
    M41_5("Druga sekundarna skolioza", "M41.5"),
    M41_8("Ostali oblici skolioze", "M41.8"),
    M41_9("Skolioza, nespecificirana", "M41.9"),
    M42("Osteohondroza kralježnice", "M42"),
    M42_0("Juvenilna osteohondroza kralježnice", "M42.0"),
    M42_1("Osteohondroza kralježnice u odraslih", "M42.1"),
    M42_9("Osteohondroza kralježnice, nespecificirana", "M42.9"),
    M43("Ostale deformirajuće dorzopatije", "M43"),
    M43_0("Spondiloliza", "M43.0"),
    M43_1("Spondilolisteza", "M43.1"),
    M43_2("Druga stapanja kralježnice", "M43.2"),
    M43_3("Povratna atlanto-aksijalna subluksacija s mijelopatijom", "M43.3"),
    M43_4("Druga povratna atlanto-aksijalna subluksacija", "M43.4"),
    M43_5("Duga povratna subluksacija kralježnice", "M43.5"),
    M43_6("Tortikolis", "M43.6"),
    M43_8("Ostale specificirane deformirajuće dorzopatije", "M43.8"),
    M43_9("Deformirajuća dorzopatija, nespecificirana", "M43.9"),
    M45("Ankilozantni spondilitis", "M45"),
    M46("Druge upalne spondilopatije", "M46"),
    M46_0("Entezopatija kralježnice", "M46.0"),
    M46_1("Sakroileitis, nespecificiran drugamo", "M46.1"),
    M46_2("Osteomijelitis kralješka", "M46.2"),
    M46_3("Infekcija intervertebralnog diska (piogena)", "M46.3"),
    M46_4("Discitis, nespecificiran", "M46.4"),
    M46_5("Druge infektivne spondilopatije", "M46.5"),
    M46_8("Ostale specificirane upalne spondilopatije", "M46.8"),
    M46_9("Upalna spondilopatija, nespecificirana", "M46.9"),
    M47("Spondiloza", "M47"),
    M47_0("Kompresijski sindromi arterija spinalis anterior i vertebralis (G99.2)", "M47.0"),
    M47_1("Druga spondiloza s mijelopatijom", "M47.1"),
    M47_2("Druga spondiloza s radikulopatijom", "M47.2"),
    M47_8("Ostale spondiloze", "M47.8"),
    M47_9("Spondiloza, nespecificirana", "M47.9"),
    M48("Ostale spondilopatije", "M48"),
    M48_0("Stenoza kralježnice", "M48.0"),
    M48_1("Ankilozantna hiperostoza (Forestier)", "M48.1"),
    M48_2("Priljubljena kralježnica ('kissing spine')", "M48.2"),
    M48_3("Traumatska spondilopatija", "M48.3"),
    M48_4("Prijelom kralješka zbog zamora", "M48.4"),
    M48_5("Prelomljeni (kolabirani) kralježak, nesvrstan drugamo", "M48.5"),
    M48_8("Druge specificirane spondilopatije", "M48.8"),
    M48_9("Spondilopatija, nespecificirana", "M48.9"),
    M49("Spondilopatije kod bolesti svrstanih drugamo", "M49"),
    M49_0("Tuberkuloza kralježnice (A18.0)", "M49.0"),
    M49_1("Brucelozni spondilitis (A23.-)", "M49.1"),
    M49_2("Enterobakterijski spondilitis (A01-A04)", "M49.2"),
    M49_3("Spondilopatija kod drugih infektivnih i parazitarnih bolesti svrstanih drugamo", "M49.3"),
    M49_4("Neuropatska spondilopatija", "M49.4"),
    M49_5("Slomljeni kralježak kod bolesti svrstanih drugamo", "M49.5"),
    M49_8("Spondilopatija kod ostalih bolesti svrstanih drugamo", "M49.8"),
    M50("Bolesti cervikalnog diska", "M50"),
    M50_0("Bolesti cervikalnog diska s mijelopatijom (G99.2)", "M50.0"),
    M50_1("Bolesti cervikalnog diska s radikulopatijom", "M50.1"),
    M50_2("Drugi pomak cervikalnog diska", "M50.2"),
    M50_3("Druge degenerativne promjene cervikalnog diska", "M50.3"),
    M50_8("Ostale bolesti cervikalnog diska", "M50.8"),
    M50_9("Bolest cervikalnog diska, nespecificirana", "M50.9"),
    M51("Druge bolesti intervertebralnog diska", "M51"),
    M51_0("Bolesti lumbalnog i drugog intervertebralnog diska s mijelopatijom (G99.2)", "M51.0"),
    M51_1("Bolesti lumbalnog i drugog intervertebralnog diska s radikulopatijom", "M51.1"),
    M51_2("Druga specificirana nestabilnost intervertebralnog diska", "M51.2"),
    M51_3("Druga specificirana degenerativna promjena intervertebralnog diska", "M51.3"),
    M51_4("Schmorlovi čvorovi", "M51.4"),
    M51_8("Ostale specificirane bolesti intervertebralnog diska", "M51.8"),
    M51_9("Bolest intervertebralnog diska, nespecificirana", "M51.9"),
    M53("Ostale dorzopatije, nesvrstane drugamo", "M53"),
    M53_0("Cervikokranijalni sindrom", "M53.0"),
    M53_1("Cervikobrahijalni sindrom", "M53.1"),
    M53_2("Nestabilnost kralježnice", "M53.2"),
    M53_3("Sakrokokcigealne bolesti, nesvrstane drugamo", "M53.3"),
    M53_8("Ostale specificirane dorzopatije", "M53.8"),
    M53_9("Dorzopatija, nespecificirana", "M53.9"),
    M54("Bol u leđima (dorzalgija)", "M54"),
    M54_0("Panikulitis koji zahvaća područje vrata i leđa", "M54.0"),
    M54_1("Radikulopatija", "M54.1"),
    M54_2("Bol u vratu (cervikalgija)", "M54.2"),
    M54_3("Išijas", "M54.3"),
    M54_4("Lumbago s išijasom", "M54.4"),
    M54_5("Bol u donjem dijelu leđa", "M54.5"),
    M54_6("Bol u torakalnoj kralježnici", "M54.6"),
    M54_8("Druga bol u leđima", "M54.8"),
    M54_9("Bol u leđima, nespecificirana", "M54.9"),
    M60("Miozitis", "M60"),
    M60_0("Infektivni miozitis", "M60.0"),
    M60_1("Intersticijski miozitis", "M60.1"),
    M60_2("Granulom stranog tijela mekoga tkiva, nesvrtan drugamo", "M60.2"),
    M60_8("Drugi miozitis", "M60.8"),
    M60_9("Miozitis, nespecificiran", "M60.9"),
    M61("Kalcifikacija i osifikacija mišića", "M61"),
    M61_0("Traumatski osificirajući miozitis (myositis ossificans traumatica)", "M61.0"),
    M61_1("Progresivni osificirajući miozitis (myositis ossificans progressiva)", "M61.1"),
    M61_2("Paralitička kalcifikacija i osifikacija mišića", "M61.2"),
    M61_3("Kalcifikacija i osifikacija mišića združena s opeklinama", "M61.3"),
    M61_4("Druga kalcifikacija mišića", "M61.4"),
    M61_5("Druga osifikacija mišića", "M61.5"),
    M61_9("Kalcifikacija i osifikacija mišića, nespecificirana", "M61.9"),
    M62("Ostale bolesti mišića", "M62"),
    M62_0("Razdvajanje (dijastaza) mišića", "M62.0"),
    M62_1("Druga ruptura mišića (netraumatska)", "M62.1"),
    M62_2("Ishemični infarkt mišića", "M62.2"),
    M62_3("Sindrom nepokretnosti (paraplegični)", "M62.3"),
    M62_4("Kontraktura mišića", "M62.4"),
    M62_5("Hipotrofija i atrofija mišića, nesvrstana drugamo", "M62.5"),
    M62_6("Istegnuti mišić", "M62.6"),
    M62_8("Ostale specificirane ozljede mišića", "M62.8"),
    M62_9("Bolest mišića, nespecificirana", "M62.9"),
    M63("Bolesti mišića kod bolesti svrstanih drugamo", "M63"),
    M63_0("Miozitis kod bakterijskih bolesti svrstanih drugamo", "M63.0"),
    M63_1("Miozitis kod protozoalnih i parazitarnih infekcija svrstanih drugamo", "M63.1"),
    M63_2("Miozitis kod ostalih infektivnih bolesti svrstanih drugamo", "M63.2"),
    M63_3("Miozitis kod sarkoidoze (D86.8)", "M63.3"),
    M63_8("Ostale mišićne bolesti kod bolesti svrstanih drugamo", "M63.8"),
    M65("Sinovitis i tenosinovitis", "M65"),
    M65_0("Apsces tetivne ovojnice", "M65.0"),
    M65_1("Drugi infektivni (teno)sinovitis", "M65.1"),
    M65_2("Kalcificirajući tendinitis", "M65.2"),
    M65_3("Škljocajući prst (trigger finger)", "M65.3"),
    M65_4("Tenosinovitis stiloidnog nastavka radijusa (de Quervain)", "M65.4"),
    M65_8("Ostali sinovitisi i tenosinovitisi", "M65.8"),
    M65_9("Sinovitis i tenosinovitis, nespecificiran", "M65.9"),
    M66("Spontani razdor zglobnih sveza i tetiva", "M66"),
    M66_0("Ruptura poplitealne ciste", "M66.0"),
    M66_1("Ruptura sinovije", "M66.1"),
    M66_2("Spontana ruptura ekstenzornih tetiva", "M66.2"),
    M66_3("Spontana ruptura fleksornih tetiva", "M66.3"),
    M66_4("Spontana ruptura ostalih tetiva", "M66.4"),
    M66_5("Spontana ruptura nespecificirane tetive", "M66.5"),
    M67("Ostale bolesti zglobnih sveza i tetiva", "M67"),
    M67_0("Skraćena Ahilova tetiva (stečena)", "M67.0"),
    M67_1("Druga kontraktura tetive (ovojnice)", "M67.1"),
    M67_2("Sinovijalna hipertrofija, nesvrstana drugamo", "M67.2"),
    M67_3("Prolazni (tranzitorni) sinovitis", "M67.3"),
    M67_4("Ganglion", "M67.4"),
    M67_8("Ostale specificirane bolesti sinovije i tetive", "M67.8"),
    M67_9("Bolest sinovije i tetive, nespecificirana", "M67.9"),
    M68("Bolest zglobnih sveza i tetiva kod bolesti svrstanih drugamo", "M68"),
    M68_0("Sinovitis i tenosinovitis kod bakterijskih bolesti svrstanih drugamo", "M68.0"),
    M68_8("Ostale bolesti sinovije i tetive kod bolesti svrstanih drugamo", "M68.8"),
    M70("Bolesti mekih tkiva nastale kao posljedica uporabe, prekomjerne uporabe i pritiska", "M70"),
    M70_0("Kronični krepitirajući sinovitis šake i ručnoga zgloba", "M70.0"),
    M70_1("Burzitis šake", "M70.1"),
    M70_2("Burzitis olekranona", "M70.2"),
    M70_3("Drugi burzitis lakta", "M70.3"),
    M70_4("Prepatelarni burzitis", "M70.4"),
    M70_5("Drugi burzitis koljena", "M70.5"),
    M70_6("Trohanterični burzitis", "M70.6"),
    M70_7("Drugi burzitis kuka", "M70.7"),
    M70_8("Ostale bolesti mekog tkiva nastale kao posljedica uporabe, prekomjerne uporabe i pritiska", "M70.8"),
    M70_9("Nespecificirane bolesti mekog tkiva nastale kao posljedica uporabe, prekomjerne uporabe i pritiska", "M70.9"),
    M71("Ostale burzopatije", "M71"),
    M71_0("Apsces burze", "M71.0"),
    M71_1("Drugi infektivni burzitis", "M71.1"),
    M71_2("Sinovijalna cista poplitealnog područja (Baker)", "M71.2"),
    M71_3("Druge ciste burze", "M71.3"),
    M71_4("Odlaganje kalcija u burzu", "M71.4"),
    M71_5("Drugi burzitis, nesvrstan drugamo", "M71.5"),
    M71_8("Ostale specificirane burzopatije", "M71.8"),
    M71_9("Burzopatija, nespecificirana", "M71.9"),
    M72("Fibroblastične bolesti", "M72"),
    M72_0("Palmarna fascijalna fibromatoza (Dupuytren)", "M72.0"),
    M72_1("Jastučići na zglobovima nastali zbog pritiska (knuckle pads)", "M72.1"),
    M72_2("Plantarna fascijalna fibromatoza", "M72.2"),
    M72_3("Nodularni fascitis", "M72.3"),
    M72_4("Pseudosarkomatozna fibromatoza", "M72.4"),
    M72_5("Fascitis, nesvrstan drugamo", "M72.5"),
    M72_8("Ostale fibroblastične bolesti", "M72.8"),
    M72_9("Fibroblastična bolest, nespecificirana", "M72.9"),
    M73("Bolesti mekoga tkiva kod bolesti svrstanih drugamo", "M73"),
    M73_0("Gonokokni burzitis (A54.4)", "M73.0"),
    M73_1("Sifilitični burzitis (A52.7)", "M73.1"),
    M73_8("Ostale bolesti mekoga tkiva kod bolesti svrstanih drugamo", "M73.8"),
    M75("Oštećenja ramena", "M74"),
    M75_0("Adhezivni kapsulitis ramena", "M74.0"),
    M75_1("Sindrom rotacijske manžete", "M74.1"),
    M75_2("Upala tetive dvoglavog nadlaktičnog mišića (tendinitis m. bicipitis)", "M74.2"),
    M75_3("Kalcificirajući tendinitis ramena", "M74.3"),
    M75_4("Sindrom subakromijalnog sraza (impingement syndrome)", "M74.4"),
    M75_5("Burzitis ramena", "M74.5"),
    M75_8("Druga oštećenja ramena", "M74.8"),
    M75_9("Oštećenje ramena, nespecificirano", "M74.9"),
    M76("Entenzopatije noge, bez stopala", "M75"),
    M76_0("Tendinitis m. gluteusa", "M75.0"),
    M76_1("Tendinitis m. psoasa", "M75.1"),
    M76_2("Izdanak (egzostoza) ilijakalne kriste", "M75.2"),
    M76_3("Sindrom iliotibijalne mišićne tetive", "M75.3"),
    M76_4("Tibijalni kolateralni burzitis (Pellegrini-Stieda)", "M75.4"),
    M76_5("Patelarni tendinitis", "M75.5"),
    M76_6("Tendinitis Ahilove tetive", "M75.6"),
    M76_7("Tendinitis m. peroneusa", "M75.7"),
    M76_8("Ostale entezopatije noge, bez stopala", "M75.8"),
    M76_9("Entezopatija noge, nespecificirana", "M75.9"),
    M77("Ostale entezopatije", "M76"),
    M77_0("Medijalni epikondilitis", "M76.0"),
    M77_1("Lateralni epikondilitis", "M76.1"),
    M77_2("Periartritis ručnoga zgloba", "M76.2"),
    M77_3("Kalkanealni izdanak (egzostoza)", "M76.3"),
    M77_4("Metatarzalgija", "M76.4"),
    M77_5("Druge entezopatije stopala", "M76.5"),
    M77_8("Ostale entezopatije, nesvrstane drugamo", "M76.8"),
    M77_9("Entezopatija, nespecificirana", "M76.9"),
    M79("Ostale bolesti mekih tkiva, nesvrstane drugamo", "M77"),
    M79_0("Reumatizam, nespecificiran", "M77.0"),
    M79_1("Mialgija", "M77.1"),
    M79_2("Neuralgija i neuritis, nespecificirani", "M77.2"),
    M79_3("Panikulitis, nespecificiran", "M77.3"),
    M79_4("Hipertrofija (infrapatelarnog) masnog jastučića", "M77.4"),
    M79_5("Zaostalo strano tijelo u mekome tkivu", "M77.5"),
    M79_6("Bol u ekstremitetu", "M77.6"),
    M79_8("Ostale specificirane bolesti mekoga tkiva", "M77.8"),
    M79_9("Bolest mekoga tkiva, nespecificirana", "M77.9"),
    M80("Osteoporoza s patološkim prijelomom", "M80"),
    M80_0("Postmenopauzalna osteoporoza s patološkim prijelomom", "M80.0"),
    M80_1("Osteoporoza s patološkim prijelomom nakon odstranjenja jajnika", "M80.1"),
    M80_2("Osteoporoza s patološkim prijelomom zbog neuporabe", "M80.2"),
    M80_3("Malapsorpcijska osteoporoza s patološkim prijelomom nakon kirurškog zahvata", "M80.3"),
    M80_4("Osteoporoza s patološkim prijelomom uzrokovana lijekovima", "M804."),
    M80_5("Idiopatska osteoporoza s patološkim prijelomom", "M80.5"),
    M80_8("Druga osteoporoza s patološkim prijelomom", "M80.8"),
    M80_9("Nespecificirana osteoporoza s patološkim prijelomom", "M80.9"),
    M81("Osteoporoza bez patološkoga prijeloma", "M81"),
    M81_0("Postmenopauzalna osteoporoza", "M81.0"),
    M81_1("Osteoporoza nakon odstranjenja jajnika", "M81.1"),
    M81_2("Osteoporoza zbog neuporabe", "M81.2"),
    M81_3("Malapsorpcijska osteoporoza nakon kirurškog zahvata", "M81.3"),
    M81_4("Osteoporoza uzrokovana lijekovima", "M81.4"),
    M81_5("Idiopatska osteoporoza", "M81.5"),
    M81_6("Ograničena (lokalizirana) osteoporoza (Lequesne)", "M81.6"),
    M81_8("Druga osteoporoza", "M81.8"),
    M81_9("Osteoporoza, nespecificirana", "M81.9"),
    M82("Osteoporoza kod bolesti svrstanih drugamo", "M82"),
    M82_0("Osteoporoza kod multiple mijelomatoze (C90.0)", "M82.0"),
    M82_1("Osteoporoza kod endokrinih bolesti (E00-E34)", "M82.1"),
    M82_8("Osteoporoza kod ostalih bolesti svrstanih drugamo", "M82.8"),
    M83("Osteomalacija u odraslih osoba", "M83"),
    M83_0("Osteomalacija u babinjama", "M83.0"),
    M83_1("Staračka (senilna) osteomalacija", "M83.1"),
    M83_2("Osteomalacija u odraslih kao posljedica malapsorpcije", "M83.2"),
    M83_3("Osteomalacija u odraslih kao posljedica loše prehrane (malnutricijska osteomalacija)", "M83.3"),
    M83_4("Aluminijska bolest kosti (aluminoza)", "M83.4"),
    M83_5("Druga osteomalacija u odraslih uzrokovana lijekovima", "M83.5"),
    M83_8("Druga osteomalacija u odraslih", "M83.8"),
    M83_9("Osteomalacija u odraslih, nespecificirana", "M83.9"),
    M84("Poremećaji kontinuiteta kosti", "M84"),
    M84_0("Loše srastao prijelom", "M84.0"),
    M84_1("Nesrastao prijelom (pseudartroza)", "M84.1"),
    M84_2("Odgođeno srašćivanje prijeloma", "M84.2"),
    M84_3("Prijelom zbog stresa, nesvrstan drugamo", "M84.3"),
    M84_4("Patološki prijelom, nesvrstan drugamo", "M84.4"),
    M84_8("Ostali poremećaji kontinuiteta kosti", "M84.8"),
    M84_9("Poremećaj kontinuiteta kosti, nespecificiran", "M84.9"),
    M85("Ostali poremećaji u čvrstoći i građi kosti", "M85"),
    M85_0("Fibrozna displazija (monostotična)", "M85.0"),
    M85_1("Koštana fluoroza", "M85.1"),
    M85_2("Hiperostoza lubanje", "M85.2"),
    M85_3("Osteitis condensans", "M85.3"),
    M85_4("Pojedinačna (solitarna) cista kosti", "M85.4"),
    M85_5("Aneurizmatska cista kosti", "M85.5"),
    M85_6("Druga cista kosti", "M85.6"),
    M85_8("Ostali specificirani poremećaji u čvrstoći i građi kosti", "M85.8"),
    M85_9("Poremećaj u čvrstoći i građi kosti, nespecificiran", "M85.9"),
    M86("Osteomijelitis", "M86"),
    M86_0("Akutni hematogeni osteomijelitis", "M86.0"),
    M86_1("Drugi akutni osteomijelitis", "M86.1"),
    M86_2("Subakutni osteomijelitis", "M86.2"),
    M86_3("Kronični osteomijelitis mnogostrukih žarišta (multifokalni)", "M86.3"),
    M86_4("Kronični osteomijelitis s drenažnim sinusom", "M86.4"),
    M86_5("Drugi kronični hematogeni osteomijelitis", "M86.5"),
    M86_6("Drugi kronični osteomijelitis", "M86.6"),
    M86_8("Drugi osteomijelitis", "M86.8"),
    M86_9("Osteomijelitis, nespecificiran", "M86.9"),
    M87("Osteonekroza", "M87"),
    M87_0("Idiopatska aseptična nekroza kosti", "M87.0"),
    M87_1("Osteonekroza uzrokovana lijekovima", "M87.1"),
    M87_2("Osteonekroza uzrokovana prijašnjom traumom", "M87.2"),
    M87_3("Druga sekundarna osteonekroza", "M87.3"),
    M87_8("Druga osteonekroza", "M87.8"),
    M87_9("Osteonekroza, nespecificirana", "M87.9"),
    M88("Pagetova bolest kosti (osteitis deformans)", "M88"),
    M88_0("Pagetova bolest lubanje", "M88.0"),
    M88_8("Pagetova bolest ostalih kostiju", "M88.8"),
    M88_9("Pagetova bolest kosti, nespecificirana", "M88.9"),
    M89("Ostali poremećaji kosti", "M89"),
    M89_0("Algoneurodistrofija", "M89.0"),
    M89_1("Epifizni zastoj (arest)", "M89.1"),
    M89_2("Drugi poremećaji razvoja i rasta kosti", "M89.2"),
    M89_3("Hipertrofija kosti", "M89.3"),
    M89_4("Ostale hipertrofične osteoartropatije", "M89.4"),
    M89_5("Razgradnja kosti (osteoliza)", "M89.5"),
    M89_6("Osteopatija nakon poliomijelitisa", "M89.6"),
    M89_8("Ostali specificirani poremećaji kosti", "M89.8"),
    M89_9("Poremećaj kosti, nespecificiran", "M89.9"),
    M90("Osteopatije kod bolesti svrstanih drugamo", "M90"),
    M90_0("Tuberkuloza kosti (A18.0)", "M90.0"),
    M90_1("Periostitis kod ostalih infektivnih bolesti svrstanih drugamo", "M90.1"),
    M90_2("Osteopatija kod drugih infektivnih bolesti svrstanih drugamo", "M90.2"),
    M90_3("Osteonekroza kod kesonske bolesti", "M90.3"),
    M90_4("Osteonekroza uzrokovana hemoglobinopatijom (D50-D64)", "M90.4"),
    M90_5("Osteonekroza kod ostalih bolesti svrstanih drugamo", "M90.5"),
    M90_6("Osteitis deformans kod novotvorina (C00-D48)", "M90.6"),
    M90_7("Prijelom kosti kod novotvorina (C00-D48)", "M90.7"),
    M90_8("Osteopatija kod ostalih bolesti svrstanih drugamo", "M90.8"),
    M91("Mladenačko okoštavanje zglobne hrskavice kuka i zdjelice (juvenilna osteohondroza kuka i zdjelice)", "M91"),
    M91_0("Mladenčka osteohondroza zdjelice", "M91.0"),
    M91_1("Mladenačka osteohondroza glave bedrene kosti (femura) (Legg-Calvé-Perthes)", "M91.1"),
    M91_2("Coxa plana", "M91.2"),
    M91_3("Pseudokoksalgija", "M91.3"),
    M91_8("Ostale mladenačke osteohondroze kuka i zdjelice", "M91.8"),
    M91_9("Mladenačka osteohondroza kuka i zdjelice, nespecificirana", "M91.9"),
    M92("Druge juvenilne osteohondroze", "M92"),
    M92_0("Mladenačka osteohondroza nadlaktične kosti (humerusa)", "M92.0"),
    M92_1("Mladenačka osteohondroza palčane i lakatne kosti (radijusa i ulne)", "M92.1"),
    M92_2("Mladenačka osteohondroza šake", "M92.2"),
    M92_3("Druga juvenilna osteohondroza ruke", "M92.3"),
    M92_4("Mladenačka osteohondroza ivera (patele)", "M92.4"),
    M92_5("Mladenačka osteohondroza goljenične i lisne kosti (tibije i fibule)", "M92.5"),
    M92_6("Mladenačka osteohondroza nožja (tarzusa)", "M92.6"),
    M92_7("Mladenačka osteohondroza donožja (metatarzusa)", "M92.7"),
    M92_8("Druga specificirana juvenilna osteohondroza", "M92.8"),
    M92_9("Mladenačka osteohondroza, nespecificirana", "M92.9"),
    M93("Ostale osteohondropatije", "M93"),
    M93_0("Epifizioliza glave bedrene kosti (femura) (netraumatska)", "M93.0"),
    M93_1("Kienböckova bolest odraslih", "M93.1"),
    M93_2("Osteochondritis dissecans", "M93.2"),
    M93_8("Ostale specificirane osteohondropatije", "M93.8"),
    M93_9("Osteohondropatija, nespecificirana", "M93.9"),
    M94("Ostali poremećaji hrskavice", "M94"),
    M94_0("Sindrom hondrokostalnoga spoja (Tietze)", "M94.0"),
    M94_1("Povratni polihondritis", "M94.1"),
    M94_2("Hondromalacija", "M94.2"),
    M94_3("Hondroliza", "M94.3"),
    M94_8("Drugi specificirani poremećaji hrskavice", "M94.8"),
    M94_9("Bolest hrskavice, nespecificirana", "M94.9"),
    M95("Ostale stečene deformacije mišićno-koštanog sustava i vezivnoga tkiva", "M95"),
    M95_0("Stečeni deformitet nosa", "M95.0"),
    M95_1("Uho u obliku cvjetače", "M95.1"),
    M95_2("Drugi stečeni deformitet glave", "M95.2"),
    M95_3("Stečeni deformitet vrata", "M95.3"),
    M95_4("Stečeni deformitet prsnog koša i rebra", "M95.4"),
    M95_5("Stečeni deformitet zdjelice", "M95.5"),
    M95_8("Ostali specificirani stečeni deformiteti mišićno-koštanog sustava", "M95.8"),
    M95_9("Stečeni deformitet mišićno-koštanog sustava, nespecificiran", "M95.9"),
    M96("Poremećaji mišićno-koštanog sustava koji se pojavljuju nakon određenih postupaka, nesvrstani drugamo", "M96"),
    M96_0("Pseudoartroza nakon osteosinteze ili artrodeze", "M96.0"),
    M96_1("Postlaminektomični sindrom, nesvrstan drugamo", "M96.1"),
    M96_2("Kifoza nakon zračenja (postradijacijska kifoza)", "M96.2"),
    M96_3("Postlaminektomična kifoza", "M96.3"),
    M96_4("Lordoza nakon kirurškog zahvata", "M96.4"),
    M96_5("Skolioza nakon zračenja (postradijacijska skolioza)", "M96.5"),
    M96_6("Prijelom kosti nakon umetanja ortopedskog implantata, zglobne proteze ili koštane ploče", "M96.6"),
    M96_8("Ostali poremećaji mišićno-koštanog sustava nakon određenih zahvata", "M96.8"),
    M96_9("Poremećaj mišićno-koštanog sustava nakon određena postupka, nespecificiran", "M96.9"),
    M99("Biomehanička oštećenja, nesvrstana drugamo", "M99"),
    M99_0("Segmentalna i somatska disfunkcija", "M99.0"),
    M99_1("Složena subluksacija (kralježnice)", "M99.1"),
    M99_2("Subluksacijska stenoza živčanog kanala", "M99.2"),
    M99_3("Koštana stenoza živčanog kanala", "M99.3"),
    M99_4("Stenoza živčanog kanala vezivnim tkivom", "M99.4"),
    M99_5("Stenoza živčanog kanala intervertebralnim diskom", "M99.5"),
    M99_6("Koštana i subluksacijska stenoza intervertebralnih otvora (foramina)", "M99.6"),
    M99_7("Stenoza intervertebralnih otvora (foramina) vezivnim tkivom i diskom", "M99.7"),
    M99_8("Ostala biomehanička oštećenja", "M99.8"),
    M99_9("Biomehaničko oštećenje, nespecificirano", "M99.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesM(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
