package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesR {
    
    R00("Abnormalnosti otkucaja srca", "R00"),
    R00_0("Nespecificirana tahikardija", "R00.0"),
    R00_1("Nespecificirana bradikardija", "R00.1"),
    R00_2("Palpitacije", "R00.2"),
    R00_8("Ostale i nespecificirane abnormalnosti srčanih otkucaja", "R00.8"),
    R01("Srčani šumovi i ostali srčani zvukovi", "R01"),
    R01_0("Dobroćudni i neopasni srčani šumovi", "R01.0"),
    R01_1("Srčani šum, nespecificiran", "R01.1"),
    R01_2("Ostali srčani zvukovi", "R01.2"),
    R02("Gangrena, nesvrstana drugamo", "R02"),
    R02_0("Gangrena, ako nije svrstana drugamo", "R02.0"),
    R03("Abnormalna vrijednost krvnoga tlaka - bez dijagnoze", "R03"),
    R03_0("Povišena vrijednost krvnoga tlaka - bez dijagnoze hipertenzije", "R03.0"),
    R03_1("Snižena vrijednost krvnoga tlaka, nespecificirana", "R03.1"),
    R04("Krvarenje iz dišnih putova", "R04"),
    R04_0("Krvarenje iz nosa (epistaksa)", "R04.0"),
    R04_1("Krvarenje iz grla", "R04.1"),
    R04_2("Hemoptiza", "R04.2"),
    R04_8("Krvarenje iz drugih dijelova dišnih putova", "R04.8"),
    R04_9("Krvarenje iz dišnih putova, nespecificirano", "R04.9"),
    R05("Kašalj", "R05"),
    R05_0("Kašalj", "R05.0"),
    R06("Nepravilnosti disanja", "R06"),
    R06_0("Dispneja", "R06.0"),
    R06_1("Stridor", "R06.1"),
    R06_2("Zviždanje (wheezing)", "R06.1"),
    R06_3("Isprekidano disanje", "R06.2"),
    R06_4("Hiperventilacija", "R06.4"),
    R06_5("Disanje na usta", "R06.5"),
    R06_6("Štucanje", "R06.6"),
    R06_7("Kihanje", "R06.7"),
    R06_8("Ostale i nespecificirane abnormalnosti disanja", "R06.8"),
    R07("Bol u grlu i prsištu", "R07"),
    R07_0("Bol u grlu", "R07.0"),
    R07_1("Bol u prsištu pri disanju", "R07.1"),
    R07_2("Prekordijalna bol", "R07.2"),
    R07_3("Druga bol u prsištu", "R07.3"),
    R07_4("Bol u prsištu, nespecificirana", "R07.4"),
    R09("Ostali simptomi i znakovi koji se odnose na cirkulacijski i dišni sustav", "R09"),
    R09_0("Gušenje (asfiksija)", "R09.0"),
    R09_1("Pleuritis (upala plućne ovojnice)", "R09.1"),
    R09_2("Zastoj disanja", "R09.2"),
    R09_3("Abnormalnosti iskašljaja", "R09.3"),
    R09_8("Ostali specificirani simptomi i znakovi koji se odnose na cirkulacijski i dišni sustav", "R09.8"),
    R10("Boli u trbuhu i zdjelici", "R10."),
    R10_0("Akutni abdomen", "R10.0"),
    R10_1("Bol u gornjem dijelu abdomena", "R10.1"),
    R10_2("Bol u zdjelici i međici", "R10.2"),
    R10_3("Bol na ostalim mjestima u donjem dijelu abdomena", "R10.3"),
    R10_4("Druge i nespecificirane boli u abdomenu", "R10.4"),
    R11("Mučnina i povraćanje", "R11"),
    R11_0("Mučnina i povraćanje", "R11.0"),
    R12("Žgaravica", "R12"),
    R12_0("Žgaravica", "R12.0"),
    R13("Disfagija", "R13"),
    R13_0("Disfagija", "R13.0"),
    R14("Nadimanje i srodna stanja", "R14"),
    R14_0("Nadimanje i srodna stanja", "R14.0"),
    R15("Nemogućnost kontroliranja stolice", "R15"),
    R15_0("Nemogućnost kontroliranja stolice", "R15.0"),
    R16("Hepatomegalija i splenomegalija (povećana jetra i povećana slezena), nesvrstane drugamo", "R16"),
    R16_0("Povećana jetra, nesvrstana drugamo", "R16.0"),
    R16_1("Povećana slezena, nesvrstana drugamo", "R16.1"),
    R16_2("Povećana jetra i slezena, nesvrstane drugamo", "R16.2"),
    R17("Žutica, nespecificirana", "R17"),
    R17_0("Žutica, nespecificirana", "R17.0"),
    R18("Ascites", "R18"),
    R18_0("Ascites", "R18.0"),
    R19("Ostali simptomi i znakovi koji se odnose na probavni sustav i trbušnu šupljinu", "R19"),
    R19_0("Oteklina, izraslina i kvržica unutar trbušne i zdjelične šupljine", "R19.0"),
    R19_1("Abnormalni zvukovi u crijevima", "R19.1"),
    R19_2("Vidljiva peristaltika", "R19.2"),
    R19_3("Napetost trbušne stijenke", "R19.3"),
    R19_4("Promjene uobičajenog rada crijeva", "R19.4"),
    R19_5("Druge abnormalnosti stolice", "R19.5"),
    R19_6("Zadah iz usta", "R19.6"),
    R19_8("Drugi specificirani simptomi i znakovi koji se odnose na probavni sustav i trbušnu šupljinu", "R19.8"),
    R20("Poremećaji osjeta kože", "R20"),
    R20_0("Anestezija (neosjetljivost) kože", "R20.0"),
    R20_1("Hipostezija (smanjena osjetljivost) kože", "R20.1"),
    R20_2("Parestezija kože", "R20.2"),
    R20_3("Hiperestezija (preosjetljivost) kože", "R20.3"),
    R20_8("Drugi i nespecificirani poremećaji osjeta kože", "R20.8"),
    R21("Osip i druge nespecificirane kožne promjene", "R21"),
    R21_0("Osip i druge nespecificirane kožne promjene", "R21.0"),
    R22("Lokalizirana oteklina, izraslina i kvržica kože i potkožnoga tkiva", "R22"),
    R22_0("Lokalizirana oteklina, izraslina i kvržica na glavi", "R22.0"),
    R22_1("Lokalizirana oteklina, izraslina i kvržica na vratu", "R22.1"),
    R22_2("Lokalizirana oteklina, izraslina i kvržica na trupu", "R22.2"),
    R22_3("Lokalizirana oteklina, izraslina i kvržica na ruci", "R22.3"),
    R22_4("Lokalizirana oteklina, izraslina i kvržica na nozi", "R22.4"),
    R22_7("Lokalizirana oteklina, izraslina i kvržica na više mjesta", "R22.7"),
    R22_9("Lokalizirana oteklina, izraslina i kvržica, nespecificirana", "R22.9"),
    R23("Druge kožne promjene", "R23"),
    R23_0("Cijanoza (modra koža)", "R23.0"),
    R23_1("Bljedoća kože", "R23.1"),
    R23_2("Crvenilo kože", "R23.2"),
    R23_3("Spontane ekhimoze (potkožna krvarenja)", "R23.3"),
    R23_4("Promjene površine kože", "R23.4"),
    R23_8("Druge i nespecificirane promjene na koži", "R23.8"),
    R25("Abnormalni nevoljni pokreti", "R25"),
    R25_0("Abnormalni pokreti glave", "R25.0"),
    R25_1("Tremor, nespecificiran", "R25.1"),
    R25_2("Grč i spazam", "R25.2"),
    R25_3("Fascikulacije", "R25.3"),
    R25_8("Drugi i nesvrstani abnormalni nevoljni pokreti", "R25.8"),
    R26("Nenormalnosti hodanja i pokretljivosti", "R26"),
    R26_0("Ataksični hod", "R26.0"),
    R26_1("Paralitični hod", "R26.1"),
    R26_2("Otežan hod, nesvrstan drugamo", "R26.2"),
    R26_8("Druga i nespecificirana nenormalnost hodanja i pokretljivosti", "R26.8"),
    R27("Druga manjkavost koordinacije", "R27"),
    R27_0("Ataksija, nespecificirana", "R27.0"),
    R27_8("Druga i nespecificirana manjkavost koordinacije", "R27.8"),
    R29("Drugi simptomi i znakovi koji se odnose na živčani i mišićno-koštani sustav", "R29"),
    R29_0("Tetanija", "R29.0"),
    R29_1("Meningizam", "R29.1"),
    R29_2("Abnormalni refleks", "R29.2"),
    R29_3("Abnormalno držanje", "R29.3"),
    R29_4("Škljocanje kuka", "R29.4"),
    R29_8("Drugi i nespecificirani simptomi i znakovi koji se odnose na živčani i mišićno-koštani sustav", "R29.8"),
    R30("Bol pri mokrenju", "R30"),
    R30_0("Dizurija", "R30.0"),
    R30_1("Grčevi mjehura (kolike)", "R30.1"),
    R30_9("Bolno mokrenje, nespecificirano", "R30.9"),
    R31("Krv u mokraći, nespecificirana", "R31"),
    R31_0("Krv u mokraći, nespecificirana", "R31.0"),
    R32("Inkontinencija mokraće, nespecificirana", "R32"),
    R32_0("Inkontinencija mokraće, nespecificirana", "R32.0"),
    R33("Retencija mokraće", "R33"),
    R33_0("Retencija mokraće", "R33.0"),
    R34("Anurija i oliguruja", "R34"),
    R34_0("Anurija i oliguruja", "R34.0"),
    R35("Poliurija", "R35"),
    R35_0("Poliurija", "R35.0"),
    R36("Iscjedak iz uretre", "R36"),
    R36_0("Iscjedak iz uretre", "R36.0"),
    R39("Drugi simptomi i znakovi koji se odnose na urinarni sustav", "R39"),
    R39_0("Mokrenje izvan normalnih putova", "R39.0"),
    R39_1("Druge poteškoće mokrenja", "R39.1"),
    R39_2("Ekstrarenalna uremija", "R39.2"),
    R39_8("Drugi i nespecificirani simptomi i znakovi koji se odnose na urinarni sustav", "R39.8"),
    R40("Somnolencija (pospanost), stupor (ukočenost, obamrlost) i koma", "R40"),
    R40_0("Somnolencija", "R40.0"),
    R40_1("Stupor", "R40.1"),
    R40_2("Koma, nespecificirana", "R40.2"),
    R41("Ostali simptomi i znakovi koji se odnose na spoznaju, percepciju, duševno stanje i ponašanje", "R41"),
    R41_0("Neorijentiranost, nespecificirana", "R41.0"),
    R41_1("Antegradna amnezija", "R41.1"),
    R41_2("Retrogradna amnezija", "R41.2"),
    R41_3("Druga amnezija", "R41.3"),
    R41_8("Ostali i nespecificirani simptomi i znakovi koji se odnose na spoznaju, percepciju, duševno stanje i ponašanje", "R41.8"),
    R42("Vrtoglavica, omaglica", "R42"),
    R42_0("Vrtoglavica, omaglica", "R42.0"),
    R43("Poremećaji mirisa i okusa", "R43"),
    R43_0("Anosmija (gubitak osjeta mirisa)", "R43.0"),
    R43_1("Parosmija (izmijenjenost osjeta mirisa)", "R43.1"),
    R43_2("Parageuzija (izmijenjenost osjeta okusa)", "R43.2"),
    R43_8("Drugi i nespecificirani poremaćaji mirisa i okusa", "R43.8"),
    R44("Drugi simptomi i znakovi koji se odnose na opće osjete i percepciju", "R44"),
    R44_0("Slušne halucinacije", "R44.0"),
    R44_1("Vidne halucinacije", "R44.1"),
    R44_2("Druge halucinacije", "R44.2"),
    R44_3("Halucinacije, nespecificirane", "R44.3"),
    R44_8("Drugi i nespecificirani simptomi i znakovi koji se odnose na opće osjete i percepciju", "R44.8"),
    R45("Simptomi i znakovi koji se odnose na emocionalno stanje", "R45"),
    R45_0("Nervoza", "R45.0"),
    R45_1("Nemir i stanja uzbuđenosti", "R45.1"),
    R45_2("Nesretnost, nezadovoljstvo", "R45.2"),
    R45_3("Obeshrabrenost i apatija", "R45.3"),
    R45_4("Razdražljivost i bijes", "R45.4"),
    R45_5("Neprijateljsko držanje", "R45.5"),
    R45_6("Fizičko nasilje", "R45.6"),
    R45_7("Stanje emocionalnog šoka ili stresa, nespecificirano", "R45.7"),
    R45_8("Drugi simptomi i znakovi koji se odnose na emocionalno stanje", "R45.8"),
    R46("Simptomi i znakovi koji se odnose na izgled i ponašanje", "R46"),
    R46_0("Vrlo niska razina osobne higijene", "R46.0"),
    R46_1("Bizaran izgled", "R46.1"),
    R46_2("Ponašanje, čudno i neobjašnjivo", "R46.2"),
    R46_3("Pretjerana aktivnost", "R46.3"),
    R46_4("Usporenost i slabo reagiranje", "R46.4"),
    R46_5("Sumnjičavost i uočljivo izbjegavanje", "R46.5"),
    R46_6("Pretjerano bavljenje i zaokupiranost stresnim događajima", "R46.6"),
    R46_7("Bolesnikova brbljavost (pričljivost) i okolišanje čine nejasnim razlog dolaska", "R46.7"),
    R46_8("Drugi simptomi i znakovi koji se odnose na izgled i ponašanje", "R46.8"),
    R47("Poremećaji govora, nesvrstani drugamo", "R47"),
    R47_0("Disfazija i afazija", "R47.0"),
    R47_1("Dizartrija i anartrija", "R47.1"),
    R47_8("Drugi i nespecificirani poremećaji govora", "R47.8"),
    R48("Disleksija i druge disfunkcije izražavanja, nesvrstane drugamo", "R48"),
    R48_0("Disleksija i aleksija", "R48.0"),
    R48_1("Agnozija (nemogućnost spoznavanja)", "R48.1"),
    R48_2("Apraksija (nemogućnost izražavanja)", "R48.2"),
    R48_8("Druge i nespecificirane disfunkcije izražavanja", "R48.8"),
    R49("Poremećaji glasa", "R49"),
    R49_0("Disfonija", "R49.0"),
    R49_1("Afonija", "R49.1"),
    R49_2("Hipernazalnost i hiponazalnost govora", "R49.2"),
    R49_8("Drugi i nespecificirani poremećaji glasa", "R49.8"),
    R50("Vrućica nepoznata podrijetla", "R50"),
    R50_0("Vrućica sa zimicom", "R50.0"),
    R50_1("Tvrdokorna vrućica", "R50.1"),
    R50_8("Vrućica, nespecificirana", "R50.8"),
    R51("Glavobolja", "R51"),
    R51_0("Glavobolja", "R51.0"),
    R52("Bol, nesvrstana drugamo", "R52"),
    R52_0("Akutna bol", "R52.0"),
    R52_1("Kronična tvrdokorna bol", "R52.1"),
    R52_2("Druga kronična bol", "R52.2"),
    R52_9("Bol, nespecificirana", "R52.9"),
    R53("Slabost i umor", "R53"),
    R53_0("Slabost i umor", "R53.0"),
    R54("Senilnost", "R54"),
    R54_0("Senilnost", "R54.0"),
    R55("Sinkopa i kolaps", "R55"),
    R55_0("Sinkopa i kolaps", "R55.0"),
    R56("Konvulzije, nesvrstane drugamo", "R56"),
    R56_0("Febrilne konvulzije", "R56.0"),
    R56_8("Druge i nespecificirane konvulzije", "R56.8"),
    R57("Šok, nesvrstan drugamo", "R57"),
    R57_0("Kardiogeni šok", "R57.0"),
    R57_1("Hipovolemični šok", "R57.1"),
    R57_8("Šok, ostali", "R57.8"),
    R57_9("Šok, nespecificiran", "R57.9"),
    R58("Krvarenje, nesvrstano drugamo", "R58"),
    R58_0("Krvarenje, nesvrstano drugamo", "R58.0"),
    R59("Povećani limfni čvorovi", "R59"),
    R59_0("Lokalno povećani limfni čvorovi", "R59.0"),
    R59_1("Generalizirano povećanje limfnih čvorova", "R59.1"),
    R59_9("Povećani limfni čvorovi, nespecificirani", "R59.9"),
    R60("Edemi, nesvrstani drugamo", "R60"),
    R60_0("Lokalizirani edem", "R60.0"),
    R60_1("Generalizirani edem", "R60.1"),
    R60_9("Edem, nespecificiran", "R60.9"),
    R61("Pojačano znojenje (hiperhidroza)", "R61"),
    R61_0("Lokalno pojačano znojenje", "R61.0"),
    R61_1("Generalizirano pojačano znojenje", "R61.1"),
    R61_9("Pojačano znojenje, nespecificirano", "R61.9"),
    R62("Izostanak očekivanoga normalnog fiziološkog razvoja", "R62"),
    R62_0("Zakašnjenje ili izostanak očekivana stupnja razvoja", "R62.0"),
    R62_8("Drugi izostanak očekivanoga normalnog fiziološkog razvoja", "R62.8"),
    R62_9("Izostanak očekivanoga normalnog fiziološkog razvoja, nespecificiran", "R62.9"),
    R63("Simptomi i znakovi koji se odnose na uzimanje hrane i tekućine", "R63"),
    R63_0("Anoreksija", "R63.0"),
    R63_1("Polidipsija (pojačano pijenje vode)", "R63.1"),
    R63_2("Polifagija (pojačano uzimanje hrane)", "R63.2"),
    R63_3("Poteškoće hranjenja i pogrešna prehrana", "R63.3"),
    R63_4("Abnormalni gubitak tjelesne težine", "R63.4"),
    R63_5("Abnormalno dobivanje na tjelesnoj težini", "R63.5"),
    R63_8("Drugi simptomi i znakovi u vezi s uzimanjem hrane i tekućina", "R63.8"),
    R64("Kaheksija", "R64"),
    R64_0("Kaheksija", "R64.0"),
    R68("Drugi opći simptomi i znakovi", "R68"),
    R68_0("Hipotermija koja nije u vezi sa sniženom vanjskom temperaturom", "R68.0"),
    R68_1("Nespecifični simptomi dojenačke dobi", "R68.1"),
    R68_2("Suhoća usta, nespecificirana", "R68.2"),
    R68_3("Zadebljanja prstiju", "R68.3"),
    R68_8("Drugi specificirani opći simptomi i znakovi", "R68.8"),
    R69("Nepoznati i nespecificirani uzroci bolesti", "R69"),
    R69_0("Nepoznati i nespecificirani uzroci bolesti", "R69.0"),
    R70("Ubrzana sedimentacija eritrocita i abnormalnosti viskoznosti krvne plazme", "R70"),
    R70_0("Ubrzana sedimentacija eritrocita", "R70.0"),
    R70_1("Abnormalna viskoznost krvne plazme", "R70.1"),
    R71("Abnormalnost crvenih krvnih stanica", "R71"),
    R71_0("Abnormalnost crvenih krvnih stanica", "R71.0"),
    R72("Abnormalnost bijelih krvnih stanica, nesvrstana drugamo", "R72"),
    R72_0("Abnormalnost bijelih krvnih stanica, nesvrstana drugamo", "R72.0"),
    R73("Povećana razina glukoze u krvi", "R73"),
    R73_0("Abnormalni nalaz testa opterećenja glukozom", "R73.0"),
    R73_9("Hiperglikemija, nespecificirana", "R73.9"),
    R74("Abnormalna razina serumskih bjelančevina", "R74."),
    R74_0("Povećanje razine transaminaze i dehidrogenaze mliječne kiseline (LDH)", "R74.0"),
    R74_8("Abnormalna razina drugih serumskih enzima", "R74.8"),
    R74_9("Abnormalna razina serumskih enzima, nespecificirana", "R74.9"),
    R75("Laboratorijski utvrđena prisutnost virusa humane imunodeficijencije (HIV)", "R75"),
    R75_0("Laboratorijski utvrđena prisutnost virusa humane imunodeficijencije (HIV)", "R75.0"),
    R76("Drugi abnormalni imunološki nalazi u serumu", "R76"),
    R76_0("Povišen titar protutijela", "R76.0"),
    R76_1("Abnormalna reakcija na test tuberkulinom", "R76.1"),
    R76_2("Lažno pozitivan serološki test na sifilis", "R76.2"),
    R76_8("Drugi specificirani abnormalni imunološki nalazi u serumu", "R76.8"),
    R76_9("Abnormalni nalaz imunoloških pretraga seruma, nespecificiran", "R76.9"),
    R77("Drugi abnormalni nalazi proteina u plazmi", "R77"),
    R77_0("Abnormalan nalaz albumina", "R77.0"),
    R77_1("Abnormalan nalaz globulina", "R77.1"),
    R77_2("Abnormalan nalaz alfa-fetoproteina", "R77.2"),
    R77_8("Drugi specificirani abnormalni nalaz plazmatskih proteina", "R77.8"),
    R77_9("Abnormalan nalaz plazmatskih proteina, nespecificiran", "R77.9"),
    R78("Prisutnost lijekova i drugih tvari kojih normalno nema u krvi", "R78"),
    R78_0("Prisutnost alkohola u krvi", "R78.0"),
    R78_1("Prisutnost opijata u krvi", "R78.1"),
    R78_2("Prisutnost kokaina u krvi", "R78.2"),
    R78_3("Prisutnost halucinogena u krvi", "R78.3"),
    R78_4("Prisutnost drugih lijekova u krvi koji mogu uzrokovati ovisnost", "R78.4"),
    R78_5("Prisutnost psihotropnih lijekova u krvi", "R78.5"),
    R78_6("Prisutnost steroidnih tvari u krvi", "R78.6"),
    R78_7("Prisutnost abnormalne razine teških metala u krvi", "R78.7"),
    R78_8("Prisutnost drugih specificiranih tvari kojih normalno nema u krvi", "R78.8"),
    R78_9("Prisutnost tvari kojih normalno nema u krvi, nespecificirana", "R78.9"),
    R79("Drugi abnormalni kemijski nalazi krvi", "R79"),
    R79_0("Abnormalna razina minerala u krvi", "R79.0"),
    R79_8("Ostali specificirani abnormalni kemijski nalazi krvi", "R79.8"),
    R79_9("Abnormalni kemijski nalazi krvi, nespecificirani", "R79.9"),
    R80("Izolirana proteinurija", "R80"),
    R80_0("Izolirana proteinurija", "R80.0"),
    R81("Glikozurija", "R81"),
    R81_0("Glikozurija", "R81.0"),
    R82("Drugi abnormalni nalazi u mokraći", "R82"),
    R82_0("Kilurija", "R82.0"),
    R82_1("Mioglobinurija", "R82.1"),
    R82_2("Biliurija", "R82.2"),
    R82_3("Hemoglobinurija", "R82.3"),
    R82_4("Acetonurija", "R82.4"),
    R82_5("Povećana razina lijekova, medikamenata i bioloških tvari u mokraći", "R82.5"),
    R82_6("Abnormalna razina tvari uglavnom nemedicinskog podrijetla u mokraći", "R82.6"),
    R82_7("Abnormalan nalaz pri mikrobiološkim pretragama mokraće", "R82.7"),
    R82_8("Abnormalan nalaz citoloških i histoloških pretraga mokraće", "R82.8"),
    R82_9("Drugi i nespecificirani abnormalni nalazi u mokraći", "R82.9"),
    R83("Abnormalan nalaz u cerebrospinalnoj tekućini", "R83"),
    R83_0("Abnormalan nalaz u cerebrospinalnoj tekućini", "R83.0"),
    R84("Abnormalan nalaz u uzorcima iz dišnog sustava i šupljine prsnog koša", "R84"),
    R84_0("Abnormalan nalaz u uzorcima iz dišnog sustava i šupljine prsnog koša", "R84.0"),
    R85("Abnormalan nalaz u uzorcima iz probavnog sustava i trbušne šupljine", "R85"),
    R85_0("Abnormalan nalaz u uzorcima iz probavnog sustava i trbušne šupljine", "R85.0"),
    R86("Abnormalan nalaz u uzorcima iz muških spolnih organa", "R86"),
    R86_0("Abnormalan nalaz u uzorcima iz muških spolnih organa", "R86.0"),
    R87("Abnormalan nalaz u uzorcima iz ženskih spolnih organa", "R87"),
    R87_0("Abnormalan nalaz u uzorcima iz ženskih spolnih organa", "R87.0"),
    R89("Abnormalan nalaz u uzorcima iz drugih organa, sustava i tkiva", "R89"),
    R89_0("Abnormalan nalaz u uzorcima iz drugih organa, sustava i tkiva", "R89.0"),
    R90("Abnormalni nalazi kod dijagnostičkoga snimanja središnjega živčanog sustava", "R90"),
    R90_0("Intrakranijalno ekspandirajuće oštećenje", "R90.0"),
    R90_8("Drugi abnormalni nalazi kod dijagnostičkoga snimanja središnjega živčanog sustava", "R90.8"),
    R91("Abnormalni nalazi kod dijagnostičkoga snimanja pluća", "R91"),
    R91_0("Abnormalni nalazi kod dijagnostičkoga snimanja pluća", "R91.0"),
    R92("Abnormalni nalazi kod dijagnostičkoga snimanja dojke", "R92"),
    R92_0("Abnormalni nalazi kod dijagnostičkoga snimanja dojke", "R92.0"),
    R93("Abnormalni nalazi kod dijagnostičkoga snimanja drugih dijelova tijela", "R93"),
    R93_0("Abnormalni nalazi kod dijagnostičkoga snimanja lubanje i glave, nesvrstani drugamo", "R93.0"),
    R93_1("Abnormalni nalazi kod dijagnostičkoga snimanja srca i koronarnog optjecaja", "R93.1"),
    R93_2("Abnormalni nalazi kod dijagnostičkoga snimanja jetre i bilijarnog sustava", "R93.2"),
    R93_3("Abnormalni nalazi kod dijagnostičkoga snimanja drugih dijelova probavnog sustava", "R93.3"),
    R93_4("Abnormalni nalazi kod dijagnostičkoga snimanja mokraćnih organa", "R93.4"),
    R93_5("Abnormalni nalazi kod dijagnostičkoga snimanja ostalih dijelova trbušne šupljine, uključujući retroperitoneum", "R93.5"),
    R93_6("Abnormalni nalazi kod dijagnostičkoga snimanja udova", "R93.6"),
    R93_7("Abnormalni nalazi kod dijagnostičkoga snimanja ostalih dijelova mišićno-koštanog sustava", "R93.7"),
    R93_8("Abnormalni nalazi kod dijagnostičkoga snimanja drugih specificiranih dijelova tijela", "R93.8"),
    R94("Abnormalni rezultati funkcionalnih ispitivanja", "R94"),
    R94_0("Abnormalni rezultati funkcionalnih pretraga središnjega živčanog sustava", "R94.0"),
    R94_1("Abnormalni rezultati funkcionalnih pretraga perifernoga živčanog sustava i osjetilnih organa", "R94.1"),
    R94_2("Abnormalni rezultati funkcionalnih pretraga pluća", "R94.2"),
    R94_3("Abnormalni rezultati funkcionalnih pretraga cirkulacijskog sustava", "R94.3"),
    R94_4("Abnormalni rezultati funkcionalnih pretraga bubrega", "R94.4"),
    R94_5("Abnormalni rezultati funkcionalnih pretraga jetre", "R94.5"),
    R94_6("Abnormalni rezultati funkcionalnih pretraga štitnjače", "R94.6"),
    R94_7("Abnormalni rezultati funkcionalnih pretraga drugih endokrinih funkcija", "R94.7"),
    R94_8("Abnormalni rezultati funkcionalnih pretraga drugih organa i sustava", "R94.8"),
    R95("Sindrom iznenadne smrti dojenčeta", "R95"),
    R95_0("Sindrom iznenadne smrti dojenčeta", "R95.0"),
    R96("Ostale iznenadne smrti nepoznata uzroka", "R96"),
    R96_0("Trenutna smrt", "R96.0"),
    R96_1("Smrt koja se dogodila za manje od 24 sata od pojave simptoma, a nije objašnjena drukčije", "R96.1"),
    R98("Smrt bez prisutnosti drugih osoba", "R98"),
    R98_0("Smrt bez prisutnosti drugih osoba", "R98.0"),
    R99("Drugi nedovoljno definirani i nespecificirani uzroci smrti", "R99"),
    R99_0("Drugi nedovoljno definirani i nespecificirani uzroci smrti", "R99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesR(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
