package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesL {
    
    L00("Sindrom stafilokoknog ljuštenja kože", "L00"),
    L00_0("Sindrom stafilokoknog ljuštenja kože", "L00.0"),
    L01("Impetigo", "L01"),
    L01_0("Impetigo (bilo koji uzročnik), (bilo koja lokalizacija)", "L01.0"),
    L01_1("Impetiginizacija ostalih dermatoza", "L01.1"),
    L02("Apsces, furunkul i karbunkul kože", "L02"),
    L02_0("Apsces, furunkul i karbunkul kože lica", "L02.0"),
    L02_1("Apsces, furunkul i karbunkul kože vrata", "L02.1"),
    L02_2("Apsces, furunkul i karbunkul kože trupa", "L02.2"),
    L02_3("Apsces, furunkul i karbunkul glutealnog područja", "L02.3"),
    L02_4("Apsces, furunkul i karbunkul kože udova (ruku i nogu)", "L02.4"),
    L02_8("Apsces, furunkul i karbunkul kože ostalih područja", "L02.8"),
    L02_9("Apsces, furunkul i karbunkul kože, nespecificiran", "L02.9"),
    L03("Celulitis", "L03"),
    L03_0("Celulitis prstiju ruku i nogu", "L03.0"),
    L03_1("Celulitis ostalih područja udova", "L03.1"),
    L03_2("Celulitis lica", "L03.2"),
    L03_3("Celulitis trupa", "L03.3"),
    L03_8("Celulitis ostalih lokalizacija", "L03.8"),
    L03_9("Celulitis, nespecificiran", "L03.9"),
    L04("Akutni limfadenitis", "L04"),
    L04_0("Akutni limfadenitis lica, glave i vrata", "L04.0"),
    L04_1("Akutni limfadenitis trupa", "L04.1"),
    L04_2("Akutni limfadenitis ruku", "L04.2"),
    L04_3("Akutni limfadenitis nogu", "L04.3"),
    L04_8("Akutni limfadenitis ostalih lokalizacija", "L04.8"),
    L04_9("Akutni limfadenitis, nespecificiran", "L04.9"),
    L05("Pilonidalna cista", "L05"),
    L05_0("Pilonidalna cista s apscesom", "L05.0"),
    L05_9("Pilonidalna cista bez apscesa", "L05.9"),
    L08("Ostale lokalne infekcije kože i potkožnoga tkiva", "L08"),
    L08_0("Piodermija", "L08.0"),
    L08_1("Eritrazma", "L08.1"),
    L08_8("Ostale specificirane lokalne infekcije kože i potkožnoga tkiva", "L08.8"),
    L08_9("Lokalne infekcije kože i potkožnoga tkiva, nespecificirane", "L08.9"),
    L10("Pemfigus", "L10"),
    L10_0("Pemfigus vulgaris", "L10.0"),
    L10_1("Pemfigus vegetans", "L10.1"),
    L10_2("Pemfigus foliaceus", "L10.2"),
    L10_3("Brazilski pemfigus (fogo selvagem)", "L10.3"),
    L10_4("Pemfigus erythematosus", "L10.4"),
    L10_5("Pemfigus uzrokovan lijekovima", "L10.5"),
    L10_8("Ostali pemfigusi", "L10.8"),
    L10_9("Pemfigus, nespecificiran", "L10.9"),
    L11("Ostali akantolitični poremećaji", "L11"),
    L11_0("Stečena folikularna keratoza", "L11.0"),
    L11_1("Prolazna akantolitična dermatoza (Grover)", "L11.1"),
    L11_8("Ostali specificirani akantolitični poremećaji", "L11.8"),
    L11_9("Akantolitični poremećaj, nespecificiran", "L11.9"),
    L12("Pemfigoid", "L12"),
    L12_0("Pemfigoid bullosus", "L12.0"),
    L12_1("Cikatricijalni pemfigoid", "L12.1"),
    L12_2("Kronična bulozna bolest u djetinjstvu", "L12.2"),
    L12_3("Stečena bulozna epidermoliza", "L12.3"),
    L12_8("Ostali pemfigoidi", "L12.8"),
    L12_9("Pemfigoid, nespecificiran", "L12.9"),
    L13("Ostali bulozni poremećaji", "L13"),
    L13_0("Dermatitis herpetiformis", "L13.0"),
    L13_1("Supkornealni pustularni dermatitis", "L13.1"),
    L13_8("Ostali specificirani bulozni poremećaji", "L13.8"),
    L13_9("Bulozni poremećaj, nespecificiran", "L13.9"),
    L14("Bulozni poremećaji u bolestima svrstanim drugamo", "L14"),
    L14_0("Bulozni poremećaji u bolestima svrstanim drugamo", "L14.0"),
    L20("Atopični dermatitis", "L20"),
    L20_0("Prurigo Besnier", "L20.0"),
    L20_8("Ostali atopični dermatitisi", "L20.8"),
    L20_9("Atopični dermatitis, nespecificiran", "L20.9"),
    L21("Seboroični dermatitis", "L21"),
    L21_0("Seboreja glave", "L21.0"),
    L21_1("Seboroični dermatitis u djece", "L21.1"),
    L21_8("Ostali seboroični dermatitisi", "L21.8"),
    L21_9("Seboroični dermatitis, nespecificiran", "L21.9"),
    L22("Pelenski dermatitis", "L22"),
    L22_0("Pelenski dermatitis", "L22.0"),
    L23("Alergijski kontaktni dermatitis", "L23"),
    L23_0("Alergijski kontaktni dermatitis uzrokovan kovinama", "L23.0"),
    L23_1("Alergijski kontaktni dermatitis uzrokovan adhezivima", "L23.1"),
    L23_2("Alergijski kontaktni dermatitis uzrokovan kozmetičkim preparatima", "L23.2"),
    L23_3("Alergijski kontaktni dermatitis uzrokovan kontaktom kože s lijekovima", "L23.3"),
    L23_4("Alergijski kontaktni dermatitis uzrokovan bojama", "L23.4"),
    L23_5("Alergijski kontaktni dermatitis uzrokovan ostalim kemijskim tvarima", "L23.5"),
    L23_6("Alergijski kontaktni dermatitis uzrokovan kontaktom kože s hranom", "L23.6"),
    L23_7("Alergijski kontaktni dermatitis uzrokovan biljkama, koje se ne koriste kao hrana", "L23.7"),
    L23_8("Alergijski kontaktni dermatitis uzrokovan ostalim tvarima", "L23.8"),
    L23_9("Alergijski kontaktni dermatitis, nespecificiran", "L23.9"),
    L24("Iritantni kontaktni dermatitis", "L24"),
    L24_0("Iritantni kontaktni dermatitis uzrokovan deterdžentima", "L24.0"),
    L24_1("Iritantni kontaktni dermatitis uzrokovan uljima i mazivima", "L24.1"),
    L24_2("Iritantni kontaktni dermatitis uzrokovan otapalima", "L24.2"),
    L24_3("Iritantni kontaktni dermatitis uzrokovan kozmetičkim preparatima", "L24.3"),
    L24_4("Iritantni kontaktni dermatitis uzrokovan kontaktom kože s lijekovima", "L24.4"),
    L24_5("Iritantni kontaktni dermatitis uzrokovan ostalim kemijskim tvarima", "L24.5"),
    L24_6("Iritantni kontaktni dermatitis uzrokovan kontaktom kože s hranom", "L24.6"),
    L24_7("Iritantni kontaktni dermatitis uzrokovan biljkama, koje se ne koriste kao hrana", "L24.7"),
    L24_8("Iritantni kontaktni dermatitis uzrokovan ostalim čimbenicima", "L24.8"),
    L24_9("Iritantni kontaktni dermatitis, nespecificiran", "L24.9"),
    L25("Nespecificirani kontaktni dermatitis", "L25"),
    L25_0("Nespecificirani kontaktni dermatitis uzrokovan kozmetičkim preparatima", "L25.0"),
    L25_1("Nespecificirani kontaktni dermatitis uzrokovan dodirom kože s lijekovima", "L25.1"),
    L25_2("Nespecificirani kontaktni dermatitis uzrokovan bojama", "L25.2"),
    L25_3("Nespecificirani kontaktni dermatitis uzrokovan ostalim kemijskim tvarima", "L25.3"),
    L25_4("Nespecificirani kontaktni dermatitis uzrokovan kontaktom kože s hranom", "L25.4"),
    L25_5("Nespecificirani kontaktni dermatitis uzrokovan biljkama, koje se ne koriste kao hrana", "L25.5"),
    L25_8("Nespecificirani kontaktni dermatitis uzrokovan ostalim čimbenicima", "L25.8"),
    L25_9("Nespecificirani kontaktni dermatitis, neoznačena uzroka", "L25.9"),
    L26("Dermatitis exfoliativa", "L26"),
    L26_0("Dermatitis exfoliativa", "L26.0"),
    L27("Dermatitis uzrokovan tvarima uzetim interno", "L27"),
    L27_0("Generalizirani osip na koži uzrokovan lijekovima i medikamentima", "L27.0"),
    L27_1("Lokalizirani osip na koži uzrokovan lijekovima i medikamentima", "L27.1"),
    L27_2("Dermatitis uzrokovan konzumiranjem hrane", "L27.2"),
    L27_8("Dermatitis uzrokovan drugim tvarima uzetim interno", "L27.8"),
    L27_9("Dermatitis uzrokovan nespecificiranim tvarima uzetim interno", "L27.9"),
    L28("Lichen simplex chronicus i prurigo", "L28"),
    L28_0("Lichen simplex chronicus", "L28.0"),
    L28_1("Prurigo nodularis", "L28.1"),
    L28_2("Ostale vrste pruriga", "L28.2"),
    L29("Pruritus", "L29"),
    L29_0("Pruritus anusa", "L29.0"),
    L29_1("Pruritus skrotuma", "L29.1"),
    L29_2("Pruritus vulve", "L29.2"),
    L29_3("Anogenitalni pruritus, nespecificiran", "L29.3"),
    L29_8("Ostali pruritusi", "L29.8"),
    L29_9("Pruritus, nespecificiran", "L29.9"),
    L30("Ostali dermatitisi", "L30"),
    L30_0("Dermatitis nummularis", "L30.0"),
    L30_1("Dishidroza (pompholyx)", "L30.1"),
    L30_2("Autosenzibilizacija kože", "L30.2"),
    L30_3("Infektivni dermatitis", "L30.3"),
    L30_4("Erythema intertigo", "L30.4"),
    L30_5("Pityriasis alba", "L30.5"),
    L30_8("Ostali specificirani dermatitisi", "L30.8"),
    L30_9("Dermatitis, nespecificiran", "L30.9"),
    L40("Psorijaza", "L40"),
    L40_0("Psoriasis vulgaris", "L40.0"),
    L40_1("Generalizirana pustularna psorijaza", "L40.1"),
    L40_2("Akrodermatitis continua", "L40.2"),
    L40_3("Pustuloza dlanova i stopala", "L40.3"),
    L40_4("Psoriasis guttata", "L40.4"),
    L40_5("Psoriasis arthropatica (M07.0-M09.0*)", "L40.5"),
    L40_8("Ostale psorijaze", "L40.8"),
    L40_9("Psorijaza, nespecificirana", "L40.9"),
    L41("Parapsorijaza", "L41"),
    L41_0("Pityriasis lichenoides et varioliformis acuta", "L41.0"),
    L41_1("Pityriasis lichenoides chronica", "L41.1"),
    L41_2("Papulosis lymphomatoides", "L41.2"),
    L41_3("Parapsorijaza s malim plakovima", "L41.3"),
    L41_4("Parapsorijaza s velikim plakovima", "L41.4"),
    L41_5("Retiformna parapsorijaza", "L41.5"),
    L41_8("Ostale parapsorijaze", "L41.8"),
    L41_9("Parapsorijaza, nespecificirana", "L41.9"),
    L42("Pityriasis rosea", "L42"),
    L42_0("Pityriasis rosea", "L42.0"),
    L43("Lihen planus", "L43"),
    L43_0("Hipertrofični lihen planus", "L43.0"),
    L43_1("Bulozni lihen planus", "L43.1"),
    L43_2("Lihenoidna reakcija na lijekove", "L43.2"),
    L43_3("Subakutni (aktivni) lihen planus", "L43.3"),
    L43_8("Ostali lihen planus", "L43.8"),
    L43_9("Lihen planus, nespecificiran", "L43.9"),
    L44("Ostali papuloskavamozni poremećaji", "L44"),
    L44_0("Pityriasis rubra pilaris", "L44.0"),
    L44_1("Lichen nitidus", "L44.1"),
    L44_2("Lichen striatus", "L44.2"),
    L44_3("Lichen ruber moniliformis", "L44.3"),
    L44_4("Infantilni papulozni akrodermatitis (Giannotti-Crosti)", "L44.4"),
    L44_8("Ostali specificirani papuloskvamozni poremećaji", "L44.8"),
    L44_9("Papuloskvamozni poremećaj, nespecificiran", "L44.9"),
    L45("Papuloskvamozni poremećaji u bolestima svrstanim drugamo", "L45"),
    L45_0("Papuloskvamozni poremećaji u bolestima svrstanim drugamo", "L45.0"),
    L50("Urtikarija", "L50"),
    L50_0("Alergijska urtikarija", "L50.0"),
    L50_1("Idiopatska urtikarija", "L50.1"),
    L50_2("Urtikarija uzrokovana hladnoćom i vrućinom", "L50.2"),
    L50_3("Dermatografička urtikarija", "L50.3"),
    L50_4("Vibracijska urtikarija", "L50.4"),
    L50_5("Kolinergijska urtikarija", "L50.5"),
    L50_6("Kontaktna urtikarija", "L50.6"),
    L50_8("Ostale urtikarije", "L50.8"),
    L50_9("Urtikarija, nespecificirana", "L50.9"),
    L51("Erythema multiforme", "L51"),
    L51_0("Erythema non bullosum multiforme", "L51.0"),
    L51_1("Erythema bullosum multiforme", "L51.1"),
    L51_2("Toksična epidermalna nekroliza (Lyell)", "L51.2"),
    L51_8("Ostali erythema multiforme", "L51.8"),
    L51_9("Erythema multiforme, nespecificiran", "L51.9"),
    L52("Erythema nodosum", "L52"),
    L52_0("Erythema nodosum", "L52.0"),
    L53("Ostala eritematozna stanja", "L53"),
    L53_0("Toksični eritem", "L53.0"),
    L53_1("Erythema anulare centrifugum", "L53.1"),
    L53_2("Erythema marginatum", "L53.2"),
    L53_3("Ostali kronični figurirani eritemi", "L53.3"),
    L53_8("Ostala specificirana eritematozna stanja", "L53.8"),
    L53_9("Eritematozna stanja, nespecificirana", "L53.9"),
    L54("Eritem kod bolesti svrstanih drugamo", "L54"),
    L54_0("Erythema marginatum kod akutne reumatske groznice (I00)", "L54.0"),
    L54_8("Eritem kod ostalih bolesti svrstanih drugamo", "L54.8"),
    L55("Opekline uzrokovane suncem", "L55"),
    L55_0("Solarne opekline prvoga stupnja", "L55.0"),
    L55_1("Solarne opekline drugoga stupnja", "L55.1"),
    L55_2("Solarne opekline trećega stupnja", "L55.2"),
    L55_8("Ostale opekline uzrokovane suncem", "L55.8"),
    L55_9("Opekline uzrokovane suncem, nespecificirane", "L55.9"),
    L56("Ostale akutne promjene na koži uzrokovane ultraljubičastim zračenjem", "L56"),
    L56_0("Fototoksična reakcija na lijekove", "L56.0"),
    L56_1("Fotoalergijska reakcija na lijekove", "L56.1"),
    L56_2("Fotokontaktni dermatitis (berloque dermatitis)", "L56.2"),
    L56_3("Solarna urtikarija", "L56.3"),
    L56_4("Polimorfni osip uzrokovan svjetlom", "L56.4"),
    L56_8("Ostale specificirane akutne promjene na koži uzrokovane ultraljubičastim zračenjem", "L56.8"),
    L56_9("Akutne promjene na koži uzrokovane ultraljubičastim zračenjem, nespecificirane", "L56.9"),
    L57("Promjene kože uzrokovane dugotrajnom izloženošću neionizirajućem zračenju", "L57"),
    L57_0("Aktinična keratoza", "L57.0"),
    L57_1("Aktinični retikuloid", "L57.1"),
    L57_2("Cutis rhomboidalis nuchae", "L57.2"),
    L57_3("Poikiloderma Civatte", "L57.3"),
    L57_4("Cutis laxa senilis", "L57.4"),
    L57_5("Aktinični granulom", "L57.5"),
    L57_8("Ostale promjene kože uzrokovane dugotrajnom izloženošću neionizirajućem zračenju", "L57.8"),
    L57_9("Promjene kože uzrokovane dugotrajnom izloženošću neionizirajućem zračenju, nespecificirane", "L57.9"),
    L58("Radiodermatitis", "L58"),
    L58_0("Akutni radiodermatitis", "L58.0"),
    L58_1("Kronični radiodermatitis", "L58.1"),
    L58_9("Radiodermatitis, nespecificiran", "L58.9"),
    L59("Ostali poremećaji kože i potkožnoga tkiva u vezi sa zračenjem", "L59"),
    L59_0("Erythema ab igne (dermatitis ab igne)", "L59.0"),
    L59_8("Ostali specificirani poremećaji kože i potkožnoga tkiva u vezi sa zračenjem", "L59.8"),
    L59_9("Poremećaji kože i potkožnoga tkiva u vezi sa zračenjem, nespecificirani", "L59.9"),
    L60("Poremećaji noktiju", "L60"),
    L60_0("Urašteni nokti", "L60.0"),
    L60_1("Oniholiza", "L60.1"),
    L60_2("Onihogrifoza", "L60.2"),
    L60_3("Distrofija noktiju", "L60.3"),
    L60_4("Beauove brazde", "L60.4"),
    L60_5("Sindrom žutih noktiju", "L60.5"),
    L60_8("Ostali poremećaji noktiju", "L60.8"),
    L60_9("Poremećaji noktiju, nespecificirani", "L60.9"),
    L62("Poremećaji noktiju kod bolesti svrstanih drugamo", "L62"),
    L62_0("Batićasti nokti kod pahidermoperiostose (M89.4)", "L62.0"),
    L62_8("Poremećaji noktiju kod ostalih bolesti svrstanih drugamo", "L62.8"),
    L63("Alopecija areata", "L63"),
    L63_0("Alopecija (glave) totalna", "L63.0"),
    L63_1("Alopecija univerzalna", "L63.1"),
    L63_2("Ofijaza", "L63.2"),
    L63_8("Ostale alopecije areate", "L63.8"),
    L63_9("Alopecija areata, nespecificirana", "L63.9"),
    L64("Androgena alopecija", "L64"),
    L64_0("Androgena alopecija uzrokovana lijekovima", "L64.0"),
    L64_8("Ostale androgene alopecije", "L64.8"),
    L64_9("Androgena alopecija, nespecificirana", "L64.9"),
    L65("Ostalo ispadanje kose bez ožiljaka", "L65"),
    L65_0("Telogeni efluvij vlasi", "L65.0"),
    L65_1("Anageni efluvij vlasi", "L65.1"),
    L65_2("Mucinozna alopecija", "L65.2"),
    L65_8("Ostalo specificirano ispadanje kose bez ožiljaka", "L65.8"),
    L65_9("Ispadanje kose bez ožiljaka, nespecificirano", "L65.9"),
    L66("Cikatricijalna alopecija (ispadanje kose s ožiljcima)", "L66"),
    L66_0("Pseudopelade Brocq", "L66.0"),
    L66_1("Lichen planopilaris", "L66.1"),
    L66_2("Folliculitis decalvans", "L66.2"),
    L66_3("Perifolliculitis capitis abscedens", "L66.3"),
    L66_4("Folliculitis ulerythematosa reticulata", "L66.4"),
    L66_8("Ostale cikatricijalne alopecije", "L66.8"),
    L66_9("Cikatricijalna alopecija, nespecificirana", "L66.9"),
    L67("Abnormalnosti boje kose i stabljike vlasi", "L67"),
    L67_0("Trichorrhexis nodosa", "L67.0"),
    L67_1("Varijacije u boji kose", "L67.1"),
    L67_8("Ostale abnormalnosti boje kose i stabljike vlasi", "L67.8"),
    L67_9("Abnormalnosti boje kose i stabljike vlasi, nespecificirane", "L67.9"),
    L68("Hipertrihoza", "L68"),
    L68_0("Hirzutizam", "L68.0"),
    L68_1("Hypertrichosis lanuginosa aquisita", "L68.1"),
    L68_2("Lokalizirana hipertrihoza", "L68.2"),
    L68_3("Politrihija", "L68.3"),
    L68_8("Ostale hipertrihoze", "L68.8"),
    L68_9("Hipertrihoza, nespecificirana", "L68.9"),
    L70("Akne", "L70"),
    L70_0("Acne vulgaris", "L70.0"),
    L70_1("Acne conglobata", "L70.1"),
    L70_2("Acne varioliformis", "L70.2"),
    L70_3("Acne tropica", "L70.3"),
    L70_4("Infantilne akne", "L70.4"),
    L70_5("Mladenačke akne", "L70.5"),
    L70_8("Ostale akne", "L70.8"),
    L70_9("Akne, nespecificirane", "L70.9"),
    L71("Rozaceja", "L71"),
    L71_0("Perioralni dermatitis", "L71.0"),
    L71_1("Rinofima", "L71.1"),
    L71_8("Ostale rozaceje", "L71.8"),
    L71_9("Rozaceja, nespecificirana", "L71.9"),
    L72("Folikularne ciste kože i potkožnoga tkiva", "L72"),
    L72_0("Epidermalna cista", "L72.0"),
    L72_1("Cystis trichilemmalis", "L72.1"),
    L72_2("Steatocystoma multiplex", "L72.2"),
    L72_8("Ostale folikularne ciste kože i potkožnoga tkiva", "L72.8"),
    L72_9("Folikularne ciste kože i potkožnoga tkiva, nespecificirane", "L72.9"),
    L73("Ostali folikularni poremećaji", "L73"),
    L73_0("Akne keloid", "L73.0"),
    L73_1("Pseudofolikulitis brade", "L73.1"),
    L73_2("Hidradenitis suppurativa", "L73.2"),
    L73_8("Ostali specificirani folikularni poremećaji", "L73.8"),
    L73_9("Folikularni poremećaj, nespecificiran", "L73.9"),
    L74("Poremećaji žlijezda znojnica", "L74"),
    L74_0("Miliaria rubra", "L74.0"),
    L74_1("Miliaria cristallina", "L74.1"),
    L74_2("Miliaria profunda", "L74.2"),
    L74_3("Miliaria, nespecificirana", "L74.3"),
    L74_4("Anhidroza", "L74.4"),
    L74_8("Ostali poremećaji žlijezda znojnica", "L74.8"),
    L74_9("Poremećaji žlijezda znojnica, nespecificirani", "L74.9"),
    L75("Poremećaji apokrinih žlijezda znojnica", "L75"),
    L75_0("Bromhidroza", "L75.0"),
    L75_1("Kromhidroza", "L75.1"),
    L75_2("Apokrina miliarija", "L75.2"),
    L75_8("Ostali poremećaji apokrinih žlijezda znojnica", "L75.8"),
    L75_9("Poremećaj apokrinih žlijezda znojnica, nespecificiran", "L75.9"),
    L80("Vitiligo", "L80"),
    L80_0("Vitiligo", "L80.0"),
    L81("Ostali poremećaji pigmentacije", "L81"),
    L81_0("Postinflamatorna hiperpigmentacija", "L81.0"),
    L81_1("Chloasma", "L81.1"),
    L81_2("Pjege (ephelides)", "L81.2"),
    L81_3("Pjege cafe au lait (pjege boje bijele kave)", "L81.3"),
    L81_4("Ostale melaninske hiperpigmentacije", "L81.4"),
    L81_5("Leukoderma, nesvrstana drugamo", "L81.5"),
    L81_6("Ostali poremećaji smanjena stvaranja melanina", "L81.6"),
    L81_7("Pigmentirana purpurična dermatoza", "L81.7"),
    L81_8("Ostali specificirani poremećaji pigmentacije", "L81.8"),
    L81_9("Poremećaj pigmentacije, nespecificiran", "L81.9"),
    L82("Keratosis seborrhoeica", "L82"),
    L82_0("Keratosis seborrhoeica", "L82.0"),
    L83("Acanthosis nigricans", "L83"),
    L83_0("Acanthosis nigricans", "L83.0"),
    L84("Kurje oči i žuljevi", "L84"),
    L84_0("Kurje oči i žuljevi", "L84.0"),
    L85("Ostala epidermalna zadebljanja", "L85"),
    L85_0("Stečena ihtioza", "L85.0"),
    L85_1("Stečena keratoza (keratodermija) dlanova i tabana", "L85.1"),
    L85_2("Keratosis punctata (dlanova i tabana)", "L85.2"),
    L85_3("Xerosis cutis", "L85.3"),
    L85_8("Ostala specificirana epidermalna zadebljanja", "L85.8"),
    L85_9("Epidermalna zadebljanja, nespecificirana", "L85.9"),
    L86("Keratodermija u bolestima svrstanim drugamo", "L86"),
    L86_0("Keratodermija u bolestima svrstanim drugamo", "L86.0"),
    L87("Poremećaji nastali zbog transepidermalne eliminacije", "L87"),
    L87_0("Keratosis follicullaris et parafollicularis in cutem penetrans (Kyrle)", "L87.0"),
    L87_1("Reaktivna perforativna kolagenoza", "L87.1"),
    L87_2("Elastosis perforans serpiginosa", "L87.2"),
    L87_8("Ostali poremećaji transepidermalne eliminacije", "L87.8"),
    L87_9("Poremećaj transepidermalne eliminacije, nespecificiran", "L87.9"),
    L88("Pyoderma gangrenosum", "L88"),
    L88_0("Pyoderma gangrenosum", "L88.0"),
    L89("Dekubitalni ulkus", "L89"),
    L89_0("Dekubitalni ulkus", "L89.0"),
    L90("Atrofični poremećaji kože", "L90"),
    L90_0("Lichen sclerosus et atrophicus", "L90.0"),
    L90_1("Schweninger-Buzzijeva anetodermija", "L90.1"),
    L90_2("Jadassohn-Pellizzarijeva anetodermija", "L90.2"),
    L90_3("Passinijeva i Pierinijeva atrofodermija", "L90.3"),
    L90_4("Acrodermatitis chronica atrophicans", "L90.4"),
    L90_5("Ožiljci i fibroza kože", "L90.5"),
    L90_6("Striae atrohpicae", "L90.6"),
    L90_8("Ostali atrofični poremećaji kože", "L90.8"),
    L90_9("Atrofični poremećaj kože, nespecificiran", "L90.9"),
    L91("Hipertrofični poremećaji kože", "L91"),
    L91_0("Keloidni ožiljak", "L91.0"),
    L91_8("Ostali hipertrofični poremećaji kože", "L91.8"),
    L91_9("Hipertrofični poremećaj kože, nespecificiran", "L91.9"),
    L92("Granulomatozni poremećaji kože i potkožnoga tkiva", "L92"),
    L92_0("Granuloma anulare", "L92.0"),
    L92_1("Necrobiosis lipoidica, nesvrstan drugamo", "L92.1"),
    L92_2("Granuloma faciei (eozinofilni granulom kože)", "L92.2"),
    L92_3("Granulom uzrokovan stranim tijelom u koži i potkožnome tkivu", "L92.3"),
    L92_8("Ostali granulomatozni poremećaji kože i potkožnoga tkiva", "L92.8"),
    L92_9("Granulomatozni poremećaj kože i potkožnoga tkiva, nespecificiran", "L92.9"),
    L93("Lupus erythematodes", "L93"),
    L93_0("Lupus erythematodes discoides", "L93.0"),
    L93_1("Subakutni kožni lupus eritematodes", "L93.1"),
    L93_2("Ostali lokalni lupus eritematodes", "L93.2"),
    L94("Ostali lokalizirani poremećaji vezivnog tkiva", "L94"),
    L94_0("Lokalizirana sklerodermija (morphea)", "L94.0"),
    L94_1("Sclerodermia linearis", "L94.1"),
    L94_2("Calcinosis cutis", "L94.2"),
    L94_3("Sklerodaktilija", "L94.3"),
    L94_4("Gottronove papule", "L94.4"),
    L94_5("Poikiloderma vasculare atrophicans", "L94.5"),
    L94_6("Ainhum", "L94.6"),
    L94_8("Ostali specificirani lokalizirani poremećaji vezivnog tkiva", "L94.8"),
    L94_9("Lokalizirani poremećaji vezivnog tkiva, nespecificirani", "L94.9"),
    L95("Vaskulitis ograničen na kožu, nesvrstan drugamo", "L95"),
    L95_0("Livedoidni vaskulitis", "L95.0"),
    L95_1("Erythema elevatum diutinum", "L95.1"),
    L95_8("Ostali vaskulitisi ograničeni na kožu", "L95.8"),
    L95_9("Vaskulitis ograničen na kožu, nespecificiran", "L95.9"),
    L97("Ulkus nogu nesvrstan drugamo", "L97"),
    L97_0("Ulkus nogu nesvrstan drugamo", "L97.0"),
    L98("Ostali poremećaji kože i potkožnoga tkiva nesvrstani drugamo", "L98"),
    L98_0("Piogeni granulom", "L98.0"),
    L98_1("Artificijalni dermatitis", "L98.1"),
    L98_2("Febrilna neutrofilna dermatoza (Sweet)", "L98.2"),
    L98_3("Eozinofilni celulitis (Wells)", "L98.3"),
    L98_4("Kronični ulkus kože, nesvrstan drugamo", "L98.4"),
    L98_5("Mucinoza kože", "L98.5"),
    L98_6("Ostali infiltrativni poremećaji kože i potkožnoga tkiva", "L98.6"),
    L98_8("Ostali specificirani poremećaji kože i potkožnoga tkiva", "L98.8"),
    L98_9("Poremećaji kože i potkožnoga tkiva, nespecificirani", "L98.9"),
    L99("Ostali poremećaji kože i potkožnoga tkiva kod bolesti svrstanih drugamo", "L99"),
    L99_0("Amiloidoza kože (E85.-)", "L99.0"),
    L99_8("Ostali specificirani poremećaji kože i potkožnoga tkiva kod bolesti svrstanih drugamo", "L99.8");
    
    private final String displayName;
    private final String code;
    
    MkbCodesL(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
