package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesK {
    
    K00("Poremećaji u razvoju i nicanju zubi", "K00"),
    K00_0("Anodoncija", "K00.0"),
    K00_1("Prekobrojni zubi", "K00.1"),
    K00_2("Abnormalnosti u veličini i obliku zubi", "K00.2"),
    K00_3("Pjegavi zubi", "K00.3"),
    K00_4("Poremećaji u oblikovanju zuba", "K00.4"),
    K00_5("Hereditarni poremećaji u strukturi zuba, nesvrstani drugamo", "K00.5"),
    K00_6("Poremećaji u nicanju zuba", "K00.6"),
    K00_7("Sindrom izbijanja (nicanja) zubi", "K00.7"),
    K00_8("Ostali poremećaji razvoja zubi", "K00.8"),
    K00_9("Poremećaj razvoja zuba, nespecificiran", "K00.9"),
    K01("Zadržani (retinirani) i ukliješteni (impaktirani) zubi", "K01"),
    K01_0("Zadržani (retinirani) zubi", "K01.0"),
    K01_1("Ukliješteni (impaktirani) zubi", "K01.1"),
    K02("Zubni karijes", "K02"),
    K02_0("Karijes ograničen na caklinu", "K02.0"),
    K02_1("Karijes dentina", "K02.1"),
    K02_2("Karijes cementa", "K02.2"),
    K02_3("Zaustavljen zubni karijes", "K02.3"),
    K02_4("Odontoklazija", "K02.4"),
    K02_8("Drugi zubni karijes", "K02.8"),
    K02_9("Zubni karijes, nespecificiran", "K02.9"),
    K03("Ostale bolesti čvrstoga zubnoga tkiva", "K03"),
    K03_0("Prekomjerna istrošenost zubi", "K03.0"),
    K03_1("Abrazija zubi", "K03.1"),
    K03_2("Erozija zubi", "K03.2"),
    K03_3("Patološka resorpcija zubi", "K03.3"),
    K03_4("Hipercementoza", "K03.4"),
    K03_5("Ankiloza zubi", "K03.5"),
    K03_6("Odlaganja (naslage) na zubima", "K03.6"),
    K03_7("Promjene boje čvrstoga tkiva nakon nicanja zubi", "K03.7"),
    K03_8("Ostale specificirane bolesti čvrstoga zubnoga tkiva", "K03.8"),
    K03_9("Bolest čvrstoga zubnoga tkiva, nespecificirana", "K03.9"),
    K04("Bolesti pulpe i periapikalnih tkiva", "K04"),
    K04_0("Upale pulpe (pulpitis)", "K04.0"),
    K04_1("Nekroza pulpe", "K04.1"),
    K04_2("Degeneracija pulpe", "K04.2"),
    K04_3("Abnormalno oblikovanje tvrdoga tkiva u pulpi", "K04.3"),
    K04_4("Akutna upala apikalnog periodonta pulparnog podrijetla", "K04.4"),
    K04_5("Kronična upala apikalnog periodonta", "K04.5"),
    K04_6("Periapikalni apsces sa sinusom", "K04.6"),
    K04_7("Periapikalni apsces bez sinusa", "K04.7"),
    K04_8("Radikularna cista", "K04.8"),
    K04_9("Ostale i nespecificirane bolesti pulpe i periapikalnih tkiva", "K04.9"),
    K05("Gingivitis i periodontalne bolesti", "K05"),
    K05_0("Akutna upala gingive (akutni gingivitis)", "K05.0"),
    K05_1("Kronična upala gingive (kronični gingivitis)", "K05.1"),
    K05_2("Akutna upala periodonta (akutni periodontitis)", "K05.2"),
    K05_3("Kronična upala periodonta (kronični periodontitis)", "K05.3"),
    K05_4("Periodontoza (parodontoza)", "K05.4"),
    K05_5("Ostale periodontalne bolesti", "K05.5"),
    K05_6("Bolest periodonta, nespecificirana", "K05.6"),
    K06("Ostali poremećaji gingive i bezuboga alveolarnog grebena", "K06"),
    K06_0("Povlačenje gingive", "K06.0"),
    K06_1("Povećanje gingive", "K06.1"),
    K06_2("Oštećenje gingive i bezuboga alveolarnog grebena udruženo s traumom", "K06.2"),
    K06_8("Ostali specificirani poremećaji gingive i bezuboga alveolarnog grebena", "K06.8"),
    K06_9("Poremećaj gingive i bezuboga alveolarnog grebena, nespecifiran", "K06.9"),
    K07("Dentofacijalne nepravilnosti (uključujući malokluziju)", "K07"),
    K07_0("Veće nepravilnosti veličine čeljusti", "K07.0"),
    K07_1("Nepravilnosti u odnosu između čeljusti i baze lubanje", "K07.1"),
    K07_2("Nepravilnosti u odnosu zubnog luka (svoda)", "K07.2"),
    K07_3("Nepravilnosti u položaju zubi", "K07.3"),
    K07_4("Malokluzija, nespecificirana", "K07.4"),
    K07_5("Dentofacijalne funkcionalne abnormalnosti", "K07.5"),
    K07_6("Promjene temporomandibularnoga zgloba", "K07.6"),
    K07_8("Ostale dentofacijalne nepravilnosti", "K07.8"),
    K07_9("Dentofacijalna nepravilnost, nespecificirana", "K07.9"),
    K08("Ostali poremećaji zubi i potpornih struktura", "K08"),
    K08_0("Gubitak zubi zbog organskih uzroka", "K08.0"),
    K08_1("Gubitak zubi zbog nesretnoga slučaja, vađenja ili lokalne periodontalne bolesti", "K08.1"),
    K08_2("Atrofija bezuboga alveolarnog grebena", "K08.2"),
    K08_3("Zaostali zubni korijen", "K08.3"),
    K08_8("Ostale specificirane promjene zubi i potpornih struktura", "K08.8"),
    K08_9("Poremećaj zubi i potpornih struktura, nespecificiran", "K08.9"),
    K09("Ciste oralnog područja koje nisu svrstane drugamo", "K09"),
    K09_0("Razvojne odontogene ciste", "K09.0"),
    K09_1("Razvojne (neodontogene) ciste oralnog područja", "K09.1"),
    K09_2("Ostale ciste čeljusti", "K09.2"),
    K09_8("Ostale ciste oralnog područja, nesvrstane drugamo", "K09.8"),
    K09_9("Cista oralnog područja, nespecificirana", "K09.9"),
    K10("Ostale bolesti čeljusti", "K10"),
    K10_0("Poremećaji razvoja česljusti", "K10.0"),
    K10_1("Granulom divovskih stanica (gigantocelularni granulom), centralni", "K10.1"),
    K10_2("Upalna stanja čeljusti", "K10.2"),
    K10_3("Alveolitis čeljusti", "K10.3"),
    K10_8("Ostale specificirane bolesti čeljusti", "K10.8"),
    K10_9("Bolest čeljusti, nespecificirana", "K10.9"),
    K11("Bolesti žlijezda slinovnica", "K11"),
    K11_0("Atrofija žlijezde slinovnice", "K11.0"),
    K11_1("Hipertrofija žlijezde slinovnice", "K11.1"),
    K11_2("Sijaloadenitis", "K11.2"),
    K11_3("Apsces žlijezde slinovnice", "K11.3"),
    K11_4("Fistula žlijezde slinovnice", "K11.4"),
    K11_5("Sijalolitijaza", "K11.5"),
    K11_6("Mukokela žlijezde slinovnice", "K11.6"),
    K11_7("Poremećaji žljezdane sekrecije", "K11.7"),
    K11_8("Ostale bolesti žlijezda slinovnica", "K11.8"),
    K11_9("Bolest žlijezde slinovnice, nespecificirana", "K11.8"),
    K12("Stomatitis i srodna oštećenja", "K12"),
    K12_0("Povratne (rekurentne) afte", "K12.0"),
    K12_1("Ostali oblici stomatitisa", "K12.1"),
    K12_2("Celulitis i apsces usne šupljine", "K12.2"),
    K13("Ostale bolesti usana i oralne sluznice", "K13"),
    K13_0("Bolesti usana", "K13.0"),
    K13_1("Griženje obraza i usne", "K13.1"),
    K13_2("Leukoplakija i ostali poremećaji oralnog epitela, uključujući i jezik", "K13.2"),
    K13_3("Dlakava leukoplakija", "K13.3"),
    K13_4("Granulom i granulomu slična oštećenja oralne sluznice", "K13.4"),
    K13_5("Oralna submukozna fibroza", "K13.5"),
    K13_6("Nadražajna hiperplazija oralne sluznice", "K13.6"),
    K13_7("Ostala i nespecificirana oštećenja oralne sluznice", "K13.7"),
    K14("Bolesti jezika", "K14"),
    K14_0("Glositis", "K14.0"),
    K14_1("Geografski jezik", "K14.1"),
    K14_2("Romboidni središnji glositis (glositis rhombica mediana)", "K14.2"),
    K14_3("Hipertrofija jezičnih papila", "K14.3"),
    K14_4("Atrofija jezičnih papila", "K14.4"),
    K14_5("Naborani jezik", "K14.5"),
    K14_6("Glosodinija", "K14.6"),
    K14_8("Ostale bolesti jezika", "K14.8"),
    K14_9("Bolest jezika, nespecificirana", "K14.9"),
    K20("Upala jednjaka (ezofagitis)", "K20"),
    K20_0("Upala jednjaka (ezofagitis)", "K20.0"),
    K21("Gastroezofagealni refluks", "K21"),
    K21_0("Gastroezofagealni refluks s ezofagitisom", "K21.0"),
    K21_9("Gastroezofagealni refluks bez ezofagitisa", "K21.9"),
    K22("Ostale bolesti jednjaka", "K22"),
    K22_0("Ahalazija kardije", "K22.0"),
    K22_1("Vrijed jednjaka (ulcus oesophagi)", "K22.1"),
    K22_2("Opstrukcija jednjaka", "K22.2"),
    K22_3("Perforacija jednjaka", "K22.3"),
    K22_4("Diskinezija jednjaka", "K22.4"),
    K22_5("Divertikul jednjaka, stečeni", "K22.5"),
    K22_6("Gastroezofagealni laceracijsko-hemoragijski sindrom", "K22.6"),
    K22_8("Ostale specificirane bolesti jednjaka", "K22.8"),
    K22_9("Bolest jednjaka, nespecificirana", "K22.9"),
    K23("Bolesti i poremećaji jednjaka kod bolesti svrstanih drugamo", "K23"),
    K23_0("Tuberkulozni ezofagitis (A18.8)", "K23.0"),
    K23_1("Megaezofagus kod Chagasove bolesti (B57.3)", "K23.1"),
    K23_8("Bolesti jednjaka kod ostalih bolesti svrstanih drugamo", "K23.8"),
    K25("Vrijed želuca (ulcus ventriculi)", "K25"),
    K25_0("Vrijed želuca (ulcus ventriculi)", "K25.0"),
    K26("Vrijed dvanaesnika (ulcus duodeni)", "K26"),
    K26_0("Vrijed dvanaesnika (ulcus duodeni)", "K26.0"),
    K27("Peptični vrijed, nespecificiranog mjesta (ulcus pepticum)", "K27"),
    K27_0("Peptični vrijed, nespecificiranog mjesta (ulcus pepticum)", "K27.0"),
    K28("Gastrojejunalni vrijed (ulcus gastrojejunalis)", "K28"),
    K28_0("Gastrojejunalni vrijed (ulcus gastrojejunalis)", "K28.0"),
    K29("Gastritis i duodenitis", "K29"),
    K29_0("Akutni hemoragijski gastritis", "K29.0"),
    K29_1("Drugi akutni gastritis", "K29.1"),
    K29_2("Gastritis uzrokovan alkoholom", "K29.2"),
    K29_3("Kronični superficijalni gastritis", "K29.3"),
    K29_4("Kronični atrofični gastritis", "K29.4"),
    K29_5("Kronični gastritis, nespecificiran", "K29.5"),
    K29_6("Drugi gastritisi", "K29.6"),
    K29_7("Gastritis, nespecificiran", "K29.7"),
    K29_8("Duodenitis", "K29.8"),
    K29_9("Gastroduodenitis, nespecificiran", "K29.9"),
    K30("Dispepsija", "K30"),
    K30_0("Dispepsija", "K30.0"),
    K31("Ostale bolesti želuca i dvanaesnika", "K31"),
    K31_0("Akutno proširenje (dilatacija) želuca", "K31.0"),
    K31_1("Hipertrofična pilorična stenoza u odraslih osoba", "K31.1"),
    K31_2("Striktura i stenoza želuca u obliku pješčanog sata", "K31.2"),
    K31_3("Pilorospazam, nesvrstan drugamo", "K31.2"),
    K31_4("Divertikul želuca", "K31.4"),
    K31_5("Opstrukcija dvanaesnika", "K31.5"),
    K31_6("Fistula želuca i dvanaesnika", "K31.6"),
    K31_8("Ostale specificirane bolesti želuca i dvanaesnika", "K31.8"),
    K31_9("Bolest želuca i dvanaesnika, nespecificirana", "K31.9"),
    K35("Akutna upala crvuljka (apendicitis)", "K35"),
    K35_0("Akutna upala crvuljka (apendicitis) s generaliziranom upalom potrbušnice", "K35.0"),
    K35_1("Akutna upala crvuljka s apscesom potrbušnice", "K35.1"),
    K35_9("Akutna upala crvuljka, nespecificirana", "K35.9"),
    K36("Druga upala crvuljka", "K36"),
    K36_0("Druga upala crvuljka", "K36.0"),
    K37("Nespecificirana upala crvuljka", "K37"),
    K37_0("Nespecificirana upala crvuljka", "K37.0"),
    K38("Ostale bolesti crvuljka", "K38"),
    K38_0("Hiperplazija apendiksa", "K38.0"),
    K38_1("Konkrementi apendiksa", "K38.1"),
    K38_2("Divertikul apendiksa", "K38.2"),
    K38_3("Fistula apendiksa", "K38.3"),
    K38_8("Ostale specificirane bolesti crvuljka", "K38.8"),
    K38_9("Bolest crvuljka, nespecificirana", "K38.9"),
    K40("Preponska kila (ingvinalna hernija)", "K40"),
    K40_0("Obostrana preponska kila s opstrukcijom, bez gangrene", "K40.0"),
    K40_1("Obostrana preponska kila s gangrenom", "K40.1"),
    K40_2("Obostrana preponska kila bez opstrukcije ili gangrene", "K40.2"),
    K40_3("Jednostrana ili nespecificirana preponska kila s opstrukcijom, bez gangrene", "K40.3"),
    K40_4("Jednostrana ili nespecificirana preponska kila s gangrenom", "K40.4"),
    K40_9("Jednostrana ili nespecificirana preponska kila bez opstrukcije ili gangrene", "K40.9"),
    K41("Bedrena kila (femoralna hernija)", "K41"),
    K41_0("Obostrana femoralna hernija s opstrukcijom, bez gangrene", "K41.0"),
    K41_1("Obostrana femoralna hernija s gangrenom", "K41.1"),
    K41_2("Obostrana femoralna hernija bez opstrukcije ili gangrene", "K41.2"),
    K41_3("Jednostrana ili nespecificirana femoralna hernija s opstrukcijom, bez gangrene", "K41.3"),
    K41_4("Jednostrana ili nespecificirana femoralna hernija s gangrenom", "K41.4"),
    K41_9("Jednostrana ili nespecificirana femoralna hernija bez opstrukcije ili gangrene", "K41.9"),
    K42("Pupčana kila (umbilikalna hernija)", "K42"),
    K42_0("Pupčana kila s opstrukcijom, bez gangrene", "K42.0"),
    K42_1("Pupčana kila s gangrenom", "K42.1"),
    K42_9("Pupčana kila bez opstrukcije ili gangrene", "K42.9"),
    K43("Trbušna kila (ventralna hernija)", "K43"),
    K43_0("Trbušna kila s opstrukcijom, bez gangrene", "K43.0"),
    K43_1("Trbušna kila s gangrenom", "K43.1"),
    K43_9("Trbušna kila bez opstrukcije ili gangrene", "K43.9"),
    K44("Ošitna kila (dijafragmalna hernija)", "K44"),
    K44_0("Dijafragmalna hernija s opstrukcijom bez gangrene", "K44.0"),
    K44_1("Dijafragmalna hernija s gangrenom", "K44.1"),
    K44_9("Dijafragmalna hernija bez opstrukcije ili gangrene", "K44.9"),
    K45("Ostale kile trbušne šupljine", "K45"),
    K45_0("Ostale specificirane kile trbušne šupljine s opstrukcijom, bez gangrene", "K45.0"),
    K45_1("Ostale specificirane kile trbušne šupljine s gangrenom", "K45.1"),
    K45_8("Ostale specificirane kile trbušne šupljine bez opstrukcije ili gangrene", "K45.8"),
    K46("Nespecificirana kila trbušne šupljine", "K46"),
    K46_0("Nespecificirana kila trbušne šupljine s opstrukcijom bez gangrene", "K46.0"),
    K46_1("Nespecificirana kila trbušne šupljine s gangrenom", "K46.1"),
    K46_9("Nespecificirana kila trbušne šupljine bez opstrukcije ili gangrene", "K46.9"),
    K50("Crohnova bolest (regionalni entritis)", "K50"),
    K50_0("Crohnova bolest tankog crijeva", "K50.0"),
    K50_1("Crohnova bolest debelog crijeva", "K50.1"),
    K50_8("Crohnova bolest, ostalo", "K50.8"),
    K50_9("Crohnova bolest, nespecificirana", "K50.9"),
    K51("Ulcerozni kolitis", "K51"),
    K51_0("Ulcerozni (kronični) enterokolitis", "K51.0"),
    K51_1("Ulcerozni (kronični) ileokolitis", "K51.1"),
    K51_2("Ulcerozni (kronični) proktitis", "K51.2"),
    K51_3("Ulcerozni (kronični) rektosigmoiditis", "K51.3"),
    K51_4("Pseudopolipoza kolona", "K51.4"),
    K51_5("Mukozni proktokolitis", "K51.5"),
    K51_8("Ulcerozni kolitis, ostalo", "K51.8"),
    K51_9("Ulcerozni kolitis, nespecificiran", "K51.9"),
    K52("Druge neinfektivne upale tankoga i debeloga crijeva", "K52"),
    K52_0("Gastroenteritis i kolitis uzrokovan zračenjem", "K52.0"),
    K52_1("Toksični gastroenteritis i kolitis", "K52.1"),
    K52_2("Alergijski i dijetetski gastroenteritis i kolitis", "K52.2"),
    K52_8("Ostali specificirani neinfektivni gastroenteritisi i kolitisi", "K52.8"),
    K52_9("Neinfektivni gastroenteritis i kolitis, nespecificiran", "K52.9"),
    K55("Poremećaj crijevnih žila", "K55"),
    K55_0("Akutni poremećaji crijevnih žila", "K55.0"),
    K55_1("Kronični poremećaji crijevnih žila", "K55.1"),
    K55_2("Angiodisplazija kolona", "K55.2"),
    K55_8("Ostali poremećaji crijevnih žila", "K55.8"),
    K55_9("Poremećaj crijevnih žila, nespecificiran", "K55.9"),
    K56("Paralitični ileus i opstrukcija crijeva bez hernije", "K56"),
    K56_0("Paralitični ileus", "K56.0"),
    K56_1("Intususcepcija", "K56.1"),
    K56_2("Volvulus", "K56.2"),
    K56_3("Ileus uzrokovan žučnim kamencem", "K56.3"),
    K56_4("Ostala uklještenja crijeva", "K56.4"),
    K56_5("Priraslice crijeva s opstrukcijom", "K56.5"),
    K56_6("Ostale i nespecificirane opstrukcije crijeva", "K56.6"),
    K56_7("Ileus, nespecificiran", "K56.7"),
    K57("Divertikuloza crijeva", "K57"),
    K57_0("Divertikuloza tankoga crijeva s perforacijom i apscesom", "K57.0"),
    K57_1("Divertikuloza tankoga crijeva bez perforacije ili apscesa", "K57.1"),
    K57_2("Divertikuloza debeloga crijeva s perforacijom i apscesom", "K57.2"),
    K57_3("Divertikuloza debeloga crijeva bez perforacije ili apscesa", "K57.3"),
    K57_4("Divertikuloza i tankoga i debeloga crijeva s perforacijom i apscesom", "K57.4"),
    K57_5("Divertikuloza i tankoga i debeloga crijeva bez perforacije ili apscesa", "K57.5"),
    K57_8("Divertikuloza nespecificiranog dijela crijeva, s perforacijom i apscesom", "K57.8"),
    K57_9("Divertikuloza nespecificiranog dijela crijeva, bez perforacije ili apscesa", "K57.9"),
    K58("Sindrom iritabilnoga crijeva", "K58"),
    K58_0("Sindrom iritabilnoga crijeva s proljevom", "K58.0"),
    K58_9("Sindrom iritabilnoga crijeva bez proljeva", "K58.9"),
    K59("Ostali funkcionalni poremećaji crijeva", "K59"),
    K59_0("Konstipacija", "K59.0"),
    K59_1("Funkcionalni proljev (dijareja)", "K59.1"),
    K59_2("Neurogeno crijevo, nesvrstano drugamo", "K59.2"),
    K59_3("Megakolon, nesvrstan drugamo", "K59.3"),
    K59_4("Analni spazam", "K59.4"),
    K59_8("Ostali specificirani funkcionalni poremećaji crijeva", "K59.8"),
    K59_9("Funkcionalni poremećaj crijeva, nespecificiran", "K59.9"),
    K60("Fisure i fistule analnog i rektalnog područja", "K60"),
    K60_0("Akutna analna fisura", "K60.0"),
    K60_1("Kronična analna fisura", "K60.1"),
    K60_2("Analna fisura, nespecificirana", "K60.2"),
    K60_3("Analna fistula", "K60.3"),
    K60_4("Rektalna fistula", "K60.4"),
    K60_5("Anorektalna fistula", "K60.5"),
    K61("Apsces analnog i rektalnog područja", "K61"),
    K61_0("Analni apsces", "K61.0"),
    K61_1("Rektalni apsces", "K61.1"),
    K61_2("Anorektalni apsces", "K61.2"),
    K61_3("Ishiorektalni apsces", "K61.3"),
    K61_4("Intrasfinkterični apsces", "K61.4"),
    K62("Ostale bolesti anusa i rektuma", "K62"),
    K62_0("Analni polip", "K62.0"),
    K62_1("Rektalni polip", "K62.1"),
    K62_2("Analni prolaps", "K62.2"),
    K62_3("Rektalni prolaps", "K62.3"),
    K62_4("Stenoza anusa i rektuma", "K62.4"),
    K62_5("Krvarenje anusa i rektuma", "K62.5"),
    K62_6("Vrijed anusa i rektuma", "K62.6"),
    K62_7("Radijacijski proktitis (proktitis uzrokovan zračenjem)", "K62.7"),
    K62_8("Ostale specificirane bolesti anusa i rektuma", "K62.8"),
    K62_9("Bolest anusa i rektuma, nespecificirana", "K62.9"),
    K63("Ostale crijevne bolesti", "K63"),
    K63_0("Apsces crijeva", "K63.0"),
    K63_1("Perforacija crijeva (netraumatska)", "K63.1"),
    K63_2("Fistula crijeva", "K63.2"),
    K63_3("Vrijed crijeva", "K63.3"),
    K63_4("Enteroptoza", "K63.4"),
    K63_8("Ostale specificirane bolesti crijeva", "K63.8"),
    K63_9("Bolest crijeva, nespecificirana", "K63.9"),
    K65("Upala potrbušnice (peritonitis)", "K65"),
    K65_0("Akutna upala potrbušnice (akutni peritonitis)", "K65.0"),
    K65_8("Ostale upale potrbušnice", "K65.8"),
    K65_9("Upala potrbušnice, nespecificirana", "K65.9"),
    K66("Ostali poremećaji potrbušnice", "K66"),
    K66_0("Priraslice potrbušnice (peritonealne adhezije)", "K66.0"),
    K66_1("Hemoperitoneum", "K66.1"),
    K66_8("Ostale specificirane bolesti potrbušnice", "K66.8"),
    K66_9("Bolest potrbušnice, nespecificirana", "K66.9"),
    K67("Bolest potrbušnice kod infektivnih bolesti svrstanih drugamo", "K67"),
    K67_0("Klamidijski peritonitis (A74.8)", "K67.0"),
    K67_1("Gonokokni peritonitis (A54.8)", "K67.1"),
    K67_2("Sifilitični peritonitis (A52.7)", "K67.2"),
    K67_3("Tuberkulozni peritonitis (A18.3)", "K67.3"),
    K67_8("Ostale bolesti potrbušnice kod infektivnih bolesti svrstanih drugamo", "K67.8"),
    K70("Alkoholna bolest jetre", "K70"),
    K70_0("Alkoholna masna jetra (steatoza jetre)", "K70.0"),
    K70_1("Alkoholni hepatitis", "K70.1"),
    K70_2("Alkoholna fibroza i skleroza jetre", "K70.2"),
    K70_3("Alkoholna ciroza jetre", "K70.3"),
    K70_4("Alkoholno zatajenje jetre", "K70.4"),
    K70_9("Alkoholna bolest jetre, nespecificirana", "K70.9"),
    K71("Toksična bolest jetre", "K71"),
    K71_0("Toksična bolest jetre s kolestazom", "K71.0"),
    K71_1("Toksična bolest jetre s nekrozom jetre", "K71.1"),
    K71_2("Toksična bolest jetre s akutnim hepatitisom", "K71.2"),
    K71_3("Toksična bolest jetre s kroničnim perzistentnim hepatitisom", "K71.3"),
    K71_4("Toksična bolest jetre s kroničnim lobularnim hepatitisom", "K71.4"),
    K71_5("Toksična bolest jetre s kroničnim aktivnim hepatitisom", "K71.5"),
    K71_6("Toksična bolest jetre s hepatitisom, nesvrstana drugamo", "K71.6"),
    K71_7("Toksična bolest jetre s fibrozom i cirozom jetre", "K71.7"),
    K71_8("Toksična bolest jetre s drugim poremećajima jetre", "K71.8"),
    K71_9("Toksična bolest jetre, nespecificirana", "K71.9"),
    K72("Zatajenje jetre, nesvrstano drugamo", "K72"),
    K72_0("Akutno ili subakutno zatajenje jetre", "K72.0"),
    K72_1("Kronično zatajenje jetre", "K72.1"),
    K72_9("Zatajenje jetre, nespecificirano", "K72.9"),
    K73("Kronični hepatitis, nesvrstan drugamo", "K73"),
    K73_0("Kronični perzistentni hepatitis, nesvrstan drugamo", "K73.0"),
    K73_1("Kronični lobularni hepatitis, nesvrstan drugamo", "K73.1"),
    K73_2("Kronični aktivni hepatitis, nesvrstan drugamo", "K73.2"),
    K73_8("Drugi kronični hepatitis, nesvrstan drugamo", "K73.8"),
    K73_9("Kronični hepatitis, nespecificiran", "K73.9"),
    K74("Fibroza i ciroza jetre", "K74"),
    K74_0("Fibroza jetre (hepatična fibroza)", "K74.0"),
    K74_1("Skleroza jetre (hepatična skleroza)", "K74.1"),
    K74_2("Fibroza jetre sa sklerozom jetre (hepatična fibroza s hepatičnom sklerozom)", "K74.2"),
    K74_3("Primarna bilijarna ciroza", "K74.3"),
    K74_4("Sekundarna bilijarna ciroza", "K74.4"),
    K74_5("Bilijarna ciroza, nespecificirana", "K74.5"),
    K74_6("Ostale i nespecificirane bolesti jetre", "K74.6"),
    K75("Druge upalne bolesti jetre", "K75"),
    K75_0("Apsces jetre", "K75.0"),
    K75_1("Flebitis portalne vene", "K75.1"),
    K75_2("Nespecifični reaktivni hepatitis", "K75.2"),
    K75_3("Granulomatozni hepatitis, nesvrstan drugamo", "K75.3"),
    K75_8("Ostale specificirane upalne bolesti jetre", "K75.8"),
    K75_9("Upalna bolest jetre, nespecificirana", "K75.9"),
    K76("Ostale bolesti jetre", "K76"),
    K76_0("Masna jetra, nesvrstana drugamo", "K76.0"),
    K76_1("Kronična pasivna kongestija jetre", "K76.1"),
    K76_2("Centralna hemoragijska nekroza jetre", "K76.2"),
    K76_3("Infarkt jetre", "K76.3"),
    K76_4("Pelioza jetre", "K76.4"),
    K76_5("Hepatična vensko-okluzivna bolest", "K76.5"),
    K76_6("Portalna hipertenzija", "K76.6"),
    K76_7("Hepatorenalni sindrom", "K76.7"),
    K76_8("Ostale specificirane bolesti jetre", "K76.8"),
    K76_9("Bolest jetre, nespecificirana", "K76.9"),
    K77("Bolesti jetre kod bolesti svrstanih drugamo", "K77"),
    K77_0("Bolesti jetre kod infektivnih i parazitarnih bolesti svrstanih drugamo", "K77.0"),
    K77_8("Bolesti jetre kod ostalih bolesti svrstanih drugamo", "K77.8"),
    K80("Žučni kamenci (kolelitijaza)", "K80"),
    K80_0("Kamenac u žučnjaku s akutnom upalom žučnjaka", "K80.0"),
    K80_1("Kamenac u žučnjaku s drugom upalom žučnjaka", "K80.1"),
    K80_2("Kamenac u žučnjaku bez upale", "K80.2"),
    K80_3("Kamenac žučnog kanala s upalom žučovoda", "K80.3"),
    K80_4("Kamenac žučnog kanala s upalom žučnjaka", "K80.4"),
    K80_5("Kamenac žučnog kanala bez upale žučovoda ili žučnjaka", "K80.5"),
    K80_8("Druga kolelitijaza", "K80.8"),
    K81("Upala žučnjaka (kolecistitis)", "K81"),
    K81_0("Akutna upala žučnjaka (akutni kolecistitis)", "K81.0"),
    K81_1("Kronična upala žučnjaka (kronični kolecistitis)", "K81.1"),
    K81_8("Druge upale žučnjaka", "K81.8"),
    K81_9("Upala žučnjaka, nespecificirana", "K81.9"),
    K82("Ostale bolesti žučnjaka", "K82"),
    K82_0("Opstrukcija žučnjaka", "K82.0"),
    K82_1("Hidrops žučnjaka", "K82.1"),
    K82_2("Perforacija žučnjaka", "K82.2"),
    K82_3("Fistula žučnjaka", "K82.3"),
    K82_4("Kolesteroloza žučnjaka", "K82.4"),
    K82_8("Ostale specificirane bolesti žučnjaka", "K82.8"),
    K82_9("Bolest žučnjaka, nespecificirana", "K82.9"),
    K83("Ostale bolesti žučnog sustava", "K83"),
    K83_0("Upala žučovoda (kolangitis)", "K83.0"),
    K83_1("Opstrukcija žučnog kanala", "K83.1"),
    K83_2("Perforacija žučnog kanala", "K83.2"),
    K83_3("Fistula žučnog kanala", "K83.3"),
    K83_4("Spazam Oddijeva sfinktera", "K83.4"),
    K83_5("Cista, žučna", "K83.5"),
    K83_8("Ostale specificirane bolesti žučnog sustava", "K83.8"),
    K83_9("Bolest žučnog sustava, nespecificirana", "K83.9"),
    K85("Akutna upala gušterače (akutni pankreatitis)", "K85"),
    K85_0("Akutna upala gušterače (akutni pankreatitis)", "K85.0"),
    K86("Ostale bolesti gušterače", "K86"),
    K86_0("Kronična upala gušterače uzrokovana alkoholom", "K86.0"),
    K86_1("Druge kronične upale gušterače", "K86.1"),
    K86_2("Cista gušterače", "K86.2"),
    K86_3("Pseudocista gušterače", "K86.3"),
    K86_8("Ostale specificirane bolesti gušterače", "K86.8"),
    K86_9("Bolest gušterače, nespecificirana", "K86.9"),
    K87("Bolesti žučnjaka, žučnog sustava i gušterače kod bolesti svrstanih drugamo", "K87"),
    K87_0("Bolesti žučnjaka i žučnog sustava kod bolesti svrstanih drugamo", "K87.0"),
    K87_1("Bolesti gušterače kod bolesti svrstanih drugamo", "K87.1"),
    K90("Crijevna malapsorpcija", "K90"),
    K90_0("Celijakija (morbus coeliacus)", "K90.0"),
    K90_1("Tropska sprue", "K90.1"),
    K90_2("Sindrom slijepe petlje, nesvrstan drugamo", "K90.2"),
    K90_3("Pankreatična steatoreja", "K90.3"),
    K90_4("Malapsorpcija zbog intolerancije, nesvrstana drugamo", "K90.4"),
    K90_8("Druga crijevna malapsorpcija", "K90.8"),
    K90_9("Crijevna malapsorpcija, nespecificirana", "K90.9"),
    K91("Poremećaji probavnog sustava koji se javljaju poslije određenih postupaka, nesvrstani drugamo", "K91"),
    K91_0("Povraćanje nakon gastrointestinalnog kirurškog zahvata", "K91.0"),
    K91_1("Sindromi nakon kirurškog zahvata na želucu", "K91.1"),
    K91_2("Malapsorpcija poslije kirurškog zahvata, nesvrstana drugamo", "K91.2"),
    K91_3("Opstrukcija crijeva nakon operativnog zahvata", "K91.3"),
    K91_4("Poremećaji funkcije kolostome i enterostome", "K91.4"),
    K91_5("Postkolecistektomični sindrom", "K91.5"),
    K91_8("Ostali poremećaji probavnog sustava koji se pojavljaju nakon određenih postupaka, nesvrstani drugamo", "K91.8"),
    K91_9("Poremećaj probavnog sustava koji se pojavljuje nakon određenog postupka, nespecificiran", "K91.9"),
    K92("Ostale bolesti probavnog sustava", "K92"),
    K92_0("Hematemeza", "K92.0"),
    K92_1("Melena", "K92.1"),
    K92_2("Krvarenje iz probavnog sustava, nespecificirano", "K92.2"),
    K92_8("Ostale specificirane bolesti probavnog sustava", "K92.8"),
    K92_9("Bolest probavnog sustava, nespecificirana", "K92.9"),
    K93("Bolesti ostalih probavnih organa kod bolesti svrstanih drugamo", "K93"),
    K93_0("Tuberkuloza crijeva, potrbušnice i mezenteričnih žlijezda (A18.3)", "K93.0"),
    K93_1("Megakolon kod Chagasove bolesti (B57.3)", "K93.1"),
    K93_8("Bolesti ostalih specificiranih probavnih organa kod bolesti svrstanih drugamo", "K93.8");
    
    private final String displayName;
    private final String code;
    
    MkbCodesK(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
