package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesN {
    
    N00("Akutni nefritički sindrom", "N00"),
    N00_0("Akutni nefritički sindrom", "N00.0"),
    N01("Brzoprogredirajući nefritički sindrom", "N01"),
    N01_0("Brzoprogredirajući nefritički sindrom", "N01.0"),
    N02("Rekurirajuća i perzistentna hematurija", "N02"),
    N02_0("Rekurirajuća i perzistentna hematurija", "N02.0"),
    N03("Kronični nefritički sindrom", "N03"),
    N03_0("Kronični nefritički sindrom", "N03.0"),
    N04("Nefrotski sindrom", "N04"),
    N04_0("Nefrotski sindrom", "N04.0"),
    N05("Nespecificirani nefritički sindrom", "N05"),
    N05_0("Nespecificirani nefritički sindrom", "N05.0"),
    N06("Izolirana proteinurija sa specificiranim morfološkim oštećenjem", "N06"),
    N06_0("Izolirana proteinurija sa specificiranim morfološkim oštećenjem", "N06.0"),
    N07("Nasljedna (hereditarna) nefropatija, nesvrstana drugamo", "N07"),
    N07_0("Nasljedna (hereditarna) nefropatija, nesvrstana drugamo", "N07.0"),
    N08("Glomerulski poremećaji u bolestima svrstanim drugamo", "N08"),
    N08_0("Glomerulski poremećaji u zaraznim i parazitarnim bolestima", "N08.0"),
    N08_1("Glomerulski poremećaji u neoplastičnim bolestima", "N08.1"),
    N08_2("Glomerulski poremećaji kod krvnih bolesti i poremećaja", "N08.2"),
    N08_3("Glomerulski poremećaji u šećernoj bolesti (E10-E14 sa zajedničkom četvrtom znamenkom .2)", "N08.3"),
    N08_4("Glomerulski poremećaji u drugim endokrinim, nutritivnim i metaboličkim bolestima", "N08.4"),
    N08_5("Glomerulski poremećaji u bolestima sistemnoga vezivnog tkiva", "N08.5"),
    N08_8("Glomerulski poremećaji u drugim bolestima svrstanima drugamo", "N08.8"),
    N10("Akutni tubulointersticijski nefritis", "N10"),
    N10_0("Akutni tubulointersticijski nefritis", "N10.0"),
    N11("Kronični tubulointersticijski nefritis", "N11"),
    N11_0("Neopstruktivni kronični pijelonefritis udružen s refluksom", "N11.0"),
    N11_1("Kronični opstruktivni pijelonefritis", "N11.1"),
    N11_8("Drugi kronični tubulointersticijski nefritis", "N11.8"),
    N11_9("Kronični tubulointersticijski nefritis, nespecificirani", "N11.9"),
    N12("Tubulointersticijski nefritis, nespecificiran kao akutni ili kronični", "N12"),
    N12_0("Tubulointersticijski nefritis, nespecificiran kao akutni ili kronični", "N12.0"),
    N13("Opstruktivna i refluksna uropatija", "N13"),
    N13_0("Hidronefroza s opstrukcijom uretero-pelvičnog spoja", "N13.0"),
    N13_1("Hidronefroza sa suženjem uretera, nesvrstana drugamo", "N13.1"),
    N13_2("Hidronefroza s bubrežnom ili ureterskom opstrukcijom (začepljenjem) zbog kamenca", "N13.2"),
    N13_3("Druga i nespecificirana hidronefroza", "N13.3"),
    N13_4("Hidroureter", "N13.4"),
    N13_5("Presavinuće (kinking) i suženje uretera bez hidronefroze", "N13.5"),
    N13_6("Pionefroza", "N13.6"),
    N13_7("Uropatija udružena s vezikoureterskim refluksom", "N13.7"),
    N13_8("Druga opstruktivna i refluksna uropatija", "N13.8"),
    N13_9("Opstruktivna i refluksna uropatija, nespecificirana", "N13.9"),
    N14("Tubulointersticijska i tubulska stanja uzrokovana lijekovima i teškim metalima (kovinama)", "N14"),
    N14_0("Analgezijska nefropatija", "N14.0"),
    N14_1("Nefropatija uzrokovana drugim lijekovima, medikamentima i biološkim tvarima", "N14.1"),
    N14_2("Nefropatija uzrokovana nespecificiranim lijekom, medikamentom ili biološkom tvari", "N14.2"),
    N14_3("Nefropatija uzrokovana teškim kovinama", "N14.3"),
    N14_4("Toksična nefropatija nesvrstana drugamo", "N14.4"),
    N15("Druge tubulointersticijske bolesti bubrega", "N15"),
    N15_0("Balkanska endemska nefropatija (endemska nefropatija)", "N15.0"),
    N15_1("Bubrežni i perinefritički apsces", "N15.1"),
    N15_8("Druge specificirane tubulointersticijske bolesti bubrega", "N15.8"),
    N15_9("Bubrežna tubulointersticijska bolest, nespecificirana", "N15.9"),
    N16("Bubrežni tubulointersticijski poremećaji u bolestima svrstanima drugamo", "N16"),
    N16_0("Bubrežni tubulointersticijski poremećaji u zaraznim i parazitarnim bolestima, svrstanima drugamo", "N16.0"),
    N16_1("Bubrežni tubulointersticijski poremećaji u neoplastičnim bolestima", "N16.1"),
    N16_2("Bubrežni tubulointersticijski poremećaji u krvnim bolestima i poremećajima imunološkog mehanizma", "N16.2"),
    N16_3("Bubrežni tubulointersticijski poremećaji u metaboličkim bolestima", "N16.3"),
    N16_4("Bubrežni tubulointersticijski poremećaji u sistemnim poremećajima vezivnoga tkiva (kalogenoze)", "N16.4"),
    N16_5("Bubrežni tubulointersticijski poremećaji u odbacivanju presatka (transplantata) (T86.-)", "N16.5"),
    N16_8("Bubrežni tubulointersticijski poremećaji u drugim bolestima svrstanima drugamo", "N16.8"),
    N17("Akutno bubrežno zatajenje (akutna bubrežna insuficijencija)", "N17"),
    N17_0("Akutno bubrežno zatajenje s tubulskom nekrozom", "N17.0"),
    N17_1("Akutno bubrežno zatajenje s akutnom kortikalnom nekrozom", "N17.1"),
    N17_2("Akutno bubrežno zatajenje s medularnom nekrozom", "N17.2"),
    N17_8("Drugo akutno bubrežno zatajenje", "N17.8"),
    N17_9("Akutno bubrežno zatajenje, nespecificirano", "N17.9"),
    N18("Kronično bubrežno zatajenje (kronična bubrežna insuficijencija)", "N18"),
    N18_0("Terminalna (end-stage) bubrežna bolest", "N18.0"),
    N18_8("Drugo kronično bubrežno zatajenje", "N18.8"),
    N18_9("Kronično bubrežno zatajenje, nespecificirano", "N18.9"),
    N19("Nespecificirano bubrežno zatajenje", "N19"),
    N20("Kamenac bubrega i uretera", "N20"),
    N20_0("Kamenac u bubregu", "N20.0"),
    N20_1("Kamenac u ureteru (mokraćovodu)", "N20.1"),
    N20_2("Bubrežni kamenac s kamencem utetera", "N20.2"),
    N20_9("Mokraćni kamenac, nespecificirani", "N20.9"),
    N21("Kamenac donjega mokraćnog sustava", "N21"),
    N21_0("Kamenac u mjehuru", "N21.0"),
    N21_1("Kamenac u mokraćnoj cijevi (uretri)", "N21.1"),
    N21_8("Kamenac ostalih dijelova donjega mokraćnoga sustava", "N21.8"),
    N21_9("Kamenac donjih mokraćnih putova, nespecificiran", "N21.9"),
    N22("Kamenac mokraćnog puta (sustava) u bolestima svrstanima drugamo", "N22"),
    N22_0("Mokraćni kamenac u shistosomijazi (bilharciozi) (B65.-)", "N22.0"),
    N22_8("Kamenac mokraćnoga sustava u drugim bolestima svrstanima drugamo", "N22.8"),
    N23("Nespecificirane bubrežne kolike", "N23"),
    N23_0("Nespecificirane bubrežne kolike", "N23.0"),
    N25("Poremećaji nastali zbog oštećenja funkcije bubrežnih tubula", "N25"),
    N25_0("Bubrežna osteodistrofija", "N25.0"),
    N25_1("Nefrogeni dijabetes insipidus", "N25.1"),
    N25_8("Drugi poremećaji nastali zbog oštećene funkcije bubrežnih tubula", "N25.8"),
    N25_9("Poremećaj nastao zbog oštećenja tubularne funkcije, nespecificiran", "N25.9"),
    N26("Nespecificiran skvrčeni bubreg", "N26"),
    N26_0("Nespecificiran skvrčeni bubreg", "N26.0"),
    N27("Maleni bubreg nepoznata uzroka", "N27"),
    N27_0("Maleni bubreg, jednostrano", "N27.0"),
    N27_1("Maleni bubreg, obostrano", "N27.1"),
    N27_9("Maleni bubreg, nespecificirano", "N27.9"),
    N28("Drugi poremećaji bubrega i uretera, nesvrstani drugamo", "N28"),
    N28_0("Ishemija i infarkt bubrega", "N28.0"),
    N28_1("Bubrežna cista, stečena", "N28.1"),
    N28_8("Drugi specificirani poremećaji bubrega i uretera", "N28.8"),
    N28_9("Poremećaji bubrega i uretera, nespecificirani", "N28.9"),
    N29("Ostali poremećaji bubrega i uretera u bolestima svrstanima drugamo", "N29"),
    N29_0("Kasni sifilis bubrega (A52.7)", "N29.0"),
    N29_1("Drugi poremećaji bubrega i uretera u zaraznim i parazitarnim bolestima svrstanima drugamo", "N29.1"),
    N29_8("Drugi poremećaji bubrega i uretera u drugim bolestima svrstanima drugamo", "N29.8"),
    N30("Upala mokraćnog mjehura (cistitis)", "N30"),
    N30_0("Akutni cistitis", "N30.0"),
    N30_1("Intersticijski cistitis (kronični)", "N30.1"),
    N30_2("Drugi kronični cistitis", "N30.2"),
    N30_3("Trigonitis", "N30.3"),
    N30_4("Iradijacijski cistitis", "N30.4"),
    N30_8("Drugi cistitis", "N30.8"),
    N30_9("Cistitis, nespecificiran", "N30.9"),
    N31("Neuromuskularna disfunkcija mokraćnoga mjehura, nesvrstana drugamo", "N31"),
    N31_0("Neinhibirani neuropatski (neurogeni) mjehur, nesvrstan drugamo", "N31.0"),
    N31_1("Refleksni neuropatski mjehur, nesvrstan drugamo", "N31.1"),
    N31_2("Flakcidni (mlohavi) neuropatski mjehur nesvrstan drugamo", "N31.2"),
    N31_8("Druga neuromuskularna disfunkcija mjehura", "N31.8"),
    N31_9("Neuromusklarna disfunkcija mjehura, nepsecificirana", "N31.9"),
    N32("Drugi poremećaji mokraćnoga mjehura", "N32"),
    N32_0("Opstrukcija vrata mjehura", "N32.0"),
    N32_1("Vezikointestinalna fistula", "N32.1"),
    N32_2("Vezikalna fistula, nesvrstana drugamo", "N32.2"),
    N32_3("Divertikul mjehura", "N32.3"),
    N32_4("Ruptura (razdor) mjehura, netraumatska", "N32.4"),
    N32_8("Drugi specificirani poremećaji mjehura", "N32.8"),
    N32_9("Poremećaj mjehura, nespecificiran", "N32.9"),
    N33("Poremećaji mjehura u bolestima svrstanima drugamo", "N33"),
    N33_0("Tuberkulozni cistitis (A18.1)", "N33.0"),
    N33_8("Poremećaji mjehura u drugim bolestima svrstanima drugamo", "N33.8"),
    N34("Uretritis i uretralni sindrom", "N34"),
    N34_0("Uretralni apsces (apsces uretre)", "N34.0"),
    N34_1("Nespecifični uretritis", "N34.1"),
    N34_2("Drugi uretritis", "N34.2"),
    N34_3("Uretralni sindrom, nespecificiran", "N34.3"),
    N35("Striktura (suženje) uretre", "N35"),
    N35_0("Posttraumatska uretralna striktura (suženje)", "N35.0"),
    N35_1("Postinfektivno suženje uretre, nesvrstano drugamo", "N35.1"),
    N35_8("Druga uretralna striktura", "N35.9"),
    N35_9("Uretralna striktura, nespecificirana", "N35.9"),
    N36("Drugi poremećaji uretre", "N36"),
    N36_0("Uretralna fistula (fistula mokraćne cijevi)", "N36.0"),
    N36_1("Uretralni divertikul", "N36.1"),
    N36_2("Uretralni karunkul", "N36.2"),
    N36_3("Prolabirana uretralna sluznica", "N36.3"),
    N36_8("Drugi specificirani poremećaji uretre", "N36.8"),
    N36_9("Poremećaj uretre, nespecificiran", "N36.9"),
    N37("Uretralni poremećaji u bolestima svrstanima drugamo", "N37"),
    N37_0("Uretritis u bolestima svrstanima drugamo", "N37.0"),
    N37_8("Drugi uretralni poremećaji u bolestima svrstanima drugamo", "N37.8"),
    N39("Drugi poremećaji urinarnog sustava", "N39"),
    N39_0("Infekcija urinarnoga trakta, lokacija neoznačena", "N39.0"),
    N39_1("Perzistirajuća proteinurija, nespecificirana", "N39.1"),
    N39_2("Ortostatska proteinurija, nespecificirana", "N39.2"),
    N39_3("Stresna inkontinencija", "N39.3"),
    N39_4("Druga specificirana urinarna inkontinencija", "N39.4"),
    N39_8("Drugi specificirani poremećaji mokraćnog sustava", "N39.8"),
    N39_9("Poremećaj mokraćnog sustava, nespecificiran", "N39.9"),
    N40("Hiperplazija prostate", "N40"),
    N40_0("Hiperplazija prostate", "N40.0"),
    N41("Upalne bolesti prostate", "N41"),
    N41_0("Akutni prostatitis", "N41.0"),
    N41_1("Kronični prostatitis", "N41.1"),
    N41_2("Apsces prostate", "N41.2"),
    N41_3("Prostatocistitis", "N41.3"),
    N41_8("Druge upalne bolesti prostate", "N41.8"),
    N41_9("Upalna bolest prostate, nespecificirana", "N41.9"),
    N42("Drugi poremećaji prostate", "N42"),
    N42_0("Kamenac prostate", "N42.0"),
    N42_1("Kongestija i hemoragija prostate", "N42.1"),
    N42_2("Atrofija prostate", "N42.2"),
    N42_8("Drugi specificirani poremećaji prostate", "N42.8"),
    N42_9("Poremećaj prostate, nespecificiran", "N42.9"),
    N43("Hidrokela i spermatokela", "N43"),
    N43_0("Cistična hidrokela", "N43.0"),
    N43_1("Inficirana hidrokela", "N43.1"),
    N43_2("Druga hidrokela", "N43.2"),
    N43_3("Hidrokela, nespecificirana", "N43.3"),
    N43_4("Spermatokela", "N43.4"),
    N44("Torzija testisa", "N44"),
    N44_0("Torzija testisa", "N44.0"),
    N45("Orhitis i epididimitis", "N45"),
    N45_0("Orhitis, epididimitis i epididimoorhitis s apscesom", "N45.0"),
    N45_9("Orhitis, epididimitis i epididimoorhitis bez apscesa", "N45.9"),
    N46("Muška neplodnost", "N46"),
    N46_0("Muška neplodnost", "N46.0"),
    N47("Prevelik prepucij, fimoza i parafimoza", "N47"),
    N47_0("Prevelik prepucij, fimoza i parafimoza", "N47.0"),
    N48("Drugi poremećaji penisa", "N48"),
    N48_0("Leukoplakija penisa", "N48.0"),
    N48_1("Balanopostitis", "N48.1"),
    N48_2("Drugi upalni poremećaji penisa", "N48.2"),
    N48_3("Prijapizam", "N48.3"),
    N48_4("Impotencija organskog podrijetla", "N48.4"),
    N48_5("Ulkus penisa (ulcer) (čir)", "N48.5"),
    N48_6("Induratio penis plastica (Peyronieva bolest)", "N48.6"),
    N48_8("Drugi specificirani poremećaji penisa", "N48.8"),
    N48_9("Poremećaj penisa, nespecificiran", "N48.9"),
    N49("Upalni poremećaji muških spolnih organa, nesvrstani drugamo", "N49"),
    N49_0("Upalni poremećaji sjemene vrećice (vezikule seminalis)", "N49.0"),
    N49_1("Upalni poremećaji sjemenovoda, tunike vaginalis i vasa deferensa", "N49.1"),
    N49_2("Upalni poremećaji skrotuma", "N49.2"),
    N49_8("Upalni poremećaji drugih specificiranih muških spolnih organa", "N49.8"),
    N49_9("Upalni poremećaji nespecificiranoga muškoga spolnog organa", "N49.9"),
    N50("Drugi poremećaji muških spolnih organa", "N50"),
    N50_0("Atrofija testisa", "N50.0"),
    N50_1("Vaskularni poremećaji muških spolnih organa", "N50.1"),
    N50_8("Drugi specificirani poremećaji muških spolnih organa", "N50.8"),
    N50_9("Poremećaji muških spolnih organa, nespecificirani", "N50.9"),
    N51("Poremećaji muških spolnih organa u bolestima svrstanima drugamo", "N51"),
    N51_0("Poremećaji prostate u bolestima svrstanima drugamo", "N51.0"),
    N51_1("Poremećaji testisa i epididimisa u bolestima svrstanima drugamo", "N51.1"),
    N51_2("Balanitis u bolestima svrstanima drugamo", "N51.2"),
    N51_8("Drugi poremećaji muških spolnih organa u bolestima svrstanima drugamo", "N51.8"),
    N60("Benigna (doboroćudna) displazija dojke", "N60"),
    N60_0("Solitarna cista dojke", "N60.0"),
    N60_1("Difuzna cistična mastopatija", "N60.1"),
    N60_2("Fibroadenoza dojke", "N60.2"),
    N60_3("Fibroskleroza dojke", "N60.3"),
    N60_4("Mamarna duktalna ektazija (proširenje)", "N60.4"),
    N60_8("Druge benigne displazije dojke", "N60.8"),
    N60_9("Benigna displazija dojke, nespecificirana", "N60.9"),
    N61("Upalni poremećaji dojke", "N61"),
    N62("Hipertrofija dojke", "N62"),
    N62_0("Hipertrofija dojke", "N62.0"),
    N63("Nespecificirana kvrga u dojci", "N63"),
    N63_0("Nespecificirana kvrga u dojci", "N63.0"),
    N64("Drugi poremećaji dojke", "N64"),
    N64_0("Fisura i fistula bradavice", "N64.0"),
    N64_1("Masna nekroza dojke", "N64.1"),
    N64_2("Atrofija dojke", "N64.2"),
    N64_3("Galaktoreja nepovezana s porođajem", "N64.3"),
    N64_4("Mastodinija (bolne dojke)", "N64.4"),
    N64_5("Ostali znakovi i simptomi na dojkama", "N64.5"),
    N64_8("Drugi specificirani poremećaji dojki", "N64.8"),
    N64_9("Poremećaj dojke, nespecificiran", "N64.9"),
    N70("Salpingitis i ooforitis", "N70"),
    N70_0("Akutni salpingitis i ooforitis", "N70.0"),
    N70_1("Kronični salpingitis i ooforitis", "N70.1"),
    N70_9("Salpingitis i ooforitis, nespecificiran", "N70.9"),
    N71("Upala maternice, osim vrata (cerviksa)", "N71"),
    N71_0("Akutna upala maternice", "N71.0"),
    N71_1("Kronična upala maternice", "N71.1"),
    N71_9("Upala maternice, nespecificirana", "N71.9"),
    N72("Upale vrata maternice", "N72"),
    N72_0("Upale vrata maternice", "N72.0"),
    N73("Druge zdjelične upalne bolesti u žena", "N73"),
    N73_0("Akutni parametritis i celulitis zdjelice", "N73.0"),
    N73_1("Kronični parametritis i celulitis zdjelice", "N73.1"),
    N73_2("Nespecificirani parametritis i celulitis zdjelice", "N73.2"),
    N73_3("Akutni zdjelični peritonitis", "N73.3"),
    N73_4("Kronični zdjelični peritonitis", "N73.4"),
    N73_5("Zdjelični peritonitis, nespecificiran", "N73.5"),
    N73_6("Zdjelične peritonealne priraslice (adhezije) u žena", "N73.6"),
    N73_8("Druge specificirane ženske zdjelične upalne bolesti", "N73.8"),
    N73_9("Zdjelična upalna bolest u žena, nespecificirana", "N73.9"),
    N74("Upalni poremećaji zdjelice žena u bolestima svrstanima drugamo", "N74"),
    N74_0("Tuberkulozna infekcija vrata maternice (A18.1)", "N74.0"),
    N74_1("Tuberkulozna zdjelična upala u žene (A18.1)", "N74.1"),
    N74_2("Sifilitična zdjelična upala u žene (A51.4, A52.7)", "N74.2"),
    N74_3("Gonokokna zdjelična upala u žene (A54.2)", "N74.3"),
    N74_4("Klamidijska zdjelična upala u žene (A56.1)", "N74.4"),
    N74_8("Zdjelični upalni poremećaji žene u drugim bolestima svrstanima drugamo", "N74.8"),
    N75("Bolesti Bartholinove žlijezde", "N75"),
    N75_0("Cista Bartholinove žlijezde", "N75.0"),
    N75_1("Apsces Bartholinove žlijezde", "N75.1"),
    N75_8("Druge bolesti Bartholinove žlijezde", "N75.8"),
    N75_9("Bolest Bartholinove žlijezde, nespecificirana", "N75.9"),
    N76("Druga upala rodnice (vagine) i vulve (stidnice)", "N76"),
    N76_0("Akutni vaginitis (akutna upala rodnice)", "N76.0"),
    N76_1("Subakutni i kronični vaginitis", "N76.1"),
    N76_2("Akutni vulvitis (akutna upala stidnice)", "N76.2"),
    N76_3("Subakutni i kronični vulvitis", "N76.3"),
    N76_4("Apsces vulve", "N76.4"),
    N76_5("Ulceracija vagine", "N76.5"),
    N76_6("Ulceracija vulve", "N76.6"),
    N76_8("Druga specificirana upala vagine i vulve", "N76.8"),
    N77("Vulvovaginalna ulceracija i upala u bolestima svrstanima drugamo", "N77"),
    N77_0("Ulceracija vulve u infektivnim i parazitarnim bolestima svrstanima drugamo", "N77.0"),
    N77_1("Vaginitis, vulvitis i vulvovaginitis u infektivnim i parazitarnim bolestima svrstanima drugamo", "N77.1"),
    N77_8("Vulvovaginalna ulceracija i upala u drugim bolestima svrstanima drugamo", "N77.8"),
    N80("Endometrioza", "N80"),
    N80_0("Endometrioza maternice", "N80.0"),
    N80_1("Endemetrioza ovarija", "N80.1"),
    N80_2("Endometrioza tube uterine", "N80.2"),
    N80_3("Endometrioza pelvičnog peritoneuma", "N80.3"),
    N80_4("Endometrioza rektovaginalnog septuma i vagine", "N80.4"),
    N80_5("Endometrioza crijeva", "N80.5"),
    N80_6("Endometrioza kožnog ožiljka", "N80.6"),
    N80_8("Druga endometrioza", "N80.8"),
    N80_9("Endometrioza, nespecificirana", "N80.9"),
    N81("Prolaps ženskih genitalija", "N81"),
    N81_0("Uretrokela žene", "N81.0"),
    N81_1("Cistokela", "N81.1"),
    N81_2("Nepotpuni uterovaginalni prolaps", "N81.2"),
    N81_3("Potpuni uterovaginalni prolaps", "N81.3"),
    N81_4("Uterovaginalni prolaps, nespecificiran", "N81.4"),
    N81_5("Vaginalna enterokela", "N81.5"),
    N81_6("Rektokela", "N81.6"),
    N81_8("Drugi prolaps ženskih genitalija", "N81.8"),
    N81_9("Prolaps ženskih genitalija, nespecificiran", "N81.9"),
    N82("Fistule koje zahvaćaju ženski spolni sustav", "N82"),
    N82_0("Vezikovaginalna fistula", "N82.0"),
    N82_1("Druge fistule ženskog genitourinarnog sustava", "N82.1"),
    N82_2("Fistula između rodnice i tankog crijeva", "N82.2"),
    N82_3("Fistula između rodnice i debeloga crijeva", "N82.3"),
    N82_4("Druge fistule ženskoga intestinalno-genitalnoga sustava", "N82.4"),
    N82_5("Fistule između ženskog spolnog sustava i kože", "N82.5"),
    N82_8("Druge fistule ženskoga spolnog sustava", "N82.8"),
    N82_9("Fistula ženskoga spolnog sustava, nespecificirana", "N82.9"),
    N83("Neupalni poremećaji ovarija, jajovoda i širokog ligamenta", "N83"),
    N83_0("Folikularna cista jajnika", "N83.0"),
    N83_1("Cista žutog tijela (corpus luteum)", "N83.1"),
    N83_2("Druge i nespecificirane ovarijske ciste", "N83.2"),
    N83_3("Stečena atrofija jajnika i jajovoda (Falopijeve tube)", "N83.3"),
    N83_4("Prolaps i hernija jajnika i jajovoda", "N83.4"),
    N83_5("Torzija jajnika, 'peteljke' jajnika i jajovoda", "N83.5"),
    N83_6("Hematosalpinx", "N83.6"),
    N83_7("Hematom širokog ligamenta (ligamentum latum)", "N83.7"),
    N83_8("Drugi neupalni poremećaji jajnika, jajovoda i širokog ligamenta", "N83.8"),
    N83_9("Neupalni poremećaji jajnika, jajovoda i širokog ligamenta, nespecificirani", "N83.9"),
    N84("Polip ženskoga spolnog sustava", "N84"),
    N84_0("Polip tijela maternice", "N84.0"),
    N84_1("Polip vrata maternice", "N84.1"),
    N84_2("Polip rodnice", "N84.2"),
    N84_3("Polip vulve", "N84.3"),
    N84_8("Polip drugih dijelova ženskog spolnog sustava", "N84.8"),
    N84_9("Polip ženskog spolnog sustava, nespecificiran", "N84.9"),
    N85("Drugi neupalni poremećaji maternice, izuzevši vrat", "N85"),
    N85_0("Glandularna hiperplazija endometrija", "N85.0"),
    N85_1("Adenomatozna hiperplazija endometrija", "N85.1"),
    N85_2("Hipertrofija uterusa", "N85.2"),
    N85_3("Subinvolucija maternice", "N85.3"),
    N85_4("Malpozicija maternice", "N85.4"),
    N85_5("Inverzija maternice", "N85.5"),
    N85_6("Intrauterine sinehije (srasline)", "N85.6"),
    N85_7("Hematometra", "N85.7"),
    N85_8("Drugi specificirani neupalni poremećaji maternice", "N85.8"),
    N85_9("Neupalni poremećaj maternice, nespecificiran", "N85.9"),
    N86("Erozija i ektropija vrata maternice", "N86"),
    N86_0("Erozija i ektropija vrata maternice", "N86.0"),
    N87("Displazija vrata maternice", "N87"),
    N87_0("Blaga cervikalna displazija", "N87.0"),
    N87_1("Umjerena cervikalna displazija", "N87.1"),
    N87_2("Teška cervikalna displazija nesvrstana drugamo", "N87.2"),
    N87_9("Displazija vrata maternice, nespecificirana", "N87.9"),
    N88("Drugi neupalni poremećaji vrata maternice", "N88"),
    N88_0("Leukoplakija vrata maternice", "N88.0"),
    N88_1("Stara laceracija vrata maternice", "N88.1"),
    N88_2("Striktura i stenoza vrata maternice", "N88.2"),
    N88_3("Insuficijencija vrata maternice", "N88.3"),
    N88_4("Hipertrofično izduženje vrata maternice", "N88.4"),
    N88_8("Drugi specificirani neupalni poremećaji vrata maternice", "N88.8"),
    N88_9("Neupalni poremećaj vrata maternice, nespecificiran", "N88.9"),
    N89("Drugi neupalni poremećaji rodnice", "N89"),
    N89_0("Blaga (laka) vaginalna displazija", "N89.0"),
    N89_1("Umjerena vaginalna displazija", "N89.1"),
    N89_2("Teška vaginalna displazija, nesvrstana drugamo", "N89.2"),
    N89_3("Displazija vagine, nespecificirana", "N89.3"),
    N89_4("Leukoplakija vagine", "N89.4"),
    N89_5("Striktura i atrezija vagine", "N89.5"),
    N89_6("Himenski prsten, čvrst", "N89.6"),
    N89_7("Hematokolpos", "N89.7"),
    N89_8("Drugi specificirani neupalni poremećaji rodnice", "N89.8"),
    N89_9("Neupalni poremećaj rodnice, nespecificiran", "N89.9"),
    N90("Drugi neupalni poremećaji vulve i perineuma (stidnice i međice)", "N90"),
    N90_0("Blaga (laka) vulvarna displazija", "N90.0"),
    N90_1("Umjerena vulvarna displazija", "N90.1"),
    N90_2("Teška vulvarna displazija, nespecificirana drugdje", "N90.2"),
    N90_3("Displazija vulve, nespecificirana", "N90.3"),
    N90_4("Leukoplakija vulve", "N90.4"),
    N90_5("Atrofija vulve", "N90.5"),
    N90_6("Hipertrofija vulve", "N90.6"),
    N90_7("Vulvarna cista", "N90.7"),
    N90_8("Drugi nespecificirani neupalni poremećaji vulve i perineuma", "N90.8"),
    N90_9("Neupalni poremećaj vulve i perineuma, nespecificiran", "N90.9"),
    N91("Izostala, oskudna i rijetka menstruacija", "N91"),
    N91_0("Primarna amenoreja", "N91.0"),
    N91_1("Sekundarna amenoreja", "N91.1"),
    N91_2("Amenoreja, nespecificirana", "N91.2"),
    N91_3("Primarna oligomenoreja", "N91.3"),
    N91_4("Sekundarna oligomenoreja", "N91.4"),
    N91_5("Oligomenoreja, nespecificirana", "N91.5"),
    N92("Prekomjerna, učestala i nepravilna menstruacija", "N92"),
    N92_0("Prekomjerna i učestala menstruacija s pravilnim (regularnim) ciklusom", "N92.0"),
    N92_1("Prekomjerna i učestala menstruacija s nepravilnim ciklusom", "N92.1"),
    N92_2("Prekomjerna menstruacija u pubertetu", "N92.2"),
    N92_3("Ovulacijsko krvarenje", "N92.3"),
    N92_4("Prekomjerno krvarenje u doba predmenopauze", "N92.4"),
    N92_5("Druga specificirana iregularna (neredovita) menstruacija", "N92.5"),
    N92_6("Neregularna menstruacija, nespecificirana", "N92.6"),
    N93("Drugo nenormalno maternično i vaginalno krvarenje", "N93"),
    N93_0("Postkoitalno i kontaktno krvarenje", "N93.0"),
    N93_8("Drugo specificirano nenormalno maternično i vaginalno krvarenje", "N93.8"),
    N93_9("Nenormalno maternično i vaginalno krvarenje, nespecificirano", "N93.9"),
    N94("Bol i druga stanja povezana sa ženskim spolnim organima i menstruacijskim ciklusom", "N94"),
    N94_0("Intermenstruacijska bol", "N94.0"),
    N94_1("Dispareunija", "N94.1"),
    N94_2("Vaginizam", "N94.2"),
    N94_3("Sindrom premenstrualne napetosti", "N94.3"),
    N94_4("Primarna dismenoreja", "N94.4"),
    N94_5("Sekundarna dismenoreja", "N94.5"),
    N94_6("Dismenoreja, nespecificirana", "N94.6"),
    N94_8("Druga nespecificirana stanja povezana sa ženskim spolnim organima i menstruacijskim ciklusom", "N94.8"),
    N94_9("Nespecificirano stanje u vezi sa ženskim spolnim organima i menstruacijskim ciklusom", "N94.9"),
    N95("Menopauzalni i drugi perimenopauzalni poremećaji", "N95"),
    N95_0("Postmenopauzalno krvarenje", "N95.0"),
    N95_1("Menopauzalna i druga ženska klimakterična stanja", "N95.1"),
    N95_2("Postmenopauzalni atrofični vaginitis", "N95.2"),
    N95_3("Stanja povezana s artificijalnom menopauzom", "N95.3"),
    N95_8("Drugi specificirani menopauzalni i perimenopauzalni poremećaji", "N95.8"),
    N95_9("Poremećaj u menopauzi i postmenopauzi, nespecificiran", "N95.9"),
    N96("Pobačaj, habitualni", "N96"),
    N96_0("Pobačaj, habitualni", "N96.0"),
    N97("Neplodnost žene", "N97"),
    N97_0("Neplodnost povezana s anovulacijom (izostankom ovulacije)", "N97.0"),
    N97_1("Neplodnost tubarnog podrijetla", "N97.1"),
    N97_2("Neplodnost materničnog podrijetla", "N97.2"),
    N97_3("Neplodnost cervikalnog podrijetla", "N97.3"),
    N97_4("Neplodnost žene povezana s muškim čimbenicima", "N97.4"),
    N97_8("Neplodnost žene drugog podrijetla", "N97.8"),
    N97_9("Neplodnost žene, nespecificirana", "N97.9"),
    N98("Komplikacije povezane s umjetnom oplodnjom", "N98"),
    N98_0("Infekcija povezana s umjetnom oplodnjom", "N98.0"),
    N98_1("Hiperstimulacija ovarija", "N98.1"),
    N98_2("Komplikacije pri uvođenju oplođenog jajašca nakon oplodnje in vitro", "N98.2"),
    N98_3("Komplikacije uvođenja embrija kod prijenosa embrija", "N98.3"),
    N98_8("Druge komplikacije povezane s umjetnom oplodnjom", "N98.8"),
    N98_9("Komplikacija povezana s umjetnom oplodnjom, nespecificirana", "N98.9"),
    N99("Poremećaji genitourinarnog sustava nakon postupaka (operacija) nesvrstani drugamo", "N99"),
    N99_0("Postoperativno zatajenje bubrega", "N99.0"),
    N99_1("Postoperativna striktura uretre", "N99.1"),
    N99_2("Postoperativne adhezije rodnice", "N99.2"),
    N99_3("Prolaps vaginalnog svoda nakon histerektomije", "N99.3"),
    N99_4("Postoperativne zdjelične peritonealne priraslice (adhezije)", "N99.4"),
    N99_5("Oštećena funkcija vanjskog ušća urinarnoga sustava", "N99.5"),
    N99_8("Drugi postoperativni poremećaji genitourinarnog sustava", "N99.8"),
    N99_9("Postoperativni poremećaji genitourinarnog sustava, nespecificirani", "N99.9");
    
    private final String displayName;
    private final String code;
    
    MkbCodesN(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
