package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesY {
    
    Y00("Napad tupim predmetom", "Y00"),
    Y00_0("Napad tupim predmetom", "Y00.0"),
    Y01("Napad guranjem s visine (s visokog mjesta)", "Y01"),
    Y01_0("Napad guranjem s visine (s visokog mjesta)", "Y01.0"),
    Y02("Napad guranjem ili postavljanjem žrtve pred objekt u pokretu", "Y02"),
    Y02_0("Napad guranjem ili postavljanjem žrtve pred objekt u pokretu", "Y02.0"),
    Y03("Napad razbijanjem motornog vozila", "Y03"),
    Y03_0("Napad razbijanjem motornog vozila", "Y03.0"),
    Y04("Napad tjelesnom silom", "Y04"),
    Y04_0("Napad tjelesnom silom", "Y04.0"),
    Y05("Seksualni napad tjelesnom silom", "Y05"),
    Y05_0("Seksualni napad tjelesnom silom", "Y05.0"),
    Y06("Zanemarivanje i napuštanje", "Y06"),
    Y06_0("Od supruga ili partnera", "Y06.0"),
    Y06_1("Od roditelja", "Y06.1"),
    Y06_2("Od poznanika ili prijatelja", "Y06.2"),
    Y06_8("Od drugih specificiranih osoba", "Y06.8"),
    Y06_9("Od nespecificirane osobe", "Y06.9"),
    Y07("Drugi sindromi zlostavljanja", "Y07"),
    Y07_0("Od supruga ili partnera", "Y07.0"),
    Y07_1("Od roditelja", "Y07.1"),
    Y07_2("Od poznanika ili prijatelja", "Y07.2"),
    Y07_3("Od službenih vlasti", "Y07.3"),
    Y07_8("Od drugih specificiranih osoba", "Y07.8"),
    Y07_9("Od nespecificirane osobe", "Y07.9"),
    Y08("Napad drugim specificiranim načinima", "Y08"),
    Y08_0("Napad drugim specificiranim načinima", "Y08.0"),
    Y09("Napad nespecificiranim načinom", "Y09"),
    Y09_0("Napad nespecificiranim načinom", "Y09.0"),
    Y10("Otrovanje i izlaganje neopioidnim analgeticima, antipireticima i antireumaticima, nakana neodređena", "Y10"),
    Y10_0("Otorovanje i izlaganje neopioidnim analgeticima, antipireticima i antireumaticima, nakana neodređena", "Y10.0"),
    Y11("Otrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima, nesvrstanim drugamo, nakana neodređena", "Y11"),
    Y11_0("Otrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima, nesvrstanim drugamo, nakana neodređena", "Y11.0"),
    Y12("Otrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo, nakana neodređena", "Y12"),
    Y12_0("Otrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo, nakana neodređena", "Y12.0"),
    Y13("Otrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav, nakana neodređena", "Y13"),
    Y13_0("Otrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav, nakana neodređena", "Y13.0"),
    Y14("Otrovanje i izlaganje drugim i nespecificiranim lijekovima, ljekovitim i biološkim tvarima, nakana neodređena", "Y14"),
    Y14_0("Otrovanje i izlaganje drugim i nespecificiranim lijekovima, ljekovitim i biološkim tvarima, nakana neodređena", "Y14.0"),
    Y15("Otrovanje i izlaganje alkoholu, nakana neodređena", "Y15"),
    Y15_0("Otrovanje i izlaganje alkoholu, nakana neodređena", "Y15.0"),
    Y16("Otrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama, nakana neodređena", "Y16"),
    Y16_0("Otrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama, nakana neodređena", "Y16.0"),
    Y17("Otrovanje i izlaganje drugim plinovima i parama, nakana neodređena", "Y17"),
    Y17_0("Otrovanje i izlaganje drugim plinovima i parama, nakana neodređena", "Y17.0"),
    Y18("Otrovanje i izlaganje pesticidima, nakana neodređena", "Y18"),
    Y18_0("Otrovanje i izlaganje pesticidima, nakana neodređena", "Y18.0"),
    Y19("Otrovanje i izlaganje drugim nespecificiranim kemikalijama i štetnim tvarima, nakana neodređena", "Y19"),
    Y19_0("Otrovanje i izlaganje drugim nespecificiranim kemikalijama i štetnim tvarima, nakana neodređena", "Y19.0"),
    Y20("Vješanje, davljenje i gušenje, nakana neodređena", "Y20"),
    Y20_0("Vješanje, davljenje i gušenje, nakana neodređena", "Y20.0"),
    Y21("Utapanje i potapanje, nakana neodređena", "Y21"),
    Y21_0("Utapanje i potapanje, nakana neodređena", "Y21.0"),
    Y22("Pucnjava iz pištolja, nakana neodređena", "Y22"),
    Y22_0("Pucnjava iz pištolja, nakana neodređena", "Y22.0"),
    Y23("Pucnjava iz puške, sačmarice i većega vatrenog oružja (većeg kalibra), nakana neodređena", "Y23"),
    Y23_0("Pucnjava iz puške, sačmarice i većega vatrenog oružja (većeg kalibra), nakana neodređena", "Y23.0"),
    Y24("Pucnjava iz drugoga nespecificiranoga vatrenog oružja, nakana neodređena", "Y24"),
    Y24_0("Pucnjava iz drugoga nespecificiranoga vatrenog oružja, nakana neodređena", "Y24.0"),
    Y25("Doticaj s eksplozivnim materijalom, nakana neodređena", "Y25"),
    Y25_0("Doticaj s eksplozivnim materijalom, nakana neodređena", "Y25.0"),
    Y26("Izloženost dimu, vatri i plamenu (žeravici), nakana neodređena", "Y26"),
    Y26_0("Izloženost dimu, vatri i plamenu (žeravici), nakana neodređena", "Y26.0"),
    Y27("Doticaj s parom, vrućim isparinama i vrućim predmetima, nakana neodređena", "Y27"),
    Y27_0("Doticaj s parom, vrućim isparinama i vrućim predmetima, nakana neodređena", "Y27.0"),
    Y28("Doticaj s oštrim predmetom, nakana neodređena", "Y28"),
    Y28_0("Doticaj s oštrim predmetom, nakana neodređena", "Y28.0"),
    Y29("Doticaj s tupim predmetom, nakana neodređena", "Y29"),
    Y29_0("Doticaj s tupim predmetom, nakana neodređena", "Y29.0"),
    Y30("Pad, skok ili guranje s visine, nakana neodređena", "Y30"),
    Y30_0("Pad, skok ili guranje s visine, nakana neodređena", "Y30.0"),
    Y31("Pad, ležanje ili trčanje ispred objekta ili prema objektu u pokretu, nakana neodređena", "Y31"),
    Y31_0("Pad, ležanje ili trčanje ispred objekta ili prema objektu u pokretu, nakana neodređena", "Y31.0"),
    Y32("Razbijanje motornog vozila, nakana neodređena", "Y32"),
    Y32_0("Razbijanje motornog vozila, nakana neodređena", "Y32.0"),
    Y33("Drugi specificirani događaji, nakana neodređena", "Y33"),
    Y33_0("Drugi specificirani događaji, nakana neodređena", "Y33.0"),
    Y34("Nespecificiran događaj, nakana neodređena", "Y34"),
    Y34_0("Nespecificiran događaj, nakana neodređena", "Y34.0"),
    Y35("Zakonske intervencije", "Y35"),
    Y35_0("Zakonske intervencije koje uključuju pucanj iz vatrenog oružja", "Y35.0"),
    Y35_1("Zakonska intervencija koja uključuje eksplozive", "Y35.1"),
    Y35_2("Zakonske intervencije koje uključuju plin", "Y35.2"),
    Y35_3("Zakonske intervencije koje uključuju tupe predmete", "Y35.3"),
    Y35_4("Zakonska intervencija koja uključuje oštre predmete", "Y35.4"),
    Y35_5("Zakonska (legalna) egzekucija (smrtna kazna)", "Y35.5"),
    Y35_6("Zakonska intervencija koja uključuje druge specificirane načine", "Y35.6"),
    Y35_7("Zakonska intervencija, način nespecificiran", "Y35.7"),
    Y36("Ratne operacije", "Y36"),
    Y36_0("Ratne operacije koje uključuju eksploziju pomorskih oružja", "Y36.0"),
    Y36_1("Ratne operacije koje uključuju razaranje letjelice", "Y36.1"),
    Y36_2("Ratne operacije koje uključuju ostale eksplozije i krhotine", "Y36.2"),
    Y36_3("Ratne operacije koje uključuju vatre, požare i zapaljive tvari", "Y36.3"),
    Y36_4("Ratne operacije koje uključuju vatreno oružje i druge oblike konvencionalnog ratovanja", "Y36.4"),
    Y36_5("Ratne operacije koje uključuju nuklearno oružje", "Y36.5"),
    Y36_6("Ratne operacije koje uključuju biološko oružje", "Y36.6"),
    Y36_7("Ratne operacije koje uključuju kemijsko oružje i druge oblike nekonvencionalnog ratovanja", "Y36.7"),
    Y36_8("Ratne operacije nakon obustave neprijateljstava", "Y36.8"),
    Y36_9("Ratne operacije, nespecificirane", "Y36.9"),
    Y40("Sistemni antibiotici", "Y40"),
    Y40_0("Penicilini", "Y40.0"),
    Y40_1("Cefalosporini i drugi beta-laktamski antibiotici", "Y40.1"),
    Y40_2("Kloramfenikoli", "Y40.2"),
    Y40_3("Makrolidi", "Y40.3"),
    Y40_4("Tetraciklini", "Y40.4"),
    Y40_5("Aminoglikozidi", "Y40.5"),
    Y40_6("Rifamicini", "Y40.6"),
    Y40_7("Antifungični antibiotici, primijenjeni sistemno", "Y40.7"),
    Y40_8("Drugi sistemni antibiotici", "Y40.8"),
    Y40_9("Sistemni antibiotik, nespecificiran", "Y40.9"),
    Y41("Drugi sistemni lijekovi protiv infekcija i nametnika", "Y41"),
    Y41_0("Sulfonamidi", "Y41.0"),
    Y41_1("Lijekovi protiv mikobakterija", "Y41.1"),
    Y41_2("Antimalarici i lijekovi koji djeluju na druge krvne protozoe", "Y41.2"),
    Y41_3("Drugi lijekovi protiv protozoa", "Y41.3"),
    Y41_4("Antihelmintici (lijekovi protiv crijevnih parazita)", "Y41.4"),
    Y41_5("Antivirusni lijekovi", "Y41.5"),
    Y41_8("Drugi specificirani sistemni lijekovi protiv infekcije i nametnika", "Y41.8"),
    Y41_9("Sistemni lijek protiv infekcije i nametnika, nespecificiran", "Y41.9"),
    Y42("Hormoni i njihovi sintetski analozi i antagonisti, nesvrstani drugamo", "Y42"),
    Y42_0("Glukokortikoidi i srodni sintetski lijekovi", "Y42.0"),
    Y42_1("Hormoni štitnjače i srodni lijekovi", "Y42.1"),
    Y42_2("Antitireoidni lijekovi", "Y42.2"),
    Y42_3("Inzulin i oralni hipoglikemični (antidijabetični) lijekovi", "Y42.3"),
    Y42_4("Oralni kontraceptivi", "Y42.4"),
    Y42_5("Drugi estrogeni i gestageni", "Y42.5"),
    Y42_6("Antigonadotropini, antiestrogeni, antiandrogeni, nesvrstani drugamo", "Y42.6"),
    Y42_7("Androgeni i srodni anabolici", "Y42.7"),
    Y42_8("Ostali i nespecificirani hormoni i njihovi sintetski analozi", "Y42.8"),
    Y42_9("Drugi i nespecificirani antagonisti hormona", "Y42.9"),
    Y43("Primarno sistemni lijekovi", "Y43"),
    Y43_0("Antialergijski i antiemetični lijekovi", "Y43.0"),
    Y43_1("Antineoplastični antimetaboliti", "Y43.1"),
    Y43_2("Antineoplastični prirodni produkti", "Y43.2"),
    Y43_3("Drugi antineoplastični lijekovi", "Y43.3"),
    Y43_4("Imunosupresivna sredstva", "Y43.4"),
    Y43_5("Sredstva za acidifikaciju i alkalinizaciju", "Y43.5"),
    Y43_6("Enzimi koji nisu svrstani drugamo", "Y43.6"),
    Y43_8("Druga primarno sistemna sredstva koja nisu svrstana drugamo", "Y43.8"),
    Y43_9("Primarno sistemno sredstvo, nespecificirano", "Y43.9"),
    Y44("Lijekovi koji primarno djeluju na krvne sastojke", "Y44"),
    Y44_0("Pripravci željeza i drugi lijekovi za liječenje hipokromne anemije (anemije zbog nedostatka željeza)", "Y44.0"),
    Y44_1("Vitamin B12, folna kiselina i drugi lijekovi za liječenje megaloblastične anemije", "Y44.1"),
    Y44_2("Antikoagulansi (sredstva protiv zgrušavanja krvi)", "Y44.2"),
    Y44_3("Antagonisti antikoagulansa, vitamin K i drugi koagulansi", "Y44.3"),
    Y44_4("Inhibitori agregacije trombocita", "Y44.4"),
    Y44_5("Trombolitični lijekovi", "Y44.5"),
    Y44_6("Prirodna krv i krvni pripravci", "Y44.6"),
    Y44_7("Nadomjesci plazme", "Y44.7"),
    Y44_9("Drugi i nespecificirani lijekovi koji djeluju na krvne sastojke", "Y44.9"),
    Y45("Analgetici, antipiretici i antiinflamatorni lijekovi", "Y45"),
    Y45_0("Opioidi i srodni analgetici", "Y45.0"),
    Y45_1("Salicilati", "Y45.1"),
    Y45_2("Derivati propionske kiseline", "Y45.2"),
    Y45_3("Drugi nesteroidni antiinflamatorni lijekovi (NSAID)", "Y45.3"),
    Y45_4("Antireumatici", "Y45.4"),
    Y45_5("Derivati 4-aminofenola", "Y45.5"),
    Y45_8("Drugi analgetici i antipiretici", "Y45.8"),
    Y45_9("Analgetik, antipiretik i antiinflamatorni lijek, nespecificiran", "Y45.9"),
    Y46("Antiepileptici i antiparkinsonici", "Y46"),
    Y46_0("Sukcinimidi", "Y46.0"),
    Y46_1("Oksazolidindioni", "Y46.1"),
    Y46_2("Derivati hidantoina", "Y46.2"),
    Y46_3("Deoksibarbiturati", "Y46.3"),
    Y46_4("Iminostilbeni", "Y46.4"),
    Y46_5("Valproična kiselina", "Y46.5"),
    Y46_6("Drugi i nespecificirani antiepileptici", "Y46.6"),
    Y46_7("Antiparkinsonici", "Y46.7"),
    Y46_8("Antispastični lijekovi", "Y46.8"),
    Y47("Sedativi, hipnotici i anksiolitici", "Y47"),
    Y47_0("Barbiturati nesvrstani drugamo", "Y47.0"),
    Y47_1("Benzodiazepini", "Y47.1"),
    Y47_2("Derivati klorala", "Y47.2"),
    Y47_3("Paraldehidi", "Y47.3"),
    Y47_4("Spojevi broma", "Y47.4"),
    Y47_5("Mješoviti sedativi i hipnotici, nesvrstani drugamo", "Y47.5"),
    Y47_8("Drugi sedativi, hipnotici i anksiolitici", "Y47.8"),
    Y47_9("Sedativ, hipnotik i anksiolitik, nespecificiran", "Y47.9"),
    Y48("Anestetici i terapijski plinovi", "Y48"),
    Y48_0("Inhalacijski anestetici", "Y48.0"),
    Y48_1("Parenteralni anestetici", "Y48.1"),
    Y48_2("Drugi i nespecificirani opći anestetici", "Y48.2"),
    Y48_3("Lokalni anestetici", "Y48.3"),
    Y48_4("Anestetik, nespecificiran", "Y48.4"),
    Y48_5("Terapijski plinovi", "Y48.5"),
    Y49("Psihotropni lijekovi, nesvrstani drugamo", "Y49"),
    Y49_0("Triciklični i tetraciklični antidepresivi", "Y49.0"),
    Y49_1("Antidepresivi iz skupine inhibitora monoamino-oksidaze", "Y49.1"),
    Y49_2("Drugi i nespecificirani antidepresivi", "Y49.2"),
    Y49_3("Fenotijazinski antipsihotici i neuroleptici", "Y49.3"),
    Y49_4("Butirofenonski i tioksantenski neuroleptici", "Y49.4"),
    Y49_5("Drugi antipsihotici i neuroleptici", "Y49.5"),
    Y49_6("Halucinogeni (psihodisleptici)", "Y49.6"),
    Y49_7("Psihostimulansi sa sposobnošću uzrokovanja ovisnosti", "Y49.7"),
    Y49_8("Drugi psihotropni lijekovi, nesvrstani drugamo", "Y49.8"),
    Y49_9("Psihotropni lijek, nespecificiran", "Y49.9"),
    Y50("Stimulatori središnjeg živčanog sustava, nesvrstani drugamo", "Y50"),
    Y50_0("Analaptici", "Y50.0"),
    Y50_1("Antagonisti opioidnih receptora", "Y50.1"),
    Y50_2("Metilksantini, nesvrstani drugamo", "Y50.2"),
    Y50_8("Drugi stimulatori središnjeg živčanog sustava", "Y50.8"),
    Y50_9("Stimulator središnjega živčanog sustava, nespecificiran", "Y50.9"),
    Y51("Lijekovi koji primarno djeluju na autonomni živčani sustav", "Y51"),
    Y51_0("Antikolinesterazni agensi", "Y51.0"),
    Y51_1("Drugi parasimpatomimetici (kolinergici)", "Y51.1"),
    Y51_2("Ganglioblokatori, nesvrstani drugamo", "Y51.2"),
    Y51_3("Drugi parasimpatikolitici (antikolinergici i antimuskarinske tvari) i spazmolitici nesvrstani drugamo", "Y51.3"),
    Y51_4("Ekscitatori alfa-adrenergičnih receptora, nesvrstani drugamo", "Y51.4"),
    Y51_5("Ekscitatori beta-adrenergičnih receptora, nesvrstani drugamo", "Y51.5"),
    Y51_6("Blokatori alfa-adrenergičnih receptora, nesvrstani drugamo", "Y51.6"),
    Y51_7("Blokatori beta-adrenergičnih receptora, nesvrstani drugamo", "Y51.7"),
    Y51_8("Lijekovi centralnog djelovanja i blokatori adrenergičnih neurona, nesvrstani drugamo", "Y51.8"),
    Y51_9("Drugi i nespecificirani lijekovi koji primarno djeluju na autonomni živčani sustav", "Y51.9"),
    Y52("Lijekovi koji primarno djeluju na kardiovaskularni sustav", "Y52"),
    Y52_0("Kardiotonični glikozidi i drugi lijekovi slična djelovanja", "Y52.0"),
    Y52_1("Antagonisti kalcija", "Y52.1"),
    Y52_2("Drugi antiaritmici nesvrstani drugamo", "Y52.2"),
    Y52_3("Koronarni vazodilatatori nesvrstani drugamo", "Y52.3"),
    Y52_4("Inhibitori angiotenzin-konvertaze", "Y52.4"),
    Y52_5("Drugi antihipertenzivni lijekovi nesvrstani drugamo", "Y52.5"),
    Y52_6("Antihiperlipemični i antiaterosklerotični lijekovi", "Y52.6"),
    Y52_7("Periferni vazodilatatori", "Y52.7"),
    Y52_8("Antivarikozni lijekovi, uključujući sklerozirajuće tvari", "Y52.8"),
    Y52_9("Drugi i nespecificirani lijekovi koji primarno djeluju na kardiovaskularni sustav", "Y52.9"),
    Y53("Lijekovi koji primarno djeluju na probavni sustav", "Y53"),
    Y53_0("Blokatori H2-receptora", "Y53.0"),
    Y53_1("Drugi antacidi i antiulkusna sredstva", "Y53.1"),
    Y53_2("Kemijski laksativi", "Y53.2"),
    Y53_3("Salinični i osmotski laksativi", "Y53.3"),
    Y53_4("Drugi laksativi", "Y53.4"),
    Y53_5("Digestivi", "Y53.5"),
    Y53_6("Antidijaroici", "Y53.6"),
    Y53_7("Emetici", "Y53.7"),
    Y53_8("Drugi lijekovi koji primarno djeluju na probavni sustav", "Y53.8"),
    Y53_9("Lijek koji primarno djeluje na probavni sustav, nespecificiran", "Y53.9"),
    Y54("Lijekovi koji djeluju na ravnotežu tjelesnih tekućina i metabolizam minerala i mokraćne kiseline", "Y54"),
    Y54_0("Mineralokortikoidi", "Y54.0"),
    Y54_1("Antagonisti mineralokortikoida (antagonisti aldosterona)", "Y54.1"),
    Y54_2("Inhibitori karboanhidraze", "Y54.2"),
    Y54_3("Derivati benzotiadiazina", "Y54.3"),
    Y54_4("Diuretici koji djeluju na ulazni krak Henleove petlje", "Y54.4"),
    Y54_5("Drugi diuretici", "Y54.5"),
    Y54_6("Lijekovi za nadoknadu tjelesnih tekućina, elektrolita i kalorija", "Y54.6"),
    Y54_7("Lijekovi koji djeluju na kalcifikaciju", "Y54.7"),
    Y54_8("Lijekovi koji djeluju na metabolizam mokraćne (urične) kiseline", "Y54.8"),
    Y54_9("Mineralne soli nesvrstane drugamo", "Y54.9"),
    Y55("Lijekovi koji primarno djeluju na glatko i skeletno mišićje i dišni sustav", "Y55"),
    Y55_0("Oksitocična sredstva", "Y55.0"),
    Y55_1("Relaksatori skeletnog mišićja (blokatori neuromuskularne veze)", "Y55.1"),
    Y55_2("Drugi i nespecificirani lijekovi koji primarno djeluju na mišićje", "Y55.2"),
    Y55_3("Antitustici", "Y55.3"),
    Y55_4("Ekspektoransi", "Y55.4"),
    Y55_5("Lijekovi protiv obične prehlade", "Y55.5"),
    Y55_6("Antiastmatici nesvrstani drugamo", "Y55.6"),
    Y55_7("Drugi i nespecificirani lijekovi koji primarno djeluju na dišni sustav", "Y55.7"),
    Y56("Lijekovi za lokalnu primjenu koji primarno djeluju na kožu i sluznice te oftalmološki, otorinolaringološki i stomatološki lijekovi", "Y56"),
    Y56_0("Lokalni antifungični, antiinfektivni i antiinflamatorni lijekovi, nesvrstani drugamo", "Y56.0"),
    Y56_1("Antipruriginozna sredstva", "Y56.1"),
    Y56_2("Lokalni adstringensi i lokalni detergensi", "Y56.2"),
    Y56_3("Emolijencije, demulcencije i zaštitna sredstva", "Y56.3"),
    Y56_4("Keratolitici, keratoplastici i drugi lijekovi i pripravci za kosu", "Y56.4"),
    Y56_5("Oftalmološki lijekovi i pripravci", "Y56.5"),
    Y56_6("Otorinolaringološki lijekovi i pripravci", "Y56.6"),
    Y56_7("Stomatološki lijekovi, primijenjeni lokalno", "Y56.7"),
    Y56_8("Druga lokalna sredstva", "Y56.8"),
    Y56_9("Lokalno sredstvo, nespecificirano", "Y56.9"),
    Y57("Drugi i nespecificirani lijekovi i ljekoviti pripravci", "Y57"),
    Y57_0("Lijekovi za suzbijanje teka (anorektici)", "Y57.0"),
    Y57_1("Lipotropni lijekovi", "Y57.1"),
    Y57_2("Antidoti i druga helatogena sredstva nesvrstana drugamo", "Y57.2"),
    Y57_3("Sredstva za odvikavanje od alkohola", "Y57.3"),
    Y57_4("Farmaceutski ekscipiensi (podloge)", "Y57.4"),
    Y57_5("Rendgenska kontrastna sredstva", "Y57.5"),
    Y57_6("Druga dijagnostička sredstva", "Y57.6"),
    Y57_7("Vitamini nesvrstani drugamo", "Y57.7"),
    Y57_8("Drugi lijekovi i ljekoviti pripravci", "Y57.8"),
    Y57_9("Lijek ili ljekoviti pripravak, nespecificiran", "Y57.9"),
    Y58("Bakterijska cjepiva", "Y58"),
    Y58_0("Cjepivo protiv tuberkuloze", "Y58.0"),
    Y58_1("Cjepivo protiv tifusa i paratifusa", "Y58.1"),
    Y58_2("Cjepivo protiv kolere", "Y58.2"),
    Y58_3("Cjepivo protiv kuge", "Y58.3"),
    Y58_4("Cjepivo protiv tetanusa", "Y58.4"),
    Y58_5("Cjepivo protiv difterije", "Y58.5"),
    Y58_6("Cjepivo protiv pertusisa, uključujući kombinacije s pertusisnom komponentom", "Y58.6"),
    Y58_8("Miješano bakterijsko cjepivo, osim kombinacija s pertusisnom komponentom", "Y58.8"),
    Y58_9("Druga i nespecificirana bakterijska cjepiva", "Y58.9"),
    Y59("Druga i nespecificirana cjepiva i biološke tvari", "Y59"),
    Y59_0("Cjepiva protiv virusa", "Y59.0"),
    Y59_1("Cjepiva protiv rikecija", "Y59.1"),
    Y59_2("Cjepiva protiv protozoa", "Y59.2"),
    Y59_3("Imunoglobulin", "Y59.3"),
    Y59_8("Druga specificirana cjepiva i biološke tvari", "Y59.8"),
    Y59_9("Cjepivo ili biološka tvar, nespecificirana", "Y59.9"),
    Y60("Nenamjeski rez, ubod, perforacija ili krvarenje u tijeku kirurškog i medicinskog zbrinjavanja", "Y60"),
    Y60_0("U tijeku kirurške operacije", "Y60.0"),
    Y60_1("U tijeku infuzije ili transfuzije", "Y60.1"),
    Y60_2("U tijeku bubrežne dijalize ili druge perfuzije", "Y60.2"),
    Y60_3("U tijeku davanja injekcije ili imunizacije", "Y60.3"),
    Y60_4("U tijeku endoskopske pretrage", "Y60.4"),
    Y60_5("U tijeku kateterizacije srca", "Y60.5"),
    Y60_6("U tijeku aspiracije, punkcije i druge kateterizacije", "Y60.6"),
    Y60_7("U tijeku davanja klistira", "Y60.7"),
    Y60_8("U tijeku drugoga kirurškog i medicinskog zbrinjavanja", "Y60.8"),
    Y60_9("U tijeku nespecificiranog kirurškog i medicinskog zbrinjavanja", "Y60.9"),
    Y61("Strani predmet slučajno ostavljen u tijelu u tijeku kirurškog i medicinskog zbrinjavanja", "Y61"),
    Y61_0("U tijeku kirurške operacije", "Y61.0"),
    Y61_1("U tijeku infuzije ili transfuzije", "Y61.1"),
    Y61_2("U tijeku bubrežne dijalize ili druge perfuzije", "Y61.2"),
    Y61_3("U tijeku davanja injekcije ili imunizacije", "Y61.3"),
    Y61_4("U tijeku endoskopske pretrage", "Y61.4"),
    Y61_5("U tijeku kateterizacije srca", "Y61.5"),
    Y61_6("U tijeku aspiracije, punkcije i druge kateterizacije", "Y61.6"),
    Y61_7("U tijeku odstranjivanja katetera ili zavoja", "Y61.7"),
    Y61_8("U tijeku drugog kirurškog i medicinskog zbrinjavanja", "Y61.8"),
    Y61_9("U tijeku nespecificiranog kirurškog i medicinskog zbrinjavanja", "Y61.9"),
    Y62("Pogreška u provođenju mjera sterilnosti u tijeku kirurškog i medicinskog zbrinjavanja", "Y62"),
    Y62_0("U tijeku kirurške operacije", "Y62.0"),
    Y62_1("U tijeku infuzije ili transfuzije", "Y62.1"),
    Y62_2("U tijeku bubrežne dijalize ili druge perfuzije", "Y62.2"),
    Y62_3("U tijeku davanja injekcije ili imunizacije", "Y62.3"),
    Y62_4("U tijeku endoskopske pretrage", "Y62.4"),
    Y62_5("U tijeku kateterizacije srca", "Y62.5"),
    Y62_6("U tijeku aspiracije, punkcije i druge kateterizacije", "Y62.6"),
    Y62_8("U tijeku drugoga kirurškog i medicinskog zbrinjavanja", "Y62.8"),
    Y62_9("U tijeku nespecificiranog kirurškog i medicinskog zbrinjavanja", "Y62.9"),
    Y63("Pogreška u doziranju u tijeku kirurškog i medicinskog zbrinjavanja", "Y63"),
    Y63_0("Prekomjerna količina krvi ili druge tekućine primljena u tijeku transfuzije ili infuzije", "Y63.0"),
    Y63_1("Pogrešno razrjeđenje tekućine upotrijebljene u tijeku infuzije", "Y63.1"),
    Y63_2("Prekomjerna doza zračenja primljena u tijeku terapije", "Y63.2"),
    Y63_3("Nesmotreno izlaganje bolesnika zračenju u tijeku medicinskog zbrinjavanja", "Y63.3"),
    Y63_4("Pogreška u doziranju kod elektrošoka ili inzulinske šokterapije", "Y63.4"),
    Y63_5("Neodgovarajuća temperatura pri lokalnoj primjeni i zavoju", "Y63.5"),
    Y63_6("Nedavanje prijeko potrebnog lijeka, ljekovitog pripravka ili biološke supstancije", "Y63.6"),
    Y63_8("Pogreška u doziranju u tijeku drugoga kirurškog i medicinskog zbrinjavanja", "Y63.8"),
    Y63_9("Pogreška u doziranju u tijeku nespecificiranog kirurškog i medicinskog zbrinjavanja", "Y63.9"),
    Y64("Onečišćene medicinske ili biološke tvari", "Y64"),
    Y64_0("Onečišćena medicinska ili biološka tvar primijenjena u transfuziji ili infuziji", "Y64.0"),
    Y64_1("Onečišćena medicinska ili biološka tvar primijenjena u injekciji ili za imunizaciju", "Y64.1"),
    Y64_8("Onečišćena medicinska ili biološka tvar primijenjena na drugi način", "Y64.8"),
    Y64_9("Onečišćena medicinska ili biološka tvar primijenjena na nespecificirani način", "Y64.9"),
    Y65("Druge nezgode u tijeku kirurškog i medicinskog zbrinjavanja", "Y65"),
    Y65_0("Neodgovarajuća krv upotrijebljena u transfuziji", "Y65.0"),
    Y65_1("Pogrešna tekućina upotrijebljena u infuziji", "Y65.1"),
    Y65_2("Pogreška u šavovima ili ligaturi u tijeku kirurške operacije", "Y65.2"),
    Y65_3("Pogrešno smješten endotrahealni tubus u tijeku anestezijskog postupka", "Y65.3"),
    Y65_4("Pogreška u uvođenju ili odstranjivanju drugog tubusa ili instrumenta", "Y65.4"),
    Y65_5("Izvođenje neodgovarajuće operacije", "Y65.5"),
    Y65_9("Druge specificirane nezgode u tijeku kirurškog i medicinskog zbrinjavanja", "Y65.9"),
    Y66("Neprimjenjivanje kirurškog i medicinskog zbrinjavanja", "Y66"),
    Y66_0("Neprimjenjivanje kirurškog i medicinskog zbrinjavanja", "Y66.0"),
    Y69("Nespecificirana nezgoda u tijeku kirurškog i medicinskog zbrinjavanja", "Y69"),
    Y69_0("Nespecificirana nezgoda u tijeku kirurškog i medicinskog zbrinjavanja", "Y69.0"),
    Y70("Anesteziološka sredstva povezana s nepovoljnim događajem", "Y70"),
    Y70_0("Anesteziološka sredstva povezana s nepovoljnim događajem", "Y70.0"),
    Y71("Kardiovaskularna sredstva povezana s nepovoljnim događajem", "Y71"),
    Y71_0("Kardiovaskularna sredstva povezana s nepovoljnim događajem", "Y71.0"),
    Y72("Otorinolaringološka sredstva povezana s nepovoljnim događajem", "Y72"),
    Y72_0("Otorinolaringološka sredstva povezana s nepovoljnim događajem", "Y72.0"),
    Y73("Gastroenterološka i urološka sredstva povezana s nepovoljnim događajem", "Y73"),
    Y73_0("Gastroenterološka i urološka sredstva povezana s nepovoljnim događajem", "Y73.0"),
    Y74("Opća bolnička i sredstva za osobnu upotrebu povezana s nepovoljnim događajem", "Y74"),
    Y74_0("Opća bolnička i sredstva za osobnu upotrebu povezana s nepovoljnim događajem", "Y74.0"),
    Y75("Neurološka sredstva povezana s nepovoljnim događajem", "Y75"),
    Y75_0("Neurološka sredstva povezana s nepovoljnim događajem", "Y75.0"),
    Y76("Porodnička i ginekološka sredstva povezana s nepovoljnim događajem", "Y76"),
    Y76_0("Porodnička i ginekološka sredstva povezana s nepovoljnim događajem", "Y76.0"),
    Y77("Oftalmološka sredstva povezana s nepovoljnim događajem", "Y77"),
    Y77_0("Oftalmološka sredstva povezana s nepovoljnim događajem", "Y77.0"),
    Y78("Radiološka sredstva povezana s nepovoljnim događajem", "Y78"),
    Y78_0("Radiološka sredstva povezana s nepovoljnim događajem", "Y78.0"),
    Y79("Ortopedska sredstva povezana s nepovoljnim događajem", "Y79"),
    Y79_0("Ortopedska sredstva povezana s nepovoljnim događajem", "Y79.0"),
    Y80("Fizikalnomedicinska sredstva povezana s nepovoljnim događajem", "Y80"),
    Y80_0("Fizikalnomedicinska sredstva povezana s nepovoljnim događajem", "Y80.0"),
    Y81("Sredstva opće i plastične kirurgije povezana s nepovoljnim događajem", "Y81"),
    Y81_0("Sredstva opće i plastične kirurugije povezana s nepovoljnim događajem", "Y81.0"),
    Y82("Druga i nespecificirana medicinska sredstva povezana s nepovoljnim događajem", "Y82"),
    Y82_0("Druga i nespecificirana medicinska sredstva povezana s nepovoljnim događajem", "Y82.0"),
    Y83("Kirurška operacija i drugi kirurški postupak kao uzrok bolesnikove abnormalne reakcije, ili kasnije komplikacije, bez napomene o nezgodi u tijeku postupka", "Y83"),
    Y83_0("Kirurška operacija s transplantacijom čitavog organa", "Y83.0"),
    Y83_1("Kirurška operacija s implantacijom umjetnoga unutrašnjeg sredstva", "Y83.1"),
    Y83_2("Kirurška operacija s anastomozom, premoštenjem (bypass) ili presatkom", "Y83.2"),
    Y83_3("Kirurška operacija s oblikovanjem vanjske stome", "Y83.3"),
    Y83_4("Drugi rekonstruktivni kirurški zahvati", "Y83.4"),
    Y83_5("Amputacija uda (udova)", "Y83.5"),
    Y83_6("Odstranjivanje drugog organa (djelomično) (potpuno)", "Y83.6"),
    Y83_8("Drugi kirurški postupci", "Y83.8"),
    Y83_9("Kirurški postupak, nespecificiran", "Y83.9"),
    Y84("Drugi medicinski postupci kao uzrok bolesnikove abnormalne reakcije, ili kasnije komplikacije, bez napomene o nezgodi u tijeku postupka", "Y84"),
    Y84_0("Kateterizacija srca", "Y84.0"),
    Y84_1("Bubrežna dijaliza", "Y84.1"),
    Y84_2("Radiološki postupci i radioterapija", "Y84.2"),
    Y84_3("Terapija šoka", "Y84.3"),
    Y84_4("Aspiracija tekućine", "Y84.4"),
    Y84_5("Uvođenje želučane ili duodenalne sonde", "Y84.5"),
    Y84_6("Kateterizacija mokraćovoda", "Y84.6"),
    Y84_7("Uzimanje uzorka krvi", "Y84.7"),
    Y84_8("Drugi medicinski postupci", "Y84.8"),
    Y84_9("Medicinski postupak, nespecificiran", "Y84.9"),
    Y85("Posljedice nezgode pri prijevozu", "Y85"),
    Y85_0("Posljedice nezgode uzrokovane motornim vozilom", "Y85.0"),
    Y85_9("Posljedice ostalih i nespecificiranih nezgoda pri prijevozu", "Y85.9"),
    Y86("Posljedice drugih nezgoda", "Y86"),
    Y86_0("Posljedice drugih nezgoda", "Y86.0"),
    Y87("Posljedice namjernog samoozljeđivanja, napadaja i događaja nespecificirane nakane", "Y87."),
    Y87_0("Posljedice namjernog samoozljeđivanja", "Y87.0"),
    Y87_1("Posljedice napadaja", "Y87.1"),
    Y87_2("Posljedice događaja neodređene nakane", "Y87.2"),
    Y88("Posljedice kirurškog ili medicinskog zbrinjavanja kao vanjskog uzroka", "Y88"),
    Y88_0("Posljedice štetna djelovanja lijekova, ljekovitog pripravka i bioloških supstancija u terapijskoj uporabi", "Y88.0"),
    Y88_1("Posljedice nezgoda za bolesnika u tijeku kirurških i medicinskih postupaka", "Y88.1"),
    Y88_2("Posljedice štetnih događaja povezanih s medicinskim sredstvima u dijagnostičkoj ili terapijskoj uporabi", "Y88.2"),
    Y88_3("Posljedice kirurških i medicinskih postupaka kao uzroka bolesnikove nenormalne reakcije, ili kasnije komplikacije, bez napomene o nezgodi u tijeku postupka", "Y88.3"),
    Y89("Posljedice ostalih vanjskih uzroka", "Y89"),
    Y89_0("Posljedice legalnih intervencija", "Y89.0"),
    Y89_1("Posljedice ratnih operacija", "Y89.1"),
    Y89_9("Posljedice nespecificirana vanjskog uzroka", "Y89.9"),
    Y90("Dokaz o prisutnosti alkohola određen razinom alkohola u krvi", "Y90."),
    Y90_0("Razina alkohola u krvi manja od 20 mg/100 ml.", "Y90.0"),
    Y90_1("Razina alkohola u krvi od 20 do 39 mg/100 ml.", "Y90.1"),
    Y90_2("Razina alkohola u krvi od 40 do 59 mg/100 ml.", "Y90.2"),
    Y90_3("Razina alkohola u krvi od 60 do 79 mg/100 ml.", "Y90.3"),
    Y90_4("Razina alkohola u krvi od 80 do 99 mg/100 ml.", "Y90.4"),
    Y90_5("Razina alkohola u krvi od 100 do 119 mg/100 ml.", "Y90.5"),
    Y90_6("Razina alkohola u krvi od 120 do 199 mg/100 ml.", "Y90.6"),
    Y90_7("Razina alkohola u krvi od 2OO do 239 mg/100 ml.", "Y90.7"),
    Y90_8("Razina alkohola u krvi od 240 mg/100 ml i više", "Y90.8"),
    Y90_9("Prisutnost alkohola u krvi, razina nespecificirana", "Y90.9"),
    Y91("Dokaz o prisutnosti alkohola određen stupnjem intoksikacije", "Y91"),
    Y91_0("Blaga alkoholna intoksikacija", "Y91.0"),
    Y91_1("Umjerena alkoholna intoksikacija", "Y91.1"),
    Y91_2("Teška alkoholna intoksikacija", "Y91.2"),
    Y91_3("Vrlo teška alkoholna intoksikacija", "Y91.3"),
    Y91_9("Prisutnost alkohola koja nije drukčije specificirana", "Y91.9"),
    Y95("Intrahospitalna stanja", "Y95"),
    Y95_0("Intrahospitalna stanja", "Y95.0"),
    Y96("Stanja povezana s radom", "Y96"),
    Y96_0("Stanja povezana s radom", "Y96.0"),
    Y97("Stanja povezana s onečišćenjem okoliša", "Y97"),
    Y97_0("Stanja povezana s onečišćenjem okoliša", "Y97.0"),
    Y98("Stanja povezana s načinom života", "Y98"),
    Y98_0("Stanja povezana s načinom života", "Y98.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesY(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
