package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesE {
    E00("Prirođeni sindrom manjka joda", "E00"),
    E00_0("Prirođeni sindrom manjka joda, neurološki tip", "E00.0"),
    E00_1("Prirođeni sindrom manjka joda, miksedematozni tip", "E00.1"),
    E00_2("Prirođeni sindrom manjka joda, mješoviti tip", "E00.2"),
    E00_9("Prirođeni sindrom manjka joda, nespecificiran", "E00.9"),
    E01("Poremećaji štitnjače i prateća stanja uvjetovana manjkom joda", "E01"),
    E01_0("Difuzna (endemska) struma uvjetovana manjkom joda", "E01.0"),
    E01_1("Multinodularna (endemska) struma uvjetovana manjkom joda", "E01.1"),
    E01_2("Struma (endemska) uvjetovana manjkom joda, nespecificirana", "E01.2"),
    E01_8("Drugi poremećaji štitnjače i prateća stanja uvjetovani manjkom joda", "E01.8"),
    E02("Supklinička hipotireoza zbog manjka joda", "E02"),
    E02_0("Supklinička hipotireoza zbog manjka joda", "E02.0"),
    E03("Ostale hipotireoze", "E03"),
    E03_0("Prirođena hipotireoza s difuznom strumom", "E03.0"),
    E03_1("Prirođena hipotireoza bez strume", "E03.1"),
    E03_2("Hipotireoza uzrokovana lijekovima i drugim egzogenim tvarima", "E03.2"),
    E03_3("Postinfekcijska hipotireoza", "E03.3"),
    E03_4("Atrofija štitnjače (stečena)", "E03.4"),
    E03_5("Miksedematozna koma", "E03.5"),
    E03_8("Druga specificirana hipotireoza", "E03.8"),
    E03_9("Hipotireoza, nespecificirana", "E03.9"),
    E04("Druge netoksične guše (strume)", "E04"),
    E04_0("Netoksična difuzna struma", "E04.0"),
    E04_1("Netoksični (pojedinačni) čvor štitnjače", "E04.1"),
    E04_2("Netoksična multinodularna struma", "E04.2"),
    E04_8("Ostale specificirane netoksične strume", "E04.8"),
    E04_9("Netoksična struma, nespecificirana", "E04.9"),
    E05("Tireotoksikoza (hipertireoza)", "E05"),
    E05_0("Tireotoksikoza s difuznom strumom", "E05.0"),
    E05_1("Tireotoksikoza s jednim toksičnim čvorom štitnjače", "E05.1"),
    E05_2("Tireotoksikoza s toksičnom multinodularnom gušavosti", "E05.2"),
    E05_3("Tireotoksikoza iz ektopičnoga tkiva štitnjače", "E05.3"),
    E05_4("Thyrotoxicosis factitia", "E05.4"),
    E05_5("Tireoidna kriza ili tireotoksična oluja", "E05.5"),
    E05_8("Tireotoksikoza drugog podrijetla", "E05.8"),
    E05_9("Tireotoksikoza, nespecificirana", "E05.9"),
    E06("Tireoiditis", "E06"),
    E06_0("Akutni tireoiditis", "E06.0"),
    E06_1("Subakutni tireoiditis", "E06.1"),
    E06_2("Kronični tireoiditis s prolaznom tireotoksikozom", "E06.2"),
    E06_3("Autoimuni tireoiditis", "E06.3"),
    E06_4("Tireoiditis uzrokovan lijekom", "E06.4"),
    E06_5("Ostali kronični tireoiditisi", "E06.8"),
    E06_9("Tireoiditis, nespecificiran", "E06.9"),
    E07("Drugi poremećaji štitnjače", "E07"),
    E07_0("Hipersekrecija kalcitonina", "E07.0"),
    E07_1("Gušavost s genetskim hormonalnim disbalansom", "E07.1"),
    E07_8("Drugi specificirani poremećaji štitnjače", "E07.8"),
    E07_9("Poremećaj štitnjače, nespecificiran", "E07.9"),
    E10("Dijabetes melitus ovisan o inzulinu", "E10"),
    E10_0("Dijabetes melitus ovisan o inzulinu", "E10.0"),
    E10_1("Dijabetes melitus ovisan o inzulinu, s ketoacidozom", "E10.1"),
    E10_2("Dijabetes melitus ovisan o inzulinu, s bubrežnim komplikacijama", "E10.2"),
    E10_3("Dijabetes melitus ovisan o inzulinu, s očnim komplikacijama", "E10.3"),
    E10_4("Dijabetes melitus ovisan o inzulinu, s neurološkim komplikacijama", "E10.4"),
    E10_5("Dijabetes melitus ovisan o inzulinu, s perifernim cirkulacijskim komplikacijama", "E10.5"),
    E10_6("Dijabetes melitus ovisan o inzulinu, s drugim specificiranim komplikacijama", "E10.6"),
    E10_7("Dijabetes melitus ovisan o inzulinu, s višestrukim komplikacijama", "E10.7"),
    E10_8("Dijabetes melitus ovisan o inzulinu, s nespecificiranim komplikacijama", "E10.8"),
    E10_9("Dijabetes melitus ovisan o inzulinu, bez komplikacija", "E10.9"),
    E11("Dijabetes melitus neovisan o inzulinu", "E11"),
    E11_0("Dijabetes melitus neovisan o inzulinu", "E11.0"),
    E11_1("Dijabetes melitus neovisan o inzulinu, s ketoacidozom", "E11.1"),
    E11_2("Dijabetes melitus neovisan o inzulinu, s bubrežnim komplikacijama", "E11.2"),
    E11_3("Dijabetes melitus neovisan o inzulinu, s očnim komplikacijama", "E11.3"),
    E11_4("Dijabetes melitus neovisan o inzulinu, s neurološkim komplikacijama", "E11.4"),
    E11_5("Dijabetes melitus neovisan o inzulinu, s perifernim cirkulacijskim komplikacijama", "E11.5"),
    E11_6("Dijabetes melitus neovisan o inzulinu, s drugim specificiranim komplikacijama", "E11.6"),
    E11_7("Dijabetes melitus neovisan o inzulinu, s višestrukim komplikacijama", "E11.7"),
    E11_8("Dijabetes melitus neovisan o inzulinu, s nespecificiranim komplikacijama", "E11.8"),
    E11_9("Dijabetes melitus neovisan o inzulinu, bez komplikacija", "E11.9"),
    E12("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski)", "E12"),
    E12_0("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski)", "E12.0"),
    E12_1("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s ketoacidozom", "E12.1"),
    E12_2("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s bubrežnim komplikacijama", "E12.2"),
    E12_3("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s očnim komplikacijama", "E12.3"),
    E12_4("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s neurološkim komplikacijama", "E12.4"),
    E12_5("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s perifernim cirkulacijskim komplikacijama", "E12.5"),
    E12_6("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s drugim specificiranim komplikacijama", "E12.6"),
    E12_7("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s višestrukim komplikacijama", "E12.7"),
    E12_8("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), s nespecificiranim komplikacijama", "E12.8"),
    E12_9("Dijabetes melitus uvjetovan pothranjenošću (malnutricijski), bez komplikacija", "E12.9"),
    E13("Drugi specificirani dijabetes melitus", "E13"),
    E13_0("Drugi specificirani dijabetes metlitus", "E13.0"),
    E13_1("Drugi specificirani dijabetes melitus, s ketoacidozom", "E13.1"),
    E13_2("Drugi specificirani dijabetes melitus, s bubrežnim komplikacijama", "E13.2"),
    E13_3("Drugi specificirani dijabetes melitus, s očnim komplikacijama", "E13.3"),
    E13_4("Drugi specificirani dijabetes melitus, s neurološkim komplikacijama", "E13.4"),
    E13_5("Drugi specificirani dijabetes melitus, s perifernim cirkulacijskim komplikacijama", "E13.5"),
    E13_6("Drugi specificirani dijabetes melitus, s drugim specificiranim komplikacijama", "E13.6"),
    E13_7("Drugi specificirani dijabetes melitus, s višestrukim komplikacijama", "E13.7"),
    E13_8("Drugi specificirani dijabetes melitus, s nespecificiranim komplikacijama", "E13.8"),
    E13_9("Drugi specificirani dijabetes melitus, bez komplikacija", "E13.9"),
    E14("Dijabetes melitus, nespecificirani", "E14"),
    E14_0("Dijabetes melitus, nespecificirani", "E14.0"),
    E14_1("Dijabetes melitus, nespecificirani, s ketoacidozom", "E14.1"),
    E14_2("Dijabetes melitus, nespecificirani, s bubrežnim komplikacijama", "E14.2"),
    E14_3("Dijabetes melitus, nespecificirani, s očnim komplikacijama", "E14.3"),
    E14_4("Dijabetes melitus, nespecificirani, s neurološkim komplikacijama", "E14.4"),
    E14_5("Dijabetes melitus, nespecificirani, s perifernim cirkulacijskim komplikacijama", "E14.5"),
    E14_6("Dijabetes melitus, nespecificirani, s drugim specificiranim komplikacijama", "E14.6"),
    E14_7("Dijabetes melitus, nespecificirani, s višestrukim komplikacijama", "E14.7"),
    E14_8("Dijabetes melitus, nespecificirani, s nespecificiranim komplikacijama", "E14.8"),
    E14_9("Dijabetes melitus, nespecificirani, bez komplikacija", "E14.9"),
    E15("Nedijabetična hipoglikemijska koma", "E15"),
    E15_0("Nedijabetična hipoglikemijska koma", "E15.0"),
    E16("Drugi poremećaji unutrašnjeg izlučivanja gušterače", "E16"),
    E16_0("Lijekom uzrokovana hipoglikemija bez kome", "E16.0"),
    E16_1("Druga hipoglikemija", "E16.1"),
    E16_2("Hipoglikemija, nespecificirana", "E16.2"),
    E16_3("Povećano izlučivanje glukagona", "E16.3"),
    E16_8("Drugi specificirani poremećaji unutrašnjeg izlučivanja gušterače", "E16.8"),
    E16_9("Poremećaj unutrašnjeg izlučivanja gušterače, nespecificiran", "E16.9"),
    E20("Hipoparatireoidizam", "E20"),
    E20_0("Idiopatski hipoparatireoidizam", "E20.0"),
    E20_1("Pseudohipoparatireoidizam", "E20.1"),
    E20_2("Drugi hipoparatireoidizam", "E20.2"),
    E20_9("Hipoparatireoidizam, nespecificiran", "E20.9"),
    E21("Hiperparatireoidizam i drugi poremećaji paratireoidne žlijezde", "E21"),
    E21_0("Primarni hiperparatireoidizam", "E21.0"),
    E21_1("Sekundarni hiperparatireoidizam, nesvrstan drugamo", "E21.1"),
    E21_2("Drugi hiperparatireoidizam", "E21.2"),
    E21_3("Hiperparatireoidizam, nespecificiran", "E21.3"),
    E21_4("Drugi specificirani poremećaji paratireoidne žlijezde", "E21.4"),
    E21_5("Poremećaj paratireoidne žlijezde, nespecificiran", "E21.5"),
    E22("Hiperfunkcija pituitarne žlijezde", "E22"),
    E22_0("Akromegalija i pituitarni gigantizam", "E22.0"),
    E22_1("Hiperprolaktinemija", "E22.1"),
    E22_2("Sindrom neodgovarajućeg izlučivanja antidiuretskog hormona", "E22.2"),
    E22_8("Ostalo prekomjerno izlučivanje pituitarne žlijezde", "E22.8"),
    E22_9("Hiperfunkcija pituitarne žlijezde, nespecificirana", "E22.9"),
    E23("Hipofunkcija i drugi poremećaji pituitarne žlijezde", "E23"),
    E23_0("Hipopituitarizam", "E23.0"),
    E23_1("Lijekom uzrokovan hipopituitarizam", "E23.1"),
    E23_2("Dijabetes insipidus", "E23.2"),
    E23_3("Hipotalamična disfunkcija, nesvrstana drugamo", "E23.3"),
    E23_6("Drugi poremećaji pituitarne žlijezde", "E23.6"),
    E23_7("Poremećaj pituitarne žlijezde, nespecificiran", "E23.7"),
    E24("Cushingov sindrom", "E24"),
    E24_0("Cushingova bolest ovisna o pituitarnoj žlijezdi", "E24.0"),
    E24_1("Nelsonov sindrom", "E24.1"),
    E24_2("Lijekom uzrokovani Cushingov sindrom", "E24.2"),
    E24_3("Ektopični ACTH sindrom", "E24.3"),
    E24_4("Pseudo-Cushingov sindrom uvjetovan alkoholom", "E24.4"),
    E24_8("Drugi Cushingov sindrom", "E24.8"),
    E24_9("Cushingov sindrom, nespecificiran", "E24.9"),
    E25("Adrenogenitalni poremećaji", "E25"),
    E25_0("Prirođeni adrenogenitalni poremećaji udruženi s manjkom enzima", "E25.0"),
    E25_8("Drugi adrenogenitalni poremećaji", "E25.8"),
    E25_9("Adrenogenitalni poremećaj, nespecificiran", "E25.9"),
    E26("Hiperaldosteronizam", "E26"),
    E26_0("Primarni hiperaldosteronizam", "E26.0"),
    E26_1("Sekundarni hiperaldosteronizam", "E26.1"),
    E26_8("Drugi hiperaldosteronizam", "E26.8"),
    E26_9("Hiperaldosteronizam, nespecificiran", "E26.9"),
    E27("Ostali poremećaji nadbubrežne žlijezde", "E27"),
    E27_0("Ostala prekomjerna adrenokortikalna aktivnost", "E27.0"),
    E27_1("Primarna adrenokortikalna insuficijencija", "E27.1"),
    E27_2("Addisonova kriza", "E27.2"),
    E27_3("Lijekom uzrokovana adrenokortikalna insuficijencija", "E27.3"),
    E27_4("Druga i nespecificirana adrenokortikalna insuficijencija", "E27.4"),
    E27_5("Adrenomedularna hiperfunkcija", "E27.5"),
    E27_8("Drugi specificirani poremećaji nadbubrežne žlijezde", "E27.8"),
    E27_9("Poremećaj nadbubrežne žlijezde, nespecificiran", "E27.9"),
    E28("Poremećaj funkcije jajnika", "E28"),
    E28_0("Suvišak estrogena", "E28.0"),
    E28_1("Suvišak androgena", "E28.1"),
    E28_2("Sindrom policističnog jajnika", "E28.2"),
    E28_3("Primarna disfunkcija jajnika", "E28.3"),
    E28_8("Ostali poremećaji jajnika", "E28.8"),
    E28_9("Disfunkcija jajnika, nespecificirana", "E28.9"),
    E29("Testikularna disfunkcija", "E29"),
    E29_0("Testikularna hiperfunkcija", "E29.0"),
    E29_1("Testikularna hipofunkcija", "E29.1"),
    E29_8("Ostali testikularni poremećaji", "E29.8"),
    E29_9("Testikularna disfunkcija, nespecificirana", "E29.9"),
    E30("Poremaćaji puberteta, nesvrstani drugamo", "E30"),
    E30_0("Zakašnjeli pubertet", "E30.0"),
    E30_1("Prijevremeni pubertet", "E30.1"),
    E30_8("Ostali poremećaji puberteta", "E30.8"),
    E30_9("Poremećaj puberteta, nespecificiran", "E30.9"),
    E31("Poliglandularna disfunkcija", "E31"),
    E31_0("Autoimuna poliglandularna disfunkcija", "E31.0"),
    E31_1("Poliglandularna hiperfunkcija", "E31.1"),
    E31_8("Druga poliglandularna disfunkcija", "E31.8"),
    E31_9("Poliglandularna disfunkcija, nespecificirana", "E31.9"),
    E32("Bolesti timusa", "E32"),
    E32_0("Trajna hiperplazija timusa", "E32.0"),
    E32_1("Apsces timusa", "E32.1"),
    E32_8("Ostale bolesti timusa", "E32.8"),
    E32_9("Bolest timusa, nespecificirana", "E32.9"),
    E34("Ostali endokrini poremećaji", "E34"),
    E34_0("Karcinoidni sindrom", "E34.0"),
    E34_1("Ostala prekomjerna izlučivanja intestinalnih hormona", "E34.1"),
    E34_2("Ektopično izlučivanje hormona, nesvrstano drugamo", "E34.2"),
    E34_3("Zaostalost u rastu, nesvrstana drugamo", "E34.3"),
    E34_4("Konstitucionalno visoki rast", "E34.4"),
    E34_5("Sindrom androgene rezistencije", "E34.5"),
    E34_8("Ostali specificirani endokrini poremećaji", "E34.8"),
    E34_9("Endokrini poremećaj, nespecificiran", "E34.9"),
    E35("Poremećaji endokrinih žlijezda u bolestima svrstanim drugamo", "E35"),
    E35_0("Poremećaji štitnjače u bolestima svrstanim drugamo", "E35.0"),
    E35_1("Poremećaji nadbubrežnih žlijezda u bolestima svrstanim drugamo", "E35.1"),
    E35_8("Poremećaji drugih endokrinih žlijezda u bolestima svrstanim drugamo", "E35.8"),
    E40("Kvašiorkor", "E40"),
    E40_0("Kvašiorkor", "E40.0"),
    E41("Marazam zbog deficitarne prehrane", "E41"),
    E41_0("Marazam zbog deficitarne prehrane", "E41.0"),
    E42("Marazmični kvašiorkor", "E42"),
    E42_0("Marazmični kvašiorkor", "E42.0"),
    E43("Nespecificirana teška proteinsko-energetska pothranjenost", "E43"),
    E43_0("Nespecificirana teška proteinsko-energetska pothranjenost", "E43.0"),
    E44("Proteinsko-energetska pothranjenost umjerenog i blagog stupnja", "E44"),
    E44_0("Umjerena proteinsko-energetska pothranjenost", "E44.0"),
    E44_1("Blaga proteinsko-energetska pothranjenost", "E44.1"),
    E45("Zaostajanje u razvoju zbog proteinsko-energetske pothranjenosti", "E45"),
    E45_0("Zaostajanje u razvoju zbog proteinsko-energetske pothranjenosti", "E45.0"),
    E46("Nespecificirana proteinsko-energetska pothranjenost", "E46"),
    E46_0("Nespecificirana proteinsko-energetska pothranjenost", "E46.0"),
    E50("Manjak vitamina A", "E50"),
    E50_0("Manjak vitamina A sa kserozom spojnica", "E50.0"),
    E50_1("Manjak vitamina A s Bitotovim pjegama i kserozom spojnica", "E50.1"),
    E50_2("Manjak vitamina A sa kserozom rožnice", "E50.2"),
    E50_3("Manjak vitamina A s ulceracijom rožnice i kserozom", "E50.3"),
    E50_4("Manjak vitamina A s keratomalacijom", "E50.4"),
    E50_5("Manjak vitamina A s noćnom sljepoćom", "E50.5"),
    E50_6("Manjak vitamina A sa kseroftalmičkim ožiljcima rožnice", "E50.6"),
    E50_7("Ostale očne manifestacije zbog manjka vitamina A", "E50.7"),
    E50_8("Ostale manifestacije zbog manjka vitamina A", "E50.8"),
    E50_9("Manjak vitamina A, nespecificiran", "E50.9"),
    E51("Manjak tiamina", "E51"),
    E51_1("Beriberi", "E51.1"),
    E51_2("Wernickeova encefalopatija", "E51.2"),
    E51_8("Ostale manifestacije manjka tiamina", "E51.8"),
    E51_9("Manjak tiamina, nespecificiran", "E51.9"),
    E52("Manjak niacina (pelagra)", "E52"),
    E52_0("Manjak niacina (pelagra)", "E52.0"),
    E53("Manjak ostalih vitamina B skupine", "E53"),
    E53_0("Manjak riboflavina", "E53.0"),
    E53_1("Manjak piridoksina", "E53.1"),
    E53_8("Manjak ostalih specificiranih vitamina skupine B", "E53.8"),
    E53_9("Manjak vitamina B, nespecificiran", "E53.9"),
    E54("Manjak askorbinske kiseline", "E54"),
    E54_0("Manjak askorbinske kiseline", "E54.0"),
    E55("Manjak vitamina D", "E55"),
    E55_0("Rahitis, aktivni", "E55.0"),
    E55_9("Manjak vitamina D, nespecificiran", "E55.9"),
    E56("Ostali nedostaci vitamina", "E56"),
    E56_0("Manjak vitamina E", "E56.0"),
    E56_1("Manjak vitamina K", "E56.1"),
    E56_8("Manjak ostalih vitamina", "E56.8"),
    E56_9("Manjak vitamina, nespecificiran", "E56.9"),
    E58("Manjak kalcija u prehrani", "E58"),
    E58_0("Manjak kalcija u prehrani", "E58.0"),
    E59("Manjak selenija u prehrani", "E59"),
    E59_0("Manjak selenija u prehrani", "E59.0"),
    E60("Manjak cinka u prehrani", "E60"),
    E60_0("Manjak cinka u prehrani", "E60.0"),
    E61("Manjak ostalih prehrambenih tvari", "E61"),
    E61_0("Manjak bakra", "E61.0"),
    E61_1("Manjak željeza", "E61.1"),
    E61_2("Manjak magnezija", "E61.2"),
    E61_3("Manjak mangana", "E61.3"),
    E61_4("Manjak kroma", "E61.4"),
    E61_5("Manjak molibdena", "E61.5"),
    E61_6("Manjak vanadija", "E61.6"),
    E61_7("Manjak više prehrambenih tvari", "E61.7"),
    E61_8("Manjak ostalih specificiranih prehrambenih tvari", "E61.8"),
    E61_9("Manjak prehrambene tvari, nespecificiran", "E61.9"),
    E63("Ostali prehrambeni nedostaci", "E63"),
    E63_0("Manjak esencijalnih masnih kiselina (EMK)", "E63.0"),
    E63_1("Neravnoteža sastojaka unesene hrane", "E63.1"),
    E63_8("Ostali specificirani prehrambeni deficiti", "E63.8"),
    E63_9("Prehrambeni nedostatak, nespecificiran", "E63.9"),
    E64("Posljedice pothranjenosti i ostalih prehrambenih nedostataka", "E64"),
    E64_0("Posljedice proteinsko energijske pothranjenosti", "E64.0"),
    E64_1("Posljedice manjka vitamina A", "E64.1"),
    E64_2("Posljedice manjka vitamina C", "E64.2"),
    E64_3("Posljedice rahitisa", "E64.3"),
    E64_8("Posljedice ostalih prehrambenih deficita", "E64.8"),
    E64_9("Posljedice nespecificiranih prehrambenih deficita", "E64.9"),
    E65("Lokalizirana pretilost", "E65"),
    E65_0("Lokalizirana pretilost", "E65.0"),
    E66("Pretilost", "E66"),
    E66_0("Pretilost zbog prekomjernog unosa energije", "E66.0"),
    E66_1("Lijekom uzrokovana pretilost", "E66.1"),
    E66_2("Krajnja (ekstremna) pretilost s alveolarnom hipoventilacijom", "E66.2"),
    E66_8("Druga pretilost", "E66.8"),
    E66_9("Pretilost, nespecificirana", "E66.9"),
    E67("Druga hiperalimentacija", "E67"),
    E67_0("Hipervitaminoza A", "E67.0"),
    E67_1("Hiperkarotinemija", "E67.1"),
    E67_2("Megavitamin-B6 sindrom", "E67.2"),
    E67_3("Hipervitaminoza D", "E67.3"),
    E67_8("Ostala specificirana hiperalimentacija", "E67.8"),
    E68("Posljedice hiperalimentacije", "E68"),
    E68_0("Posljedice hiperalimentacije", "E68.0"),
    E70("Poremećaji metabolizma aromatskih aminokiselina", "E70"),
    E70_0("Klasična fenilketonurija", "E70.0"),
    E70_1("Ostale hiperfenilalaninemije", "E70.1"),
    E70_2("Poremećaji metabolizma tirozina", "E70.2"),
    E70_3("Albinizam", "E70.3"),
    E70_8("Ostali poremećaji metabolizma aromatskih aminokiselina", "E70.8"),
    E70_9("Poremećaj metabolizma aromatskih aminokiselina,nespecificiran", "E70.9"),
    E71("Poremećaji metabolizma lančano vezanih aminokiselina i metabolizma masnih kiselina", "E71"),
    E71_0("Bolest s mokraćom poput javorova sirupa", "E71.0"),
    E71_1("Ostali poremećaji metabolizma lančano vezanih aminokiselina", "E71.1"),
    E71_2("Poremećaj metabolizma lančano vezanih aminokiselina, nespecificiran", "E71.2"),
    E71_3("Poremećaji metabolizma masnih kiselina", "E71.3"),
    E72("Ostali poremećaji metabolizma aminokiselina", "E72"),
    E72_0("Poremećaji prijenosa aminokiselina", "E72.0"),
    E72_1("Poremećaji metabolizma aminokiselina koje sadrže sumpor", "E72.1"),
    E72_2("Poremećaji metabolizma ciklusa ureje", "E72.2"),
    E72_3("Poremećaji metabolizma lizina i hidroksilizina", "E72.3"),
    E72_4("Poremećaji metabolizma ornitina", "E72.4"),
    E72_5("Poremećaji metabolizma glicina", "E72.5"),
    E72_8("Ostali specificirani poremećaji metabolizma aminokiselina", "E72.8"),
    E72_9("Poremećaj metabolizma aminokiselina, nespecificiran", "E72.9"),
    E73("Intolerancija laktoze", "E73"),
    E73_0("Prirođeni manjak laktaze", "E73.0"),
    E73_1("Sekundarni manjak laktaze", "E73.1"),
    E73_8("Druga intolerancija laktoze", "E73.8"),
    E73_9("Intolerancija laktoze, nespecificirana", "E73.9"),
    E74("Drugi poremećaji metabolizma ugljikohidrata", "E74"),
    E74_0("Bolest nagomilavanja glikogena", "E74.0"),
    E74_1("Poremećaji metabolizma fruktoze", "E74.1"),
    E74_2("Poremećaji metabolizma galaktoze", "E74.2"),
    E74_3("Ostali poremećaji crijevne apsorpcije ugljikohidrata", "E74.3"),
    E74_4("Poremećaji metabolizma piruvata i glukoneogeneze", "E74.4"),
    E74_8("Drugi specificirani poremećaji metabolizma ugljikohidrata", "E74.8"),
    E74_9("Poremećaj metabolizma ugljikohidrata, nespecificiran", "E74.9"),
    E75("Poremećaji metabolizma sfingolipida i ostali poremećaji nakupljanja lipida", "E75"),
    E75_0("GM2 gangliozidoza", "E75.0"),
    E75_1("Ostale gangliozidoze", "E75.1"),
    E75_2("Ostale sfingolipidoze", "E75.2"),
    E75_3("Sfingolipidoza, nespecificirana", "E75.3"),
    E75_4("Neuronalna ceroidna lipofuscinoza", "E75.4"),
    E75_5("Ostali poremećaji pohranjivanja lipida", "E75.5"),
    E75_6("Poremećaj pohranjivanja lipida, nespecificiran", "E75.6"),
    E76("Poremećaji metabolizma glikozaminoglikana", "E76"),
    E76_0("Mukopolisaharidoza, tip I", "E76.0"),
    E76_1("Mukopolisaharidoza, tip II", "E76.1"),
    E76_2("Ostale mukopolisaharidoze", "E76.2"),
    E76_3("Mukopolisaharidoza, nespecificirana", "E76.3"),
    E76_8("Ostali poremećaji metabolizma glukozaminoglikana", "E76.8"),
    E76_9("Poremećaj metabolizma glukozaminoglikana, nespecificiran", "E76.9"),
    E77("Poremećji metabolizma glikoproteina", "E77"),
    E77_0("Defekti u posttranslacijskoj modifikaciji lizosomskih enzima", "E77.0"),
    E77_1("Defekti u razgradnji glikoproteina", "E77.1"),
    E77_8("Ostali poremećaji metabolizma glikoproteina", "E77.8"),
    E77_9("Poremećaj metabolizma glikoproteina, nespecificiran", "E77.9"),
    E78("Poremećaji metabolizma lipoproteina i ostale lipidemije", "E78"),
    E78_0("Hiperkolesterolemija", "E78.0"),
    E78_1("Hipergliceridemija", "E78.1"),
    E78_2("Mješovita hiperlipidemija", "E78.2"),
    E78_3("Hiperhilomikronemija", "E78.3"),
    E78_4("Druga hiperlipidemija", "E78.4"),
    E78_5("Hiperlipidemija, nespecificirana", "E78.5"),
    E78_6("Manjak lipoproteina", "E78.6"),
    E78_8("Ostali poremećaji metabolizma lipoproteina", "E78.8"),
    E78_9("Poremećaj metabolizma lipoproteina, nespecificiran", "E78.9"),
    E79("Poremećaji metabolizma purina i pirimidina", "E79"),
    E79_0("Hiperuricemija bez znakova upalnog artritisa i stvaranja tofa", "E79.0"),
    E79_1("Lesch-Nyhanov sindrom", "E79.1"),
    E79_8("Ostali poremećaji metabolizma purina i pirimidina", "E79.8"),
    E79_9("Poremećaj metabolizma purina i pirimidina, nespecificiran", "E79.9"),
    E80("Poremećaj eritropoezna porfirija", "E80"),
    E80_1("Porphyria cutenea tarda", "E80.1"),
    E80_2("Druga porfirija", "E80.2"),
    E80_3("Defekti katalaze i peroksidaze", "E80.3"),
    E80_4("Gilbertov sindrom", "E80.4"),
    E80_5("Crigler-Najjarov sindrom", "E80.5"),
    E80_6("Ostali poremećaji metabolizma bilirubina", "E80.6"),
    E80_7("Poremećaj metabolizma bilirubina, nespecificiran", "E80.7"),
    E83("Poremećaji metabolizma minerala", "E83"),
    E83_0("Poremećaji metabolizma bakra", "E83.0"),
    E83_1("Poremećaji metabolizma željeza", "E83.1"),
    E83_2("Poremećaji metabolizma cinka", "E83.2"),
    E83_3("Poremećaji metabolizma fosfora", "E83.3"),
    E83_4("Poremećaji metabolizma magnezija", "E83.4"),
    E83_5("Poremećaji metabolizma kalcija", "E83.5"),
    E83_8("Ostali poremećaji metabolizma minerala", "E83.8"),
    E83_9("Poremećaj metabolizma minerala, nespecificiran", "E83.9"),
    E84("Cistična fibroza", "E84"),
    E84_0("Cistična fibroza s plućnim manifestacijama", "E84.0"),
    E84_1("Cistična fibroza s crijevnim manifestacijama", "E84.1"),
    E84_8("Cistična fibroza s ostalim manifestacijama", "E84.8"),
    E84_9("Cistična fibroza, nespecificirana", "E84.9"),
    E85("Amiloidoza", "E85"),
    E85_0("Neneuropatska heredofamilijarna amiloidoza", "E85.0"),
    E85_1("Neuropatska heredofamilijarna amiloidoza", "E85.1"),
    E85_2("Heredofamilijarna amiloidoza, nespecificirana", "E85.2"),
    E85_3("Sekundarna sistemna amiloidoza", "E85.3"),
    E85_4("Izolirana amiloidoza ograničena na organe", "E85.4"),
    E85_8("Druga amiloidoza", "E85.8"),
    E85_9("Amiloidoza, nespecificirana", "E85.9"),
    E86("Smanjenje volumena tekućina", "E86"),
    E86_0("Smanjenje volumena tekućina", "E86.0"),
    E87("Ostali poremećaji tekućine, elektrolita i acidobazne ravnoteže", "E87"),
    E87_0("Hiperosmolalnost i hipernatremija", "E87.0"),
    E87_1("Hipoosmolalnost i hiponatremija", "E87.1"),
    E87_2("Acidoza", "E87.2"),
    E87_3("Alkaloza", "E87.3"),
    E87_4("Mješoviti poremećaj acidobazne ravnoteže", "E87.4"),
    E87_5("Hiperkalemija", "E87.5"),
    E87_6("Hipokalemija", "E87.6"),
    E87_7("Preopterećenost tekućinom", "E87.7"),
    E87_8("Ostali poremećaji elektrolita i ravnoteže tekućine, nesvrstani drugamo", "E87.8"),
    E88("Ostali metabolični poremećaji", "E88"),
    E88_0("Poremećaji metabolizma plazmaproteina, nesvrstani drugamo", "E88.0"),
    E88_1("Lipodistrofija, nesvrstana drugamo", "E88.1"),
    E88_2("Lipomatoza, nesvrstana drugamo", "E88.2"),
    E88_8("Ostali specificirani metabolični poremećaji", "E88.8"),
    E88_9("Metabolični poremećaj, nespecificiran", "E88.9"),
    E89("Endokrini i metabolični poremećaji nakon medicinskog postupka, nesvrstani drugamo", "E89"),
    E89_0("Hipotireoza nakon medicinskog postupka", "E89.0"),
    E89_1("Hipoinzulinemija nakon medicinskog postupka", "E89.1"),
    E89_2("Hipoparatireoidizam nakon medicinskog postupka", "E89.2"),
    E89_3("Hipopituitarizam nakon medicinskog postupka", "E89.3"),
    E89_4("Oštećenje funkcije jajnika nakon medicinskog postupka", "E89.4"),
    E89_5("Testikularna hipofunkcija nakon medicinskog postupka", "E89.5"),
    E89_6("Adrenokortikalna (medularna) hipofunkcija nakon medicinskog postupka", "E89.6"),
    E89_8("Ostali endokrini i metabolični poremećaji nakon medicinskog postupka", "E89.8"),
    E89_9("Endokrini i metabolični poremećaj nakon medicinskog postupka, nespecificiran", "E89.9"),
    E90("Prehrambeni i metabolični poremećaji u bolestima svrstanim drugamo", "E90"),
    E90_0("Prehrambeni i metabolični poremećaji u bolestima svrstanim drugamo", "E90.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesE(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
