package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesA {
    A00("Kolera", "A00"),
    A00_0("Kolera koju uzrokuje Vibrio cholerae, biovar cholerae, klasična kolera", "A00.0"),
    A00_1("Kolera koju uzrokuje Vibrio cholerae 01, biovar El Tor, El Tor kolera", "A00.1"),
    A00_9("Kolera, nespecificirana", "A00.9"),
    A01("Trbušni tifus i paratifus", "A01"),
    A01_0("Trbušni tifus, Uzročnik Salmonella typhi", "A01.0"),
    A01_1("Paratifus Aw", "A01.1"),
    A01_2("Paratifus B", "A01.2"),
    A01_3("Paratifus C", "A01.3"),
    A01_4("Paratifus, nespecificiran, Uzročnik Salmonella paratyphi BPO", "A01.4"),
    A02("Ostale infekcije uzrokovane salmonelama", "A02"),
    A02_0("Entritis uzrokovan salmonelom, salmoneloza", "A02.0"),
    A02_1("Sepsa uzrokovana salmonelom", "A02.1"),
    A02_2("Lokalizirane infekcije salmonelama", "A02.2"),
    A02_8("Ostale specificirane infekcije salmonelama", "A02.8"),
    A02_9("Infekcije salmonelama, nespecificirane", "A02.9"),
    A03("Šigeloze", "A03"),
    A03_0("Šigeloza koju uzrokuje Shigella dysenteriae, Šigeloza grupe A (Shiga-Kruse disenterija)", "A03.0"),
    A03_1("Šigeloza koju uzrokuje Shigella flexneri, Šigeloza grupe B", "A03.1"),
    A03_2("Šigeloza koju uzrokuje Shigella boydii, Šigeloza grupe C", "A03.2"),
    A03_3("Šigeloza koju uzrokuje Shigella sonnei, Šigeloza grupe D", "A03.3"),
    A03_8("Ostale šigeloze", "A03.8"),
    A03_9("Šigeloza, nespecificirana, Bacilarna dizenterija BPO", "A03.9"),
    A04("Ostale bakterijske crijevne infekcije", "A04"),
    A04_0("Infekcija enteropatogenom E.coli", "A04.0"),
    A04_1("Infekcija enterotoksičnom E.coli", "A04.1"),
    A04_2("Infekcija enteroinvazivnom E.coli", "A04.2"),
    A04_3("Infekcija enterohemoragijskom E.coli", "A04.3"),
    A04_4("Ostale crijevne infekcije koje uzrokuje Escherichia coli, Enteritis koji uzrokuje E.coli BPO", "A04.4"),
    A04_5("Enteritis koji uzrokuje Campylobacter", "A04.5"),
    A04_6("Enteritis koji uzrokuje Yersinia enterocolitica", "A04.6"),
    A04_7("Enterokolitis koji uzrokuje Clostridium difficile", "A04.7"),
    A04_8("Ostale specificirane crijevne bakterijske infekcije", "A04.8"),
    A04_9("Bakterijske crijevne infekcije, nespecificirane, Bakterijski enteritis BPO", "A04.9"),
    A05("Ostala bakterijska trovanja hranom (alimentarne intoksikacije)", "A05"),
    A05_0("Alimentarna stafilokokna intoksikacija", "A05.0"),
    A05_1("Botulizam", "A05.1"),
    A05_2("Alimentarna intoksikacija koju uzrokuje Clostridium perfringens (Clostridum welchii) Enteritis necroticans Pig-bel", "A05.2"),
    A05_3("Alimentarna intoksikacija uzrokovana mikroorganizmom Vibrio parahaemolyticus", "A05.3"),
    A05_4("Alimentarna intoksikacija uzrokovana mikroorganizmom Bacillus cereus", "A05.4"),
    A05_8("Ostale specificirane bakterijske alimentarne intoksikacije", "A05.8"),
    A05_9("Bakterijska alimentarna intoksikacija, nespecificirana", "A05.9"),
    A06("Amebijaza", "A06"),
    A06_0("Akutna amebna dizenterija, Akutna amebijaza, Crijevna amebijaza BPO", "A06.0"),
    A06_1("Kronična crijevna amebijaza", "A06.1"),
    A06_2("Amebni nedizenterični kolitis", "A06.2"),
    A06_3("Intestinalni amebom, Amebom BPO", "A06.3"),
    A06_4("Amebni apsces jetre, Hepatalna amebijaza", "A06.4"),
    A06_5("Amebni apsces pluća (J99.8*), Amebni apsces pluća (i jetre)", "A06.5"),
    A06_6("Amebni apsces mozga (G07*), Amebni apsces mozga (i jetre) (i pluća)", "A06.6"),
    A06_7("Kožna amebijaza", "A06.7"),
    A06_8("Amebna infekcija drugih lokalizacija, Amebni apendicitis, balanitis (N51.2*)", "A06.8"),
    A06_9("Amebijaza, nespecificirana", "A06.9"),
    A07("Ostale crijevne bolesti uzrokovane protozoima", "A07"),
    A07_0("Balantidijaza, Dizenterija uzrokovana balantidijama", "A07.0"),
    A07_1("Giardijaza (lamblijaza)", "A07.1"),
    A07_2("Izosporijaza, Infekcije koje uzrokuju Isospora belli i Isospora hominis, Crijevna kokcidioidoza, Izosporoza", "A07.2"),
    A07_8("Ostale specificirane crijevne bolesti uzrokovane protozoima, Crijevna trihomonijaza, Sarkocistoza, Sarkosporidijaza", "A07.8"),
    A07_9("Crijevne bolesti uzrokovane protozoima, nespecificirane, Dijareja uzrokovana flagelatima, Protozoarni(a) kolitis, dijareja, dizenterija", "A07.9"),
    A08("Virusne i druge specificirane crijevne infekcije", "A08"),
    A08_0("Enteritis uzrokovan rotavirusima", "A08.0"),
    A08_1("Akutna gastroenteropatija uzrokovana Norwalk agensom, Enteritis uzrokovan sitnim okruglastim virusima", "A08.1"),
    A08_2("Enteritis uzrokovan adenovirusima", "A08.2"),
    A08_3("Ostali virusni enteritisi", "A08.3"),
    A08_4("Virusne crijevne infekcije, nespecificirane, Virusni enteritis BPO, gastroenteritis BPO, gastroenteropatija BPO", "A08.4"),
    A08_5("Ostale specificirane crijevne infekcije", "A08.5"),
    A09("Dijareja i gastroenteritis za koje se pretpostavlja da su infekcioznog podrijetla", "A09"),
    A09_0("Dijareja i gastroenteritis za koje se pretpostavlja da su infekcioznog podrijetla", "A09.0"),
    A15("Tuberkuloza dišnih putova dokazana bakteriološki i histološki", "A15"),
    A15_0("Tuberkuloza pluća, dokazana mikroskopskim pregledom iskašljaja s kulturom ili bez nje", "A15.0"),
    A15_1("Tuberkuloza pluća, dokazana samo kulturom, Stanje šifrirano kao A15.0, dokazano samo kulturom", "A15.1"),
    A15_2("Tuberkuloza pluća, dokazana histološki, Stanje šifrirano kao A15.0, dokazano histološki", "A15.2"),
    A15_3("Tuberkuloza pluća, dokazana nespecificiranim tehnikama, Stanje šifrirano kao A15.0, dokazano ali nespecificirano da li bakteriološki", "A15.3"),
    A15_4("Tuberkuloza intratorakalnih limfnih čvorova, dokazana bakteriološki i histološki, Tuberkuloza limfnih čvorova", "A15.4"),
    A15_5("Tuberkuloza larinksa, traheje i bronha, dokazana", "A15.5"),
    A15_6("Tuberkulozni plueritis, dokazan bakteriološki i histološki", "A15.6"),
    A15_7("Primarna tuberkuloza dišnog sustava, dokazana bakteriološki i histološki", "A15.7"),
    A15_8("Tuberkuloza dišnog sustava ostalih lokalizacija, dokazana bakteriološki i histološki", "A15.8"),
    A15_9("Tuberkuloza dišnih putova pobliže nespecificirana, dokazana bakteriološki i histološki", "A15.9"),
    A16("Tuberkuloza dišnih putova, nedokazana bakteriološki ili histološki", "A16"),
    A16_0("Tuberkuloza pluća, bakteriološki i histološki negativna", "A16.0"),
    A16_1("Tuberkuloza pluća, bakteriološke i histološke pretrage nisu obavljene", "A16.1"),
    A16_2("Tuberkuloza pluća, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.2"),
    A16_3("Tuberkuloza intratorakalnih limfnih čvorova, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.3"),
    A16_4("Tuberkuloza larinksa, traheje i bronha, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.4"),
    A16_5("Tuberkulozni pleuritis, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.5"),
    A16_7("Primarna respiratorna tuberkuloza bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.7"),
    A16_8("Tuberkuloza dišnog sustava ostalih lokalizacija, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.8"),
    A16_9("Nespecificirana tuberkuloza dišnog sustava, bez naznake o bakteriološkoj ili histološkoj potvrdi", "A16.9"),
    A17("Tuberkuloza živčanog sustava", "A17"),
    A17_0("Tuberkulozni meningitis (G01*), Tuberkuloza moždanih ovojnica (cerebralnih) (spinalnih), Tuberkulozni leptomeningitis", "A17.0"),
    A17_1("Meningealni tuberkulom (G07*), Tuberkulom meninga", "A17.1"),
    A17_8("Tuberkuloza ostalih dijelova živčanog sustava", "A17.8"),
    A17_9("Tuberkuloza živčanog sustava, nespecificirana (G99.9*)", "A17.9"),
    A18("Tuberkuloza ostalih organa", "A18"),
    A18_0("Tuberkuloza kostiju i zglobova", "A18.0"),
    A18_1("Tuberkuloza genitourinarnog sustava", "A18.1"),
    A18_2("Tuberkulozna periferna limfadenopatija", "A18.2"),
    A18_3("Tuberkuloza crijeva, potrbušnice i mezenterijalnih žlijezda", "A18.3"),
    A18_4("Tuberkuloza kože i potkožnog tkiva", "A18.4"),
    A18_5("Tuberkuloza oka", "A18.5"),
    A18_6("Tuberkuloza uha", "A18.6"),
    A18_7("Tuberkuloza nadbubrežne žlijezde (E35.1*), Addisonova bolest, tuberkulozna", "A18.7"),
    A18_8("Tuberkuloza drugih specificiranih organa", "A18.8"),
    A19("Milijarna tuberkuloza", "A19"),
    A19_0("Akutna milijarna tuberkuloza jedne određene lokalizacije", "A19.0"),
    A19_1("Akutna milijarna tuberkuloza više lokalizacija", "A19.1"),
    A19_2("Akutna milijarna tuberkuloza, nespecificirana", "A19.2"),
    A19_8("Ostala milijarna tuberkuloza", "A19.8"),
    A19_9("Milijarna tuberkuloza, nespecificirana", "A19.9"),
    A20("Kuga", "A20"),
    A20_0("Bubonska kuga", "A20.0"),
    A20_1("Celulokutana kuga", "A20.1"),
    A20_2("Plućna kuga", "A20.2"),
    A20_3("Meningitis (kužni)", "A20.3"),
    A20_7("Septična kuga", "A20.7"),
    A20_8("Ostali oblici kuge, abortivna kuga, asimptomatska kuga, Pestis minor", "A20.8"),
    A20_9("Kuga, nespecificirana", "A20.9"),
    A21("Tularemija", "A21"),
    A21_0("Ulceroglandularna tularemija", "A21.0"),
    A21_1("Okuloglandularna tularemija", "A21.1"),
    A21_2("Plućna tularemija", "A21.2"),
    A21_3("Gastrointestinalna tularemija", "A21.3"),
    A21_7("Generalizirana tularemija", "A21.7"),
    A21_8("Ostali oblici tularemije", "A21.8"),
    A21_9("Tularemija, nespecificirana", "A21.9"),
    A22("Antraks (crni prišt)", "A22"),
    A22_0("Kožni antraks, Maligni(a) karbunkul, pustula", "A22.0"),
    A22_1("Plućni antraks", "A22.1"),
    A22_2("Gastrointestinalni antraks", "A22.2"),
    A22_7("Antraksna sepsa", "A22.7"),
    A22_8("Ostali oblici antraksa", "A22.8"),
    A22_9("Antraks, nespecificiran", "A22.9"),
    A23("Bruceloza", "A23"),
    A23_0("Bruceloza koju uzrokuje Brucella melitensis", "A23.0"),
    A23_1("Bruceloza koju uzrokuje Brucella abortus", "A23.1"),
    A23_2("Bruceloza koju uzrokuje Brucella suis", "A23.2"),
    A23_3("Bruceloza koju uzrokuje Brucella canis", "A23.3"),
    A23_8("Ostale bruceloze", "A23.8"),
    A23_9("Bruceloza, nespecificirana", "A23.9"),
    A24("Sakagija i melioidoza", "A24"),
    A24_0("Sakagija", "A24.0"),
    A24_1("Akutna i fulminantna melioidoza", "A24.1"),
    A24_2("Subakutna i kronična melioidoza", "A24.2"),
    A24_3("Ostale melioidoze", "A24.3"),
    A24_4("Melioidoza, nespecificirana", "A24.4"),
    A25("Rat-bite fever (groznica štakorskog ugriza)", "A25"),
    A25_0("Spiriloza", "A25.0"),
    A25_1("Streptobaciloza", "A25.1"),
    A25_9("Rat-bite fever (groznica štakorskog ugriza), nespecificirana", "A25.9"),
    A26("Erizipeloid", "A26"),
    A26_0("Erythema migrans", "A26.0"),
    A26_7("Sepsa koju uzrokuje Erysipelotrix rhusiopathiae", "A26.7"),
    A26_8("Ostali oblici erizipeloida", "A26.8"),
    A26_9("Erizipeloid, nespecificiran", "A26."),
    A27("Leptospiroza", "A27"),
    A27_0("Ikterohemoragična leptospiroza", "A27.0"),
    A27_8("Ostali oblici leptospiroza", "A27.8"),
    A27_9("Leptospiroza, nespecificirana", "A27.9"),
    A28("Ostale zoonoze uzrokovane bakterijama, nesvrstane drugamo", "A28"),
    A28_0("Pasteureloza", "A28.0"),
    A28_1("Cat-scratch disease (bolest mačjeg ogreba)", "A28.1"),
    A28_2("Ekstraintestinalna jersinioza", "A28.2"),
    A28_8("Ostale specificirane bakterijske zoonoze, nesvrstane drugamo", "A28.8"),
    A28_9("Bakterijske zoonoze, nespecificirane", "A28.9"),
    A30_0("Nedeterminirana lepra", "A30.0"),
    A30_1("Tuberkuloidna lepra", "A30.1"),
    A30_2("Granična tuberkuloidna lepra", "A30.2"),
    A30_3("Granična lepra", "A30.3"),
    A30_4("Granična lepromatozna lepra", "A30.4"),
    A30_5("Lepromatozna lepra", "A30.5"),
    A30_8("Ostali oblici lepre", "A30.8"),
    A30_9("Lepra, nespecificirana", "A30.9"),
    A31("Infekcije uzrokovane drugim mikobakterijama", "A31"),
    A31_0("Plućna infekcija mikobakterijama", "A31.0"),
    A31_1("Kožne infekcije mikobakterijama", "A31.1"),
    A31_8("Ostale infekcije mikobakterijama", "A31.8"),
    A31_9("Mikobakterijska infekcija, nespecificirana", "A31.9"),
    A32("Listerioza", "A32"),
    A32_0("Kožna listerioza", "A32.0"),
    A32_1("Listerijski meningitis i meningoencefalitis", "A32.1"),
    A32_7("Listerijska sepsa", "A32.7"),
    A32_8("Ostali oblici listerioze", "A32.8"),
    A32_9("Listerioza, nespecificirana", "A32.9"),
    A33("Tetanus neonatorum (novorođenački tetanus)", "A33"),
    A33_0("Tetanus neonatorum (novoro|enački tetanus)", "A33.0"),
    A34("Opstetrični tetanus (porodnički tetanus)", "A34"),
    A34_0("Opstetrični tetanus (porodnički tetanus)", "A34.0"),
    A35("Ostali tetanus", "A35"),
    A35_0("Ostali tetanus", "A35.0"),
    A36("Difterija", "A36"),
    A36_0("Difterija farinksa (ždrijela)", "A36.0"),
    A36_1("Nazofaringealna difterija", "A36.1"),
    A36_2("Difterija larinksa (grkljana)", "A36.2"),
    A36_3("Kožna difterija", "A36.3"),
    A36_8("Ostali oblici difterije", "A36.8"),
    A36_9("Difterija, nespecificirana", "A36.9"),
    A37("Hripavac (pertussis)", "A37"),
    A37_0("Hripavac koji uzrokuje Bordetella pertussis", "A37.0"),
    A37_1("Hripavac koji uzrokuje Bordetella parapertussis", "A37.1"),
    A37_8("Hripavac uzrokovan drugim vrstama bordetela", "A37.8"),
    A37_9("Hripavac, nespecificiran", "A37.9"),
    A38("Šarlah (scarlatina)", "A38"),
    A38_0("Šarlah (scarlatina)", "A38.0"),
    A39("Meningokokna infekcija", "A39"),
    A39_0("Meningokokni meningitis (G01*)", "A39.0"),
    A39_1("Waterhouse-Friderichsenov sindrom (E35.1*)", "A39.1"),
    A39_2("Akutna meningokokcemija", "A39.2"),
    A39_3("Kronična meningokokcemija", "A39.3"),
    A39_4("Meningokokcemija, nespecifična meningokokna bakterijemija BPO", "A39.4"),
    A39_5("Meningokokna srčana bolest", "A39.5"),
    A39_8("Ostale meningokokne infekcije", "A39.8"),
    A39_9("Meningokokna infekcija, nespecificirana", "A39.9"),
    A40("Streptokokna sepsa", "A40"),
    A40_0("Sepsa uzrokovana streptokokima grupe A", "A40.0"),
    A40_1("Sepsa uzrokovana streptokokima grupe B", "A40.1"),
    A40_2("Sepsa uzrokovana streptokokima grupe D", "A40.2"),
    A40_3("Sepsa koju uzrokuje Streptococcus pneumoniae", "A40.3"),
    A40_8("Ostale streptokokne sepse", "A40.8"),
    A40_9("Streptokokna sepsa, nespecificirana", "A40.9"),
    A41("Ostale sepse", "A41"),
    A41_0("Sepsa koju uzrokuje Staphylococcus aureus", "A41.0"),
    A41_1("Sepsa uzrokovana drugim specificiranim stafilokokima", "A41.1"),
    A41_2("Sepsa uzrokovana nespecificiranim stafilokokom", "A41.2"),
    A41_3("Sepsa koju uzrokuje Haemophilus influenzae", "A41.3"),
    A41_4("Sepsa uzrokovana anaerobima", "A41.4"),
    A41_5("Sepsa uzrokovana ostalim Gram-negativnim organizmima", "A41.5"),
    A41_8("Ostale specificirane sepse", "A41.8"),
    A41_9("Sepsa, nespecificirana", "A41.9"),
    A42("Aktinomikoza", "A42"),
    A42_0("Plućna aktinomikoza", "A42.0"),
    A42_1("Abdominalna aktinomikoza", "A42.1"),
    A42_2("Cervikofacijalna aktinomikoza", "A42.2"),
    A42_7("Aktinomikotična sepsa", "A42.7"),
    A42_8("Ostali oblici aktinomikoze", "A42.8"),
    A42_9("Aktinomikoza, nespecificirana", "A42.9"),
    A43("Nokardioza", "A43"),
    A43_0("Plućna nokardioza", "A43.0"),
    A43_1("Kožna nokardioza", "A43.1"),
    A43_8("Ostali oblici nokardioze", "A43.8"),
    A43_9("Nokardioza, nespecificirana", "A43.9"),
    A44("Bartoneloza", "A44"),
    A44_0("Sistemska bartoneloza", "A44.0"),
    A44_1("Kutana i mukokutana bartoneloza", "A44.1"),
    A44_8("Ostali oblici bartoneloze", "A44.8"),
    A44_9("Bartoneloza, nespecificirana", "A44.9"),
    A46("Erizipel", "A46"),
    A46_0("Erizipel", "A46.0"),
    A48("Ostale bolesti uzrokovane bakterijama, nesvrstane drugamo", "A48"),
    A48_0("Plinska gangrena", "A48.0"),
    A48_1("Legionarska bolest", "A48.1"),
    A48_2("Izvanplućni oblik legionarske bolesti (Pontiack groznica)", "A48.2"),
    A48_3("Toksični šok-sindrom", "A48.3"),
    A48_4("Brazilska purpurna groznica", "A48.4"),
    A48_8("Ostale specificirane bakterijske bolesti", "A48.8"),
    A49("Bakterijske infekcije nespecificiranog mjesta", "A49"),
    A49_0("Stafilokokna infekcija, nespecificirana", "A49.0"),
    A49_1("Streptokokna infekcija, nespecificirana", "A49.1"),
    A49_2("Infekcija koju uzrokuje Haemophilus influenzae, nespecificirana", "A49.2"),
    A49_3("Infekcija mikoplazmom, nespecificirana", "A49.3"),
    A49_8("Ostale bakterijske infekcije nespecificiranog mjesta", "A49.8"),
    A49_9("Bakterijska infekcija, nespecificirana", "A49.9"),
    A50("Prirođeni sifilis", "A50"),
    A50_0("Rani prirođeni sifilis, simptomatski", "A50.0"),
    A50_1("Rani prirođeni sifilis, latentni", "A50.1"),
    A50_2("Rani prirođeni sifilis, nespecificiran", "A50.2"),
    A50_3("Kasna prirođena sifilitična okulopatija", "A50.3"),
    A50_4("Kasni prirođeni neurosifilis (juvenilni neurosifilis)", "A50.4"),
    A50_5("Drugi kasni prirođeni sifilis, simptomatski", "A50.5"),
    A50_6("Kasni prirođeni sifilis, latentni", "A50.6"),
    A50_7("Kasni prirođeni sifilis, nespecificiran", "A50.7"),
    A50_9("Prirođeni sifilis, nespecificiran", "A50.9"),
    A51("Rani sifilis", "A51"),
    A51_0("Primarni genitalni sifilis", "A51.0"),
    A51_1("Primarni analni sifilis", "A51.1"),
    A51_2("Primarni sifilis druge lokalizacije", "A51.2"),
    A51_3("Sekundarni sifilis kože i sluznica", "A51.3"),
    A51_4("Ostali sekundarni sifilis", "A51.4"),
    A51_5("Rani sifilis, latentni", "A51.5"),
    A51_9("Rani sifilis, nespecificiran", "A51.9"),
    A52("Kasni sifilis", "A52"),
    A52_0("Kardiovaskularni sifilis", "A52.0"),
    A52_1("Simptomatski neurosifilis", "A52.1"),
    A52_2("Asimptomatski neurosifilis", "A52.2"),
    A52_3("Neurosifilis, nespecificiran", "A52.3"),
    A52_7("Ostali simptomatski kasni sifilis", "A52.7"),
    A52_8("Kasni sifilis, latentni", "A52.8"),
    A52_9("Kasni sifilis, nespecificiran", "A52.9"),
    A53("Ostali i nespecificirani sifilis", "A53"),
    A53_0("Latentni sifilis, nespecificiran kao rani ili kasni", "A53.0"),
    A53_9("Sifilis, nespecificiran", "A53.9"),
    A54("Gonokokna infekcija", "A54"),
    A54_0("Gonokokna infekcija donjeg dijela genitourinarnog sustava, bez apscesa periuretralnih i akcesornih žlijezda", "A54.0"),
    A54_1("Gonokokna infekcija donjeg dijela genitourinarnog sustava s popratnim periuretralnim apscesom i apscesom akcesornih žlijezda", "A54.1"),
    A54_2("Gonokokni pelvioperitonitis i druge gonokokne infekcije genitourinarnog sustava", "A54.2"),
    A54_3("Gonokokna infekcija oka", "A54.3"),
    A54_4("Gonokokna infekcija mišićno koštanog sustava", "A54.4"),
    A54_5("Gonokokni faringitis", "A54.5"),
    A54_6("Gonokokna infekcija anusa i rektuma", "A54.6"),
    A54_8("Druge gonokokne infekcije", "A54.8"),
    A54_9("Gonokokna infekcija, nespecificirana", "A54.9"),
    A55("Klamidijski limfogranulom (venereum)", "A55"),
    A55_0("Klamidijski limfogranulom (venereum)", "A55.0"),
    A56("Druge spolno prenosive klamidijske bolesti", "A56"),
    A56_0("Klamidijske infekcije donjeg dijela genitourinarnog sustava", "A56.0"),
    A56_1("Klamidijske infekcije pelvioperitoneuma i drugih genitourinarnih organa", "A56.1"),
    A56_2("Klamidijska infekcija genitourinarnog sustava, nespecificirana", "A56.2"),
    A56_3("Klamidijska infekcija anusa i rektuma", "A56.3"),
    A56_4("Klamidijska infekcija ždrijela", "A56.4"),
    A56_8("Spolno prenesena klamidijska infekcija drugih lokalizacija", "A56.8"),
    A57("Kankroid", "A57"),
    A57_0("Kankroid", "A57.0"),
    A58("Granuloma inguinale", "A58"),
    A58_0("Granuloma inguinale", "A58.0"),
    A59("Trihomonijaza", "A59"),
    A59_0("Urogenitalna trihomonijaza", "A59.0"),
    A59_8("Trihomonijaza druge lokalizacije", "A59.8"),
    A59_9("Trihomonijaza, nespecificirana", "A59.9"),
    A60("Anogenitalni herpes (herpes simpleks)", "A60"),
    A60_0("Herpesvirusna infekcija genitalnog i urogenitalnog sustava", "A60.0"),
    A60_1("Herpesvirusna infekcija perianalne kože i rektuma", "A60.1"),
    A60_9("Anogenitalna herpesvirusna infekcija, nespecificirana", "A60.9"),
    A63("Ostale bolesti koje se poglavito prenose spolnim putem, nesvrstane drugamo", "A63"),
    A63_0("Anogenitalne (venerične) bradavice", "A63.0"),
    A63_8("Druge specificirane bolesti koje se prenose poglavito spolnim putem", "A63.8"),
    A64("Bolesti koje se prenose poglavito spolnim putem, nespecificirane", "A64"),
    A64_0("Bolesti koje se prenose poglavito spolnim putem, nespecificirane", "A64.0"),
    A65("Nevenerični sifilis", "A65"),
    A65_0("Nevenerični sifilis", "A65.0"),
    A66("Frambezija (yaws)", "A66"),
    A66_0("Inicijalna lezija kod frambezije", "A66.0"),
    A66_1("Multipli papilomi i wet crab frambezija", "A66.1"),
    A66_2("Druge rane kožne lezije kod frambezije", "A66.2"),
    A66_3("Hiperkeratoza kod frambezije", "A66.3"),
    A66_4("Frambezijska guma i ulkus", "A66.4"),
    A66_5("Gangosa", "A66.5"),
    A66_6("Lezije kosti i zglobova kod frambezije", "A66.6"),
    A66_7("Ostali oblici frambezije", "A66.7"),
    A66_8("Latentna frambezija", "A66.8"),
    A66_9("Frambezija, nespecificirana", "A66.9"),
    A67("Pinta (carate)", "A67"),
    A67_0("Primarna lezija u pinte", "A67.0"),
    A67_1("Intermedijarne pinta lezije", "A67.1"),
    A67_2("Kasne pinta lezije", "A67.2"),
    A67_3("Miješane pinta lezije", "A67.3"),
    A67_9("Pinta, nespecificirana", "A67.9"),
    A68("Povratne groznice", "A68"),
    A68_0("Povratna groznica koju prenosi uš", "A68.0"),
    A68_1("Povratna groznica koju prenosi krpelj", "A68.1"),
    A68_9("Povratna groznica, nespecificirana", "A68.9"),
    A69("Ostale bolesti uzrokovane spirohetama", " A69"),
    A69_0("Nekrotizirajući ulcerativni stomatitis", " A69.0"),
    A69_1("Druge Vincentove infekcije", " A69.1"),
    A69_2("Lyme borelioza (Lymeova bolest)", " A69.2"),
    A69_8("Ostale specificirane infekcije spirohetama", " A69.8"),
    A69_9("Infekcija spirohetama, nespecificirana", " A69.9"),
    A70("Infekcije koje uzrokuje Chlamydia psittaci", "A70"),
    A70_0("Infekcija koju uzrokuje Chlamydia psittaci", "A70.0"),
    A71("Trahom", "A71"),
    A71_0("Inicijalni stadij trahoma", "A71.0"),
    A71_1("Aktivni stadij trahoma", "A71.1"),
    A71_9("Trahom, nespecificiran", "A71.9"),
    A74("Ostale bolesti uzrokovane klamidijama", "A74"),
    A74_0("Klamidijski konjunktivitis (H13.1*)", "A74.0"),
    A74_8("Ostale bolesti uzrokovane klamidijama", "A74.8"),
    A74_9("Klamidijska infekcija, nespecificirana", "A74.9"),
    A75("Tifusna groznica", "A75"),
    A75_0("Epidemijski tifus koji uzrokuje Rickettsia prowazekii, a prenose ga uši (pjegavac)", "A75.0"),
    A75_1("Kasni recidiv pjegavca (Brillova bolest)", "A75.1"),
    A75_2("Tifusna groznica koju uzrokuje Rickettsia typhi", "A75.2"),
    A75_3("Tifusna groznica koju uzrokuje Rickettsia tsutsugamushi", "A75.3"),
    A75_9("Tifusna groznica, nespecificirana", "A75.9"),
    A77("Pjegava groznica (rikecioze koje prenose krpelji)", "A77"),
    A77_0("Pjegava groznica koju uzrokuje Rickettsia rickettsii", "A77.0"),
    A77_1("Pjegava groznica koju uzrokuje Rickettsia conorii", "A77.1"),
    A77_2("Pjegava groznica koju uzrokuje Rickettsia siberica", "A77.2"),
    A77_3("Pjegava groznica koju uzrokuje Rickettsia australis", "A77.3"),
    A77_8("Ostale pjegave groznice", "A77.8"),
    A77_9("Pjegava groznica, nespecificirana", "A77.9"),
    A78("Q-groznica", "A78"),
    A78_0("Q-groznica", "A78.0"),
    A79("Ostale rikecioze", "A79"),
    A79_0("Rovovska groznica (trench fever)", "A79.0"),
    A79_1("Rikecijske boginje koje uzrokuje Rickettsia akari", "A79.1"),
    A79_8("Druge specificirane rikecioze", "A79.8"),
    A79_9("Rikecioza, nespecificirana", "A79.9"),
    A80("Akutni poliomijelitis", "A80"),
    A80_0("Akutni paralitični poliomijelitis, u vezi s cijepljenjem", "A80.0"),
    A80_1("Akutni paralitični poliomijelitis, divlji virus, unesen", "A80.1"),
    A80_2("Akutni paralitični poliomijelitis, divlji virus, autohtoni", "A80.2"),
    A80_3("Akutni paralitični poliomijelitis, ostali i nespecificirani", "A80.3"),
    A80_4("Akutni neparalitični poliomijelitis", "A80.4"),
    A80_9("Akutni poliomijelitis, nespecificiran", "A80.9"),
    A81("Virusne infekcije središnjega živčanog sustava sporog tijeka (slow virus infections)", "A81"),
    A81_0("Creutzfeld-Jakobova bolest", "A81.0"),
    A81_1("Subakutni sklerozirajući panencefalitis", "A81.1"),
    A81_2("Progresivna multifokalna leukoencefalopatija", "A81.2"),
    A81_8("Druge virusne infekcije središnjega živčanog sustava sporog tijeka", "A81.8"),
    A81_9("Virusna infekcija središnjega živčanog sustava sporog tijeka, nespecificirana", "A81.9"),
    A82("Bjesnoća (rabies)", "A82"),
    A82_0("Silvatična bjesnoća", "A82.0"),
    A82_1("Urbana bjesnoća", "A82.1"),
    A82_9("Bjesnoća, nespecificirana", "A82.9"),
    A83("Virusni encefalitis koji prenose komarci", "A83"),
    A83_0("Japanski encefalitis", "A83.0"),
    A83_1("Zapadni konjski encefalitis", "A83.1"),
    A83_2("Istočni konjski encefalitis", "A83.2"),
    A83_3("St Louis encefalitis", "A83.3"),
    A83_4("Australski encefalitis", "A83.4"),
    A83_5("Kalifornijski encefalitis", "A83.5"),
    A83_6("Bolest uzrokovana Rocio virusima", "A83.6"),
    A83_8("Drugi virusni encefalitis koji prenose komarci", "A83.8"),
    A83_9("Virusni encefalitis koji prenose komarci, nespecificiran", "A83.9"),
    A84("Virusni encefalitis koji prenose krpelji", "A84"),
    A84_0("Dalekoistočni krpeljni encefalitis (ruski proljetno-ljetni encefalitis)", "A84.0"),
    A84_1("Srednjoeuropski krpeljni encefalitis", "A84.1"),
    A84_8("Drugi virusni encefalitisi koje prenose krpelji", "A84.8"),
    A84_9("Virusni encefalitis koji prenose krpelji, nespecificiran", "A84.9"),
    A85("Ostali virusni encefalitisi, nesvrstani drugamo", "A85"),
    A85_0("Enterovirusni encefalitis (G05.1*)", "A85.0"),
    A85_1("Adenovirusni encefalitis (G05.1*)", "A85.1"),
    A85_2("Arbo (arthropod-borne) virusni encefalitis, nespecificirani", "A85.2"),
    A85_8("Ostali specificirani virusni encefalitisi", "A85.8"),
    A86("Nespecificirani virusni encefalitis", "A86"),
    A86_0("Nespecificirani virusni encefalitis", "A86.0"),
    A87("Virusni meningitisi", "A87"),
    A87_0("Enterovirusni meningitis (G02.0*)", "A87.0"),
    A87_1("Adenovirusni meningitis (G02.0*)", "A87.1"),
    A87_2("Limfocitarni horiomeningitis", "A87.2"),
    A87_8("Ostali virusni meningitisi", "A87.8"),
    A87_9("Virusni meningitis, nespecificiran", "A87.9"),
    A88("Druge virusne infekcije središnjega živčanog sustava, nesvrstane drugamo", "A88"),
    A88_0("Enterovirusna osipna groznica (Bostonski egzantem)", "A88.0"),
    A88_1("Epidemijski vertigo", "A88.1"),
    A88_8("Ostale specificirane virusne infekcije središnjega živčanog sustava", "A88.8"),
    A89("Nespecificirane virusne infekcije središnjega živčanog sustava", "A89"),
    A89_0("Nespecificirane virusne infekcije središnjega živčanog sustava", "A89.0"),
    A90("Dengue (groznica) (klasična denga)", "A90"),
    A90_0("Dengue (groznica) (klasična denga)", "A90.0"),
    A91("Denga hemoragijska groznica", "A91"),
    A91_0("Denga hemoragijska groznica", "A91.0"),
    A92("Ostale virusne groznice koje prenose komarci", "A92"),
    A92_0("Chikungunya virusna bolest", "A92.0"),
    A92_1("O'nyong-nyong groznica", "A92.1"),
    A92_2("Venezuelska konjska groznica", "A92.2"),
    A92_3("West Nile groznica (groznica zapadnog Nila)", "A92.3"),
    A92_4("Rift Valley groznica (groznica doline Rift)", "A92.4"),
    A92_8("Druge specificirane virusne groznice koje prenose komarci", "A92.8"),
    A92_9("Virusne groznice koje prenose komarci, nespecificirane", "A92.9"),
    A93("Druge arbovirusne groznice, nesvrstane drugamo", "A93"),
    A93_0("Oropouche virusna bolest", "A93.0"),
    A93_1("Sandfly fever", "A93.1"),
    A93_2("Kolorado krpeljna groznica", "A93.2"),
    A93_8("Ostale specificirane arbovirusne groznice", "A93.8"),
    A94("Nespecificirane arbovirusne groznice", "A94"),
    A94_0("Nespecificirane arbovirusne groznice", "A94.0"),
    A95("Žuta groznica", "A95"),
    A95_0("Silvatična žuta groznica", "A95.0"),
    A95_1("Urbana žuta groznica", "A95.1"),
    A95_9("Žuta groznica, nespecificirana", "A95.9"),
    A96("Hemoragijska groznica uzrokovana arenavirusima", "A96"),
    A96_0("Junin hemoragijska groznica", "A96.0"),
    A96_1("Machupo hemoragijska groznica", "A96.1"),
    A96_2("Lassa groznica", "A96.2"),
    A96_8("Ostale arenavirusne hemoragijske groznice", "A96.8"),
    A96_9("Arenavirusna hemoragijska groznica, nespecificirana", "A96.9"),
    A98("Druge virusne hemoragijske groznice, nesvrstane drugamo", "A98"),
    A98_0("Krimsko-Kongoanska hemoragijska groznica", "A98.0"),
    A98_1("Omska hemoragijska groznica", "A98.1"),
    A98_2("Kyasanur Forest groznica (groznica šume Kyasanur)", "A98.2"),
    A98_3("Marburška hemoragijska groznica", "A98.3"),
    A98_4("Ebola hemoragijska groznica", "A98.4"),
    A98_5("Hemoragijska groznica s bubrežnim sindromom", "A98.5"),
    A98_8("Druge specificirane virusne hemoragijske groznice", "A98.8"),
    A99("Nespecificirane virusne hemoragijske groznice", "A99"),
    A99_0("Nespecificirane virusne hemoragijske groznice", "A99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesA(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
