package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesF {
    F00("Demencija u Alzheimerovoj bolesti", "F00"),
    F00_0("Demencija u Alzheimerovoj bolesti, s ranim početkom", "F00.0"),
    F00_1("Demencija u Alzheimerovoj bolesti, s kasnim početkom", "F00.1"),
    F00_2("Atipična ili mješovita demencija u Alzheimerovoj bolesti", "F00.2"),
    F00_9("Demencija u Alzheimerovoj bolesti, nespecificirana", "F00.9"),
    F01("Vaskularna demencija", "F01"),
    F01_0("Akutna vaskularna demecija", "F01.0"),
    F01_1("Demencija zbog više infarkta", "F01.1"),
    F01_2("Vaskularna demencija u potkori mozga", "F01.2"),
    F01_3("Vaskularna demencija u kori i potkori mozga", "F01.3"),
    F01_8("Druga vaskularna demencija", "F01.8"),
    F01_9("Vaskularna demencija, nespecificirana", "F01.9"),
    F02("Demencija u drugim bolestima", "F02"),
    F02_0("Demencija u Pickovoj bolesti", "F02.0"),
    F02_1("Demencija u Creutzfeldt-Jakobovoj bolesti", "F02.1"),
    F02_2("Demencija u Huntingtonovoj bolesti", "F02.2"),
    F02_3("Demencija u Parkinsonovoj bolesti", "F02.3"),
    F02_4("Demencija u bolesti AIDSa", "F02.4"),
    F02_8("Demencija u drugim označenim bolestima", "F02.8"),
    F03("Demencija, nespecificirana", "F03"),
    F04("Organski sindrom amnezije", "F04"),
    F05("Delirij", "F05"),
    F05_0("Delirij bez demencije", "F05.0"),
    F05_1("Delirij s demencijom", "F05.1"),
    F05_8("Drugi deliriji", "F05.8"),
    F05_9("Delirij, nespecificiran", "F05.9"),
    F06("Drugi mentalni poremećaji uzrokovani oštećenjem i disfunkcijom mozga te tjelesnom bolešću", "F06"),
    F06_0("Organska halucinoza", "F06.0"),
    F06_1("Organski katatoni poremećaj", "F06.1"),
    F06_2("Organski sumanuti poremećaj (sličan shizofreniji)", "F06.2"),
    F06_3("Organski poremećaji raspoloženja", "F06.3"),
    F06_4("Organski anksiozni poremećaj", "F06.4"),
    F06_5("Organski disocijativni poremećaj", "F06.5"),
    F06_6("Organski emocionalni poremećaj (astenički)", "F06.6"),
    F06_7("Blagi kognitivni poremećaj", "F06.7"),
    F06_8("Drugi specificirani mentalni poremećaji uzrokovani oštećenjem i disfunkcijom mozga i bolešću tijela", "F06.8"),
    F06_9("Mentalni poremećaj uzrokovan oštećenjem i disfunkcijom mozga i bolešću tijela, nespecificiran", "F06.9"),
    F07("Poremećaji ličnosti i ponašanja uzrokovani bolešću, oštećenjem i disfunkcijom mozga", "F07"),
    F07_0("Organski poremećaji ličnosti", "F07.0"),
    F07_1("Postencefalitički sindrom", "F07.1"),
    F07_2("Sindrom poslije potresa mozga", "F07.2"),
    F07_8("Drugi organski poremećaji ličnosti i ponašanja uzrokovani bolešću, oštećenjem i disfunkcijom mozga", "F07.8"),
    F07_9("Organski poremećaji ličnosti i poremećaj ponašanja, uzrokovan bolešću, oštećenjem i disfunkcijom mozga, nespecificiran", "F07.9"),
    F09("Nespecificirani organski ili simptomatski mentalni poremećaji", "F09"),
    F09_0("Akutno trovanje", "F09.0"),
    F09_1("Zloupotreba", "F09.1"),
    F09_2("Sindrom ovisnosti", "F09.2"),
    F09_3("Apstinencijski sindrom", "F09.3"),
    F09_4("Apstinencijski sindrom s delirijem", "F09.4"),
    F09_5("Mentalni poremećaj", "F09.5"),
    F09_6("Sindrom amnezije", "F09.6"),
    F09_7("Psihotičke posljedice i kasni početak", "F09.7"),
    F09_8("Drugi mentalni poremećaji i poremećaji ponašanja", "F09.8"),
    F09_9("Mentalni poremećaj i poremećaj ponašanja, nespecificiran", "F09.9"),
    F10("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje", "F10"),
    F10_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, akutna intoksikacija", "F10.0"),
    F10_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, zloupotreba", "F10.1"),
    F10_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, sindrom ovisnosti", "F10.2"),
    F10_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, apsitencijski sindrom", "F10.3"),
    F10_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, apstinencijski sindrom s delirijem", "F10.4"),
    F10_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, psihotični poremećaj", "F10.5"),
    F10_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, sindrom amnezije", "F10.6"),
    F10_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, psihotični poremećaj", "F10.7"),
    F10_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, drugi mentalni poremećaji i poremećaji ponašanja", "F10.8"),
    F10_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola - akutno trovanje, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F10.9"),
    F11("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida", "F11"),
    F11_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, akutna intoksikacija", "F11.0"),
    F11_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, zloupotreba", "F11.1"),
    F11_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, sindrom ovisnosti", "F11.2"),
    F11_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, apsitencijski sindrom", "F11.3"),
    F11_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, apstinencijski sindrom s delirijem", "F11.4"),
    F11_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, psihotični poremećaj", "F11.5"),
    F11_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, sindrom amnezije", "F11.6"),
    F11_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, psihotični poremećaj", "F11.7"),
    F11_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, drugi mentalni poremećaji i poremećaji ponašanja", "F11.8"),
    F11_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom opioida, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F11.9"),
    F12("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida", "F12"),
    F12_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, akutna intoksikacija", "F12.0"),
    F12_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, zloupotreba", "F12.1"),
    F12_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, sindrom ovisnosti", "F12.2"),
    F12_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, apsitencijski sindrom", "F12.3"),
    F12_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, apstinencijski sindrom s delirijem", "F12.4"),
    F12_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, psihotični poremećaj", "F12.5"),
    F12_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, sindrom amnezije", "F12.6"),
    F12_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, psihotični poremećaj", "F12.7"),
    F12_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, drugi mentalni poremećaji i poremećaji ponašanja", "F12.8"),
    F12_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kanabinoida, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F12.9"),
    F13("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa", "F13"),
    F13_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, akutna intoksikacija", "F13.0"),
    F13_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, zloupotreba", "F13.1"),
    F13_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, sindrom ovisnosti", "F13.2"),
    F13_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, apsitencijski sindrom", "F13.3"),
    F13_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, apstinencijski sindrom s delirijem", "F13.4"),
    F13_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, psihotični poremećaj", "F13.5"),
    F13_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, sindrom amnezije", "F13.6"),
    F13_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, psihotični poremećaj", "F13.7"),
    F13_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, drugi mentalni poremećaji i poremećaji ponašanja", "F13.8"),
    F13_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom hipnotika ili sedativa, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F13.9"),
    F14("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina", "F14"),
    F14_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, akutna intoksikacija", "F14.0"),
    F14_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, zloupotreba", "F14.1"),
    F14_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, sindrom ovisnosti", "F14.2"),
    F14_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, apsitencijski sindrom", "F14.3"),
    F14_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, apstinencijski sindrom s delirijem", "F14.4"),
    F14_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, psihotični poremećaj", "F14.5"),
    F14_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, sindrom amnezije", "F14.6"),
    F14_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, psihotični poremećaj", "F14.7"),
    F14_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, drugi mentalni poremećaji i poremećaji ponašanja", "F14.8"),
    F14_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom kokaina, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F14.9"),
    F15("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein", "F15"),
    F15_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, akutna intoksikacija", "F15.0"),
    F15_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, zloupotreba", "F15.1"),
    F15_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, sindrom ovisnosti", "F15.2"),
    F15_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, apsitencijski sindrom", "F15.3"),
    F15_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, apstinencijski sindrom s delirijem", "F15.4"),
    F15_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, psihotični poremećaj", "F15.5"),
    F15_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, sindrom amnezije", "F15.6"),
    F15_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, psihotični poremećaj", "F15.7"),
    F15_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, drugi mentalni poremećaji i poremećaji ponašanja", "F15.8"),
    F15_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom drugih stimulansa, uključujući kofein, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F15.9"),
    F16("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena", "F16"),
    F16_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, akutna intoksikacija", "F16.0"),
    F16_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, zloupotreba", "F16.1"),
    F16_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, sindrom ovisnosti", "F16.2"),
    F16_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, apsitencijski sindrom", "F16.3"),
    F16_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, apstinencijski sindrom s delirijem", "F16.4"),
    F16_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, psihotični poremećaj", "F16.5"),
    F16_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, sindrom amnezije", "F16.6"),
    F16_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, psihotični poremećaj", "F16.7"),
    F16_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, drugi mentalni poremećaji i poremećaji ponašanja", "F16.8"),
    F16_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom halucinogena, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F16.9"),
    F17("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana", "F17"),
    F17_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, akutna intoksikacija", "F17.0"),
    F17_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, zloupotreba", "F17.1"),
    F17_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, sindrom ovisnosti", "F17.2"),
    F17_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, apsitencijski sindrom", "F17.3"),
    F17_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, apstinencijski sindrom s delirijem", "F17.4"),
    F17_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, psihotični poremećaj", "F17.5"),
    F17_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, sindrom amnezije", "F17.6"),
    F17_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, psihotični poremećaj", "F17.7"),
    F17_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, drugi mentalni poremećaji i poremećaji ponašanja", "F17.8"),
    F17_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom duhana, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F17.9"),
    F18("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala", "F18"),
    F18_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, akutna intoksikacija", "F18.0"),
    F18_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, zloupotreba", "F18.1"),
    F18_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, sindrom ovisnosti", "F18.2"),
    F18_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, apsitencijski sindrom", "F18.3"),
    F18_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, apstinencijski sindrom s delirijem", "F18.4"),
    F18_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, psihotični poremećaj", "F18.5"),
    F18_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, sindrom amnezije", "F18.6"),
    F18_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, psihotični poremećaj", "F18.7"),
    F18_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, drugi mentalni poremećaji i poremećaji ponašanja", "F18.8"),
    F18_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom isparavajućih otapala, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F18.9"),
    F19("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari", "F19"),
    F19_0("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, akutna intoksikacija", "F19.0"),
    F19_1("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, zloupotreba", "F19.1"),
    F19_2("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, sindrom ovisnosti", "F19.2"),
    F19_3("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, apsitencijski sindrom", "F19.3"),
    F19_4("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, apstinencijski sindrom s delirijem", "F19.4"),
    F19_5("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, psihotični poremećaj", "F19.5"),
    F19_6("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, sindrom amnezije", "F19.6"),
    F19_7("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, psihotični poremećaj", "F19.7"),
    F19_8("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, drugi mentalni poremećaji i poremećaji ponašanja", "F19.8"),
    F19_9("Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom više vrsta droga i drugih psihoaktivnih tvari, nespecificirani mentalni poremećaj i poremećaj ponašanja", "F19.9"),
    F20("Shizofrenija", "F20"),
    F20_0("Paranoidna shizofrenija", "F20.0"),
    F20_1("Hebefrena shizofrenija", "F20.1"),
    F20_2("Katatona shizofrenija", "F20.2"),
    F20_3("Nediferencirana shizofrenija", "F20.3"),
    F20_4("Postshizofrena depresija", "F20.4"),
    F20_5("Rezidualna shizofrenija", "F20.5"),
    F20_6("Obična shizofrenija", "F20.6"),
    F20_8("Druga shizofrenija", "F20.8"),
    F20_9("Shizofrenija, nespecificirani", "F20.9"),
    F21("Poremećaj sličan shizofreniji", "F21"),
    F22("Stalna sumanuta stanja", "F22"),
    F22_0("Paranoja", "F22.0"),
    F22_8("Druga stalna sumanuta stanja", "F22.8"),
    F22_9("Stalno sumanuto stanje, nespecificirani", "F22.9"),
    F23("Akutna i prolazna mentalna oboljenja", "F23"),
    F23_0("Akutni polimorfni psihotični poremećaj bez simptoma shizofrenije", "F23.0"),
    F23_1("Akutni polimorfni psihotični poremećaj sa simptomima shizofrenije", "F23.1"),
    F23_2("Akutni mentalni poremećaj sličan shizofreniji", "F23.2"),
    F23_3("Drugi akutni pretežno sumanuti psihotični poremećaji", "F23.3"),
    F23_8("Drugi akutni i prolazni psihotični poremećaj", "F23.8"),
    F23_9("Akutni i prolazni psihotični poremećaj, nespecificiran", "F23.9"),
    F24("Inducirano sumanuto stanje (Folie à deux)", "F24"),
    F25("Shizoafektivni poremećaji", "F25"),
    F25_0("Shizoafektivni poremećaj, tip manija", "F25.0"),
    F25_1("Shizoafektivni poremećaj, tip depresija", "F25.1"),
    F25_2("Shizoafektivni poremećaj, mješoviti tip", "F25.2"),
    F25_8("Drugi shizoafektivni poremećaji", "F25.8"),
    F25_9("Shizoafektivni poremećaj, nespecificirani", "F25.9"),
    F28("Drugi neorganski psihotični poremećaji", "F28"),
    F29("Neorganske psihoze, nespecificirani", "F29"),
    F30("Epizode manije", "F30"),
    F30_0("Hipomanija", "F30.0"),
    F30_1("Manija bez simptoma psihoze", "F30.1"),
    F30_2("Manija sa simptomima psihoze", "F30.2"),
    F30_8("Druge manijske epizode", "F30.8"),
    F30_9("Manijska epizoda, nespecificirana", "F30.9"),
    F31("Bipolarni poremećaj", "F31"),
    F31_0("Bipolarni afektivni poremećaj, hipomanijska epizoda", "F31.0"),
    F31_1("Bipolarni afektivni poremećaj, manijska epizoda bez simptoma psihoze", "F31.1"),
    F31_2("Bipolarni afektivni poremećaj, manijska epizoda sa simptomima psihoze", "F31.2"),
    F31_3("Bipolarni afektivni poremećaj, blaga ili umjerena depresijska epizoda", "F31.3"),
    F31_4("Bipolarni afektivni poremećaj, teška depresijska epizoda bez simptoma psihoza", "F31.4"),
    F31_5("Bipolarni afektivni poremećaj, teška depresijska epizoda sa simptomima psihoze", "F31.5"),
    F31_6("Bipolarni afektivni poremećaj, mješovita epizoda", "F31.6"),
    F31_7("Bipolarni afektivni poremećaj, u remisiji", "F31.7"),
    F31_8("Drugi bipolarni afektivni poremećaj", "F31.8"),
    F31_9("Bipolarni afektivni poremećaj, nespecificiran", "F31.9"),
    F32("Depresija", "F32"),
    F32_0("Blaga depresijska epizoda", "F32.0"),
    F32_1("Umjerena depresijska epizoda", "F32.1"),
    F32_2("Teška depresijska epizoda bez simptoma psihoze", "F32.2"),
    F32_3("Teška depresijska epizoda sa simptomima psihoze", "F32.3"),
    F32_8("Druge depresijske epizode", "F32.8"),
    F32_9("Depresijska epizoda, nespecificirana", "F32.9"),
    F33("Povratni depresijski poremećaj", "F33"),
    F33_0("Blag povratni depresijski poremećaj", "F33."),
    F33_1("Umjeren povratni depresijski poremećaj", "F33."),
    F33_2("Težak povratni depresijski poremećaj bez simptoma psihoze", "F33."),
    F33_3("Težak povratan depresijski poremećaj sa simptomima psihoze", "F33."),
    F33_4("Povratni depresijski poremećaj, u remisiji", "F33."),
    F33_8("Drugi povratni depresijski poremećaj", "F33."),
    F33_9("Povratni depresijski poremećaj, nespecificiran", ""),
    F34("Stalni poremećaji raspoloženja", "F34"),
    F34_0("Ciklotimija", "F34.0"),
    F34_1("Distimija", "F34.1"),
    F34_8("Drugi stalni poremećaji raspoloženja", "F34.8"),
    F34_9("Stalni poremećaj raspoloženja, nespecificiran", "F34.9"),
    F38("Drugi poremećaji raspoloženja", "F38"),
    F38_0("Drugi pojedinačni poremećaji raspoloženja", "F38.0"),
    F38_1("Drugi povratni poremećaji raspoloženja", "F38.1"),
    F38_8("Drugi specificirani poremećaji raspoloženja", "F38.8"),
    F39("Poremećaj raspoloženja, nespecificiran", "F39"),
    F40("Fobični anksiozni poremećaji", "F40"),
    F40_0("Agorafobija", "F40.0"),
    F40_1("Socijalna fobija", "F40.1"),
    F40_2("Specificirana (izolirana) fobija", "F40.2"),
    F40_8("Drugi fobijsko-anksiozni poremećaji", "F40.8"),
    F40_9("Fobijsko-anksiozni poremećaj, nespecificiran", "F40.9"),
    F41("Drugi anksiozni poremećaj", "F41"),
    F41_0("Panični poremećaj, epizodna paroksizimalna anksioznost", "F41.0"),
    F41_1("Anksiozni generalizirani poremećaj", "F41.1"),
    F41_2("Mješoviti anksiozni i depresijski poremećaj", "F41.2"),
    F41_9("Anksiozni poremećaj, nespecificiran", "F41.9"),
    F42("Opsesivno-kompulzivni poremećaj", "F42"),
    F42_9("Opsesivno-kompulzivni poremećaj, nespecificiran", "F42.9"),
    F43("Reakcija na teški stres i poremećaji prilagođavanja", "F43"),
    F43_0("Akutna reakcija na stres", "F43.0"),
    F43_1("Posttraumatski stresni poremećaj", "F43.1"),
    F43_2("Poremećaj prilagođavanja", "F43.2"),
    F44("Disocijativni (konverzivni) poremećaji", "F44"),
    F44_0("Disocijativna amnezija", "F44.0"),
    F44_1("Psihogeno lutanje", "F44.1"),
    F44_2("Disocijativna ošamućenost", "F44.2"),
    F44_3("Trans i poremećaji posjedovanja", "F44.3"),
    F44_4("Disocijativni mišićni poremećaj", "F44.4"),
    F44_5("Disocijativne konvulzije", "F44.5"),
    F44_6("Disocijativna anestezija i gubitak senzornih funkcija", "F44.6"),
    F44_7("Mješoviti disocijativni (konverzivni) poremećaji", "F44.7"),
    F44_8("Drugi disocijativni (konverzivni) poremećaji (Ganserov sindrom) (Višestruka osobnost)", "F44.8"),
    F45("Somatoformni poremećaji", "F45"),
    F45_0("Somatizacijski poremećaj", "F45.0"),
    F45_1("Nediferencirani somatoformni poremećaj", "F45.1"),
    F45_2("Hipohondrija", "F45.2"),
    F45_3("Somatoformna disfunkcija vegetativnog živčanog sustava", "F45.3"),
    F45_4("Perzistirajući somatoformni bolni poremećaj", "F45.4"),
    F45_8("Ostali somatoformni poremećaji", "F45.8"),
    F45_9("Somatoformni poremećaj, nespecificiran", "F45.9"),
    F48("Drugi neurotski poremećaji", "F48"),
    F48_0("Neurastenija", "F48.0"),
    F48_1("Sindrom depersonalizacije", "F48.1"),
    F50("Poremećaj hranjenja", "F50"),
    F50_0("Anoreksija nervosa", "F50.0"),
    F50_1("Atipična anoreksija nervosa", "F50.1"),
    F50_2("Bulimija", "F50.2"),
    F50_3("Atipična bulimija", "F50.3"),
    F50_4("Pretjerano jedenje s drugim psihičkim smetnjama", "F50.4"),
    F50_5("Povraćanje s drugim psihičkim smetnjama", "F50.5"),
    F50_8("Drugi poremećaji hranjenja (Pika, u odraslih)", "F50.8"),
    F51("Neorganski poremećaji spavanja", "F51"),
    F51_0("Neorganska insomnija", "F51.0"),
    F51_1("Neorganska hipersomnija", "F51.1"),
    F51_2("Neorganski poremećaj ritma spavanja", "F51.2"),
    F51_3("Mjesečarenje", "F51.3"),
    F51_4("Noćni strah", "F51.4"),
    F51_5("Noćne more", "F51.5"),
    F52("Seksualna disfunkcija", "F52"),
    F52_0("Nedostatak ili gubitak spolne želje", "F52.0"),
    F52_1("Seksualna averzija i nedostatak spolnog užitka", "F52.1"),
    F52_2("Izostanak genitalnog odgovora", "F52.2"),
    F52_3("Poremećaj orgazma", "F52.3"),
    F52_4("Prijevremena ejakulacija", "F52.4"),
    F52_5("Neorganski vaginizam", "F52.5"),
    F52_6("Neorganska dispaurenija", "F52.6"),
    F52_7("Pretjerani spolni nagon (Erotomanija) (Nimfomanija)", "F52.7"),
    F52_8("Drugi neorganski poremećaj spolnog odnosa", "F52.8"),
    F52_9("Neorganski poremećaj spolnog odnosa, nespecificiran", "F52.9"),
    F53("Mentalni poremećaji i poremećaji udruženi s babinjama (postporođajni period)", "F53"),
    F53_0("Blagi mentalni poremećaj i poremećaj ponašanja s babinjama", "F53.0"),
    F53_1("Težak mentalni poremećaj i poremećaj ponašanja udružen s babinjama", "F53.1"),
    F53_8("Drugi mentalni poremećaji i poremećaji ponašanja udruženi s babinjama", "F53.8"),
    F53_9("Mentalni poremećaj u babinjama, nespecificiran", "F53.9"),
    F54("Psihološki poremećaji i poremećaji ponašanja u drugim bolestima", "F54"),
    F55("Zloupotreba lijekova bez uzrokovanja tolerancije", "F55"),
    F59("Sindromi ponašanja udruženi s fiziološkim smetnjama i fizičkim čimbenicima, nespecificirani", "F59"),
    F60("Specificirani poremećaji ličnosti", "F60"),
    F60_0("Paranoidni poremećaj ličnosti", "F60.0"),
    F60_1("Shizoidni poremećaji ličnosti", "F60.1"),
    F60_2("Disocijalni poremećaj ličnosti", "F60.2"),
    F60_3("Granični poremećaj ličnosti (Borderline poremećaj osobnosti)", "F60.3"),
    F60_4("Histrionski poremećaj ličnosti", "F60.4"),
    F60_5("Anankastički poremećaj ličnosti", "F60.5"),
    F60_6("Anksiozni (izbjegavajući) poremećaj ličnosti", "F60.6"),
    F60_7("Ovisna ličnost", "F60.7"),
    F60_9("Poremećaj ličnosti, nespecificiran", "F60.9"),
    F61("Mješoviti i drugi poremećaji ličnosti", "F61"),
    F62("Trajna promjena ličnosti neorganskog porijekla", "F62"),
    F62_0("Trajna promjena ličnosti nakon doživljene katastrofe", "F62.0"),
    F62_1("Trajna promjena ličnosti nakon psihijatrijske bolesti", "F62.1"),
    F62_8("Druge trajne promjene ličnosti", "F62.8"),
    F62_9("Trajna promjena ličnosti, nespecificirana", "F62.9"),
    F63("Poremećaji navika i impulsa", "F63"),
    F63_0("Patološko kockanje", "F63.0"),
    F63_1("Piromanija", "F63.1"),
    F63_2("Kleptomanija", "F63.2"),
    F63_3("Trihotilomanija", "F63.3"),
    F63_8("Drugi poremećaji navika i impulsa", "F63.8"),
    F63_9("Poremećaj navika i impulsa, nespecificiran", "F63.9"),
    F64("Poremećaj spolnog identiteta", "F64"),
    F64_0("Transseksualizam", "F64.0"),
    F64_1("Transvestitizam", "F64.1"),
    F64_2("Poremećaj spolnog identiteta u djetinjstvu", "F64.2"),
    F64_8("Drugi poremećaji spolnog identiteta", "F64.8"),
    F64_9("Poremećaj spolnog identiteta, nespecificiran", "F64.9"),
    F65("Poremećaji spolne sklonosti", "F65"),
    F65_0("Fetišizam", "F65.0"),
    F65_1("Fetišistički transvestitizam", "F65.1"),
    F65_2("Egzibicionizam", "F65.2"),
    F65_3("Voajerizam", "F65.3"),
    F65_4("Pedofilija", "F65.4"),
    F65_5("Sadomazohizam", "F65.5"),
    F65_6("Višestruki poremećaji spolne sklonosti", "F65.6"),
    F65_8("Drugi poremećaji spolne sklonosti (Nekrofilija)", "F65.8"),
    F65_9("Poremećaj spolne sklonosti, nespecificiran", "F65.9"),
    F66("Psihološki poremećaji i poremećaji ponašanja povezani sa spolnim razvojem i orijentacijom", "F66"),
    F66_0("Poremećaj spolnog sazrijevanja", "F66.0"),
    F66_1("Egodistonička spolna orijentacija", "F66.1"),
    F66_2("Poremećaj spolnog odnosa partnera", "F66.2"),
    F66_8("Drugi psihoseksualni razvojni poremećaji", "F66.8"),
    F66_9("Psihoseksualni razvojni poremećaj, nespecificiran", "F66.9"),
    F68("Drugi poremećaji ličnosti i poremećaji ponašanja odraslih", "F68"),
    F68_0("Obrada tjelesnih simptoma zbog psihičkih razloga", "F68.0"),
    F68_1("Namjerno izazivanje ili simulacija tjelesnih simptoma psihičkih nesposobnosti", "F68.1"),
    F68_8("Drugi specificirani poremećaji ličnosti i poremećaji ponašanja odraslih", "F68.8"),
    F69("Poremećaji ličnosti i poremećaji ponašanja odrasle osobe, nespecificirani", "F69"),
    F70("Laka mentalna retardacija", "F70"),
    F70_0("Laka mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F70.0"),
    F70_1("Laka mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F70.1"),
    F70_8("Laka mentalna retardacija, ostala oštećenja ponašanja", "F70.8"),
    F70_9("Laka mentalna retardacija, bez spominjanja oštećenja ponašanja", "F70.9"),
    F71("Umjerena mentalna retardacija", "F71"),
    F71_0("Umjerena mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F71.0"),
    F71_1("Umjerena mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F71.1"),
    F71_8("Umjerena mentalna retardacija, ostala oštećenja ponašanja", "F71.8"),
    F71_9("Umjerena mentalna retardacija, bez spominjanja oštećenja ponašanja", "F71.9"),
    F72("Teža mentalna retardacija", "F72"),
    F72_0("Teža mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F72.0"),
    F72_1("Teža mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F72.1"),
    F72_8("Teža mentalna retardacija, ostala oštećenja ponašanja", "F72.8"),
    F72_9("Teža mentalna retardacija, bez spominjanja oštećenja ponašanja", "F72.9"),
    F73("Teška mentalna retardacija", "F73"),
    F73_0("Teška mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F73.0"),
    F73_1("Teška mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F73.1"),
    F73_8("Teška mentalna retardacija, ostala oštećenja ponašanja", "F73.8"),
    F73_9("Teška mentalna retardacija, bez spominjanja oštećenja ponašanja", "F73.9"),
    F78("Ostala mentalna retardacija", "F78"),
    F78_0("Ostala mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F78.0"),
    F78_1("Ostala mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F78.1"),
    F78_8("Ostala mentalna retardacija, ostala oštećenja ponašanja", "F78.8"),
    F78_9("Ostala mentalna retardacija, bez spominjanja oštećenja ponašanja", "F78.9"),
    F79("Nespecificirana mentalna retardacija", "F79"),
    F79_0("Nespecificirana mentalna retardacija, nepostojanje ili minimalno oštećenje ponašanja", "F79.0"),
    F79_1("Nespecificirana mentalna retardacija, znatno oštećenje ponašanja koje zahtijeva nadzor ili liječenje", "F79.1"),
    F79_8("Nespecificirana mentalna retardacija, ostala oštećenja ponašanja", "F79.8"),
    F79_9("Nespecificirana mentalna retardacija, bez spominjanja oštećenja ponašanja", "F79.9"),
    F80("Specificirani poremećaji razvoja govora i jezika", "F80"),
    F80_0("Specificirani poremećaj artikulacije", "F80.0"),
    F80_1("Poremećaj ekspresivnog govora", "F80.1"),
    F80_2("Poremećaj receptivnog govora", "F80.2"),
    F80_3("Landau-Kleffnerov stečeni gubitak govora s epilepsijom", "F80.3"),
    F80_8("Drugi poremećaji razvoja govora i jezika", "F80.8"),
    F80_9("Poremećaj razvoja govora i jezika, nespecificiran", "F80.9"),
    F81("Specificirani razvojni poremećaji školskih vještina", "F81"),
    F81_0("Specificiran poremećaj čitanja", "F81.0"),
    F81_1("Specificiran poremećaj slovkanja", "F81.1"),
    F81_2("Specificiran poremećaj računanja", "F81.2"),
    F81_3("Mješoviti poremećaj sposobnosti za školovanje", "F81.3"),
    F81_8("Drugi poremećaji razvoja sposobnosti za školovanje", "F81.8"),
    F82("Specificirani poremećaj razvoja motoričkih funkcija", "F82"),
    F83("Mješoviti specificirani poremećaji razvoja", "F83"),
    F84("Pervazivni razvojni poremećaj", "F84"),
    F84_0("Dječji autizam", "F84.0"),
    F84_1("Atipičan autizam", "F84.1"),
    F84_2("Rettov sindrom", "F84.2"),
    F84_3("Drugi disintegrativni poremećaj djetinjstva", "F84.3"),
    F84_4("Poremećaj hiperaktivnosti povezan s mentalnom retardacijom i stereotipnim pokretima", "F84.4"),
    F84_5("Aspergerov sindrom", "F84.5"),
    F84_8("Drugi pervazivni poremećaji razvoja", "F84.8"),
    F84_9("Pervazivni poremećaj razvoja, nespecificiran", "F84.9"),
    F88("Drugi psihički poremećaji razvoja", "F88"),
    F89("Poremećaj psihičkog razvoja, nespecificiran", "F89"),
    F90("Hiperkinetski poremećaj", "F90"),
    F90_0("Poremećaj aktivnosti i pažnje (Poremećaj hiperaktivnosti i deficita pažnje (ADHD))", "F90.0"),
    F90_1("Hiperkinetski poremećaj ponašanja", "F90.1"),
    F90_8("Drugi hiperkinetski poremećaji", "F90.8"),
    F90_9("Hiperkinetski poremećaj, nespecificiran", "F90.9"),
    F91("Poremećaji ponašanja", "F91"),
    F91_0("Poremećaj ponašanja u kontekstu obitelji", "F91.0"),
    F91_1("Poremećaj ponašanja uzrokovan nepotpunom socijalizacijom", "F91.1"),
    F91_2("Poremećaj socijaliziranog ponašanja", "F91.2"),
    F91_3("Poremećaji protivljenja i prkosa", "F91.3"),
    F91_8("Drugi poremećaji ponašanja", "F91.8"),
    F91_9("Poremećaj ponašanja, nespecificiran", "F91.9"),
    F92("Mješoviti poremećaji ponašanja i emocija", "F92"),
    F92_0("Poremećaji ponašanja depresivna tipa", "F92.0"),
    F92_8("Drugi mješoviti poremećaji ponašanja i emocija", "F92.8"),
    F92_9("Mješoviti poremećaj ponašanja i emocija, nespecificiran", "F92.9"),
    F93("Emocionalni poremećaji s početkom u djetinjstvu", "F93"),
    F93_0("Anksiozni poremećaj odvajanja u djetinjstvu", "F93.0"),
    F93_1("Fobično-anksiozni poremećaj u djetinjstvu", "F93.1"),
    F93_2("Socijalno-anksiozni poremećaj u djetinjstvu", "F93.2"),
    F93_3("Rivalitet između braće i sestara", "F93.3"),
    F93_8("Drugi emocionalni poremećaj u djetinjstvu", "F93.8"),
    F93_9("Emocionalni poremećaj nastao u djetinjstvu, nespecificiran", "F93.9"),
    F94("Poremećaji socijalnog funkcioniranja nastali u djetinjstvu i adolescenciji", "F94"),
    F94_0("Elektivni mutizam", "F94.0"),
    F94_1("Reaktivni emocionalni poremećaj u djetinjstvu", "F94.1"),
    F94_2("Poremećaj neinhibiranosti u djetinjstvu", "F94.2"),
    F94_8("Drugi poremećaji socijalnog funkcioniranja u djetinjstvu", "F94.8"),
    F94_9("Poremećaj socijalnog funkcioniranja u djetinjstvu, nespecificiran", "F94.9"),
    F95("Tikovi", "F95"),
    F95_0("Prolazni tik", "F95.0"),
    F95_1("Kronični motorni ili glasovni tik", "F95.1"),
    F95_2("Kombinirani glasovno-motorni tik", "F95.2"),
    F95_8("Drugi tik", "F95.8"),
    F95_9("Tik, nespecificiran", "F95.9"),
    F98("Ostali poremećaji emocija i ponašanja nastali u djetinjstvu i adolescenciji", "F98"),
    F98_0("Neorganska enureza", "F98.0"),
    F98_1("Neorganska enkopreza", "F98.1"),
    F98_2("Poremećaj hranjenja dojenčadi i djeteta", "F98.2"),
    F98_3("Pika u ranom i kasnijem djetinjstvu", "F98.3"),
    F98_4("Poremećaj sa stereotinim pokretima", "F98.4"),
    F98_5("Mucanje", "F98.5"),
    F98_6("Eksplozivni govor s prekidima (Cluttering)", "F98.6"),
    F98_8("Drugi specificirani poremećaji emocija i poremećaji ponašanja s početkom u djetinjstvu", "F98.8"),
    F98_9("Poremećaji emocija i poremećaji ponašanja s početkom u djetinjstvu i adolescenciji, nespecificirani", "F98.9"),
    F99("Neodređeni mentalni poremećaj", "F99");
    
    private final String displayName;
    private final String code;
    
    MkbCodesF(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
