package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesW {
    
    W00("Pad na istoj razini na ledu i snijegu", "W00"),
    W00_0("Pad na istoj razini na ledu i snijegu", "W00.0"),
    W01("Pad na istoj razini prilikom okliznuća, spoticanja i posrtanja", "W01"),
    W01_0("Pad na istoj razini prilikom okliznuća, spoticanja i posrtanja", "W01.0"),
    W02("Pad prilikom klizanja, skijanja, koturanja ili vožnje na skateboardu", "W02"),
    W02_0("Pad prilikom klizanja, skijanja, koturanja ili vožnje na skateboardu", "W02.0"),
    W03("Drugi pad na istoj razini prilikom sudaranja ili guranja druge osobe", "W03"),
    W03_0("Drugi pad na istoj razini prilikom sudaranja ili guranja druge osobe", "W03.0"),
    W04("Pad za vrijeme nošenja ili pridržavanja od druge osobe", "W04"),
    W04_0("Pad za vrijeme nošenja ili pridržavanja od druge osobe", "W04.0"),
    W05("Pad iz invalidskih kolica", "W05"),
    W05_0("Pad iz invalidskih kolica", "W05.0"),
    W06("Pad s kreveta", "W06"),
    W06_0("Pad s kreveta", "W06.0"),
    W07("Pad sa stolice", "W07"),
    W07_0("Pad sa stolice", "W07.0"),
    W08("Pad s drugih dijelova pokućstva", "W08"),
    W08_0("Pad s drugih dijelova pokućstva", "W08.0"),
    W09("Pad s naprave za tjelovježbu", "W09"),
    W09_0("Pad s naprave za tjelovježbu", "W09.0"),
    W10("Pad na stubištu ili sa stubišta ili stuba", "W10"),
    W10_0("Pad na stubištu ili sa stubišta ili stuba", "W10.0"),
    W11("Pad na ljestve ili s njih", "W11"),
    W11_0("Pad na ljestve ili s njih", "W11.0"),
    W12("Pad na skelu ili s nje", "W12"),
    W12_0("Pad na skelu ili s nje", "W12.0"),
    W13("Pad s, iz ili kroz zgradu ili konstrukciju", "W13"),
    W13_0("Pad s, iz ili kroz zgradu ili konstrukciju", "W13.0"),
    W14("Pad sa stabla", "W14"),
    W14_0("Pad sa stabla", "W14.0"),
    W15("Pad sa stijene", "W15"),
    W15_0("Pad sa stijene", "W15.0"),
    W16("Ronjenje ili skakanje u vodu koje uzrokuje ozljedu, izuzevši utapanje ili potapanje", "W16"),
    W16_0("Ronjenje ili skakanje u vodu koje uzrokuje ozljedu, izuzevši utapnje ili potapanje", "W16.0"),
    W17("Drugi pad s jedne razine na drugu", "W17"),
    W17_0("Drugi pad s jedne razine na drugu", "W17.0"),
    W18("Drugi pad na istoj razini", "W18"),
    W18_0("Drugi pad na istoj razini", "W18.0"),
    W19("Nespecificirani pad", "W19"),
    W19_0("Nespecificirani pad", "W19.0"),
    W20("Pogođenost bačenim, ispaljenim ili padajućim predmetom", "W20"),
    W20_0("Pogođenost bačenim, ispaljenim ili padajućim predmetom", "W20.0"),
    W21("Sudaranje s predmetom iz športske opreme ili udaranje njime", "W21"),
    W21_0("Sudaranje s predmetom iz športske opreme ili udaranje njime", "W21.0"),
    W22("Sudaranje ili udaranje drugim predmetima", "W22"),
    W22_0("Sudaranje ili udaranje drugim predmetima", "W22.0"),
    W23("Zahvaćenost, gnječenje, stiskanje ili uklještenje predmetima ili između predmeta", "W23"),
    W23_0("Zahvaćenost, gnječenje, stiskanje ili uklještenje predmetima ili između predmeta", "W23.0"),
    W24("Doticaj s napravama za dizanje i prijenos, nesvrstanima drugamo", "W24"),
    W24_0("Doticaj s napravama za dizanje i prijenos, nesvrstanima drugamo", "W24.0"),
    W25("Doticaj s oštrim staklom", "W25"),
    W25_0("Doticaj s oštrim staklom", "W25.0"),
    W26("Doticaj s nožem, mačem ili bodežom", "W26"),
    W26_0("Doticaj s nožem, mačem ili bodežom", "W26.0"),
    W27("Doticaj s ručnim alatom bez motora", "W27"),
    W27_0("Doticaj s ručnim alatom bez motora", "W27.0"),
    W28("Doticaj s motornom kosilicom za travu", "W28"),
    W28_0("Doticaj s motornom kosilicom za travu", "W28.0"),
    W29("Doticaj s drugim motornim ručnim alatom ili električnim kućanskim aparatima", "W29"),
    W29_0("Doticaj s drugim motornim ručnim alatom ili električnim kućanskim aparatima", "W29.0"),
    W30("Doticaj s poljoprivrednim strojevima", "W30"),
    W30_0("Doticaj s poljoprivrednim strojevima", "W30.0"),
    W31("Doticaj s drugim i nespecificiranim strojevima", "W31"),
    W31_0("Doticaj s drugim i nespecificiranim strojevima", "W31.0"),
    W32("Pucnjava iz ručnog vatrenog oružja", "W32"),
    W32_0("Pucnjava iz ručnog vatrenog oružja", "W32.0"),
    W33("Pucnjava iz puške, sačmarice i teškoga vatrenog oružja", "W33"),
    W33_0("Pucnjava iz puške, sačmarice i teškoga vatrenog oružja", "W33.0"),
    W34("Pucnjava iz drugog i nespecificiranoga vatrenog oružja", "W34"),
    W34_0("Pucnjava iz drugog i nespecificiranoga vatrenog oružja", "W34.0"),
    W35("Eksplozija i prsnuće parnog kotla (bojlera)", "W35"),
    W35_0("Eksplozija i prsnuće parnog kotla (bojlera)", "W35.0"),
    W36("Eksplozija i prsnuće plinske boce", "W36"),
    W36_0("Eksplozija i prsnuće plinske boce", "W36.0"),
    W37("Eksplozija i prsnuće automobilske gume, cijevi ili crijeva za polijevanje", "W37"),
    W37_0("Eksplozija i prsnuće automobilske gume, cijevi ili crijeva za polijevanje", "W37.0"),
    W38("Eksplozija i prsnuće drugih specificiranih naprava pod tlakom", "W38"),
    W38_0("Eksplozija i prsnuće drugih specificiranih naprava pod tlakom", "W38.0"),
    W39("Ispaljivanje vatrometa", "W39.0"),
    W39_0("Ispaljivanje vatrometa", "W39.0"),
    W40("Eksplozija drugih sredstava", "W40"),
    W40_0("Eksplozija drugih sredstava", "W40.0"),
    W41("Izloženost djelovanju visokotlačnog mlaza", "W41"),
    W41_0("Izloženost djelovanju visokotlačnog mlaza", "W41.0"),
    W42("Izloženost buci", "W42"),
    W42_0("Izloženost buci", "W42.0"),
    W43("Izloženost vibracijama", "W43"),
    W43_0("Izloženost vibracijama", "W43.0"),
    W44("Doticaj sa stranim tijelom koje je prodrlo u ili kroz oko ili prirodni otvor", "W44"),
    W44_0("Doticaj sa stranim tijelom koje je prodrlo u ili kroz oko ili prirodni otvor", "W44.0"),
    W45("Doticaj sa stranim tijelom ili predmetom koje je prodrlo kroz kožu", "W45"),
    W45_0("Doticaj sa stranim tijelom ili predmetom koje je prodrlo kroz kožu", "W45.0"),
    W49("Izloženost drugim i nespecificiranim neživim mehaničkim silama", "W49"),
    W49_0("Izloženost drugim i nespecificiranim neživim mehaničkim silama", "W49.0"),
    W50("Udaranje, rušenje, udaranje nogom, savijanje, grizenje ili grebanje od druge osobe", "W50"),
    W50_0("Udaranje, rušenje, udaranje nogom, savijanje, grizenje ili grebanje od druge osobe", "W50.0"),
    W51("Udaranje ili nalijetanje na drugu osobu", "W51"),
    W51_0("Udaranje ili nalijetanje na drugu osobu", "W51.0"),
    W52("Gnječenje, guranje ili gaženje od mnoštva ili gomile ljudi u paničnome trku (human stampede)", "W52"),
    W52_0("Gnječenje, guranje ili gaženje od mnoštva ili gomile ljudi u paničnome trku (human stampede)", "W52.0"),
    W53("Ugriz štakora", "W53"),
    W53_0("Ugriz štakora", "W53.0"),
    W54("Ugriz ili udarac psa", "W54"),
    W54_0("Ugriz ili udarac psa", "W54.0"),
    W55("Ugriz ili udarac drugih sisavaca", "W55"),
    W55_0("Ugriz ili udarac drugih sisavaca", "W55.0"),
    W56("Doticaj s morskim sisavcima", "W56"),
    W56_0("Doticaj s morskim sisavcima", "W56.0"),
    W57("Ugriz ili ubod neotrovnog insekta ili drugih neotrovnih artropoda", "W57"),
    W57_0("Ugriz ili ubod neotrovnog insekta ili drugih neotrovnih artropoda", "W57.0"),
    W58("Ugriz ili udarac krokodila ili aligatora", "W58"),
    W58_0("Ugriz ili udarac krokodila ili aligatora", "W58.0"),
    W59("Ugriz ili zgnječenje od drugih reptila", "W59"),
    W59_0("Ugriz ili zgnječenje od drugih reptila", "W59.0"),
    W60("Doticaj s trnovitom biljkom, bodljikama i oštrim listovima", "W60"),
    W60_0("Doticaj s trnovitom biljkom, bodljikama i oštrim listovima", "W60.0"),
    W64("Izloženost drugim i nespecificiranim živim mehaničkim silama", "W64"),
    W64_0("Izloženost drugim i nespecificiranim živim mehaničkim silama", "W64.0"),
    W65("Utapanje ili potapanje u kadi za kupanje", "W65"),
    W65_0("Utapanje ili potapanje u kadi za kupanje", "W65.0"),
    W66("Utapanje ili potapanje nakon pada u kadu za kupanje", "W66"),
    W66_0("Utapanje ili potapanje nakon pada u kadu za kupanje", "W66.0"),
    W67("Utapanje ili potapanje u bazenu za plivanje", "W67"),
    W67_0("Utapanje ili potapanje u bazenu za plivanje", "W67.0"),
    W68("Utapanje ili potapanje nakon pada u bazen za plivanje", "W68"),
    W68_0("Utapanje ili potapanje nakon pada u bazen za plivanje", "W68.0"),
    W69("Utapanje ili potapanje u prirodnoj vodi", "W69"),
    W69_0("Utapanje ili potapanje u prirodnoj vodi", "W69.0"),
    W70("Utapanje ili potapanje nakon pada u prirodnu vodu", "W70"),
    W70_0("Utapanje ili potapanje nakon pada u prirodnu vodu", "W70.0"),
    W73("Drugo specificirano utapanje ili potapanje", "W73"),
    W73_0("Drugo specificirano utapanje ili potapanje", "W73.0"),
    W74("Nespecificirano utapanje ili potapanje", "W74"),
    W74_0("Nespecificirano utapanje ili potapanje", "W74.0"),
    W75("Slučajno gušenje i davljenje u krevetu", "W75"),
    W75_0("Slučajno gušenje i davljenje u krevetu", "W75.0"),
    W76("Drugo slučajno vješanje i davljenje", "W76"),
    W76_0("Drugo slučajno vješanje i davljenje", "W76.0"),
    W77("Ugroženost disanja zbog urušavanja, odrona zemlje i drugih tvari", "W77"),
    W77_0("Ugroženost disanja zbog urušavanja, odrona zemlje i drugih tvari", "W77.0"),
    W78("Inhalacija želučanog sadržaja", "W78"),
    W78_0("Inhalacija želučanog sadržaja", "W78.0"),
    W79("Inhalacija i ingestija hrane koja uzrokuje opstrukciju dišnog sustava", "W79"),
    W79_0("Inhalacija i ingestija hrane koja uzrokuje opstrukciju dišnog sustava", "W79.0"),
    W80("Inhalacija i ingestija drugih predmeta koja uzrokuje opstrukciju dišnog sustava", "W80"),
    W80_0("Inhalacija i ingestija drugih predmeta koja uzrokuje opstrukciju dišnog sustava", "W80.0"),
    W81("Osoba zatvorena ili uhvaćena u okolišu s niskom koncentracijom kisika", "W81"),
    W81_0("Osoba zatvorena ili uhvaćena u okolišu s niskom koncentracijom kisika", "W81.0"),
    W83("Ostali specificirani oblici ugrožavanja disanja", "W83"),
    W83_0("Ostali specificirani oblici ugrožavanja disanja", "W83.0"),
    W84("Nespecificirani oblik ugrožavanja disanja", "W84"),
    W84_0("Nespecificirani oblik ugrožavanja disanja", "W84.0"),
    W85("Izloženost električnim prijenosnim vodovima", "W85"),
    W85_0("Izloženost električnim prijenosnim vodovima", "W85.0"),
    W86("Izloženost drugoj specificiranoj električnoj struji", "W86"),
    W86_0("Izloženost drugoj specificiranoj električnoj struji", "W86.0"),
    W87("Izloženost nespecificiranoj električnoj struji", "W87"),
    W87_0("Izloženost nespecificiranoj električnoj struji", "W87.0"),
    W88("Izloženost ionizirajućem zračenju", "W88"),
    W88_0("Izloženost ionizirajućem zračenju", "W88.0"),
    W89("Izloženost umjetno nastaloj i ultraljubičastoj svjetlosti", "W89"),
    W89_0("Izloženost umjetno nastaloj i ultraljubičastoj svjetlosti", "W89.0"),
    W90("Izloženost drugom neionizirajućem zračenju", "W90"),
    W90_0("Izloženost drugom neionizirajućem zračenju", "W90.0"),
    W91("Izloženost nespecificiranoj vrsti zračenja", "W91"),
    W91_0("Izloženost nespecificiranoj vrsti zračenja", "W91.0"),
    W92("Izloženost prekomjernoj toplini umjetnog podrijetla", "W92"),
    W92_0("Izloženost prekomjernoj toplini umjetnog podrijetla", "W92.0"),
    W93("Izloženost prekomjernoj hladnoći umjetnog podrijetla", "W93"),
    W93_0("Izloženost prekomjernoj hladnoći umjetnog podrijetla", "W93.0"),
    W94("Izloženost visokom ili niskom tlaku zraka i promjenama u tlaku zraka", "W94"),
    W94_0("Izloženost visokom ili niskom tlaku zraka i promjenama u tlaku zraka", "W94.0"),
    W99("Izloženost drugim i nespecificiranim umjetnim čimbenicima okoliša", "W99"),
    W99_0("Izloženost drugim i nespecificiranim umjetnim čimbenicima okoliša", "W99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesW(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
