package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesX {
    
    X00("Izloženost nekontroliranoj vatri u zgradi ili konstrukciji", "X00"),
    X00_0("Izloženost nekontroliranoj vatri u zgradi ili konstrukciji", "X00.0"),
    X01("Izloženost nekontroliranoj vatri izvan zgrade ili konstrukcije", "X01"),
    X01_0("Izloženost nekontroliranoj vatri izvan zgrade ili konstrukcije", "X01.0"),
    X02("Izloženost vatri pod kontrolom u zgradi ili konstrukciji", "X02"),
    X02_0("Izloženost vatri pod kontrolom u zgradi ili konstrukciji", "X02.0"),
    X03("Izloženost vatri pod kontrolom izvan zgrade ili konstrukcije", "X03"),
    X03_0("Izloženost vatri pod kontrolom izvan zgrade ili konstrukcije", "X03.0"),
    X04("Izloženost zapaljenim lako zapaljivim materijalima", "X04"),
    X04_0("Izloženost zapaljenim lako zapaljivim materijalima", "X04.0"),
    X05("Izloženost zapaljenoj ili rastaljenoj noćnoj odjeći", "X05"),
    X05_0("Izloženost zapaljenoj ili rastaljenoj noćnoj odjeći", "X05.0"),
    X06("Izloženost zapaljenoj ili rastaljenoj drugoj odjeći i opremi (ukrasima, nakitu)", "X06"),
    X06_0("Izloženost zapaljenoj ili rastaljenoj drugoj odjeći i opremi (ukrasima, nakitu)", "X06.0"),
    X08("Izloženost drugom specificiranom dimu, vatri i plamenu", "X08"),
    X08_0("Izloženost drugom specificiranom dimu, vatri i plamenu", "X08.0"),
    X09("Izloženost nespecificiranom dimu, vatri i plamenu", "X09"),
    X09_0("Izloženost nespecificiranom dimu, vatri i plamenu", "X09.0"),
    X10("Doticaj s vrućim pićima, hranom, masti i jestivim uljem", "X10"),
    X10_0("Doticaj s vrućim pićima, hranom, masti i jestivim uljem", "X10.0"),
    X11("Doticaj s vrućom vodom iz slavine", "X11"),
    X11_0("Doticaj s vrućom vodom iz slavine", "X11.0"),
    X12("Doticaj s drugim vrućim tekućinama", "X12"),
    X12_0("Doticaj s drugim vrućim tekućinama", "X12.0"),
    X13("Doticaj s parom i vrućim isparinama", "X13"),
    X13_0("Doticaj s parom i vrućim isparinama", "X13.0"),
    X14("Doticaj s vrućim zrakom i plinovima", "X14"),
    X14_0("Doticaj s vrućim zrakom i plinovima", "X14.0"),
    X15("Doticaj s vrućim kućanskim aparatima", "X15"),
    X15_0("Doticaj s vrućim kućanskim aparatima", "X15.0"),
    X16("Doticaj s uređajima za grijanje, radijatorima i cijevima", "X16"),
    X16_0("Doticaj s uređajima za grijanje, radijatorima i cijevima", "X16.0"),
    X17("Doticaj s vrućim oruđima, strojevima i alatima", "X17"),
    X17_0("Doticaj s vrućim oruđima, strojevima i alatima", "X17.0"),
    X18("Doticaj s drugim vrućim kovinama", "X18"),
    X18_0("Doticaj s drugim vrućim kovinama", "X18.0"),
    X19("Doticaj s drugim i nespecificiranim izvorom topline i vrućim tvarima", "X19"),
    X19_0("Doticaj s drugim i nespecificiranim izvorom topline i vrućim tvarima", "X19.0"),
    X20("Doticaj s otrovnim zmijama i gušterima", "X20"),
    X20_0("Doticaj s otrovnim zmijama i gušterima", "X20.0"),
    X21("Doticaj s otrovnim paucima", "X21"),
    X21_0("Doticaj s otrovnim paucima", "X21.0"),
    X22("Doticaj sa škorpionima", "X22"),
    X22_0("Doticaj sa škorpionima", "X22.0"),
    X23("Doticaj sa stršljenima, osama i pčelama", "X23"),
    X23_0("Doticaj sa stršljevima, osama i pčelama", "X23.0"),
    X24("Doticaj sa stonogama i otrovnim milipodima (tropskim)", "X24"),
    X24_0("Doticaj sa stonogama i otrovnim milipodima (tropskim)", "X24.0"),
    X25("Doticaj s drugim specificiranim otrovnim artropodima", "X25"),
    X25_0("Doticaj s drugim specificiranim otrovnim artropodima", "X25.0"),
    X26("Doticaj s otrovnim morskim životinjama i biljkama", "X26"),
    X26_0("Doticaj s otrovnim morskim životinjama i biljkama", "X26.0"),
    X27("Doticaj s drugim specificiranim otrovnim životinjama", "X27"),
    X27_0("Doticaj s drugim specificiranim otrovnim životinjama", "X27.0"),
    X28("Doticaj s drugim specificiranim otrovnim biljkama", "X28"),
    X28_0("Doticaj s drugim specificiranim otrovnim biljkama", "X28.0"),
    X29("Doticaj s nespecificiranom otrovnom životinjom ili biljkom", "X29"),
    X29_0("Doticaj s nespecificiranom otrovnom životinjom ili biljkom", "X29.0"),
    X30("Izloženost prekomjernoj prirodnoj toplini", "X30"),
    X30_0("Izloženost prekomjernoj prirodnoj toplini", "X30.0"),
    X31("Izloženost prekomjernoj prirodnoj hladnoći", "X31"),
    X31_0("Izloženost prekomjernoj prirodnoj hladnoći", "X31.0"),
    X32("Izloženost sunčevu svjetlu", "X32"),
    X32_0("Izloženost sunčevu svjetlu", "X32.0"),
    X33("Žrtva udara groma", "X33"),
    X33_0("Žrtva udara groma", "X33.0"),
    X34("Žrtva potresa", "X34"),
    X34_0("Žrtva potresa", "X34.0"),
    X35("Žrtva vulkanske erupcije", "X35"),
    X35_0("Žrtva vulkanske erupcije", "X35.0"),
    X36("Žrtva lavine, odrona i drugih pokretanja zemlje", "X36"),
    X36_0("Žrtva lavine, odrona i drugih pokretanja zemlje", "X36.0"),
    X37("Žrtva katastrofalnog nevremena (oluje)", "X37"),
    X37_0("Žrtva katastrofalnog nevremena (oluje)", "X37.0"),
    X38("Žrtva poplave", "X38"),
    X38_0("Žrtva poplave", "X38.0"),
    X39("Izloženost drugim i nespecificiranim prirodnim silama", "X39"),
    X39_0("Izloženost drugim i nespecificiranim prirodnim silama", "X39.0"),
    X40("Slučajno otrovanje i izlaganje neopioidnim anlgeticima, antipireticima ili antireumaticima", "X40"),
    X40_0("Slučajno otrovanje i izlaganje neopioidnim analgeticima, antipireticima ili aniteumaticima", "X40.0"),
    X41("Slučajno otrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima nesvrstanim drugamo", "X41"),
    X41_0("Slučajno otrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima nesvrstanim drugamo", "X41.0"),
    X42("Slučajno otrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo", "X42"),
    X42_0("Slučajno otrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo", "X42.0"),
    X43("Slučajno otrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav", "X43"),
    X43_0("Slučajno otrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav", "X43.0"),
    X44("Slučajno otrovanje i izlaganje nespecificiranim lijekovima, ljekovitim i biološkim tvarima", "X44"),
    X44_0("Slučajno otrovanje i izlaganje nespecificiranim lijekovima, ljekovitim i biološkim tvarima", "X44.0"),
    X45("Slučajno otrovanje i izlaganje alkoholu", "X45"),
    X45_0("Slučajno otrovanje i izlaganje alkoholu", "X45.0"),
    X46("Slučajno otrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama", "X46"),
    X46_0("Slučajno otrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama", "X46.0"),
    X47("Slučajno otrovanje i izlaganje drugim plinovima i parama", "X47"),
    X47_0("Slučajno otrovanje i izlaganje drugim plinovima i parama", "X47.0"),
    X48("Slučajno otrovanje i izlaganje pesticidima", "X48"),
    X48_0("Slučajno otrovanje i izlaganje pesticidima", "X48.0"),
    X49("Slučajno otrovanje i izlaganje drugim i nespecificiranim kemikalijama i štetnim tvarima", "X49"),
    X49_0("Slučajno otrovanje i izlaganje drugim i nespecificiranim kemikalijama i štetnim tvarima", "X49.0"),
    X50("Prenaprezanje i naporni ili ponovljani pokreti", "X50"),
    X50_0("Prenaprezanje i naporni ili ponovljani pokreti", "X50.0"),
    X51("Putovanje i kretanje", "X51"),
    X51_0("Putovanje i kretanje", "X51.0"),
    X52("Produžen boravak u bestežinskom okolišu", "X52"),
    X52_0("Produžen boravak u bestežinskom okolišu", "X52.0"),
    X53("Nedostatak hrane", "X53"),
    X53_0("Nedostatak hrane", "X53.0"),
    X54("Nedostatak vode", "X54"),
    X54_0("Nedostatak vode", "X54.0"),
    X57("Nespecificirana oskudica", "X57"),
    X57_0("Nespecificirana oskudica", "X57.0"),
    X58("Izloženost drugim specificiranim čimbenicima", "X58"),
    X58_0("Izloženost drugim specificiranim čimbenicima", "X58.0"),
    X59("Izloženost nespecificiranom čimbeniku", "X59"),
    X59_0("Izloženost nespecificiranom čimbeniku", "X59.0"),
    X60("Namjerno samootrovanje i izlaganje neopioidnim analgeticima, antipireticima i antireumaticima", "X60"),
    X60_0("Namjerno samootrovanje i izlaganje neopioidnim analgeticima, antipireticima i antireumaticima", "X60.0"),
    X61("Namjerno samootrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima, nesvrstanim drugamo", "X61"),
    X61_0("Namjerno samootrovanje i izlaganje antiepilepticima, sedativima-hipnoticima, antiparkinsonicima i psihotropnim lijekovima, nesvrstanim drugamo", "X61.0"),
    X62("Namjerno samootrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo", "X62"),
    X62_0("Namjerno samootrovanje i izlaganje narkoticima i psihodislepticima (halucinogenima), nesvrstanim drugamo", "X62.0"),
    X63("Namjerno samootrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav", "X63"),
    X63_0("Namjerno samootrovanje i izlaganje drugim lijekovima koji djeluju na autonomni živčani sustav", "X63.0"),
    X64("Namjerno samootrovanje i izlaganje drugim i nespecificiranim lijekovima, ljekovitim i biološkim tvarima", "X64"),
    X64_0("Namjerno samootrovanje i izlaganje drugim i nespecificiranim lijekovima, ljekovitim i biološkim tvarima", "X64.0"),
    X65("Namjerno samootrovanje i izlaganje alkoholu", "X65"),
    X65_0("Namjerno samootrovanje i izlaganje alkoholu", "X65.0"),
    X66("Namjerno samootrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama", "X66"),
    X66_0("Namjerno samootrovanje i izlaganje organskim otapalima i halogeniranim ugljikovodicima i njihovim parama", "X66.0"),
    X67("Namjerno samootrovanje i izlaganje drugim plinovima i parama", "X67"),
    X67_0("Namjerno samootrovanje i izlaganje drugim plinovima i parama", "X67.0"),
    X68("Namjerno samootrovanje i izlaganje pesticidima", "X68"),
    X68_0("Namjerno samootrovanje i izlaganje pesticidima", "X68.0"),
    X69("Namjerno samootrovanje i izlaganje drugim i nespecificiranim kemikalijama i štetnim tvarima", "X69"),
    X69_0("Namjerno samootrovanje i izlaganje drugim i nespecificiranim kemikalijama i štetnim tvarima", "X69.0"),
    X70("Namjerno samoozljeđivanje vješanjem, davljenjem i ugušenjem", "X70"),
    X70_0("Namjerno samoozljeđivanje vješanjem, davljenjem i ugušenjem", "X70.0"),
    X71("Namjerno samoozljeđivanje utapanjem i potapanjem", "X71"),
    X71_0("Namjerno samoozljeđivanje utapanjem i potapanjem", "X71.0"),
    X72("Namjerno samoozljeđivanje hicem iz pištolja", "X72"),
    X72_0("Namjerno samoozljeđivanje hicem iz pištolja", "X72.0"),
    X73("Namjerno samoozljeđivanje hicem iz puške, sačmarice i većeg vatrenog oružja (većeg kalibra)", "X73"),
    X73_0("Namjerno samoozljeđivanje hicem iz puške, sačmarice i većeg vatrenog oružja (većeg kalibra)", "X73.0"),
    X74("Namjerno samoozljeđivanje hicem iz drugoga i nespecificiranoga vatrenog oružja", "X74"),
    X74_0("Namjerno samoozljeđivanje hicem iz drugoga i nespecificiranoga vatrenog oružja", "X74.0"),
    X75("Namjerno samoozljeđivanje eksplozivnim materijalom", "X75"),
    X75_0("Namjerno samoozljeđivanje eksplozivnim materijalom", "X75.0"),
    X76("Namjerno samoozljeđivanje dimom, vatrom i plamenom (žeravicom)", "X76"),
    X76_0("Namjerno samoozljeđivanje dimom, vatrom i plamenom (žeravicom)", "X76.0"),
    X77("Namjerno samoozljeđivanje parom, vrućim isparinama i vrućim predmetima", "X77"),
    X77_0("Namjerno samoozljeđivanje parom, vrućim isparinama i vrućim predmetima", "X77.0"),
    X78("Namjerno samoozljeđivanje oštrim predmetom", "X78"),
    X78_0("Namjerno samoozljeđivanje oštrim predmetom", "X78.0"),
    X79("Namjerno samoozljeđivanje tupim predmetom", "X79"),
    X79_0("Namjerno samoozljeđivanje tupim predmetom", "X79.0"),
    X80("Namjerno samoozljeđivanje skokom s visokog mjesta (visine)", "X80"),
    X80_0("Namjerno samoozljeđivanje skokom s visokog mjesta (visine)", "X80.0"),
    X81("Namjerno samoozljeđivanje skokom pred objekt u pokretu ili lijeganjem pred njega", "X81"),
    X81_0("Namjerno samoozljeđivanje skokom pred objekt u pokretu ili lijeganjem pred njega", "X81.0"),
    X82("Namjerno samoozljeđivanje razbijanjem motornog vozila", "X82"),
    X82_0("Namjerno samoozljeđivanje razbijanjem motornog vozila", "X82.0"),
    X83("Namjerno samoozljeđivanje na drugi specificirani način", "X83"),
    X83_0("Namjerno samoozljeđivanje na drugi specificirani način", "X83.0"),
    X84("Namjerno samoozljeđivanje na nespecificiran način", "X84"),
    X84_0("Namjerno samoozljeđivanje na nespecificiran način", "X84.0"),
    X85("Napad pomoću lijekova, ljekovitih i bioloških tvari", "X85"),
    X85_0("Napad pomoću lijekova, ljekovitih i bioloških tvari", "X85.0"),
    X86("Napad korozivnom tvari", "X86"),
    X86_0("Napad korozivnom tvari", "X86.0"),
    X87("Napad pesticidima", "X87"),
    X87_0("Napad pesticidima", "X87.0"),
    X88("Napad plinovima i isparinama", "X88"),
    X88_0("Napad plinovima i isparinama", "X88.0"),
    X89("Napad drugim specificiranim kemikalijama i štetnim tvarima", "X89"),
    X89_0("Napad drugim specificiranim kemikalijama i štetnim tvarima", "X89.0"),
    X90("Napad nespecificiranim kemikalijama ili štetnim tvarima", "X90"),
    X90_0("Napad nespecificiranim kemikalijama ili štetnim tvarima", "X90.0"),
    X91("Napad vješanjem, davljenjem i gušenjem", "X91"),
    X91_0("Napad vješanjem, davljenjem i gušenjem", "X91.0"),
    X92("Napad utapanjem i potapanjem", "X92"),
    X92_0("Napad utapanjem i potapanjem", "X92.0"),
    X93("Napad hicem iz pištolja", "X93"),
    X93_0("Napad hicem iz pištolja", "X93.0"),
    X94("Napad hicem iz puške, sačmarice i većeg vatrenog oružja (većeg kalibra)", "X94"),
    X94_0("Napad hicem iz puške, sačmarice i većeg vatrenog oružja (većeg kalibra)", "X94.0"),
    X95("Napad hicem iz drugog i nespecificiranog vatrenog oružja", "X95"),
    X95_0("Napad hicem iz drugog i nespecificiranog vatrenog oružja", "X95.0"),
    X96("Napad eksplozivnim materijalom", "X96"),
    X96_0("Napad eksplozivnim materijalom", "X96.0"),
    X97("Napad dimom, vatrom i plamenom", "X97"),
    X97_0("Napad dimom, vatrom i plamenom", "X97.0"),
    X98("Napad parom, vrućim isparinama i vrućim predmetima", "X98"),
    X98_0("Napad parom, vrućim isparinama i vrućim predmetima", "X98.0"),
    X99("Napad oštrim predmetom", "X99"),
    X99_0("Napad oštrim predmetom", "X99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesX(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
