package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesT {
    
    T00("Površinske ozljede koje zahvaćaju više dijelova tijela", "T00"),
    T00_0("Površinske ozljede koje zahvaćaju glavu s vratom", "T00.0"),
    T00_1("Površinske ozljede koje zahvaćaju toraks s abdomenom, donjim dijelom leđa i zdjelicom", "T00.1"),
    T00_2("Površinske ozljede koje zahvaćaju više dijelova ruke(u)", "T00.2"),
    T00_3("Površinske ozljede koje zahvaćaju više dijelova noge(u)", "T00.3"),
    T00_6("Površinske ozljede koje zahvaćaju više dijelova ruke(u) s nogom(ama)", "T00.6"),
    T00_8("Površinske ozljede koje zahvaćaju druge kombinacije dijelova tijela", "T00.8"),
    T00_9("Višestruke površinske ozljede, nespecificirane", "T00.9"),
    T01("Otvorene rane više dijelova tijela", "T01"),
    T01_0("Otvorene rane koje zahvaćaju glavu s vratom", "T01.0"),
    T01_1("Otvorene rane koje zahvaćaju toraks s abdomenom, donji dio leđa i zdjelicu", "T01.1"),
    T01_2("Otvorene rane koje zahvaćaju više dijelova ruke(u)", "T01.2"),
    T01_3("Otvorene rane koje zahvaćaju više dijelova noge(u)", "T01.3"),
    T01_6("Otvorene rane koje zahvaćaju više dijelova ruke(u) s nogom(ama)", "T01.6"),
    T01_8("Otvorene rane koje zahvaćaju druge kombinacije dijelova tijela", "T01.8"),
    T01_9("Višestruke otvorene rane, nespecificirane", "T01.9"),
    T02("Prijelomi koji zahvaćaju više dijelova tijela", "T02"),
    T02_0("Prijelomi glave s vratom", "T02.0"),
    T02_1("Prijelomi koji zahvaćaju toraks s donjim dijelom leđa i zdjelicom", "T02.1"),
    T02_2("Prijelomi više dijelova jedne ruke", "T02.2"),
    T02_3("Prijelomi više dijelova jedne noge", "T02.3"),
    T02_4("Prijelomi više dijelova obiju ruku", "T02.4"),
    T02_5("Prijelomi više dijelova obiju nogu", "T02.5"),
    T02_6("Prijelomi više dijelova ruke(u) s nogom(ama)", "T02.6"),
    T02_7("Prijelomi koji zahvaćaju toraks s donjim dijelom leđa i zdjelicu s udom(vima)", "T02.7"),
    T02_8("Prijelomi koji zahvaćaju druge kombinacije dijelova tijela", "T02.8"),
    T02_9("Višestruki prijelomi, nespecificirani", "T02.9"),
    T03("Dislokacije, iščašenja i nategnuća koja zahvaćaju više dijelova tijela", "T03"),
    T03_0("Dislokacije, iščašenja i nategnuća koja zahvaćaju glavu s vratom", "T03.0"),
    T03_1("Dislokacije, iščašenja i nategnuća toraksa s donjim dijelom leđa i zdjelicom", "T03.1"),
    T03_2("Dislokacije, iščašenja i nategnuća više dijelova ruke(u)", "T03.2"),
    T03_3("Dislokacije, iščašenja i nategnuća više dijelova noge(u)", "T03.3"),
    T03_4("Dislokacije, iščašenja i nategnuća više dijelova ruke(u) s nogom(ama)", "T03.4"),
    T03_8("Dislokacije, iščašenja i nategnuća koja zahvaćaju druge kombinacije dijelova tijela", "T03.8"),
    T03_9("Višestruke dislokacije, iščašenja i nategnuća, nespecificirana", "T03.9"),
    T04("Zgnječenja (crush ozljede) više dijelova tijela", "T04"),
    T04_0("Zgnječenja glave s vratom", "T04.0"),
    T04_1("Zgnječenja toraksa s abdomenom, donjim dijelom leđa i zdjelicom", "T04.1"),
    T04_2("Zgnječenja više dijelova ruke(u)", "T04.2"),
    T04_3("Zgnječenja više dijelova noge(u)", "T04.3"),
    T04_4("Zgnječenja više dijelova ruke(u) s nogom(ama)", "T04.4"),
    T04_7("Zgnječenja toraksa s abdomenom, donjim dijelom leđa i zdjelicom s udom(vima)", "T04.7"),
    T04_8("Zgnječenja koja zahvaćaju druge kombinacije dijelova tijela", "T04.8"),
    T04_9("Višestruka zgnječenja, nespecificirana", "T04.9"),
    T05("Traumatske amputacije koje zahvaćaju više dijelova tijela", "T05"),
    T05_0("Traumatska amputacija obiju šaka", "T05.0"),
    T05_1("Traumatska amputacija jedne šake i druge ruke (na bilo kojoj razini, osim šake)", "T05.1"),
    T05_2("Traumatska amputacija obiju ruku (na bilo kojoj razini)", "T05.2"),
    T05_3("Traumatska amputacija obaju stopala", "T05.3"),
    T05_4("Traumatska amputacija jednog stopala i druge noge (na bilo kojoj razini, osim stopala)", "T05.4"),
    T05_5("Traumatska amputacija obiju nogu (na bilo kojoj razini)", "T05.5"),
    T05_6("Traumatska amputacija ruku i nogu, bilo koja kombinacija (na bilo kojoj razini)", "T05.6"),
    T05_8("Traumatske amputacije koje zahvaćaju kombinacije drugih dijelova tijela", "T05.8"),
    T05_9("Višestruke traumatske amputacije, nespecificirane", "T05.9"),
    T06("Ostale ozljede koje zahvaćaju više dijelova tijela, nesvrstane drugamo", "T06"),
    T06_0("Ozljede mozga i moždanih živaca s ozljedama živaca i kralježnične moždine u razini vrata", "T06.0"),
    T06_1("Ozljede živaca i kralježnične moždine koje zahvaćaju više dijelova tijela", "T06.1"),
    T06_2("Ozljede živaca koje zahvaćaju više dijelova tijela", "T06.2"),
    T06_3("Ozljede krvnih žila koje zahvaćaju više dijelova tijela", "T06.3"),
    T06_4("Ozljede mišića i tetiva koje zahvaćaju više dijelova tijela", "T06.4"),
    T06_5("Ozljede intratorakalnih s intraabdominalnim i zdjeličnim organima", "T06.5"),
    T06_8("Ostale specificirane ozljede koje zahvaćaju više dijelova tijela (politrauma)", "T06.8"),
    T07("Nespecificirane višestruke ozljede", "T07"),
    T07_0("Nespecificirane višestruke ozljede", "T07.0"),
    T08("Prijelom kralježnice, nespecificiranog mjesta", "T08"),
    T08_0("Prijelom kralježnice, nespecificiranog mjesta", "T08.0"),
    T09("Ostale ozljede kralježnice i trupa, nespecificiranog mjesta", "T09"),
    T09_0("Površinska ozljeda trupa, nespecificiranog mjesta", "T09.0"),
    T09_1("Otvorena rana trupa, nespecificiranog mjesta", "T09.1"),
    T09_2("Dislokacija, iščašenje i nategnuće nespecificiranog zgloba i ligamenta trupa", "T09.2"),
    T09_3("Ozljeda kralježnične moždine, nespecificirane razine", "T09.3"),
    T09_4("Ozljeda nespecificiranog živca, korijena kralježničnog živca i pleksusa trupa", "T09.4"),
    T09_5("Ozljeda nespecificiranog mišića i tetive trupa", "T09.5"),
    T09_6("Traumatska amputacija trupa, nespecificirane razine", "T09.6"),
    T09_8("Ostale specificirane ozljede trupa, nespecificiranog mjesta", "T09.8"),
    T09_9("Nespecificirana ozljeda trupa, nespecificiranog mjesta", "T09.9"),
    T10("Prijelom ruke, nespecificiranog mjesta", "T10"),
    T10_0("Prijelom ruke, nespecificiranog mjesta", "T10.0"),
    T11("Ostale ozljede ruke, nespecificiranog mjesta", "T11"),
    T11_0("Površinska ozljeda ruke, nespecificiranog mjesta", "T11.0"),
    T11_1("Otvorena rana ruke, nespecificiranog mjesta", "T11.1"),
    T11_2("Dislokacija, iščašenje i nategnuće nespecificiranog zgloba i ligamenta ruke, nespecificiranog mjesta", "T11.2"),
    T11_3("Ozljeda nespecificiranog živca ruke, nespecificiranog mjesta", "T11.3"),
    T11_4("Ozljeda nespecificirane krvne žile ruke, nespecificiranog mjesta", "T11.4"),
    T11_5("Ozljeda nespecificiranog mišića i tetive ruke, nespecificiranog mjesta", "T11.5"),
    T11_6("Traumatska amputacija ruke, nespecificirane razine", "T11.6"),
    T11_8("Ostale označene ozljede ruke, nespecificiranog mjesta", "T11.8"),
    T11_9("Nespecificirana ozljeda ruke, nespecificiranog mjesta", "T11.9"),
    T12("Prijelom noge, nespecificiranog mjesta", "T12"),
    T12_0("Prijelom noge, nespecificiranog mjesta", "T12.0"),
    T13("Ostale ozljede noge, nespecificiranog mjesta", "T13"),
    T13_0("Površinska ozljeda noge, nespecificiranog mjesta", "T13.0"),
    T13_1("Otvorena rana noge, nespecificiranog mjesta", "T13.1"),
    T13_2("Dislokacija, iščašenje i nategnuće nespecificiranog zgloba i ligamenta noge, nespecificiranog mjesta", "T13.2"),
    T13_3("Ozljeda nespecificiranog živca noge, nespecificiranog mjesta", "T13.3"),
    T13_4("Ozljeda nespecificirane krvne žile noge, nespecificiranog mjesta", "T13.4"),
    T13_5("Ozljeda nespecificiranog mišića i tetive noge, nespecificiranog mjesta", "T13.5"),
    T13_6("Traumatska amputacija noge, nespecificirane razine", "T13.6"),
    T13_8("Ostale označene ozljede noge, nespecificiranog mjesta", "T13.8"),
    T13_9("Nespecificirana ozljeda noge, nespecificiranog mjesta", "T13.9"),
    T14("Ozljeda nespecificiranog dijela tijela", "T14"),
    T14_0("Površinska ozljeda nespecificiranog dijela tijela", "T14.0"),
    T14_1("Otvorena rana nespecificiranog dijela tijela", "T14.1"),
    T14_2("Prijelom nespecificiranog dijela tijela", "T14.2"),
    T14_3("Dislokacija, iščašenje i nategnuće nespecificiranog dijela tijela", "T14.3"),
    T14_4("Ozljeda živca(aca) nespecificiranog dijela tijela", "T14.4"),
    T14_5("Ozljeda krvne(ih) žile(a) nespecificiranog dijela tijela", "T14.5"),
    T14_6("Ozljeda tetiva i mišića nespecificiranog dijela tijela", "T14.6"),
    T14_7("Zgnječenje i traumatska amputacija nespecificiranog dijela tijela", "T14.7"),
    T14_8("Ostale ozljede nespecificiranog dijela tijela", "T14.8"),
    T14_9("Ozljeda, nespecificirana", "T14.9"),
    T15("Strano tijelo u vanjskom dijelu oka", "T15"),
    T15_0("Strano tijelo u rožnici (korneji)", "T15.0"),
    T15_1("Strano tijelo u konjunktivalnoj vrećici", "T15.1"),
    T15_8("Strano tijelo u više drugih dijelova vanjskog oka", "T15.8"),
    T15_9("Strano tijelo u vanjskom dijelu oka, nespecificiranog dijela", "T15.9"),
    T16("Strano tijelo u uhu", "T16"),
    T16_0("Strano tijelo u uhu", "T16.0"),
    T17("Strano tijelo u dišnom sustavu", "T17"),
    T17_0("Strano tijelo u nosnom sinusu", "T17.0"),
    T17_1("Strano tijelo u nosnici", "T17.1"),
    T17_2("Strano tijelo u ždrijelu (farinksu)", "T17.2"),
    T17_3("Strano tijelo u grkljanu (larinksu)", "T17.3"),
    T17_4("Strano tijelo u dušniku (traheji)", "T17.4"),
    T17_5("Strano tijelo u bronhu", "T17.5"),
    T17_8("Strano tijelo u drugim i više dijelova dišnog sustava", "T17.8"),
    T17_9("Strano tijelo u dišnom sustavu, nespecificiranog dijela", "T17.9"),
    T18("Strano tijelo u probavnom sustavu", "T18"),
    T18_0("Strano tijelo u ustima", "T18.0"),
    T18_1("Strano tijelo u jednjaku (ezofagusu)", "T18.1"),
    T18_2("Strano tijelo u želucu", "T18.2"),
    T18_3("Strano tijelo u tankome crijevu", "T18.3"),
    T18_4("Strano tijelo u kolonu", "T18.4"),
    T18_5("Strano tijelo u anusu i rektumu", "T18.5"),
    T18_8("Strano tijelo u drugim i više dijelova probavnog sustava", "T18.8"),
    T18_9("Strano tijelo u probavnom sustavu, nespecificiranog dijela", "T18.9"),
    T19("Strano tijelo u genitourinarnom sustavu", "T19"),
    T19_0("Strano tijelo u mokraćnoj cijevi (uretri)", "T19.0"),
    T19_1("Strano tijelo u mokraćnom mjehuru (vezici urinariji)", "T19.1"),
    T19_2("Strano tijelo u stidnici i rodnici (vulvi i vagini)", "T19.2"),
    T19_3("Strano tijelo u maternici (uterusu) (bilo kojem dijelu)", "T19.3"),
    T19_8("Strano tijelo u više drugih dijelova genitourinarnog sustava", "T19.8"),
    T19_9("Strano tijelo u genitourinarnom sustavu, nespecificiranog dijela", "T19.9"),
    T20("Opeklina i korozija glave i vrata", "T20"),
    T20_0("Opeklina glave i vrata nespecificirana stupnja", "T20.0"),
    T20_1("Opeklina glave i vrata prvoga stupnja", "T20.1"),
    T20_2("Opeklina glave i vrata drugoga stupnja", "T20.2"),
    T20_3("Opeklina glave i vrata trećega stupnja", "T20.3"),
    T20_4("Korozija glave i vrata nespecificiranog stupnja", "T20.4"),
    T20_5("Korozija glave i vrata prvoga stupnja", "T20.5"),
    T20_6("Korozija glave i vrata drugoga stupnja", "T20.6"),
    T20_7("Korozija glave i vrata trećega stupnja", "T20.7"),
    T21("Opeklina i korozija trupa", "T21"),
    T21_0("Opeklina trupa nespecificirana stupnja", "T21.0"),
    T21_1("Opeklina trupa prvoga stupnja", "T21.1"),
    T21_2("Opeklina trupa drugoga stupnja", "T21.2"),
    T21_3("Opeklina trupa trećega stupnja", "T21.3"),
    T21_4("Korozija trupa nespecificirana stupnja", "T21.4"),
    T21_5("Korozija trupa prvoga stupnja", "T21.5"),
    T21_6("Korozija trupa drugoga stupnja", "T21.6"),
    T21_7("Korozija trupa trećega stupnja", "T21.7"),
    T22("Opeklina i korozija ramena i ruke, osim zapešća i šake", "T22"),
    T22_0("Opeklina nespecificirana stupnja ramena i ruke, osim zapešća i šake", "T22.0"),
    T22_1("Opeklina prvoga stupnja ramena i ruke, osim zapešća i šake", "T22.1"),
    T22_2("Opeklina drugoga stupnja ramena i ruke, osim zapešća i šake", "T22.2"),
    T22_3("Opeklina trećega stupnja ramena i ruke, osim zapešća i šake", "T22.3"),
    T22_4("Korozija nespecificirana stupnja ramena i ruke, osim zapešća i šake", "T22.4"),
    T22_5("Korozija prvoga stupnja ramena i ruke, osim zapešća i šake", "T22.5"),
    T22_6("Korozija drugoga stupnja ramena i ruke, osim zapešća i šake", "T22.6"),
    T22_7("Korozija trećega stupnja ramena i ruke, osim zapešća i šake", "T22.7"),
    T23("Opeklina i korozija zapešća i šake", "T23"),
    T23_0("Opeklina nespecificirana stupnja zapešća i šake", "T23.0"),
    T23_1("Opeklina prvoga stupnja zapešća i šake", "T23.1"),
    T23_2("Opeklina drugoga stupnja zapešća i šake", "T23.2"),
    T23_3("Opeklina trećega stupnja zapešća i šake", "T23.3"),
    T23_4("Korozija nespecificirana stupnja zapešća i šake", "T23.4"),
    T23_5("Korozija prvoga stupnja zapešća i šake", "T23.5"),
    T23_6("Korozija drugoga stupnja zapešća i šake", "T23.6"),
    T23_7("Korozija trećega stupnja zapešća i šake", "T23.7"),
    T24("Opeklina i korozija kuka i noge, osim gležnja i stopala", "T24"),
    T24_0("Opeklina nespecificirana stupnja kuka i noge, osim gležnja i stopala", "T24.0"),
    T24_1("Opeklina prvoga stupnja kuka i noge, osim gležnja i stopala", "T24.1"),
    T24_2("Opeklina drugoga stupnja kuka i noge, osim gležnja i stopala", "T24.2"),
    T24_3("Opeklina trećega stupnja kuka i noge, osim gležnja i stopala", "T24.3"),
    T24_4("Korozija nespecificirana stupnja kuka i noge, osim gležnja i stopala", "T24.4"),
    T24_5("Korozija prvoga stupnja kuka i noge, osim gležnja i stopala", "T24.5"),
    T24_6("Korozija drugoga stupnja kuka i noge, osim gležnja i stopala", "T24.6"),
    T24_7("Korozija trećega stupnja kuka i noge, osim gležnja i stopala", "T24.7"),
    T25("Opeklina i korozija gležnja i stopala", "T25"),
    T25_0("Opeklina nespecificirana stupnja gležnja i stopala", "T25.0"),
    T25_1("Opeklina prvoga stupnja gležnja i stopala", "T25.1"),
    T25_2("Opeklina drugoga stupnja gležnja i stopala", "T25.2"),
    T25_3("Opeklina trećega stupnja gležnja i stopala", "T25.3"),
    T25_4("Korozija nespecificirana stupnja gležnja i stopala", "T25.4"),
    T25_5("Korozija prvoga stupnja gležnja i stopala", "T25.5"),
    T25_6("Korozija drugoga stupnja gležnja i stopala", "T25.6"),
    T25_7("Korozija trećega stupnja gležnja i stopala", "T25.7"),
    T26("Opeklina i korozija ograničena na oko i očne adnekse", "T26"),
    T26_0("Opeklina očnih vjeđa i periokularnoga prostora", "T26.0"),
    T26_1("Opeklina rožnice i spojnične vrećice", "T26.1"),
    T26_2("Opeklina s posljedičnim prsnućem i razaranjem očne jabučice", "T26.2"),
    T26_3("Opeklina drugih dijelova oka i adneksa", "T26.3"),
    T26_4("Opeklina oka i adneksa, nespecificiranih dijelova", "T26.4"),
    T26_5("Korozija očnih vjeđa i periokularnoga prostora", "T26.5"),
    T26_6("Korozija rožnice i spojnične vrećice", "T26.6"),
    T26_7("Korozija s posljedičnim prsnućem i razaranjem očne jabučice", "T26.7"),
    T26_8("Korozija drugih dijelova oka i adneksa", "T26.8"),
    T26_9("Korozija oka i adneksa, nespecificiranih dijelova", "T26.9"),
    T27("Opeklina i korozija dišnih putova", "T27"),
    T27_0("Opeklina grkljana i dušnika", "T27.0"),
    T27_1("Opeklina grkljana, dušnika i pluća", "T27.1"),
    T27_2("Opeklina drugih dijelova dišnih putova", "T27.2"),
    T27_3("Opeklina dišnih putova, nespecificirana dijela", "T27.3"),
    T27_4("Korozija grkljana i dušnika", "T27.4"),
    T27_5("Korozija grkljana, dušnika i pluća", "T27.5"),
    T27_6("Korozija drugih dijelova dišnih putova", "T27.6"),
    T27_7("Korozija dišnih putova, nespecificirana dijela", "T27.7"),
    T28("Opeklina i korozija drugih unutrašnjih organa", "T28"),
    T28_0("Opeklina usta i ždrijela", "T28.0"),
    T28_1("Opeklina jednjaka", "T28.1"),
    T28_2("Opeklina drugih dijelova probavnog sustava", "T28.2"),
    T28_3("Opeklina unutrašnjih genitourinarnih organa", "T28.3"),
    T28_4("Opeklina drugih i nespecificiranih unutrašnjih organa", "T28.4"),
    T28_5("Korozija usta i ždrijela", "T28.5"),
    T28_6("Korozija jednjaka", "T28.6"),
    T28_7("Korozija drugih dijelova probavnog sustava", "T28.7"),
    T28_8("Korozija unutrašnjih genitourinarnih organa", "T28.8"),
    T28_9("Korozija drugih i nespecificiranih unutrašnjih organa", "T28.9"),
    T29("Opekline i korozije multiplih lokalizacija", "T29"),
    T29_0("Opekline multiplih lokalizacija, nespecificirana stupnja", "T29.0"),
    T29_1("Opekline multiplih lokalizacija, naznačene ne više od prvoga stupnja", "T29.1"),
    T29_2("Opekline multiplih lokalizacija, naznačene ne više od drugoga stupnja", "T29.2"),
    T29_3("Opekline multiplih lokalizacija, najmanje jedna označena trećim stupnjem", "T29.3"),
    T29_4("Korozije multiplih lokalizacija, nespecificirana stupnja", "T29.4"),
    T29_5("Korozije multiplih lokalizacija, naznačene ne više od prvoga stupnja", "T29.5"),
    T29_6("Korozije multiplih lokalizacija, naznačene ne više od drugoga stupnja", "T29.6"),
    T29_7("Korozije multiplih lokalizacija, najmanje jedna označena trećim stupnjem", "T29.7"),
    T30("Opeklina i korozija, nespecificirane tjelesne regije", "T30"),
    T30_0("Opeklina nespecificirana dijela tijela, nespecificirana stupnja", "T30.0"),
    T30_1("Opeklina prvoga stupnja, nespecificirana dijela tijela", "T30.1"),
    T30_2("Opeklina drugoga stupnja, nespecificirana dijela tijela", "T30.2"),
    T30_3("Opeklina trećega stupnja, nespecificirana dijela tijela", "T30.3"),
    T30_4("Korozija nespecificirana dijela tijela, nespecificirana stupnja", "T30.4"),
    T30_5("Korozija prvoga stupnja, nespecificirana dijela tijela", "T30.5"),
    T30_6("Korozija drugoga stupnja, nespecificirana dijela tijela", "T30.6"),
    T30_7("Korozija trećega stupnja, nespecificirana dijela tijela", "T30.7"),
    T31("Opekline svrstane prema veličini zahvaćene tjelesne površine", "T31"),
    T31_0("Opekline s manje od 10% zahvaćene tjelesne površine", "T31.0"),
    T31_1("Opekline s 10-19% zahvaćene tjelesne površine", "T31.1"),
    T31_2("Opekline s 20-29% zahvaćene tjelesne površine", "T31.2"),
    T31_3("Opekline s 30-39% zahvaćene tjelesne površine", "T31.3"),
    T31_4("Opekline s 40-49% zahvaćene tjelesne površine", "T31.4"),
    T31_5("Opekline s 50-59% zahvaćene tjelesne površine", "T31.5"),
    T31_6("Opekline sa 60-69% zahvaćene tjelesne površine", "T31.6"),
    T31_7("Opekline sa 70-79% zahvaćene tjelesne površine", "T31.7"),
    T31_8("Opekline s 80-89% zahvaćene tjelesne površine", "T31.8"),
    T31_9("Opekline s više od 90% zahvaćene tjelesne površine", "T31.9"),
    T32("Korozije svrstane prema veličini zahvaćene tjelesne površine", "T32"),
    T32_0("Korozije s manje od 10% zahvaćene tjelesne površine", "T32.0"),
    T32_1("Korozije s 10-19% zahvaćene tjelesne površine", "T32.1"),
    T32_2("Korozije s 20-29% zahvaćene tjelesne površine", "T32.2"),
    T32_3("Korozije s 30-39% zahvaćene tjelesne površine", "T32.3"),
    T32_4("Korozije s 40-49% zahvaćene tjelesne površine", "T32.4"),
    T32_5("Korozije s 50-59% zahvaćene tjelesne površine", "T32.5"),
    T32_6("Korozije sa 60-69% zahvaćene tjelesne površine", "T32.6"),
    T32_7("Korozije sa 70-79% zahvaćene tjelesne površine", "T32.7"),
    T32_8("Korozije s 80-89% zahvaćene tjelesne površine", "T32.8"),
    T32_9("Korozije s više od 90% zahvaćene tjelesne površine", "T32.9"),
    T33("Površinske smrzotine", "T33"),
    T33_0("Površinska smrzotina glave", "T33.0"),
    T33_1("Površinska smrzotina vrata", "T33.1"),
    T33_2("Površinska smrzotina prsnoga koša", "T33.2"),
    T33_3("Površinska smrzotina trbušne stjenke, donjeg dijela leđa i zdjelice", "T33.3"),
    T33_4("Površinska smrzotina ruke", "T33.4"),
    T33_5("Površinska smrzotina zapešća i šake", "T33.5"),
    T33_6("Površinska smrzotina kuka i natkoljenice", "T33.6"),
    T33_7("Površinska smrzotina koljena i potkoljenice", "T33.7"),
    T33_8("Površinska smrzotina gležnja i stopala", "T33.8"),
    T33_9("Površinska smrzotina drugih i nespecificiranih mjesta", "T33.9"),
    T34("Smrzotina s nekrozom tkiva", "T34"),
    T34_0("Smrzotina glave s nekrozom tkiva", "T34.0"),
    T34_1("Smrzotina vrata s nekrozom tkiva", "T34.1"),
    T34_2("Smrzotina prsnoga koša s nekrozom tkiva", "T34.2"),
    T34_3("Smrzotina trbušne stijenke, donjeg dijela leđa i zdjelice s nekrozom tkiva", "T34.3"),
    T34_4("Smrzotina ruke s nekrozom tkiva", "T34.4"),
    T34_5("Smrzotina zapešća i šake s nekrozom tkiva", "T34.5"),
    T34_6("Smrzotina kuka i natkoljenice s nekrozom tkiva", "T34.6"),
    T34_7("Smrzotina koljena i potkoljenice s nekrozom tkiva", "T34.7"),
    T34_8("Smrzotina gležnja i stopala s nekrozom tkiva", "T34.8"),
    T34_9("Smrzotina s nekrozom tkiva drugih i nespecificiranih mjesta", "T34.9"),
    T35("Smrzotine multiplih lokalizacija i nespecificirane smrzotine", "T35"),
    T35_0("Površinske smrzotine multiple lokalizacije", "T35.0"),
    T35_1("Smrzotine s nekrozom tkiva multiple lokalizacije", "T35.1"),
    T35_2("Nespecificirane smrzotine glave i vrata", "T35.2"),
    T35_3("Nespecificirane smrzotine prsnoga koša, trbuha, donjeg dijela leđa i zdjelice", "T35.3"),
    T35_4("Nespecificirane smrzotine ruke", "T35.4"),
    T35_5("Nespecificirane smrzotine noge", "T35.5"),
    T35_6("Nespecificirane smrzotine multiple lokalizacije", "T35.6"),
    T35_7("Nespecificirane smrzotine nespecificirana mjesta", "T35.7"),
    T36("Otrovanje sistemnim antibioticima", "T36"),
    T36_0("Penicilini", "T36.0"),
    T36_1("Cefalosporini i drugi beta-laktamski antibiotici", "T36.1"),
    T36_2("Kloramfenikolna skupina", "T36.2"),
    T36_3("Makrolidi", "T36.3"),
    T36_4("Tetraciklini", "T36.4"),
    T36_5("Aminoglikozidi", "T36.5"),
    T36_6("Rifamicini", "T36.6"),
    T36_7("Antimikotični antibiotici, sistemno primijenjeni", "T36.7"),
    T36_8("Ostali sistemni antibiotici", "T36.8"),
    T36_9("Sistemni antibiotici, nespecificirani", "T36.9"),
    T37("Otrovanje drugim sistemnim antiinfekcijskim i antiparazitarnim sredstvima", "T37"),
    T37_0("Sulfonamidi", "T37.0"),
    T37_1("Antimikobakterijski lijekovi", "T37.1"),
    T37_2("Antimalarici i lijekovi koji djeluju na druge krvne protozoe", "T37.2"),
    T37_3("Ostali antiprotozoarni lijekovi", "T37.3"),
    T37_4("Antihelmintici", "T37.4"),
    T37_5("Antivirusni lijekovi", "T37.5"),
    T37_8("Druga specificirana sistemna antiinfekcijska i antiparazitarna sredstva", "T37.8"),
    T37_9("Sistemna antiinfekcijska i antiparazitarna sredstva, nespecificirana", "T37.9"),
    T38("Otrovanje hormonima i njihovim sintetskim zamjenama i antagonistima, nesvrstanim drugamo", "T38"),
    T38_0("Glukokortikoidi i sintetske zamjene", "T38.0"),
    T38_1("Tireoidni hormoni i njihovi supstituenti", "T38.1"),
    T38_2("Antitireoidna sredstva", "T38.2"),
    T38_3("Inzulin i oralni hipoglikemijski lijekovi (antidijabetici)", "T38.3"),
    T38_4("Oralni kontraceptivi", "T38.4"),
    T38_5("Ostali estrogeni i gestageni", "T38.5"),
    T38_6("Antigonadotropini, antiestrogeni, antiandrogeni, nesvrstani drugamo", "T38.6"),
    T38_7("Androgeni i istovrsni anabolici", "T38.7"),
    T38_8("Ostali i nespecificirani hormoni i njihove sintetske zamjene", "T38.8"),
    T38_9("Ostali i nespecificirani antagonisti hormona", "T38.9"),
    T39("Otrovanje neopioidnim analgeticima, antipireticima i antireumaticima", "T39"),
    T39_0("Salicilati", "T39.0"),
    T39_1("Derivati 4-aminofenola", "T39.1"),
    T39_2("Derivati pirazolona", "T39.2"),
    T39_3("Ostali nesteroidni antiinflamatorni lijekovi (NSAID)", "T39.3"),
    T39_4("Antireumatici, nesvrstani drugamo", "T39.4"),
    T39_8("Ostali neopioidni analgetici, antipiretici i antireumatici, nesvrstani drugamo", "T39.8"),
    T39_9("Neopioidni analgetici, antipiretici i antireumatici, nespecificirani", "T39.9"),
    T40("Otrovanje narkoticima i psihterapeuticima (halucinogenima)", "T40"),
    T40_0("Opijum", "T40.0"),
    T40_1("Heroin", "T40.1"),
    T40_2("Ostali opijati", "T40.2"),
    T40_3("Metadon", "T40.3"),
    T40_4("Ostali sintetski narkotici", "T40.4"),
    T40_5("Kokain", "T40.5"),
    T40_6("Ostali i nespecificirani narkotici", "T40.6"),
    T40_7("Kanabis (derivati)", "T40.7"),
    T40_8("Lizergid (LSD)", "T40.8"),
    T40_9("Ostali i nespecificirani psihodisleptici (halucinogeni)", "T40.9"),
    T41("Otrovanje anesteticima i terapijskim plinovima", "T41"),
    T41_0("Inhalacijski anestetici", "T41.0"),
    T41_1("Intravenski anestetici", "T41.1"),
    T41_2("Ostali i nespecificirani opći anestetici", "T41.2"),
    T41_3("Lokalni anestetici", "T41.3"),
    T41_4("Anestetici, nespecificirani", "T41.4"),
    T41_5("Terapijski plinovi", "T41.5"),
    T42("Otrovanje antiepilepticima, sedativima-hipnoticima i antiparkinsonicima", "T42"),
    T42_0("Derivati hidantoina", "T42.0"),
    T42_1("Iminostilbenzeni", "T42.1"),
    T42_2("Sukcinimidi i oksazolidindioni", "T42.2"),
    T42_3("Barbiturati", "T42.3"),
    T42_4("Benzodiazepini", "T42.4"),
    T42_5("Mješavina antiepileptika, nesvrstanih drugamo", "T42.5"),
    T42_6("Ostali antiepileptici i sedativi-hipnotici", "T42.6"),
    T42_7("Antiepileptici i sedativi-hipnotici, nespecificirani", "T42.7"),
    T42_8("Antiparkinsonici i ostali centralni depresori mišićnog tonusa", "T42.8"),
    T43("Otrovanje psihotropnim lijekovima, nesvrstanim drugamo", "T43"),
    T43_0("Triciklični i tetraciklični antidepresivi", "T43.0"),
    T43_1("Antidepresivi iz skupine inhibitora monoamino-oksidaze", "T43.1"),
    T43_2("Ostali i nespecificirani antidepresivi", "T43.2"),
    T43_3("Fenotijazinski antipsihotici i neuroleptici", "T43.3"),
    T43_4("Butirofenonski i tioksantenski neuroleptici", "T43.4"),
    T43_5("Ostali i nespecificirani antipsihotici i neuroleptici", "T43.5"),
    T43_6("Psihostimulatori s mogućim navikavanjem", "T43.6"),
    T43_8("Ostali psihotropni lijekovi, nesvrstani drugamo", "T43.8"),
    T43_9("Psihotropni lijekovi, nespecificirani", "T43.9"),
    T44("Otrovanje lijekovima s osnovnim djelovanjem na vegetativni živčani sustav", "T44"),
    T44_0("Antikolinesterazna sredstva", "T44.0"),
    T44_1("Ostali parasimpatomimetici (kolinergici)", "T44.1"),
    T44_2("Ganglioblokatori, nesvrstani drugamo", "T44.2"),
    T44_3("Ostali parasimpatolitici (antikolinergici i antimuskarinske tvari) i spazmolitici, nesvrstani drugamo", "T44.3"),
    T44_4("Ekscitatori alfa-adrenergičnih receptora, nesvrstani drugamo", "T44.4"),
    T44_5("Ekscitatori beta-adrenergičnih receptora, nesvrstani drugamo", "T44.5"),
    T44_6("Blokatori alfa-adrenergičnih receptora, nesvrstani drugamo", "T44.6"),
    T44_7("Blokatori beta-adrenergičnih receptora, nesvrstani drugamo", "T44.7"),
    T44_8("Lijekovi centralnog djelovanja i blokatori adrenergičnih neurona, nesvrstani drugamo", "T44.8"),
    T44_9("Ostali i nespecificirani lijekovi s osnovnim djelovanjem na vegetativni živčani sustav", "T44.9"),
    T45("Otrovanje primarno sistemnim i hematološkim sredstvima, nesvrstanim drugamo", "T45"),
    T45_0("Antialergici i antiemetici", "T45.0"),
    T45_1("Antineoplastici i imunosupresivi", "T45.1"),
    T45_2("Vitamini, nesvrstani drugamo", "T45.2"),
    T45_3("Enzimi, nesvrstani drugamo", "T45.3"),
    T45_4("Otrovanje željezom i spojevima željeza", "T45.4"),
    T45_5("Antikoagulansi", "T45.5"),
    T45_6("Sredstva koja djeluju na fibrinolizu", "T45.6"),
    T45_7("Antagonisti antikoagulanasa, vitamin K i drugi koagulansi", "T45.7"),
    T45_8("Ostali primarno sistemni i hematološki lijekovi", "T45.8"),
    T45_9("Primarno sistemni i hematološki lijekovi, nespecificirani", "T45.9"),
    T46("Otrovanje lijekovima s primarnim djelovanjem na kardiovaskularni sustav", "T46"),
    T46_0("Kardiotonični glikozidi i lijekovi slična djelovanja", "T46.0"),
    T46_1("Antagonisti kalcija", "T46.1"),
    T46_2("Ostali antidizritmični lijekovi (regulatori srčanog ritma), nesvrstani drugamo", "T46.2"),
    T46_3("Koronarni vazodilatatori, nesvrstani drugamo", "T46.3"),
    T46_4("Inhibitori angiotenzin-konvertaze", "T46.4"),
    T46_5("Ostali antihipertenzivni lijekovi, nesvrstani drugamo", "T46.5"),
    T46_6("Antihiperlipemici i antiarteriosklerotici", "T46.6"),
    T46_7("Periferni vazodilatatori", "T46.7"),
    T46_8("Antivarikozni lijekovi, uključujući sklerozirajuća sredstva", "T46.8"),
    T46_9("Ostali i nespecificarni lijekovi s primarnim djelovanjem na kardiovaskularni sustav", "T46.9"),
    T47("Otrovanje lijekovima s primarnim djelovanjem na gastrointestinalni sustav", "T47"),
    T47_0("Antagonisti histaminskih H2-receptora", "T47.0"),
    T47_1("Ostali antacidi i lijekovi protiv želučane sekrecije", "T47.1"),
    T47_2("Stimulirajući (nadražujući) laksativi", "T47.2"),
    T47_3("Soli za čišćenje i osmotski laksativi", "T47.3"),
    T47_4("Ostali laksativi", "T47.4"),
    T47_5("Digestivi", "T47.5"),
    T47_6("Antidijaroici", "T47.6"),
    T47_7("Emetici", "T47.7"),
    T47_8("Ostala sredstva s primarnim djelovanjem na gastrointestinalni sustav", "T47.8"),
    T47_9("Sredstva s primarnim djelovanjem na gastrointestinalni sustav, nespecificirana", "T47.9"),
    T48("Otrovanje sredstvima s primarnim djelovanjem na glatko i skeletno mišićje te dišni sustav", "T48"),
    T48_0("Oksitocična sredstva", "T48.0"),
    T48_1("Relaksansi skeletnog mišićja (neuromuskularni blokatori)", "T48.1"),
    T48_2("Ostala i nespecificirana sredstva s primarnim djelovanjem na mišićje", "T48.2"),
    T48_3("Antitusici", "T48.3"),
    T48_4("Ekspektoransi", "T48.4"),
    T48_5("Sredstva protiv prehlade", "T48.5"),
    T48_6("Antiastmatici, nesvrstani drugamo", "T48.6"),
    T48_7("Ostala i nespecificirana sredstva s primarnim djelovanjem na dišni sustav", "T48.7"),
    T49("Otrovanje sredstvima za lokalnu primjenu s primarnim djelovanjem na kožu i sluznice te oftalmološkim, otorinolaringološkim i stomatološkim lijekovima", "T49"),
    T49_0("Lokalni antimikotični, antiinfekcijski i antiinflamatorni lijekovi, nesvrstani drugamo", "T49.0"),
    T49_1("Antipruritična sredstva (sredstva protiv svrbeža)", "T49.1"),
    T49_2("Lokalni adstringensi i detergensi", "T49.2"),
    T49_3("Emolijencije, demulcencije i zaštitna sredstva", "T49.3"),
    T49_4("Keratolitici, keratoplastici i ostali lijekovi i pripravci za kosu", "T49.4"),
    T49_5("Oftalmološki lijekovi i pripravci", "T49.5"),
    T49_6("Otorinolaringološki lijekovi i pripravci", "T49.6"),
    T49_7("Zubni lijekovi primijenjeni lokalno", "T49.7"),
    T49_8("Ostala sredstva za lokalnu primjenu", "T49.8"),
    T49_9("Sredstvo za lokalnu primjenu, nespecificirano", "T49.9"),
    T50("Otrovanje diureticima te drugim i nespecificiranim lijekovima, ljekovitim i biološkim tvarima", "T50"),
    T50_0("Mineralokortikoidi i njihovi antagonsti", "T50.,"),
    T50_1("Diuretici koji djeluju na uzlazni krak Henleove petlje", "T50.1"),
    T50_2("Inhibitori karboanhidraze, benzotiadizini i drugi diuretici", "T50.2"),
    T50_3("Elekroliti, kalorijska sredstva i sredstva za održavanje ravnoteže tjelesnih tekućina", "T50.3"),
    T50_4("Lijekovi s djelovanjem na metabolizam mokraćne kiseline", "T50.4"),
    T50_5("Sredstva za smanjenje (smanjivanje) apetita", "T50.5"),
    T50_6("Antidoti i kelati, nesvrstani drugamo", "T50.6"),
    T50_7("Analeptici i antagonisti opijatskih receptora", "T50.7"),
    T50_8("Dijagnostička sredstva", "T50.8"),
    T50_9("Ostale i nespecificirane lijekovi, ljekovite i biološke tvari", "T50.9"),
    T51("Toksičan učinak alkohola", "T51"),
    T51_0("Etanol", "T51.0"),
    T51_1("Metanol", "T51.1"),
    T51_2("2-Propanol", "T51.2"),
    T51_3("Patočno ulje", "T51.3"),
    T51_8("Ostali alkoholi", "T51.8"),
    T51_9("Alkohol, nespecificiran", "T51.9"),
    T52("Toksičan učinak organskih otapala", "T52"),
    T52_0("Naftni derivati", "T52.0"),
    T52_1("Benzen", "T52.1"),
    T52_2("Homolozi benzena", "T52.2"),
    T52_3("Glikoli", "T52.3"),
    T52_4("Ketoni", "T52.4"),
    T52_8("Ostala organska otapala", "T52.8"),
    T52_9("Organsko otapalo, nespecificirano", "T52.9"),
    T53("Toksičan učinak halogenih derivata alifatskih i aromatskih ugljikovodika", "T53"),
    T53_0("Ugljični tetraklorid", "T53.0"),
    T53_1("Kloroform", "T53.1"),
    T53_2("Trikloretilen", "T53.2"),
    T53_3("Tetrakloretilen", "T53.3"),
    T53_4("Diklormetan", "T53.4"),
    T53_5("Klorofluorokarbonati", "T53.5"),
    T53_6("Ostali halogeni derivati alifatskih ugljikovodika", "T53.6"),
    T53_7("Ostali halogeni derivati aromatskih ugljikovodika", "T53.7"),
    T53_9("Halogeni derivati alifatskih i aromatskih ugljikovodika, nespecificirani", "T53.9"),
    T54("Toksičan učinak korozivnih tvari", "T54"),
    T54_0("Fenol i njegovi homolozi", "T54.0"),
    T54_1("Ostali korozivni organski spojevi", "T54.1"),
    T54_2("Korozivne kiseline i kiselinama slične tvari", "T54.2"),
    T54_3("Korozivne alkalije i njima slične tvari", "T54.3"),
    T54_9("Korozivna tvar, nespecificirana", "T54.9"),
    T55("Toksičan učinak sapuna i deterdženata", "T55"),
    T55_0("Toksičan učinak sapuna i deterdženata", "T55.0"),
    T56("Toksičan učinak kovina", "T56"),
    T56_0("Olovo i njegovi spojevi", "T56.0"),
    T56_1("Živa i njezini spojevi", "T56.1"),
    T56_2("Krom i njegovi spojevi", "T56.2"),
    T56_3("Kadmij i njegovi spojevi", "T56.3"),
    T56_4("Bakar i njegovi spojevi", "T56.4"),
    T56_5("Cink i njegovi spojevi", "T56.5"),
    T56_6("Kositar i njegovi spojevi", "T56.6"),
    T56_7("Berilij i njegovi spojevi", "T56.7"),
    T56_8("Ostale kovine", "T56.8"),
    T56_9("Kovina, nespecificirana", "T56.9"),
    T57("Toksičan učinak drugih anorganskih tvari", "T57"),
    T57_0("Arsen i njegovi spojevi", "T57.0"),
    T57_1("Fosfor i njegovi spojevi", "T57.1"),
    T57_2("Mangan i njegovi spojevi", "T57.2"),
    T57_3("Cijanovodik", "T57.3"),
    T57_8("Ostale specificirane anorganske tvari", "T57.8"),
    T57_9("Anorganska tvar, nespecificirana", "T57.9"),
    T58("Toksičan učinak ugljičnog monoksida", "T58"),
    T58_0("Toksičan učinak ugljičnog monoksida", "T58.0"),
    T59("Toksičan učinak ostalih plinova, dimova i para", "T59"),
    T59_0("Dušikovi oksidi", "T59.0"),
    T59_1("Sumporni dioksid", "T59.1"),
    T59_2("Formaldehid", "T59.2"),
    T59_3("Suzni plin", "T59.3"),
    T59_4("Klorni plin", "T59.4"),
    T59_5("Fluorni plin i fluorovodik", "T59.5"),
    T59_6("Sumporovodik", "T59.6"),
    T59_7("Ugljični dioksid", "T59.7"),
    T59_8("Ostali specificirani plinovi, dimovi i pare", "T59.8"),
    T59_9("Plinovi, dimovi i pare, nespecificirani", "T59.9"),
    T60("Toksičan učinak pesticida", "T60"),
    T60_0("Organofosforni i karbamatski insekticidi", "T60.0"),
    T60_1("Halogenski insekticidi", "T60.1"),
    T60_2("Ostali insekticidi", "T60.2"),
    T60_3("Herbicidi i fungicidi", "T60.3"),
    T60_4("Rodenticidi", "T60.4"),
    T60_8("Ostali pesticidi", "T60.8"),
    T60_9("Pesticid, nespecificiran", "T60.9"),
    T61("Toksičan učinak štetnih tvari pojedenih s hranom iz mora", "T61"),
    T61_0("Ciguatera otrovanje ribom", "T61.0"),
    T61_1("Skombroidno otrovanje ribom", "T61.1"),
    T61_2("Ostala otrovanja ribama i školjkama", "T61.2"),
    T61_8("Toksičan učinak druge hrane iz mora", "T61.8"),
    T61_9("Toksičan učinak nespecificirane hrane iz mora", "T61.9"),
    T62("Toksičan učinak drugih štetnih tvari pojedenih s hranom", "T62"),
    T62_0("Pojedene gljive", "T62.0"),
    T62_1("Pojedeni bobičasti plodovi", "T62.1"),
    T62_2("Druge pojedene (dijelovi) biljke (biljaka)", "T62.2"),
    T62_8("Ostale specificirane štetne tvari pojedene u hrani", "T62.8"),
    T62_9("Štetne tvari pojedene u hrani, nespecificirane", "T62.9"),
    T63("Toksičan učinak doticaja s otrovnim životinjama", "T63"),
    T63_0("Zmijski otrov", "T63.0"),
    T63_1("Otrov drugih gmazova (reptila)", "T63.1"),
    T63_2("Otrov škorpiona", "T63.2"),
    T63_3("Otrov pauka", "T63.3"),
    T63_4("Otrov drugih člankonožaca", "T63.4"),
    T63_5("Toksičan učinak dodira s ribom", "T63.5"),
    T63_6("Toksičan učinak dodira s drugim morskim životinjama", "T63.6"),
    T63_8("Toksičan učinak dodira s drugim otrovnim životinjama", "T63.8"),
    T63_9("Toksičan učinak dodira s nespecificiranom otrovnom životinjom", "T63.9"),
    T64("Toksičan učinak aflatoksina i ostalih mikotoksina kontaminanata hrane", "T64"),
    T64_0("Toksičan učinak aflatoksina i ostalih mikotoksina kontaminanata hrane", "T64.0"),
    T65("Toksičan učinak ostalih i nespecificiranih tvari", "T65"),
    T65_0("Cijanidi", "T65.0"),
    T65_1("Strihnin i njegove soli", "T65.1"),
    T65_2("Duhan i nikotin", "T65.2"),
    T65_3("Nitroderivati i aminoderivati benzena i njegovih homologa", "T65.3"),
    T65_4("Ugljični disulfid", "T65.4"),
    T65_5("Nitroglicerin i ostale dušične kiseline i esteri", "T65.5"),
    T65_6("Ličila i boje, nesvrstane drugamo", "T65.6"),
    T65_8("Toksičan učinak ostalih specificiranih tvari", "T65.8"),
    T65_9("Toksičan učinak nespecificirane tvari", "T65.9"),
    T66("Nespecificirani učinci zračenja", "T66"),
    T66_0("Nespecificirani učinci zračenja", "T66.0"),
    T67("Učinci topline i svjetla", "T67"),
    T67_0("Toplinski udar i sunčanica", "T67.0"),
    T67_1("Toplinska sinkopa", "T67.1"),
    T67_2("Toplinski grč", "T67.2"),
    T67_3("Toplinska iscrpljenost, anhidrija", "T67.3"),
    T67_4("Toplinska iscrpljenost zbog gubitka soli", "T67.4"),
    T67_5("Toplinska iscrpljenost, nespecificirana", "T67."),
    T67_6("Toplinski zamor, prolazan", "T67.6"),
    T67_7("Toplinski edem", "T67.7"),
    T67_8("Ostali učinci topline i svjetla", "T67.8"),
    T67_9("Učinak topline i svjetla, nespecificiran", "T67.9"),
    T68("Hipotermija", "T68"),
    T68_0("Hipotermija", "T68.0"),
    T69("Ostali učinci niske temperature", "T69"),
    T69_0("Imerzija (potapanje) šake i stopala", "T69.0"),
    T69_1("Ozebline", "T69.1"),
    T69_8("Ostali označeni učinci snižene temperature", "T69.8"),
    T69_9("Učinci snižene temperature, nespecificirani", "T69.9"),
    T70("Učinci tlaka zraka i tlaka vode", "T70"),
    T70_0("Barotrauma uha", "T70.0"),
    T70_1("Barotrauma sinusa", "T70.1"),
    T70_2("Ostali i nespecificirani učinci velike visine", "T70.2"),
    T70_3("Kesonska bolest (dekompresijska bolest)", "T70.3"),
    T70_4("Učinci tekućina pod visokim tlakom", "T70.4"),
    T70_8("Ostali učinci tlaka zraka i tlaka vode", "T70.8"),
    T70_9("Učinak tlaka zraka i tlaka vode, nespecificiran", "T70.9"),
    T71("Asfiksija", "T71"),
    T71_0("Asfiksija", "T71.0"),
    T73("Učinci ostalih nedostataka", "T73"),
    T73_0("Učinci gladi", "T73.0"),
    T73_1("Učinci žeđi", "T73.1"),
    T73_2("Iscrpljenost zbog izloženosti", "T73.2"),
    T73_3("Iscrpljenost zbog pretjeranog napora", "T73.3"),
    T73_8("Ostali učinci nedostataka", "T73.8"),
    T73_9("Učinak nedostatka, nespecificiran", "T73.9"),
    T74("Sindromi zlostavljanja", "T74"),
    T74_0("Zapuštanje ili napuštanje", "T74.0"),
    T74_1("Tjelesno zlostavljanje", "T74.1"),
    T74_2("Spolno zlostavljanje", "T74.2"),
    T74_3("Psihološko zlostavljanje", "T74.3"),
    T74_8("Ostali sindromi zlostavljanja", "T74.8"),
    T74_9("Sindrom zlostavljanja, nespecificiran", "T74.9"),
    T75("Učinci drugih vanjskih uzroka", "T75"),
    T75_0("Učinci groma", "T75.0"),
    T75_1("Utapanje i nesmrtonosno potapanje", "T75.1"),
    T75_2("Učinci vibracije", "T75.2"),
    T75_3("Bolest kretanja", "T75.3"),
    T75_4("Učinci električne struje", "T75.4"),
    T75_8("Ostali specificirani učinci vanjskih uzroka", "T75.8"),
    T78("Štetni učinci, nesvrstani drugamo", "T78"),
    T78_0("Anafilaktični šok uzrokovan štetnim djelovanjem hrane", "T78.0"),
    T78_1("Ostala štetna djelovanja hrane, nesvrstana drugamo", "T78.1"),
    T78_2("Anafilaktični šok, nespecificiran", "T78.2"),
    T78_3("Angioneurotski edem", "T78.3"),
    T78_4("Alergija, nespecificirana", "T78.4"),
    T78_8("Ostali štetni učinci, nesvrstani drugamo", "T78.8"),
    T78_9("Štetni učinci, nespecificirani", "T78.9"),
    T79("Rane komplikacije traume, nesvrstane drugamo", "T79"),
    T79_0("Zračna embolija (traumatska)", "T79.0"),
    T79_1("Masna embolija (traumatska)", "T79.1"),
    T79_2("Traumatsko sekundarno i ponovljeno krvarenje", "T79.2"),
    T79_3("Posttraumatska infekcija rane, nesvrstana drugamo", "T79.3"),
    T79_4("Traumatski šok", "T79.4"),
    T79_5("Traumatska anurija", "T79.5"),
    T79_6("Traumatska ishemija mišića", "T79.6"),
    T79_7("Traumatski supkutani emfizem", "T79.7"),
    T79_8("Ostale rane komplikacije traume", "T79.8"),
    T79_9("Nespecificirane rane komplikacije traume", "T79.9"),
    T80("Komplikacije nakon infuzije, transfuzije i terapijske injekcije", "T80"),
    T80_0("Zračna embolija nakon infuzije, transfuzije i terapijske injekcije", "T80.0"),
    T80_1("Vaskularne komplikacije nakon infuzije, transfuzije i terapijske injekcije", "T80.1"),
    T80_2("Infekcije nakon infuzije, transfuzije i terapijske injekcije", "T80.2"),
    T80_3("Reakcija AB0 inkopatibilnosti", "T80.3"),
    T80_4("Reakcija na Rh inkopatibilnosti", "T80.4"),
    T80_5("Anafilaktični šok uzrokovan serumom", "T80.5"),
    T80_6("Ostale reakcije na serum", "T80.6"),
    T80_8("Ostale komplikacija nakon infuzije, transfuzije i terapijske injekcije", "T80.8"),
    T80_9("Nespecificirana komplikacija nakon infuzije, transfuzije i terapijske injekcije", "T80.9"),
    T81("Komplikacije postupaka, nesvrstanih drugamo", "T81"),
    T81_0("Krvarenje i hematom kao komplikacije postupka, nesvrstane drugamo", "T81.0"),
    T81_1("Šok u tijeku ili nakon postupka, nesvrstan drugamo", "T81.1"),
    T81_2("Nehotičan (slučajan) ubod ili laceracija u tijeku postupka, nesvrstani drugamo", "T81.2"),
    T81_3("Dizrupcija operativne rane, nesvrstana drugamo", "T81.3"),
    T81_4("Infekcija nakon postupka, nesvrstana drugamo", "T81.4"),
    T81_5("Strano tijelo, nehotice ostavljeno u tjelesnoj šupljini ili operativnoj rani nakon postupka", "T81.5"),
    T81_6("Akutna reakcija na stranu tvar nehotice ostavljenu u tijeku postupka", "T81.6"),
    T81_7("Vaskularne komplikacije nakon postupka, nesvrstane drugamo", "T81.7"),
    T81_8("Ostale komplikacije postupaka, nesvrstane drugamo", "T81.8"),
    T81_9("Nespecificirane komplikacije postupka", "T81.9"),
    T82("Komplikacije srčanih i vaskularnih protetskih naprava, implantata i transplantata", "T82"),
    T82_0("Mehaničke komplikacije proteza srčanih valvula (zalistaka)", "T82.0"),
    T82_1("Mehaničke komplikacije srčane elektronske naprave", "T82.1"),
    T82_2("Mehaničke komplikacije premoštenja koronarnih arterija i umjetnih zalistaka", "T82.2"),
    T82_3("Mehaničke komplikacije ostalih vaskularnih umjetnih naprava", "T82.3"),
    T82_4("Mehaničke komplikacije s kateterom za vaskularnu dijalizu", "T82.4"),
    T82_5("Mehaničke komplikacije ostalih srčanih i vaskularnih naprava i implantata", "T82.5"),
    T82_6("Infekcija i upalna reakcija uzrokovana umjetnim srčanim zaliscima", "T82.6"),
    T82_7("Infekcija i upalna reakcija uzrokovana drugim srčanim i vaskularnim protetskim napravama, implantatima i transplantatima", "T82.7"),
    T82_8("Ostale komplikacije srčanih i vaskularnih protetskih naprava, implantata i transplantata", "T82.8"),
    T82_9("Nespecificirana komplikacija srčanih i vaskularnih protetskih naprava, implantata i transplantata", "T82.9"),
    T83("Komplikacije genitourinarnih protetskih naprava, implantata i transplantata", "T83"),
    T83_0("Mehanička komplikacija urinarnog (stalnog) katetera", "T83.0"),
    T83_1("Mehanička komplikacija ostalih urinarnih naprava i implantata", "T83.1"),
    T83_2("Mehaničke komplikacije presađenog urinarnog organa", "T83.2"),
    T83_3("Mehaničke komplikacije intrauterinom kontracepcijskom napravom (sredstvom)", "T83.3"),
    T83_4("Mehaničke komplikacije ostalih protetskih naprava, implantata i transplantata spolnog sustava", "T83.4"),
    T83_5("Infekcija i upalna reakcija uzrokovana protetskom napravom, implantatom i transplantatom u mokraćnom sustavu", "T83.5"),
    T83_6("Infekcija i upalna reakcija uzrokovana protetskom napravom, implantatom i transplantatom u spolnom sustavu", "T83.6"),
    T83_8("Ostale komplikacije genitourinarnih protetskih naprava, implantata i transplantata", "T83.8"),
    T83_9("Nespecificirana komplikacija genitourinarne naprave, implantata i transplantata", "T83.9"),
    T84("Komplikacija unutrašnjih ortopedskih protetskih naprava, implantata i transplantata", "T84"),
    T84_0("Mehaničke komplikacije unutrašnje proteze zgloba", "T84.0"),
    T84_1("Mehaničke komplikacije unutrašnjih učvršćujućih naprava za kosti udova", "T84.1"),
    T84_2("Mehaničke komplikacije unutrašnjih učvrščujućih naprava za ostale kosti", "T84.2"),
    T84_3("Mehaničke komplikacije ostalih koštanih naprava, implantata i transplantata", "T84.3"),
    T84_4("Mehaničke komplikacije ostalih unutrašnjih ortopedskih naprava, implantata i transplantata", "T84.4"),
    T84_5("Infekcija i upalna reakcija uzrokovana unutrašnjom zglobnom protezom", "T84.5"),
    T84_6("Infekcija i upalna reakcija uzrokovana unutrašnjom učvršćujućom napravom (na bilo kojem mjestu)", "T84.6"),
    T84_7("Infekcija i upalna reakcija uzrokovana ostalim unutrašnjim ortopedskim napravama, implantatima i transplantatima", "T84.7"),
    T84_8("Ostale komplikacije unutrašnjih ortopedskih protetskih naprava, implantata i transplantata", "T84.8"),
    T84_9("Nespecificirana komplikacija unutrašnjih ortopedskih protetskih naprava, implantata i transplantata", "T84.9"),
    T85("Komplikacije ostalih unutrašnjih protetskih naprava, implantata i transplantata", "T85"),
    T85_0("Mehaničke komplikacije s ventrikularnim intrakranijalnim (komunikacijskim) šantom", "T85.0"),
    T85_1("Mehaničke komplikacije s implantiranim elektronskim stimulatorom živčanog sustava", "T85.1"),
    T85_2("Mehaničke komplikacije intraokularne leće", "T85.2"),
    T85_3("Mehaničke komplikacije s ostalim intraokularnim protetskim napravama, implantatima i transplantatima", "T85.3"),
    T85_4("Mehanička komplikacija s protezom i implantatom dojke", "T85.4"),
    T85_5("Mehaničke komplikacije s gastrointestinalnim protetskim napravama, implantatima i transplantatima", "T85.5"),
    T85_6("Mehaničke komplikacije s ostalim unutrašnjim protetskim napravama, implantatima i transplantatima", "T85.6"),
    T85_7("Infekcija i upalna reakcija uzrokovana ostalim unutrašnjim protetskim napravama, implantatima i transplantatima", "T85.7"),
    T85_8("Ostale komplikacije unutrašnjih protetskih naprava, implantata i transplantata, nesvrstane drugamo", "T85.8"),
    T85_9("Nespecificirana komplikacija unutrašnje protetske naprave, implantata i transplantata", "T85.9"),
    T86("Neuspjeh i odbacivanje presađenih organa i tkiva", "T86"),
    T86_0("Odbacivanje transplantata koštane srži", "T86.0"),
    T86_1("Neuspjeh i odbacivanje transplantata bubrega", "T86.1"),
    T86_2("Neuspjeh i odbacivanje transplantata srca", "T86.2"),
    T86_3("Neuspjeh i odbacivanje transplantata srce-pluća", "T86.3"),
    T86_4("Neuspjeh i odbacivanje transplantata jetre", "T86.4"),
    T86_8("Neuspjeh i odbacivanje ostalih presađenih organa i tkiva", "T86.8"),
    T86_9("Neuspjeh i odbacivanje nespecificiranoga presađenog organa i tkiva", "T86.9"),
    T87("Komplikacije znakovite za ponovno prišivanje i amputaciju", "T87"),
    T87_0("Komplikacije ponovno prišivene ruke (ili dijela)", "T87.0"),
    T87_1("Komplikacije ponovno prišivene noge (ili dijela)", "T87.1"),
    T87_2("Komplikacije ostalih ponovno prišivenih dijelova tijela", "T87.2"),
    T87_3("Neurom amputacijskog bataljka", "T87.3"),
    T87_4("Infekcija amputacijskog bataljka", "T87.4"),
    T87_5("Nekroza amputacijskog bataljka", "T87.5"),
    T87_6("Ostale i nespecificirane komplikacije amputacijskog bataljka", "T87.6"),
    T88("Ostale komplikacije kirurške i medicinske skrbi, nesvrstane drugamo", "T88"),
    T88_0("Infekcija nakon imunizacije", "T88.0"),
    T88_1("Ostale komplikacije nakon imunizacije, nesvrstane drugamo", "T88.1"),
    T88_2("Šok uzrokovan anestezijom (anestezijski šok)", "T88.2"),
    T88_3("Anestezijska maligna hipertermija", "T88.3"),
    T88_4("Neuspjela ili teška intubacija", "T88.4"),
    T88_5("Ostale komplikacije anestezije", "T88.5"),
    T88_6("Anafilaktični šok zbog štetnoga djelovanja ispravno primijenjenoga, pravilno propisanoga lijeka", "T88.6"),
    T88_7("Nespecificiran štetan učinak ljekovite tvari ili lijeka", "T88.7"),
    T88_8("Ostale specificirane komplikacije kirurške i medicinske skrbi, nesvrstane drugamo", "T88.8"),
    T88_9("Komplikacija kirurške i medicinske skrbi, nespecificirana", "T88.9"),
    T90("Posljedice ozljede glave", "T90"),
    T90_0("Posljedice površinske ozljede glave", "T90.0"),
    T90_1("Posljedice otvorene rane glave", "T90.1"),
    T90_2("Posljedice prijeloma lubanje i kostiju glave", "T90.2"),
    T90_3("Posljedice ozljede kranijalnih živaca", "T90.3"),
    T90_4("Posljedice ozljede oka i orbite", "T90.4"),
    T90_5("Posljedice intrakranijalne ozljede", "T90.5"),
    T90_8("Posljedice ostalih specificiranih ozljeda glave", "T90.8"),
    T90_9("Posljedice nespecificirane ozljede glave", "T90.9"),
    T91("Posljedice ozljeda vrata i trupa", "T91"),
    T91_0("Posljedice površinske ozljede i otvorene rane vrata i trupa", "T91.0"),
    T91_1("Posljedice prijeloma kralježnice", "T91.1"),
    T91_2("Posljedice ostalih prijeloma prsnoga koša i zdjelice", "T91.2"),
    T91_3("Posljedice ozljede kralježnične moždine", "T91.3"),
    T91_4("Posljedice ozljede intratorakalnih organa", "T91.4"),
    T91_5("Posljedice ozljede intraabdominalnih i zdjeličnih organa", "T91.5"),
    T91_8("Posljedice ostalih specificiranih ozljeda vrata i trupa", "T91.8"),
    T91_9("Posljedice nespecificirane ozljede vrata i trupa", "T91.9"),
    T92("Posljedice ozljeda ruke", "T92"),
    T92_0("Posljedice otvorene rane ruke", "T92.0"),
    T92_1("Posljedice prijeloma ruke", "T92.1"),
    T92_2("Posljedice prijeloma zapešća i šake", "T92.2"),
    T92_3("Posljedice dislokacije, iščašenja i uganuća ruke", "T92.3"),
    T92_4("Posljedice ozljede živca ruke", "T92.4"),
    T92_5("Posljedice ozljede mišića i tetive ruke", "T92.5"),
    T92_6("Posljedice nagnječenja i traumatske amputacije ruke", "T92.6"),
    T92_8("Posljedice ostalih specificiranih ozljeda ruke", "T92.8"),
    T92_9("Posljedice nespecificirane ozljede ruke", "T92.9"),
    T93("Posljedice ozljeda noge", "T93"),
    T93_0("Posljedice otvorene rane noge", "T93.0"),
    T93_1("Posljedice prijeloma femura", "T93.1"),
    T93_2("Posljedice ostalih prijeloma noge", "T93.2"),
    T93_3("Posljedice dislokacije, iščašenja i uganuća noge", "T93.3"),
    T93_4("Posljedice ozljede živca noge", "T93.4"),
    T93_5("Posljedice ozljede mišića i tetiva noge", "T93.5"),
    T93_6("Posljedice nagnječenja i traumatske amputacije noge", "T93.6"),
    T93_8("Posljedice ostalih specificiranih ozljeda noge", "T93.8"),
    T93_9("Posljedice nespecificirane ozljede noge", "T93.9"),
    T94("Posljedice multiplih ozljeda i ozljeda nespecificiranog dijela tijela", "T94"),
    T94_0("Posljedice višestrukih ozljeda tijela", "T94.0"),
    T94_1("Posljedice ozljeda nespecificirana dijela tijela", "T94.1"),
    T95("Posljedice opeklina, korozija i smrzotina", "T95"),
    T95_0("Posljedice opekline, korozije i smrzotine glave i vrata", "T95.0"),
    T95_1("Posljedice opekline, korozije i smrzotine trupa", "T95.1"),
    T95_2("Posljedice opekline, korozije i smrzotine ruke", "T95.2"),
    T95_3("Posljedice opekline, korozije i smrzotine noge", "T95.3"),
    T95_4("Posljedice opekline i korozije koje se mogu svrstati samo u odnosu na zahvaćenu površinu tijela", "T95.4"),
    T95_8("Posljedice ostale specificirane opekline, korozije i smrzotine", "T95.8"),
    T95_9("Posljedice nespecificirane opekline, korozije i smrzotine", "T95.9"),
    T96("Posljedice otrovanja lijekovima, ljekovitim i biološkim tvarima", "T96"),
    T96_0("Posljedice otrovanja lijekovima ljekovitim i biološkim tvarima", "T96.0"),
    T97("Posljedice toksičnih učinaka tvari pretežno nemedicinskog podrijetla", "T97"),
    T97_0("Posljedice toksičnih učinaka tvri pretežno nemedicinskog podrijetla", "T97.0"),
    T98("Posljedice ostalih i nespecificiranih djelovanja vanjskih uzroka", "T98"),
    T98_0("Posljedice učinaka stranog tijela koje je prodrlo kroz prirodni otvor", "T98.0"),
    T98_1("Posljedice ostalih i nespecificiranih djelovanja vanjskih uzroka", "T98.1"),
    T98_2("Posljedice nekih ranih komplikacija trauma", "T98.2"),
    T98_3("Posljedice komplikacija kirurške i medicinske skrbi, nesvrstane drugamo", "T98.3");
    
    private final String displayName;
    private final String code;
    
    MkbCodesT(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
