package hr.dbasic.anephysiobe.models.patients.mkbcodes;

import lombok.Getter;

@Getter
public enum MkbCodesB {
    
    B00("Herpesvirusne infekcije (herpes simpleks)", "B00"),
    B00_0("Eczema herpeticum", "B00.0"),
    B00_1("Herpesvirusni vezikulozni dermatitis", "B00.1"),
    B00_2("Herpesvirusni gingivostomatitis i faringotonsilitis", "B00.2"),
    B00_3("Herpesvirusni meningitis (G02.0*)", "B00.3"),
    B00_4("Herpesvirusni encefalitis (G05.1*)", "B00.4"),
    B00_5("Herpesvirusne bolesti oka", "B00.5"),
    B00_7("Diseminirana herpesvirusna bolest", "B00.7"),
    B00_8("Ostali oblici herpesvirusne infekcije", "B00.8"),
    B00_9("Herpesvirusna infekcija, nespecificirana", "B00.9"),
    B01("Vodene kozice (varicella)", "B01"),
    B01_0("Vodene kozice komplicirane meningitisom (G02.0*)", "B01.0"),
    B01_1("Vodene kozice komplicirane encefalitisom (G05.1*)", "B01.1"),
    B01_2("Vodene kozice komplicirane pneumonijom (J17.1*)", "B01.2"),
    B01_8("Varicela s drugim komplikacijama", "B01.8"),
    B01_9("Varicela bez naznačenih komplikacija", "B01.9"),
    B02("Zoster (herpes zoster)", "B02"),
    B02_0("Zoster - encefalitis (G05.1*)", "B02.0"),
    B02_1("Zoster - meningitis (G02.0*)", "B02.1"),
    B02_2("Zoster drugih dijelova živčanog sustava", "B02.2"),
    B02_3("Oftalmički zoster", "B02.3"),
    B02_7("Diseminirani zoster", "B02.7"),
    B02_9("Zoster bez naznačenih komplikacija", "B02.9"),
    B03("Velike boginje", "B03"),
    B03_0("Velike boginje", "B03.0"),
    B04("Majmunske boginje", "B04"),
    B04_0("Majmunske boginje", "B04.0"),
    B05("Ospice (morbilli)", "B05"),
    B05_0("Morbili komplicirani encefalitisom (G05.1*)", "B05.0"),
    B05_1("Morbili komplicirani meningitisom (G02.0*)", "B05.1"),
    B05_2("Morbili komplicirani pneumonijom (J17.1*)", "B05.2"),
    B05_3("Morbili komplicirani upalom srednjeg uha (H67.1*)", "B05.3"),
    B05_4("Morbili praćeni crijevnim komplikacijama", "B05.4"),
    B05_8("Morbili praćenidrugim komplikacijama", "B05.8"),
    B05_9("Morbili bez naznačenih komplikacija", "B05.9"),
    B06("Rubeola (rubella)", "B06"),
    B06_0("Rubeola s neurološkim komplikacijama", "B06.0"),
    B06_8("Rubeola s drugim komplikacijama", "B06.8"),
    B06_9("Rubeola bez naznačenih komplikacija", "B06.9"),
    B07("Virusne bradavice", "B07"),
    B07_0("Virusne bradavice", "B07.0"),
    B08("Druge virusne infekcije karakterizirane promjenama na koži i sluznicama, nesvrstane drugamo", "B08"),
    B08_0("Druge infekcije uzrokovane ortopoxvirusom", "B08.0"),
    B08_1("Molluscum contagiosum", "B08.1"),
    B08_2("Exanthema subitum (šesta bolest)", "B08.2"),
    B08_3("Erythema infectiosum (peta bolest)", "B08.3"),
    B08_4("Enterovirusni vezikulozni stomatitis s osipom", "B08.4"),
    B08_5("Enterovirusni vezikulozni faringitis", "B08.5"),
    B08_8("Ostale specificirane virusne infekcije karakterizirane lezijama kože i sluznica", "B08.8"),
    B09("Nespecificirane virusne infekcije karakterizirane lezijama kože i sluznica", "B09"),
    B09_0("Nespecificirane virusne infekcije karakterizirane lezijama kože i sluznica", "B09.0"),
    B15("Akutni hepatitis A", "B15"),
    B15_0("Hepatitis A s hepatalnom komom", "B15.0"),
    B15_9("Hepatitis A bez hepatalne kome", "B15.9"),
    B16("Akutni hepatitis B", "B16"),
    B16_0("Akutni hepatitis B s delta-antigenom (koinfekcija) s hepatalnom komom", "B16.0"),
    B16_1("Akutni hepatitis B s delta-antigenom (koinfekcija) bez hepatalne kome", "B16.1"),
    B16_2("Akutni hepatitis B bez delta-antigena s hepatalnom komom", "B16.2"),
    B16_9("Akutni hepatitis B bez delta-antigena i bez hepatalne kome", "B16.9"),
    B17("Drugi akutni virusni hepatitisi", "B17"),
    B17_0("Akutna delta (super)infekcija nosioca hepatitisa B", "B17.0"),
    B17_1("Akutni hepatitis C", "B17.1"),
    B17_2("Akutni hepatitis E", "B17.2"),
    B17_8("Ostali specificirani akutni virusni hepatitisi", "B17.8"),
    B18("Kronični virusni hepatitis", "B18"),
    B18_0("Kronični virusni hepatitis B s delta-antigenom", "B18.0"),
    B18_1("Kronični virusni hepatitis B bez delta-antigena", "B18.1"),
    B18_2("Kronični virusni hepatitis C", "B18.2"),
    B18_8("Drugi kronični virusni hepatitis", "B18.8"),
    B18_9("Kronični virusni hepatitis, nespecificirani", "B18.9"),
    B19("Nespecificirani virusni hepatitis", "B19"),
    B19_0("Nespecificirani virusni hepatitis s komom", "B19.0"),
    B19_9("Nespecificirani virusni hepatitis bez kome", "B19.9"),
    B20("Bolest uzrokovan humanim imunodeficijencijskim virusom (HIV) s posljedičnom infekcijskom i parazitarnom bolešću", "B20"),
    B20_0("HIV-bolest s posljedičnom infekcijom mikobakterijama", "B20.0"),
    B20_1("HIV-bolest s posljedičnom infekcijom drugim bakterijama", "B20.1"),
    B20_2("HIV-bolest s posljedičnom citomegalovirusnom bolešću", "B20.2"),
    B20_3("HIV-bolest s posljedičnom infekcijom drugim virusima", "B20.3"),
    B20_4("HIV-bolest s posljedičnom kandidijazom", "B20.4"),
    B20_5("HIV-bolest s posljedičnom drugom mikozom", "B20.5"),
    B20_6("HIV-bolest s posljedičnom pneumonijom koju uzrokuje Pneumocystis carini", "B20.6"),
    B20_7("HIV-bolest s posljedičnim multiplim infekcijama", "B20.7"),
    B20_8("HIV-bolest s posljedičnim drugim infekcijskim i parazitarnim bolestima", "B20.8"),
    B20_9("HIV-bolest s posljedičnom nespecificiranom infekcijskom i parazitarnom bolešću", "B20.9"),
    B21("Bolest izazvana humanim imunodeficijencijskim virusom (HIV) s posljedičnim zloćudnim novotvorinama", "B21"),
    B21_0("HIV-bolest s posljedičnim Kaposijevim sarkomom", "B21.0"),
    B21_1("HIV-bolest s posljedičnim Burkittovim limfomom", "B21.1"),
    B21_2("HIV-bolest s posljedičnim drugim non Hodgkinovim limfomima", "B21.2"),
    B21_3("HIV-bolest s posljedičnim drugim zloćudnim novotvorinama limfoidnog, hematopoetskog i srodnog tkiva", "B21.3"),
    B21_7("HIV-bolest s posljedičnim multiplim zloćudnim novotvorinama", "B21.7"),
    B21_8("HIV-bolest s posljedičnim drugim zloćudnim novotvorinama", "B21.8"),
    B21_9("HIV-bolest s posljedičnim nespecificiranim zloćudnim novotvorinama", "B21.9"),
    B22("Bolest izazvana humanim imunodeficijencijskim virusom (HIV) s posljedičnim drugim specificiranim bolestima", "B22"),
    B22_0("HIV-bolest s posljedičnom encefalopatijom", "B22.0"),
    B22_1("HIV-bolest s posljedičnim intersticijalnim limfoidnim pneumonitisom", "B22.1"),
    B22_2("HIV-bolest s posljedičnim sindromom propadanja", "B22.2"),
    B22_7("HIV-bolest s posljedičnim multiplim bolestima svrstanim drugamo", "B22.7"),
    B23("Bolest uzrokovana humanim imunodeficijencijskim virusom (HIV) s rezultirajućim drugim stanjima", "B23"),
    B23_0("Sindrom akutne HIV infekcije", "B23.0"),
    B23_1("HIV-bolest s rezultirajućom (perzistirajućom) generaliziranom limfadenopatijom", "B23.1"),
    B23_2("HIV-bolest s posljedičnim hematološkim i imunološkim poremećajima nesvrstanim drugamo", "B23.2"),
    B23_8("HIV-bolest s posljedičnim drugim specificiranim stanjima", "B23.8"),
    B24("Nespecificirana bolest uzrokovana humanim imunodeficijencijskim virusom (HIV)", "B24"),
    B24_0("Nespecificirana bolest uzrokovana humanim imunodeficijencijskim virusom (HIV)", "B24.0"),
    B25("Bolest uzrokovana citomegalovirusom", "B25"),
    B25_0("Citomegalovirusni pneumonitis (J17.1*)", "B25.0"),
    B25_1("Citomegalovirusni hepatitis (K77.0*)", "B25.1"),
    B25_2("Citomegalovirusni pankreatitis (K87.1*)", "B25.2"),
    B25_8("Druge citomegalovirusne bolesti", "B25.8"),
    B25_9("Citomegalovirusna bolest, nespecificirana", "B25.9"),
    B26("Zaušnjaci (parotitis)", "B26"),
    B26_0("Parotitis orhitis (N51.1*)", "B26.0"),
    B26_1("Parotitis meningitis (G02.0*)", "B26.1"),
    B26_2("Parotitis encefalitis (G05.1*)", "B26.2"),
    B26_3("Parotitis pankreatitis (K87.1*)", "B26.3"),
    B26_8("Parotitis s drugim komplikacijama", "B26.8"),
    B26_9("Parotitis bez komplikacija", "B26.9"),
    B27("Infekciozna mononukleoza", "B27"),
    B27_0("Gamaherpesvirusna mononukleoza", "B27.0"),
    B27_1("Citomegalovirusna mononukleoza", "B27.1"),
    B27_8("Druga infekciozna mononukleoza", "B27.8"),
    B27_9("Infekciozna mononukleoza, nespecificirana", "B27.9"),
    B30_0("Keratokonjunktivitis uzrokovan adenovirusima (H19.2*)", "B30.0"),
    B30_1("Konjunktivitis uzrokovan adenovirusima (H13.1*)", "B30.1"),
    B30_2("Virusni faringokonjunktivitis", "B30.2"),
    B30_3("Akutni epidemijski hemoragijski konjunktivitis", "B30.3"),
    B30_8("Ostali virusni konjunktivitisi (H13.1*)", "B30.8"),
    B30_9("Virusni konjunktivitis, nespecificiran", "B30.9"),
    B33("Ostale virusne bolesti, nesvrstane drugamo", "B33"),
    B33_0("Epidemijska mijalgija", "B33.0"),
    B33_1("Bolest rijeke Ross (Ross River)", "B33.1"),
    B33_2("Virusni karditis", "B33.2"),
    B33_3("Retrovirusna infekcija, nesvrstana drugamo", "B33.3"),
    B33_8("Druge specificirane virusne bolesti", "B33.8"),
    B34("Virusne infekcije nespecificirane lokalizacije", "B34"),
    B34_0("Adenovirusna infekcija, nespecificirana", "B34.0"),
    B34_1("Enterovirusna infekcija, nespecificirana", "B34.1"),
    B34_2("Koronavirusna infekcija, nespecificirana", "B34.2"),
    B34_3("Parvovirusna infekcija, nespecificirana", "B34.3"),
    B34_4("Papovavirusna infekcija, nespecificirana", "B34.4"),
    B34_8("Ostale virusne infekcije nespecificirane lokalizacije", "B34.8"),
    B34_9("Virusna infekcija, nespecificirana", "B34.9"),
    B35("Dermatofitija", "B35"),
    B35_0("Tinea brade i tinea vlasišta", "B35.0"),
    B35_1("Tinea nokta", "B35.1"),
    B35_2("Tinea šake", "B35.2"),
    B35_3("Tinea stopala", "B35.3"),
    B35_4("Tinea tijela", "B35.4"),
    B35_5("Tinea imbricata", "B35.5"),
    B35_6("Tinea cruris", "B35.6"),
    B35_8("Druge dermatofitija", "B35.8"),
    B35_9("Dermatofitija, nespecificirana", "B35.9"),
    B36("Ostale površinske mikoze", "B36"),
    B36_0("Pityriasis versicolor", "B36.0"),
    B36_1("Tinea nigra", "B36.1"),
    B36_2("Bijela piedra", "B36.2"),
    B36_3("Crna piedra", "B36.3"),
    B36_8("Ostale specificirane površne mikoze", "B36.8"),
    B36_9("Površna mikoza, nespecificirana", "B36.9"),
    B37("Kandidijaza", "B37"),
    B37_0("Kandidijaza ustiju", "B37.0"),
    B37_1("Plućna kandidijaza", "B37.1"),
    B37_2("Kandidijaza kože i nokta", "B37.2"),
    B37_3("Kandidijaza rodnice i stidnice (N77.1*)", "B37.3"),
    B37_4("Kandidijaza druge urogenitalne lokalizacije", "B37.4"),
    B37_5("Kandida meningitis (G02.1*)", "B37.5"),
    B37_6("Kandida endokarditis (I39.8*)", "B37.6"),
    B37_7("Sepsa uzrokovana kandidom", "B37.7"),
    B37_8("Kandidijaza drugih lokalizacija", "B37.8"),
    B37_9("Kandidijaza, nespecificirana", "B37.9"),
    B38("Kokcidioidomikoza", "B38"),
    B38_0("Akutna plućna kokcidioidomikoza", "B38.0"),
    B38_1("Kronična plućna kokcidioidomikoza", "B38.1"),
    B38_2("Plućna kokcidioidomikoza, nespecificirana", "B38.2"),
    B38_3("Kožna kokcidioidomikoza", "B38.3"),
    B38_4("Kokcidioidozni meningitis (G02.1*x)", "B38.4"),
    B38_7("Diseminirana kokcidioidomikoza", "B38.7"),
    B38_8("Ostali oblici kokcidioidomikoze", "B38.8"),
    B38_9("Kokcidioidomikoza, nespecificirana", "B38.9"),
    B39("Histoplazmoza", "B39"),
    B39_0("Akutna histoplazmoza pluća koju uzrokuje Histoplasma capsulati", "B39.0"),
    B39_1("Kronična histoplazmoza pluća koju uzrokuje Histoplasma capsulati", "B39.1"),
    B39_2("Histoplazmoza pluća koju uzrokuje Histoplasma capsulati", "B39.2"),
    B39_3("Diseminirana histoplazmoza koju uzrokuje Histoplasma capsulati", "B39.3"),
    B39_4("Histoplazmoza koju uzrokuje Histoplasma capsulati, nespecificirana", "B39.4"),
    B39_5("Histoplazmoza duboisii", "B39.5"),
    B39_9("Histoplazmoza, nespecificirana", "B39.9"),
    B40("Blastomikoza", "B40"),
    B40_0("Akutna plućna blastomikoza", "B40.0"),
    B40_1("Kronična plućna blastomikoza", "B40.1"),
    B40_2("Plućna blastomikoza, nespecificirana", "B40.2"),
    B40_3("Kožna blastomikoza", "B40.3"),
    B40_7("Diseminirana blastomikoza", "B40.7"),
    B40_8("Ostali oblici blastomikoze", "B40.8"),
    B40_9("Blastomikoza, nespecificirana", "B40.9"),
    B41("Parakokcidioidomikoza", "B41"),
    B41_0("Plućna parakokcidioidomikoza", "B41.0"),
    B41_7("Diseminirana parakokcidioidomikoza", "B41.7"),
    B41_8("Ostali oblici parakokcidioidomikoza", "B41.9"),
    B41_9("Parakokcidioidomikoza, nespecificirana", "B41.9"),
    B42("Sporotrihoza", "B42"),
    B42_0("Plućna sporotrihoza (J99.8*)", "B42.0"),
    B42_1("Limfokutana sporotrihoza", "B42.1"),
    B42_7("Diseminirana sporotrihoza", "B42.7"),
    B42_8("Ostali oblici sporotrihoze", "B42.8"),
    B42_9("Sporotrihoza, nespecificirana", "B42.9"),
    B43("Kromomikoza i feomikotski apsces", "B43"),
    B43_0("Kožna kromomikoza", "B43.0"),
    B43_1("Feomikotski moždani apsces", "B43.1"),
    B43_2("Subkutani feomikotski apsces i cista", "B43.2"),
    B43_8("Ostali oblici kromomikoze", "B43.8"),
    B43_9("Kromomikoza, nespecificirana", "B43.9"),
    B44("Aspergiloza", "B44"),
    B44_0("Invazivna plućna aspergiloza", "B44.0"),
    B44_1("Druge plućne aspergiloze", "B44.1"),
    B44_2("Aspergiloza tonzila", "B44.2"),
    B44_7("Diseminirana aspergiloza", "B44.7"),
    B44_8("Druge forme aspergiloze", "B44.8"),
    B44_9("Aspergiloza, nespecificirana", "B44.9"),
    B45("Kriptokokoza", "B45"),
    B45_0("Plućna kriptokokoza", "B45.0"),
    B45_1("Cerebralna kriptokokoza", "B45.1"),
    B45_2("Kožna kriptokokoza", "B45.2"),
    B45_3("Koštana kriptokokoza", "B45.3"),
    B45_7("Diseminirana kriptokokoza", "B45.7"),
    B45_8("Ostali oblici kriptokokoze", "B45.8"),
    B45_9("Kriptokokoza, nespecificirana", "B45.9"),
    B46("Zigomikoza", "B46"),
    B46_0("Plućna mukormikoza", "B46.0"),
    B46_1("Rinocerebralna mukormikoza", "B46.1"),
    B46_2("Gastrointestinalna mukormikoza", "B46.2"),
    B46_3("Kožna mukormikoza", "B46.3"),
    B46_4("Diseminirana mukormikoza", "B46.4"),
    B46_5("Mukormikoza, nespecificirana", "B46.5"),
    B46_8("Ostale zigomikoze", "B46.8"),
    B46_9("Zigomikoza, nespecificirana", "B46.9"),
    B47("Micetom", "B47"),
    B47_0("Eumicetom", "B47.0"),
    B47_1("Aktinomicetom", "B47.1"),
    B47_9("Micetom, nespecificiran", "B47.9"),
    B48("Ostale mikoze, nesvrstane drugamo", "B48"),
    B48_0("Lobomikoza", "B48.0"),
    B48_1("Rinosporidioza", "B48.1"),
    B48_2("Alešerijaza", "B48.2"),
    B48_3("Geotrihoza", "B48.3"),
    B48_4("Peniciloza", "B48.4"),
    B48_7("Oportunističke mikoze", "B48.7"),
    B48_8("Ostale specificirane mikoze", "B48.8"),
    B49("Nespecificirane mikoze", "B49"),
    B49_0("Nespecificirane mikoze", "B49.0"),
    B50("Malarija koju uzrokuje Plasmodium falciparum", "B50"),
    B50_0("Plasmodium falciparum malarija s cerebralnim komplikacijama", "B50.0"),
    B50_8("Ostale teške Plasmodium falciparum malarije s komplikacijama", "B50.8"),
    B50_9("Plasmodium falciparum malarija, nespecificirana", "B50.9"),
    B51("Malarija koju uzrokuje Plasmodium vivax", "B51"),
    B51_0("Plasmodium vivax malarija s rupturom slezene", "B51.0"),
    B51_8("Plasmodium vivax malarija s drugim komplikacijama", "B51.8"),
    B51_9("Plasmodium vivax malarija bez komplikacija", "B51.9"),
    B52("Malarija koju uzrokuje Plasmodium malariae", "B52"),
    B52_0("Plasmodium malariae malarija s nefropatijom", "B52.0"),
    B52_8("Plasmodium malariae malarija s drugim komplikacijama", "B52.8"),
    B52_9("Plasmodium malariae malarija bez komplikacija", "B52.9"),
    B53("Ostale parazitološki dokazane malarije", "B53"),
    B53_0("Malarija koju uzrokuje Plasmodium ovale", "B53.0"),
    B53_1("Malarija uzrokovana majmunskim plasmodijima", "B53.1"),
    B53_8("Ostale parazitološki potvr|ene malarije, nesvrstane drugamo", "B53.8"),
    B54("Malarija, nespecificirana", "B54"),
    B54_0("Malarija, nespecificirana", "B54.0"),
    B55("Lišmenijaza", "B55"),
    B55_0("Visceralna lišmenijaza", "B55.0"),
    B55_1("Kožna lišmenijaza", "B55.1"),
    B55_2("Mukokutana lišmenijaza", "B55.2"),
    B55_9("Lišmanijaza, nespecificirana", "B55.9"),
    B56("Afrička tripanosomijaza", "B56"),
    B56_0("Gambiense tripanosomijasa", "B56.0"),
    B56_1("Rhodesiense tripanosomijaza", "B56."),
    B56_9("Afrička tripanosomijaza, nespecificirana", "B56.9"),
    B57("Chagasova bolest", "B57"),
    B57_0("Akutna Chagasova bolest sa srčanim komplikacijama (I41.2*-98.1*)", "B57.0"),
    B57_1("Akutna Chagasova bolest bez srčanih komplikacija", "B57.1"),
    B57_2("Chagasova bolest (kronična) sa srčanim komplikacijama (I41.2*-98.1*)", "B57.2"),
    B57_3("Chagasova bolest (kronična) s komplikacijama probavnog sustava", "B57.3"),
    B57_4("Chagasova bolest (kronična) s komplikacijama živčanog sustava", "B57.4"),
    B57_5("Chagasova bolest (kronična) sa zahvaćanjem drugih organa", "B57.5"),
    B58("Toksoplazmoza", "B58"),
    B58_0("Toksoplazma oftamopatija", "B58.0"),
    B58_1("Toksoplazma hepatitis (K77.0*)", "B58.1"),
    B58_2("Toksoplazma meningoencefalitis (G05.2*)", "B58.2"),
    B58_3("Plućna toksoplazmoza (J17.3*)", "B58.3"),
    B58_8("Toksoplazmoza s afekcijom drugih organa", "B58.8"),
    B58_9("Toksoplazmoza, nespecificirana", "B58.9"),
    B59("Pneumocistoza", "B59"),
    B59_0("Pneumocistoza", "B59.0"),
    B60("Ostale bolesti uzrokovane protozoama nesvrtane drugamo", "B60"),
    B60_0("Babezioza", "B60.0"),
    B60_1("Akantamebijaza", "B60.1"),
    B60_2("Neglerijaza", "B60.2"),
    B60_8("Druge specificirane protozoarne bolesti", "B60.8"),
    B64("Nespecificirane protozoarne bolesti", "B64"),
    B64_0("Nespecificirane protozoarne bolesti", "B64.0"),
    B65("Shistosomijaza (bilharcioza)", "B65"),
    B65_0("Shistosomijaza koju uzrokuje Schistosoma haematobium (urinarna šistosomijaza)", "B65.0"),
    B65_1("Shistosomijaza koju uzrokuje Schistosoma mansoni (intestinalna šistosomijaza)", "B65.1"),
    B65_2("Shistosomijaza koju uzrokuje Schistosoma japonicum", "B65.2"),
    B65_3("Cerkarijski dermatitis", "B65.3"),
    B65_8("Ostale shistosomijaze", "B65.8"),
    B65_9("Shistosomijaza, nespecificirana", "B65.9"),
    B66("Druge metiljne infekcije", "B66"),
    B66_0("Opistorkijaza", "B66.0"),
    B66_1("Klonorkijaza", "B66.1"),
    B66_2("Dikrocelijaza", "B66.2"),
    B66_3("Fasciolijaza", "B66.3"),
    B66_4("Paragonimijaza", "B66.4"),
    B66_5("Fasciolopsijaza", "B66.5"),
    B66_8("Ostale specificirane metiljne infekcije", "B66.8"),
    B66_9("Metiljna infekcija, nespecificirana", "B66.9"),
    B67("Ehinokokoza", "B67"),
    B67_0("Ehinokokoza jetre koju uzrokuje Echinococcus granulosus", "B67.0"),
    B67_1("Ehinokokoza pluća koju uzrokuje Echinococcus granulosus", "B67.1"),
    B67_2("Ehinokokoza kosti koju uzrokuje Echinococcus granulosus", "B67.2"),
    B67_3("Ehinokokoza druge i multiple lokalizacije koju uzrokuje Echinococcus granulosus", "B67.3"),
    B67_4("Ehinokokoza koju uzrokuje Echinococcus granulosus, nespecificirana", "B67.4"),
    B67_5("Ehinokokoza jetre koju uzrokuje Echinococcus multilocularis", "B67.5"),
    B67_6("Ehinokokoza druge i multiple lokalizacije koju uzrokuje Echinococcus multilocularis", "B67.6"),
    B67_7("Ehinokokoza koju uzrokuje Echinococcus multilocularis, nespecificirana", "B67.7"),
    B67_8("Ehinokokoza jetre, nespecificirana", "B67.8"),
    B67_9("Ehinokokoza, ostala i nespecificirana", "B67.9"),
    B68("Tenijaza", ""),
    B68_0("Tenijaza koju uzrokuje Taenia solium", ""),
    B68_1("Tenijaza koju uzrokuje Taenia saginata", ""),
    B68_9("Tenijaza, nespecificirana", ""),
    B69("Cisticerkoza", "B69"),
    B69_0("Cisticerkoza središnjeg živčanog sustava", "B69.0"),
    B69_1("Cisticerkoza oka", "B69.1"),
    B69_8("Cisticerkoza drugih lokalizacija", "B69.8"),
    B69_9("Cisticerkoza, nespecificirana", "B69.9"),
    B70("Difilobotrijaza i sparganoza", "B70"),
    B70_0("Difilobotrijaza", "B70.0"),
    B70_1("Sparganoza", "B70.1"),
    B71("Ostale cestodne infekcije", "B71"),
    B71_0("Himenolepijaza", "B71.0"),
    B71_1("Dipilidijaza", "B71.1"),
    B71_8("Druge specificirane cestodne infekcije", "B71.8"),
    B71_9("Cestodna infekcija, nespecificirana", "B71.9"),
    B72("Drakunkuloza", "B72"),
    B72_0("Drakunkuloza", "B72.0"),
    B73("Onkocerkoza", "B73"),
    B73_0("Onkocerkoza", "B73.0"),
    B74("Filarijaza", "B74"),
    B74_0("Filarijaza koju uzrokuje Wuchereria bancrofti", "B74.0"),
    B74_1("Filarijaza koju uzrokuje Brugia malayi", "B74.1"),
    B74_2("Filarijaza koju uzrokuje Brugia timori", "B74.2"),
    B74_3("Loijaza", "B74.3"),
    B74_4("Mansonelijaza", "B74.4"),
    B74_8("Druge filarijaze", "B74.8"),
    B74_9("Filarijaza, nespecificirana", "B74.9"),
    B75("Trihineloza", "B75"),
    B75_0("Trihineloza", "B75.0"),
    B76("Bolesti uzrokovane krivoustim crvima", "B76"),
    B76_0("Ankilostomijaza", "B76.0"),
    B76_1("Nekatorijaza", "B76.1"),
    B76_8("Druge bolesti uzrokovane krivoustim crvima", "B76.8"),
    B76_9("Bolest uzrokovana krivoustim crvima, nespecificirana", "B76.9"),
    B77("Askarijaza", "B77"),
    B77_0("Askarijaza s crijevnim komplikacijama", "B77.0"),
    B77_8("Askarijaza s drugim komplikacijama", "B77.8"),
    B77_9("Askarijaza, nespecificirana", "B77.9"),
    B78("Strongiloidoza", "B78"),
    B78_0("Crijevna strongiloidoza", "B78.0"),
    B78_1("Kožna strongiloidoza", "B78.1"),
    B78_7("Diseminirana strongiloidoza", "B78.7"),
    B78_9("Strongiloidoza, nespecificirana", "B78.9"),
    B79("Trihurijaza", "B79"),
    B79_0("Trihurijaza", "B79.0"),
    B80("Enterobijaza", "B80"),
    B80_0("Enterobijaza", "B80.0"),
    B81("Ostale crijevne helmintijaze, nesvrstane drugamo", "B81"),
    B81_0("Anisakijaza", "B81.0"),
    B81_1("Crijevna kapilarijaza", "B81.1"),
    B81_2("Trihostrongilijaza", "B81.2"),
    B81_3("Crijevna angiostrongilijaza", "B81.3"),
    B81_4("Miješane crijevne helminitijaze", "B81.4"),
    B81_8("Druge specificirane crijevne helmintijaze", "B81.8"),
    B82("Nespecificirane crijevne parazitoze", "B82"),
    B82_0("Crijevna helmintijaza, nespecificirana", "B82.0"),
    B82_9("Crijevni parazitizam, nespecificiran", "B82.9"),
    B83("Ostale helmintijaze", "B83"),
    B83_0("Visceralna larva migrans", "B83.0"),
    B83_1("Gnatostomijaza", "B83.1"),
    B83_2("Angiostrongilijaza koju uzrokuje Parastrongylus cantonensis", "B83.2"),
    B83_3("Singamijaza", "B83.3"),
    B83_4("Unutrašnja hirudinijaza", "B83.4"),
    B83_8("Ostale specificirane helmintijaze", "B83.8"),
    B83_9("Helmintijaza, nespecificirana", "B83.9"),
    B85("Ušljivost (pedikuloza)", "B85"),
    B85_0("Ušljivost koju uzrokuje Pediculus humanus capitis", "B85.0"),
    B85_1("Ušljivost koju uzrokuje Pediculus humanus", "B85.1"),
    B85_2("Ušljivost (pedikuloza) nespecificirana", "B85.2"),
    B85_3("Ftirijaza (ušljivost spolovila)", "B85.3"),
    B85_4("Miješana ušljivost (pedikuloza i ftirijaza)", "B85.4"),
    B86("Svrab (scabies)", "B86"),
    B86_0("Svrab (scabies)", "B86.0"),
    B87("Mijaza", "B87"),
    B87_0("Kožna mijaza", "B87.0"),
    B87_1("Mijaza rane", "B87.1"),
    B87_2("Očna mijaza", "B87.2"),
    B87_3("Nazofaringealna mijaza", "B87.3"),
    B87_4("Mijaza uha", "B87.4"),
    B87_8("Mijaza druge lokalizacije", "B87.8"),
    B87_9("Mijaza, nespecificirana", "B87.9"),
    B88("Ostale infestacije", "B88"),
    B88_0("Ostale akarijaze", "B88.0"),
    B88_1("Tungijaza (infestacija pješčanom buhom)", "B88.1"),
    B88_2("Ostale infestacije člankonošcima (artropoda)", "B88.2"),
    B88_3("Vanjska hirudinijaza", "B88.3"),
    B88_8("Ostale specificirane infestacije", "B88.8"),
    B88_9("Infestacija, nespecificirana", "B88.9"),
    B89("Nespecificirane parazitoze", "B89"),
    B89_0("Nespecificirane parazitoze", "B89.0"),
    B90("Posljedice tuberkuloze", "B90"),
    B90_0("Posljedice tuberkuloze središnjega živčanog sustava", "B90.0"),
    B90_1("Posljedice genitourinarne tuberkuloze", "B90.1"),
    B90_2("Posljedice tuberkuloze kostiju i zglobova", "B90.2"),
    B90_8("Posljedice tuberkuloze drugih organa", "B90.8"),
    B90_9("Posljedice respiratorne i nespecificirane tuberkuloze", "B90.9"),
    B91("Posljedice poliomijelitisa", "B91"),
    B91_0("Posljedice poliomijelitisa", "B91.0"),
    B92("Posljedice lepre (gube)", "B92"),
    B92_0("Posljedice lepre (gube)", "B92.0"),
    B94("Posljedice drugih nespecificiranih zaraznih i parazitarnih bolesti", "B94"),
    B94_0("Posljedice trahoma", "B94.0"),
    B94_1("Posljedice virusnog encefalitisa", "B94.1"),
    B94_2("Posljedice virusnog hepatitisa", "B94.2"),
    B94_8("Posljedice ostalih specificiranih zaraznih i parazitarnih bolesti", "B94.8"),
    B94_9("Posljedice nespecificiranih zaraznih i parazitarnih bolesti", "B94.9"),
    B95("Streptokok i stafilokok kao uzročnici bolesti koje su svrstane u druga poglavlja", "B95"),
    B95_0("Streptokok grupe A, kao uzročnik bolesti svrstanih u druga poglavlja", "B95.0"),
    B95_1("Streptokok grupe B, kao uzročnik bolesti svrstanih u druga poglavlja", "B95.1"),
    B95_2("Streptokok grupe D, kao uzročnik bolesti svrstanih u druga poglavlja", "B95.2"),
    B95_3("Streptococcus pneumoniae kao uzročnik bolesti svrstanih u druga poglavlja", "B95.3"),
    B95_4("Ostali streptokoki kao uzročnici bolesti svrstanih u druga poglavlja", "B95.4"),
    B95_5("Nespecificirani streptokok kao uzročnik bolesti svrstanih u druga poglavlja", "B95.5"),
    B95_6("Staphylococcus aureus kao uzročnik bolesti svrstanih u druga poglavlja", "B95.6"),
    B95_7("Ostali stafilokoki kao uzročnici bolesti svrstanih u druga poglavlja", "B95.7"),
    B95_8("Nespecificirani stafilokok kao uzročnik bolesti svrstanih u druga poglavlja", "B95.8"),
    B96("Drugi bakterijski uzročnici bolesti svrstanih u druga poglavlja", "B96"),
    B96_0("Mycoplasma pneumoniae (M. pneumoniae) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.0"),
    B96_1("Klebsiella pneumoniae (K. pneumoniae) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.1"),
    B96_2("Escherichia coli (E. coli) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.2"),
    B96_3("Haemophilus influenzae (H. influenzae) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.3"),
    B96_4("Proteus (mirabilis)(morganii) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.4"),
    B96_5("Pseudomonas (aeruginosa)(mallei)(pseudomallei) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.5"),
    B96_6("Bacillus fragilis (B. fragilis) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.6"),
    B96_7("Clostridium perfringens (C.perfringens) kao uzročnik bolesti svrstanih u druga poglavlja", "B96.7"),
    B96_8("Ostale specificirane bakterije kao uzročnici bolesti svrstanih u druga poglavlja", "B96.8"),
    B97("Virusi kao uzročnici bolesti svrstanih u druga poglavlja", "B97"),
    B97_0("Adenovirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.0"),
    B97_1("Enterovirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.1"),
    B97_2("Koronavirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.2"),
    B97_3("Retrovirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.3"),
    B97_4("Respiratorno-sincicijski virus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.4"),
    B97_5("Reovirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.5"),
    B97_6("Parvovirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.6"),
    B97_7("Papilomavirus kao uzročnik bolesti svrstanih u druga poglavlja", "B97.7"),
    B97_8("Ostali virusi kao uzročnici bolesti svrstanih u druga poglavlja", "B97.8"),
    B99_0("Ostale i nespecificirane zarazne bolesti", "B99.0");
    
    private final String displayName;
    private final String code;
    
    MkbCodesB(String displayName, String code) {
        this.displayName = displayName;
        this.code = code;
    }
    
    @Override
    public String toString() {
        return code + " " + displayName;
    }
}
