package hr.dbasic.anephysiobe.services;

import hr.dbasic.anephysiobe.dto.responses.physioFileResponse.PhysioFileResponseDto;
import hr.dbasic.anephysiobe.dto.responses.physioFileResponse.functionalDiagnosisResponse.CreateFunctionalDiagnosisRequestDto;
import hr.dbasic.anephysiobe.dto.responses.physioFileResponse.functionalDiagnosisResponse.DeleteFunctionalDiagnosisRequestDto;
import hr.dbasic.anephysiobe.dto.responses.physioFileResponse.functionalDiagnosisResponse.FunctionalDiagnosisResponseDto;
import hr.dbasic.anephysiobe.dto.responses.physioFileResponse.functionalDiagnosisResponse.UpdateFunctionalDiagnosisRequestDto;

import java.util.List;

public interface FunctionalDiagnosisService {
    List<FunctionalDiagnosisResponseDto> findAllFunctionalDiagnoses();
    PhysioFileResponseDto createFunctionalDiagnosis(CreateFunctionalDiagnosisRequestDto createFunctionalDiagnosisRequestDto);
    PhysioFileResponseDto updateFunctionalDiagnosisById(String id, UpdateFunctionalDiagnosisRequestDto updateFunctionalDiagnosisRequestDto);
    void deleteFunctionalDiagnosisById(DeleteFunctionalDiagnosisRequestDto deleteFunctionalDiagnosisRequestDto);
}
